### ISSUE TITLE
Expanding "spec" testing is limited

### ISSUE THREAD

**Issue by butterfieldcons** [mgechev/angular2-seed#100]
As a reference I included text from original issue below since i cannot re-open the original.

I'm still trying to get my head around this one.  The previous anguar2-seed project that used alpha36 (tsc 1.5.3) can use the ~1.6.0 Typescript compiler just fine.  If I use the tsc 1.5.3 against the new angular2-seed project alpha37 I still get the same problems as described below.  I can stub out definitions in the ng2_test.d.ts; there just seems to be some pathing issue I cannot figure out.

Looked at this for a while, I'm hoping its just something simple that I'm missing. With a basic git clone of the current project how come I cannot......

import {Pipeline} from 'angular2/src/router/pipeline';

into, let's say, about_spec.ts?

app\components\about\about_spec.ts(19,24): error TS2307: Cannot find module 'angular2/src/router/pipeline'.

Scratching my head a little bit since I had this working with a previous version (.36) (again base clone will produce error message)

Thanks All!!

@butterfieldcons This is just a TypeScript compiler issue. Adding the following declaration to app/typings/ng2_test.d.ts should fix it.

declare module "angular2/src/router/pipeline" {
  export = ng;
}

or simply
import {Pipeline} from 'angular2/router';

**Comment by ludohenin** [comment]
What is the problem using alpha.37 and ts 1.6.x ?

**Comment by butterfieldcons** [comment]
previously I asked why cant I do this,

 With a basic git clone of the current project how come I cannot......

import {Pipeline} from 'angular2/src/router/pipeline';

With alpha.37 and 1.6.x a suggestion was made to 

declare module "angular2/src/router/pipeline" {
export = ng;
}

or simply
import {Pipeline} from 'angular2/router';

However, the transpiler version 1.5.3 does not work with the current angular2-seed project which uses alpha.37 and the new transpiler 1.6.x works with the previous version of angular2-seed which used alpha.36.

**Comment by ludohenin** [comment]
> Shouldnt the old 1.5.3 work?

Maybe it should, but then it is an issue with the TypeScript compiler, not this seed (which is working as provided).

**Comment by butterfieldcons** [comment]
People looking and asking questions is a good thing,  The fact that the new transpiler 1.6.x works with the previous angular2-seed project (maybe a week ago or so) suggests something changed in the project.  Which is working as provided is fine with me, I thought others might have the same question.

**Comment by butterfieldcons** [comment]
Agreed thanks for hanging in there!  TypeScript compiler issue.  I dropped back to the old working version and slowly upgraded to see where things were failing.
