### ISSUE TITLE
Integrate it with ASP.NET MVC Project

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#1006]
Hi Guys,

I am using the angular2-seed project. 

When running with npm-start, it works perfectly.

Now I want it to start from an ASP.NET MVC project. I tried to copy and paste the index.html, where there are the paths, etc.. in my homepage.cshtml and change the paths accordingly, but it is still loading....

The error which I am having right now is:  http://localhost:12646/angular2-seed/dist/dev/app/+home/index.js 404 (Not Found)

Can anyone guide me on this in order to get it started and working with ASP.net MVC project (Umbraco project)?

Thanks in advance.

Kind Regards

**Comment by mgechev** [comment]
I'd suggest to run the ASP.NET MVC service on different port and enable CORS.

This way you will have the seed dev server running on port 5555, making requests to your RESTful (for instance) service. I use setup similar to this one in production where we provide the prod build from a CDN, and it works perfectly.
