### ISSUE TITLE
Error loading materialize css

### ISSUE THREAD

**Issue by germnix** [mgechev/angular2-seed#1008]
I'm trying to build a minimal application using angular2-seed and Materialize CSS framework.

I installed the following dependencies:

```
npm install materialize-css --save
npm install angular2-materialize --save
```

Then I tried to open the app with

`npm start`

But I'm seeing the following error in the javascript console:

GET http://localhost:5555/node_modules/materialize/package.json 404 (Not Found)

Which seems logical because materialize folder is called "**materialize-css**". I tried updating seed.config.ts but I haven't been able to make it work. 

Is the normal way to add dependencies to the project to just add them to package.json?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
