### ISSUE TITLE
Stagin environment

### ISSUE THREAD

**Issue by JanickRoss** [mgechev/angular2-seed#1009]
How it's the simplest way to add staging environment to have different constante specific on each environment as an API end point url ?

Thanks

**Comment by mgechev** [comment]
You can add a `deploy` task (or whatever you name it) and add a task specific configuration in `project.config.ts`.

You can even load the different configurations from JSON files which are located wherever you prefer.

For further information on how to use task-specific config take a look [here](https://github.com/mgechev/angular2-seed/blob/227135ccf18a959ca26aa034cf21d4433569926a/tools/utils/seed/code_change_tools.ts#L10).
