### ISSUE TITLE
OnsenUI integration ?

### ISSUE THREAD

**Issue by gotenxds** [mgechev/angular2-seed#1012]
Hello, I'm opening this here because I believe this is an issue with the seed and not with the onsen ui library.

I'm trying to add OnsenUI to my project and after adding : 
`
import 'onsenui';
import {ONS_DIRECTIVES} from 'angular2-onsenui';
`

To my Main.ts file

and 

`
{src: 'angular2-onsenui/dist/src/angular2-onsenui.js', inject: 'libs'},
`

to my project.config file
I get the following errors: 

![image](https://cloud.githubusercontent.com/assets/3519520/16172937/c9ced114-359b-11e6-920a-a349c2dd0e9c.png)

Does any one know what I might be missing ?

**Comment by gotenxds** [comment]
NVM PBCK

**Comment by LockonF** [comment]
@gotenxds. Sorry to reopen the thread. Do you happen to remember what did you do to make it run?
