### ISSUE TITLE
Dev serve only works in Chrome.

### ISSUE THREAD

**Issue by wawyed** [mgechev/angular2-seed#1013]
When trying to launch the app in Firefox or IE on Windows 10, I get lots of 404 when trying to load the libraries files. It would appear to be related to trying to request a fail with extra slashes.

Some examples:

Firefox:
`http://localhost:5555//node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js` **404 Not found**

Yet is fine requesting:
`http://localhost:5555/node_modules/@angular/common/bundles/common.umd.js` **200 OK**

IE:
But IE returns 404 on that same file:
`http://localhost:5555//node_modules/@angular/common/bundles/common.umd.js` **404 Not found**

Chrome works fine.

**Comment by eimyss** [comment]
Interestengly enough, I got same issue even with clean copy of master. I think this issue was introduced not so long ago.

**Comment by AntonFLB** [comment]
Hi,
got the same error on Windows 7. Clean copy of master, after npm install and npm start automatically opens up IE 11. Nothing Shows up and i got following Error Message in DevToolbar:
`{
   [functions]: ,
   __proto__: { },
   description: "undefined",
   message: "",
   name: "Error",
   number: NaN,
   originalErr: { },
   stack: null
}`
Not very helpful ;) but i hope one of the contributors knows where it Comes from. 
Workaround for me at the moment: open in Chrome :)

Greetings
Anton

**Comment by lifaon74** [comment]
It seems IE 10 & 11 cant handle urls containing /\ or // . I solved temporarily this with:

```ts
this.NPM_BASE = 'node_modules/';
this.SYSTEM_CONFIG_DEV = {
      defaultJSExtensions: true,
      packageConfigPaths: [
        `${this.NPM_BASE}*/package.json`,
        `${this.NPM_BASE}**/package.json`,
        `${this.NPM_BASE}@angular/*/package.json`
      ],
      paths: {
        [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
        '@angular/core': `${this.NPM_BASE}@angular/core/bundles/core.umd.js`,
        '@angular/common': `${this.NPM_BASE}@angular/common/bundles/common.umd.js`,
        '@angular/compiler': `${this.NPM_BASE}@angular/compiler/bundles/compiler.umd.js`,
        '@angular/forms': `${this.NPM_BASE}@angular/forms/bundles/forms.umd.js`,
        '@angular/http': `${this.NPM_BASE}@angular/http/bundles/http.umd.js`,
        '@angular/router': `${this.NPM_BASE}@angular/router/index.js`,
        '@angular/platform-browser': `${this.NPM_BASE}@angular/platform-browser/bundles/platform-browser.umd.js`,
        '@angular/platform-browser-dynamic': `${this.NPM_BASE}@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js`,
        'rxjs/*': `${this.NPM_BASE}rxjs/*`,
        'app/*': `/app/*`,
        '*': `${this.NPM_BASE}*`
      },
      packages: {
        rxjs: { defaultExtension: false }
      }
    };
```

I removed the first /. Now it'w working on all browsers but it's not realy proper (APP_BASE not takenin account).

**Comment by ZuSe** [comment]
Since this commit I am not able to resolve my custom libraries anymore.

I get:
(index):150 Error: (SystemJS) Error: XHR error (404 Not Found) loading https://localhost:3333/node_modules/moment.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"
for nearly every library.

It works when I change the import statement to  xxx FROM {folder/filename} but that should be no solution.
E.g.
import {AuthHttp, AuthConfig, AUTH_PROVIDERS} from 'angular2-jwt';

to

import {AuthHttp, AuthConfig, AUTH_PROVIDERS} from 'angular2-jwt/angular2-jwt';

**Comment by kamikaze** [comment]
same here... are you testing your changes, guys?

**Comment by bozhidarc** [comment]
With the latest update I have problem with loading lodash, too. I'm receiving 404 because it tries to load loadash from node_modules/lodash.js instead of node_modules/lodash/loadash.js
And I notice that loadsh package.json is not found, which may be is the main reason for not loading the lodash.

**Comment by mgechev** [comment]
@ZuSe, @bozhidarc thanks for commenting! The issue should be now fixed by https://github.com/mgechev/angular2-seed/commit/145524edf6d5d43469a34c077daf26daf94af2ba.

**Comment by mgechev** [comment]
@ZuSe what is ponyfill?

**Comment by ZuSe** [comment]
```
@mgechev 
Nothing, that's a stupid systemjs error. There was another issue opened related to it before.

My project works if I do:

 /**
   * The configuration of SystemJS for the `dev` environment.
   * @type {any}
   */
  protected SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    // packageConfigPaths: [
    //   `/node_modules/*/package.json`,
    //   `/node_modules/**/package.json`,
    //   `/node_modules/@angular/*/package.json`
    // ],
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '@angular/common': `node_modules/@angular/common/bundles/common.umd.js`,
      '@angular/compiler': `node_modules/@angular/compiler/bundles/compiler.umd.js`,
      '@angular/core': `node_modules/@angular/core/bundles/core.umd.js`,
      '@angular/forms': `node_modules/@angular/forms/bundles/forms.umd.js`,
      '@angular/http': `node_modules/@angular/http/bundles/http.umd.js`,
      '@angular/platform-browser': `node_modules/@angular/platform-browser/bundles/platform-browser.umd.js`,
      '@angular/platform-browser-dynamic': `node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js`,
      '@angular/router': `node_modules/@angular/router/index.js`,
      'rxjs/*': `node_modules/rxjs/*`,
      // Workaround until SystemJS resolution is fixed
      'moment': 'node_modules/moment/moment',
      'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt',
      // End of Workaround
      'app/*': `/app/*`,
      '*': `node_modules/*`
    },
    packages: {
      rxjs: { defaultExtension: false }
    }
  };
```

But it breaks the whole sense of systemjs if I have to add ever library I use to paths.
It seems like SystemJS can't resolve them by using the packageConfigPaths settings.

**Comment by mgechev** [comment]
It can resolve them by using `packageConfigPaths`, it can resolve even Angular. We have set direct paths to the bundles in order to speed-up the reload time.

**Comment by ZuSe** [comment]
You tried with those two libs?
I mean you get a crazy error when trying to resolve them via packegeConfigPaths or not?

**Comment by mgechev** [comment]
Yeah, both work. You don't need any changes from the original configuration.

You can import the modules as follow:

```ts
import * as JWT from 'angular2-jwt';
import * as moment from 'moment';

console.log(JWT, moment);

```
