### ISSUE TITLE
Add External Dependency wiki

### ISSUE THREAD

**Issue by reach4thelasers** [mgechev/angular2-seed#1014]
So I've spent about 3 hours already on how to add extenal dependencies, following this wiki page:

https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

After defeating several issues I am now at 

```
angular2-jwt.ts:1Uncaught ReferenceError: require is not defined
zone.js?1466336288895:101 GET http://localhost:5556/node_modules/angular2-jwt.js 404 (Not Found)
(index):95 Error: Error: XHR error (404 Not Found) loading http://localhost:5556/node_modules/angular2-jwt.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"
zone.js?1466336288895:101 GET http://localhost:5556/node_modules/angular2-jwt.js 404 (Not Found)
```
﻿
Can anyone give me updated instructions for this?  I am new to Angular2 and to JSPM and the learning curve is steep and everything on the web is out of date for RC2 now.  JWT is being loaded into scripts now but require not defined???!

**Comment by danielcrisp** [comment]
I'm having the same problem with the https://github.com/marcj/angular2-localStorage module because it only includes `*.ts` files. Should SystemJS handle the transpiling to JS?

**Comment by danielcrisp** [comment]
I've made a bit of progress by setting the `transpiler` option to `'typescript'` in the SystemJS config:

    transpiler: 'typescript'

The `require is not defined` message has gone but I've got other problems now (although I think they're probably my fault)

**Comment by mgechev** [comment]
It is responsibility of the module maintainer to distribute transpiled files with the npm module.

**Comment by mgechev** [comment]
@reach4thelasers you haven't provided proper path mapping for `angular2-jwt`:

It should be something like:

```ts
System.config({
  //...
  path: {
    'angular2-jwt': '/node_modules/angular2-jwt/angular2-jwt.js'
  }
  //...
});
```
