### ISSUE TITLE
Foudation Zurb Template with angular2-seed - Unable to compile Typescript errors

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#1017]
Hi Guys,

I am using Foundation zurb template mainly for SASS compiling/watching to CSS. Now, I want to reference the CSS file that I'am using in this foundation-zurb template.

Now, I have copied my foundation-zurb template (having node_modules as well) to the root of the angular2-seed but when type npm start at the root for angular2-seed, error show up:

Unable to compile Typescripts.

Errors are all related to node_modules components

![image](https://cloud.githubusercontent.com/assets/19478530/16192463/c0736f40-36e9-11e6-8f1a-01fb43e1c440.png)

Any help please?

Thanks

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
