### ISSUE TITLE
Error with gulp build.prod --color

### ISSUE THREAD

**Issue by lmkerr** [mgechev/angular2-seed#1019]
Cloned the repository and everything works splendidly so far except when I try and build for prod.

In the command line, I run:
`npm run build.prod` 

and I am given an error at line 23 of build.bundles.app when trying to run the builder.  I thought the issue might have been something i did to my fork, but apparently it's in the master branch as well.  Any help is appreciated as it's currently blocking my release.

Thanks,
-Loren

**Comment by mgechev** [comment]
On what operating system you are having the issue?

**Comment by lmkerr** [comment]
Windows 7

**Comment by scaryroy** [comment]
Same issue here, on linux, wont start

**Comment by mgechev** [comment]
I can't reproduce the issue...would you share the entire error message?

**Comment by scaryroy** [comment]
I seem to have solved it after install gulp and/or typings globally (ill try narrow down the culprit):
npm install gulp --global
npm install typings --global
typings install

**Comment by mgechev** [comment]
@scaryroy thanks! Lets close the issue then.

**Comment by scaryroy** [comment]
@mgechev great seed project! Just wondering what made you want to create a project like this?

Also, back on topic, I didnt need to do this for your RC1 release, do you know whats changed for me to have to do this? I don't imagine i had to install and global dependencies for me to run this project?

**Comment by mgechev** [comment]
Nothing in the build has changed. Most likely issues related to the reinstallation `node_modules`/`typings`. Just guesses.

**Comment by scaryroy** [comment]
Hmm strange, because when i remove all my global dependencies, and brand new checkout of this repo (with no existing global dependencies installed), it will give me this error. this happened my linux and mac. This issue could potentially stump a few people?

**Comment by scaryroy** [comment]
Sorry, my mistake, I just didnt have enough permissions to run the postinstall script, that why i had to run "typings install" manually.

**Comment by mgechev** [comment]
No worries, hopefully we found the issue :-).

**Comment by lmkerr** [comment]
this worked! thanks @scaryroy ! worked at home on mac, but pulled the repo on my machine at the clients.  forgot to install my globals.  are these worth having the readme? 

Also general thanks for the project, you guys are doing great work.
