### ISSUE TITLE
Cant get lodash to load 

### ISSUE THREAD

**Issue by gotenxds** [mgechev/angular2-seed#1021]
Hello, I had no problem loading libraries into the seed in the past but for some reason I just cant get lodash to load.

steps I toke 

npm install lodash --save
typing install lodash --ambiant --save

added 
`'lodash': `${this.NPM_BASE}lodash/lodash.js`,`

importing like this:

`import _ from 'lodash';`
to config

Still getting this error on npm start :
`error TS2307: Cannot find module 'lodash'.`

Am I being stupid ?

**Comment by mgechev** [comment]
This is problem of lack of type definitions. Take a look at [this](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/) blog post.

**Comment by gotenxds** [comment]
@mgechev 
Ive read it now, I dont see how he did anything  I did not do, I already know about all of that and like I said I installed the ambient definitions, also, I do not have the "Duplicate identifier"  problem because I already excluded the 'main' definitions, my problem this error : `error TS2307: Cannot find module 'lodash'.`

**Comment by mgechev** [comment]
Well, your problem is not that you have duplicate ambient type definitions but that you are missing them for lodash.

**Comment by gotenxds** [comment]
@mgechev 
But I'm not did you read what I wrote ?
have a look 
![image](https://cloud.githubusercontent.com/assets/3519520/16270557/66abfa10-389f-11e6-91fb-35623e04457e.png)

Also my browser.d.ts has :
`/// <reference path="browser/ambient/lodash/index.d.ts" />`

Something else is wrong, please read the process I described and tell me I if skiped something because you keep telling me I did not do stuff I clearly stated I did do.

**Comment by mgechev** [comment]
I read your explanation, and yes, you're missing the type definitions for `lodash`.

You're using old version of typings. `browser.d.ts` is not used in the compilation process.

Take a look at the [migration process](https://github.com/typings/typings).

**Comment by mgechev** [comment]
Btw, for support requests I recommend the [usage gitter](https://gitter.im/mgechev/angular2-seed).
