### ISSUE TITLE
Routing does not update CSS style properties on 'Home'

### ISSUE THREAD

**Issue by avhetman** [mgechev/angular2-seed#1030]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

Nothing needs to be done other than starting the app. Click on 'About' to navigate to the About page.

**Current behavior**
The styling on the 'about' item changes to active as expected when it is clicked, but the 'router-link-active'  class remains on the 'home' item. 
**Expected/desired behavior**

The class 'router-link-active' should be removed from Home in the navbar when Home is not the active page.
**Other information**

**Comment by mgechev** [comment]
Not sure this issue is related to the seed. It seems like an upstream bug to me.

**Comment by mgechev** [comment]
Also, it seems you're using older version of the seed, not the one in master, right?

**Comment by avhetman** [comment]
You're right Minko, I was using an older version. I just pulled latest and this is no longer an issue. What a great seed project! Thank you for all the work, I'd love to contribute to this sometime however I can.
