### ISSUE TITLE
add web-animations.min.js?

### ISSUE THREAD

**Issue by Shyam-Chen** [mgechev/angular2-seed#1031]
https://github.com/web-animations/web-animations-js

**Comment by mgechev** [comment]
It makes sense given the new animation API. Lets keep the issue open and gather other opinions.

**Comment by TheDonDope** [comment]
Hm, i guess it kind of makes sense, but IMHO it would be enough to either add the information in the README linking to the documentation (https://angular.io/docs/ts/latest/guide/animations.html) and / or update the wiki, maybe including it in the wiki article (https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency) as another example.

Just my 2 cents

Cheers 

Dope

**Comment by troyanskiy** [comment]
I would say that better add information about that and not include by default.

**Comment by Perezmarc** [comment]
I tried to import the web-animations-js as a external dependency following the tutorial but its not working... 

`this.SYSTEM_CONFIG_DEV.paths['web-animations-js'] =
      `${this.APP_BASE}node_modules/web-animations-js`;

    this.SYSTEM_BUILDER_CONFIG.packages['web-animations-js'] = {
      main: 'web-animations.js',
      defaultExtension : 'js'
    };`

also tried adding this to main.ts and app.component, though I think it doesn't need it:
`import * as webAnimations from 'web-animations-js';`
this line throws me an error that is not found, but I see it in node_modules.

for now I am importing it through cdn in index.html
`  <script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js"></script>`

**Comment by troyanskiy** [comment]
@Perezmarc 
You should add it to NPM_DEPENDENCIES in Project.config.ts constructor
```ts
 this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      //{src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'web-animations-js/web-animations.min.js', inject: 'shims'}
      // {src: 'q/q.js', inject: 'libs'},
      // {src: 'lodash/lodash.js', inject: 'libs'}
    ];
```

**Comment by gforceg** [comment]
What if you want to use a CDN? Say you are developing several intranet applications that will all use the same CDN?
