### ISSUE TITLE
I did a pull, and then a npm install, did not change anyhting else, get error

### ISSUE THREAD

**Issue by mthor** [mgechev/angular2-seed#1033]
do a fresh pull and npm install, seems to error out on the gulpfile.ts 

Using gulpfile ~/WebstormProjects/test/gulpfile.ts
[09:23:55] Starting 'webdriver'...
[09:23:56] 'webdriver' errored after 1.1 ms
[09:23:56] TypeError: task is not a function

**Comment by mgechev** [comment]
Where are you running these commands (what terminal emulator, operating system, node environment, etc.)? Did you run any other commands except `git clone...` and `npm install`?

**Comment by mthor** [comment]
I did a pull from the source project, then did an npm install from root of project,

Mac, terminal, webstorm,  node 4.2.3

I will try another clone in a new folder

**Comment by mthor** [comment]
my apologies, I removed my dir, did a fresh clone, and I had no issues, sorry for the false alarm.
