### ISSUE TITLE
The build.prod task should fail on TS error?

### ISSUE THREAD

**Issue by Sjiep** [mgechev/angular2-seed#1034]
Currently the `build.prod` will succeed, even when there are TS errors.

I can understand that this is desired behavior on `build.dev` since the watch would otherwise continuously break. However, to me it makes sense that when running the `build.prod` it should fail the build. (Since we have the `build.prod` running in a Jenkins CI)

@mgechev Is there an interest in including this functionality? I can make a PR for it.

**Comment by mgechev** [comment]
Yes, please do.
