### ISSUE TITLE
NPM packages with RC2-related version: avoiding require-not-found or 404

### ISSUE THREAD

**Issue by Myrmex** [mgechev/angular2-seed#1035]
I have just upgraded my project to the latest release of this seed, and found that most of the external (NPM) dependencies now require an explicit paths alias, as suggested in https://github.com/mgechev/angular2-seed/issues/1014. It thus seems that now the Wiki page about external dependencies is no more correct, as failing to define these aliases will produce a lot of runtime errors when launching the app ("require not defined", or 404's).

By trial and error, and following the suggestion to use SystemJS paths, I managed to restore my dependencies. I now wonder if this is the intended way of adding these dependencies, so I try to sketch my steps here. If these are OK, we might update the docs accordingly; otherwise, could you suggest the right path?

1. install the npm package with option `--save`.
2. edit `tool/config/project.config.ts` to add a paths alias pointing to the `node_modules` subfolder including the installed package stuff: in the `ProjectConfig` constructor, add code like this (I use as samples angular2-jwt, toastr, moment and jquery):

```typescript
// angular2-jwt
(<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-jwt'] =
  '/node_modules/angular2-jwt/angular2-jwt.js';

// toastr
(<any>this.SYSTEM_CONFIG_DEV.paths)['toastr'] =
  '/node_modules/toastr/toastr.js';

// moment
(<any>this.SYSTEM_CONFIG_DEV.paths)['moment'] =
  '/node_modules/moment/moment.js';

// jquery
(<any>this.SYSTEM_CONFIG_DEV.paths)['jquery'] =
  '/node_modules/jquery/dist/jquery.js';
```

Note that for some packages you might need to also include its dependencies into packages. This happens for the ngrx router, which can be used as a replacement for the Angular2 new-new router:

```typescript
    // router-start
    (<any>this.SYSTEM_CONFIG_DEV.paths)['@ngrx/core'] =
        `${this.APP_BASE}node_modules/@ngrx/core`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['@ngrx/router'] =
        `${this.APP_BASE}node_modules/@ngrx/router`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['path-to-regexp'] =
        `${this.APP_BASE}node_modules/path-to-regexp`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['isarray'] =
        `${this.APP_BASE}node_modules/isarray`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['query-string'] =
        `${this.APP_BASE}node_modules/query-string`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['strict-uri-encode'] =
        `${this.APP_BASE}node_modules/strict-uri-encode`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['object-assign'] =
        `${this.APP_BASE}node_modules/object-assign`;

    (<any>this.SYSTEM_CONFIG_DEV.packages)['@ngrx/core'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    (<any>this.SYSTEM_CONFIG_DEV.packages)['@ngrx/router'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    (<any>this.SYSTEM_CONFIG_DEV.packages)['path-to-regexp'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    (<any>this.SYSTEM_CONFIG_DEV.packages)['isarray'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    (<any>this.SYSTEM_CONFIG_DEV.packages)['query-string'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    (<any>this.SYSTEM_CONFIG_DEV.packages)['strict-uri-encode'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    (<any>this.SYSTEM_CONFIG_DEV.packages)['object-assign'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
    // router-end
```

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by tinuF** [comment]
Thank you @Myrmex. I had the same problem with the moment dependency, but with your code snippet it works now for me, too.  I'm following this seed for several months now. I use this seed because it worked out of the box for development. However for extra stuff like for example moment or, in my case a 3rd party library like https://github.com/paulrosen/abcjs, which is not listed on npm, it was always hard to figure out how integration works. Thus it really would be helpful having a better documentation which is up to date with breaking changes. The advantage of this seed really is not having to bother about deployment stuff. But this is only possible with a good documentation.

**Comment by Flood** [comment]
@Myrmex is this still working for you? I have try added your code with no luck. Still seeing "Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/query-string.js" in the console.

**Comment by Myrmex** [comment]
Currently I'm using these packages, maybe these samples can help you:

 

```

npm install --save jquery@2.2.4

npm install --save bootstrap

npm install --save font-awesome

npm install --save moment

npm install --save toastr

npm install --save angular2-jwt

```

 

Note on jquery: currently Bootstrap 3 is not compatible with jquery version 3 or above, so you must stick with jquery 2, whose latest version is 2.2.4. It seems that this will not be fixed for Bootstrap 3, we will have to wait for Bootstrap 4. Thus, you must install version 2.2.4 of jquery. If your `package.json` has a more recent version, uninstall jquery and reinstall the correct version like this:

 

```

npm uninstall --save jquery

npm install --save jquery@2.2.4

```

 

Then ensure that your `package.json` file has the exact version number for jquery, i.e. `2.2.4` (and not `^2.2.4`).

 

Each of these must be added to the project's configuration in file `project.config.ts`. As for some of them:

 

- jQuery: uncomment reference to it already present in the `project.config.ts` file.

- bootstrap: see https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles.

- Font Awesome: see https://github.com/mgechev/angular2-seed/wiki/Add-external-fonts. Also, remember to add the CSS code by injecting `{src: 'font-awesome/css/font-awesome.min.css', inject: true}`.

- angular2-jwt: see https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency: this requires adding code to `tools/utils/project/sample_util.ts` and to `src/app/main.ts`. Note that you must not add this library in `project.config.ts`.

 

The code added is thus:

 

```

this.APP_TITLE = '...';

 

// angular2-jwt

// https://github.com/mgechev/angular2-seed/issues/1014

(<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-jwt'] =

  '/node_modules/angular2-jwt/angular2-jwt.js';

this.SYSTEM_BUILDER_CONFIG.packages['angular2-jwt'] = {

    main: 'angular2-jwt.js',

    defaultExtension : 'js'

};

 

// moment

(<any>this.SYSTEM_CONFIG_DEV.paths)['moment'] =

  '/node_modules/moment/moment.js';

this.SYSTEM_BUILDER_CONFIG.packages['moment'] = {

    main: 'moment.js',

    defaultExtension : 'js'

};

 

// jquery

(<any>this.SYSTEM_CONFIG_DEV.paths)['jquery'] =

  '/node_modules/jquery/dist/jquery.js';

 

// Add `NPM` third-party libraries to be injected/bundled.

this.NPM_DEPENDENCIES = [

  ...this.NPM_DEPENDENCIES,

  // {src: 'lodash/lodash.min.js', inject: 'libs'},

  {src: 'jquery/dist/jquery.min.js', inject: 'libs'},

  // bootstrap (the CSS in my sample code is replaced by a customized theme)

  {src: 'bootstrap/dist/js/bootstrap.min.js', inject: 'libs'},

  //{src: 'bootstrap/dist/css/bootstrap.min.css', inject: true}, // inject into css section

  // font awesome

  {src: 'font-awesome/css/font-awesome.min.css', inject: true}, // inject into css section

  // toastr

  {src: 'toastr/build/toastr.min.js', inject: 'libs'},

  {src: 'toastr/build/toastr.min.css', inject: true}, // inject into css section

  // moment

  {src: 'moment/min/moment-with-locales.min.js', inject: 'libs'}

];

 

// Add `local` third-party libraries to be injected/bundled.

this.APP_ASSETS = [

  ...this.APP_ASSETS,

  // my custom Bootstrap theme

  { src: `${this.CSS_SRC}/bootstrap-mit.min.css`, inject: true, vendor: false }

  // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false}

  // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},

];

```
