### ISSUE TITLE
Config param INLINE_TEMPLATES not working correctly

### ISSUE THREAD

**Issue by vyakymenko** [mgechev/angular2-seed#1036]
```js
...
  /**
   * The flag to include templates into JS app prod file.
   * Per default the option is `true`, but can it can be set to false using `--inline-template false`
   * flag when running `npm run build.prod`.
   * @type {boolean}
   */
  INLINE_TEMPLATES = argv['inline-template'] !== 'false';
...
```

If you will try to set it to ```false``` and make a ```npm run build.prod```, it will not build a correct build, because your ```app.js``` will try to load *templates* from *root* directory.

**Comment by mgechev** [comment]
Thanks for the issue! We should remove this option since we always inline the templates in prod and never in dev.

**Comment by vyakymenko** [comment]
@mgechev , I'm not using this one, just want to notify you. I will close the issue.

**Comment by mgechev** [comment]
Lets reopen it in order to remember to remove the option tomorrow :-)

**Comment by vyakymenko** [comment]
@mgechev , pull request is ready for this one.

**Comment by mgechev** [comment]
Awesome! Thanks!

**Comment by troyanskiy** [comment]
I was correctly working for me.
Just need to specify full path to the template, Ex: `templateUrl: "\app\client\path\to\file.html"`

**Comment by vyakymenko** [comment]
@troyanskiy , we know that, but, it's will be a deprecated feature.

**Comment by troyanskiy** [comment]
I'see...
