### ISSUE TITLE
assets folder not created in prod build

### ISSUE THREAD

**Issue by tinuF** [mgechev/angular2-seed#1038]
My project: https://github.com/tinuF/eTuneBook2.
abcjs_editor_2.3-min.js under src/client/assets
this is a 3rd party js file which is not listed on npm
npm start works fine: dist/dev/assets is generated with abcjs_editor_2.3-min.js
npm run serve.prod runs without errors, however: dist/prod/assets is not generated
is this an issue or have I missed something in my project.config?: https://github.com/tinuF/eTuneBook2/blob/master/tools/config/project.config.ts

**Comment by TheDonDope** [comment]
Hi @tinuF,

have a look here: https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.assets.prod.ts#L29 (or in your fork:  https://github.com/tinuF/eTuneBook2/blob/master/tools/tasks/seed/build.assets.prod.ts#L29). JavaScript Files are not copied over. Probably `src/client/assets/` would also not be the correct place to put 3rd party scripts.
