### ISSUE TITLE
Problem or Bug in build.prod  to sub-systems (APP_BASE)

### ISSUE THREAD

**Issue by rodolfocop** [mgechev/angular2-seed#1040]
Hi everyone,

I'm with @jvitor83 using "windows 10 and IIS" in the company where we work and we go through problems with seed due to sub-systems.

My suggestion so that other people using the same SO, can solve.

I have the following scenario:

Main application: www.site.com
Another application: www.site.com/subsite/

Problems found:

1 Any change in the "APP_BASE" in "SeedConfig class" modified the addresses of files *.js and *.css, getting always pointing to a subdomain more than I had

 1.1 - APP_BASE = argv['base'] || '/Subsite'; Generated the following url: www.site.com/subsite/#/subsite/ - She had no problems, but it is not correct.

2 Another option was to change the addresses of the script via files, as found here on an issue "npm run build.prod -- --env=prod --app-env=build.dev --dest=subsite --base=/subsite/ "and change the 
  2.1 This would be the best option because the project would be with APP_BASE pointing to my "subsite" and define "base url" as '/', making this option had the following problem.
2.1.1 Access Url: www.site.com/subsite/# was changed to www.site.com/#/subsite/ being impossible to access the functionality when it was accessed directly (Save to favorites), he tried to access a route Main application of "www.site.com/#" where not met and redirected to the page 404.

Solution:

The only solution we found after this test was because the idea of ​​@JMSantos94 in #755. Even so we would have to always manually change what was unfeasible

At that moment changed again the variable APP_BASE = argv ['base'] || '' <- No parameter.

It worked properly, without presenting any of the above reported problems.

I believe it can solve many of the problems with sub-systems that can appear in Windows.

Thanks!

**Comment by mgechev** [comment]
Hey @rodolfocop! Thanks for the issue, and the detailed description! I'll take a look during the weekend and see how we can collaborate to resolve it.
