### ISSUE TITLE
Problem with watch and browser sync

### ISSUE THREAD

**Issue by martinsvb** [mgechev/angular2-seed#1048]
Hello,
may be I'm doing something wrong or have wrong expectation.
I run npm start and application is built in dev mode and localhost server started.
But after this actions changes aren't watched and propagate to the browser sync.
Please can you help me/describe problem?
Thanks
Martin

**Comment by mgechev** [comment]
What is your OS, node.js, npm versions?

Did you make any changes in the seed or this occurs in fresh clone?

**Comment by dbrezoev** [comment]
I think I have almost the same problem. Every time after npm start everything works just fine, but after I change something it throw me `Error: SyntaxError: Unexpected token < in JSON at position 0(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"` I just added some classes (services) in the seed. I am on win 10, node 4.4.6, npm 2.15.5. I just tried with a fresh clone, and everything is working.

**Comment by mgechev** [comment]
Would you share the content of your `tools/env/config.json`?

**Comment by dbrezoev** [comment]
`{
  "dev": {
    "API": "https://demo.com"
  },
  "prod": {
    "API": "https://prod.com"
  },
  "staging": {
    "API": "https://staging.com"
  }
}
`

**Comment by martinsvb** [comment]
I am on win 7, node 4.2.4, npm 3.10.2 (updated today, it was broken in v2 too)
It occurs in fresh clone.
I run browser at localhost:5555 (automatically opened), localhost:4000 is unavailable.
When I change for example home.component.html and save it, watch isn't processed.

**Comment by martinsvb** [comment]
Hello again, it looks on problem with npm 3.10.2 v. On my older notebook with npm v2 version it works ok. Concretely I checkout repo, run "npm i" twice (maybe not needed) and "npm i typings" an it works ok.

**Comment by martinsvb** [comment]
Anyway thank you for perfect seed! :-)

**Comment by martinsvb** [comment]
Hi again, on other computer browser sync works with npm v3. So it isn't related to npm version. Probably some local problem in my notebook.

**Comment by mgechev** [comment]
Ok, thanks. Lets close the issue then.

**Comment by dbrezoev** [comment]
Hello again, I found out why my issue occurs. I use Visual Studio for both backend and frontend (typescript) and sometimes I misclick f5 for building the frontend instead of the backend. So it generates me all the `.js` files and browsersync stops working. After I discard these files everything is fine. I thought it would be nice if you know this.

**Comment by jwbuitenhuis** [comment]
I ran into this issue too, it went away after I rebuilt the app.
