### ISSUE TITLE
Documentation lacks information to add angular2-jwt for prod

### ISSUE THREAD

**Issue by BouncingBit** [mgechev/angular2-seed#1049]
1. Add the latest version of angular-jwt to the project according to the documentation here:
https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

2. Try to call 
`npm runbuild.prod`

3. Notice, the following error output where the build.bundles.app tries to resolve the angular2-jwt library at <your-seed-project>/node_modules/angular2-jwt/angular2-jwt.js

To fix the issue, you i.e. have to add something like this within the constructor section of the _tools/config/project.config.js_ file:

```
    this.SYSTEM_BUILDER_CONFIG.packages['angular2-jwt'] = {
      main: 'angular2-jwt.js',
      defaultExtension : 'js'
    };
```
Maybe you want to add this information to the affordmentioned documentation (or a better solution than mine. ;) )

**Comment by mgechev** [comment]
Looks good to me! Would you add details to the wiki?

**Comment by BouncingBit** [comment]
Sure thing. Updated the documentation and added a cast to <any> to prevent TS lint warnings. Cheers.
