### ISSUE TITLE
 The list of local files to be injected in the `index.html

### ISSUE THREAD

**Issue by mthor** [mgechev/angular2-seed#1052]
I can add node_modules packages no problem, I can add css files in the seed.config.ts  (line 266, APP_ASSETS) ,  

I am having issues adding a local .js file I need to inject.  

ex) { src: `${this.APP_SRC}/resources/layout/js/nanoscroller.js }`, inject: true, vendor: false } 

that does not get injected.   what am I missing?

**Comment by ludohenin** [comment]
Strange, this should work. You should no modify  `seed.config.ts` but rather use `project.config.ts` instead, but that's not the reason. Are you sure the path is correct ?

**Comment by mthor** [comment]
yes, I am sure this is happening, 

I did first try to modify the project.config with 


      {src: `${this.APP_DEST}/resources/layout/js/nanoscroller.js }`, inject: true }

but I get that the file is not found, but I check the path and the file is in my folder structure under dist/dev

**Comment by sfabriece** [comment]
try changing `inject:true` to `inject:'libs'`

**Comment by mgechev** [comment]
You can try:

```
...
    let additional_deps: InjectableDependency[] = [
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      { src: `${this.PROJECT_ROOT}/${this.APP_DEST}/app/demo.js`, vendor: false, inject: true }
    ];
...
```

Which works well.
