### ISSUE TITLE
ROUTER - Go to Component

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#1054]
Hi Guys,

Using angular 2 seed, how can I state to direct user to a component? For example, after user logs in, I need to direct user to another component (dashboard)?

Thank yoou

**Comment by TheDonDope** [comment]
Hi @simoazzo, this is not an issue regarding the seed, however i will provide you some directions:

In your `*component.ts`file you can do something like this:

```TypeScript
  /**
   * Handles a successful login attempt by redirecting to the dashboard.
   */
  loginSuccessful(): void {
    this.router.navigate(['/dashboard'], { relativeTo: this.activatedRoute });
  }
```

**Comment by simoazzo** [comment]
Thanks.

Where can I submit any questions that I might have please?

Thank you

**Comment by TheDonDope** [comment]
@simoazzo Have a look here: https://github.com/mgechev/angular2-seed/issues/1021#issuecomment-227767436
