### ISSUE TITLE
Routes in Angular 2 Seed

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#1058]
Hi Guys,

I am quiet confusing how  routes are working, especially those ... elipsis app.routes.

Are there any guide on this, on how to user routing in angular 2 seed project?

Thank you

Kind regards

**Comment by TheDonDope** [comment]
Hi @simoazzo, have a look at the official developer guide here: https://angular.io/docs/ts/latest/guide/router.html

As for the ellipsis:

![capture](https://cloud.githubusercontent.com/assets/1188033/16431612/abbab52e-3d81-11e6-9097-4c9c8240d09e.PNG)
