### ISSUE TITLE
Need some help regarding Observables

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#1062]
hi guys,

I have this chunk of chode

```
var _loginResponseModel = new LoginResponseModel();
        this.checkIfUserIsLoggedIn().subscribe(
            result => {

                _loginResponseModel = result;
                 console.log(_loginResponseModel.IsAuthenticated);
            }
             
         );

         console.log(_loginResponseModel.IsAuthenticated);
        return _loginResponseModel.IsAuthenticated;
```

the first console.log if keeping the value (true) but outiside the subscribe, the value is `undefined`

Any thoughts please?

thank you

**Comment by simoazzo** [comment]
This code is in a service, called AuthService, where I want to set either true or false so that it can be used for CanActivate

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
