### ISSUE TITLE
Issue in  bulld.prod -> build.bundles.app:  Unhandled rejection Error on fetch for dist\tmp\app\main.js

### ISSUE THREAD

**Issue by ocace** [mgechev/angular2-seed#1064]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

I built the app successfully. After doing an npm clear cache, the error started to occured in many machines.The error happens when I do: npm run bulld.prod and only when it build the app bundles.

Here is the error:

[17:19:57] Starting 'build.bundles.app'...
Unhandled rejection Error on fetch for dist\tmp\app\main.js at file:///C:/NF Development/dotNetSolutions_2012/N1/AdminPortal/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'C:\NF Development\dotNetSolutions_2012\N1\AdminPortal\node_modules\dist\tmp\app\main.js'
    at Error (native)

It seems that this line "  [`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`," in the paths is not respected and it jumps to the nodemodules one.

SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    packageConfigPaths: [
      join(this.PROJECT_ROOT, 'node_modules', '*', 'package.json'),
      join(this.PROJECT_ROOT, 'node_modules', '@angular', '*', 'package.json')
    ],
    paths: {
      [`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`,
      'file-saver/filesaver.js':'node_modules/filesaverjs/filesaver.js',
      '*': 'node_modules/*'
    },

machine: Windows 10, npm v:3.9.3, node -v: 4.4.5 

Another question: Is there an easy way to just call build.bundles.app instead of the whole production build. Is there a way to log some results or debug this??

**Comment by ZuSe** [comment]
I can confirm this. Same issue here.
Windows 10, node 5.10.1, npm 3.8.3

On my Ubuntu it works -> seems to be a windows related issue

**Comment by mgechev** [comment]
I wasn't able to reproduce the issue on Windows 8 after running:

```bash
git clone https://github.com/mgechev/angular2-seed --depth 1
cd angular2-seed
npm cache clean
npm i
npm run build.prod
```

Would you try a clean install and tell me if you can still reproduce it?

**Comment by ocace** [comment]
It works in the new version. Is there a way to debug the tasks?
