### ISSUE TITLE
Dynamic Template Functionality

### ISSUE THREAD

**Issue by nitish3488** [mgechev/angular2-seed#1071]
How can we pass the templateUrl dynamically(instance specific) to implement dynamic-template/theme functionality on the basis of some parameters like can we apply any condition in component metadata lets say on templateUrl on the basis of instance.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
