### ISSUE TITLE
Need help! npm run serve.dev screws up compilation while watching file changes

### ISSUE THREAD

**Issue by csreddy** [mgechev/angular2-seed#1075]
`npm start` or `npm run serve.dev` work fine on the initial start. After i make changes in my application code and save files, it re-runs the compilation. After this, the application fails with the below error. 
I have to restart the task everytime or  run `npm run build.dev` repeatedly after every file save. It's killing me!

NOTE: This issue started happening recently. I'm almost sure there is nothing wrong in the seed files. I just need any clues/suggestion on how to fix the problem. Your help is much appreciated.

```
status:97 Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:9002/.app/main.js
	Error loading http://localhost:9002/.app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"
```
Apparently its looking for `.app/main.js` instead of `app/main.js`

**Comment by csreddy** [comment]
Ok I narrowed down to system config in index.html
When `npm run build.dev` is run the path looks like this
```
 "paths": {
    "app/main": "/app/main",
    "rxjs/*": "/rxjs/*",
    "app/*": "/app/*",
    "*": "/node_modules/*"
  },
```

after recompilation it becomes this
```
  "paths": {
    "app/main": ".app/main",
    "rxjs/*": ".rxjs/*",
    "app/*": "/app/*",
    "*": ".node_modules/*"
  },
```

What's causing the change in path?

**Comment by csreddy** [comment]
Ok after little more investigation I found that setting   APP_BASE = '.'  was causing the problem.
Changing it back to `/` fixed the issue. But the new router suggests to use `.` 
I'm confused with this now. Any explanation ?

**Comment by mgechev** [comment]
```
  "paths": {
    "app/main": ".app/main",
    "rxjs/*": ".rxjs/*",
    "app/*": "/app/*",
    "*": ".node_modules/*"
  },
```
is part of the SystemJS config and has nothing to do with the router. No worries, you can keep the `APP_BASE` to equal `/`.
