### ISSUE TITLE
External Dependencies that are not part of NPM

### ISSUE THREAD

**Issue by scaryroy** [mgechev/angular2-seed#1077]
**Current behavior**
All external dependencies must be in the node_modules directory.

**Expected/desired behavior**
I'm not quite sure about how this is going to work.

**Comment by mgechev** [comment]
We support external dependencies in `node_modules`. You can also "Inject" dependencies by declaring them [here](https://github.com/mgechev/angular2-seed/blob/master/tools/config/project.config.ts#L17-L20).
