### ISSUE TITLE
GET http://localhost:5555/node_modules/@ngrx/package.json 404 (Not Found)

### ISSUE THREAD

**Issue by SahilDude89ss** [mgechev/angular2-seed#1080]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
1. Follow all the steps to setup the repo.
2. Install @ngrx store and core from here [https://github.com/ngrx/store]
3. Update the SeedConfg.SYSTEM_CONFIG_DEV.packageConfigPaths (tools/config/seed.config.ts) to add ``/node_modules/@ngrx/*/package.json``
4. Update the SeedConfg.SYSTEM_CONFIG_DEV.paths (tools/config/seed.config.ts) to add '@ngrx/core': `node_modules/@ngrx/core/index.js` AND '@ngrx/store': `node_modules/@ngrx/store/index.js`.
5. Update SYSTEM_BUILDER_CONFIG.packageConfigPaths (tools/config/seed.config.ts) to add join(this.PROJECT_ROOT, 'node_modules', '@ngrx', '*', 'package.json') and SYSTEM_BUILDER_CONFIG.packages to add ``'@ngrx/core': { main: 'index.js', format: 'cjs'}, '@ngrx/store': {main: 'index.js', format: 'cjs'}
6. Run ``npm start``.

_What steps should we try in your demo to see the problem?_
SAME AS ABOVE ^^

**Current behavior**
The APP is not booting at all.

**Expected/desired behavior**
The main.ts should load the default page.

**Other information**

**Comment by mgechev** [comment]
The `packageConfigPaths` should be ordered this way:

```
...
  "packageConfigPaths": [
    "/node_modules/*/package.json",
    "/node_modules/**/package.json",
    "/node_modules/@ngrx/*/package.json",
    "/node_modules/@angular/*/package.json"
  ],
...
```

**Comment by geekrumper** [comment]
Hi there,
too bad the opener (@SahilDude89ss ) did not respond to the comment from @mgechev .
I have the same issue not being able to load

- @ngrx/core
- @ngrx/store
- @ngrx/effects

Here I are the modifications of "seed.config.ts":
https://gist.github.com/geekrumper/1578437aee508001db6eccfd6f452b15

Shouldn't I be able to see all three modules served here?
![angular-seed-ngrx-browser-console](https://cloud.githubusercontent.com/assets/662318/17319590/eb1c7810-588e-11e6-8abc-3736d3f22fa4.png)

**Comment by thomas-bee** [comment]
I ran into the same problem and the above works. However, does this have to configured in `seed.config.ts` or is there a way to integrate @ngrx in `project.config.ts` ?
