### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xvs32x** [mgechev/angular2-seed#1083]
`Uncaught RangeError: Maximum call stack size exceeded`

Hello, I got this error in prod build only.
I'm find this report in angular repository https://github.com/angular/angular/issues/7930
So, if this `mangle` param, how i can turn off him. Thanks!

**Comment by mgechev** [comment]
Mangling is [disabled by default](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.bundles.app.ts#L12-L16). 

Do you reproduce this from clean clone or you did changes?

**Comment by xvs32x** [comment]
@mgechev did changes, many changes... :)

**Comment by mgechev** [comment]
Most likely the issue is not related to the seed itself but to the changes that you have done :-).

For support requests you can move the discussion to gitter.
