### ISSUE TITLE
Use third-party lightbox script in angular2-seed project

### ISSUE THREAD

**Issue by HehnRobert** [mgechev/angular2-seed#1085]
Hi, 
I'm new to typescript and angular 2 as well and I'm trying to display an image gallery with angular2-seed project. I tried to 
`import '../../js/lightbox-plus-jquery.min.js';`
at the beginning of the component, but I got

> Error: ENOENT: no such file or directory, open '/Users/roberthehn/WebstormProjects/hehn/dist/tmp/app/+home/src/client/js/lightbox-plus-jquery.min.js'

Then, after searching on the wiki page, I tried adding
`{src: '/Users/roberthehn/WebstormProjects/hehn/src/client/js/lightbox-plus-jquery.min.js', inject: 'libs'}`
inside project.config.ts still without success, giving me the following error:

> Error: Octal literals are not allowed in strict mode (line: 23821, col: 15, pos: 973662)

Can you please help me with this issue?
Thank you.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
