### ISSUE TITLE
Sass support doesn't seem to work with unit tests

### ISSUE THREAD

**Issue by variuse** [mgechev/angular2-seed#1086]
When enabling SCSS support in seed or project config like `ENABLE_SCSS = true;` and using *.scss files instead of *.css files for component styling, unit tests can't run properly since *.css files are still referenced in components.

So in the end I tried both options: 

Referencing *.css in component definition like this
`styleUrls: ['about.component.css']`
Result: 
Karma crashes because it can't find *.css files since I'm using *.scss in src folder, but app is running properly from dist

Referencing *.scss in component definition like this
`styleUrls: ['about.component.scss']`
Result: 
Karma and unit tests run properly, but app crashes since it of course can't find *.scss files in dist 

I'm not an expert with Karma and apologize in advance if I'm doing something terribly wrong ;)

**Comment by mgechev** [comment]
@variuse thanks for the issue! Most likely you're not doing anything wrong.

@hank-ehly would you have some time to take a look at this one?

**Comment by hank-ehly** [comment]
@variuse 

Thank you for your comment. I'll take a look.
