### ISSUE TITLE
SASS support and gulp-inline-ng2-template in production build not working

### ISSUE THREAD

**Issue by giovannicandido** [mgechev/angular2-seed#1088]
To reproduce: 

1. Enable SASS Support
2. Rename main.css to main.scss
3. Run `npm run build.prod`

Exceptions:

> Error in plugin 'run-sequence(build.bundles.app)'
> Message:
>     Error on fetch for dist/tmp/app/+about/about.component.js at file:///Users/giovanni/tmp/angular2-seed/dist/tmp/app/+about/about.component.js
> 	Loading dist/tmp/app/+about/index.js
> 	Loading dist/tmp/app/app.routes.js
> 	Loading dist/tmp/app/main.js
> 	ENOENT: no such file or directory, open '/Users/giovanni/tmp/angular2-seed/dist/tmp/app/+about/about.component.js'

In my investigation, the problem is the plugin **gulp-inline-ng2-template**

Removing the plugin from the build, does allow the build to complete, but in runtime the templates are not located.

**Dev Build is OK**

**Comment by giovannicandido** [comment]
After more investigation I see that the **tools/tasks/seed/build.html_css.ts** doesn't process .css files if SASS is enable.

The code

    function processComponentStylesheets() {
      return ENABLE_SCSS ? processComponentScss() : processComponentCss();
    }

Is called in the export function. So, by the time the plugin gulp-inline-ng2-template is executed, the .css files of the components are not in the stream.

Solution:

Rename all css  files in *app* with the command

    find . -name "*.css" -exec rename 's/\.css$/.scss/' '{}' \;

## Question

Is this by design?
Should we use the two at the same time?

If yes, I think the documentation must have a warning it in the SCSS section.

**Comment by hank-ehly** [comment]
@giovannicandido 

Thank you for your comment. 

According to the [wiki](https://github.com/mgechev/angular2-seed/wiki/Enabling-SASS-support), it is required that you "rename **all** of your *.css files to *.scss" (it looks like you found the solution yourself).

**Comment by giovannicandido** [comment]
@hank-ehly Thank you
Hum... interesting, I miss that :-)
Now I try to run test and get the error:

> Error: ENOENT: no such file or directory, open '/Users/giovanni/tmp/angular2-seed/src/client/app/+about/about.component.css'

Maybe related to your issue: https://github.com/mgechev/angular2-seed/issues/1086

**Comment by giovannicandido** [comment]
@hank-ehly Removing the inlineNg2Template pipe in *build.js.test.ts* solve the issue and the tests pass.

Can you try in your problem. By the way, my components styleUrl points to the *css* file and not the sass one.

**Comment by hank-ehly** [comment]
@giovannicandido 

The css-related errors that occur when you run `npm test`  are being discussed in #1086. 
I would recommend watching that issue for more updates!

**Comment by mgechev** [comment]
Lets close this issue since it is duplication of https://github.com/mgechev/angular2-seed/issues/1086.
