### ISSUE TITLE
ng2-bootstrap production build not running

### ISSUE THREAD

**Issue by red010b37** [mgechev/angular2-seed#1089]
Hi guys

I was wondering if you could help me out Ive searched high and low - went through the advanced seed but still cant get there.

I have added ng-bootstap to my project - works great in dev. but when I build a production build it thows this 
`
shims.js?1467776952952:6 Uncaught TypeError: System.registerDynamic is not a function(anonymous function) @ shims.js?1467776952952:6
app.js?1467776952953:47 EXCEPTION: Error: Uncaught (in promise): ReferenceError: _ is not defined`

when i comment out the code to import bootstrap everything is fine
```
 //{ src: 'ng2-bootstrap/bundles/ng2-bootstrap.js', inject: 'libs' }, //- no problem

 { src: 'ng2-bootstrap/bundles/ng2-bootstrap.js', inject: 'libs' }, //- problem

```

Now i think it has something todo with the systemJS Builder and moment but cant seem to work it out.

here is my config
```
import { join } from 'path';

import { SeedConfig } from './seed.config';
import { InjectableDependency } from './seed.config.interfaces';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedConfig {

    PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');
    VENDOR_DIR = join(process.cwd(), this.APP_SRC, 'vendor');
    CSS_PROD_BUNDLE = 'main.css';

    constructor() {
        super();
        this.APP_TITLE = 'MILK Editor';
        this.APP_CLIENT = 'editor';
        this.APP_SRC = `src/${this.APP_CLIENT}`;

      let additional_deps: InjectableDependency[] = [

        { src: 'ng2-bootstrap/bundles/ng2-bootstrap.js', inject: 'libs' },

        { src: 'aws-sdk/dist/aws-sdk.min.js', inject: 'libs' },
        { src: `async/dist/async.min.js`, vendor: false, inject: true },
        { src: `underscore/underscore-min.js`, vendor: false, inject: true },
        { src: 'blueimp-load-image/js/load-image.all.min.js', inject: 'libs' },
        { src: 'hammerjs/hammer.min.js', inject: 'libs' },
        { src: 'bootstrap-slider/dist/bootstrap-slider.min.js', inject: 'libs' },

        { src: 'gsap/src/minified/TweenLite.min.js', inject: 'libs' },
        { src: 'gsap/src/minified/plugins/CSSPlugin.min.js', inject: 'libs' },
        { src: 'gsap/src/minified/easing/EasePack.min.js', inject: 'libs' },

        { src: `${this.PROJECT_ROOT}/${this.APP_DEST}/scripts/main.js`, vendor: false, inject: true },
        { src: `${this.PROJECT_ROOT}/${this.APP_DEST}/scripts/load.mage.custom.js`, vendor: false, inject: true },
        { src: `${this.PROJECT_ROOT}/${this.APP_DEST}/scripts/underscore.naturalsort.js`, vendor: false, inject: true }

        ];

        const seedDependencies = this.NPM_DEPENDENCIES;

        this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);


        // Add moment to the system config for ng2-bootstrap
        this.SYSTEM_CONFIG['map'] = {
          'moment': `${this.APP_BASE}node_modules/moment/moment`,
        };

        /* THINK THIS IS THE ISSUE - HELP ANYONE*/
        this.SYSTEM_BUILDER_CONFIG.packages['moment/moment'] =  {
          main: 'moment.js',
          defaultExtension: 'js'
        } ;



    }
}

```

**Comment by mgechev** [comment]
Hey @red010b37 `ng2-bootstrap` is not intended to be injected. Generally, injection of scripts should happen in only **rare** cases when a side-effect is indented (such as exposing a global variable).

Yes, as you guessed, most likely the issue is related to misconfigured SystemJS builder. For further information on how to configure the builder properly you can take a look at the [docs of SystemJS](https://github.com/systemjs/builder) or try the [gitter channel of the seed](https://gitter.im/mgechev/angular2-seed).

**Comment by AshMcConnell** [comment]
How do I get ng2-bootstrap added to the production build?  Is there any guide on what method is used to include different types of 3rd party libs?  Thanks guys!

**Comment by karlhaas** [comment]
I think you don't need any special config for the builder. Do you have `'node_modules/*': 'node_modules/*',` in SYSTEM_BUILDER_CONFIG.paths?

**Comment by AshMcConnell** [comment]
Thanks Karl, I have ***': 'node_modules/*'** in SYSTEM_BUILDER_CONFIG.paths, should it be **'node_modules/*': 'node_modules/*'**, ?

If I don't have: - '

```
'ng2-bootstrap': {
                main: 'ng2-bootstrap.js',
                defaultExtenstion: 'js'
            },
```

in the SYSTEM_BUILDER_CONFIG.packages I get a file not found error when building

> Error on fetch for ng2-bootstrap.js at file:///C:/Work/MyProject/src/web/node_modules/ng2-bootstrap.js

**Comment by karlhaas** [comment]
You need both:
```
    paths: {
      [join(this.TMP_DIR, 'app', '*')]: `${this.TMP_DIR}/app/*`,
      'node_modules/*': 'node_modules/*',
      '*': 'node_modules/*'
    },
```
For me it works without any special config. Do you have the latest seed.config.ts?

**Comment by AshMcConnell** [comment]
I'm a few weeks out of date, I'll try that, thanks!
