### ISSUE TITLE
SASS watch exiting with 'unknown error, open' on main.css

### ISSUE THREAD

**Issue by Sjiep** [mgechev/angular2-seed#1090]
With the `npm start` command running, it sometimes exits 'randomly' with the following error, whenever some file is changed.

```
[BS] Reloading Browsers...
[11:16:18] Starting 'build.dev'...
[11:16:18] Starting 'build.assets.dev'...
[11:16:18] Finished 'build.assets.dev' after 93 ms
[11:16:18] Starting 'build.html_css'...
Error: UNKNOWN: unknown error, open '...project\dist\dev\css\main.css'
    at Error (native)
```

I've never really figured out why this is happening. 

Im running the seed with SASS enabled. Does anybody else experience this error?

@hank-ehly Could this possibly have anything to do with some timing issue where the `main.scss` is still being converted to `main.css` but the next step in the gulp process is already expecting `main.css` to be there.

**Comment by hank-ehly** [comment]
@Sjiep 

Thank you for your comment. I'll take a look.

**Comment by Sjiep** [comment]
I did a bit of debugging to find out where it exactly happens in the `build.html_css` task and found out that tasks crashes in the following [pipe command](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.html_css.ts#L102).

I'm am still rather clueless why it's happening though...

**Comment by Sjiep** [comment]
Still haven't found the real reason why this is happening. I found an ugly workaround for myself such that the doesn't occur any more (or at least very rarely). In task `build.html_css.ts` I added a `wait` into the pipeline at the function `processAllExternalStylesheets`, i.e.:

```
function processAllExternalStylesheets() {
  return merge(getExternalCssStream(), getExternalScssStream())
    .pipe(isProd ? plugins.concatCss(CSS_PROD_BUNDLE, {rebaseUrls: false}) : plugins.util.noop())
    .pipe(plugins.postcss(processors))
    .pipe(isProd ? cleanCss() : plugins.util.noop())
    //TODO: really dodgy way of solving the 'watch reload main.css' error
    .pipe(plugins.wait(400))
    .pipe(gulp.dest(CSS_DEST));
}
```
