### ISSUE TITLE
not an issue need some sugessation

### ISSUE THREAD

**Issue by vivdkool** [mgechev/angular2-seed#1097]
Hi @mgechev 

I am starting new project for that was looking seed project for angular2 and bit confused between https://github.com/AngularClass/angular2-webpack-starter and this seed as well as angular CLI which one would you recommend. I have seen you are contributor on both, thats why asked to you.

**Comment by mgechev** [comment]
This is a matter of personal preferences. If you want to open a discussion for this [gitter is a good option](https://gitter.im/mgechev/angular2-seed).
