### ISSUE TITLE
npm start  not working ? 

### ISSUE THREAD

**Issue by zenghuiLee** [mgechev/angular2-seed#1103]
os: mac10.10.5
node v6.2.0
npm  v3.8.9

@mgechev
os problem or seed problem?

[00:45:54] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,30): Cannot find module 'run-sequence'. (2307)
tools/config/project.config.ts (1,22): Cannot find module 'path'. (2307)
tools/config/project.config.ts (11,28): Cannot find name 'process'. (2304)
tools/config/seed.config.ts (1,22): Cannot find module 'path'. (2307)
tools/config/seed.config.ts (2,22): Cannot find module 'yargs'. (2307)
tools/config/seed.config.ts (39,23): Cannot find name '__dirname'. (2304)
tools/config/seed.config.ts (152,25): Cannot find name 'process'. (2304)
tools/config/seed.config.ts (412,20): Cannot find name 'require'. (2304)
tools/config/seed.config.ts (427,27): Cannot find name 'require'. (2304)
tools/config/seed.config.ts (436,24): Cannot find name 'require'. (2304)
tools/config/seed.config.ts (464,51): Cannot find name 'require'. (2304)
tools/config/seed.config.ts (489,13): Cannot find name 'require'. (2304)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by mgechev** [comment]
Duplication of https://github.com/mgechev/angular2-seed/issues/930 and https://github.com/mgechev/angular2-seed/issues/591, and others.
