### ISSUE TITLE
Non-component CSS throws MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by uautkarsh** [mgechev/angular2-seed#1104]
Hello,

To reproduce the issue, just clone the latest version, and try the following task.
I am trying to include an extra CSS file `extra.css` file along with `main.css`, in the folder `src/client/css/`

I am not sure what reference should be added to `project.config.ts`. I have tried various statements such as:
`{src: 'css/extra.css', inject: true}`
`{src: '../../css/extra.css', inject: true}`
`{src: '${this.APP_SRC}/css/extra.css', inject: true}`
`{src: '${this.APP_CSS}/extra.css', inject: true}`
etc

I have exhausted search engine results, the wiki for the seed app and gitter.

When I execute npm start, I get the `code: MODULE_NOT_FOUND` error.

I expect `extra.css` to be added to the `dist/dev/css/` folder in development mode, and the respective stylesheet injection in `index.html`, and get appended to `dist/prod/css/main.css` in production mode, and the respective stylesheet linked in `index.html`

I request you to please help me resolve the issue.

Thank You

**Comment by TheDonDope** [comment]
Hi @uautkarsh, have a look at the changes from this PR ( #1101): https://github.com/mgechev/angular2-seed/pull/1101/files .

Could you try with this again? (Adding your css through `project.config.ts` like in the sample from the PR)

Greetings

Dope

**Comment by uautkarsh** [comment]
Hello,

Thank you for the reply.

I confirm that the CSS issue is resolved for dev and prod.

I tried to do the same thing for JS files, but I failed to do so. The JS files get added to the builds, but are not referenced in index.html, minified, or bundled with main.js.

I followed the steps mentioned at ["Add external scripts and styles" ](https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles) to add bootstrap. I tried the tooltip example of bootstrap, and it did not seem to work. Can you provide an example on how to add and use the external scripts properly? I hope I am not missing some step for script files.

Thank you
