### ISSUE TITLE
Routing: 404 Not Found status in production build

### ISSUE THREAD

**Issue by daivinhtran** [mgechev/angular2-seed#1105]
I run 'npm run build.prod' to build the production build. I could navigate to http://127.0.0.1:8080/about by clicking on the navbar. However, when I refresh the page or go directly to the about page by typing http://127.0.0.1:8080/about to the url box, I get 404 Not Found status. 

This does not happen in the development build.

I am using http-server to serve the production build. Does anyone have a similar issue?

Update: I also tried using Apache and Nginx, same issues still appear.

**Comment by TheDonDope** [comment]
Hi @daivinhtran, have a look here: https://github.com/mgechev/angular2-seed/wiki/Deploying-prod-build-to-Apache-2

**Comment by tpruthi** [comment]
hi @TheDonDope  can you tell me the what would be the configuration for nginx

**Comment by TheDonDope** [comment]
Hi @tpruthi, i do not know the specific configuration, but you could take a look here: https://github.com/vyakymenko/angular2-seed-express, more specifically https://github.com/vyakymenko/angular2-seed-express#how-to-configure-my-nginx.
Paging @vyakymenko
