### ISSUE TITLE
Integration of Vaadin-elements in Seed Project

### ISSUE THREAD

**Issue by abhibly** [mgechev/angular2-seed#1106]
Hello...I am trying to setup vaadin elements in angular2 seed project.According to the tuturial provided here https://vaadin.com/docs/-/part/elements/angular2-polymer/tutorial-index.html i need to mention the packages in systemjs.config.js file but i couldnt find systemjs.config.js in the seed project.I want to know where should i define the packages as explained in the tutorial.Thanks...

**Comment by TheDonDope** [comment]
Hi @abhibly, have a look here: https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2

**Comment by abhibly** [comment]
Thanks @TheDonDope

**Comment by abhibly** [comment]
Hello @TheDonDope...From the link you gave i gave the path references for vaadin elements in project.config.ts but i shouldnot import the 'app' folder until webcomponents are ready.Writing this statement throws me this error

**Comment by TheDonDope** [comment]
Hi @abhibly, sorry i cannot help you with that. From the vaadin docs link you posted in your initial post, i just found their example GitHub repository: https://github.com/vaadin/angular2-polymer-quickstart

**Comment by abhibly** [comment]
Hi @TheDonDope , this is the link which explains about the integration of vaadin elements in angular2-application https://vaadin.com/docs/-/part/elements/angular2-polymer/tutorial-index.html ...
In my angular2 seed project i have made the following changes based on the above link

1. Added bower.json file and installed all the dependencies

2.Installed angular2-polymer using this instruction `npm install @vaadin/angular2-polymer --save`

3. And then made changes in project.config.ts file like this 
`
    this.SYSTEM_CONFIG_DEV.paths['@vaadin/angular2-polymer'] =
      `${this.APP_BASE}node_modules/@vaadin/angular2-polymer`;

    this.SYSTEM_BUILDER_CONFIG.packages['@vaadin/angular2-polymer'] = {
        main: 'index.js',
        defaultExtension : 'js'
    };
`

4. I downloaded the needed elements index.html and added this event 
`  <script>
      document.addEventListener('WebComponentsReady', function() {
        System.import('app').catch(function(err){ console.error(err); });
      });
    </script>`
If possible can you please checkout that tutorial link which i gave and tell me where i am doing wrong and what is the correct approach for integrating vaadin in angular2-seed project
