### ISSUE TITLE
How to incorporate different approach of environment configuration

### ISSUE THREAD

**Issue by anho** [mgechev/angular2-seed#1109]
Hi everyone,

I'm looking for a solution, or maybe a draft how to do it, to incorporate a different approach to environment configuration. In our company we do not use configuration files/values that are put directly into the shippable component. Instead we have components that can be configured on demand during runtime (e.g. Docker images configured through environment variables). So I was thinking of something like requesting the configuration file (e.g. ``/config.json``) on startup and injecting this information into the application after receiving it.
Can someone help me out on this one, especially on how to make it happen with Angular2 and seed.

Best regads
Andreas

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by anho** [comment]
Is there a more async way to discuss these kind of questions? I'm not eager to hang around at gitter waiting for an answer and would prefer something like a forum or google group.
