### ISSUE TITLE
Problem in integrating vaadin elements in seed project

### ISSUE THREAD

**Issue by abhibly** [mgechev/angular2-seed#1111]
Hello guys I am trying to integrate vaadin elements in in my seed project.I went through these links https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency  &  https://vaadin.com/docs/-/part/elements/angular2-polymer/tutorial-index.html  and made changes accordingly but i am getting this error `Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@vaadin/package.json(…)`
Somebody please tell me why am i getting this error and what is the correct way to add polymer dependencies in my seed project.I have made a repo here https://github.com/abhibly/Angular2-Seed-Project demonstrating my issue.Thanks

**Comment by TheDonDope** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

Also duplication of #1106

**Comment by abhibly** [comment]
@TheDonDope Hi...I went through the resources which you gave but couldn't succeed.For integrating vaadin-polymer in angular2 application i used to make the following changes in systemjs.config.js file
`  // map tells the System loader where to look for things
  var map = {
    '@vaadin':                    'node_modules/@vaadin'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    '@vaadin/angular2-polymer':   { main: 'index.js', defaultExtension: 'js' }
  };`

I made the following changes in project.config.ts 
`    this.SYSTEM_CONFIG_DEV.paths['@vaadin'] =
        `${this.APP_BASE}node_modules/@vaadin`;

    this.SYSTEM_BUILDER_CONFIG.packages['@vaadin/angular2-polymer'] = {
        main: 'index.js',
        defaultExtension: 'js'
    };`
and got this error 
`Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@vaadin/package.json(…)`
What changes should i make in project.config.ts to make vaadin-polymer work in my angular-seed?Can you please show me the changes to make my vaadin-polymer work in seed-project

**Comment by j4in** [comment]
any progress on this ?

**Comment by zkewal** [comment]
I am facing similar issue. Please let me know if you find a solution.

**Comment by zkewal** [comment]
I made the following changes and now it is working for me:

```
    this.SYSTEM_CONFIG_DEV.paths['@vaadin/angular2-polymer'] =
      `${this.APP_BASE}node_modules/@vaadin/angular2-polymer`

    this.SYSTEM_CONFIG_DEV.packageConfigPaths =
      this.SYSTEM_CONFIG_DEV.packageConfigPaths.concat([
        `${this.APP_BASE}node_modules/@vaadin/*/package.json`
      ])

    this.SYSTEM_BUILDER_CONFIG.packages['@vaadin/angular2-polymer'] = {
      main: 'index.js',
      defaultExtension: 'js'
    }
```
