### ISSUE TITLE
empty data.json causes infinite xhr call loop

### ISSUE THREAD

**Issue by billsworld** [mgechev/angular2-seed#1113]
When [data.json](https://github.com/mgechev/angular2-seed/blob/master/src/client/assets/data.json) contains an empty array ```[]``` it causes an infinite loop. It seems the seed should handle an empty response better.

The code that needs updating lies here https://github.com/mgechev/angular2-seed/blob/master/src/client/app/shared/name-list/name-list.service.ts#L43

```
  get(): Observable<string[]> {
    if (this.names && this.names.length) {
      return Observable.from([this.names]);
    }
    if (!this.request) {
      this.request = this.http.get('/assets/data.json')
        .map((response: Response) => response.json())
        .map((data: string[]) => {
          this.request = null;
          return this.names = data;
        }).publishReplay(1).refCount();
    }
    return this.request;
  }

**Comment by mgechev** [comment]
Thanks for the issue! Would you open a PR with the suggested page?

**Comment by TheDonDope** [comment]
The implications from the PR #960 that changed the original implementation and added `publishReplay(1).refCount()` are not as obvious as might be expected. Essentially this change turned the `Observable` from a cold one (one, that only starts to emit values when subscribed to), to a hot one (one that starts emitting values, regardless if an Observer subscribed to it) (Further read: http://blog.thoughtram.io/angular/2016/06/16/cold-vs-hot-observables.html). This "might" cause this nfinity loop issue on an empty `data` array. The safe bet here would be to remove the `publishReplay(1).refCount();` part, as the original description of what PR #960 fixed was not quite correct (see the PR for the description). Calling `subscribe()` twice on an observable means registering another Observer on that Observable. So the "bug" behaviour was/is not a bug, but rather a misunderstood behaviour (snippet taken from article above): 

![unbenannt](https://cloud.githubusercontent.com/assets/1188033/16804201/e6da72b8-490a-11e6-8a7d-f6196939cd34.PNG)

Greetings

Dope

**Comment by billsworld** [comment]
@TheDonDope I did try removing that part but it wasn't helpful. I have something in the works that might work better. PR on the way.

**Comment by billsworld** [comment]
@mgechev how does this change look? It might be more than necessary, but was the best way I could get things working better.

https://github.com/mgechev/angular2-seed/pull/1123/commits

**Comment by NN77** [comment]
Now data.json is calling every single routing base returning
