### ISSUE TITLE
d3js import module not found

### ISSUE THREAD

**Issue by estradamarkie** [mgechev/angular2-seed#1114]
I've installed d3 using npm install d3 --save and updated my seed-config.ts however when I try to import it to my component it shows "can't find module" but no console error at all. Am I missing something?

Thanks

**Comment by TheDonDope** [comment]
Hi @estradamarkie,

taken from the old issue submit template:

> Before submitting the issue, take a look at the already existing solutions to:
> - [x] `Cannot find module '...'` - your issue is related to not existing type definitions. 

Also: how exactly did you update your `seed.config.ts` ? You do not necessarily need to update it through the `seed.config.ts` but can override it rather in the `project.config.ts` (thus preventing possible merge conflicts for future updates) like this for example:

`project.config.ts`
```TypeScript
...
constructor() {
...
    // Third-party libraries to have their paths configured
    // MomentJS
    (<any>this.SYSTEM_CONFIG_DEV.paths)['moment'] =
      '/node_modules/moment/moment.js';
}
```

You may also take a look at this article here: https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2
