### ISSUE TITLE
Weird error when running  gulp serve.prod?

### ISSUE THREAD

**Issue by lmessinger** [mgechev/angular2-seed#1117]
Hi

switching to prod build, all goes great until buildhtml_css, where I get (at the very end, even after .pipe(gulp.dest(CSS_DEST)) (based on .on('end' logging)
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: /home/liorm/devcode/servo-admin/src/client/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:14:1: Unknown word

//# sourceMappingURL=map-file-comment.css.map
^

any ideas??

thank so much for any clue
Lior

**Comment by mgechev** [comment]
PostCSS complains about invalid CSS syntax. [This is the valid syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Comments) for adding comments in CSS.
