### ISSUE TITLE
Trying to import import 'ag-grid-enterprise/main'; but showing me an error

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#1118]
Hi Guys,

Can anyone give me an insight why I am trying to add the ag-grid-enterprise in one of my components and is showing me the following error (I am using the angular-2-seed-project):

TypeError: main_1.QuerySelector is not a function(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

My code is: 

```
import { Component, OnInit } from '@angular/core';
import {AgGridNg2} from 'ag-grid-ng2/main';
import {GridOptions} from 'ag-grid/main';
import 'ag-grid-enterprise/main';

```

Thank for any help

Kind Regards

**Comment by TheDonDope** [comment]
Hi @simoazzo,

have you installed the corresponding typings for ag-grid-enterprise, or provided manual typings for them?

**Comment by simoazzo** [comment]
I have followed the instructions by the ag-grid-enterprise.

What do you mean manual typings? can you please give me an example?

**Comment by mgechev** [comment]
@simoazzo most of the imports from your snippet above are unnecessary. [As the guide of `ag-grid-enterprise` states](https://www.ag-grid.com/best-angular-2-data-grid/index.php), for Angular 2 you need:

```bash
"dependencies": {
    ...
    "ag-grid": "5.0.x",
    "ag-grid-ng2": "5.0.x"
}
```

after that:

```ts
import {AgGridNg2} from 'ag-grid-ng2/main';
//...
@Component({
    directives: [AgGridNg2],
    ...
})
```
