### ISSUE TITLE
build.prod run locally? system is trying to get c:/js/app.js

### ISSUE THREAD

**Issue by davidgfolch** [mgechev/angular2-seed#1119]
Hi all,

npm run build.prod OK

When I access via firefox to the created local file: file:///C:/.../demo-xf-angular2/dist/prod/index.html

I can only see "Loading...", cause injected js are not loading cause of base href="/" and:

```
  <script src="/js/shims.js?1468495405482"></script>
  <script src="/js/app.js?1468495405485"></script>
```

Is this expected to run like that or we need an apache installed locally?

**Comment by davidgfolch** [comment]
I've fixed that manually removing from index.html base href & first / on the scripts, and app loads.
But I have a:
`shims.js?1468495405482:4 XMLHttpRequest cannot load file:///C:/.../demo-xf-angular2/dist/prod/assets/i18n/ES.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Comment by TheDonDope** [comment]
Hi @davidgfolch, 

If you want to run a local prod build and serve it, you can either:

A) `$ npm run serve.prod` 

or 

B) `$ npm run build.prod && http-server dist/prod` (if you have the npm package `http-server` installed (`$ npm install -g http-server`)

Greetings

Dope
