### ISSUE TITLE
(index):94 Error: SyntaxError: Unexpected token < in JSON at position 0(…)

### ISSUE THREAD

**Issue by mthor** [mgechev/angular2-seed#1120]
This error happens with the base app that I cloned, I clone the app, run npm install, then npm start. the first time the page loads fine, but if I make anychange, including just a space and hit save, I get the error 

(index):94 Error: SyntaxError: Unexpected token < in JSON at position 0(…)

**Comment by TheDonDope** [comment]
Hi @mthor,

> if I make anychange, including just a space and hit save

Where do you make a change? To some file under `src/` `? To a HTML file? To a CSS file? Can you provide some specific steps to reproduce?

Also: 
> (index):94 Error: SyntaxError: Unexpected token < in JSON at position 0(…)
Is this the complete error message? If there is a longer stacktrace please include it.

Greetings

Dope

**Comment by mthor** [comment]
an example, is I create a folder in the shared folder named "events"  then I add a index.ts  if I do this while npm start is running after I add the .ts file the browser refreshes with the error above. 

(index):75 Error: SyntaxError: Unexpected token < in JSON at position 0(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ (index):75ZoneDelegate.invoke @ zone.js?1468519665105:323Zone.run @ zone.js?1468519665105:216(anonymous function) @ zone.js?1468519665105:571ZoneDelegate.invokeTask @ zone.js?1468519665105:356Zone.runTask @ zone.js?1468519665105:256drainMicroTaskQueue @ zone.js?1468519665105:474ZoneTask.invoke @ zone.js?1468519665105:426

**Comment by mgechev** [comment]
@mthor on what OS?

**Comment by mthor** [comment]
Thanks for the reply,

I am on osx yosemity

I have all my imports as /index,

to duplicate the error, I can just copy the name-list.service into another folder and change the component name and set the correct path to the index file,  I can check systemjs, but I did take from the latest project pull,

**Comment by mthor** [comment]
this seems to be fixed as of latest pull! thanks
