### ISSUE TITLE
gulp build redirect failure

### ISSUE THREAD

**Issue by Zwoleo** [mgechev/angular2-seed#1124]
When I am running gulp build.prod everything works fine.
Since I started to using gradle, standard task for gradle is gulp build, so I decided to create task:

```
gulp.task('build', (done: any) =>
  runSequence('build.prod',
              done));

```
or task with copied tasks from build.prod

```
gulp.task('build', (done: any) =>
  runSequence('clean.prod',
              'tslint',
              'css-lint',
              'build.assets.prod',
              'build.html_css',
              'copy.js.prod',
              'build.js.prod',
              'build.bundles',
              'build.bundles.app',
              'build.index.prod',
              done));

```
When I am trying to run gulp build it fails on:

```
[15:13:50] Starting 'build.js.prod'...
[15:13:51] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open 'C:\PROJEKTY\test\dist\tmp\app\xxx.css'
Details:
    errno: -4058
    code: ENOENT
    syscall: open
    path: xxx
    fileName: xxx
```

I can't understand that, it should only redirect it to another working tasks.

Important in this case is that dist/tmp includes only .ts files. There is no css/jss files. Because error fails on css and js files. Second fact is that after it fails. In dist I see only dev and tmp folder. Where is prod folder?
When I changed
`DEV_DEST =${this.DIST_DIR}/xyz;`
task generate files in folder xyz. So in someway it using dev variables, but chaning dev dist to prod directory still not fix the errors.

I can't understand why using "gulp build" use only DEV variables ?

EDIT:
Ok so even renaming task build.prod to xyz 
Destroys task...
Configuration is passed by name of gulp task ?????

**Comment by mgechev** [comment]
You need to explicitly set the environment if you change the task name. Try the following:

1. Make a clean clone of the seed.
2. Change the `build.prod` task to `build` (as you aim to do).
3. Run `gulp build --env prod`.
