### ISSUE TITLE
CI silent errors

### ISSUE THREAD

**Issue by jarnstedt** [mgechev/angular2-seed#1125]
The CI is throwing errors without failing: `ERROR: Error{stack: null, originalErr: SyntaxError{}}`. It seems to happen in all environments. Also had the same error happening in CircleCI.

See in Travis https://travis-ci.org/mgechev/angular2-seed/jobs/144942094#L368

**Comment by Shyam-Chen** [comment]
This should be `Karma` itself is the problem.

**Comment by nimaen** [comment]
I had the same problem : I resolved it by adding rules to the `test-main.js` in the system config.
You should watch all files from your added modules in the `karma.conf.js` files entry as well.

**Comment by gvsdan** [comment]
we didn't remove the tildify.ts and replace it with the d.ts file instead and we had a tildify.js file in our folder we  remove the file and solve the problem thanks
