### ISSUE TITLE
Typings conflict (angular-protractor vs jquery)

### ISSUE THREAD

**Issue by AloeDream** [mgechev/angular2-seed#1126]
Steps to reproduce.
In my case I use signalR library and typings for it, added to typings.json at project root. Signalr uses jquery.
So when trying to use something like in one of my services:
`this.hubConnection = jQuery.hubConnection();`
or this:
`this.hubConnection = $.hubConnection();`

I'm getting error both in editor and during build:
> Subsequent variable declarations must have the same type.  
> Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.

I've tried to reference only signalR .d.ts file in my code, tried using signalR's alternative alias for "$", but during build it fails anyway as it concats everything I guess.

**Expected/desired behavior**
I think test (where angular-protractor belongs, as I understand) should be somehow separated in build process to avoid such conflicts.

[related issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2734](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2734)

**Comment by mgechev** [comment]
You can exclude the protractor's type definition if you pass: `"!PATH_TO_PROTRACTOR_DEF.d.ts"`. Since most likely the protractor's type definition is referenced within `typings/index.d.ts` you'll have to exclude this file as well.

**Comment by vinaychandra** [comment]
@mgechev, I could run with jquery in normal `npm start`. The  issue when running with `gulp test` is that the error is `$ is not defined` rather than pointing to some other thing.

**Comment by ludohenin** [comment]
Have you include a ref to jQuery in `karma.conf` file ?

**Comment by vinaychandra** [comment]
Yes. Also, there are no 404 errors on console. And $ works on console of karma browser as expected. It just does not work on unit tests 



On Sun, Aug 21, 2016 at 9:47 PM +0530, "Ludovic HENIN" <notifications@github.com> wrote:












Have you include a ref to jQuery in karma.conf file ?

**Comment by Sn3b** [comment]
Have you tried to change the type of $ from JQueryStatic to cssSelectorHelper in jquery.d.ts from the typings folder?

**Comment by vinaychandra** [comment]
I never have mentioned the type for $. I used any for $. It works fine for normal server but fails for karma 



On Mon, Aug 22, 2016 at 11:19 AM +0530, "Sebastien de Salvador" <notifications@github.com> wrote:












Have you tried to change the type of $ from JQueryStatic to cssSelectorHelper in jquery.d.ts from the typings folder?

**Comment by Sn3b** [comment]
I'm talking about the typing file you downloaded from definitely typed, it mentions that $ is of type JQueryStatic. Try to change the type to cssSelectorHelper.

The only problem is that whenever you run npm install it'll re-download the typings file for jquery and will reset this...

**Comment by Sn3b** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L3239-L3240

**Comment by vinaychandra** [comment]
@Sn3b, I did not use the d.ts file for jQuery. I circumvented the file requirement by using the alternative `declare var $: any`. This would make typescript accept $ as any variable and thus eliminating the variable.

**Comment by ashblue** [comment]
Overriding the `$` variable to circumvent typings really doesn't solve the issue at hand. See #1645 for my findings on the issue with a potential / possible solution.
