### ISSUE TITLE
(feature request) Uncss support

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#1128]
I just found out about uncss. Is there already support for it and if not, is it something that would work with angular2 and should it be added to the seed? Thanks :smile:

**Comment by mgechev** [comment]
I'm not sure if uncss is going to play well with Angular. The CSS selectors used in the style sheets are being modified because of the view encapsulation.

**Comment by sfabriece** [comment]
I thought so. Thanks.
