### ISSUE TITLE
Used rules in tslint.json

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#113]
I added this on PR #109 with following modifications:

Original
```
"quotemark": [true, "double"],
"sort-object-literal-keys": true,
```

Modified
```
"quotemark": [true, "single"],
"sort-object-literal-keys": false,
```

@mgechev suggested that we open new issue and discuss about these rules.

**Comment by mgechev** [comment]
I added some comments here https://github.com/mgechev/angular2-seed/pull/109/files

Great job in developing the gulp task! I'd want to make the `tslint.json` config not too opinionated. My idea is to provide a generic `tslint.json`, which includes only a few rules, which are generally considered as best practices.

Here's my suggestion:

```json
{
  "rules": {
    "class-name": true,
    "curly": true,
    "eofline": true,
    "indent": "spaces",
    "max-line-length": [true, 140],
    "member-ordering": [true,
      "public-before-private",
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-construct": true,
    "no-duplicate-key": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-eval": true,
    "no-trailing-comma": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "no-unreachable": true,
    "no-use-before-declare": true,
    "one-line": [true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [true, "single"],
    "semicolon": true,
    "triple-equals": true,
    "variable-name": false
  }
}
```

// cc: @ludohenin @NathanWalker

**Comment by tarlepp** [comment]
Yeah, for the note, I just copied that tslint.json file from tslint repository and made only those two little changes to it.

**Comment by ludohenin** [comment]
One thing we could do is to provide a basic foundation as suggested by @mgechev and provide another empty tslint.json file (for customization) inside the tools folder that we extend with the default one.
We could also do the same for jshint.
this way we have a seamless integration of customize config.

**Comment by mgechev** [comment]
Or we can stick to TypeScript and use it for gulp as well. This way we won't need jshint as dependency.

**Comment by ludohenin** [comment]
yep, make sense
