### ISSUE TITLE
Example of async routes

### ISSUE THREAD

**Issue by francesco-strazzullo** [mgechev/angular2-seed#1133]
It could be useful to have an example of an async loading route. Something like this starter. https://github.com/AngularClass/angular2-webpack-starter

Thanks!

**Comment by TheDonDope** [comment]
Hi @francesco-strazzullo,

actually we already do have examples for that. The components in the subfolders `+home` (https://github.com/mgechev/angular2-seed/tree/master/src/client/app/%2Babout)  and `+about` (https://github.com/mgechev/angular2-seed/tree/master/src/client/app/%2Bhome)  are async components with their own respective route files (https://github.com/mgechev/angular2-seed/blob/master/src/client/app/%2Bhome/home.routes.ts & https://github.com/mgechev/angular2-seed/blob/master/src/client/app/%2Babout/about.routes.ts ).

Greetings

Dope
