### ISSUE TITLE
app base not working

### ISSUE THREAD

**Issue by zwolej** [mgechev/angular2-seed#1134]
Hello,
I am on fresh seed version and when I am setting some custom APP_BASE

`  APP_BASE = argv['base'] || (this.ENV === ENVIRONMENTS.DEVELOPMENT ? '/api/' : '/api/');`

Application seems to not work properly. There are problem with finding example json file from assets folder.

**Comment by TheDonDope** [comment]
Paging @jvitor83 (because of #1122) & @rodolfocop (because of https://github.com/mgechev/angular2-seed/pull/1122#discussion_r70965095)  : Could you have a look at this?

**Comment by rodolfocop** [comment]
Hi, I think not explained properly about the use of it.

When using subdomains, the only variable should be changed to '/ api /' when using the command build.dev

APP_BASE = argv['base'] || (this.ENV === ENVIRONMENTS.DEVELOPMENT ? '/api/' : '');

There is no need to put the command to the build.pod.

See you

**Comment by jvitor83** [comment]
@zwolej Our modification doesn't change the behavior, but only set the default for the environment.
I doens't see the need to change the default args on the seed.config (like you make).
You can try to put the `npm run build.prod -- --base=/api/` if you need to, or only use the **`npm run build.prod`** without the base parameter (this are working for us).

Basically, you keep the base arg the way it are on the seed:
`APP_BASE = argv['base'] || (this.ENV === ENVIRONMENTS.DEVELOPMENT ? '/' : '');`
And build without passing the base arg:
`npm run build.prod` or `npm start`

@zwolej, Tell me if it works this way for you.

**Comment by TheDonDope** [comment]
@jvitor83 one question though: 
> Our modification doesn't change the behavior, but only set the default for the environment.

Before the change the `APP_BASE` was **always** set to `'/'`, regardless of the environment.
However now, it will only be set to `'/'` if the environment is `DEVELOPMENT`. (because of the `: ''` part at the end). So doesn't that mean, that for every other environment, that is **not** `DEVELOPMENT`, the `APP_BASE` will not be set? And therefore, it would be different to the behaviour before (having set `APP_BASE` to `'/'` **always**) ?

Sorry for the confusion :)

**Comment by jvitor83** [comment]
@TheDonDope sorry. The behavior is changed, but what i mean is that before the change, the build.prod whas not getting the right path to be "independent from where to host", if subsite or not.
This change enable the build.prod to not only work on "www.site.com" but "www.site.com/subsite" without break the path to the assets.

Actually, you can create a subsite on the web server and put the files there "www.site.com/subsite" 
OR 
you can build.prod with the base argument like `npm run build.prod -- --base=/subsite/` and put the files in the base site "www.site.com" and the result should be the "www.site.com/subsite" working too.

Both scenarios should work.

_Anyway, you still can change the default like before if needed to (but i don't see the need for this anymore)._

Sorry if i wasn't too clear about the change.

**Comment by Sjiep** [comment]
I just recently merged the latest changes from the seed into our project. The fact that the `base` tag wasn't set to `/` anymore actually 'broke' our `build.prod`. Files like `app.js` and `shims.js` where requested from the wrong location once routes did not get loaded from the `base` anymore (so `www.site.com` would work fine, but with `www.site.com/subsite` the `app.js` file would be loaded from `subsite/app.js`).

Looking at the [Angular 2 Route docs](https://angular.io/docs/ts/latest/guide/router.html#!#base-href), I would say the default value should not be empty, but at least a `/`.

I'm not sure what the most common scenario, but in our case, we have to change the default empty value.
