### ISSUE TITLE
Exception on build when there's a comment in tslint.json

### ISSUE THREAD

**Issue by AloeDream** [mgechev/angular2-seed#1135]
**Steps to reproduce and a minimal demo of the problem**
Just put a comment for any custom rule and try run build task.

**Current behavior**
> SyntaxError: C:\Users\Sergey\Source\Repos\RubezhGlobal\Projects\GkWebUI\tslint.json: Unexpected token / in JSON at position 5820
>     at Object.parse (native)
>     at Object.Module._extensions..json (module.js:558:27)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at customRules (../../../tools/config/seed.config.ts:532:18)
>     at ProjectConfig.SeedConfig (../../../tools/config/seed.config.ts:252:21)
>     at new ProjectConfig (../../../tools/config/project.config.ts:14:5)

**Expected/desired behavior**
No exception even if comments exists in tslint.json

**Other information**
I guess something should be fixed in this function inside seed.config.ts:
`/**
 * Returns the linting configuration to be used for `codelyzer`.
 * @return {string[]} The list of linting rules.
 */
function customRules(): string[] {
  var lintConf = require('../../tslint.json');
  return lintConf.rulesDirectory;
}`

**Comment by TheDonDope** [comment]
Actually, there is no way to put comments in JSON files with `/** */` or `/* */`.
See here: http://stackoverflow.com/questions/244777/can-i-use-comments-inside-a-json-file

So the only way to work around is would be to actually delete the lines you do not want to use.
