### ISSUE TITLE
coverage reports broken (remap-istanbul)?

### ISSUE THREAD

**Issue by njs50** [mgechev/angular2-seed#1136]
there appears to be an error when running remap-istanbul which appears to be related to the inline sourcemaps.

to repro (running vs current master branch):

```npm run serve.coverage```

result:

```
> remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color

/Users/njs50/edc/angular2-seed/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:210
            text = structuredText[startLine].text;
                                            ^

TypeError: Cannot read property 'text' of undefined
    at /Users/njs50/edc/angular2-seed/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:210:45
    at Array.forEach (native)
    at annotateStatements (/Users/njs50/edc/angular2-seed/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:193:33)
```

possibly an issue with the inline sourcemaps in the dist/dev/*.js files?

**Comment by TheDonDope** [comment]
Hi @njs50,
this problem is sticking around for quite a while now, but there is a workaround for it:

**Comment by TheDonDope** [comment]
Closing as it is a duplication of #844 as well as an upstream issue, not directly seed related.

**Comment by njs50** [comment]
hrm, that sounds more like a problem in the `npm run test` task than something upstream if rebuilding fixes it (which it does). Is it that the test task instrumentation is causing the issues with sourcemaps, which the rebuilding then fixes? perhaps the sourcemaps are generated prior to instrumentation (which would then break them)?

**Comment by TheDonDope** [comment]
Hey @njs50, you are right, sorry, i have misformulated that sentence. For more details take a look at the conversation in #844, we already talked a bit about it there. Alas, so far there has not been done anything about it.

**Comment by njs50** [comment]
There should probably be an open issue in that case, as it appears to be a seed configuration issue and not an upstream issue.
