### ISSUE TITLE
Get seed APP_BASE programatically

### ISSUE THREAD

**Issue by davidgfolch** [mgechev/angular2-seed#1138]
How can I get APP_BASE in runtime?
I'm trying do do something like that (I needed for a viewSourceComponent)

  public APP_PATH='<%= APP_BASE %>'; //gives me http://uiexamples/components/messages/Messages.ts

I've also tried with 
import { APP_BASE_HREF } from '@angular/common';

**Comment by mgechev** [comment]
You have to inject `APP_BASE_HREF`:

```ts
...
constructor(@Inject(APP_BASE_HREF) path: string) {
  ...
}
...
```

**Comment by davidgfolch** [comment]
Thank you!
