### ISSUE TITLE
zip compression during prod deployment

### ISSUE THREAD

**Issue by tpruthi** [mgechev/angular2-seed#1140]
Is there any way to add gulp-zip task in the list of build.prod task, so the files generated in dist/prod
will be zipped and the zip file can be deployed directly to nginx or any other server.

**Comment by TheDonDope** [comment]
We _kind of_ have this, but not actually for building the artifacts, but at runtime, when using `npm run serve.prod` , see here: #1092

**Comment by mgechev** [comment]
@tpruthi usually your web server is the one which performs the compression. In case of some compression algorithms it can be based on the browser which did the request.
