### ISSUE TITLE
shadow dom sourcemaps

### ISSUE THREAD

**Issue by levidobson** [mgechev/angular2-seed#1141]
Hi,
Is it possible to show line numbers in Chrome dev toolbar that correspond to the original component css/scss file? All it shows is "style" indicating its an inline style, but no line numbers are present.

I tried both emulated and native view encapsulation, and scss transpilation with both inline and external sourcemaps with no avail. I am beginning to think it's a Chrome + shadow dom problem, but maybe a proper configuration exists in the universe that would bring me well deserved source line numbers for my component css stylesheets.
Thx!

**Comment by mgechev** [comment]
There is nothing we can do at the moment https://github.com/angular/angular/issues/9664.

**Comment by asl-dave** [comment]
I am running into the same issues as @levidobson, and it looks like angular/angular#9664 was fixed and folded into 2.0.0-rc6. Has anyone been able to get source maps working in Angular2 component styles?

**Comment by Marc-Hansen** [comment]
is this working for anybody still? cant get source maps from component styles to work
