### ISSUE TITLE
Node module dependency on a JSON file fails

### ISSUE THREAD

**Issue by omargon** [mgechev/angular2-seed#1144]
I'm not sure if it is a seed configuration or not but I'm trying to use the moment-timezone package and when I import it as:

```
import * as moment from 'moment-timezone';
```

And then run my app I get the following error:

```
GET /node_modules/moment-timezone/data/packed/latest.json.js 404 (Not Found)
```

The get request is adding a .js ad the end of the `latest.json` file which does exist at that location.

If I remove the package import I then get the following typescript error:

```
error TS2349: Cannot invoke an expression whose type lacks a call signature.
```

If this is not a seed configuration issue I will gladly close or delete this ticket.

**Comment by mgechev** [comment]
You need to reconfigure SystemJS and do not allow `js` extension for `/node_modules/moment-timezone/data/packed/latest.json`. You can take a look at [SystemJS docs](https://github.com/systemjs/systemjs) for further information.

**Comment by doapp-ryanp** [comment]
@omargon did you ever figure this one out?  Per the [SystemJS Docs](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use)

> Note that if using the defaultJSExtensions compatibility feature, plugins for resources with custom extensions will only work by using the package configuration defaultExtension: false option to override this for specific packages.

So in theory adding the following to `project.config.ts` should work but it is not:

```javascript
this.SYSTEM_BUILDER_CONFIG.packages['moment-timezone'] = {
  defaultExtension: false``
};
```

@mgechev any idea what I'm missing here?

**Comment by mgechev** [comment]
You can disable the `defaultJSExtensions` for this [package](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages).

**Comment by doapp-ryanp** [comment]
@mgechev isn't that what I did above in my example? `defaultExtension` option on the package per the docs is the way to disable `defaultJSExtensions` for the `moment-timezone` package as far as I can tell.

**Comment by doapp-ryanp** [comment]
So I got it sort-of working.

If I put `import * as moment from 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js';` in my component and the following in `project.config.ts`

```javascript
this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'moment', inject: 'libs'},
      {src: 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];
```

This allows me to use moment-timezone methods and member vars, however I get this error from my component on the import:

```
error TS2307: Cannot find module 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js'.
```

I'm pretty sure I know how to fix this, however any modifications/additions I make to [`seed.config.ts::SYSTEM_BUILDER_CONFIG.packages`](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L391) are not taking effect

Is `SYSTEM_BUILDER_CONFIG.packages` even used in development? I can make one of the well known objects incorrect and app still works fine.  Ex I put in an invalid `main` for `@angular/router`:

```javascript
'@angular/router': {
        main: 'blah.js',
        defaultExtension: 'js'
      },
```

I think the true fix is to configure SystemJS with the following, however I cant get angular2-seed to pass it along

```
//import * as moment from 'moment-timezone'; in component
'moment-timezone': {
  main: 'builds/moment-timezone-with-data-2010-2020.min.js',
  defaultExtension: 'js'
}
```

**Comment by doapp-ryanp** [comment]
I figured it out.  For others that run into this issue here is how you fix:

`npm install moment moment-timezone --save` and `npm install @types/moment @types/moment-timezone --save-dev`

In my component I do `import * as moment from 'moment-timezone';`.

In `project.config.ts` I do:

```javascript
...
 constructor() {
 
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'moment', inject: 'libs'},
      {src: 'moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js', inject: 'libs'},
    ];

...
    const mtzc = {
      main: 'builds/moment-timezone-with-data-2010-2020.min.js',
      defaultExtension: 'js'
    };

    this.SYSTEM_BUILDER_CONFIG.packages['moment-timezone'] = mtzc;
    this.SYSTEM_CONFIG_DEV.packages['moment-timezone'] = mtzc;
  }
```

I can then use `console.log(moment.tz.guess());`

@mgechev I'm guessing `SYSTEM_BUILDER_CONFIG` is used when doing production builds? So it is necessary to duplicate the SystemJS configuration in `SYSTEM_BUILDER_CONFIG` and `SYSTEM_CONFIG_DEV` correct?

**Comment by mgechev** [comment]
I tried to get rid of one of the configurations in the past and I'm willing to do so in future but at this point we cannot cover all usage scenarios with only a single one.
