### ISSUE TITLE
How to enable hot loader?

### ISSUE THREAD

**Issue by mazoni** [mgechev/angular2-seed#1147]
Hello everyone,
you have made a great job creating this seed. It's really useful.

How do I enable the hot loader? I've uncommented the hot_loader_main.ts and I'm running with --hot-loader flag. But the app never starts with the hot loader port and whenever I edit a file I get a:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

on the file: http://localhost:5555/app/main.js

Thank you.

**Comment by mgechev** [comment]
The hot loader is disabled because it is not up-to-date.

**Comment by mazoni** [comment]
@mgechev, do you cancel and run the server on every change?  Do you think if I follow these steps: https://github.com/mgechev/angular2-hot-loader , I'll be able to get it running?
