### ISSUE TITLE
Sourcemaps for CSS

### ISSUE THREAD

**Issue by smartm0use** [mgechev/angular2-seed#1149]
Hello, i created my first Angular2 app and i would get sourcemaps for CSS. Here is an example of Component:

```
import {Component} from '@angular/core';

@Component({
    moduleId: module.id,
    selector: 'home',
    templateUrl: 'home.component.html',
    styleUrls: ['home.component.css']
})

export class HomeComponent {
}
```

[As far as i know](https://github.com/mgechev/angular2-seed/issues/779) in Angular2 all component CSS code is injected as `<style>` tag and this prevents CSS to be mapped: in Chrome inspector i have no sourcemaps for style files.

So, any idea to map and then debug CSS files in Angular2?

**Comment by mgechev** [comment]
It is duplication of https://github.com/mgechev/angular2-seed/issues/1141.
