### ISSUE TITLE
has alpha.38 move from rx to the reactivex libraries?

### ISSUE THREAD

**Issue by butterfieldcons** [mgechev/angular2-seed#115]
node_modules\angular2\node_modules\rx\

is now 

node_modules\angular2\node_modules\@reactivex  etc....

**Comment by ludohenin** [comment]
yes. This will come once #112 will be merged.

**Comment by hpinsley** [comment]
This sounds like good news. I've been struggling using some Rx features because it seems that that angular has been using a stripped-down version. Does that mean that it's going to start using the RX.all.JS library.  As an example I want to use functions like buffer with time.

**Comment by ludohenin** [comment]
> Does that mean that it's going to start using the RX.all.JS library

I don't know, haven't checked the details yet.
