### ISSUE TITLE
@angular/core.js can't be found!!

### ISSUE THREAD

**Issue by YogenRaii** [mgechev/angular2-seed#1150]
Why I'm getting this error please??
localhost/:69 Error: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/core.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by mgechev** [comment]
You have misconfigured SystemJS. Take a look at `tools/config/seed.config.ts` for proper configuration.
