### ISSUE TITLE
(feature request) load configuration from .env

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#1153]
I'm working in a team where we are finding the loading of configuration, specifically the `API host` to be cumbersome. 
I would like to propose adding an option to load some configurations from a .env file which is gitignored.
If it is not present then we load them from the config.json and so on.

Any thoughts?

**Comment by mgechev** [comment]
Yes, this makes sense. It can be implemented in a similar fashion but except using `./tools/env` we can look for `*.env` files in the root of the projects and/or in `./tools/env`.

In such case I don't see a point to keep the JSON configuration.

**Comment by mgechev** [comment]
Thinking about this further, I'm not sure `*.env` is the best option. By having:

```
/tools
  /config
    base.config.js
    env1.config.js
    env2.config.js
```

You get the following:

- You can have a base configuration which contains the entire config common for `env1` and `env2`.
- You can use comments in your configuration.
- You can include custom logic (including reading `*.env` files from root).

Later today I'll open a PR which implements this functionality.

**Comment by sfabriece** [comment]
will the files in `/env` be `gitignored` besides base.config.js ?
Because of the problem of multi teams working on the same code base.

**Comment by mgechev** [comment]
You can add the files to `.gitignore` in your version of the seed, I'm sure there won't be any merge conflicts when you update since we barely change this file upstream.

**Comment by sfabriece** [comment]
ok, thanks :)
