### ISSUE TITLE
External dependencies and Karma

### ISSUE THREAD

**Issue by reflog** [mgechev/angular2-seed#1155]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

npm install -S openlayers

Added mapping according to https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

_What steps should we try in your demo to see the problem?_

**Current behavior**

npm run test fails with 404, cannot find '/base/node_modules/openlayers'

**Expected/desired behavior**

**Other information**

Any suggestions or a more detailed example (except for angular-jwt) on how to add 3rd party libraries?

Thank you!

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
