### ISSUE TITLE
Multiple Projects in a Single Seed

### ISSUE THREAD

**Issue by mko** [mgechev/angular2-seed#1157]
It appears that `gulp-typescript` requires (as of `v2.13.6`) a new TS Project file created for each running build task, as opposed to the intent which is for the TS Project file to be reused to reduce compilation time ( https://github.com/ivogabe/gulp-typescript/issues/307#issuecomment-226237437 ). For most users, that means the current setup of `angular2-seed` is perfectly fine, as they're only building and rebuilding a single application. Unfortunately, if you are building and rebuilding a complex suite of applications with a single seed (or an Angular2 library and a demo app using the library), this becomes an issue very fast.

I found a workaround by disabling `gulp-cached` in the build steps and moving the TS Project creation into the task itself ( https://github.com/ivogabe/gulp-typescript/issues/342#issuecomment-235044823 ).

There's a few things to unpack here:

1. For the `angular2-seed`, is there any intention of having "out of the box" support for multiple projects in a single seed? **I feel like this is a non-trivial decision, but I think having support for multiple projects in a single seed is a very valuable and useful feature.** 
2. By utilizing `gulp-cached` in the TypeScript compilation task for caching TS Project, we're triggering an error in which `gulp-typescript` can't recompile changes to the watched files, thus making incremental builds problematic. _Note: I have seen reports of this problem affecting non-complex seed project builds as well, but they're seem less likely to occur._ **I love `gulp-cached` but I think it would be valuable to identify somewhere to the users of the `angular2-seed` what files get cached and why.**
3. Is there any value in adding some sort of configuration value like `TSPROJECT_CACHING = argv['tsprojcache'] || true;` where we can allow the user at runtime or in their project config to override the use of TSProject Caching but leaving in place the current caching for existing seed users? **I'd be happy to put together a pull request to implement this if people think it would be valuable.**

**Comment by ivogabe** [comment]
Author of gulp-typescript here. I would advise to not use gulp-cached with gulp-typescript. TypeScript already has incremental compilation, which is supported by gulp-typescript too. gulp-cached can actually prevent this incremental compilation, and it can be dangerous in certain situations. The emit of an unchanged file can change when some other file does change, and type checking of files depends on other files too. So, I'd advise to call `createProject` outside of the compilation tasks (create one for each task) and drop gulp-cached for TypeScript compilation. If this is too slow, you can use `isolatedModules` to get very fast and safe (incremental) compilation, though I'm not sure whether that works with Angular and decorator metadata.

**Comment by mko** [comment]
@ivogabe: Thanks for the input!

**Comment by mgechev** [comment]
Hey @mko! This issue aims to solve similar problem https://github.com/mgechev/angular2-seed/issues/913.

@d3viant0ne and @NathanWalker were working on it but experienced some issues with the SystemJS configuration. AFAIK @NathanWalker builds multiple projects for multiple platforms in his [advanced seed](https://github.com/NathanWalker/angular2-seed-advanced).

It makes sense to drop `gulp-cached` as @ivogabe mentioned. Here are other strategies for speeding the build up https://github.com/mgechev/angular2-seed/wiki/Speeding-the-build-up.

**Comment by mgechev** [comment]
Closing it due to lack of activity.
