### ISSUE TITLE
CRUD-Tasks with Rest-Backend

### ISSUE THREAD

**Issue by Meistercoach83** [mgechev/angular2-seed#1161]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

Hi,
I´d love to see it, if this project could add routing, controllers etc for an restful backend.
Or can someone tell me how I could do it on my own?

**Steps to reproduce and a minimal demo of the problem**
_What steps should we try in your demo to see the problem?_

**Current behavior**
No Rest-Server in the project

**Expected/desired behavior**
Serving the express app with node.js backend

**Other information**

**Comment by mgechev** [comment]
It is out of the scope of the project to add such functionality, we don't want to be coupled to any specific BE. For express integration you can take a look at [this project](https://github.com/vyakymenko/angular2-seed-express) by @vyakymenko which is based on the angular2-seed.

**Comment by mgechev** [comment]
@Meistercoach83 here's a [demo of using the seed with an express backend](http://thelillysblog.com/2016/11/02/MEAN-stack-with-Angular2/).
