### ISSUE TITLE
ORIGINAL EXCEPTION: No provider for Router!

### ISSUE THREAD

**Issue by neridonk** [mgechev/angular2-seed#1163]
I can't route anymore?

if   I put Router in providers: [Router]

I get an error with "? ? ?..."

I did anything from this tut https://angular.io/docs/ts/latest/guide/router.html 
Im confused by all that deprecating and implementing heeeelp

**Comment by neridonk** [comment]
ok for anyone who else use Router with parameters 
 import the old { ROUTER_PROVIDERS } from '@angular/router-deprecated'; and it works rofl

**Comment by TheDonDope** [comment]
Hi @neridonk,

you are right, your statement imports the old router. However the router was rewritten (again) for rc3 of Angular 2, and now is in Beta. You should check it out and migrate to it: https://angular.io/docs/ts/latest/guide/router.html
