### ISSUE TITLE
Route with parameters and sub routes fail in production

### ISSUE THREAD

**Issue by omargon** [mgechev/angular2-seed#1164]
When requesting a sub route or a route with parameters directly from the browser address bar from a production build by means of `npm run serve.prod` I get the following errors:

```
shims.js:1 Uncaught SyntaxError: Unexpected token <
app.js:1 Uncaught SyntaxError: Unexpected token <
```

One level routes work fine and if I request the sub route and pass parameters while navigating app through route links no issues only when requested via address bar.

It doesn't happen when execute from a development build I don't get any lint or build errors.

Any ideas?

**Comment by PareshMangukiya** [comment]
I am also facing same issue.

**Comment by neridonk** [comment]
+1

**Comment by rathodsanjay** [comment]
+1
On initial investigation, it seems like the issue prevails because it appends a trailing slash ('/') to the URL when requested via the address bar (only in prod build)

**Comment by vyakymenko** [comment]
I fix it 3 days ago :)

Go to `seed.config.ts`:

And change this one:

`APP_BASE`
```js
/**
   * The path for the base of the application at runtime.
   * The default path is based on the environment ('/' for development and '' for production),
   * which can be overriden by the `--base` flag when running `npm start`.
   * @type {string}
   */
  APP_BASE = argv['base'] || (this.ENV === ENVIRONMENTS.DEVELOPMENT ? '/' : '/');
```

**Comment by vyakymenko** [comment]
Will create a pull request with normal fix :D

**Comment by rathodsanjay** [comment]
Great @vyakymenko (Y) 
Just a suggestion

Can't we use: 
`APP_BASE = argv['base'] || '/';`

**Comment by vyakymenko** [comment]
@rathodsanjay , I will create same pull request with `APP_BASE = argv['base'] || '/';`, 3 days ago I was need very fast fix, sorry :D

**Comment by vyakymenko** [comment]
Pr for this one:

https://github.com/mgechev/angular2-seed/pull/1166 :)

**Comment by Shyam-Chen** [comment]
#1166

**Comment by jvitor83** [comment]
@vyakymenko, can you try instead of changing the APP_BASE, just change the `main.web.ts` to use the HashLocationStrategy?

What i mean is, leaving the APP_BASE like this:
`APP_BASE = argv['base'] || (this.ENV === ENVIRONMENTS.DEVELOPMENT ? '/' : '');`
and changing the main.ts to add at bootstrap the provider:
`provide(LocationStrategy, {useClass: HashLocationStrategy})`

Please, let me know the result.

**Comment by vyakymenko** [comment]
@jvitor83 , bad idea. Do you remember about dual hash, sources for files, path security and more... ? Have you tried this one with nav + hash nav ? More problems will be then solutions. So this is a reason why it's better to keep this solution.

**Comment by jvitor83** [comment]
Ok @vyakymenko, i agree with you. My intention was to discover the real problem, not to make this change final.
My problem is to host the app in a subsite like "www.site.com/subsite", there is several ways to get this done, but **my intention is to try make the app "agnostic" about the base address**.
_Forget about the HashLocationStrategy._


Can you try reproduce your problem, with this new way?

Leaving the **APP_BASE** from **seed.config.ts** like this:
```
APP_BASE = argv['base'] || (this.ENV === ENVIRONMENTS.DEVELOPMENT ? '/' : '');
```
and **commenting** lines 19-22 from the **main.ts** like this:
```
//  {
//      provide: APP_BASE_HREF,
//      useValue: '<%= APP_BASE %>'
//  }
```
What i see with this change is that we could build.prod the seed and put the dist/prod files at any host/environment (www.site.com/subsite1/subsite2) and it will work (without any change or rebuild with base arg).
What i cound't reproduce is your problem to see if those modifications solve it or not.
I really apreciate your help on this.
