### ISSUE TITLE
NPM Dependencies are not being injected

### ISSUE THREAD

**Issue by avhetman** [mgechev/angular2-seed#1165]
Go to the project.config.ts file and uncomment the jquery or the lodash. Build and everything is fine (the dependencies are present in the index.html) 

Now install a new package, in my case semantic-ui-css and add it like so:

// Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      {src: 'semantic-ui-css/dist/semantic.min.css', inject: 'css'},
    ];

The path is correct. 
When I build, the new dependancy is not being injected into the index.html. I even tried changing it to:
{src: 'semantic-ui-css/dist/semantic.min.css', inject: 'libs'}
to see if it will get placed into the libs section, and that doesn't happen either.

Any ideas?

**Comment by vyakymenko** [comment]
`semantic-ui-css` is in `node_modules` folder?

Maybe you need `APP_DEPENDENCIES` injection ?

**Comment by avhetman** [comment]
There is no APP_DEPENDENCIES.

**Comment by vyakymenko** [comment]
@avhetman , it must be in `project.config.ts`.

**Comment by avhetman** [comment]
@vyakymenko it is not, here's the project,config.ts: https://github.com/mgechev/angular2-seed/blob/master/tools/config/project.config.ts

**Comment by vyakymenko** [comment]
@avhetman , sorry my typo, I was talked about `APP_ASSETS`.

**Comment by avhetman** [comment]
I tried this, but still no luck:
// Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false},
      // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
      {src: `${this.NPM_BASE}/semantic-ui-css/dist/semantic.min.css`, inject: 'css'}
    ];

**Comment by avhetman** [comment]
By the way, I really appreciate your help @vyakymenko

**Comment by vyakymenko** [comment]
@avhetman , step-by-step configuration:
```sh
# install semantic-ui ( don't forget about steps selecting when installing )
$  npm i semantic-ui jquery --save
```
Then, configure `project.config.ts`:
```ts
...
// Add `NPM` third-party libraries to be injected/bundled.
// Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'semantic-ui/dist/semantic.min.css', inject: true},
      {src: 'semantic-ui/dist/semantic.min.js', inject: 'libs'},
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];
...
```

Test is 2 min ago:
```
Request URL:http://localhost:5555/node_modules/jquery/dist/jquery.min.js?1469733581816
Request URL:http://localhost:5555/node_modules/semantic-ui/dist/semantic.min.css?1469733581820
Request URL:http://localhost:5555/node_modules/semantic-ui/dist/semantic.min.js?1469733581818
```

**Comment by vyakymenko** [comment]
@avhetman , after test, please close issue,

Thanks!

**Comment by avhetman** [comment]
@vyakymenko you are the man! I was having so many problems with 'semantic-ui-css' and I would have much rather used the full library. Thanks so much!
