### ISSUE TITLE
Bundling a lazily loaded NPM package in production mode fails due to ENOENT

### ISSUE THREAD

**Issue by ComFreek** [mgechev/angular2-seed#1168]
**Steps to reproduce and a minimal demo of the problem**

I would like to use an NPM package, which is supposed to be lazily loaded only when a component really needs it. Therefore, I tried tinkering with SYSTEM_BUILDER_CONFIG instead of NPM_DEPENDENCIES since libraries given in the latter one are always injected into index.html.

1. `npm install myPrivatePackage --save` (a private NPM package written in TypeScript)
2. Use this library in various Angular components and services: `import { ... } from 'myPrivatePackage` which gets compiled to `require('myPrivatePackage')`
3. Edit tools\config\project.config.ts:
  ```
import { join } from 'path';
import { SeedConfig } from './seed.config';

export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();

    this.SYSTEM_BUILDER_CONFIG.paths.myPrivatePackage = 'node_modules/myPrivatePackage/dist/index.js';
  }

}
```

4. `npm run build.prod`

**Current behavior**

```
[11:17:45] Starting 'build.bundles.app'...
[11:17:46] 'build.bundles.app' errored after 720 ms
[11:17:46] Error on fetch for myPrivatePackage.js at file:///D:/Desktop/Project/angular2-seed/node_modules/myPrivatePackage.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'D:\Desktop\Project\angular2-seed\node_modules\myPrivatePackage.js'
    at Error (native)
[11:17:46] 'build.prod' errored after 10 s
[11:17:46] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for myPrivatePackage.js at file:///D:/Desktop/Project/angular2-seed/node_modules/myPrivatePackage.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        ENOENT: no such file or directory, open 'D:\Desktop\Project\angular2-seed\node_modules\myPrivatePackage.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'D:\Desktop\Project\angular2-seed\node_modules\myPrivatePackage.js'
Stack:
Error on fetch for myPrivatePackage.js at file:///D:/Desktop/Project/angular2-seed/node_modules/myPrivatePackage.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'D:\Desktop\Project\angular2-seed\node_modules\myPrivatePackage.js'
    at Error (native)

npm ERR! Windows_NT 10.0.10586
npm ERR! node v5.7.0
npm ERR! npm  v3.5.1
/* ... */
```

**Expected/desired behavior**

Why does systemjs-builder still search for `node_modules/myPrivatePackage.js` instead of the specified path in SYSTEM_BUILDER_CONFIG?
It seems that tools/tasks/seed/build.bundles.app.ts directly passes the configuration object to systemjs-builder.

**Comment by TheDonDope** [comment]
Maybe because of this? https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L353

**Comment by TheDonDope** [comment]
In any way: It is not an issue related to the seed per se, but rather your system build config :)

**Comment by ComFreek** [comment]
Thanks for the answer. I tried changing the order to no avail, however, no one should rely on the order anyway as it is undefined for dictionaries.

I've browsed through the examples provided in the README. The one which came closest to my intention was [angular2-seed-example-mashup with Bootstrap as a dependency](
https://github.com/AngularShowcase/angular2-seed-example-mashup/blob/e2b87f36304e637465574badd6c055bc1f7df56a/tools/config.ts#L121), however, adapting the linked line to my path didn't work either (same error).

> In any way: It is not an issue related to the seed per se, but rather your system build config :)

I agree :). I thought it's easier to ask here why the angular2-seed built-in dependencies (i.e. mostly @angular) work contrary to mine.

**Comment by TheDonDope** [comment]
> I tried changing the order to no avail, however, no one should rely on the order anyway as it is undefined for dictionaries.

That was just an assumption that this could be the issue (path order), i did not claim to know it for the truth :) I have no idea how SystemJS/Builder works internally. Maybe it's in the docs?

**Comment by ComFreek** [comment]
Yay, I've finally solved it :)

1. All the changes made in `tools/config/project.config.ts` were for nothing until I realized that neither `gulp build.prod` nor `gulp build.bundles.app` nor `gulp clean.all` clean and re-compile the TS files in `tools/config`!
 -> **You have to force it by running `gulp build.js.tools`.**

2. **The following lines eventually enabled a flawless build:**
 ```
this.SYSTEM_BUILDER_CONFIG.paths['myPrivatePackage'] = `${this.APP_BASE}node_modules/myPrivatePackage/dist/index.js`;
this.SYSTEM_BUILDER_CONFIG.paths['myPrivatePackage/*'] = `${this.APP_BASE}node_modules/myPrivatePackage/dist/*.js`;
```
 Using only the first line led to an error related to a helper file which is included inside `myPrivatePackage/dist/index.js` via `require('./helperFile')` (import in the TypeScript file, respectively):

 ````
[14:10:53] Error tracing myPrivatePackage at file:///node_modules/myPrivatePackage/dist/index.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Error: Unable to calculate canonical name to bundle file:///node_modules/myPrivatePackage/dist/helperFile.js. Ensure that this module sits within the baseURL or a wildcard path config.
    at getCanonicalNamePlain (D:\Desktop\Project\angular2-seed\node_modules\systemjs-builder\lib\utils.js:218:13)
    at getCanonicalName (D:\Desktop\Project\angular2-seed\node_modules\systemjs-builder\lib\utils.js:145:19)
    at D:\Desktop\Project\angular2-seed\node_modules\systemjs-builder\lib\trace.js:482:36
[14:10:53] 'build.prod' errored after 9.73 s
[14:10:53] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error tracing myPrivatePackage at file:///node_modules/myPrivatePackage/dist/index.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Unable to calculate canonical name to bundle file:///node_modules/myPrivatePackage/dist/helperFile.js. Ensure that this module sits within the baseURL or a wildcard path config.
Details:
    originalErr: Error: Unable to calculate canonical name to bundle file:///node_modules/myPrivatePackage/dist/helperFile.js. Ensure that this module sits within the baseURL or a wildcard path config.
Stack:
Error tracing myPrivatePackage at file:///node_modules/myPrivatePackage/dist/index.js
        Loading dist/tmp/app/app.routes.js
        Loading dist/tmp/app/main.js
        Error: Unable to calculate canonical name to bundle file:///node_modules/myPrivatePackage/dist/helperFile.js. Ensure that this module sits within the baseURL or a wildcard path config.
    at getCanonicalNamePlain (D:\Desktop\Project\angular2-seed\node_modules\systemjs-builder\lib\utils.js:218:13)
    at getCanonicalName (D:\Desktop\Project\angular2-seed\node_modules\systemjs-builder\lib\utils.js:145:19)
    at D:\Desktop\Project\angular2-seed\node_modules\systemjs-builder\lib\trace.js:482:36
```

In my opinion, this project would benefit from:

- a hint in the README or wiki that _only_ `gulp build.js.tools` forces a rebuild of the tools directory and
- the two lines of System.js Builder configuration above in the example section.

What do you think?
