### ISSUE TITLE
Migrate to Types from Typings 

### ISSUE THREAD

**Issue by Shyam-Chen** [mgechev/angular2-seed#1172]
Types: https://github.com/types
Typings: https://github.com/typings

**Comment by TheDonDope** [comment]
So, what is the deal about "Types"? Which problem does it solve? Are there specific problems with "Typings" that "Types" solve? Or what is the purpose?

**Comment by mgechev** [comment]
@Shyam-Chen correct me if I'm wrong but, as far as I understand, the organization `types` contains only type definitions, not a tool for managing them (i.e. they still use typings). Also, take a look at [this blog post](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/).
