### ISSUE TITLE
Wrong path for CSS injection

### ISSUE THREAD

**Issue by carol-braileanu** [mgechev/angular2-seed#1173]
I downloaded the project and built it, and right out of the box the main.css file is included with the wrong path.

Build the project and in index.html you will find: 
```
  <!-- inject:css -->
  <link rel="stylesheet" href="/dist/dev/css/main.css?1470054810731">
  <!-- endinject -->
```

The desired path should be:
```
  <!-- inject:css -->
  <link rel="stylesheet" href="/css/main.css?1470054810731">
  <!-- endinject -->
```

I tried changing the CSS_DEST variable but it didn't seem to change anything.

**Comment by ludohenin** [comment]
I guess you did a dev build. If so then the path is correct (`/dist/dev/css/main.css`)

**Comment by carol-braileanu** [comment]
The root of the website is the /dev folder, so the path should be relative to that. This way the css file isn't found.

**Comment by ckapilla** [comment]
> The root of the website is the /dev folder
Not so, in the dev environment, the root directory is by default the 'top' folder of the project, i.e, where package.json lives. This is because (one reason at least) the application needs to reference files from the node_modules folder, which lives at the top level. There would be no way to get at them if /dev were the root.  The production build works more like you are expecting, with dist/prod being the root.

**Comment by carol-braileanu** [comment]
I was using the dev folder as the root with node_modules as a virtual directory. It is all working fine except for the css folder. 

I tried to set the root in the main folder and access the site using something like http://localhost/dist/dev, but now routing is messed up and so are plenty other .js references. 

How can i change the include path of the css file for the dev build?

**Comment by ckapilla** [comment]
It sounds like you are trying to run the dev build using an external server? That may be possible, but not worth the effort. Just run "npm start" in the root directory and everything will run correctly out of the 'box'.

**Comment by mgechev** [comment]
@carol-braileanu, @ckapilla has a point here. In development I'd recommend you to use your API by using CORS. You can deploy the production build (which is standalone and doesn't have any dependencies outside `dist/prod`) to any environment.
