### ISSUE TITLE
src/client/tsconfig.json is totally ignored by "gulp tasks" that compiles typescript 

### ISSUE THREAD

**Issue by dmitriyse** [mgechev/angular2-seed#1174]
1) Clone repo
2) Change src/client/tsconcfig.json (for example change module: "system" or even module: "any_string")
3) Perform gulp build.dev
4) Inspect dist/dev/app/main.js and see that it produced the same as with module: "commonjs" option.

As i understand we needs two configs tsconfig.json - for tools and src/client/tsconfig.json for application.

**Comment by mgechev** [comment]
Thanks for the issue! Fixed by https://github.com/mgechev/angular2-seed/pull/1177.

**Comment by dmitriyse** [comment]
Thank you.
