### ISSUE TITLE
Warnings / deprecated during npm install

### ISSUE THREAD

**Issue by Jorg71** [mgechev/angular2-seed#1175]
OS: Win 10
NPM Version: 2.14.7 as demanded in the installation instructions of the angular2-seed
Node Version: v4.4.7

During installation (npm install) I get some warnings:

npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

[...]

> angular2-seed@0.0.0 postinstall C:\Users\jh\Projects\angular2-seed
> typings install && gulp check.versions && npm prune && gulp webdriver

typings WARN deprecated 2016-06-02: "registry:dt/core-js#0.0.0+20160317120654" is deprecated (updated, replaced or removed)

Everything else is fine.

Should I ignore the warnings?

How can I solve this? I'm thankful for all help.

**Comment by mgechev** [comment]
Most of the issues come from gulp. You can ignore them for now.
