### ISSUE TITLE
home:98 Error: (SystemJS) XHR error (404 Not Found) loading /node_modules/@angular/package.json(…)

### ISSUE THREAD

**Issue by drychlik76** [mgechev/angular2-seed#1178]
I used the seed project from this repo https://github.com/AngularShowcase/ng2-bootstrap-sbadmin.  I installed the latest beta release of Angular 2.

  "dependencies": {
    "angular2": "2.0.0-beta.17",
    "bootstrap": "^3.3.6",
    "es6-module-loader": "^0.17.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "0.35.0",
    "font-awesome": "^4.6.1",
    "moment": "^2.12.0",
    "ng2-bootstrap": "1.0.24",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "~0.19.25",
    "zone.js": "^0.6.10"
  }

The install went fine, but now I am getting an error with a library dependency @angular.  @angular has items I need for developing the routers required by our application.

I am now getting this error.  home:98 Error: (SystemJS) XHR error (404 Not Found) loading /node_modules/@angular/package.json(…)

I tried hacking around with seed.config.ts but reverted back to the original copy.  After several hours of trying to resolve these library dependency issues, I decided to post a bug report.  

Thanks so much for your assistance.

**Comment by mgechev** [comment]
https://github.com/AngularShowcase/ng2-bootstrap-sbadmin is not up to date. Use the angular2-seed from https://github.com/mgechev/angular2-seed.
