### ISSUE TITLE
Angularfire2: error concerning typings

### ISSUE THREAD

**Issue by Jorg71** [mgechev/angular2-seed#1179]
I want to integrate firebase to angular2-seed. Therefore I'm following the step by step guide in the Wiki: [https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2](url)

I get errors when trying the second step:

2) Install typings for firebase (angular2fire currently relies on the firebase3.d.ts file for typings):

`typings install file:node_modules/angularfire2/firebase3.d.ts --save --global`

I'm in the project directory:

C:\Users\jh\Projects\angular2-seed>typings install file:node_modules/angularfire2/firebase3.d.ts --save --global
typings ERR! message Unable to read typings for "firebase3". You should check the entry paths in "firebase3.d.ts" are up to date
typings ERR! caused by ENOENT: no such file or directory, open 'C:\Users\jh\Projects\angular2-seed\node_modules\angularfire2\firebase3.d.ts'

typings ERR! cwd C:\Users\jh\Projects\angular2-seed
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jh\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install" "file:node_modules/angularfire2/firebase3.d.ts" "--save" "--global"
typings ERR! node -v v4.4.7
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

Could you please give me a hint to solve this?

**Comment by mgechev** [comment]
You don't need to install any typings. Take a look at this issue for reference https://github.com/mgechev/angular2-seed/issues/1156.

**Comment by Jorg71** [comment]
I should ignore step 2 in guide [https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2], right?

**Comment by yarnball** [comment]
I agree with Jorg71- this is not clear
