### ISSUE TITLE
TypeScript/map files are not served when running Karma

### ISSUE THREAD

**Issue by cmeredith** [mgechev/angular2-seed#1180]
I'm hoping to get some help here. By default, it seems as though TypeScript files are being served for the specs but not for any of the actual code. This makes debugging tests very difficult. I've looked through the Karma configuration as well as the build scripts and can't seem to pinpoint where I can enable this. Has anyone gotten the TS files to show up in the Karma window?

**Comment by mgechev** [comment]
It'll be fixed once #1232 gets merged.
