### ISSUE TITLE
Integration with AngularFire2: error TS2307: Cannot find module 'angularfire2'.

### ISSUE THREAD

**Issue by Jorg71** [mgechev/angular2-seed#1181]
I'm following the guide "Integration with AngularFire2" https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2.

Step 1: OK
Step 2: I ignored step 2, because of #1179 
Step 3: OK
If I do "npm start" after step 3, there are no errors
Step 4: not OK

**Details to step 4**
I've put the line

`import { FIREBASE_PROVIDERS, defaultFirebase } from 'angularfire2';`

on top of (= as the first line in) file project.config.ts

I also modified "bootstrap(AppComponent,[...]" in the same file as follows:

```
bootstrap(AppComponent, [
  FIREBASE_PROVIDERS,
  defaultFirebase({
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxx',
    authDomain: 'xxxxxxxxxxxx.firebaseapp.com',
    databaseURL: 'https://xxxxxxxxxxxx.firebaseio.com',
    storageBucket: 'xxxxxxxxxxxx.appspot.com',
  }),
  disableDeprecatedForms(),
  provideForms(),
  APP_ROUTER_PROVIDERS,
  {
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  }

]);
```

My editor is "Visual Studio Code". "angularfire2" is underlined red. The editor says:

> [ts] 
> Cannot find module 'angularfire2'.

If I do

`npm start`

I get an error:

> src\client\app\main.ts(1,53): error TS2307: Cannot find module 'angularfire2'.

**Comment by mgechev** [comment]
Here's [branch with the integration](https://github.com/mgechev/angular2-seed/tree/angularfire2). You can take a look [at the diff](https://github.com/mgechev/angular2-seed/commit/384036d8cfd7fed3a4b924ee41ddc0acb3c6d783).

**Comment by Jorg71** [comment]
Thanks a lot, Minko.

Do you plan to keep this branch actual? I saw you made changes in the
master files.

Jorg

---

Mit freundlichen Grüßen / Best Regards

Jörg Hartgen

Müllergäßchen 5
87600 Kaufbeuren

Germany

Tel.: +49 (0)8341 – 96 17 607
Fax: +49 (0)8341 – 96 17 601

Email: joerg.hartgen@googlemail.com

2016-08-03 14:42 GMT+02:00 Minko Gechev <notifications@github.com>:

**Comment by mgechev** [comment]
You can: git remote add upstream https://github.com/mgechev/angular2-seed && git pull upstream master.
