### ISSUE TITLE
Set default configEnvName depending on the process

### ISSUE THREAD

**Issue by salemdar** [mgechev/angular2-seed#1182]
Currently, both `npm run build.dev` and `npm run build.prod` use `'dev'` as default value for `configEnvName` in `template_locals.ts`. 

Although it is not so critical, it would be really nice if user could set default values for different build process in the `project.config.ts` file. Something like:

```typescript
ENV_CONFIG_NAME_DEFAULTS: any = {
    dev: 'dev',
    prod: 'prod'
}
```

So user won't have to set `config-env` every time s/he runs `npm run build.prod`.

I can send a PR, if you accept the feature.

Best regards,
Samet

**Comment by mgechev** [comment]
Good point! I'll open a PR with a fix.
