### ISSUE TITLE
Protractor tests are broken.

### ISSUE THREAD

**Issue by karel1980** [mgechev/angular2-seed#1185]
Version: 9a8bf12eef0f28d310ecc0e568f6c5235422749e

There seem to be 2 issues really. I suspect both are problems with protractor & co, but I wanted to make sure I'm not missing anything and that I'm not the only one seeing this.

Issue 1: All tests run succesfully, but after that the npm e2e goal errors out. See output below
Issue 2: If you change a test in an attempt to break it, it doesn't fail. E.g. in the about e2e spec, change to toEquals('this should fail'); -> The test still reports green.

± |master ✗| → npm run e2e

> angular2-seed@0.0.0 e2e /Users/karelvervaeke/work/test/angular2-seed
> protractor

[16:53:05] I/direct - Using ChromeDriver directly...
[16:53:05] I/launcher - Running 1 instances of WebDriver
Spec started
Started

  About
    ✓ should have correct feature heading
.
  Home
    ✓ should have an input
.    ✓ should have a list of computer scientists
.    ✓ should add a name to the list using the form
.
  App
    ✓ should have a title
.    ✓ should have <nav>
.    ✓ should have correct nav text for Home
.    ✓ should have correct nav text for About
.
Executed 8 of 8 specs SUCCESS in 0.074 sec.

8 specs, 0 failures
Finished in 0.075 seconds
/Users/karelvervaeke/work/test/angular2-seed/node_modules/protractor/built/exitCodes.js:87
                if (e.message.indexOf(errMsg) !== -1) {
                             ^

TypeError: Cannot read property 'indexOf' of undefined
    at Function.ErrorHandler.isError (/Users/karelvervaeke/work/test/angular2-seed/node_modules/protractor/built/exitCodes.js:87:30)
    at Function.ErrorHandler.parseError (/Users/karelvervaeke/work/test/angular2-seed/node_modules/protractor/built/exitCodes.js:98:26)
    at process.<anonymous> (/Users/karelvervaeke/work/test/angular2-seed/node_modules/protractor/built/launcher.js:169:54)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process.emit (/Users/karelvervaeke/work/test/angular2-seed/node_modules/source-map-support/source-map-support.js:419:21)
    at process._fatalException (node.js:236:26)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/karelvervaeke/.nvm/versions/node/v5.10.1/bin/node" "/Users/karelvervaeke/.nvm/versions/node/v5.10.1/bin/npm" "run" "e2e"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 e2e: `protractor`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 e2e script 'protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/karelvervaeke/work/test/angular2-seed/npm-debug.log

**Comment by fvandangeon** [comment]
Hello, 
I confirm the "Issue 2" you mentioned on version f0b496f6
All tests passes successfully even though a test is suppose to failed (wrong text in about header).
But if you put an "expect(true).toBe(false)", it fails as expected.
I suspect an issue within protractor ControlFlow ...  

NB: I used FireFox webdriver instead of Chrome one, there is no "indexof" error  with it.

**Comment by fvandangeon** [comment]
I've downgrade protractor from v4.0.0 to v3.3.0 and the issue is gone.

**Comment by karel1980** [comment]
I haven't had an opportunity to test this throughly, but I think e2e tests can be fixed without downgrading if you replace useAllAngular2AppRoots: true with rootElement: 'sd-app' in protractor.conf.js

**Comment by vinaychandra** [comment]
@karel1980, your solution did not work for me. I am receiving the same error

**Comment by karel1980** [comment]
Doesn't work for me anymore either. Weird. I'll have to sit down and figure
out what changed since last time. Will probably not be today tho.

Karel

**Comment by karel1980** [comment]
@vinaychandra Please ignore all my previous suggestions to a solution.
Downgrading to protractor 3.3.0 seems to work for me though.
Issue 1&2 are tied together. The 'npm run e2e / protractor' exit status now correctly reflects the test outcome.

**Comment by christiandreher** [comment]
Are there any news on this? I am having the same issue

**Comment by christiandreher** [comment]
Maybe you're interessted in the insights at angular/protractor: https://github.com/angular/protractor/issues/3505

**Comment by mgechev** [comment]
@christiandreher thanks for the link!

**Comment by christiandreher** [comment]
This issue right here motivated me to file a bug report there at protractor, knowing that I am not the only one with that problem, so thanks to you :)

**Comment by christiandreher** [comment]
Now fixed with protractor@4.0.5 (https://github.com/angular/protractor/issues/3505#issuecomment-245397418)
