### ISSUE TITLE
Why can not I rename  project folders

### ISSUE THREAD

**Issue by seamusic** [mgechev/angular2-seed#1187]
I clone this seed project, and run "cnpm i"(I'm in China), It's run well.
then I run "npm start", that is run well too.

but when I rename the project folders or move the folder to other places,  and run "npm start", it's report error.

like this:

Z:\CP>npm start

 angular2-seed@0.0.0 start Z:\CP
 gulp serve.dev --color --config-env dev

module.js:442
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (Z:\CP\node_modules\.gulp@3.9.1\bin\gulp.js:4:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lennon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color --config-env dev

*but when I delete node_modules folder and run "cnpm i", it's run ok.*

**why? what it's happen?**

**Comment by mgechev** [comment]
This is not an issue in angular2-seed. Take a look at this [stackoverflow question](https://stackoverflow.com/questions/18974436/change-node-modules-location).

**Comment by seamusic** [comment]
This question not like the stackoverflow question.
It's like this:

I clone the project to the folder
> Z:\angular2-seed

It's run very well.
But afer I rename the folder to other.
like this

> Z:\xx

then run npm start, It's EEROR!

**Comment by mgechev** [comment]
Yes, same reason - there is node_modules directory. It contains absolute paths inside the modules's directories. You rename the base directory so you break the seed. What you need to do is to remove node_modules and run "npm i" again.
