### ISSUE TITLE
npm install angularfire2 firebase --save does not work

### ISSUE THREAD

**Issue by ix-xerri** [mgechev/angular2-seed#1188]
My old issues about these seems to be closed and I don't know if anyone saw the messages. Sorry if this is a duplicate. I am back to using this branch since it is better maintained. Trying to run `npm install angularfire2 firebase --save` creates the following error. Just updated the project to the latest commit.

> ── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.4
> ├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.4
> ├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.4
> ├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.4
> ├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.0.0-rc.4
> ├── angularfire2@2.0.0-beta.2 
> └── firebase@3.2.1

>

**Comment by AdamJo** [comment]
The message you are getting is related to the npm install and angularfire2's peer dependencies and not this repo.  AngularFire2 will still work even with those messages, so you can just ignore them for now. 

We will have to wait for AngularFire2 to update it on their side ( possibly with a new version ) for those messages to be removed.

If you need help installing AngularFire2 further you can check out this wiki  https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2.

**Comment by mgechev** [comment]
Here's sample integration with AngularFire 2 https://github.com/mgechev/angular2-seed/commit/85bf726a7a57471ebf4d69a303a80837bcd44451.

**Comment by ix-xerri** [comment]
@mgechev  how can I clone the repository with that integration?

**Comment by TheDonDope** [comment]
@ix-xerri 

```bash
$ git clone git@github.com:mgechev/angular2-seed.git
$ cd angular2-seed
$ git checkout 85bf726a7a57471ebf4d69a303a80837bcd44451
```
