### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by markjovis** [mgechev/angular2-seed#1189]
I need to do some mapping configuration like the example below (usually done in a systemjs.config.js file):

(function (global) {
  // map tells the System loader where to look for things
  var map = {
    **'angular2-adal': 'lib/angular2-adal',
    'adal': 'lib/adal-angular/lib'**
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
     **'angular2-adal': { main: 'core.js', defaultExtension: 'js' },
    'adal': { main: 'adal.js', defaultExtension: 'js' }**
  };

Since this angular2-seed doesn't have a systemjs config, where can i configure mappings like above? Any help would be greatly appreciated.

Thanks, mark.

**Comment by mgechev** [comment]
angular2-seed [has systemjs config](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L339).
