### ISSUE TITLE
Unit tests running automatically in serve.dev build?

### ISSUE THREAD

**Issue by variuse** [mgechev/angular2-seed#1193]
As a suggestion, wouldn't it be nice for the unit tests to continuously run while working with BrowserSync serve.dev build? This would mean starting up karma once with serve.dev, letting the tests run with every build change to be notified directly if something breaks.

At the moment the testing has to be triggered manually decoupled from the development flow by stopping the build and starting a "gulp test" waiting for everything to start up an run once.

Testing would be integrated in the dev workflow more seamlessly leading to better code quality.

**Comment by mgechev** [comment]
This will be in soon.
