### ISSUE TITLE
Hi! is my first time using angular 2. how I can create an api with express + mongoose and set it correctly?

### ISSUE THREAD

**Issue by jortegamo** [mgechev/angular2-seed#1197]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by TheDonDope** [comment]
Hi @jortegamo, this is not an issue related to the seed, but i recommend checking out @vyakymenko repository https://github.com/vyakymenko/angular2-seed-express
