### ISSUE TITLE
Thirdparty libraries will not be injected, if they are not in APP_SRC directory

### ISSUE THREAD

**Issue by webia1** [mgechev/angular2-seed#1199]
**my_module**s in the following configuration example are in the same directory like **node_modules** and the following configuration does not work:

```
    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
        ...this.APP_ASSETS,
        {src: `my_modules/app-design/scripts/app-design.js`, inject:true, vendor: false},
        {src: `my_modules/app-design/styles/app-design.css`, inject:true, vendor: false}
    ];
```

If I would move my modules into APP_SRC directory like
````
    {src: `${this.APP_SRC}/my_modules/app-design/styles/app-design.css`, inject: true, vendor: false},
````
it would be successfully injected. 

How can I solve this problem? I want to place my own modules in the same directory like node_modules.

thank you!

**Comment by ludohenin** [comment]
@webia1 you have to add a route to browser-sync here https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L437

**Comment by webia1** [comment]
Thank you very much! The following addition in project.config.ts was the solution:

```
this.PLUGIN_CONFIGS['browser-sync'].server.routes[`${this.APP_BASE}my_modules`] = 'my_modules';
```
