### ISSUE TITLE
Unable to integrate angular2-polymer 

### ISSUE THREAD

**Issue by surya84** [mgechev/angular2-seed#1200]
I am unable to integrate angular2-polymer  into angular2-seed

I have modified project.config.ts to have

`  this.SYSTEM_CONFIG_DEV.paths['@vaadin/angular2-polymer'] =
      `${this.APP_BASE}node_modules/@vaadin/angular2-polymer`;

    this.SYSTEM_CONFIG_DEV.packageConfigPaths =
      this.SYSTEM_CONFIG_DEV.packageConfigPaths.concat([
        `${this.APP_BASE}node_modules/@vaadin/angular2-polymer/package.json`
      ]);

    this.SYSTEM_BUILDER_CONFIG.packages['@vaadin/angular2-polymer'] = {
      main: 'index.js',
      defaultExtension: 'js'
    }`
![ng2-polymer](https://cloud.githubusercontent.com/assets/6713590/17481207/6c68f632-5d99-11e6-892d-65ca4cfe6338.JPG)

Please help me.

Error:
**localhost/:87 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/@angular/platform-browser/src/browser/browser_adapter.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1470662929282:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1470662929282:356:38)
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1470662929282:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1470662929282:423:34)
	Error loading http://localhost:5555/@angular/platform-browser/src/browser/browser_adapter.js as "@angular/platform-browser/src/browser/browser_adapter" from http://localhost:5555/node_modules/@vaadin/angular2-polymer/src/polymer-element.js "Report this error at https://github.com/mgechev/angular2-seed/issues"**

**Comment by BenevidesLecontes** [comment]
I'm whiling to know this as well. I tried so many times and no success

**Comment by unnamed666** [comment]
here's how my config looks like:
`//vaadin polymer
    this.SYSTEM_CONFIG_DEV.paths['@vaadin/angular2-polymer'] = `${this.APP_BASE}node_modules/@vaadin/angular2-polymer`;
    this.SYSTEM_CONFIG_DEV.packageConfigPaths.push(`/node_modules/@vaadin/*/package.json`);
    this.SYSTEM_BUILDER_CONFIG.packages['@vaadin/angular2-polymer'] = {
        main: 'index.js',
        defaultExtension : 'js'
    }`

and it's working fine.

**Comment by kfichter** [comment]
Having this issue too, even using the exact config as @unnamed666

**Comment by unnamed666** [comment]
what angular release are you using, rc6 ? if yes, you need to upgrade angular2-polymer to newest (yesterdays) rc6 branch
