### ISSUE TITLE
Feat request: don't reload on error

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#1201]
Currently when an error happens, the browser is reloaded with the last working version. If you don't have the terminal up, it takes time to discover that some error has happened. 

My suggestion, would be to don't reload on error or load an error page.

**Comment by sfabriece** [comment]
Sorry, working on my phone. My suggestion, would be to don't reload on error or load an error page.

**Comment by mgechev** [comment]
You have to open Chrome DevTools:
![Uploading Screen Shot 2016-08-13 at 17.21.47.png…]()
![Uploading Screen Shot 2016-08-13 at 17.20.57.png…]()

**Comment by sfabriece** [comment]
What i'm experiencing is that the last working version is sent to the browser, so opening the chrome tools won't help here. What helps is opening the terminal. But when the terminal is hidden due to code editing then it takes time to figure out an error has happened. The browser reloads as usual, just not with the latest version. (maybe a typeless compilation problem)

**Comment by mgechev** [comment]
That is weird. You're using Windows?

**Comment by sfabriece** [comment]
yes, I am.
