### ISSUE TITLE
external dependencies not correctly loaded with SystemJS (Socket.io)

### ISSUE THREAD

**Issue by gempir** [mgechev/angular2-seed#1202]
The wiki suggests adding https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency the import statement should automaticly load the dependencies but that doesn't seem to work as i am getting these issues:
http://i.stack.imgur.com/h2eCQ.png

I've tried following the full example which looks something like this in my project.config.ts

```
this.SYSTEM_CONFIG_DEV.paths['socket.io-client'] =
        `${this.APP_BASE}node_modules/socket.io-client`;

    this.SYSTEM_BUILDER_CONFIG.packages['socket.io-client'] = {
        main: 'socket.io.js',
        defaultExtension : 'js'
    }
```

But this won't load the dependencies either. Is this an issue with SystemJS or a special config? I have installed socket.io-client and the typings for it.

**Comment by mgechev** [comment]
I'd suggest to inject the socket.io client instead of using SystemJS to load it. If you put something like this in your `tools/config/project.config.ts` everything should work:

```ts
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'socket.io-client/socket.io.js', inject: 'libs'}
    ];
```

**Comment by xvs32x** [comment]
This solution not working for me. I see many errors like in @gempir example :(

**Comment by gempir** [comment]
I added the io script to the main html and used it as a global var,  dirty but it works.

**Comment by technixp** [comment]
@gempir @xvs32x cleaner solution should be editing 

> tools/config/project.config.ts .

For socket.io-client add 
` this.mergeObject(this.SYSTEM_CONFIG.paths, {'socket.io-client': 'node_modules/socket.io-client/socket.io.js'});`
