### ISSUE TITLE
angular2-swiper component

### ISSUE THREAD

**Issue by csabapurerocklab** [mgechev/angular2-seed#1203]
I have installed angular2-seed project. // no error
I have installed angular2-swiper component (npm install angular2-swiper --save) // no error

npm start

I have got this error message:
TypeError: AMD module http://localhost:5556/node_modules/swiper/dist/js/swiper.js did not define(…) 

Node version: v6.2.2
Npm version: v3.10.2

**Comment by ludohenin** [comment]
This is obviously not an issue with the seed.
For support request please the gitter room.

**Comment by Andychen41** [comment]
HI,  @csabapurerocklab. I got the same error message, could you share how to fix it? Thx.

**Comment by uzumakinaruto123** [comment]
@csabapurerocklab @Andychen41 did you get the solution ? I am getting same error

**Comment by Andychen41** [comment]
@uzumakinaruto123 
I just update to the newest Angular 2 and related libs, everything goes well.
Anyway, you should check that `KSSwiperModule` is added in correct module.

**Comment by unrl** [comment]
try `angular2-swiper-wrapper`, works perfectly.

**Comment by mitijain123** [comment]
I had tried with angular2-swiper-wrapper and it is working perfectly in development mode with 

npm start ==> running perfectly

npm run build.prod  ===> built without any issues.

npm run serve.prod ==> error message Uncaught Module 92 not present.

let me know
