### ISSUE TITLE
Discuss about directory structure to share code between projects

### ISSUE THREAD

**Issue by netstart** [mgechev/angular2-seed#1205]
What is the best practice to share code between projects?
How can I share components between projects?

Below dashboard example should be use components of the eye project, and nose project.

In this case, I run three commands to see all aplications , but, I need copy nose  source and eye  source to dashboard project to share componets 

```
npm run serve.dev -- --client eye
npm run serve.dev -- --client nose
npm run serve.dev -- --client dashboard
```

I miss the hot reload, because if modify eye.component or nose.component need copy this components to dashboard project

src
├── eye
│   ├── app
│   │   ├── components
│   │   │   ├── eye.component.html
│   │   │   ├── eye.component.ts
│   │   │   ├── eye.component.css
├── nose
│   ├── app
│   │   ├── components
│   │   │   ├── nose.component.html
│   │   │   ├── nose.component.ts
│   │   │   ├── nose.component.css
├── dashboard
│   ├── app
│   │   ├── components
│   │   │   ├── dashboard.component.html
│   │   │   ├── dashboard.component.ts
│   │   │   ├── dashboard.component.css

Other example, to ilustrate

In the structure below, commonaplication need share eye.component and nose.component with bodyaplication and dashboardaplication.
src
├── commonaplication
│ ├── app
│ │ ├── components
│ │ │ ├── eye.component.ts
│ │ │ ├── nose.component.ts
├── bodyaplication
│ ├── app
│ │ ├── components
│ │ │ ├── head.component.ts
├── dashboardaplication
│ ├── app
│ │ ├── components
│ │ │ ├── dashboard.component.ts

**Comment by mgechev** [comment]
It should be fairly easy to achieve by setting the `BOOTSTRAP_DIR`. You can:

```
npm start -- --app foo
npm start -- --app bar
npm start -- --app baz
```

Here's a sample branch which [illustrates](https://github.com/mgechev/angular2-seed/tree/multi-apps) the idea.
