### ISSUE TITLE
Add generic tasks for application resources handling

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#121]
As adding/processing font, images, less/sass, ... is common in app development it might be a good idea to have generic task(s) for the same.

Any suggestions ?

**Comment by tarlepp** [comment]
Yeah, imho less/sass processing is common in app development so +1 for this. Also what do you guys think about bower integration? So that installed bower packages are automatic injected to index.html?

**Comment by briantopping** [comment]
I wonder if the use case of component builds (i.e. directories under `components`) can be addressed in this.  A contrived example is if one component uses less and another component uses sass. Both components internally reference the stylesheets that are built, but the components need to be built differently.

If the components each had their own a gulpfile, isolation of the differences could be maintained.

**Comment by mgechev** [comment]
@briantopping this seems like a corner case most projects agree upon common preprocessors. Probably if a team is using both sass and less for a single project they have to do something custom.

**Comment by briantopping** [comment]
@mgechev I may have mentioned on gitter, my point about component builds was contrived: "deliberately created rather than arising naturally or spontaneously". I agree that most projects use common preprocessors. Components may have variant needs. One goal of a component is to decouple a set of code from other code so that it may be used interchangeably. 

More importantly to this template, by pushing component build specifics (whatever they may be), the top level build has fewer local changes. This is valuable in a template where merges from the template to projects created with it can become quite complex over time.

**Comment by mgechev** [comment]
What structure you suggest in order to handle your concerns?

**Comment by tarlepp** [comment]
Imho, it would be really great if we have tasks for SASS and LESS. Those should not be a waste, and then users could use one of those or both.

**Comment by briantopping** [comment]
@mgechev It seems like it would be quite flexible if the component folders could also have `tools` folders, and everything in `tools/tasks` would be parsed on build. 

To your point about it being difficult to find the aggregate list of all available tasks, it might be desirable for there to be something of a `gulp tasks` CLI option to list the available tasks by name in a comma separated list.

**Comment by briantopping** [comment]
@tarlepp Couldn't that be simply dropped into the `tools/tasks`? Agreed that it would be useful to a lot of people.

@mgechev If I wasn't clear, this seems to illustrate some value to not having the tasks explicitly listed in the top-level gulpfile. Maybe if there was some kind of `contrib` folder for tasks, each fork of the template could pick and choose which tasks (i.e. SASS or LESS) they wanted to be a part of their build by copying them from `contrib` to `tools/tasks`. The top-level gulpfile would not be changed, again with the goal of making future merges more manageable.

**Comment by mgechev** [comment]
Having separate gulp tasks for the individual components seems like a possible real-life scenario but I'm not sure it is inside of the scope of a minimalistic seed as this one.

For sure it is a good idea to document this practice.

**Comment by briantopping** [comment]
@mgechev I guess it just depends on whether the minimalistic seed is intended to be used as a base for production apps and how easy or hard it should be to keep apps updated with changes to the seed. Both sound like they would be great to me, but maybe that's why my suggestions sound off-base?

**Comment by tarlepp** [comment]
Imho maybe some ```optional_tasks``` folder, which could contain tasks for LESS, SASS, etc. and then some configuration value to tell which optional tasks are also included.

In that way we'll have minimalistic basic configuration + some optional tasks that users could easily to enable in their projects.

**Comment by ludohenin** [comment]
For your information, I'm working on a refactoring of the build to make it easier to extend.
I's not yet show-able but will post here when I have something.
I'll place it here for experiments: [ludohenin/angular2-seed-extended](https://github.com/ludohenin/angular2-seed-extended)

**Comment by briantopping** [comment]
@tarlepp Agreed, that's what I was talking about with `contrib`.

**Comment by briantopping** [comment]
@ludohenin So that's not a fork but a brand new template?

**Comment by mgechev** [comment]
Yes, this makes sense

**Comment by ludohenin** [comment]
I pushed someting, it's broken but will give you an idea where it's going.
Please forward you feedback.
[ludohenin/angular2-seed-extended](https://github.com/ludohenin/angular2-seed-extended)

**Comment by ludohenin** [comment]
It's somewhat working now (test tasks to be debugged).
What are your thoughts about the direction I'm taking ?

**Comment by mgechev** [comment]
@ludohenin looks good to me!

**Comment by ludohenin** [comment]
@briantopping `gulp --tasks-simple` list all available tasks

**Comment by ludohenin** [comment]
it will come with the updated build.

**Comment by briantopping** [comment]
@ludohenin yes, `gulp --tasks-simple` works, as does `gulp --tasks`. Not sure why there's a problem discovering tasks.

What will "come with the updated build"?

**Comment by mgechev** [comment]
@ludohenin we can close this after your build refactoring.
