### ISSUE TITLE
Would you update for RC5?

### ISSUE THREAD

**Issue by webia1** [mgechev/angular2-seed#1213]
There are many breaking changes,..

than you and kind rgds from Vienna

**Comment by jjokela** [comment]
Not sure if I understood correctly, but the package.json file references to RC5 files, like @angular/common": "2.0.0-rc.5

**Comment by tarlepp** [comment]
See #1208

**Comment by webia1** [comment]
Our corporate proxy hat an older version, sorry and thank you!
