### ISSUE TITLE
http get can't read  datasource for singleton like {name:'Ben',sex:'man'}

### ISSUE THREAD

**Issue by pzw224** [mgechev/angular2-seed#1214]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
if data.json like {name:'Ben',sex:'man'},how to use the http for rxjs
_What steps should we try in your demo to see the problem?_

**Current behavior**
data.json just use data for array?

**Expected/desired behavior**
i can't get the datasource for singleton

**Other information**

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
