### ISSUE TITLE
Iam getting the error while using this command in terminal    npm install -g blockchain-wallet-service

### ISSUE THREAD

**Issue by vijayalakshmireddy** [mgechev/angular2-seed#1216]
- nan@2.3.3 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws/node_modules/utf-8-validate/node_modules/nan
bluebird@2.10.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/bluebird -> node_modules/blockchain-wallet-service/node_modules/bluebird
- inherits@2.0.1 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/http-errors/node_modules/inherits
- iconv-lite@0.4.13 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/iconv-lite
- bytes@2.3.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/raw-body/node_modules/bytes
- raw-body@2.1.6 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/raw-body
bs58@2.0.1 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/bs58 -> node_modules/blockchain-wallet-service/node_modules/bs58
buffer-compare@1.1.1 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/buffer-compare -> node_modules/blockchain-wallet-service/node_modules/buffer-compare
buffer-equals@1.0.3 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/buffer-equals -> node_modules/blockchain-wallet-service/node_modules/buffer-equals
buffer-reverse@1.0.1 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/buffer-reverse -> node_modules/blockchain-wallet-service/node_modules/buffer-reverse
bytes@2.2.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/bytes -> node_modules/blockchain-wallet-service/node_modules/bytes
caseless@0.11.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/caseless -> node_modules/blockchain-wallet-service/node_modules/caseless
colors@1.0.3 node_modules/blockchain-wallet-service/node_modules/winston/node_modules/colors -> node_modules/blockchain-wallet-service/node_modules/colors
content-disposition@0.5.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/content-disposition -> node_modules/blockchain-wallet-service/node_modules/content-disposition
content-type@1.0.2 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/content-type -> node_modules/blockchain-wallet-service/node_modules/content-type
cookie@0.1.5 node_modules/blockchain-wallet-service/node_modules/express/node_modules/cookie -> node_modules/blockchain-wallet-service/node_modules/cookie
cookie-signature@1.0.6 node_modules/blockchain-wallet-service/node_modules/express/node_modules/cookie-signature -> node_modules/blockchain-wallet-service/node_modules/cookie-signature
core-util-is@1.0.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is -> node_modules/blockchain-wallet-service/node_modules/core-util-is
cycle@1.0.3 node_modules/blockchain-wallet-service/node_modules/winston/node_modules/cycle -> node_modules/blockchain-wallet-service/node_modules/cycle
delayed-stream@1.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream -> node_modules/blockchain-wallet-service/node_modules/delayed-stream
combined-stream@1.0.5 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/combined-stream -> node_modules/blockchain-wallet-service/node_modules/combined-stream
depd@1.1.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/depd -> node_modules/blockchain-wallet-service/node_modules/depd
destroy@1.0.4 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send/node_modules/destroy -> node_modules/blockchain-wallet-service/node_modules/destroy
ee-first@1.1.1 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/on-finished/node_modules/ee-first -> node_modules/blockchain-wallet-service/node_modules/ee-first
es5class@2.3.1 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/es5class -> node_modules/blockchain-wallet-service/node_modules/es5class
escape-html@1.0.3 node_modules/blockchain-wallet-service/node_modules/express/node_modules/escape-html -> node_modules/blockchain-wallet-service/node_modules/escape-html
escape-string-regexp@1.0.5 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/request-promise/node_modules/chalk/node_modules/escape-string-regexp -> node_modules/blockchain-wallet-service/node_modules/escape-string-regexp
etag@1.7.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/etag -> node_modules/blockchain-wallet-service/node_modules/etag
eventemitter3@1.2.0 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/eventemitter3 -> node_modules/blockchain-wallet-service/node_modules/eventemitter3
- mime-db@1.23.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/accepts/node_modules/mime-types/node_modules/mime-db
- mime-types@2.1.11 node_modules/blockchain-wallet-service/node_modules/express/node_modules/accepts/node_modules/mime-types
- content-type@1.0.2 node_modules/blockchain-wallet-service/node_modules/express/node_modules/content-type
- ms@0.7.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/debug/node_modules/ms
- debug@2.2.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/debug
- depd@1.1.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/depd
- unpipe@1.0.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/finalhandler/node_modules/unpipe
- ee-first@1.1.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/on-finished/node_modules/ee-first
- on-finished@2.3.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/on-finished
- inherits@2.0.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send/node_modules/http-errors/node_modules/inherits
- http-errors@1.3.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send/node_modules/http-errors
- ms@0.7.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send/node_modules/ms
- serve-static@1.10.2 node_modules/blockchain-wallet-service/node_modules/express/node_modules/serve-static
- media-typer@0.3.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/type-is/node_modules/media-typer
- mime-db@1.23.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/type-is/node_modules/mime-types/node_modules/mime-db
- mime-types@2.1.11 node_modules/blockchain-wallet-service/node_modules/express/node_modules/type-is/node_modules/mime-types
- type-is@1.6.13 node_modules/blockchain-wallet-service/node_modules/express/node_modules/type-is
extend@3.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/extend -> node_modules/blockchain-wallet-service/node_modules/extend
extsprintf@1.0.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/extsprintf -> node_modules/blockchain-wallet-service/node_modules/extsprintf
eyes@0.1.8 node_modules/blockchain-wallet-service/node_modules/winston/node_modules/eyes -> node_modules/blockchain-wallet-service/node_modules/eyes
forever-agent@0.6.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/forever-agent -> node_modules/blockchain-wallet-service/node_modules/forever-agent
forwarded@0.1.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/proxy-addr/node_modules/forwarded -> node_modules/blockchain-wallet-service/node_modules/forwarded
fresh@0.3.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/fresh -> node_modules/blockchain-wallet-service/node_modules/fresh
generate-function@2.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-function -> node_modules/blockchain-wallet-service/node_modules/generate-function
assert-plus@1.0.0 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/assert-plus -> node_modules/blockchain-wallet-service/node_modules/getpass/node_modules/assert-plus
getpass@0.1.6 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/getpass -> node_modules/blockchain-wallet-service/node_modules/getpass
graceful-readlink@1.0.1 node_modules/blockchain-wallet-service/node_modules/commander/node_modules/graceful-readlink -> node_modules/blockchain-wallet-service/node_modules/graceful-readlink
has-ansi@2.0.0 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/request-promise/node_modules/chalk/node_modules/has-ansi -> node_modules/blockchain-wallet-service/node_modules/has-ansi
hoek@2.16.3 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/hawk/node_modules/hoek -> node_modules/blockchain-wallet-service/node_modules/hoek
boom@2.10.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/hawk/node_modules/boom -> node_modules/blockchain-wallet-service/node_modules/boom
cryptiles@2.0.5 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/hawk/node_modules/cryptiles -> node_modules/blockchain-wallet-service/node_modules/cryptiles
iconv-lite@0.4.13 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/iconv-lite -> node_modules/blockchain-wallet-service/node_modules/iconv-lite
inherits@2.0.1 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/inherits -> node_modules/blockchain-wallet-service/node_modules/inherits
cipher-base@1.0.2 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/cipher-base -> node_modules/blockchain-wallet-service/node_modules/cipher-base
ipaddr.js@1.0.5 node_modules/blockchain-wallet-service/node_modules/express/node_modules/proxy-addr/node_modules/ipaddr.js -> node_modules/blockchain-wallet-service/node_modules/ipaddr.js
is-property@1.0.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property -> node_modules/blockchain-wallet-service/node_modules/is-property
generate-object-property@1.2.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property -> node_modules/blockchain-wallet-service/node_modules/generate-object-property
is-typedarray@1.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/is-typedarray -> node_modules/blockchain-wallet-service/node_modules/is-typedarray
isarray@1.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/isarray -> node_modules/blockchain-wallet-service/node_modules/isarray
isstream@0.1.2 node_modules/blockchain-wallet-service/node_modules/winston/node_modules/isstream -> node_modules/blockchain-wallet-service/node_modules/isstream
jsbn@0.1.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/jsbn -> node_modules/blockchain-wallet-service/node_modules/jsbn
jodid25519@1.0.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/jodid25519 -> node_modules/blockchain-wallet-service/node_modules/jodid25519
ecc-jsbn@0.1.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/ecc-jsbn -> node_modules/blockchain-wallet-service/node_modules/ecc-jsbn
- ms@0.7.1 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/debug/node_modules/ms
- debug@2.2.0 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/debug
json-schema@0.2.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/json-schema -> node_modules/blockchain-wallet-service/node_modules/json-schema
json-stringify-safe@5.0.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/json-stringify-safe -> node_modules/blockchain-wallet-service/node_modules/json-stringify-safe
jsonparse@1.2.0 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/jsonparse -> node_modules/blockchain-wallet-service/node_modules/jsonparse
jsonpointer@2.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/jsonpointer -> node_modules/blockchain-wallet-service/node_modules/jsonpointer
lodash@3.10.1 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/lodash -> node_modules/blockchain-wallet-service/node_modules/lodash
media-typer@0.3.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/type-is/node_modules/media-typer -> node_modules/blockchain-wallet-service/node_modules/media-typer
merge-descriptors@1.0.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/merge-descriptors -> node_modules/blockchain-wallet-service/node_modules/merge-descriptors
methods@1.1.2 node_modules/blockchain-wallet-service/node_modules/express/node_modules/methods -> node_modules/blockchain-wallet-service/node_modules/methods
mime@1.3.4 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send/node_modules/mime -> node_modules/blockchain-wallet-service/node_modules/mime
mime-db@1.23.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/type-is/node_modules/mime-types/node_modules/mime-db -> node_modules/blockchain-wallet-service/node_modules/mime-db
mime-types@2.1.11 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/type-is/node_modules/mime-types -> node_modules/blockchain-wallet-service/node_modules/mime-types
form-data@1.0.0-rc4 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/form-data -> node_modules/blockchain-wallet-service/node_modules/form-data
ms@0.7.1 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/debug/node_modules/ms -> node_modules/blockchain-wallet-service/node_modules/ms
debug@2.2.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/debug -> node_modules/blockchain-wallet-service/node_modules/debug
bufferutil@1.2.1 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws/node_modules/bufferutil -> node_modules/blockchain-wallet-service/node_modules/bufferutil
negotiator@0.5.3 node_modules/blockchain-wallet-service/node_modules/express/node_modules/accepts/node_modules/negotiator -> node_modules/blockchain-wallet-service/node_modules/negotiator
accepts@1.2.13 node_modules/blockchain-wallet-service/node_modules/express/node_modules/accepts -> node_modules/blockchain-wallet-service/node_modules/accepts
node-uuid@1.4.7 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/node-uuid -> node_modules/blockchain-wallet-service/node_modules/node-uuid
oauth-sign@0.8.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/oauth-sign -> node_modules/blockchain-wallet-service/node_modules/oauth-sign
object-assign@4.1.0 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/object-assign -> node_modules/blockchain-wallet-service/node_modules/object-assign
on-finished@2.3.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/on-finished -> node_modules/blockchain-wallet-service/node_modules/on-finished
options@0.0.6 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/options -> node_modules/blockchain-wallet-service/node_modules/options
parseurl@1.3.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/parseurl -> node_modules/blockchain-wallet-service/node_modules/parseurl
path-to-regexp@0.1.7 node_modules/blockchain-wallet-service/node_modules/express/node_modules/path-to-regexp -> node_modules/blockchain-wallet-service/node_modules/path-to-regexp
pinkie@2.0.4 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie -> node_modules/blockchain-wallet-service/node_modules/pinkie
pinkie-promise@2.0.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise -> node_modules/blockchain-wallet-service/node_modules/pinkie-promise
pkginfo@0.3.1 node_modules/blockchain-wallet-service/node_modules/winston/node_modules/pkginfo -> node_modules/blockchain-wallet-service/node_modules/pkginfo
process-nextick-args@1.0.7 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/process-nextick-args -> node_modules/blockchain-wallet-service/node_modules/process-nextick-args
proxy-addr@1.0.10 node_modules/blockchain-wallet-service/node_modules/express/node_modules/proxy-addr -> node_modules/blockchain-wallet-service/node_modules/proxy-addr
randombytes@2.0.3 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/randombytes -> node_modules/blockchain-wallet-service/node_modules/randombytes
range-parser@1.0.3 node_modules/blockchain-wallet-service/node_modules/express/node_modules/range-parser -> node_modules/blockchain-wallet-service/node_modules/range-parser
- inherits@2.0.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/inherits
- ansi-styles@2.2.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/ansi-styles
- escape-string-regexp@1.0.5 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/escape-string-regexp
- ansi-regex@2.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex
- has-ansi@2.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi
- ansi-regex@2.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi/node_modules/ansi-regex
- strip-ansi@3.0.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color
- chalk@1.1.3 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/chalk
- jsprim@1.2.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/jsprim
- dashdash@1.13.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/dashdash
- sshpk@1.8.3 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk
- isstream@0.1.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/isstream
- mime-db@1.23.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/mime-types/node_modules/mime-db
- mime-types@2.1.11 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/mime-types
- qs@6.1.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/qs
- tough-cookie@2.2.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/tough-cookie
- request@2.72.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request
requires-port@1.0.0 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/url-parse/node_modules/requires-port -> node_modules/blockchain-wallet-service/node_modules/requires-port
ripemd160@1.0.1 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ripemd160 -> node_modules/blockchain-wallet-service/node_modules/ripemd160
statuses@1.2.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send/node_modules/statuses -> node_modules/blockchain-wallet-service/node_modules/serve-static/node_modules/statuses
sha.js@2.4.5 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/sha.js -> node_modules/blockchain-wallet-service/node_modules/sha.js
create-hash@1.1.2 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/create-hash -> node_modules/blockchain-wallet-service/node_modules/create-hash
create-hmac@1.1.4 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/create-hmac -> node_modules/blockchain-wallet-service/node_modules/create-hmac
bs58check@1.0.8 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/bs58check -> node_modules/blockchain-wallet-service/node_modules/bs58check
sntp@1.0.9 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/hawk/node_modules/sntp -> node_modules/blockchain-wallet-service/node_modules/sntp
hawk@3.1.3 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/hawk -> node_modules/blockchain-wallet-service/node_modules/hawk
assert-plus@1.0.0 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/assert-plus -> node_modules/blockchain-wallet-service/node_modules/sshpk/node_modules/assert-plus
stack-trace@0.0.9 node_modules/blockchain-wallet-service/node_modules/winston/node_modules/stack-trace -> node_modules/blockchain-wallet-service/node_modules/stack-trace
statuses@1.3.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/http-errors/node_modules/statuses -> node_modules/blockchain-wallet-service/node_modules/statuses
http-errors@1.3.1 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/http-errors -> node_modules/blockchain-wallet-service/node_modules/http-errors
send@0.13.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/send -> node_modules/blockchain-wallet-service/node_modules/send
string_decoder@0.10.31 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/string_decoder -> node_modules/blockchain-wallet-service/node_modules/string_decoder
stringstream@0.0.5 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/stringstream -> node_modules/blockchain-wallet-service/node_modules/stringstream
strip-ansi@3.0.1 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/request-promise/node_modules/chalk/node_modules/strip-ansi -> node_modules/blockchain-wallet-service/node_modules/strip-ansi
supports-color@2.0.0 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/request-promise/node_modules/chalk/node_modules/supports-color -> node_modules/blockchain-wallet-service/node_modules/supports-color
chalk@1.1.3 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/request-promise/node_modules/chalk -> node_modules/blockchain-wallet-service/node_modules/chalk
tunnel-agent@0.4.3 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/tunnel-agent -> node_modules/blockchain-wallet-service/node_modules/tunnel-agent
tweetnacl@0.13.3 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/tweetnacl -> node_modules/blockchain-wallet-service/node_modules/tweetnacl
type-is@1.6.13 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/type-is -> node_modules/blockchain-wallet-service/node_modules/type-is
typeforce@1.6.2 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/typeforce -> node_modules/blockchain-wallet-service/node_modules/typeforce
ultron@1.0.2 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ultron -> node_modules/blockchain-wallet-service/node_modules/ultron
unpipe@1.0.0 node_modules/blockchain-wallet-service/node_modules/body-parser/node_modules/raw-body/node_modules/unpipe -> node_modules/blockchain-wallet-service/node_modules/unpipe
finalhandler@0.4.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/finalhandler -> node_modules/blockchain-wallet-service/node_modules/finalhandler
url-join@0.0.1 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/url-join -> node_modules/blockchain-wallet-service/node_modules/url-join
url-pattern@0.10.2 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/url-pattern -> node_modules/blockchain-wallet-service/node_modules/url-pattern
utf-8-validate@1.2.1 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws/node_modules/utf-8-validate -> node_modules/blockchain-wallet-service/node_modules/utf-8-validate
util-deprecate@1.0.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/util-deprecate -> node_modules/blockchain-wallet-service/node_modules/util-deprecate
readable-stream@2.0.6 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl/node_modules/readable-stream -> node_modules/blockchain-wallet-service/node_modules/readable-stream
bl@1.1.2 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/bl -> node_modules/blockchain-wallet-service/node_modules/bl
utils-merge@1.0.0 node_modules/blockchain-wallet-service/node_modules/express/node_modules/utils-merge -> node_modules/blockchain-wallet-service/node_modules/utils-merge
vary@1.0.1 node_modules/blockchain-wallet-service/node_modules/express/node_modules/vary -> node_modules/blockchain-wallet-service/node_modules/vary
verror@1.3.6 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror -> node_modules/blockchain-wallet-service/node_modules/verror
http-signature@1.1.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/http-signature -> node_modules/blockchain-wallet-service/node_modules/http-signature
websocket-extensions@0.1.1 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions -> node_modules/blockchain-wallet-service/node_modules/websocket-extensions
websocket-driver@0.6.5 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/faye-websocket/node_modules/websocket-driver -> node_modules/blockchain-wallet-service/node_modules/websocket-driver
faye-websocket@0.11.0 node_modules/blockchain-wallet-service/node_modules/json-rpc2/node_modules/faye-websocket -> node_modules/blockchain-wallet-service/node_modules/faye-websocket
wif@1.2.1 node_modules/blockchain-wallet-service/node_modules/bitcoinjs-lib/node_modules/wif -> node_modules/blockchain-wallet-service/node_modules/wif
ws@0.8.1 node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws -> node_modules/blockchain-wallet-service/node_modules/ws
xtend@4.0.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend -> node_modules/blockchain-wallet-service/node_modules/xtend
is-my-json-valid@2.13.1 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid -> node_modules/blockchain-wallet-service/node_modules/is-my-json-valid
har-validator@2.0.6 node_modules/blockchain-wallet-service/node_modules/request-promise/node_modules/request/node_modules/har-validator -> node_modules/blockchain-wallet-service/node_modules/har-validator
- bip39@2.1.2 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/bip39
- bitcoinjs-lib@2.1.4 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/bitcoinjs-lib
- es6-promise@3.1.2 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/es6-promise
- isomorphic-fetch@2.2.1 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/isomorphic-fetch
- sjcl@1.0.3 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/sjcl
- ws@1.1.0 node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws
/usr/lib
`-- blockchain-wallet-service@0.22.0 
  +-- bitcoinjs-lib@2.2.0
  | +-- bigi@1.4.2 
  | `-- ecurve@1.0.3 
  +-- blockchain-wallet-client-prebuilt@3.22.0 
  +-- blockchain.info@2.2.3
  | +-- url-parse@1.1.3 
  | | `-- querystringify@0.0.4 
  | `-- ws@0.8.1
  |   `-- bufferutil@1.2.1
  |     `-- nan@2.4.0 
  +-- body-parser@1.14.2
  | `-- raw-body@2.1.7 
  |   `-- bytes@2.4.0 
  +-- express@4.13.4
  | +-- send@0.13.1
  | | `-- statuses@1.2.1 
  | `-- serve-static@1.10.3 
  |   `-- send@0.13.2 
  `-- request-promise@2.0.1
    +-- lodash@4.15.0 
    `-- request@2.74.0 
      +-- http-signature@1.1.1
      | +-- jsprim@1.3.0 
      | `-- sshpk@1.9.2 
      |   `-- dashdash@1.14.0 
      |     `-- assert-plus@1.0.0 
      +-- qs@6.2.1 
      `-- tough-cookie@2.3.1 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ror/npm-debug.log

**Comment by TheDonDope** [comment]
In no part of the stack trace, nor your description is there any relation to this seed project.
