### ISSUE TITLE
Add a STAGING environment and build tasks to seed.config.ts

### ISSUE THREAD

**Issue by calvinhmw** [mgechev/angular2-seed#1218]
Sometimes in staging build the application will have to use a different api endpoint, but it looks like the current seed.config.ts does not define a staging environment. There is no gulp tasks for staging build as well. Please consider adding those.

**Comment by mgechev** [comment]
You can configure one by:

- Create a file `tools/env/staging.ts`.
- Run the seed with `npm run build.prod -- --config-env staging`.
