### ISSUE TITLE
Understanding-question about RC5 Upgrade

### ISSUE THREAD

**Issue by webia1** [mgechev/angular2-seed#1221]
As you can see all the modules are already imported in the app.module.ts:

```
@NgModule({
  imports: [BrowserModule, HttpModule, RouterModule.forRoot(routes), AboutModule, HomeModule, SharedModule.forRoot()],
........
```

Why do I have to import them **again**:

`import { ....., NavbarComponent, ToolbarComponent } from './shared/index';`

**and again** (this time in form of directives)

`directives: [........, NavbarComponent, ToolbarComponent]`

Should we not move them into the app.module.ts (Declarations,..) ?

Why do we need in "+home" and "+about" pages additional *.module.ts files? They are not independed modules or? Did I miss an important concept? 

I am a little bit confused O_o

Thank you for your feedback,..

**Comment by Shyam-Chen** [comment]
#1211

**Comment by Nightapes** [comment]
You can add of course everything in the app.module. But angular added the concept of feature modules to help organize application into cohesive blocks of functionality. 

> A feature module delivers a cohesive set of functionality. focused on an application business domain, a user workflow, a facility (forms, http, routing), or a collection of related utilities.
> https://angular.io/docs/ts/latest/guide/ngmodule.html#!#feature-modules

Normally a module contains multiple components, services or pipes. This here is a really minimalist example.

**Comment by webia1** [comment]
Thank you!
