### ISSUE TITLE
Cannot run npm start

### ISSUE THREAD

**Issue by ix-xerri** [mgechev/angular2-seed#1222]
When I try to start a clean clone with npm start I get the following error.

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@0.0.0~prestart: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@0.0.0~start: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/matthewxerri/Documents/dev/angular2-seed/node_modules/.bin:/usr/local/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mongodb/bin
10 verbose lifecycle angular2-seed@0.0.0~start: CWD: /Users/matthewxerri/Documents/dev/angular2-seed
11 silly lifecycle angular2-seed@0.0.0~start: Args: [ '-c', 'gulp serve.dev --color --config-env dev' ]
12 silly lifecycle angular2-seed@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve.dev --color --config-env dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd /Users/matthewxerri/Documents/dev/angular2-seed
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 start: `gulp serve.dev --color --config-env dev`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color --config-env dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve.dev --color --config-env dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ckapilla** [comment]
did you remember to do npm install before doing the npm start?

**Comment by ix-xerri** [comment]
yes I did

**Comment by mgechev** [comment]
I've seen this issue a couple of times in the past. Here's a solution https://github.com/mgechev/angular2-seed/issues/359.

**Comment by ix-xerri** [comment]
I've installed angular-cli (-g) before this happened if that has anything to do with it.

**Comment by mgechev** [comment]
`npm clean cache` and `npm install` after that should make it.

**Comment by ix-xerri** [comment]
npm install worked as before but npm start did not. side-note - I'm trying to stop using sudo by running following [option 1](https://docs.npmjs.com/getting-started/fixing-npm-permissions) but it doesn't work.

**Comment by mgechev** [comment]
@ix-xerri angular-cli should not be the problem. I guess it is something environment specific. Let me know if [nothing helps](https://www.google.com/search?q=angular2-seed%400.0.0~start%3A+unsafe-perm+in+lifecycle+true&oq=angular2-seed%400.0.0~start%3A+unsafe-perm+in+lifecycle+true&aqs=chrome..69i57.115j0j1&sourceid=chrome&ie=UTF-8&safe=high). I guess it is something environment specific but lets keep an eye on what you'd find.

**Comment by Yuvaraj777** [comment]
npm clean cache and npm install works perfectly. Thanks @mgechev
