### ISSUE TITLE
How to include ng-bootstrap

### ISSUE THREAD

**Issue by hucba** [mgechev/angular2-seed#1223]
[Here](https://github.com/AngularShowcase/ng2-bootstrap-sbadmin/blob/master/tools/config/project.config.ts) it is shown how to include ng-bootstrap, but it is rather bad style to directly inject the lib like this:
`let additionalDeps: InjectableDependency[] = [
      { src: 'ng2-bootstrap/bundles/ng2-bootstrap', inject: 'lib' },
      { src: 'bootstrap/dist/css/bootstrap.css', inject: true },
      { src: 'font-awesome/css/font-awesome.min.css', inject: true }
    ];`

 What is the proper way to do this?

Angular: 2.0.0-rc.5
ng-bootstrap: 1.0.0-alpha.3

**Comment by mgechev** [comment]
Most likely you'd want to include it in the SystemJS configuration.

For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by JunusErgin** [comment]
I had the same issue and fixed it the following way:

Go to project.config.ts and add the lib:

>    this.SYSTEM_CONFIG_DEV.paths['@ng-bootstrap/ng-bootstrap'] =
>       `${this.APP_BASE}node_modules/@ng-bootstrap/ng-bootstrap/index.js`;
> 
>     this.SYSTEM_BUILDER_CONFIG.packages['@ng-bootstrap/ng-bootstrap'] = {
>       main: 'index.js',
>       defaultExtension: 'js'
>     };

Afterwards i extended the seed.config.ts with an extra line in the `packageConfigPaths`:

>  protected SYSTEM_CONFIG_DEV: any = {
>     defaultJSExtensions: true,
>     packageConfigPaths: [
>       `/node_modules/*/package.json`,
>       `/node_modules/**/package.json`,
>       `/node_modules/@angular/*/package.json`,
>       `/node_modules/@ng-bootstrap/*/package.json`
>     ],...

@mgechev If there any way to edit this in the projet.config.ts?

Best,

Junus´

PS: Sorry for the bad formatting ;)

**Comment by mgechev** [comment]
Yes, this is supposed to be in the `project.config.ts`. You can overwrite the properties in the constructor there.

**Comment by iscalfonsoolivares** [comment]
I had some issues including ng-bootstrap in angular2-seed, what it worked for me was include 

protected SYSTEM_CONFIG_DEV: any = {
     defaultJSExtensions: true,
     packageConfigPaths: [
       `/node_modules/*/package.json`,
       `/node_modules/**/package.json`,
       `/node_modules/@angular/*/package.json`,
       `/node_modules/@ng-bootstrap/*/package.json`
     ],...

as @JunusErgin mentions but with this lines ..

    this.SYSTEM_CONFIG_DEV.paths['@ng-bootstrap/ng-bootstrap'] =
      `${this.APP_BASE}node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap`;

    this.SYSTEM_BUILDER_CONFIG.packages['@ng-bootstrap/ng-bootstrap'] = {
        main: 'ng-bootstrap.js',
        defaultExtension : 'js'
    }

**Comment by GNUletik** [comment]
As I spent a lot of time trying to make it work, here is the proper way to do it (without changing `seed.config.ts`).    
Here is the needed lines in `project.config.ts` : 
```
    this.SYSTEM_CONFIG_DEV.paths['@ng-bootstrap/ng-bootstrap'] =
      `${this.APP_BASE}node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js`;

    this.SYSTEM_BUILDER_CONFIG.packages['@ng-bootstrap/ng-bootstrap'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };

    this.SYSTEM_BUILDER_CONFIG.packageConfigPaths.push(
      join('node_modules', '@ng-bootstrap', '*', 'package.json')
    );

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      { src: 'jquery/dist/jquery.js', inject: 'libs' },
      { src: 'bootstrap/dist/js/bootstrap.js', inject: 'libs' },
      { src: 'bootstrap/dist/css/bootstrap.css', inject: true }
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

```
And it just works :)

**Comment by amalshehu** [comment]
I think you got a clear idea about adding an external dependency.I added material with my angular2 project.But the autocomplete feature is not available with it.So i would like to include md2, another dependency which covers all the missing items as of now by material. Can anyone help me integrate md2 with angular-seed?

**Comment by GNUletik** [comment]
@amalshehu All I know is from the [wiki page](https://github.com/mgechev/angular-seed/wiki/Add-external-dependency).
If the wiki steps doesn't work for you, you should open a new issue for this specific issue.

**Comment by benediktdertinger** [comment]
Currently **@ng-bootstrap** can be added in _tools/config/project.config.ts_ like this:
```javascript
...
// Add packages
let additionalPackages: ExtendPackages[] = [{
  name: '@ng-bootstrap/ng-bootstrap',
  // Path to the package's bundle
  path: 'node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js'
}];

this.addPackagesBundles(additionalPackages);
```
Import it in _src/client/web.module.ts_ like this:
```javascript
...
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
...
@NgModule({
  imports: [
    ...
    NgbModule.forRoot()
```
If you're using a module (like in _src/client/modules/shared/shared.module.ts_ for your bootstrap collapse navbar) **do not forget to import it here as well!**
```javascript
...
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
...
const SHARED_MODULES: any[] = [
  ...
  NgbModule,
```
To add tests etc. see https://github.com/mgechev/angular-seed/wiki/Add-external-dependency
The installation guide from ng-bootstrap can be found here: https://ng-bootstrap.github.io/#/getting-started

I hope this helps!
