### ISSUE TITLE
Cannot run karma tests

### ISSUE THREAD

**Issue by vinaychandra** [mgechev/angular2-seed#1229]
**Steps to reproduce and a minimal demo of the problem**

- Clone the repository and change the component to use any observable.

**Current behavior**

```
18 08 2016 22:22:50.426:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
18 08 2016 22:22:50.430:INFO [launcher]: Starting browser Chrome
18 08 2016 22:22:52.115:INFO [Chrome 52.0.2743 (Linux 0.0.0)]: Connected on socket /#iiI-4vTinwev68hfAAAA with id 59110883
18 08 2016 22:22:53.251:WARN [web-server]: 404: /base/node_modules/rxjs.js
Chrome 52.0.2743 (Linux 0.0.0) ERROR: Error{originalErr: Error{}}
```

**Expected/desired behavior**
There should be no such error

**Other information**
This one is *probably* introduced with rc5 build 

The stack trace is
```
GET http://localhost:9876/base/node_modules/rxjs.js 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/rxjs.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js:789:30)
	    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js:365:38)
	    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js:265:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js:432:34)
	Error loading http://localhost:9876/base/node_modules/rxjs.js as "rxjs" from http://localhost:9876/base/dist/dev/app/account/auth/auth.service.js
```
The `auth.sevice.js` file contains `import { Observable } from 'rxjs';`

**Comment by Nightapes** [comment]
I could reproduce the error.

Can you replace the `import { Observable } from 'rxjs';` to `import { Observable } from 'rxjs/Observable';` and try it again? It should fix the error

**Comment by vinaychandra** [comment]
It fixes the error :+1: But it would be better if we could import from `rxjs` instead of others

**Comment by SamFarrington** [comment]
Just hit this error on an unrelated project and this thread was literally the only one on Google which mentioned it. THANKS!
