### ISSUE TITLE
JQuery with testing

### ISSUE THREAD

**Issue by vinaychandra** [mgechev/angular2-seed#1230]
**Steps to reproduce and a minimal demo of the problem**
- Setup the seed to use jquery in `project.config.ts`
- Do a `declare var $: any;` in a component and use it normally
- Run a unit test using Jasmine which calls the component function that uses jquery.

**Current behavior**
- When running tests with `gulp test` we get `ReferenceError: $ is not defined`

**Expected/desired behavior**
- `$` is already defined using `declare var` so, it should work without a problem.

**Other Information**
The issue seems to be with karma but adding `      {pattern: 'node_modules/jquery/dist/jquery.js', included: false, watched: false}` to the `karma.conf.js` file does not remove the problem

**Comment by mgechev** [comment]
Here are a [couple of related issues](https://github.com/mgechev/angular2-seed/issues?q=is%3Aissue+JQuery+is%3Aclosed).
