### ISSUE TITLE
npm install fails on webdriver with "TypeError: task is not a function" error

### ISSUE THREAD

**Issue by nabeelbukhari** [mgechev/angular2-seed#1234]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
just run npm install

_What steps should we try in your demo to see the problem?_
I followed steps mentioned in how to start

**Current behavior**
It fails with "TypeError: task is not a function"

**Expected/desired behavior**
Should complete build process.

**Other information**
Find attached debug file.
[npm-debug.txt](https://github.com/mgechev/angular2-seed/files/429416/npm-debug.txt)

**Comment by mgechev** [comment]
Did you try `npm cache clean && npm i`? There are a lot of [similar issues which are already solved](https://github.com/mgechev/angular2-seed/issues?q=is%3Aissue+unsafe-perm+in+lifecycle+true+is%3Aclosed).

**Comment by nabeelbukhari** [comment]
Hi,
Thanks for quick response. Yes, I tried running reinstall and cache clean but still same issue. I also tried removing and re-installing node/npm/gulp but it didn't help.

BTW, I am using windows 10 with npm v3.10.5.

**Comment by nabeelbukhari** [comment]
Solution to problem is cloning in a new directory and start again.
The only differences I found are following:

[09:10:04] Using gulpfile ~\Desktop\angular2-seed\gulpfile.ts
[09:10:04] Starting 'webdriver'...
Updating selenium standalone to version 2.52.0
downloading https://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar...
Updating chromedriver to version 2.21
downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip...
chromedriver_2.21win32.zip downloaded to C:\Users\VERIPARK\Desktop\angular2-seed\node_modules\protractor\selenium\chromedriver_2.21win32.zip
selenium-server-standalone-2.52.0.jar downloaded to C:\Users\VERIPARK\Desktop\angular2-seed\node_modules\protractor\selenium\selenium-server-standalone-2.52.0.jar
[09:13:47] Finished 'webdriver' after 3.72 min
angular2-seed@0.0.0 C:\Users\VERIPARK\Desktop\angular2-seed


Previously it was not downloading chromedriver. Can you add condition to check if its downloading and if not it should start the download.

Thanks for helping :)

**Comment by mgechev** [comment]
Ah, I see. This is in the readme but it makes sense to download it conditionally.
