### ISSUE TITLE
cssnano from build.html_css breaks the build

### ISSUE THREAD

**Issue by htdt** [mgechev/angular2-seed#1235]
MacOS, Node v6.4.0, npm@3.10.3, fresh clone and `npm install`.

`npm start` and `npm build.prod` output an error
```
[12:47:19] Starting 'build.html_css'...
[12:47:20] 'build.html_css' errored after 303 ms
[12:47:20] TypeError: Cannot read property 'length' of undefined
...
```

Removing https://github.com/mgechev/angular2-seed/blob/02aafed6bbd0c031a699238e4d305b7ee7111eff/tools/tasks/seed/build.html_css.ts#L36-L45 fixes the error.

**Comment by ludohenin** [comment]
@htdt I can't reproduce with the same setup as you.

**Comment by mgechev** [comment]
Probably an issue in a third party library. If you share your CSS file may be we can reproduce it and/or report it to the cssnano guys.

**Comment by htdt** [comment]
@mgechev the error occurs for a clean freshly cloned seed without any modification of css.
Please note, it's present even for dev build, where the problematic code is not executed.
According to it, I think, it's a problem of transpiling this gulp task from typescript to js.

**Comment by mgechev** [comment]
I didn't notice that was a fresh clone, sorry. Are you still able to reproduce it?

**Comment by htdt** [comment]
Yes, still occurs.
Here are the package versions:
> npm ls --depth=0
> ├── @angular/common@2.0.0-rc.5
> ├── @angular/compiler@2.0.0-rc.5
> ├── @angular/core@2.0.0-rc.5
> ├── @angular/forms@0.3.0
> ├── @angular/http@2.0.0-rc.5
> ├── @angular/platform-browser@2.0.0-rc.5
> ├── @angular/platform-browser-dynamic@2.0.0-rc.5
> ├── @angular/router@3.0.0-rc.1
> ├── async@2.0.1
> ├── autoprefixer@6.4.0
> ├── browser-sync@2.14.0
> ├── codelyzer@0.0.25
> ├── colorguard@1.2.0
> ├── compression@1.6.2
> ├── connect@3.4.1
> ├── connect-history-api-fallback@1.3.0
> ├── connect-livereload@0.5.4
> ├── core-js@2.4.1
> ├── cssnano@3.7.4
> ├── deep-extend@0.4.1
> ├── doiuse@2.4.1
> ├── es6-module-loader@0.17.11
> ├── event-stream@3.3.4
> ├── express@4.14.0
> ├── express-history-api-fallback@2.0.0
> ├── extend@3.0.0
> ├── gulp@3.9.1
> ├── gulp-cached@1.1.0
> ├── gulp-clean-css@2.0.12
> ├── gulp-concat@2.6.0
> ├── gulp-concat-css@2.3.0
> ├── gulp-filter@4.0.0
> ├── gulp-inject@4.1.0
> ├── gulp-inline-ng2-template@2.1.0
> ├── gulp-load-plugins@1.2.4
> ├── gulp-plumber@1.1.0
> ├── gulp-postcss@6.1.1
> ├── gulp-progeny@0.3.1
> ├── gulp-protractor@2.6.0
> ├── gulp-replace@0.5.4
> ├── gulp-sass@2.3.2
> ├── gulp-sass-lint@1.2.0
> ├── gulp-shell@0.5.2
> ├── gulp-sourcemaps@2.0.0-alpha
> ├── gulp-template@4.0.0
> ├── gulp-tslint@6.0.2
> ├── gulp-typescript@2.13.6
> ├── gulp-uglify@1.5.4
> ├── gulp-util@3.0.7
> ├── gulp-watch@4.3.9
> ├── is-ci@1.0.9
> ├── isstream@0.1.2
> ├── jasmine-core@2.4.1
> ├── jasmine-spec-reporter@2.7.0
> ├── karma@0.13.22
> ├── karma-chrome-launcher@1.0.1
> ├── karma-coverage@1.1.1
> ├── karma-jasmine@1.0.2
> ├── karma-mocha-reporter@2.1.0
> ├── merge-stream@1.0.0
> ├── open@0.0.5
> ├── postcss-reporter@1.4.1
> ├── protractor@3.3.0
> ├── remap-istanbul@0.6.4
> ├── rimraf@2.5.4
> ├── run-sequence@1.2.2
> ├── rxjs@5.0.0-beta.6
> ├── semver@5.3.0
> ├── serve-static@1.11.1
> ├── slash@1.0.0
> ├── stream-series@0.1.1
> ├── stylelint@7.1.0
> ├── stylelint-config-standard@11.0.0
> ├── systemjs@0.19.27
> ├── systemjs-builder@0.15.14
> ├── tildify@1.2.0
> ├── tiny-lr@0.2.1
> ├── traceur@0.0.111
> ├── ts-node@1.3.0
> ├── tslint@3.14.0
> ├── tslint-stylish@2.1.0-beta
> ├── typescript@1.8.10
> ├── typings@1.3.2
> ├── vinyl-buffer@1.0.0
> ├── vinyl-source-stream@1.1.0
> ├── walk@2.3.9
> ├── yargs@4.8.1
> └── zone.js@0.6.13

**Comment by johankarlstrom** [comment]
I had the same problem as htdt at the same time, as you might have seen on Gitter. I have the same setup as him, MacOS, Node v6.4.0, npm@3.10.3. Just now I got a fresh clone and tried it and it seems to be gone. No errors when building or starting.

**Comment by htdt** [comment]
I confirm, just have reinstalled the seed and there is no error. Nothing really changed, but it works now.
