### ISSUE TITLE
Integrating third party libraries

### ISSUE THREAD

**Issue by renecardozo** [mgechev/angular2-seed#1238]
**IMPORTANT**: Integrate third party libraries

**Steps to reproduce and a minimal demo of the problem**

_Hi Guys, First to all thanks for this great seed to get started with angular2, it is posible to integrate libraries like a bootstrap or Jquery? please ... send the feedback. thanks in advance._

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
There's further information on how to use third-party libraries in the [wiki](https://github.com/mgechev/angular2-seed/wiki).

**Comment by renecardozo** [comment]
Thanks so much.
