### ISSUE TITLE
build.prod problem with external libraries.

### ISSUE THREAD

**Issue by Bigous** [mgechev/angular2-seed#1241]
When we have external libraries (like ng2-highcharts) and try to build.prod, the build.bundle.app task tries to load all the libraries to bundle together, but it's not following the behavior of typescript or node for libraries.
if the library is imported like this:

```typescript
import { Ng2Highcharts } from 'ng2-highcharts';
```

It tries to load `node_modules/ng2-highcharts.js` which does not exists and fails. It should look for `node_modules/ng2-highcharts/index.js` which exisits and it would work.

Importing it like this:

```typescript
import { Ng2Highcharts } from 'ng2-highcharts/index';
```

Solves the problem, but it's not the common.

**Comment by Bigous** [comment]
I think it's more a systemjs-builder problem thou.

**Comment by ckapilla** [comment]
Did you try adding something like this to the packages section of the systemjs config?

      'ng2-highcharts': {
        main: 'index.js',
        defaultExtension: 'js'
      },

**Comment by Bigous** [comment]
Changing the `build.bundles.app.ts` from:
```typescript
/**
 * Executes the build process, bundling the JavaScript files using the SystemJS builder.
 */
export = (done: any) => {
  let builder = <any> new Builder(SYSTEM_BUILDER_CONFIG);
  builder
    .buildStatic(join(TMP_DIR, BOOTSTRAP_MODULE),
                 join(JS_DEST, JS_PROD_APP_BUNDLE),
                 BUNDLER_OPTIONS)
    .then(() => done())
    .catch((err:any) => done(err));
};
```
to
```typescript
/**
 * Executes the build process, bundling the JavaScript files using the SystemJS builder.
 */
export = (done: any) => {
  let builder = <any> new Builder(SYSTEM_BUILDER_CONFIG);
  builder.config({
    packages: {
      'ng2-highcharts': {
        main: 'index.js',
        defaultExtension: 'js'
      }
    }
  });
  builder
    .buildStatic(join(TMP_DIR, BOOTSTRAP_MODULE),
                 join(JS_DEST, JS_PROD_APP_BUNDLE),
                 BUNDLER_OPTIONS)
    .then(() => done())
    .catch((err:any) => done(err));
};
```
as suggested by @ckapilla works too, but again, it's configure systemjs to do what should be the default behaviour. For now I'll use the `'ng2-highcharts/index'` form which I think that is less invasive.

I don't really know if this is the right forum to put the issue, what do you thing @mgechev ? I've wrote it here so we could document it for others, but it seems to me that we should just wait it to be address by systemjs-builder or systemjs itself.

Or we could put it at `seed.config.js` which is overridden by `project.config.js` and so it could be configurable at the project level too...

**Comment by Bigous** [comment]
Or at `SYSTEM_BUILDER_CONFIG` in the project.

**Comment by mgechev** [comment]
The SystemJS builder should be able to discover the main file based on the `package.json` metadata. Most likely we're using outdated version of the package so we should update, however, I remember there were a lot of issues with the production build under windows when we tried to apply the latest version.

**Comment by vyakymenko** [comment]
@Bigous , I have `highcharts` in the real project. Here is guide how to use:
`$ npm install angular2-highcharts --save`

`your.component.ts`
```ts
import { CHART_DIRECTIVES } from 'angular2-highcharts/index';

export class YourComponent implements OnInit {

chartOptions: any;

constructor() {
 this.chartOptions = { } // Chart config here.
}
```

`your.component.html`
```html
<div>
<chart [options]="chartOptions"></chart>
</div>
```
