### ISSUE TITLE
npm run test.watch do not work

### ISSUE THREAD

**Issue by netstart** [mgechev/angular2-seed#1242]
![image](https://cloud.githubusercontent.com/assets/200232/17906543/2f5bb322-694e-11e6-9966-08dc19b990b8.png)

**Comment by mgechev** [comment]
The script is [here](https://github.com/mgechev/angular2-seed/blob/master/package.json#L14). Most likely you haven't updated your seed version.

**Comment by netstart** [comment]
Yes, you wright!

But, in actual seed version has problem in windows to run > nm run test.watch



![image](https://cloud.githubusercontent.com/assets/200232/17932953/972e0e92-69e8-11e6-9131-65fb7b075a6f.png)
