### ISSUE TITLE
cannot run with forever start -c "npm run serve.prod"  ! please help!

### ISSUE THREAD

**Issue by kahnle** [mgechev/angular2-seed#1245]
> angular2-seed@0.0.0 serve.prod /Users/hanle/Documents/workspace/project
> gulp serve.prod --color --config-env prod "/Users/hanle/Documents/workspace/project/tools/tasks/project"

[^[[90m11:22:48^[[39m] Loading tasks folder ^[[33m/Users/hanle/Documents/workspace/project/tools/tasks/seed^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.assets.dev^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.assets.prod^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.bundles.app^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.bundles^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.docs^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.html_css^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.index.dev^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.index.prod^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.js.dev^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.js.e2e^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.js.prod^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.js.test^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/build.js.tools^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/check.versions^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/clean.all^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/clean.coverage^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/clean.dev^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/clean.prod^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/clean.tools^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/copy.js.prod^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/css-lint^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/e2e^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/generate.manifest^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/karma.start^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/serve.coverage^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/serve.docs^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/server.prod^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/server.start^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/tslint^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/watch.dev^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/watch.e2e^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/watch.test^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/seed/webdriver^[[39m
[^[[90m11:22:48^[[39m] Loading tasks folder ^[[33m/Users/hanle/Documents/workspace/project/tools/tasks/project^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/project/build.fonts^[[39m
[^[[90m11:22:48^[[39m] Registering task ^[[33m~/Documents/workspace/project/tools/tasks/project/sample.task^[[39m
[^[[90m11:22:48^[[39m] Using gulpfile ^[[35m~/Documents/workspace/project/gulpfile.js^[[39m
[^[[90m11:22:48^[[39m] ^[[31mTask '/Users/hanle/Documents/workspace/project/tools/tasks/project' is not in your gulpfile^[[39m
[^[[90m11:22:48^[[39m] Please check the documentation for proper gulpfile formatting

**Comment by mgechev** [comment]
Hey @kahnle why you need forever?  `npm run serve.prod` should not fail it's execution and is also not intended for production use. What you should do is to deploy the content of `dist/prod` to your production environment (i.e. just copy/paste the directory's content).
