### ISSUE TITLE
npm run test.watch do not work in actual seed version on MS Windows 10

### ISSUE THREAD

**Issue by netstart** [mgechev/angular2-seed#1246]
In actual seed version has problem in Microsoft Windows to execute: nm run test.watch

![image](https://cloud.githubusercontent.com/assets/200232/17933050/f6962298-69e8-11e6-9957-63f3c7f8d8eb.png)

**Comment by mgechev** [comment]
You can take a look at this [issue here](https://github.com/Workiva/karma-jspm/issues/97). The way to go is to either increase the limit with of open files with `ulimit -n 10480` or to reduce the amount of watched files in `karma.config.js`.
