### ISSUE TITLE
prod build: lang_1.global.System.import is not a function ; 

### ISSUE THREAD

**Issue by Marcelh29** [mgechev/angular2-seed#1253]
I lazy load my component:

 { path: 'dashboard', loadChildren: 'app/+dashboard/dashboard.module' },

When I run the dev build its works fine. When I run the prod build I get the following error:
lang_1.global.System.import is not a function ; 

It goes wrong in this part of the code: 

                var _this = this
                  , _a = path.split(_SEPARATOR)
                  , module = _a[0]
                  , exportName = _a[1];
                return void 0 === exportName && (exportName = "default"),
                lang_1.global.System["import"](module).then(function(module) {
                    return module[exportName]

 path = app/manager/+dashboard/dashboard.ma.page.module
_SEPARATOR = #

**Comment by mgechev** [comment]
Yes, that is because we're bundling the application as a commonjs module now. Currently the production build doesn't support lazy loading but it's in the roadmap.

**Comment by dfaglioni** [comment]
is there any prevision to support lazy loading?

**Comment by mgechev** [comment]
https://github.com/mgechev/angular2-seed/issues/864#issue-154456682
