### ISSUE TITLE
What is the best way to upgrade seed project?

### ISSUE THREAD

**Issue by abhibly** [mgechev/angular2-seed#1255]
Hello...I'm using an early version of angular2-seed with angular2-version-RC1. A lot has been changed in RC5 and i want to update my seed project.
I am thinking about these options for updating the seed->
1.Should i be replacing all other folders other than the src folder where i have my code?
2.Should i take a look at all the files that have been changed and try to make those changes to my existing Project? 
is there a better way to do this? Can someone suggest me the easiest way to update.Thank you

**Comment by ludohenin** [comment]
You should have a look here https://help.github.com/articles/syncing-a-fork/
