### ISSUE TITLE
> angular2-seed@0.0.0 postinstall D:\Code\smartgitCode\GoldRushStreet_new\grs-cl ient > typings install && gulp check.versions && npm prune && gulp webdriver  typings ERR! message Unable to resolve "github:gdi2290/typed-xhr2#69f2b8d40d0cd4 07c1b2a2f2f41fecc6852cabbb" from "xhr2"

### ISSUE THREAD

**Issue by clp334264003** [mgechev/angular2-seed#1256]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.
> angular2-seed@0.0.0 postinstall D:\Code\smartgitCode\GoldRushStreet_new\grs-cl
ient
> typings install && gulp check.versions && npm prune && gulp webdriver

typings ERR! message Unable to resolve "github:gdi2290/typed-xhr2#69f2b8d40d0cd4
07c1b2a2f2f41fecc6852cabbb" from "xhr2"
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/g
di2290/typed-xhr2/69f2b8d40d0cd407c1b2a2f2f41fecc6852cabbb/typings.json"
typings ERR! caused by getaddrinfo EAI_AGAIN raw.githubusercontent.com:443

typings ERR! cwd D:\Code\smartgitCode\GoldRushStreet_new\grs-client
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "F:\\SoftwareInstallation\\nodejs\\node.exe" "D:\\Code\\sma
rtgitCode\\GoldRushStreet_new\\grs-client\\node_modules\\typings\\dist\\bin.js"
"install"
typings ERR! node -v v5.10.1
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fseve
nts:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\SoftwareInstallation\\nodejs\\node.exe" "F:\\SoftwareInstalla
tion\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `typings install && gulp check.version
s && npm prune && gulp webdriver`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'typings install &
& gulp check.versions && npm prune && gulp webdriver'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriv
er
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Code\smartgitCode\GoldRushStreet_new\grs-client\npm-debug.log

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
Most likely you're behind a proxy and typings cannot install the ambient type definitions. Take a look [here](https://github.com/typings/typings/issues/106).
