### ISSUE TITLE
Cannot extend EnvConfig within env.config.ts

### ISSUE THREAD

**Issue by dalpiazk** [mgechev/angular2-seed#1260]
Changes to env.config.ts are not reflected in the EnvConfig type used in the ts files within tools/env. This would seem to be because tsconfig.json in the base directory is excluding src, which contains env.config.ts. 

To reproduce:
1) Build the project
2) Add a property to EnvConfig within src/client/app/shared/config/env.config.ts
3) Set a value for that property within tools/env/base.ts
At this point, the IDE should error, but optionally you can try to build again to receive an error as well.

For a workaround, src can be removed from tsconfig.json, at the cost of a longer build time.

**Comment by mgechev** [comment]
Yes, changes in `tools/env` are reflected in `env.config.ts`.

**Comment by mgechev** [comment]
I cannot reproduce the issue, although it makes sense to have this issue given that we have `src` in the exclude array of `./tsconfig.json`.

**Comment by mgechev** [comment]
I cannot reproduce the issue with the latest changes introduced by https://github.com/mgechev/angular2-seed/commit/791b8103f500c18da3eea7c48ee0ebf7be5d501c. Tried building the project and also VSCode + WebStorm.
