### ISSUE TITLE
CI - Unable to compyle TypeScript

### ISSUE THREAD

**Issue by sirgalleto** [mgechev/angular2-seed#1266]
Yesterday I has a problem compyling the Typescript in my developer enviroment and I fixed this error with `tsc --project tsconfig.json`, but in the drone CI I can't fix the bug. 

The result of the console has the following error: 

```TSError: ⨯ Unable to compile TypeScript
tools/utils/seed/tasks_tools.ts (6,26): Cannot find module 'tildify'. (2307)```

**Comment by sirgalleto** [comment]
@gvsdan fixed it removing `tools/manual_typings/seed/tildify.ts`.

**Comment by gvsdan** [comment]
we didn't remove the tildify.ts and replace it with the d.ts file instead and we had a tildify.js file in our folder we remove the file and solve the problem thanks
