### ISSUE TITLE
Injection of external dependencies does not seem to work for build.prod

### ISSUE THREAD

**Issue by seustachi** [mgechev/angular2-seed#1270]
I tried to follow the instructions of the page : 
https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles

Maybe I don't understand what is supposed to be produced.

In the case of the **DEV** build, it works as I expect it to : I get (or it get injected elsewhere, depending of the configuration)

` 
  <script src="/node_modules/bootstrap/dist/js/bootstrap.min.js?1472656786779"></script>
  `

However, in the case of PROD, nothing is injected in index.html (+ I would expect the file to be copied somewhere in the dist folder, in order to have a self-contained, deployable app).

So I believe there is something broken in case of PROD build for external dependencies injection

**Comment by mgechev** [comment]
For `prod` bootstrap will get part of `app.js` file. Take a look at [build.bundles.ts](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.bundles.ts).
