### ISSUE TITLE
Trying to integrate with Angular 2 Schema Form - Getting error

### ISSUE THREAD

**Issue by anupamarachuri** [mgechev/angular2-seed#1278]
I am trying to integrate with https://github.com/makinacorpus/angular2-schema-form

import { disableDeprecatedForms, provideForms} from "@angular/forms"
import { WidgetRegistry } from "angular2-schema-form";

bootstrap: [AppComponent,[disableDeprecatedForms(),provideForms(),WidgetRegistry]]

My requirement is to have some pages dynamic and some pages static. So I tried both bootstrapping inside the the main.ts, about.module.ts and also inside the app.module.ts, but got the same error.

I am pretty new to Angular 2 and not able to find out why the integration is not working. Could you please help in integrating this?

![error](https://cloud.githubusercontent.com/assets/20385639/18183287/a27ab5b4-7061-11e6-9524-4e607ee6d9b2.PNG)

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
