### ISSUE TITLE
List gulp-cli as a prerequisite

### ISSUE THREAD

**Issue by savcha** [mgechev/angular2-seed#1280]
If gulp-cli is not installed globally the "npm install" command will fail on the postinstall 
"postinstall": "typings install && <b>gulp check.versions</b> && npm prune && gulp webdriver",

Would be helpful to newcomers if documentation mentioned that gulp-cli should be installed
`npm install -g gulp-cli`

**Comment by robstoll** [comment]
I did not install gulp before and npm install worked fine for me

**Comment by mgechev** [comment]
Global gulp dependency should not be required. `npm` uses executables from `./node_modules/.bin` and since it's postinstall script `gulp` should be already available there.
