### ISSUE TITLE
Can't import module when running tsc --project tsconfig.json

### ISSUE THREAD

**Issue by liuyangc3** [mgechev/angular2-seed#1281]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
```
git clone --depth 1 https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install
tsc --project tsconfig.json
```
_What steps should we try in your demo to see the problem?_

**Current behavior**
```
> tsc --project tsconfig.json

1 import { join } from 'path';
                       ~~~~~~~
tools/config/project.config.ts(1,22): error TS2307: Cannot find module 'path'.

2 import { argv } from 'yargs';
                       ~~~~~~~

tools/config/seed.config.ts(2,22): error TS2307: Cannot find module 'yargs'.
```

**Expected/desired behavior**
it worked fine when this repo use RC5, I used this seed in my project before on the same Windows box.

**Other information**
OS Win10

node v4.4.7

npm  v3.10.7

**Comment by mgechev** [comment]
Would you also try:

```bash
npm i -g typings
typings install
```

**Comment by liuyangc3** [comment]
@mgechev  thx
I don't kouwn why but it works now!

**Comment by mgechev** [comment]
It was not supposed to be required this time neither..in the `postinstall` phase some of the typings were missing on any reason.
