### ISSUE TITLE
Error loading http://localhost:5555/node_modules/@angular2-material/button/button.js as "@angular2-material/button/button"

### ISSUE THREAD

**Issue by clp334264003** [mgechev/angular2-seed#1287]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by vyakymenko** [comment]
@clp334264003 , [firtst wiki link (Add external dependency)](https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency), [second wiki link (Add external scripts and styles)](https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles)
