### ISSUE TITLE
Error in Chrome console when npm start 

### ISSUE THREAD

**Issue by liuyangc3** [mgechev/angular2-seed#1292]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
git pull
npm install
npm start
_What steps should we try in your demo to see the problem?_

**Current behavior**
can not open index in broswer
in terminal :
```
src\client\app\main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'.
```
and Chrome console
![image](https://cloud.githubusercontent.com/assets/6705844/18235695/b5deef3e-7350-11e6-827b-218228bb9b5f.png)

Chrome index
![image](https://cloud.githubusercontent.com/assets/6705844/18235733/2e06f2b8-7351-11e6-917c-3a48a8cb6e08.png)

**Expected/desired behavior**
should be no error

**Other information**
OS Windows 10
node 4.4.7
npm 3.10.7
Chrome  53.0.2785.89 m (64-bit)

**Comment by liuyangc3** [comment]
in system-config.js I see:
```
System.config(JSON.parse('[object Object]'));
```

**Comment by mgechev** [comment]
Thanks for reporting the issue! Should be fixed in master.

**Comment by liuyangc3** [comment]
thx

**Comment by daftfox** [comment]
I ran into the same issue while trying to run the tests.

Steps to reproduce and a minimal demo of the problem
git pull
npm install
npm run webdriver-start
npm run serve.e2e

Current behavior
can not open index in browser
in terminal :
src\client\app\main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'.

Chrome
Identical to @liuyangc3

Chrome index
Identical to @liuyangc3

Expected/desired behavior
should be no error

Other information
OS Windows 10
node 4.4.7
npm 3.10.7
Chrome 52.0.2743.116 m (64-bit)
