### ISSUE TITLE
XHR error (404 Not Found) loading app/main.js

### ISSUE THREAD

**Issue by dereklin** [mgechev/angular2-seed#1293]
I have justed clone the app and tried running it at 8:15PM PST.
![angular2-seed-error](https://cloud.githubusercontent.com/assets/2231799/18236744/6d42dbd6-72de-11e6-81f8-a643c4ac4531.JPG)

**Comment by liuyangc3** [comment]
try npm install

**Comment by dereklin** [comment]
npm install shows two warnings:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```
Is fsevents the issue?

**Comment by oehm-smith** [comment]
Upon a `npm run build.dev` I see:

    src/client/app/main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'.

I don't know if it is related.  Though will investigate.

**Comment by dereklin** [comment]
I am using Windows 10.  Could you guys do me a favor? Could you clone the repo now and do npm install and npm start and see if you see what I see?

**Comment by mgechev** [comment]
Thanks for reporting the issue! Should be fixed in master.

**Comment by oehm-smith** [comment]
Great thanks, that works.
