### ISSUE TITLE
How to use the environment configuration to set different API endpoints.

### ISSUE THREAD

**Issue by factoryberlin** [mgechev/angular2-seed#1294]
It is very unclear how to set different API endpoints via the `env/prod.ts` and `env/dev.ts` files and how to access these values in an app, for example in a service that calls an external API. Clarification and an example would help a lot! Should I modify the files directly? Should I check the current environment? And if so, how? 

Thanks.

**Comment by Flood** [comment]
It's not that hard. Here is an example.

//dev.ts
const DevConfig: EnvConfig = {
	ENV: 'DEV',
	API: 'wss://devapi.com'
};

//prod.ts
const ProdConfig: EnvConfig = {
	ENV: 'PROD',
	API: 'wss://prodapi.com/'
};

And then in your app.module.ts, import env.config.ts
import { Config } from '../../env.config';

Use it like this:
@NgModule({
	imports: [
		CommonModule,
		FormsModule,
		HttpModule
	],
	providers: [
		{provide:$WebSocket,  useValue: new $WebSocket(Config.API) } //Will be different depending on environment.
	]
})
