### ISSUE TITLE
index.html script include path /app/system-config.js does not consider APP_BASE

### ISSUE THREAD

**Issue by omerfarukyilmaz** [mgechev/angular2-seed#1295]
**Current behavior**

The script in index.html

`<script src="/app/system-config.js"></script>`

does not consider APP_BASE set via config files or at runtime via the --base flag

**Other information**

I am not 100% certain but I think:

`<script src="<%= APP_BASE %>app/system-config.js"></script>`

should solve the problem?

**Comment by ludohenin** [comment]
Can you send a PR ?
