### ISSUE TITLE
build.html_css freezes for production build.

### ISSUE THREAD

**Issue by Flood** [mgechev/angular2-seed#1297]
**Steps to reproduce and a minimal demo of the problem**
ENABLE_SCSS = true;
run "npm run build.prod"

**Current behavior**
The build.html_css task freezes. It does not show any error message and I have to press ctrl+c to cancel the build.

**Other information**
I have tried hard code the isProd flag to false in the task, then it finishes the task but complaining about missing css files in later steps.

**Comment by danielcrisp** [comment]
I'm having a similar problem right now actually, but for me it _eventually_ completes after about 3-4 minutes.

I get these sort of errors:

```
Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open '/project/dist/tmp/app/routes/+about/about.component.css'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: /project/v2/dist/tmp/app/routes/+about/about.component.css
    fileName: /project/v2/dist/tmp/app/routes/+about/about.component.ts
```

I thought that it was because the component was specifying a `*.css` file but in the src directory it was a `*.scss` file, but the `about.component` in the example above was actually using a `css` file.

**Comment by danielcrisp** [comment]
Looks related to https://github.com/mgechev/angular2-seed/issues/1088 and https://github.com/mgechev/angular2-seed/issues/1086

**Comment by Flood** [comment]
I have the latest seed and still experiencing this though. 

The path in the error message looks weird, why is 'routes' included?

**Comment by Flood** [comment]
Oh, now it was succeded, after 9 minutes. Something must be wrong?

**Comment by danielcrisp** [comment]
That's just my app architecture

**Comment by mgechev** [comment]
I can't reproduce this issue. What pull the latest changes & run `npm install` after that? I reverted back to inlining the Angular templates by default.

**Comment by Flood** [comment]
No worries! I wounder if it could be that I have bootstraps .scss files in my solution, and that takes 10 minutes to compile?

My collegue also said that if you for example have an "@import 'filePathDoesNotExist'" in your .scss it freezes on the same step (even the dev.build), and gives no error message.

**Comment by Flood** [comment]
So I've solved the long compile time now. In my css folder I have this structure.

- css
- -bootstrap
- -buttons.scss
- -colors.scss
- -main.scss

The build.html_css.ts has this function

```
function getExternalScss() {
  return DEPENDENCIES.filter(dep => /\.scss$/.test(dep.src)).map(dep => dep.src)
    .concat([join(CSS_SRC, '**', '*.scss')]);
}
```

If I changed to 

```
function getExternalScss() {
  return DEPENDENCIES.filter(dep => /\.scss$/.test(dep.src)).map(dep => dep.src)
    .concat([join(CSS_SRC, 'main.scss')]);
}
```

It works. Then in main.scss I can even fix the order of imports etc.

**Comment by Flood** [comment]
Is this something we can update the seed with?

**Comment by mgechev** [comment]
@Flood thanks for sharing your experience and your findings!

Probably updating the wiki is a better idea? Otherwise we'll couple the build with the format of `main.scss` that you described, i.e. one will be required to include `@import` statements to all the `scss` files in `main.scss`.

**Comment by Flood** [comment]
Of course, no problem! 

Yes, updating the wiki would be a better idea!
