### ISSUE TITLE
Error in build.js.prod and build.js.prod.exp

### ISSUE THREAD

**Issue by sasikumardr** [mgechev/angular2-seed#1300]
**Steps to reproduce and a minimal demo of the problem**
1) Intentionally bring an error in one of app TS file. (I have changed @Component to @Component1 in app.component.ts)
2) comment out tslint in build.prod and build.prod.exp task (in gulpfile.ts)
3) execute either `gulp build.prod` or `gulp build.prod.exp`

**Current behavior**
angular2-seed\tools\tasks\seed\build.js.prod.ts:33
               this.once('finish', () => process.exit(1));

TypeError: _this.once is not a function

**Expected/desired behavior**
gulp task should gracefully exit instead of runtime error.

**Other information**
line no: 32 in build.js.prod  and line no:24 in build.js.prod.exp.ts

changing
`.once('error', (e: any) => {` 
to 
`.once('error', function(e: any) {` 
will solve in this issue.

**Comment by mgechev** [comment]
@sasikumardr would you open a PR with that change? It is weird that the arrow function doesn't work in this case.

**Comment by sasikumardr** [comment]
I have very poor github skills. Haven't tried anything other than browsing before  :stuck_out_tongue:

**Comment by sasikumardr** [comment]
If no one fixes this,  I'll try to open PR this weekend,  after learning through YouTube :D

**Comment by mgechev** [comment]
No worries! If you don't have any git experience, you can open [the](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.js.prod.exp.ts) [files](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.js.prod.ts) and edit them via the web UI. This still works :-).
