### ISSUE TITLE
Best practice for importing ng modules

### ISSUE THREAD

**Issue by doapp-ryanp** [mgechev/angular2-seed#1301]
I looking for guidance on the best way to load an ng module into angular2-seed via the `tools/config/project.config.ts`

For an example I am trying to load [ng-bootstrap](https://ng-bootstrap.github.io/#/getting-started).

I have gotten this to load via the following two methods:

**Method 1**

```javascript
this.SYSTEM_CONFIG_DEV.paths['@ng-bootstrap/ng-bootstrap'] = `${this.APP_BASE}node_modules/@ng-bootstrap/ng-bootstrap`;
this.SYSTEM_CONFIG_DEV.packageConfigPaths.push(`/node_modules/@ng-bootstrap/*/package.json`);
this.SYSTEM_BUILDER_CONFIG.packages['@ng-bootstrap/ng-bootstrap'] = {
    main: 'index.js',
    defaultExtension: 'js'
};
```

**Method 2**

```javascript
this.SYSTEM_CONFIG_DEV.packageConfigPaths.push(`/node_modules/@ng-bootstrap/*/package.json`);
this.mergeObject(this.SYSTEM_BUILDER_CONFIG, {
      packages: {
        '@ng-bootstrap/ng-bootstrap': {
          main: 'index.js',
          defaultExtension: 'js'
        }
      }
    });
```

Is there a better way to load than this? Both of these feel hackish to me, but I'm a total Angular2 noob

**Comment by mgechev** [comment]
Both options work. You're extending the base configuration which is the way to go. 

(Un)Fortunately this is not an Angular specific thing. With the current module loaders landscape there are plenty of different ways to approach which are completely independent for each individual module loader. In angular2-seed, for now, we're using SystemJS and that is the most convenient method.

**Comment by rynop** [comment]
Thanks for the quick response.

The [External dependency docs](https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency#installation) on the wiki make no reference to needing the `this.SYSTEM_CONFIG_DEV.packageConfigPaths.push()` line, however I'm seeing that it is required.  If I don't include the line I get a 404 (in development) trying to find the dependencies `package.json` file.

Am I doing something wrong or are the docs just out of date?
