### ISSUE TITLE
Including leaflet.js works in dev mode, fails in prod.

### ISSUE THREAD

**Issue by tapia** [mgechev/angular2-seed#1304]
I've included leaflet in my project adding this to the NPM_DEPENDENCIES:

      {src: 'leaflet/dist/leaflet.js', inject: true},
      {src: 'leaflet/dist/leaflet.css', inject: true},

And I've coded a component with a simple map. It works perfectly in dev mode, but when I build the prod bundle, the leaflet map fails, without any errors in the console (the map is the only thing broken, the rest of the app works fine).

This is the working map in dev mode:

<img width="1199" alt="captura de pantalla 2016-09-06 a las 22 34 33" src="https://cloud.githubusercontent.com/assets/589897/18290106/79849e2a-7482-11e6-9344-81b5990b181f.png">

And this is the broken production build (note it's not only the map tiles order. If I hover the mouse over the map, it starts re-rendering the map randomly, messing it even more):

<img width="1572" alt="captura de pantalla 2016-09-06 a las 22 35 52" src="https://cloud.githubusercontent.com/assets/589897/18290132/98df76f0-7482-11e6-92ee-6c1b58176176.png">

Since I got no error in the console, I'm completely clueless about what's going on. Any ideas, please?

**Comment by mgechev** [comment]
It seems like a CSS related issue. Would you try to disable `cssnano` and see if it works?

```
// build.html_css.ts
if (isProd) {
/*  processors.push(
    cssnano({
      discardComments: {removeAll: true},
      discardUnused: false,
      safe: true
    })
  ); */
}
```

**Comment by tapia** [comment]
I don't have a task called `build.html_css.ts`, I only have one called `build.scss.ts`, and `cssnano` is already disabled:

```
import * as gulp from 'gulp';
import * as gulpLoadPlugins from 'gulp-load-plugins';
import * as merge from 'merge-stream';
// import * as cssnano from 'cssnano';
import {join} from 'path';
import {APP_SRC, CSS_PROD_BUNDLE, CSS_DEST, APP_DEST, TMP_DIR, ENV, SASS_OPTIONS} from '../../config';
const plugins = <any>gulpLoadPlugins();

// const processors = [
//   autoprefixer({
//     browsers: BROWSER_LIST
//   })
// ];

const isProd = ENV === 'prod';

if (isProd) {
  // processors.push(
  //   cssnano({
  //     discardComments: {removeAll: true}
  //   })
  // );
}

export = () => merge(processComponentScss(), processExternalScss());

function processComponentScss() {
  return gulp.src([
      join(APP_SRC, '**', '*.scss'),
      '!' + join(APP_SRC, 'assets', '**', '*.scss')
    ])
    .pipe(plugins.sass(SASS_OPTIONS))
    .pipe(isProd ? plugins.cached('process-component-css') : plugins.util.noop())
    // .pipe(plugins.postcss(processors))
    .pipe(gulp.dest(isProd ? TMP_DIR: APP_DEST));
}

function processExternalScss() {
  return gulp.src([
      join(APP_SRC, 'assets', '**', '*.scss')
    ])
    .pipe(plugins.sass(SASS_OPTIONS))
    .pipe(isProd ? plugins.cached('process-external-css') : plugins.util.noop())
    // .pipe(plugins.postcss(processors))
    .pipe(isProd ? plugins.concat(CSS_PROD_BUNDLE) : plugins.util.noop())
    .pipe(gulp.dest(CSS_DEST));
}
```

**Comment by mgechev** [comment]
So you have custom fork? Where is the file `build.scss.ts` located? The seed has a task called `build.html_css` which is invoked as part of the production build. Have you disabled it?

**Comment by mgechev** [comment]
Any updates?

**Comment by mgechev** [comment]
@tapia let me know what you find. I think this might be an environment specific issue.
