### ISSUE TITLE
npm run serve.prod -- --app appfoo

### ISSUE THREAD

**Issue by netstart** [mgechev/angular2-seed#1305]
Clone app to appfoo, 
execute 
npm run serve.prod  cause below problem:
![image](https://cloud.githubusercontent.com/assets/200232/18291240/371f6bf2-745d-11e6-859c-a0ac138f59da.png)

execute 
npm run serve.prod -- --app appfoo
or
npm start -- --app appfoo
cause the same problem

**Comment by mgechev** [comment]
Are you using the latest version of the seed? There were related issues which I fixed yesterday and todai.

**Comment by netstart** [comment]
Yes,  I cloned the repository a few minutes

![image](https://cloud.githubusercontent.com/assets/200232/18291480/3bd925ec-745e-11e6-93a3-5be12a325d14.png)

**Comment by tinuF** [comment]
Might be related to https://github.com/mgechev/angular2-seed/issues/1300. If there's one ts error, serve.prod will fail even if tslint is commented out in gulpfile.

**Comment by tinuF** [comment]
Might be related to https://github.com/mgechev/angular2-seed/issues/1300. If there's one ts error, serve.prod will fail even if tslint is commented out in gulpfile.

**Comment by sasikumardr** [comment]
Line number 26 in build.js.prod make sure that ${BOOTSTRAP_FACTORY_PROD_MODULE}.ts not included in files to compile. Interesting to see it got picked up. 
Can you please check again what src files are considered in your local copy and master branch?

**Comment by mgechev** [comment]
@netstart `build.js.prod` does not include `${BOOTSTRAP_FACTORY_PROD_MODULE}.ts` which is the only file which requires `app.module.ngfactory.ts` so most likely you're not using the latest version. Make sure you've recompiled your build files if you're on windows.

**Comment by netstart** [comment]
Sorry, but no.

I Cloned the repository again, and we have problem yet

![image](https://cloud.githubusercontent.com/assets/200232/18348577/83b119de-75a2-11e6-98ab-0f8adf22a8d8.png)

![image](https://cloud.githubusercontent.com/assets/200232/18348607/b69b4bee-75a2-11e6-933a-a94e4e72e14c.png)

**Comment by sasikumardr** [comment]
Can you plz paste your build.js.prod content here? Also seed.config.ts showing BOOTSTRAP_MODULE, BOOTSTRAP_PROD_MODULE values

**Comment by netstart** [comment]
In the linux we have problem to.

Need copy 'app' directory to 'appfoo' for example, this action will reproduce this situation

```
[09:18:16] Finished 'copy.prod' after 130 ms
[09:18:16] Starting 'build.js.prod'...
dist/tmp/app/main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'.
[09:18:22] TypeScript: 1 semantic error
[09:18:22] TypeScript: emit succeeded (with errors)

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build.prod" "--" "--app" "foo"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 build.prod: `gulp build.prod --color --config-env prod "--app" "foo"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 build.prod script 'gulp build.prod --color --config-env prod "--app" "foo"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color --config-env prod "--app" "foo"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pdi/dev/workspace/angular2-seed/npm-debug.log
pdi@mint-douglas ~/dev/workspace/angular2-seed $
```


build.js.prod content, below
```
import * as gulp from 'gulp';
import * as gulpLoadPlugins from 'gulp-load-plugins';
import { join } from 'path';

import { BOOTSTRAP_FACTORY_PROD_MODULE, TMP_DIR, TOOLS_DIR } from '../../config';
import { makeTsProject, templateLocals } from '../../utils';

const plugins = <any>gulpLoadPlugins();

const INLINE_OPTIONS = {
  base: TMP_DIR,
  useRelativePaths: true,
  removeLineBreaks: true
};

/**
 * Executes the build process, transpiling the TypeScript files for the production environment.
 */

export = () => {
  let tsProject = makeTsProject();
  let src = [
    'typings/index.d.ts',
    TOOLS_DIR + '/manual_typings/**/*.d.ts',
    join(TMP_DIR, '**/*.ts'),
    '!' + join(TMP_DIR, `**/${BOOTSTRAP_FACTORY_PROD_MODULE}.ts`)
  ];
  let result = gulp.src(src)
    .pipe(plugins.plumber())
    .pipe(plugins.inlineNg2Template(INLINE_OPTIONS))
    .pipe(plugins.typescript(tsProject))
    .once('error', function(e: any) {
      this.once('finish', () => process.exit(1));
    });


  return result.js
    .pipe(plugins.template(templateLocals()))
    .pipe(gulp.dest(TMP_DIR))
    .on('error', (e: any) => {
      console.log(e);
    });
};

```

**Comment by sasikumardr** [comment]
Can you please provide BOOTSTRAP variables in your seed.config.ts file also?

**Comment by netstart** [comment]
Can you see on my fork: https://github.com/netstart/angular2-seed

To see the error, If you clone my fork, execute 
npm run serve.prod -- --app foooo

**Comment by sasikumardr** [comment]
Ok found the problem.

1) Your src has 2 folders 'app' and  'foooo' (both has main-prod.ts file)
2) Your seed.config file has BOOTSTRAP_FACTORY_PROD_MODULE set as 'foooo/main-prod.ts' when you pass argv['app'] as foooo
3) in build.js.prod.ts file, we are removing 'foooo/main-prod.ts', but remaining set of ts files include 'app/main-prod.ts' file. - this will give above error

I suppose this seed project expects only one app directory in src folder. 

Possible Solutions:
1) change your copy.prod.ts to include only your 'foooo' specific ts files (from BOOTSTRAP_DIR) to temp directory
2) Somebody needs to change this seed project to support multiple app folders

**Comment by netstart** [comment]
I understand your suppose, but this seed support mult app, 

We can check it in: https://github.com/mgechev/angular2-seed/tree/multi-apps

And in the readme we have
![image](https://cloud.githubusercontent.com/assets/200232/18351404/747bfaac-75b0-11e6-9c9a-929d43ec58d0.png)

**Comment by sasikumardr** [comment]
Sorry. My fault in understanding project's capabilities. 

In that case needs to add fix

I think in build.js.dev
Changing
```
let src = [
    join(APP_SRC, '**/*.ts'),
    '!' + join(APP_SRC, BOOTSTRAP_FACTORY_PROD_MODULE + '.ts'),
    '!' + join(APP_SRC, '**/*.spec.ts'),
    '!' + join(APP_SRC, '**/*.e2e-spec.ts')
  ];
```
to 
```
let src = [
    join(APP_SRC, BOOTSTRAP_DIR, '**/*.ts'),
    '!' + join(APP_SRC, BOOTSTRAP_FACTORY_PROD_MODULE + '.ts'),
    '!' + join(APP_SRC, '**/*.spec.ts'),
    '!' + join(APP_SRC, '**/*.e2e-spec.ts')
  ];
```

Should solve problem with dev build. Similarly we have to include only BOOTSTRAP_DIR in copy.prod task

**Comment by sasikumardr** [comment]
My bad again. I didn't consider sharing codes between apps. In that case you need to exclude all main-prod.ts files from src instead of using` '!' + join(APP_SRC, BOOTSTRAP_FACTORY_PROD_MODULE + '.ts').`
