### ISSUE TITLE
Feat.req.: protractor.conf.js chrome i18n config

### ISSUE THREAD

**Issue by davidgfolch** [mgechev/angular2-seed#1306]
Hi all,

I require a i18n default config for protractor tests, maybe you want to include it in seed:

protractor.conf.js:

capabilities: {
    browserName: 'chrome'
    ,chromeOptions: { args: ['lang=es-ES']}
  },

**Comment by mgechev** [comment]
Sure, would you open a PR with it?

**Comment by mgechev** [comment]
Closing it since there are no updates and the feature is not requested by anyone else.
