### ISSUE TITLE
There is no directive with "exportAs" set to "ngForm" ("ter">                 <form class="uloginregister-form" [formGroup]="form" (ngSubmit)="onSubmit()" [ERROR ->]#registerForm="ngForm">                     <div class="group-input">                         <span"): RegisterComponent@5:93 Can't bind to 'formGroup' since it isn't a known property of 'form'. ("1> -->

### ISSUE THREAD

**Issue by clp334264003** [mgechev/angular2-seed#1307]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.
There is no directive with "exportAs" set to "ngForm" ("ter">
                <form class="uloginregister-form" [formGroup]="form" (ngSubmit)="onSubmit()" [ERROR ->]#registerForm="ngForm">
                    <div class="group-input">
                        <span"): RegisterComponent@5:93
Can't bind to 'formGroup' since it isn't a known property of 'form'. ("1> -->

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by sasikumardr** [comment]
Did you import `ReactiveFormsModule` in AppModule?

```
import { FormsModule, ReactiveFormsModule  }   from '@angular/forms';

@NgModule({
    imports: [
        ...
        FormsModule,
        ReactiveFormsModule
    ],
    ...
})
export class AppModule { }
```

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.

**Comment by amrography** [comment]
You need to import `ReactiveFormsModule` in `.spec` files too. In both `app.component.spec.ts` and _where you have the form_ `*.spec.ts`.
