### ISSUE TITLE
404 "node_modules/symbol-observable.js" when importing Redux

### ISSUE THREAD

**Issue by bbaki** [mgechev/angular2-seed#1308]
Hey,
I get the following error while trying to create a store with redux. This worked yesterday and the only thing that could have broken it was `npm install typings` and `typings install`. Any idea what could have gone wrong?

I'm using the older rc5 version.

```
(index):78 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/symbol-observable.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1473277441313:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1473277441313:356:38)
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1473277441313:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1473277441313:423:34)
	Error loading http://localhost:5555/node_modules/symbol-observable.js as "symbol-observable" from http://localhost:5555/node_modules/redux/lib/createStore.js "Report this error at https://github.com/mgechev/angular2-seed/issues"
```

I've spent like the last 2-3 hours trying to fix this. If there is no easy answer to how to fix this just close this issue. Thanks in advance.

**Comment by mgechev** [comment]
I'd recommend you to:

```
git remote add upstream https://github.com/mgechev/angular2-seed
git pull upstream master
```

Let me know if it doesn't work after that. In general, I'm surprised that you're getting this error if you're using rc5 because it comes with new version of rxjs.

**Comment by bbaki** [comment]
I've ditched rc5 in favor of rc6 but with no real success. I get the same problem whenever I try to add Redux, maybe ng-redux would work. I guess I'll try aurelia and see how that goes. Thanks anyway.
