### ISSUE TITLE
build.prod issue

### ISSUE THREAD

**Issue by canygt27** [mgechev/angular2-seed#1317]
Hello,

When I write npm run-script build.prod -- --scss it is building okey, but when I click index.html in prod directory it is saying that

Failed to load resource: net::ERR_FILE_NOT_FOUND file:///css/main.css?1473518410621
Failed to load resource: net::ERR_FILE_NOT_FOUND  file:///js/shims.js?1473518410618 
Failed to load resource: net::ERR_FILE_NOT_FOUND  file:///js/app.js?1473518410619 

Can you help me?

*P.S: I am new on the angular2-seed.

**Comment by mgechev** [comment]
Move `dist/prod` to the root directory of your web server or start one in the directory.
