### ISSUE TITLE
"Element is not exported" warning In Webstorm

### ISSUE THREAD

**Issue by lihaibh** [mgechev/angular2-seed#1318]
Im receiving an error in Webstorm IDE regarding all the tasks that import "tools/config.ts".
The IDE could not resolve the properties properly for example: APP_BASE, PORT from "ProjectConfig" object..
in order to access these properties i have to import like this:
import * as config from '../../config';
then access by:
config.APP_BASE

**Comment by mgechev** [comment]
Would you open a PR with the change?
