### ISSUE TITLE
help with dev build and prod build

### ISSUE THREAD

**Issue by chungtinhlakho** [mgechev/angular2-seed#1320]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by chungtinhlakho** [comment]
I am fairly new at this, I'm hoping to get some help to lead me in the right direction.  

My production environment is not node and my application will not the the only thing on my webserver.  Hence, I need the app to pull resources from it's current directory instead of root/resources...  this project's  APP_BASE is set to '/' which starts at root.  I modify it to '/dist/prod/' so that it works when i build prod.  However, doing so will make the dev also pulling resource from '/dis/prod/', how can i modify the seed.config.ts so that when i build, the resource is coming from the current directory whereever the project folder is at?

thanks lot

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
