### ISSUE TITLE
Help with Gulp configuration

### ISSUE THREAD

**Issue by Podkekette** [mgechev/angular2-seed#1321]
Hi all,

I just did migration from Ng2 rc5 to RC6. 

When I run the app, I have 2 errors with gulp and the systemjs.config.

Please help, I am on it since wednesday 5th september :(
![xhrerror](https://cloud.githubusercontent.com/assets/12861710/18432270/56bfeaf8-78e1-11e6-83c2-11aa8857796f.PNG)

**Comment by mgechev** [comment]
How did you do the migration? Did you also updated the version of the seed with `git pull upstream master`?
