### ISSUE TITLE
Import external librairies import

### ISSUE THREAD

**Issue by sylc** [mgechev/angular2-seed#1325]
Hi there,
I had trouble importing angular2-google-maps package. SystemJs would not find the right file.
I have followed the wiki and added 

```
this.SYSTEM_CONFIG_DEV.paths["angular2-google-maps"] =        `${this.APP_BASE}node_modules/angular2-google-maps`;

this.SYSTEM_BUILDER_CONFIG.packages["angular2-google-maps/core"] =       { main: 'core.umd.js', defaultExtension: 'js' }
```

error is:
`error: cannot find node_modules/angular2-google-maps/core.js
`

I have tried few other things but SystemJS would always try it to load angular2-google-maps/core.js, instead of angular2-google-maps/core/core.umd.js

**to reproduce:** 
`npm install angular2-google-maps` and follow [package link](https://github.com/SebastianM/angular2-google-maps)

**Work around:** 
i believe the problem is in seed.config.ts from 

```
packageConfigPaths: [
    `/node_modules/*/package.json`,
    `/node_modules/**/package.json`,
    `/node_modules/@angular/*/package.json`
    ],
```

Finally, I got it to work by rewriting seed.config.ts using Heroes app as example

 ```
  SYSTEM_CONFIG_DEV: any = {
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: '/app/',
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs': 'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      }

    }
 ```

and in project.config.ts:
 ```
    this.SYSTEM_CONFIG_DEV.map['angular2-google-maps'] =        `${this.APP_BASE}node_modules/angular2-google-maps` ; 
 
    this.SYSTEM_CONFIG_DEV.packages['angular2-google-maps/core']=   { main: 'core.umd.js', defaultExtension: 'js' };

```

SystemJS documentation advice to use _map_ instead of _paths_ . Is there any reason in the angular2_seed build process to keep using _paths_?

thanks

**Comment by vyakymenko** [comment]
@sylc , Hello, I have `angular2 google maps` in my project:

How to for old angular versions `rc.4`:
`project.config.ts`
```ts
...
    this.SYSTEM_CONFIG_DEV.paths['angular2-google-maps/core'] =
      `${this.APP_BASE}node_modules/angular2-google-maps/core/core.umd.js`;

    this.SYSTEM_BUILDER_CONFIG.packages['angular2-google-maps/core'] = {
      main: 'core.umd.js',
      defaultExtension : 'js'
    };
...
```
Then in `main.ts`:
```ts
..
  GOOGLE_MAPS_PROVIDERS,
  provideLazyMapsAPILoaderConfig({
    apiKey: 'YOUR_SECURE_GOOGLE_API_KEY',
  }),
..
```

For new angular version, you just need this [GUIDE](https://angular-maps.com/docs/getting-started.html#angular2-google-maps-setup) :)

**Comment by sylc** [comment]
@vyakymenko, thanks. 

I was missing the `/core` in this.SYSTEM_CONFIG_DEV.paths['angular2-google-maps**/core**']

**Comment by vyakymenko** [comment]
@sylc , your welcome.

**Comment by emilio-simoes** [comment]
I still have a problem, when I try yo run the unit tests I get a "(SystemJS) XHR error (404 Not Found)"error:

30 09 2016 17:28:32.085:WARN [web-server]: 404: /node_modules/angular2-google-maps/package.json
Chrome 53.0.2785 (Windows 10 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/node_modules/angular2-google-maps/package.json
        Error: XHR error (404 Not Found) loading http://localhost:9876/node_modules/angular2-google-maps/package.json
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:636:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:225:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:125:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:293:33)
        Error loading http://localhost:9876/node_modules/angular2-google-maps/package.json
        Error loading http://localhost:9876/base/dist/dev/app/home/home.component.spec.js'
