### ISSUE TITLE
external library problem,

### ISSUE THREAD

**Issue by canygt27** [mgechev/angular2-seed#1326]
Hello again, 

I have added the swiper slider to my angular2 project and there is a problem in inspect console like this;

## Error: TypeError: AMD module http://localhost:5556/node_modules/swiper/dist/js/swiper.min.js did not define(…)

Also in my terminal is saying that; 

## error TS2304: Cannot find name 'Swiper'.

can you help me?

Have a nice day.

**Comment by vyakymenko** [comment]
@canygt27 , hello, please look for:
[Add external dependency](https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency) and [Add external scripts and styles WIKI](https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles)

**Comment by canygt27** [comment]
I already did it and still have this issue.

**Comment by vyakymenko** [comment]
@canygt27 , fork ?

**Comment by vyakymenko** [comment]
@canygt27 , is it a typings `ts`, or just JavaScript module?

**Comment by canygt27** [comment]
It is a javascript module and I am writing it in ngOnInit.

**Comment by vyakymenko** [comment]
@canygt27 , can you give me a fork ? Because per error, you not inject it

**Comment by canygt27** [comment]
What kind of fork? Sorry I am new for this.

**Comment by vyakymenko** [comment]
@canygt27 , access to you repository, fork :)

**Comment by canygt27** [comment]
Okey I did.

**Comment by vyakymenko** [comment]
@canygt27 , create a pr in your fork.

**Comment by canygt27** [comment]
Hello again,

Thanks for your helping vyakmenko. I have a question to for you. I also wanna code jquery in my ts files. how can I code it?

**Comment by vyakymenko** [comment]
@canygt27 , as you saw my comment, use `jQuery` selector instead `$`, and all will working fine :)
