### ISSUE TITLE
Unable to create build properly

### ISSUE THREAD

**Issue by sanjitbauli** [mgechev/angular2-seed#1328]
if i run 
npm start

css missing in browser.
My code is like
`
    <link type="text/css" href="css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="css/style.css" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="css/style3.css" rel="stylesheet" type="text/css" />
  `

in view the source i can see like 
`
    <link rel="stylesheet" href="/dist/dev/css/main.css?1473780635934">
    `

Another problem,
I put my own code as client/app
and the when run `npm run build.prod`
it is still creating dist with default app which is built in with this repository.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
