### ISSUE TITLE
redundant file names

### ISSUE THREAD

**Issue by doapp-ryanp** [mgechev/angular2-seed#1331]
Why do all files under `app/<dirname>/` have the prefix of the `<dirname>`?

I am aware of the [style guide application structure section](https://angular.io/styleguide#!#application-structure) however nothing in there to me indicates a reason for this redundancy that angular2-seed has chosen.

There must be a good reason for it, but from what I can tell (only using angular2 for a week now) you remove lots of redundancy by leveraging convention over configuration when naming files in an app folder.

## Proposed change

Now:
```
app/home:
  - home.component.css|html|e2e-spec.ts|spec.ts|ts
  - home.module.ts
  - home.routes.ts
  - index.ts
```

New:
```
app/home:
  - component.css|html|e2e-spec.ts|spec.ts|ts
  - module.ts
  - routes.ts
  - index.ts
```

**Comment by TheDonDope** [comment]
The idea is, that when you work in your Editor/IDE you can do a Quick Open and type the corresponding filename. The backdraw to your `new` section is that you would have the same names for all different components, and would have to choose/browse/scroll to the appropiate file to find it. With the `now` naming scheme you will not have this problem :)

**Comment by doapp-ryanp** [comment]
@TheDonDope thanks for the quick reply. Makes sense, however most IDEs allow for class and symbol search in addition to file name.

For example see https://www.jetbrains.com/help/webstorm/2016.1/navigating-to-class-file-or-symbol-by-name.html

Since we are using TypeScript, all classes show up via Class search - everything else (routes etc) show up via symbol search.

Where you do have me is quick open for `.html` files not sure offhand how to do that.

If our team decides to go the `new` way, it wont be harder to debug problems in the field or anything will it?  I know it shows full path for errors in dev, I'm more curious about production..

**Comment by mgechev** [comment]
We're following the official style guide. In case you think parts of it should be reconsidered, you can open an issue in [angular.io](https://github.com/angular/angular.io/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20styleguide).
