### ISSUE TITLE
css inject not loading when npm start

### ISSUE THREAD

**Issue by sanjitbauli** [mgechev/angular2-seed#1333]
Hi,
when i insert all my css inside the inject:css block, it is working fine for my build, but npm run does not include all those css but including a single css main.css?xxx
but all files are copied as it is indie /dist/dev/css/ folder

app/index.html source code:
`
-- inject:css --
    <link type="text/css" href="css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="css/style.css" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="css/style3.css" rel="stylesheet" type="text/css">
  -- endinject --
`
Browser's view source:
`
-- inject:css --
    <link rel="stylesheet" href="/dist/dev/css/main.css?1473865114118">
-- endinject --
`

What should be here is, when npm run, it should not replace my source code sources with main.css

**Comment by sasikumardr** [comment]
You should not directly add css files in index.html
Add it in seed.config or project.config so that it will be injected automatically at build phase

**Comment by mgechev** [comment]
You can add reference to `bootstrap.min.css` similar to the way the dependencies are declared [here](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L276-L281). Here's more information https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles.
