### ISSUE TITLE
Cannot find module './app.module.ngfactory' in IntelliJ

### ISSUE THREAD

**Issue by Sjiep** [mgechev/angular2-seed#1338]
With the IntelliJ Typescript compiler active and a fresh clone of the seed. The following error is listed in the Typescript pane of IntelliJ it gives the following error:
```
Error:(8, 36) TS2307: Cannot find module './app.module.ngfactory'.
```

All build tasks seem to work fine, producing no error, but it's annoying to this this error constantly listed while developing. Does anybody have any idea how to 'fix this issue'?

**Comment by mgechev** [comment]
Just ignore main-prod.ts. It is already blacklisted by the config but it seems IntelliJ takes everything from the directory.

**Comment by pantonis** [comment]
Have the same problem but with VS2015. How do I ignore it?
