### ISSUE TITLE
SCSS build injecting wrong generated css file path into index.html

### ISSUE THREAD

**Issue by nosachamos** [mgechev/angular2-seed#1340]
Hopefully I'm not missing something obvious, but if so please let me know.

I cloned the repo, and enabled SCSS by setting `ENABLE_SCSS` to true in seed.config.ts. I then renamed the main.css file to main.scss and ran `npm start`.

The build succeeds, but the demo app comes without proper formatting. I noticed that in the index.html file, the path to the main.css seems incorrect. It comes like so: 

```
  <!-- inject:css -->
  <link rel="stylesheet" href="/dist/dev/css/main.css?1473978623939">
  <!-- endinject -->
```

It should be 

```
  <!-- inject:css -->
  <link rel="stylesheet" href="/css/main.css?1473978623939">
  <!-- endinject -->
```

instead.

If I manually add `<link rel="stylesheet" href="/css/main.css?1473978623939">` to the index.html file, it finds the generated css and it works fine.

I'm running the latest release against RC7.

**Comment by mgechev** [comment]
Yes, this is already implemented by this PR https://github.com/mgechev/angular2-seed/pull/1335.

**Comment by nosachamos** [comment]
@mgechev perfect! I was about to submit one. I will just wait for that to get merged. Thank you!

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/commit/0069fda30fd383da96a034a178cbd422fc53bd10.
