### ISSUE TITLE
Project Config

### ISSUE THREAD

**Issue by Meistercoach83** [mgechev/angular2-seed#1343]
How about moving the project.config.ts to the src/client folder or somewhere else? every time i pull from master (described in the wiki) i have to update the file again..

**Comment by mgechev** [comment]
`project.config.ts` is used only by scripts in the `tools` directory.

Why do you have to update it each time? Recently there was a "breaking change" regarding the import of `Config` which might have led to merge conflicts in this file but in general this is supposed to happen in very rare cases.

**Comment by Meistercoach83** [comment]
Every time I pull from git the file is overwritten. So I thought to move it to an other position.

**Comment by mgechev** [comment]
Would you describe the steps you go through when you update the seed?

**Comment by Meistercoach83** [comment]
I move the src/client folder to client_backup, git stash,
then I do a git pull upstream master. after that i have to add my dependencies to the package.json file again, i have to update my project-config and move the client-folder backwards
