### ISSUE TITLE
TSConfig ES6 conversion does not work

### ISSUE THREAD

**Issue by zeeshanjan82** [mgechev/angular2-seed#1348]
I am using the seed project and instead of es5 I am trying to compile typescript to es6 by change the  ```    "target": "es6",``` value in tsconfig.json file however I am facing 2 issues when running ```npm start ``` or ```npm run build.prod```:
```
 Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module.m._compile (D:\Work\isalepos_client\Client\server\node_modules\ts-node\src\index.ts:299:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\Work\isalepos_client\Client\server\node_modules\ts-node\src\index.ts:302:14)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\isalepos_client\Client\server\tools\utils\seed.utils.ts:9:1)

````
This issue is coming in line:
```
    let config = Object.assign({
      typescript: require('typescript')
    }, options);
```
in file tsproject.ts
Another issue is coming in line:
```
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
    ];
````
Unexpected Token ...

**Comment by mgechev** [comment]
You need to change the `target` version in `src/tsconfig.json`. After that you'll need to change the tasks `tools/tasks/seed/build.js.(dev|prod).ts` to exclude `core-js`'s type definitions.

**Comment by ZuSe** [comment]
Did you manage to get it work with the new @types?

**Comment by mgechev** [comment]
For types you need to modify `src/tsconfig.json` (not the `tsconfig.json` in root) and remove `core-js` and whatever other ES6 typings you have.

**Comment by ZuSe** [comment]
@mgechev 

That's exactly what I did. I tried it with the plain seed, but it does not work.

Here is the output of gulp build.prod

> 
> src/client/app/about/about.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
> src/client/app/about/about.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
> src/client/app/about/about.module.ts(2,30): error TS2307: Cannot find module '@angular/common'.
> src/client/app/about/about.routes.ts(1,23): error TS2307: Cannot find module '@angular/router'.
> src/client/app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
> src/client/app/app.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
> src/client/app/app.module.ts(2,31): error TS2307: Cannot find module '@angular/platform-browser'.
> src/client/app/app.module.ts(3,31): error TS2307: Cannot find module '@angular/common'.
> src/client/app/app.module.ts(4,30): error TS2307: Cannot find module '@angular/router'.
> src/client/app/app.module.ts(5,28): error TS2307: Cannot find module '@angular/http'.
> src/client/app/app.routes.ts(1,24): error TS2307: Cannot find module '@angular/router'.
> src/client/app/home/home.component.ts(1,35): error TS2307: Cannot find module '@angular/core'.
> src/client/app/home/home.component.ts(41,10): error TS7006: Parameter 'names' implicitly has an 'any' type.
> src/client/app/home/home.component.ts(42,10): error TS7006: Parameter 'error' implicitly has an 'any' type.
> src/client/app/home/home.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
> src/client/app/home/home.module.ts(2,30): error TS2307: Cannot find module '@angular/common'.
> src/client/app/home/home.routes.ts(1,23): error TS2307: Cannot find module '@angular/router'.
> src/client/app/main.ts(5,32): error TS2307: Cannot find module '@angular/core'.
> src/client/app/main.ts(7,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
> src/client/app/shared/name-list/name-list.service.ts(1,28): error TS2307: Cannot find module '@angular/core'.
> src/client/app/shared/name-list/name-list.service.ts(2,32): error TS2307: Cannot find module '@angular/http'.
> src/client/app/shared/name-list/name-list.service.ts(3,28): error TS2307: Cannot find module 'rxjs/Observable'.
> src/client/app/shared/navbar/navbar.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
> src/client/app/shared/shared.module.ts(1,47): error TS2307: Cannot find module '@angular/core'.
> src/client/app/shared/shared.module.ts(2,30): error TS2307: Cannot find module '@angular/common'.
> src/client/app/shared/shared.module.ts(3,29): error TS2307: Cannot find module '@angular/forms'.
> src/client/app/shared/shared.module.ts(4,30): error TS2307: Cannot find module '@angular/router'.
> src/client/app/shared/toolbar/toolbar.component.ts(1,26): error TS2307: Cannot find module '@angular/core'.
> tools/manual_typings/seed/express-history-api-fallback.d.ts(3,34): error TS2307: Cannot find module 'express'.
> node_modules/@types/express/index.d.ts(16,30): error TS2307: Cannot find module 'serve-static'.
> node_modules/@types/serve-static/index.d.ts(16,20): error TS2307: Cannot find module 'mime'.
> [10:14:20] Plumber found unhandled error:
>  TypeError in plugin 'gulp-template'
> Message:
>
