### ISSUE TITLE
manual_typings doesn't work

### ISSUE THREAD

**Issue by apocarteres** [mgechev/angular2-seed#1350]
Suppose we need to integrate some generated code in the project. 
The generated part includes 2 files:

- foo.d.ts
- foo.js

```foo.d.ts``` looks like:
```
declare module 'foo' {
export class TFoo {
}
}
```

```foo.js``` contains generated impl for ```TFoo```

What i'm doing right now is do put ```foo.d.ts``` under ```tools/manual_typings/project``` dir and create dir ```foo``` under ```node_modules``` path. My dir ```foo``` contains ```package.json``` and JS implementaion

This hacky schema is going to work only when i run app in dev mode, but Karma tests are not working this way, i permanenly got: ``` 404: /base/node_modules/foo.js```

Could you explain please how do i integrate generated code like described above to the angular2-seed?

**Comment by mgechev** [comment]
Would you share your `package.json`? In general everything is supposed to work because both, the dev build and karma use the `SYSTEM_CONFIG_DEV` which is in `src/client/app/system-config.ts`.

**Comment by apocarteres** [comment]
I checked out fresh ```angular2-seed``` master and put these files:

node_modules/foo/package.json
```json
{"name":"foo","version":"0.0.1","main":"foo.js"}
```

node_modules/foo/foo.js
```js
TFoo = function(args) {
};
```

tools/manual_typings/project/foo.d.ts
```ts
declare module 'foo' {
  export class TFoo {
  }
}
```

Using class ```TFoo``` in the bundled ```name-list-service```
```ts
import {TFoo} from 'foo';
...
constructor(private http: Http) {
  console.log('test object is: ', new TSignupRequest());
}
```

also add single line to service spec :
```ts
import {TFoo} from 'foo';
...
it('should resolve to list of names when get called', () => {
  console.log('test object is: ', new TFoo());
  let names:any;
  initialResponse.subscribe((data:any) => names = data);
  expect(names).toEqual(['Dijkstra', 'Hopper']);
});
```

afte that i do:
```
npm test
```

and see the
```
START:
18 09 2016 08:12:44.947:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
18 09 2016 08:12:44.952:INFO [launcher]: Starting browser Chrome
18 09 2016 08:12:45.956:INFO [Chrome 53.0.2785 (Mac OS X 10.11.6)]: Connected on socket /#ZxB4gJyefvnwOEB9AAAA with id 35661467
18 09 2016 08:12:46.560:WARN [web-server]: 404: /base/node_modules/foo.js
Chrome 53.0.2785 (Mac OS X 10.11.6) ERROR: Error{originalErr: Error{}}
18 09 2016 08:12:46.696:WARN [web-server]: 404: /base/node_modules/foo.js
```

**Comment by mgechev** [comment]
Thanks for the detailed comment. You need to do two things:

- Karma needs to know about `foo`. In `karma.config.js` add:

```js
      { pattern: 'node_modules/@angular/**/*.js', included: false, watched: true },
      { pattern: 'node_modules/@angular/**/*.js.map', included: false, watched: false },

      // The ONLY file that needs to be included by you
      { pattern: 'node_modules/foo/**/*.js', included: false, watched: true },

      { pattern: 'dist/dev/**/*.js', included: false, watched: true },
```

- Compliment the SystemJS mapping. In the `paths` object in `SYSTEM_CONFIG_DEV` add:

```
      'foo': 'node_modules/foo/foo.js',
```

The second is not supposed to be required...probably there's more elegant solution - altering the `packageConfigPaths` or something similar.

**Comment by apocarteres** [comment]
many thanks @mgechev , really appreciate

**Comment by apocarteres** [comment]
@mgechev just fyi: i recently got updated to latest seed version and noticed that way to handle manual_typing described above, doesn't work for me anymore. New working approach is just add Foo as additional package into ```project.config.ts```:

```
    this.addPackagesBundles([{
      name: 'my.foo.lib',
      path: 'node_modules/my.foo.lib',
      packageMeta: {
        defaultExtension: 'js'
      }
    }]);
```
