### ISSUE TITLE
Adding firebase breaks the seed

### ISSUE THREAD

**Issue by prabhatsharma** [mgechev/angular2-seed#1353]
added firebase (npm install firebase --save) and got this error in chrome console.

(index):47 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/firebase/auth-node.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

Folder structure is node_modules/firebase/auth-node/index.js

**Comment by mgechev** [comment]
Here are instructions for AngularFire2 https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2.
