### ISSUE TITLE
Changing APP_BASE from '/' to anything else breaks application

### ISSUE THREAD

**Issue by omerfarukyilmaz** [mgechev/angular2-seed#1354]
**Steps to reproduce and a minimal demo of the problem**

clone fresh repo.
run command:

`npm start -- --port 8081 --base /myBase/`

**Current behavior**

The error message:

![image](https://cloud.githubusercontent.com/assets/5538485/18624515/facade54-7e50-11e6-92ab-f269a7751908.png)

which looks at:

![image](https://cloud.githubusercontent.com/assets/5538485/18624492/d45d18a4-7e50-11e6-833b-703ac635782e.png)

**Other information**

I could not find after which commit this stopped working (or else I would fix it and send a PR). Any help is appreciated.

**Comment by omerfarukyilmaz** [comment]
A temporary fix I put together thanks to @mgechev from issue #1351.

in `tools/config/project.config.ts`

I put

`import { argv } from 'yargs';`

and inside the constructor()

    this.PLUGIN_CONFIGS['browser-sync'] = {
      middleware: [require('connect-history-api-fallback')({ index: `${this.APP_BASE}index.html` })],
      port: this.PORT,
      startPath: this.APP_BASE,
      open: argv['b'] ? false : true,
      injectChanges: false,
      server: {
        baseDir: `${this.DIST_DIR}/empty/`,
        routes: {
          [`${this.APP_BASE}${this.APP_SRC}`]: this.APP_SRC,
          [`${this.APP_BASE}${this.APP_DEST}`]: this.APP_DEST,
          [`${this.APP_BASE}node_modules`]: 'node_modules',
          [`${this.APP_BASE.replace(/\/$/, '')}`]: this.APP_DEST
        }
      }
    }

**Comment by mgechev** [comment]
@omerfarukyilmaz what is the change inside the constructor?

**Comment by omerfarukyilmaz** [comment]
@mgechev I overrode PLUGIN_CONFIGS['browser-sync'] inside the `constructor()` in `tools/config/project.config.ts` like this:


    constructor() {
      super();
      // this.APP_TITLE = 'Put name of your app here';

      // ...

      this.PLUGIN_CONFIGS['browser-sync'] = {
        middleware: [require('connect-history-api-fallback')({ index: `${this.APP_BASE}index.html` })],
        port: this.PORT,
        startPath: this.APP_BASE,
        open: argv['b'] ? false : true,
        injectChanges: false,
        server: {
          baseDir: `${this.DIST_DIR}/empty/`,
          routes: {
            [`${this.APP_BASE}${this.APP_SRC}`]: this.APP_SRC,
            [`${this.APP_BASE}${this.APP_DEST}`]: this.APP_DEST,
            [`${this.APP_BASE}node_modules`]: 'node_modules',
            [`${this.APP_BASE.replace(/\/$/, '')}`]: this.APP_DEST
          }
        }
      };

    }


 just as you showed on issue #1351. After that, changing APP_BASE with the --base flag like
`npm start -- --port 8081 --base /myBase/`
worked. This is just a temporary solution. 

I believe the middleware index, rewrites, or disableDotRule (the commit that helped make links with . work) is the root cause of this.

**Comment by lifaon74** [comment]
Bug confirmed (I passed 2hours searching for a solution, thx omerfarukyilmaz).

**Comment by omerfarukyilmaz** [comment]
I just tested it and it's fixed with commit https://github.com/mgechev/angular2-seed/commit/da9ed29d362057de38b4ade8d7e13661b0e29954.

Thank you.
