### ISSUE TITLE
AngularFire2 guide out of date

### ISSUE THREAD

**Issue by daniel7912** [mgechev/angular2-seed#1360]
Hi,

I tried following your guide to implement AngularFire2 but the code looks as though it's out of date. E.g. there is no `SYSTEM_CONFIG_DEV` variable in `project.config.ts`, and the bootstrap function looks different too.

Intsead, I included the files in project.config.ts like this:

```
this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'firebase/firebase.js', inject: 'libs'},
      {src: 'angularfire2/angularfire2.js', inject: 'libs'},
    ];
```

I also tried creating the code as described in the wiki currently:

```
this.SYSTEM_CONFIG_DEV.paths['firebase'] =
      `${this.APP_BASE}node_modules/firebase/firebase`;

    this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/angularfire2`;

    this.SYSTEM_BUILDER_CONFIG.packages['firebase'] = {
        main: 'firebase.js',
        defaultExtension : 'js'
    };

    this.SYSTEM_BUILDER_CONFIG.packages['angularfire2'] = {
        main: 'angularfire2.js',
        defaultExtension : 'js'
    };
```

But this caused the folllowing console error:

`Cannot GET /node_modules/angularfire2/bundles/angularfire2.umd.js`

I then followed the [official install instructions](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) and included AngularFireModule in the `app.module.ts` `@NgModule` instead. This gave me a load of typescript errors, such as:

`/node_modules/angularfire2/interfaces.d.ts(12,35): error TS2503: Cannot find namespace 'firebase'.`

Could you update the wiki please?

**Comment by fedeguzman** [comment]
Hi, I follow this instructions but I'm not getting some errors...

1 - Install angularfire2 and firebase:

`npm install --save angularfire2 firebase`

2 - When I tried to install typings I got this error:

> ERR! message Unable to read typings for "firebase3". You should check the entry paths in "firebase3.d.ts" are up to date

I searched and found this #1179 and #1156 so I ignored step 2

3 - I copied inside the ProjectConfig constructor this:

`  this.SYSTEM_CONFIG_DEV.paths['firebase'] =
      ${this.APP_BASE}node_modules/firebase/firebase;

    this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/angularfire2`;

    this.SYSTEM_BUILDER_CONFIG.packages['firebase'] = {
        main: 'firebase.js',
        defaultExtension : 'js'
    };

    this.SYSTEM_BUILDER_CONFIG.packages['angularfire2'] = {
        main: 'angularfire2.js',
        defaultExtension : 'js'
    };`


4 -

Following the [official install instructions](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md)

In the app.module.ts I create this:
```
export const firebaseConfig = {
  apiKey: "----------",
  authDomain: "------.firebaseapp.com",
  databaseURL: "https://------.firebaseio.com",
  storageBucket: "------.appspot.com"
};
```

```

@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    RouterModule.forRoot(routes),
    AboutModule,
    HomeModule,
    SharedModule.forRoot(),
    **AngularFireModule.initializeApp(firebaseConfig)**
  ]

```

5 - To check if everything was working okay in home.component.ts I did this:


```
import { AngularFire, FirebaseListObservable } from 'angularfire2';
...

export class HomeComponent implements OnInit {

  ... 

  items: FirebaseListObservable<any[]>;

  constructor(public nameListService: NameListService, **af: AngularFire**) {
    this.items = af.database.list('items');
  }

```

Errors:

**1. Cannot find namespace 'firebase'.**

I fixed it by opening `src/client/tsconfig.json` and add the "types" array as follows:

```
 "types": [
      "core-js",
      "express",
      "jasmine",
      "node",
      "protractor",
      "systemjs",
      "firebase"
    ]

```
**2. Error: ReferenceError: require is not defined(…) **

**Comment by mgechev** [comment]
Just updated the guide.

**Comment by daniel7912** [comment]
Thanks for updating the guide @mgechev. I've followed it and have AngularFire2 working now but I am still getting the typescript errors like `"Cannot find namespace 'firebase'."`.

I've added `"firebase"` to the types array in `src/client/tsconfig.ts` but the errors are still there. Any ideas?

**Comment by mgechev** [comment]
You also installed `@types/firebase`, right?

**Comment by daniel7912** [comment]
Yes that's installed OK. I think the problem may be related to `@types/request` because I noticed this error/warning:

`UNMET PEER DEPENDENCY @types/request@0.0.31`
`npm WARN EPEERINVALID angularfire2@2.0.0-beta.5 requires a peer of @types/request@0.0.30 but none was installed.`

My package.json dependencies looks like this:

```
"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@types/firebase": "^2.4.30",
    "@types/form-data": "0.0.32",
    "@types/node": "^6.0.39",
    "@types/request": "0.0.31",
    "angularfire2": "^2.0.0-beta.5",
    "core-js": "^2.4.0",
    "es-module-loader": "^1.0.0",
    "firebase": "^3.4.0",
    "moment": "^2.15.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "0.6.21"
  }
```

I also tried installing `@types/node` and `@types/form-data` manually before installing `@types/request` but that still didn't help.

@types/request appears to be installed fine in `node_modules/@types/request/ ` though.

**Comment by daniel7912** [comment]
In case I had done something wrong along the way, I started a new seed project and installed AngularFire2 again and now I get this error instead (the typescript errors have gone):

`localhost/:47 Error: ReferenceError: require is not defined
	    at eval (http://localhost:5555/node_modules/traceur/src/node/api.js:22:12)
	Evaluating http://localhost:5555/node_modules/traceur/src/node/api.js
	Error loading http://localhost:5555/node_modules/traceur/src/node/api.js
	Error loading http://localhost:5555/node_modules/angularfire2/angularfire2.js as "angularfire2" from http://localhost:5555/app/app.module.js "Report this error at https://github.com/mgechev/angular2-seed/issues"`

**Comment by fedeguzman** [comment]
Hey everyone!

I followed the updated guide of AngularFire2 and I got this error:

`UNMET PEER DEPENDENCY @types/request@0.0.31` - Same error as @daniel7912 had.

I ignored this and followed the guide (I used AngularFireModule from official documentation) and I got AngularFire2 to work and without any errors or warnings.

But I noticed when I run `npm start` I got this in my console:
```

node_modules/@types/protractor/index.d.ts(22,27): error TS2305: Module 'webdriver' has no exported member 'IButton'.
node_modules/@types/protractor/index.d.ts(25,24): error TS2305: Module 'webdriver' has no exported member 'IKey'.
node_modules/@types/protractor/index.d.ts(28,45): error TS2339: Property 'Error' does not exist on type 'typeof error'.
node_modules/@types/protractor/index.d.ts(29,40): error TS2305: Module 'webdriver.error' has no exported member 'IErrorCode'.
node_modules/@types/protractor/index.d.ts(36,37): error TS2305: Module 'webdriver.logging' has no exported member 'IType'.
node_modules/@types/protractor/index.d.ts(37,38): error TS2305: Module 'webdriver.logging' has no exported member 'ILevelValues'.
node_modules/@types/protractor/index.d.ts(39,67): error TS2305: Module 'webdriver.logging' has no exported member 'ILevel'.
node_modules/@types/protractor/index.d.ts(40,67): error TS2305: Module 'webdriver.logging' has no exported member 'ILevel'.
node_modules/@types/protractor/index.d.ts(287,39): error TS2339: Property 'stacktrace' does not exist on type 'typeof webdriver'.
node_modules/@types/protractor/index.d.ts(288,42): error TS2339: Property 'stacktrace' does not exist on type 'typeof webdriver'.
node_modules/@types/protractor/index.d.ts(303,35): error TS2305: Module 'webdriver' has no exported member 'stacktrace'.
node_modules/@types/protractor/index.d.ts(340,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(414,52): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(462,53): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(664,29): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(673,32): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(704,39): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(725,35): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(801,48): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(808,30): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1111,32): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1139,30): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1362,51): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1363,42): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1364,41): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1440,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1461,60): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1477,41): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1491,51): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1505,58): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1574,79): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1594,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1614,36): error TS2305: Module 'webdriver' has no exported member 'Locator'.

```

Besides that I'm not getting more errors or warnings.

**Comment by fedeguzman** [comment]
I started a new seed project and installed AngularFire2, made some changes to remove this errors:

```
...
node_modules/@types/protractor/index.d.ts(1614,36): error TS2305: Module 'webdriver' has no exported member 'Locator'.
...
```

but now I'm getting this:

`E:/angular2-seed/node_modules/angularfire2/interfaces.d.ts(12,35): error TS2503: Cannot find namespace 'firebase'.`

`@types/firebase` is installed and I've added firebase to the types array

I'm still getting this:

```
UNMET PEER DEPENDENCY @types/request@0.0.31
npm WARN EPEERINVALID angularfire2@2.0.0-beta.5 requires a peer of @types/request@0.0.30 but none was installed.

```

Any ideas?

**Comment by fedeguzman** [comment]
Everything is now working!

This is how I fixed each issue:

1. Change the order of the type roots:

```
"typeRoots": [
      "../../node_modules",
      "../../node_modules/@types"
    ],
```

2. In tools/config/project.config.ts, inside the ProjectConfig constructor: 

```
this.SYSTEM_CONFIG_DEV.paths['firebase'] =
      `${this.APP_BASE}node_modules/firebase/firebase`;

    this.SYSTEM_BUILDER_CONFIG.packages['firebase'] = {
      main: 'firebase.js',
      defaultExtension : 'js'
    };

    this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/angularfire2`;

    this.SYSTEM_BUILDER_CONFIG.packages['angularfire2'] = {
      main: 'angularfire2.js',
      defaultExtension : 'js'
    };
```

Extra step: #1369 #1366 

In package.json I changed this:

`"@types/selenium-webdriver": "2.44.*",`

Everything works fine now.

**Comment by daniel7912** [comment]
Thanks @fedeguzman, switching the order of the type roots fixed my problem!

I was also getting the webdriver typescript errors earlier today but I didn't get them in a fresh clone just now so I guess that's been fixed?

**Comment by fedeguzman** [comment]
You're welcome @daniel7912. Yes, it's been fixed it. #1369

**Comment by daniel7912** [comment]
OK now I'm completely baffled. I think part of the problem is with my PC.

I cloned the seed, installed firebase etc. but I get the error:

`localhost/:47 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/angularfire2/bundles/angularfire2.umd.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:636:29)
	    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:225:37)
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:125:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:293:33)
	Error loading http://localhost:5555/node_modules/angularfire2/bundles/angularfire2.umd.js as "angularfire2" from http://localhost:5555/app/app.module.js "Report this error at https://github.com/mgechev/angular2-seed/issues"`

I then rsync'd the entire directory over to my macbook and ran `npm start`, and it works fine!
Both computers have `node v6.4.0` and `npm v3.10.0`. On the PC that isn't working, I have tried using a different port too with no joy.

Any ideas what could be wrong?

**Comment by fedeguzman** [comment]
The same happened to me in a PC while I was trying to make a prod build. 

Try adding this inside the ProjectConfig constructor: (Only if you want to run the npm run build.pro, if you just run `npm start` might failed)

```
this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      ${this.APP_BASE}node_modules/angularfire2/angularfire2`;

    this.SYSTEM_BUILDER_CONFIG.packages['angularfire2'] = {
      main: 'angularfire2.js',
      defaultExtension : 'js'
    };

```
I hope this will help

**Comment by daniel7912** [comment]
Adding those seems to work for the `build.prod` command, but gives me the old `require` error for `npm start`.

It says on the AngularFire2 page that the current fix for that is temporary so hopefully they will replace it with something better soon

**Comment by fedeguzman** [comment]
Is this only happening in a PC?

**Comment by daniel7912** [comment]
Yep, I have followed the exact same process you laid out above, once on Ubuntu 16.04 and once on a macbook OSX. It works fine on the macbook but on Ubuntu I get the 404 error when running `npm start`. Both have the same versions of node & npm so it's very odd.

**Comment by fedeguzman** [comment]
So I was able to remove that old require error!

Try to copy this in your `project.config.ts`, this worked for me:

```typescript
import { join } from 'path';

import { SeedConfig } from './seed.config';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    // this.APP_TITLE = 'Put name of your app here';

    /* Enable typeless compiler runs (faster) between typed compiler runs. */
    // this.TYPED_COMPILE_INTERVAL = 5;

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
      //{src:'material-design-lite/dist/material.min.css', inject: true},
      //{src:'material-design-lite/dist/material.cyan-red.min.css', inject: true},
      //{src:'material-design-lite/dist/material.min.js', inject: 'libs'}
      ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false}
      // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
    ];

    this.SYSTEM_CONFIG_DEV.paths['firebase'] =
      `${this.APP_BASE}node_modules/firebase/firebase`;

    this.SYSTEM_BUILDER_CONFIG.packages['firebase'] = {
      main: 'firebase.js',
      defaultExtension : 'js'
    };
/*
    this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/angularfire2`;

    this.SYSTEM_BUILDER_CONFIG.packages['angularfire2'] = {
      main: 'angularfire2.js',
      defaultExtension : 'js'
    };*/

    /* Add to or override NPM module configurations: */
    // this.mergeObject(this.PLUGIN_CONFIGS['browser-sync'], { ghostMode: false });
  }

}
```

**Comment by daniel7912** [comment]
That's the same setup I already have which produces the 404 error on Ubuntu :(

**Comment by fedeguzman** [comment]
It's so weird! Now in Windows 10 is working without any "require" error. Wish I could help you but I don't have Ubuntu here :(  Could you post the error here? Maybe someone can help us.

@mgechev Any idea why @daniel7912 is getting the 404 error on Ubuntu?

**Comment by daniel7912** [comment]
Sure, its this error:

`localhost/:47 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/angularfire2/bundles/angularfire2.umd.js at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:636:29) at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:225:37) at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:125:47) at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474542144430:293:33) Error loading http://localhost:5555/node_modules/angularfire2/bundles/angularfire2.umd.js as "angularfire2" from http://localhost:5555/app/app.module.js "Report this error at https://github.com/mgechev/angular2-seed/issues"`

I have an Arch linux install too so I'll give that a try when I can. Interested to see if it happens there too.

**Comment by daniel7912** [comment]
Just tried this on Arch and got the same 404 problem again. The only difference I can think of other than linux/osx is that I'm using [nvm](https://github.com/creationix/nvm) on both Linux installs. Would that make a difference?

**Comment by koodinorja** [comment]
I got rid of the 'require is not defined' error by modifying the project.config file
```
this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/bundles/angularFire2.umd.js`;
```
after that i was getting this error message: 
`Cannot read property 'FacebookAuthProvider' of undefined`

googling that lead me to [this](https://github.com/angular/angularfire2/issues/576) issue in angularfire2 github

so i downgraded my firebase to version 3.4.0

**Comment by samuelfernandez** [comment]
@koodinorja, Then could you sum up all the steps you followed from a fresh clone of the seed to have AngularFire2 working?
Or if anyone else has an update about it I'd be glad to hear it, because by now if tried almost everything in this thread without success.

**Comment by koodinorja** [comment]
@samuelfernandez , alrighty then!
The steps for me are almost identical to the [original guide](https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularFire2)

1) Install angularfire2 and firebase.

`npm install --save angularfire2 firebase@3.4.0 @types/request @types/firebase`

2) Declare the types for the dependencies in `src/client/tsconfig.json`

`"types": [
  "firebase",
  "angularfire2",
  "core-js",
  "express",
  "jasmine",
  "node",
  "protractor",
  "systemjs"
]`

3) In `tools/config/project.config.ts`, inside the ProjectConfig constructor I add these lines
```javascript
    this.SYSTEM_CONFIG_DEV.paths['firebase'] =
      `${this.APP_BASE}node_modules/firebase/firebase`;

    this.SYSTEM_BUILDER_CONFIG.packages['firebase'] = {
      main: 'firebase.js',
      defaultExtension : 'js'
    };

    this.SYSTEM_CONFIG_DEV.paths['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/bundles/angularFire2.umd.js`;

    this.SYSTEM_BUILDER_CONFIG.packages['angularfire2'] = {
      main: 'angularfire2.js',
      defaultExtension : 'js'
    };
```

4) Import and add it to module in `client/app/app.module.ts`

```javascript
import { AngularFireModule } from 'angularfire2';
const firebaseConfig = {
  apiKey: "API-KEY",
  authDomain: "AUTH-DOMAIN",
  databaseURL: "DATABASE-URL",
  storageBucket: "STORAGE-BUCKET",
  messagingSenderId: "MESSAGING-SENDER-ID"
}

@NgModule({
  imports: [BrowserModule, HttpModule, RouterModule.forRoot(routes),
            AboutModule, HomeModule, SharedModule.forRoot(), AngularFireModule.initializeApp(firebaseConfig)],
  declarations: [AppComponent],
  providers: [{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  }],
  bootstrap: [AppComponent]
})
```

5) Start using it in your components

I hope this works for you

**Comment by samuelfernandez** [comment]
Thanks so much for your help, now I have it working!
I think it was because of the version of firebase I was using, and the `project.config.ts` file. Just as a note when installing, specify the version for `@types/request@0.0.30` as it matches the current requirement for angularfire2.

The thing now is that after adding AngularFire to a component, its unit test gives me this:

`28 10 2016 13:53:02.800:WARN [web-server]: 404: /node_modules/angularfire2/bundles/angularFire2.umd.js
Chrome 53.0.2785 (Windows 10 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/node_modules/angularfire2/bundles/angularFire2.umd.js
        Error: XHR error (404 Not Found) loading http://localhost:9876/node_modules/angularfire2/bundles/angularFire2.umd.js
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:647:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:236:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:136:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:304:33)
        Error loading http://localhost:9876/node_modules/angularfire2/bundles/angularFire2.umd.js as "angularfire2" from http://localhost:9876/base/dist/dev/app/login/login.component.spec.js'
Chrome 53.0.2785 (Windows 10 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/node_modules/angularfire2/bundles/angularFire2.umd.js
        Error: XHR error (404 Not Found) loading http://localhost:9876/node_modules/angularfire2/bundles/angularFire2.umd.js
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:647:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:236:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:136:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?c35727d0e64913b5669320b167e496fc94fc6928:304:33)
        Error loading http://localhost:9876/node_modules/angularfire2/bundles/angularFire2.umd.js as "angularfire2" from http://localhost:9876/base/dist/dev/app/login/login.component.spec.js'`

Is there anything else that needs to be configured in order to have tests working?

**Comment by samuelfernandez** [comment]
@koodinorja, do you know why my tests are failing? I think that some configuration is missing. Maybe I should add something to karma.conf.js, but I don't know how.

By the way, angularfire2 has been updated to version 2.0.0-beta.6. With this version @types/firebase is not needed, and `"firebase"` can be removed from `"types"` at `src/client/tsconfig.json`.

**Comment by samuelfernandez** [comment]
@koodinorja @mgechev I've updated the wiki for [AngularFire2](https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularFire2) with the latest versions of all packages that work well together. As the way of using types for firebase and angularfire has changed in the last release, and the way of using the seed for declaring packages at SystemJS has changed since last time the wiki was written, I've updated all related information. I added how to modify karma.conf.js to enable testing with it. This setting is working for me right now with the latest seed. I hope this can prove useful for other people. By the way, I think there is no approval for wiki edits, so if you could take a look into it I'll be glad :) (And sorry in advance if I shouldn't have done this without asking first...)

**Comment by koodinorja** [comment]
@samuelfernandez really nice that you had time to figure it out. I'm really new to karma and testing, so i didn't even try the testing part with my configurations
