### ISSUE TITLE
jQuery and Angular-protractor defined type conflicts

### ISSUE THREAD

**Issue by duytrantps** [mgechev/angular2-seed#1362]
Hi, when I use jQuery in my angular 2 app, it has an error

> node_modules/angular2/typings/jquery/index.d.ts(3218,13): error TS2403:
> Subsequent variable declarations must have the same type.  Variable '$' must be of type
> 'cssSelectorHelper', but here has type 'JQueryStatic'.

I tried to fix by change the content of that file but it seem not allowed to change, they will lead to errors can not fetch rxjs.

**Comment by mgechev** [comment]
[Duplicate](https://github.com/mgechev/angular2-seed/issues?q=is%3Aissue+jQuery+is%3Aclosed).
