### ISSUE TITLE
Problem installing external dependency using Wiki instructions

### ISSUE THREAD

**Issue by danielcrisp** [mgechev/angular2-seed#1363]
This is _really_ a support issue, but it is possibly caused by the Wiki being out-of-date - or it might even be a bug. I'll let you decide.

I am trying to install [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) into a fresh clone of angular2-seed but I keep getting `'tab' is not a known element` errors, even after following the steps described in the Wiki here: https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

I noticed it is still referring to `bootstrap` rather than `NgModule`, which is why I think it is out-of-date.

**Steps to reproduce and a minimal demo of the problem**

Full details posted here: http://stackoverflow.com/questions/39598409/tab-is-not-a-known-element-errors-when-adding-ng2-bootstrap-to-angular2-seed

Repo / demo here: https://github.com/danielcrisp/angular2-seed

_What steps should we try in your demo to see the problem?_

    npm i
    npm start

**Current behavior**

Errors

```
zone.js?1474384853974:344 Unhandled Promise rejection: Template parse errors:
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. If 'tab' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("

<tabset>
  [ERROR ->]<tab>1</tab>
  <tab>2</tab>
</tabset>
"): HomeComponent@14:2
'tab' is not a known element:
1. If 'tab' is an Angular component, then verify that it is part of this module.
2. If 'tab' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
<tabset>
  <tab>1</tab>
  [ERROR ->]<tab>2</tab>
</tabset>
"): HomeComponent@15:2
```

**Expected/desired behavior**

It should render two tabs beneath the usual Home contents.

**Other information**

I've used the same approach in two other projects that use older versions of angular2-seed and they work ok. One of which is using Angular 2.0.0.

**Comment by mgechev** [comment]
This is not an issue in the seed, you haven't added the tab component as part of the module where the component that uses it is.

**Comment by danielcrisp** [comment]
Not a seed problem, but I thought you'd know the answer! THANK YOU!

**Comment by AAAnderson7301** [comment]
@danielcrisp  With your project I noticed that the build was failing on my pc after a fresh clone. Can you run "build.prod.exp" and get a clean build?

**Comment by danielcrisp** [comment]
You're right, I get an error:

    Error: Unexpected value 'Ng2BootstrapModule' imported by the module 'HomeModule'

**Comment by AAAnderson7301** [comment]
@danielcrisp  I started fresh with the original project. Installed ng2 also added the two lines to the project.config.ts file and I got an error about moment js so I added these lines to project.config.ts and my project is now working just fine building AOT etc.. I can throw together a sample repo later. 
      `` ` 
this.SYSTEM_CONFIG_DEV.paths['moment'] =
    `${this.APP_BASE}node_modules/moment/moment.js`;

    this.SYSTEM_BUILDER_CONFIG.packages['moment'] = {
      main: 'moment.js',
      defaultExtension : 'js'
    };
```

**Comment by danielcrisp** [comment]
Seems to be in this task: `compile.ahead.prod`
```
[15:10:28] Starting 'compile.ahead.prod'...
Error: Unexpected value 'Ng2BootstrapModule' imported by the module 'HomeModule'
    at /Users/danielcrisp/Desktop/angular2-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:14126:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/danielcrisp/Desktop/angular2-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
    at /Users/danielcrisp/Desktop/angular2-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:12952:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/danielcrisp/Desktop/angular2-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:12951:21)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:110:45)
    at codegen (/Users/danielcrisp/Desktop/angular2-seed/tools/tasks/seed/compile.ahead.prod.ts:14:69)
    at Object.main (/Users/danielcrisp/Desktop/tools/@angular/tsc-wrapped/src/main.ts:44:12)
    at module.exports (/Users/danielcrisp/Desktop/angular2-seed/tools/tasks/seed/compile.ahead.prod.ts:32:7)
Compilation failed
```

**Comment by danielcrisp** [comment]
Just updated my repo with your suggestion but it's still failing for me...

By the way I discovered the other day that including `${this.APP_BASE}` in the path caused a problem... I can't remember exactly what with though! 

I think it might have been the unit tests / Karma. The files should have been loaded from `/base/node_modules...` but because `APP_BASE` is `/` they were loading from `/node_modules...` instead
