### ISSUE TITLE
Protractor typings

### ISSUE THREAD

**Issue by tgoyer** [mgechev/angular2-seed#1366]
Getting the following error for each of the defs in the Protractor index.d.ts running the "start" script:
`node_modules/@types/protractor/index.d.ts(22,27): error TS2305: Module 'webdriver' has no exported member 'IButton'.`

Brand new clone.  Just ran `npm install` and then `npm start`.  

Do I need to update anything on my box to get this to work or is there some breaking change to the type definitions?

Full error output:

[23:53:48] Starting 'build.js.dev'...
node_modules/@types/protractor/index.d.ts(22,27): error TS2305: Module 'webdriver' has no exported member 'IButton'.
node_modules/@types/protractor/index.d.ts(25,24): error TS2305: Module 'webdriver' has no exported member 'IKey'.
node_modules/@types/protractor/index.d.ts(28,45): error TS2339: Property 'Error' does not exist on type 'typeof error'.
node_modules/@types/protractor/index.d.ts(29,40): error TS2305: Module 'webdriver.error' has no exported member 'IErrorCode'.
node_modules/@types/protractor/index.d.ts(36,37): error TS2305: Module 'webdriver.logging' has no exported member 'IType'.
node_modules/@types/protractor/index.d.ts(37,38): error TS2305: Module 'webdriver.logging' has no exported member 'ILevelValues'.
node_modules/@types/protractor/index.d.ts(39,67): error TS2305: Module 'webdriver.logging' has no exported member 'ILevel'.
node_modules/@types/protractor/index.d.ts(40,67): error TS2305: Module 'webdriver.logging' has no exported member 'ILevel'.
node_modules/@types/protractor/index.d.ts(287,39): error TS2339: Property 'stacktrace' does not exist on type 'typeof webdriver'.
node_modules/@types/protractor/index.d.ts(288,42): error TS2339: Property 'stacktrace' does not exist on type 'typeof webdriver'.
node_modules/@types/protractor/index.d.ts(303,35): error TS2305: Module 'webdriver' has no exported member 'stacktrace'.
node_modules/@types/protractor/index.d.ts(340,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(414,52): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(462,53): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(664,29): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(673,32): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(704,39): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(725,35): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(801,48): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(808,30): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1111,32): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1139,30): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1362,51): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1363,42): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1364,41): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1440,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1461,60): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1477,41): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1491,51): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1505,58): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1574,79): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1594,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
node_modules/@types/protractor/index.d.ts(1614,36): error TS2305: Module 'webdriver' has no exported member 'Locator'.
[23:53:51] TypeScript: 33 semantic errors
[23:53:51] TypeScript: emit succeeded (with errors)

**Comment by greg-md** [comment]
I get the same.

**Comment by soesoftcn** [comment]
I get the same.

**Comment by dodoshanti** [comment]
Similar errors when trying a prod build

**Comment by Flood** [comment]
I have similar errors, but not only protractor.
Here are some errors, but not all of them.

@types/node/index.d.ts(570,18): error TS2300: Duplicate identifier 'EventEmitter'.
@types/node/index.d.ts(611,22): error TS2430: Interface 'Server' incorrectly extends interface 'Server'.
@types/node/index.d.ts(732,18): error TS2300: Duplicate identifier 'Agent'.
@types/node/index.d.ts(777,18): error TS2300: Duplicate identifier 'Worker'.
@types/node/index.d.ts(2253,22): error TS2430: Interface 'Server' incorrectly extends interface 'Server'.
@types/node/index.d.ts(2253,22): error TS2430: Interface 'Server' incorrectly extends interface 'Server'.
Types of property 'listen' are incompatible.
    Type '{ (port: number, host?: string, backlog?: number, listeningListener?: Function): Server; (path: s...' is not assignable to type '{ (port: number, hostname?: string, backlog?: number, listeningListener?: Function): Server; (por...'.
      Type 'Server' is not assignable to type 'Server'.
        Types of property 'listen' are incompatible.
          Type '{ (port: number, host?: string, backlog?: number, listeningListener?: Function): Server; (path: s...' is not assignable to type '{ (port: number, hostname?: string, backlog?: number, listeningListener?: Function): Server; (por...'.
            Types of parameters 'host' and 'backlog' are incompatible.
              Type 'number' is not assignable to type 'string'.

**Comment by markwhitfeld** [comment]
I got the same issue and have found the fix for it...
There are two problems here... the duplicates and the protractor dependency:
**Duplicates:**
Change the order of the typeRoots in "src/client/tsconfig.json" so that the @types line is first.
**Protractor Dependency:**
The @types/selenium-webdriver dependency was published with a breaking change in moving from version 2.44 to 2.53 (Something that is not strictly following semver practices, argh!). Now @types/protractor is expecting the version of the webdriver typings as found in 2.44.* 
So, to fix it, change selenium typings line in 'package.json' to lock down the minor version as follows:
"@types/selenium-webdriver": "2.44.*"
I will submit a pull request now but I thought that I would quickly publish this comment so that people can get going again.

**Comment by markwhitfeld** [comment]
I submitted the pull request  ( #1369 ) above to fix the issue.
I did find it interesting though that this issue was not picked up in the build. 
(Please note: I am not too familiar with travis conventions so please forgive me if I sound a fool)
I see that the ".travis.yml" file has listed the node_modules folder as a cache folder.
I assume that this would preserve this folder between builds.
The issue would have been reproduced on the build server if the node_modules folder was not cached, or if "npm update" was called before the build.
In my opinion it would be best to call "npm update" before "npm run tests.all" in the build script.
@mgechev it is up to you what way you would like to go with this... I have not submitted a pull request for the build script improvement.

**Comment by tgoyer** [comment]
Thanks for that fix, @markwhitfeld!

**Comment by ndcunningham** [comment]
`node_modules/@types/protractor/index.d.ts(1614,36): error TS2305: Module 'webdriver' has no exported member 'Locator'.`

Still having this issue after i did the changes in your update

**Comment by markwhitfeld** [comment]
@ndcunningham Did you run "npm install" to fix your dependencies after you did the update?

**Comment by ndcunningham** [comment]
@markwhitfeld See update. Yes I did.

I didn't have this issue. 
Once i issued the npm install it started, these started appearing. I guess it's really reference the comment you made about caching....

**Comment by ndcunningham** [comment]
Problem was with systemJS loading. updating to `0.19.38` allowed me to see what module was not being mapped correctly.
RE: https://github.com/systemjs/systemjs/commit/bac2cc52bef77c2e38a831e726fe644e625ec524
