### ISSUE TITLE
Error in serve.prod

### ISSUE THREAD

**Issue by aldrindizonh** [mgechev/angular2-seed#1367]
I have a service that contains: 

```
Import { Injectable } from '@angular/core';
import { NewsSelectorComponent } from './news/index';
import { MyEventsSelectorComponent } from './myevents/index';
import { MyActionItemSelectorComponent } from './my-action-item/index';
import { WatchItemSelectorComponent } from './watch-items/index';

declare var jQuery:any;

@Injectable()
export class HomeService {

  private  	listbox:any[]= [];

  private widgets = window.localStorage.getItem('widget_list') === null ? [] : window.localStorage.getItem('widget_list').split(',');

  getUserWidgets() {
  
     console.log('data: ', WatchItemSelectorComponent);

  }
}
```

in dev it works fine, but when doing: 
`npm run serve.prod`

the output on the console is 
`function e(e) {this._watchItemService=e,this.isLoading=!0,this.isError=!1}`

my expected output was
```
function WatchItemSelectorComponent(_watchItemService) {
        this._watchItemService = _watchItemService;
        this.isLoading = true;
        this.isError = false;
    } 
```

**Comment by SamVerschueren** [comment]
It's because the output is uglified. I don't really see what you want to do here because the output is actually expected.

**Comment by aldrindizonh** [comment]
Hello Sam. I created a drag and drop widget on my apps, That's why I pass the class in object and using that class I can use the class name to call an image

**Comment by SamVerschueren** [comment]
Class names aren't preserved after compiling (mangling, uglifying, ...). So that's not a good practice to do. Better would be to add a name property (or something else) to your component that could identify the image.

**Comment by aldrindizonh** [comment]
Do you have an idea on how to do it in my component? because I almost spend a week to research that but I didn't find thats why I use the class name as my last resort.. Thank you Sam for your feedback!!

**Comment by SamVerschueren** [comment]
It's very hard to make good decisions without looking into what you have and how it is built.

```js
@Component({
    ...
})
class WatchItemSelectorComponent {
    private name = 'watch-item-selector';
}
```

Not sure if that fits your application design though.

**Comment by SamVerschueren** [comment]
@aldrindizonh I updated my example

**Comment by aldrindizonh** [comment]
Woah!!! Thank you Sam!!! it works!!!!!!

**Comment by SamVerschueren** [comment]
Your welcome. You can safely close this issue then ;).
