### ISSUE TITLE
Firebase Integration: require is not defined

### ISSUE THREAD

**Issue by Meistercoach83** [mgechev/angular2-seed#1368]
Hi, I´d like to use firebase / angularfire2. After adding it to my project.config and reloading, i get an error

> "require is not defined".

Searching the angularfire issues i found this: 
https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#2-cannot-find-name-require-this-is-just-a-temporary-workaround-for-the-angular-cli

where do i have to include this in the seed?

**Comment by fedeguzman** [comment]
We're talking about this error here #1360

**Comment by mgechev** [comment]
@Meistercoach83 take a look at the guide and as @fedeguzman mentioned https://github.com/mgechev/angular2-seed/issues/1360.
