### ISSUE TITLE
Atom editor not able to load TypeScript files properly

### ISSUE THREAD

**Issue by dchacke** [mgechev/angular2-seed#1372]
**Steps to reproduce and a minimal demo of the problem**

- Use the Atom text editor
- Install the package atom-typescript
- Quit and restart the editor
- Open the project in Atom and open any TypeScript file in the home directory
- Wait for a few seconds, and the following error will appear:

![screen shot 2016-09-21 at 3 28 48 pm](https://cloud.githubusercontent.com/assets/2866749/18731323/2380ddec-8010-11e6-82ab-52a3bd8cd9d3.png)

**Current behavior**
Atom is unable to offer autocompletion or smart method previews because of this. This used to work fine with previous versions of angular2-seed, so I'm assuming somewhere down the road something broke. *I don't think this is an issue with Atom itself or the TypeScript plugin for Atom*. It may have to do with the `tsconfig.json` files in the project.

You should be able to reproduce it with the file `src/client/app/app.component.ts`.

**Expected/desired behavior**
Atom should be able to load every TypeScript file and show autocompletion for file paths, method names, etc as before.

**Other information**
Only files in the `src` directory seem to be affected by this. For example, `tools/config/seed.config.ts` works fine (in this example screenshot, it does not show the error message from above, and it offers autocompletion for attributes on `this`, for which it must have parsed the TypeScript file successfully):

![screen shot 2016-09-21 at 3 33 59 pm](https://cloud.githubusercontent.com/assets/2866749/18731449/da2aa08c-8010-11e6-949c-259f4ea47030.png)

Enabling text editors to parse TypeScript in this way is extremely helpful and speeds up development.

**Comment by mgechev** [comment]
Thanks for the well described issue! I'll take a look at it as soon as I can.

**Comment by mgechev** [comment]
I tried to reproduce the issue today with clean seed clone but everything worked fine (which surprised me because I've experienced issues with Atom and the seed in the past).

Most likely the issue is related with the new way of management type definitions. For more details you can take a look at this issue https://github.com/mgechev/angular2-seed/issues/1408. Let me know if this helps.

**Comment by dchacke** [comment]
I pulled the latest commits from the seed and it then it worked fine. It may well have been that change in src/client/tsconfig.json!

Thanks! So glad it's working now, very helpful.
