### ISSUE TITLE
how to use Angular-material2 and other packages in Angular2-seed

### ISSUE THREAD

**Issue by rahullsinha** [mgechev/angular2-seed#1376]
![image](https://cloud.githubusercontent.com/assets/20947986/18759416/05e875b4-811a-11e6-94d1-ce52fdeaccdd.png)

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
