### ISSUE TITLE
Browser IE 11 issues

### ISSUE THREAD

**Issue by ashok176** [mgechev/angular2-seed#1379]
Browser IE 11,
SCRIPT438: Object doesn't support property or method 'keys'
File: core.umd.js 

same error in compiler.umd.js

How to solve this issue in angular 2.0.0 latest version. Please Help me.

**Comment by mgechev** [comment]
I can't reproduce this issue. `Object.keys` is an ES5 feature which is supported by all modern browsers (including IE11). Most likely this is environment specific issue.
