### ISSUE TITLE
[BUG] build.bundles.app not working if import on root folder

### ISSUE THREAD

**Issue by lifaon74** [mgechev/angular2-seed#1381]
**Steps to reproduce and a minimal demo of the problem**

Import a npm module 'root' folder (ex:  `import * from 'rxjs'`)
Windows 10 (or whaterver version)
run build.prod

**Current behavior**

> Error on fetch for rxjs.js at ...../node_modules/rxjs.js

It does'nt work because it's not fetching the entry file of the npm module (avaiblable into package.json)

**Expected/desired behavior**

Build properlly (works fine on dev, bacause SystemJs call package.json and read "main"). One of my coworker have a mac and can build prod with this kind of import.

**Other information**

There is a simple way to patch it: `import * from 'rxjs/Rx' ` => import the entry file. But for some external libraries, which use `import * from 'rxjs'` I cant build prod.

**Comment by mgechev** [comment]
Thanks for the issue. I'll work on this today.
