### ISSUE TITLE
PATH IN INDEX FOR PROD DOESN'T WORK

### ISSUE THREAD

**Issue by imaress** [mgechev/angular2-seed#1386]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
git clone repo
npm install
npm run prod.build
copy prod dir to webapp dir of jetty server

**Current behavior**
The app don't run because js and css files didn't found. I watch in the code and the build.index.prod.ts task have in his transformPath function the next code: 
```
...
arguments[0] = Config.APP_BASE + path.slice(slice_after, path.length).join(sep) + `?${Date.now()}`;
...
```
But maybe i miss something because i can't find some instruction or option for assign a value to Config.APP_BASE for prod environment. I try: npm run build.prod --base /something but doesn't work only with start script (but the app compile but doesn't work). Then i put this in my project.config.ts:

```
if(this.ENV === 'prod'){
      this.APP_BASE = '/something/';
    }
```
And work!!

**Expected/desired behavior**
I expect the paths in the index compiled out of the box and if i want a base dir can specify somewhere for prod environment and the --base option for development works.

**Other information**
Sorry for the bad english and thanks for all effort, this work better than angular-cli (Y)

**Comment by mgechev** [comment]
Thanks for the detailed explanation!

You should run the build like this:

```
# Note the "--" before "--base"
npm run build.prod -- --base /something
```
