### ISSUE TITLE
Dolar sign break on production

### ISSUE THREAD

**Issue by oxycoder** [mgechev/angular2-seed#1387]
$ sign change to another character on production build.

**Steps to reproduce and a minimal demo of the problem**

git clone --depth 1 https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install

_What steps should we try in your demo to see the problem?_
**home.component.html**
```html
  <p>This orange cost $5 each</p>
  <p>This banana cost $10 each</p>
  <p>$10 plus $5 equal $15</p>
```
**Current behavior**
```
This orange cost $5 each
This banana cost .html'0 each
.html'0 plus $5 equal .html'5
```
**Expected/desired behavior**
```
This orange cost $5 each
This banana cost $10 each
$10 plus $5 equal $15
```
**Other information**
OS: Mac OSX Sierra.
NPM: 3.10.7
NodeJS: v6.6.0

**Comment by mgechev** [comment]
It seems like something related with inlining the templates. @ludohenin do you think the problem could be in `gulp-inline-ng2-template`?

@oxycoder you can build with `npm run build.prod.exp` with the AoT compilation enabled. This way the issue is no longer reproducible.
