### ISSUE TITLE
Add external fonts

### ISSUE THREAD

**Issue by ghatul** [mgechev/angular2-seed#1389]
hi, 
i used bootstrap external font  ,download from http://getbootstrap.com/getting-started/#download on development env  it not getting any problem but when  on production environment getting some warnings and  all Glyphicons  not display

Failed to decode downloaded font: http://--.--.--.117/css/assets/fonts/gothamrnd-light.woff
login:1 OTS parsing error: invalid version tag

i dont figure out this problem

**Comment by mgechev** [comment]
Most likely your font is not being copied to this location. Would you verify what the content of `/dist/prod/css/assets/fonts/` is?

**Comment by TheDonDope** [comment]
1. Create file `build.fonts.ts` in `/tools/tasks/project` with the following content:

```TypeScript
import * as gulp from 'gulp';

import Config from '../../config';

/**
 * Executes the build process, building the font files.
 */
export = () => {
  return gulp.src(Config.FONTS_SRC).pipe(gulp.dest(Config.FONTS_DEST));
};
```

2. In ` project.config.ts` in `/tools/config/` add the following:

```TypeScript
 FONTS_DEST = `${this.APP_DEST}/fonts`;
  FONTS_SRC = ['node_modules/font-awesome/fonts/**'];
```

3. In `gulpfile.ts` edit the following:

add `build.fonts` to `build.dev|e2e|prod|prod.exp|test` as well as `clean.dev|prod|once`

for example:
```TypeScript

// --------------
// Build dev.
gulp.task('build.dev', (done: any) =>
  runSequence(//'clean.dev',
              //'tslint',
              //'css-lint',
              'build.assets.dev',
              **'build.fonts',**
              'build.html_css',
              'build.js.dev',
              'build.index.dev',
              done));
```

**Comment by ghatul** [comment]
in development all is ok, all Glyphicons are loaded . but in production mode icons not loaded

**Comment by ghatul** [comment]
in development mode all is ok that Glyphicons loaded ,but on production mode is not working .
i am not add build.fonts in build.dev but it allready working on development .........

**Comment by ghatul** [comment]
i added build.fonts as per above mention but getting error after gulp build.tools 
"...........tools/config" has no default export.

**Comment by ghatul** [comment]
![screen shot 2016-09-27 at 11 11 32 am](https://cloud.githubusercontent.com/assets/19589441/18861599/2f0308f0-84a4-11e6-920f-8945688754a5.png)
![screen shot 2016-09-27 at 11 12 39 am](https://cloud.githubusercontent.com/assets/19589441/18861600/2f03072e-84a4-11e6-9593-d044700c722f.png)

**Comment by ghatul** [comment]
![screen shot 2016-09-27 at 11 11 32 am](https://cloud.githubusercontent.com/assets/19589441/18862246/74e9943e-84a8-11e6-933d-1724904f9832.png)
![prod](https://cloud.githubusercontent.com/assets/19589441/18862255/88ad2f9e-84a8-11e6-9708-13c6b29a0312.PNG)

**Comment by ghatul** [comment]
FONTS_SRC = ['../../node_modules/bootstrap/dist/fonts/**'];
 
Cannot read property 'FONTS_SRC' of undefined on --> gulp build.prod or npm run build.prod

**Comment by ghatul** [comment]
FONTS_SRC = ['../../node_modules/bootstrap/dist/fonts/**'];
on -> gulp build.prod     


[12:19:20] 'build.prod' errored after 17 s
[12:19:20] TypeError in plugin 'run-sequence(build.fonts)'
Message:
    Cannot read property 'FONTS_SRC' of undefined
Stack:
TypeError: Cannot read property 'FONTS_SRC' of undefined
    at module.exports (tools/tasks/project/build.fonts.ts:9:27)
    at Gulp.<anonymous> (tools/utils/seed/tasks_tools.ts:32:31)
    at module.exports (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/techprimelab/Desktop/myWorkspace/tpl-web-fullstack-seed/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)

**Comment by Wihan** [comment]
@TheDonDope Instead of `FONT_DEST` and `FONT_SRC` in `project.config.ts`, I had to add it in `seed.config.ts` 

```
  /**
   * The folder of the applications font files.
   * @type {string}
   */
  FONTS_SRC = `${this.APP_SRC}/fonts`;

  /**
   * The folder for the built Font files.
   * @type {string}
   */
  FONTS_DEST = `${this.APP_DEST}/fonts`;
```

Then in `project.config.ts` I changed `FONT_SRC` to the appropriate directory in my case twitter bootstrap glyphicons not showing.

`this.FONTS_SRC = 'node_modules/bootstrap/dist/fonts/**';`

It's working in production now. Thx!
