### ISSUE TITLE
Component dynamic templates

### ISSUE THREAD

**Issue by singhmohancs** [mgechev/angular2-seed#1398]
I am creating a component with different type of list using dynamic templates. I can achieve this easily with angular 1.x .

````javascript
angular
  .module('app')
  .component('list', {
    templateUrl: [
      '$attrs',
      function ($attrs) {
        var layoutType = $attrs.layout || 'default';
        return 'patials/' + layoutType.toLowerCase() + '-list.html';
      }
    ],
    controller: 'ListController'
  });
````
According to angular 2 documentation. it does support inline template or external template URL.

Question:
Is it possible to have dynamic template in Angular 2 component?

**Comment by mgechev** [comment]
It should be possible if the component is rendered dynamically. Here's an example https://github.com/mgechev/codelyzer/issues/83#issuecomment-247118018.

**Comment by singhmohancs** [comment]
i did know where to report this issue.

Anyway Thanks @mgechev
