### ISSUE TITLE
Ignore semantic error during build.prod

### ISSUE THREAD

**Issue by tpruthi** [mgechev/angular2-seed#1401]
How can i ignore the following semantic errors during build.prod

[14:46:35] Starting 'build.js.prod'...
dist\tmp\app\+broker\company.edit\company.edit.ts(368,43): error TS2339: Property 'result' does not exist on type 'EventTarget'.
dist\tmp\app\+broker\company.edit\company.edit.ts(402,43): error TS2339: Property 'result' does not exist on type 'EventTarget'.
dist\tmp\app\+broker\company.registration\companyregister.ts(331,35): error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
dist\tmp\app\+broker\company.registration\companyregister.ts(350,35): error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
dist\tmp\app\+broker\company.registration\companyregister.ts(371,35): error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
dist\tmp\app\+broker\company.registration\companyregister.ts(383,40): error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
dist\tmp\app\+broker\company.registration\companyregister.ts(392,40): error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
dist\tmp\app\+broker\company.registration\companyregister.ts(440,41): error TS2339: Property 'result' does not exist on type 'EventTarget'.
dist\tmp\app\+broker\company.registration\companyregister.ts(474,41): error TS2339: Property 'result' does not exist on type 'EventTarget'.
dist\tmp\app\+broker\company.registration\companyregister.ts(815,20): error TS2339: Property 'setYear' does not exist on type 'Date'.
dist\tmp\app\+broker\company.registration\companyregister.ts(848,20): error TS2339: Property 'setYear' does not exist on type 'Date'.
dist\tmp\app\+broker\company.registration\companyregister.ts(868,20): error TS2339: Property 'setYear' does not exist on type 'Date'.
dist\tmp\app\+broker\placement\placement.ts(303,47): error TS2339: Property 'result' does not exist on type 'EventTarget'.
dist\tmp\app\+employee\+enrol.component\enrol.GPA\enrol.gpa.ts(222,31): error TS7006: Parameter 'data' implicitly has an 'any' type.
dist\tmp\app\+employee\+enrol.component\enrol.GPA\enrol.gpa.ts(233,30): error TS7006: Parameter 'observer' implicitly has an 'any' type.
dist\tmp\app\shared\toolbar\toolbar.component.ts(3,9): error TS2305: Module '"E:/tan/talinto/EBS/v2/ebs-ui/node_modules/ng2-bootstrap/ng2-bootstrap"' has no exported member 'DROPDOWN_DIRECTIVES'.
E:/tan/talinto/EBS/v2/ebs-ui/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(47,5): error TS7008: Member 'readonly' implicitly has an 'any' type.
E:/tan/talinto/EBS/v2/ebs-ui/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(149,27): error TS2304: Cannot find name 'jQuery'.
E:/tan/talinto/EBS/v2/ebs-ui/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(171,27): error TS2304: Cannot find name 'jQuery'.
[14:46:54] TypeScript: 19 semantic errors
[14:46:54] TypeScript: emit succeeded (with errors)

npm ERR! Windows_NT 10.0.10586

**Comment by sfabriece** [comment]
I think this should be configurable with the default being enabled.

**Comment by TheDonDope** [comment]
> with the default being enabled.

Waitaminute, so we use/have TypeScript for type safety and compile time error checking, but when errors arise, you want to be able to ignore them? Or did i understood you in a wrong way?

**Comment by sfabriece** [comment]
@TheDonDope I mean that semantic error checking should be enabled by default.
According the issue, some people might not want the checking enabled.

**Comment by tpruthi** [comment]
As of now i have removed following code from build.js.prod file to make it work

.once('error', function(e: any) {
      this.once('finish', () => process.exit(1));

**Comment by lifaon74** [comment]
Seems not to be a serious job if you disable semantic error. 'build.prod' is here to optimise final app AND have proper code for you and other developpers. If you have errors, you should fix them instead of hidding them... if you want to extend objects (ex: EventTarget qith result), you could create a new class and extend it with EventTarget or use something like `type EventTargetType = EventTarget & {result:any};`

**Comment by mgechev** [comment]
If you're absolutely sure what you do, you can set isolatedModules to true in compiler options,  but I'd not recommend you to do so.

**Comment by rousdan** [comment]
theres any alternative to ignore this in build.prod ? for example i'm using `zxcvbn` in one of my components but when i run prod i get can not find `zxcvbn`  i search in npm @types  but is not there so i added rigth in to `NPM_DEPENENCIES` Array
