### ISSUE TITLE
includes, findIndex, find does not exist on arrays?

### ISSUE THREAD

**Issue by neridonk** [mgechev/angular2-seed#1409]
Did I miss a breaking change or is this an Issue?

**Comment by mgechev** [comment]
Ost likely core-js is missing from your production/dev environment.

**Comment by mgechev** [comment]
On the other hand, the problem might be related with missing type definitions so this will be a duplication of https://github.com/mgechev/angular2-seed/issues/1408. 

The breaking change is that we migrated to the official solution of Microsoft for managing ambient type definitions.
