### ISSUE TITLE
build.dev task don't generate map files

### ISSUE THREAD

**Issue by nuzolx** [mgechev/angular2-seed#1410]
**Steps to reproduce and a minimal demo of the problem**

```
git clone --depth 1 https://github.com/mgechev/angular2-seed.git 
cd angular2-seed
npm install
npm run build.dev
```

_What steps should we try in your demo to see the problem?_

```
> find dist/ -name '*.map'
>
```
**Expected/desired behavior**
Generate map files for each ts file in app.

Thanks!

**Comment by mgechev** [comment]
We generate inline sourcemaps in order to reduce HTTP requests.
