### ISSUE TITLE
Cannot add bootstrap sass files

### ISSUE THREAD

**Issue by sinel** [mgechev/angular2-seed#1412]
Hi,

I'm trying to add the sass files from Bootstrap 4 into the seed. The seed is running fine as-is, and this is the first customization that I am attempting on top of it.

First, I added 
this.ENABLE_SCSS = true;
to project.config.ts, and changed all the existing .css extensions to .scss. This works fine.

Then, after installing Bootstrap 4 via npm, I added
{src: 'bootstrap/scss/bootstrap.scss', inject: true}
under NPM_DEPENDENCIES in project.config.ts. Running npm start, everything goes fine until it just stops at the following lines:
[17:29:47] Starting 'build.js.dev'...
[17:29:50] Finished 'build.js.dev' after 2.87 s
[17:29:50] Starting 'build.index.dev'...
[17:29:50] gulp-inject 2 files into index.html.
[17:29:50] gulp-inject 2 files into index.html.

There are no errors or any debug info reported. As best as I could, I tried going through build.index.dev by adding some logs and using gulp-debug, but I was unable to find anything that hints at what might be going wrong.

Checking my dist folder, I can see that a bootstrap.css file is generated successfully in the proper location. However, nothing is injected into the index.html file. 

I also tried adding
{ src: `${this.CSS_SRC}/bootstrap.css`, inject: true, vendor: false }
under APP_ASSETS in project.config.ts, but this does not help either.

If I manually copy the resulting bootstrap.css file into my src folder, and add a reference to it under APP_ASSETS only, then npm start works as expected. Yet I would like to customize the bootstrap sass files dynamically - it would be rather cumbersome to compile them separately each time.

Is this a bug, or am I trying to accomplish this in the wrong way?

Thanks!

**Comment by sinel** [comment]
If I copy the whole bootstrap sass folder under src, and add a reference to it under APP_ASSETS, then both the sass compilation and injection into index.html is working fine. Practically, this is a good enough solution since it only requires one extra step of copying the files from node_modules folder to src folder.

Still, this is not what I would have expected to do based on the documentation. So is this a minor bug, or am I misunderstanding the approach suggested by your documentation?

Thanks!

**Comment by sean-perkins** [comment]
You shouldn't have to modify the project config at all. Just leverage this all within your main sass file, via importing the actual bootstrap library in:

i.e. For the `bootstrap-sass` npm dependency: 
`@import 'bootstrap-sass/assets/stylesheets/bootstrap';`;

**Comment by sinel** [comment]
Thanks. That is what I'm basically doing now. I also understand that I can point directly to the bootstrap installation under node_modules, so I wouldn't have to copy the folder either. 
However I think accomplishing this by overriding NPM_DEPENDENCIES in project.config.ts is more consistent and much cleaner, and that is what I expected  to do based on the documentation.  Install via npm, override and it is injected for you. There is actually an example of this using bootstrap in the wiki:
https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles
So does this work with css only and we cannot handle sass in this manner?

**Comment by mgechev** [comment]
It should work with Sass too but you should refer to the CSS file not sass since it won't be copied to the target directory.

**Comment by HereThereBeMonsters** [comment]
I am struggling with this too. The main reason to use SASS bootstrap files over plain CSS files is so that you can customize them, so I think the approach to import them into your `main.scss` file makes more sense. You can then override variables and other things in this main file (or other SCSS files that you import into the main).

However I cannot import the bootstrap SCSS file from node_modules into my `main.scss`. I tried :

`@import '../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap';`

It does not work : the compilation fails because some bootstrap variables, used in my main, are undefined.

Any hint on how to achieve this without the additional manual copying step ? Should the path be relative to some other directory ?

**Comment by acivang** [comment]
@sinel hello! By the issues, so we only copy the bootstrap-sass folder to client/sass folder? i had the same problem.

**Comment by acivang** [comment]
oh!keep the seed config, it only add:

```code
@import 'bootstrap-sass/assets/stylesheets/bootstrap'; 
```

to css/main.scss
