### ISSUE TITLE
exclude module from the prod build

### ISSUE THREAD

**Issue by starswish2100** [mgechev/angular2-seed#1424]
Hi,

I do not use anugular 2 routing, rxjs, form, and http in my app. I want to exclude them from the finial build, to save some bandwidth. Can you please tell me how to do it?

Regards,
John Xu

**Comment by mgechev** [comment]
Sure, you can take a look at the [bundle arithmetic of systemjs](https://github.com/systemjs/builder#bundle-arithmetic). Basically you'd need to override the `bundle.*.prod` tasks (simply copy/paste them in `tools/tasks/project`) and reconfigure systemjs by taking in [mind this](https://github.com/systemjs/builder#bundle-arithmetic).
