### ISSUE TITLE
How do I use Semantic UI with NG2 Seed ?

### ISSUE THREAD

**Issue by marsdk** [mgechev/angular2-seed#1426]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

I am trying to add ngSemantic to be able to use https://github.com/vladotesanovic/ngSemantic

I have tried to add

this.NPM_DEPENDENCIES = [
            ...this.NPM_DEPENDENCIES,
            {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
            {src: 'ng-semantic/ng-semantic.js', inject: 'libs'},
];

Just adding with jquery does not fail, but adding the ng-semantic afterwards fails.

I have also tried adding it as 

this.APP_ASSETS = [
            ...this.APP_ASSETS,
             {src: `${this.APP_SRC}/node_modules/ng-semantic/ng-semantic.js`, inject: true, vendor: true}
        ];

Setting the vendor to either true or false gives the same. 

**Current behavior**

I keep getting this error : 
ng-semantic.js?1475608741400:14 Uncaught ReferenceError: require is not defined

The server is having issues locating it. 
WARN [web-server]: 404: /base/node_modules/ng-semantic.js
Chrome 53.0.2785 (Mac OS X 10.11.6) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng-semantic.js
	Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng-semantic.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:636:29)

I have also tried to change module in tsconfig.json 
 "module": "system",

That really gave a lot of error. 

**Expected/desired behavior**
I would love to use Semantic UI with NG2 Seed, but as a bigtime backender I am rather baffled with all the loading and JS magic that happens and not quite sure where to start here.

**Comment by mgechev** [comment]
Most likely you'd want to inject jquery and load ng-semantic ui `path`/`package` config with systemjs. This means keeping:

```ts
// notice that semantic ui is no here anymore
this.NPM_DEPENDENCIES = [
...this.NPM_DEPENDENCIES,
{src: 'jquery/dist/jquery.min.js', inject: 'libs'}
];
```

and add an entry in `SYSTEM_DEV_CONFIG`, or just require it with a regular import statement and probably it is going to work.
