### ISSUE TITLE
Suport to components using bower

### ISSUE THREAD

**Issue by netstart** [mgechev/angular2-seed#1430]
We need support to componentes using bower.

Like this...
https://vaadin.com/elements/-/element/vaadin-grid

**Comment by mgechev** [comment]
We are not planning to introduce bower support but you can do this yourself by updating the SystemJS configuration to take a look at modules in bower_components as well. If the bower packages that you're using expose global variables, you may consider injecting the script files (similarly to NPM_DEPENDENCIES.
