### ISSUE TITLE
Object doesn't support property or method "keys" IE 11

### ISSUE THREAD

**Issue by punov** [mgechev/angular2-seed#145]
Browser IE 11,
Object is not supported property or method 'keys',
File: angular2.dev.js, line: 4027, row: 5
if ((new exports.Map()).keys().next)  ....

What we can do here, any possible workarounds?
Thank you

**Comment by mgechev** [comment]
Its weird that https://github.com/mgechev/angular2-seed/pull/143 didn't fixes that issue.

Are you using any tag or the latest version, which is in master?

**Comment by punov** [comment]
Update with new changes helped as a charm, thank you!
Sorry for bothering

**Comment by navcoder** [comment]
Hi,
Has anyone checked this issue with the production build? I am facing this issue even with the seed project where npm-start (dev) version works fine on IE 11, but when I use "npm run build.prod" to create production build, it again throws the same error "Object doesn't support property or method "keys" on IE 11.
Please help its urgent.

**Comment by JohnCashmore** [comment]
I have this issue as well

**Comment by mgechev** [comment]
@navcoder most likely you'll need to include [this polyfill](https://github.com/mgechev/angular2-seed/blob/master/test-main.js#L1-L10) somewhere in the prod build:

**Comment by JohnCashmore** [comment]
should this not be included as part of the seed build? or is it down to something @navcoder put in their  project?

**Comment by mgechev** [comment]
Actually it is included in [dev and prod by default](https://github.com/mgechev/angular2-seed/blob/master/src/client/index.html#L21-L32).

Do you have this shim missing in your index.html, prod output?

**Comment by JohnCashmore** [comment]
I have the same issue and it is in the prod index.html and it still happens.

On Wed, Apr 20, 2016 at 2:03 PM, Minko Gechev <notifications@github.com>
wrote:

> Actually it is included in dev and prod by default
> <https://github.com/mgechev/angular2-seed/blob/master/src/client/index.html#L21-L32>
> .
>
> Do you have this shim missing in your index.html, prod output?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgechev/angular2-seed/issues/145#issuecomment-212414716>
>



-- 
Whoooop Ltd is a company registered in England and Wales. Registered
number: 8877885. VAT Registered: GB182051824. Registered office: 7
Kingsfield Crescent, Biddulph, ST8 6DW

**Comment by navcoder** [comment]
@mgechev , the error I mentioned specifically relates to the same es6-shim issue that was mentioned earlier.
On dev build I can see es6-shim js loaded and hence this error doesn't appear in it, but on production build since all the shims are bundled in shim.js I feel that es6 is not bundled in the shim.js, even though shim.js in added in index.html.
I also noticed that the NPM_DEPENDENCIES in seed.config.ts has "{ src: 'es6-shim/es6-shim.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },". Does this mean that es6 shim will not be bundled in production environment?

**Comment by nulldev07** [comment]
@mgechev @navcoder It works if I change NPM_DEPENDENCIES to:

```
  NPM_DEPENDENCIES: InjectableDependency[] = [
    { src: 'systemjs/dist/system-polyfills.src.js', inject: 'shims' },
    { src: 'reflect-metadata/Reflect.js', inject: 'shims' },
    { src: 'es6-shim/es6-shim.js', inject: 'shims' },
    { src: 'systemjs/dist/system.src.js', inject: 'shims' },
    { src: 'angular2/bundles/angular2-polyfills.js', inject: 'shims' },
    { src: 'rxjs/bundles/Rx.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/angular2.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/router.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/http.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT }
  ];
```

@JohnCashmore Can you please verify if this works for you?

**Comment by mgechev** [comment]
@nulldev07 would you try it with:

```ts
  NPM_DEPENDENCIES: InjectableDependency[] = [
    { src: 'systemjs/dist/system-polyfills.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'reflect-metadata/Reflect.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'es6-shim/es6-shim.js', inject: 'shims' },
    { src: 'systemjs/dist/system.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/angular2-polyfills.js', inject: 'shims' },
    { src: 'rxjs/bundles/Rx.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/angular2.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/router.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/http.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT }
  ];
```

**Comment by navcoder** [comment]
@mgechev  Nops with your change I am getting "Cannot redefine non-configurable property 'Reflect'" error in shim.js now.
@nulldev07 Yes with your changes it is working. Thanks ..

**Comment by navcoder** [comment]
It looks we can exclude "system-polyfills.src.js" as well. Below is working which means we need reflect, es6 and angular2-polyfill in production build to have it working on IE 11.

NPM_DEPENDENCIES: InjectableDependency[] = [
    { src: 'systemjs/dist/system-polyfills.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'reflect-metadata/Reflect.js', inject: 'shims' },
    { src: 'es6-shim/es6-shim.js', inject: 'shims' },
    { src: 'systemjs/dist/system.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/angular2-polyfills.js', inject: 'shims' },
    { src: 'rxjs/bundles/Rx.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/angular2.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/router.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/http.js', inject: 'libs', env: ENVIRONMENTS.DEVELOPMENT }
  ];

**Comment by nulldev07** [comment]
@mgechev Any reason why the shims were initially included in prod, but now they are not?

**Comment by mgechev** [comment]
It is a bug. Btw, @navcoder, @nulldev07 a PR with the valid config is welcome!

**Comment by nulldev07** [comment]
@mgechev Sent you a PR.
