### ISSUE TITLE
tslint is not warning of use of var

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#148]
Imho usages of ```var foo = 'bar';``` should be warned - we should user ```let foo = 'bar';``` right?

**Comment by ludohenin** [comment]
This is maybe too much opinionated ?

**Comment by mgechev** [comment]
Yeah, lets leave the tslint rules the way they are.

**Comment by tarlepp** [comment]
Hmm, I still think that we shoud add ```"no-var-keyword": true``` option to [tslint.json](https://github.com/mgechev/angular2-seed/blob/master/tslint.json) file to make sure that everyone is using the same coding style.

This was also discussed on #157
