### ISSUE TITLE
check node and npm version on preinstall

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#149]
I have seen multiple issues that users are getting when they use old version of ```npm```. So I recommend that we add ```engines``` definition to ```package.json``` for starters. Another thing could be simple test in ```preinstall``` task to make sure that current environment is ready for this awesome seed.

What do you think about this?

**Comment by ludohenin** [comment]
:+1:

**Comment by mgechev** [comment]
:+1:

**Comment by mgechev** [comment]
Actually, I'm not sure we set any restriction for usage of `npm` >= `3.0.0` or `node` >= `4.0.0` using engines, since developers won't get the seed from npm anyway.

Do you have any ideas how to workaround this?

**Comment by tarlepp** [comment]
That preinstall check could be the answer.
