### ISSUE TITLE
"serve" without using "build"

### ISSUE THREAD

**Issue by svrcekmichal** [mgechev/angular2-seed#15]
Just wanted to ask, why `serve.env` does call `build.app.env` and doesn't call `build.env`? I believe that building whole project on start of server is better solution, no need to enter `build.env` before `serve.env`.

**Comment by mgechev** [comment]
Thanks for the note! I think it makes sense to update `gulpfile.js`.

**Comment by ludohenin** [comment]
FYI, my idea behind that was that lib can take long to build and when working and a project I start the server more often than I need to build the libs. But that also fine.

**Comment by mgechev** [comment]
Yeah, makes sense as well. I think the feedback given by gulp is enough to make the developers aware that something is going on.
