### ISSUE TITLE
Inject dependency to Service

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#150]
Maybe it is not related to the project but it doesn't work.

I created new file services/model.ts

```typescript
export class Model {
  data = 'the data';
}
```
and edited name_list.ts:

```typescript
import {Inject} from 'angular2/angular2';
import {Model} from './model';

@Inject(Model)
export class NameList {
  names = ['Dijkstra', 'Knuth', 'Turing', 'Hopper'];
  constructor(model:Model) {
    console.log(model.data);
  }
  get(): string[] {
    return this.names;
  }
  add(value: string): void {
    this.names.push(value);
  }
}
```

When I click 'About' there is exception in browser console:
EXCEPTION: No provider for Model! (About -> NameList -> Model)

**Comment by ludohenin** [comment]
I think (to be confirmed) you have to tell ts compiler to generate metadata on your `Model` class.
this is a way:

```typescript
@Injectable()
export class Model {}
```

and you remove `@Inject`on `NameList` class.

**Comment by tandu** [comment]
I have tried to add `Injectable` to `Model` and it doesn't work. I have looked at generated js file, it properly wraps `NameList` and adds `Model` to its metadata, but browser shows that exception. I have searched in internet, it seems to be a correct way to add dependency to service, for example, check [here](http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html).

**Comment by mgechev** [comment]
As @ludohenin said, you need to add `@Injectable` to the `NameList` class.

```ts
@Injectable()
export class NameList {
  names = ['Dijkstra', 'Knuth', 'Turing', 'Hopper'];
  constructor(model:Model) {
    console.log(model.data);
  }
  get(): string[] {
    return this.names;
  }
  add(value: string): void {
    this.names.push(value);
  }
}
```

You should also provide a binding for the `Modal` class:

```ts
// ...
import {NameList, Model} from './services/name_list';

@Component({
  selector: 'app',
  viewBindings: [NameList, Model],
  templateUrl: './app.html',
  styleUrls: ['./app.css'],
  encapsulation: ViewEncapsulation.None,
  directives: [ROUTER_DIRECTIVES]
})
// ...
```

or 

```ts
bootstrap(App, [
  Model,
  ROUTER_BINDINGS,
  bind(ROUTER_PRIMARY_COMPONENT).toValue(App)
]);
```

**Comment by tandu** [comment]
It works, thank you for explanation.
