### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#157]
Should this repository contain some guidelines for contributing? Eg. something like https://github.com/makeusabrew/bootbox/blob/master/CONTRIBUTING.md ?

**Comment by ludohenin** [comment]
Nice one. Was thinking about the same.
I would add:

* open new issue to discuss new features before pulling requests.

**Comment by mgechev** [comment]
Yes, makes sense. I'd also add to run tslint in order to make sure they're following the same coding style.

**Comment by tarlepp** [comment]
Hmm, should we add tslint task to run with tests?

**Comment by ludohenin** [comment]
yes

**Comment by mgechev** [comment]
Imho, both testing and linting needs to be part of the CI, however, used as individual tasks i.e. linting should not be a subtask of testing since their purpose is different.

**Comment by mgechev** [comment]
Closed by https://github.com/mgechev/angular2-seed/commit/e9b77fccb6d4ff92a3dc19278585579273425830
