### ISSUE TITLE
Add clean node_modules folder onpreinstall ?

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#158]
I've also had some troubles installing the deps on a non fresh clone.
I think it'd good to clean node_module folder in preinstall script.

**Comment by tarlepp** [comment]
I think this would solve some issues about installation.

**Comment by tarlepp** [comment]
We could use same approach as in ng2 repository: https://github.com/angular/angular/blob/master/package.json#L26

**Comment by mgechev** [comment]
@tarlepp makes sense

**Comment by ludohenin** [comment]
@tarlepp :+1: - Shall I assign it to you ?

**Comment by tarlepp** [comment]
Seems like npm shrinkwrap is the way to handle this. This will cause some "extra" work when updating packages but not much. More info https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md .

Bigger problem is npm itself, seems like 3.x version has some major problems with shrinkwrap, more info https://github.com/npm/npm/issues/9907

**Comment by mgechev** [comment]
Yeah, I have some painful memories with shrinkwrap...Lets stay away from that until it gets the only option :-)

**Comment by tarlepp** [comment]
You have some other solution / thoughs for this?

**Comment by mgechev** [comment]
We can clean node_modules by using fs.unlinkSync for example.

**Comment by tarlepp** [comment]
sure but that won't fix the problem, also that would not prevent package versions changes. If that is the only option, then I would just add some "installation problems" section to readme.md and describe this there.

**Comment by mgechev** [comment]
Why would we need to lock the versions of the dependencies of the dependencies of the seed?

@ludohenin your problem occurs because of some mess around overriding of the dependencies caused by preinstall with existing `node_modules`, right?

**Comment by tarlepp** [comment]
imho the reason are fairly clear explained on ng2 repo https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md

If we don't want to _or_ can't use this aproach we should add eg. "Possible failures" to README.MD and provide these solutions there.

**Comment by ludohenin** [comment]
> If we don't want to or can't use this aproach we should add eg. "Possible failures" to README.MD and provide these solutions there.

I'd prefer the possible failure approach (a lot simpler :).
isn't it enough what we already have in the readme ?
```bash
npm install   # clean npm cache & delete node_modules folder if you get an error
```

**Comment by jesperronn** [comment]
[`npm prune`](https://docs.npmjs.com/cli/prune) is already done through `npm postinstall`, which in turn calls `gulp postinstall`, which calls `npm prune`.

**Comment by jesperronn** [comment]
@ludohenin I like your idea of keeping it simple and guide the user when in trouble. Have a look at #197 and see if that can help

**Comment by tarlepp** [comment]
So does anyone have other ideas for this? Still I think that shrinkwrap is the way to go, but it seems to be broken in 3.x npm atm.

**Comment by mgechev** [comment]
@ludohenin is this issue still active?

**Comment by ludohenin** [comment]
No, I think we have the right scripts for that now.
