### ISSUE TITLE
Refactor question - component naming with suffix 'Cmp' ...

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#164]
I'm not sure I agree with the direction of the usage of `Cmp` suffix on components at this point. I don't think that's become a standard and not sure we should adopt that yet.

The Ionic team with v2 has stuck with `Ctrl` suffix on components and that may be a better way to go as well as carry the torch on the good parts of Angular v1 and be easier for users of Angular v1 to move into. `Ctrl` may make the most sense.

\cc @mgechev @ludohenin 

...from Ionic v2 sample app:
![screen shot 2015-10-17 at 9 35 45 am](https://cloud.githubusercontent.com/assets/457187/10560030/ec975842-74b2-11e5-8a69-1a4182ee8459.png)

**Comment by mgechev** [comment]
@NathanWalker I agree that controller makes sense. I've talked with Misko and thats what the purpose of these ES2015 classes are. Respectively their constructor could be considered as the linking function of the directives from AngularJS 1.x.

**Comment by ludohenin** [comment]
Shall we go for `Ctrl` suffix then ? I'm also fine wit it.

**Comment by NathanWalker** [comment]
I think so. I would submit a PR today for it but doesn't look like I'll
have time.

**Comment by mgechev** [comment]
Okay

**Comment by NathanWalker** [comment]
Hmm well now I'm not sure lol. I saw a couple demo's from AngularConnect that were using `Cmp` as suffix, in particular Brian Ford's routing demo I believe used that.... sooooo, idk. I think I like `Ctrl` but I definitely like using standards that will be adopted everywhere. Whatever you guys think here.

**Comment by ludohenin** [comment]
`Cmp`for me. These classes are primarly annotated with `@Component.
Though in the continuation of ng1 it should be `Ctrl`.

**Comment by natarajanmca11** [comment]
I agree with @ludohenin point.

**Comment by mgechev** [comment]
`Cmp` works for components, however when you define a directive `Cmp` looks kind of confusing to me.

[Here is a poll](https://twitter.com/mgechev/status/658722311101620228) I started.

**Comment by JakePartusch** [comment]
According to John Papa's style guide, the Angular 1.x naming convention for controllers is: "ExampleController" with a file name of "example.controller.js"

With that in mind, it seems like "ExampleComponent" and "example.component.ts" will probably be the suggested Angular 2 naming conventions.

https://github.com/johnpapa/angular-styleguide#style-y124

**Comment by NathanWalker** [comment]
I've worked with many Angular apps and never seen `ExampleController` with `example.controller.js`. It's always been `Ctrl` as suffix. I can't even think of a sample online that used `Controller` as a suffix. Papa's styleguide is great, although that point I don't agree with.

It looks like `Cmp` is winning on the poll https://twitter.com/mgechev/status/658722824736129024

I think I'm still for `Ctrl` though as it does work for both components and directives, great point @mgechev

**Comment by jimthedev** [comment]
I will probably use example-list.component.ts and ExampleListComponent.

**Comment by JakePartusch** [comment]
If it adds any weight, at the Angular Connect conference, Rado Kirov and Naomi Black use ```HeroesComponent```

https://youtu.be/LS3aewTkfHI?t=174

**Comment by NathanWalker** [comment]
@jimthedev even for directives?

**Comment by jimthedev** [comment]
Yeppers. big-font.directive.ts, BigFontDirective class name. I can always import as something else (using 'import as' syntax) but I want it to be clear in my intellisense what I'm being selecting.

**Comment by NathanWalker** [comment]
@jimthedev Are you opposed to shorthand like `BigFontDir` or `BigFontDrv`?
I feel like shorter names with sensible shorthands is always nicer to navigate than full names.

**Comment by NathanWalker** [comment]
I recently wrote a library (https://github.com/NathanWalker/ng2-image-lazy-load) where I ended up using `Cmp` as suffix and `.directive` or `.service` in naming files. Go figure, it just made sense.

And maybe this debate is over?  Seems `Cmp` is winning out?

**Comment by ludohenin** [comment]
For @johnpapa this is `Component`.
https://github.com/johnpapa/vscode-angular2-snippets/blob/master/snippets/typescript.json#L12

**Comment by NathanWalker** [comment]
I can understand using the full name as suggested above. My only reservation there is sometimes I code a lot on the go, and often on a smaller screen. Simply put, longer names get truncated more often. 
I also like to browse a file tree with less clutter and shorter names, just faster to sift through. (without requiring one to potentially widen the default OS X column view finder window size.)

I find it somewhat surprising that longer names are recommended when often their short equivalent is more than adequate.

**Comment by ludohenin** [comment]
@NathanWalker I agree with you. Was just to share it.

**Comment by mgechev** [comment]
We can close it for now and rename the components according to the official style guide which the Angular team will propose.
