### ISSUE TITLE
typescript-register throws error in gulp postinstall

### ISSUE THREAD

**Issue by TylerEich** [mgechev/angular2-seed#179]
~~Here's the full log from npm: http://cl.ly/1A2x163g1L12/npm-debug.log
Obviously the errors related to postinstall will be at the end.~~

```
angular2-seed/node_modules/typescript-register/index.js:132
    var result = checker.emitFiles();
                         ^

TypeError: checker.emitFiles is not a function
```

~~I'm assuming this is typescript-register's fault, but the build process is broken for this repo, so I thought I'd bring it up.~~

I think my internet connection may be flaking out on the build process, closing until I know for sure…

**Comment by UncleVader** [comment]
Hi, could you share your experience about solving this issue, please?
I have the same, but don't know what I need to do.
Thanks!

**Comment by TylerEich** [comment]
I think I just deleted and reinstalled. I can't say for sure tho…I use the Angular CLI now, which solved many of my issues from a few months ago
