### ISSUE TITLE
Urls use absolute paths, should use relative ones

### ISSUE THREAD

**Issue by brtnshrdr** [mgechev/angular2-seed#18]
I have this project deployed at http://.....com/test/

The project doesn't work because the links use absolute paths, not relative ones (It tries pulling files, say "angular.js", from http://...com/angular.js instead of http://.....com/test/angular.js)

I got it to "work" by modifing this line in the gulpfile.js

arguments[0] = filepath.replace('/' + PATH.dest[env].all, '') + v;
with
arguments[0] = filepath.replace('/' + PATH.dest[env].all, './') + v; (Notice the "./")

It created some weird but tolerable side effects, but after updating the project to master, those lines were changed and the fix no longer works! 
Any ideas on how to fix this?

**Comment by mgechev** [comment]
Thanks for pointing this out! I'll take a look at this issue today

**Comment by brtnshrdr** [comment]
Everytime you refresh the page now, it adds an extra "/" to the url. So after 5 refreshes, the url looks like this:

`http://.....com/test//////`
