### ISSUE TITLE
Mismatch between SASS and components

### ISSUE THREAD

**Issue by briantopping** [mgechev/angular2-seed#188]
Seems like there is a mismatch between SASS and components. Components all have their own CSS files and `tools/tasks/build.sass.dev.ts` compiles CSS from the entire project.

Ideally, each component would be able to have it's own SASS compilation, including import of partials from the top-level project. The results for each SASS compilation would be usable by the corresponding `styleUrls` attribute of the individual component.

**Comment by ludohenin** [comment]
Not sure to follow you. Sass tasks is more here for illustration purpose.

**Comment by briantopping** [comment]
We talked about this in chat yesterday, you said "as we don't have components-wise approach". Maybe the components folder should be called something else then. 

If it's just for illustration purpose, maybe #193 should be there too? It's just there for illustration as well. Not very good for components and I don't use the word "media". :-)

**Comment by DennisRoam** [comment]
I think he means to have each sass file compile against a "main" sass file so you can import the colors, variables, etc. without adding the @import to each file. So instead of a simple * in the gulp you'd have an iterating function. 

I played with it for a bit and it's totally doable but for the mean time I just do @import to a base file..

**Comment by simonh1000** [comment]
I think it may be enough to import one specific scss file first, and then the rest using glob

**Comment by DennisRoam** [comment]
Yeah I think so too, I haven't had the chance to work on the gulp file enough to figure out how to do it. I'd love to see what someone could come up with.

**Comment by simonh1000** [comment]
Spoke too soon - I had forgotten that each file is compiled separately and returned into its original direction (polluting the source files with compiled content), and thus there is not a big concatenation of files where we could put the variables first. 

I'm not sure how to combine an scss file with a set of variables in gulp, but will look into it

**Comment by ludohenin** [comment]
SASS seems to be topic here, anyone with suggestions how to improve how SASS build is handled.

**Comment by mgechev** [comment]
Lets close this one for now since SASS is not our current focus. However, we can keep an eye on it in case SASS support is highly demanded.

**Comment by malfborger** [comment]
Have someone solved it nicely w/ SASS?

**Comment by simonh1000** [comment]
No, and after implementing SASS per the example instructions by production build completely fails looking for css files in each component.
