### ISSUE TITLE
`./tsd_typings/**/*.d.ts`  entry is not required in `tsconfig.json` file's `filesGlob` array object. 

### ISSUE THREAD

**Issue by natarajanmca11** [mgechev/angular2-seed#189]
`./tsd_typings/**/*.d.ts`  entry is not required in `tsconfig.json` file's `filesGlob` array object. 
Please confirm.
Briefly explain about 'filesGlob' in tsconfig.json.

**Comment by ludohenin** [comment]
@natarajanmca11 filesGlob is used by IDE's to auto-populate the `files` array.

**Comment by jesperronn** [comment]
See also #224 for a simpler solution
