### ISSUE TITLE
Gulp Error

### ISSUE THREAD

**Issue by previousdeveloper** [mgechev/angular2-seed#190]
⨯ Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)

**Comment by briantopping** [comment]
Did you install according to the README? What versions of NPM and Node are you using?

**Comment by previousdeveloper** [comment]
yes I did, npm =3.3.3 and node= v4.0.0

**Comment by briantopping** [comment]
You might want to try something closer to 3.3.6 and 4.2.1.

**Comment by previousdeveloper** [comment]
I have updated but still same error , this is error detail

[20:31:30] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
----------------------------------

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

**Comment by briantopping** [comment]
Did you try removing `node_modules` and do a `git clean -f` after upgrading? I've seen this before, but I don't remember exactly how I fixed it.

**Comment by ludohenin** [comment]
pretty sure this is related to #184

**Comment by ludohenin** [comment]
@previousdeveloper do you still have this issue ?
I checked again about a possible explanation (#184) but it works just fine on my machine.

**Comment by ludohenin** [comment]
@previousdeveloper any updates on this issue ?

**Comment by previousdeveloper** [comment]
I am getting still same error in case of about a possible explanation [#184](https://github.com/mgechev/angular2-seed/issues/184)

**Comment by mgechev** [comment]
@previousdeveloper still reproducible?

**Comment by 1thrasher** [comment]
@mgechev Yes, this is still occurring. Running `tsd update` (see #232) prior to `npm start` fixes it.

**Comment by previousdeveloper** [comment]
thanks
