### ISSUE TITLE
Cleanup Removing merged branches

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#199]
Hi

could one of you with admin permissions please remove the branches already merged in this project

The easiest is probably to navigate to https://github.com/mgechev/angular2-seed/branches and delete the following:

```
  remotes/upstream/alpha42            f1a48e6 Update to alpha42
  remotes/upstream/alpha44            298d4a1 Update to alpha44
  remotes/upstream/issue_130          46b673d Fix #130
  remotes/upstream/revert-162-alpha42 0325deb Revert "Update to alpha42"
```

Thanks for keeping this repos clean :+1:

**Comment by ludohenin** [comment]
Done. Thanks for pointing that out :).
