### ISSUE TITLE
Update for Angular2 alpha 21

### ISSUE THREAD

**Issue by johnjelinek** [mgechev/angular2-seed#2]
Is there any plans to update this to the latest alpha (and TypeScript 1.5 beta)?

**Comment by mgechev** [comment]
Next few days I'll be busy traveling. Right after that I'll update it, it's in my schedule already. Thanks for the reminder! :-)

**Comment by johnjelinek** [comment]
yw

**Comment by flyingzl** [comment]
I seems that upgrading to `Angular2 alpha 21`  will break `gulp build:angular`

**Comment by johnjelinek** [comment]
alpha 22 is out now



—

**Comment by mgechev** [comment]
Yes, I saw that. I'll spend the rest of the day working on migration of the seed project to alpha 22.

**Comment by johnjelinek** [comment]
Great! Don't forget to change your imports for Components/Views/Directives:


```

import { ComponentAnnotation as Component, ViewAnnotation as View } from "angular2/angular2";

```




The @RouteConfig() annotation is now available too, but you'll need to add the additional router lib and import from "angular/router".





—

**Comment by mgechev** [comment]
There are still some things which could be polished but it works with alpha 23.

**Comment by johnjelinek** [comment]
:+1: thanks.

**Comment by mgechev** [comment]
We have some tags [here](https://github.com/mgechev/angular2-seed/releases). I didn't create one for alpha 23, if someone need it I will.
