### ISSUE TITLE
Adding dependencies compile-time, test-time, run-time

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#201]
I really like how the seed project here helps me getting started on new projects. :+1: 

A typical task is to add an external library to my code (based on this project). Last week I burned my fingers twice, since I neglected to see there were many places I had to add the dependency.

Given you use the dependency in a test, you have to add it to the following

1. [package.json] as a dependency
2. [karma.conf.js] for loading during test
3. [test-main.js] also for test purposes (not sure I can explain exactly when or why this is needed)
4. [tools/config.ts] which is adding runtime to the main index.html page

It has bitten me twice last week alone. And my problem is I can add at 1 and 2, and my tests are happy. If I forget 3, I get a compile error. But if I forget 4, i will get no error at all.

Forgetting number 4 simply gives me a runtime error, which I will never see compile-time or test-time.

I had a look at how number 4 is used. The files listed in [tools/config.ts] are used in the main [app/index.html] file and injected JavaScript files. One per line. This is pretty much the same functionality I have seen in Wiredep module earlier. 

### Problem 1: Speed and rankings

I have one big problem with adding individual files to my page: Individual javascript files require individual HTTP requests (at least until HTTP2/SPDY is widespread), and it affects my SpeedIndex results, and my Google rankings.

The common solution is to add one or two concatenated, prebuilt files (minified).

Sometimes this is not done in 'developer mode', in order to ease debugging which can be harder in minified files (Ruby on Rails or Grails frameworks are examples for that).

Now, after Sourcemaps are working in all modern browsers, I see no problem with this. We can have the minified files, and easily debug with the help of sourcemaps. 

### Next problem: Not catching errors before runtime

The three lists in the three different files represent a potential problem for people like me that neglect to add the dependencies in all the files. I would really like us to be able to catch that last error before runtime, since runtime requires tedious, repeated, manual testing.

### One suggestion:

I don't know exactly how, but I would really like to use the same list of files in all three places. Can you help me figuring out how this should be done? 

* Make use of same dependency list in [karma.conf.js], [test-main.js], [app/index.html]
* Build and minify a javascript bundle – minified, concatenated (could be implemented separately)

This would have the obvious advantage of catching the error earlier and having no differences between compiled and served. Perhaps we could use the concatenated, minified js version in the tests as well?

I really love to hear your thoughts on this, since I think this is an area where errors can be easily made. 
And also hard to discover. Please share your thoughts :)

/cc @larsthorup

[package.json]: https://github.com/mgechev/angular2-seed/blob/399e411195075bbfb1e3fafd41043f52ec1b2f09/package.json
[karma.conf.js]: https://github.com/mgechev/angular2-seed/blob/399e411195075bbfb1e3fafd41043f52ec1b2f09/karma.conf.js#L26
[test-main.js]: https://github.com/mgechev/angular2-seed/blob/399e411195075bbfb1e3fafd41043f52ec1b2f09/test-main.js#L14
[tools/config.ts]: https://github.com/mgechev/angular2-seed/blob/399e411195075bbfb1e3fafd41043f52ec1b2f09/tools/config.ts#L43
[app/index.html]: https://github.com/mgechev/angular2-seed/blob/399e411195075bbfb1e3fafd41043f52ec1b2f09/app/index.html#L17

**Comment by ludohenin** [comment]
Thanks for your inputs @jesperronn 
I'm actually still working on improving the build and config. Will for sure consider your suggestions.

**Comment by jesperronn** [comment]
:+1:

**Comment by RuneMolin** [comment]
Running

    npm install postal --save
    npm run tsd install postal

seem to install to module and typings, and updates package.json

**Comment by mgechev** [comment]
Lets close this one. We're on our way of solving the way the dependencies should be provided here https://github.com/mgechev/angular2-seed/issues/255
