### ISSUE TITLE
Test with Internet Explorer?

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#202]
To ensure browser compatibility, I would like to run the Karma test suite via the CI service Appveyor.com as a supplement to the Travis build.

My preliminary findings:

Appveyor jobs seem very flaky. I am currently experimenting in my own fork of the seed project: 

* https://ci.appveyor.com/project/jesperronn/angular2-seed/history

Also, job times seem to vary immensely: It can take anythiing from 4 to 41 minutes to run a job. Compare that to ~3 minutes on Travis.

Thoughts?

**Comment by jesperronn** [comment]
Update, I am closer than before. I was able to bypass tsd-errors with PR contents from #200, and now I am down to this error in the [appveyor build](https://ci.appveyor.com/project/jesperronn/angular2-seed/build/22)

```
> gulp test
 
[11:49:29] Requiring external module ts-node/register
npm : 
At line:1 char:1
+ npm test # PowerShell
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\projects\angular2-seed\tools\utils\tasks-tools.ts:32
    readdirSync(path).forEach(function(file) {
                      ^
TypeError: undefined is not a function
    at C:\projects\angular2-seed\tools\utils\tasks-tools.ts:38:47
    at Array.forEach (native)
    at walk (C:\projects\angular2-seed\tools\utils\tasks-tools.ts:32:23)
    at scanDir (C:\projects\angular2-seed\tools\utils\tasks-tools.ts:29:3)
    at Object.autoRegisterTasks (C:\projects\angular2-seed\tools\utils\tasks-tools.ts:10:3)
    at Object.<anonymous> (C:\projects\angular2-seed\gulpfile.ts:13:1)
    at Module._compile (module.js:460:26)
    at Object.loader (C:\projects\angular2-seed\node_modules\ts-node\dist\ts-node.js:94:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
 
npm
 
ERR!
 Test failed.  See above for more details.
 
```

Any help interpreting or changing the code will be greately appreciated :+1:

**Comment by ludohenin** [comment]
Looks like issue #195 solved by #196 (to be merged, see open discussion)

**Comment by ludohenin** [comment]
What version of node are you running ?

**Comment by jesperronn** [comment]
The appveyor now runs `{"node":"0.12.7","npm":"2.11.3"}`, which I believe is their standard.

The build takes a loong time, so for now, I wanted to avoid installing specific versions. these are the defaults, but can be easily modified in [`appveyor.yml`](https://github.com/mgechev/angular2-seed/blob/1aa2d865e67653ed7ee965ff28928717b07f9c63/appveyor.yml)

**Comment by ludohenin** [comment]
Then it confirm you're having the same issue as #195.

**Comment by jesperronn** [comment]
Thanks @ludohenin, will try to downgrade to 0.10 for the sake of this experiment. :+1: for solving #195

**Comment by tarlepp** [comment]
Hmm, I have done some work with Travis CI (currently Travis CI is testing linux and osx environments, see #207 ) and now I'm searching CI system for Windows environment. Is appveyor the only one?

**Comment by mgechev** [comment]
https://github.com/mgechev/angular2-seed/issues/195#issuecomment-152824109

**Comment by jesperronn** [comment]
@mgechev @tarlepp I looked into some other projects wanting windows support. Travis started considering this in 2011, but still hasn't windows support. See this thread for details https://github.com/travis-ci/travis-ci/issues/216

Node-sqlite3 project actually has windows builds, and they seem to be using appveyor.

See 

* https://github.com/mapbox/node-sqlite3/issues/261
* https://ci.appveyor.com/project/Mapbox/node-sqlite3/history

Although 'support' I see a LOT of red builds in appveyor. Which is annoying. 

Closing would be more appropriate if we had another solution. However, agree that the current state of this PR gives too many errors. 

Current appveyor seems flaky. Examples from other projects: 

* https://github.com/mapbox/node-sqlite3/pull/486
* https://github.com/mapbox/node-sqlite3/pull/488

BTW, Ember seem to have less red in the history of appveyor builds:
https://ci.appveyor.com/project/embercli/ember-cli/history

Any alternatives to Appveyor?
Any obious modifications to my example that could help?

**Comment by jesperronn** [comment]
Awesome! I now think I have a [stable setup of Appveyor/Internet explorer](https://ci.appveyor.com/project/jesperronn/angular2-seed/build/60). Will give a Pull-req on it

**Comment by mgechev** [comment]
Great! Looking forward to merge it!
