### ISSUE TITLE
API Deprecation in alpha 41

### ISSUE THREAD

**Issue by mmrath** [mgechev/angular2-seed#205]
Looking at the change log for alpha 41, there are quite a few deprecations. We should change to use the new terminology?

https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha41-2015-10-13

**Comment by mgechev** [comment]
We have already tagged alpha42. What changes do you suggest?

**Comment by ludohenin** [comment]
@mgechev I rapidly checked ng2 source today and yes, basically all `binding(s)` are now called `provider(s)`. There is maybe more. It works as is but prop/method are annotated `@Deprecated`.

**Comment by mgechev** [comment]
Yeah, `bindings` -> `providers`, `events` -> `outputs`, `properties` -> `inputs`. I didn't notice we're using `bindings`.

**Comment by mmrath** [comment]
Angular release note says
>"DI Binding" terminology has changed to "DI Providers" to avoid conflicts/confusion with data-binding. All commonly used apis that use "bind" or "binding" in the name still work but are deprecated and will be removed in future alpha releases. Please update your code:
bind -> provide
@Component(bindings: ...) -> @Component(providers: ...)
@Component(viewBindings: ...) -> @Component(viewProviders: ...)
HTTP_BINDINGS -> HTTP_PROVIDERS
JSONP_BINDINGS -> JSONP_PROVIDERS
ROUTER_BINDINGS -> ROUTER_PROVIDERS
FORM_BINDINGS -> FORM_PROVIDERS
ELEMENT_PROBE_BINDINGS -> ELEMENT_PROBE_PROVIDERS
NoBindingError -> NoProviderError
AbstractBindingError -> AbstractProviderError
InvalidBindingError -> InvalidProviderError
beforeEachBindings -> beforeEachProviders
Binding -> Provider

One example from angular-seed app/bootstrap.ts
```typescript
import {bind, bootstrap} from 'angular2/angular2';
import {ROUTER_BINDINGS, ROUTER_PRIMARY_COMPONENT} from 'angular2/router';
import {AppCmp} from './components/app/app';
```
Do we need to change this to 

```typescript
import {provide, bootstrap} from 'angular2/angular2';
import {ROUTER_PROVIDERS, ROUTER_PRIMARY_COMPONENT} from 'angular2/router';
import {AppCmp} from './components/app/app';
```
