### ISSUE TITLE
Make test and start tasks fail on lint errors?

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#206]
Due to our test/ci setup, it would be useful if the test or server task can fail if any linting errors occur.

There is no reason the test suite runs if there is a linting error and code may not be working. For me, that would make turnaround faster.

Technically, the test job uses Gulp `run-sequence` plugin, but don't quite get how that should be modified if you like the idea.

What do you think?

**Comment by mgechev** [comment]
Sounds like a good idea to me.

I've implemented similar functionality at https://github.com/mgechev/javascript-algorithms

**Comment by ludohenin** [comment]
The simplest way I see is to install `tslint` and to add `tslint **/*.ts` to npm scripts hash wherever required.

**Comment by ludohenin** [comment]
btw, this way we can probably remove the `tslint` task.

**Comment by e-oz** [comment]
Please leave some config to turn this behavior off, because for some projects ts-linting is just annoying addition (IDE shows all errors and much smarter).

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/commit/18b988cef70fe9c07abb7ecac64822d7d59f566e
