### ISSUE TITLE
import own modules, not from files

### ISSUE THREAD

**Issue by sclausen** [mgechev/angular2-seed#209]
I thought it would be a good idea for large scale applications to write own definitions, for importing by module name and not by filename.
So I created a `name_list.d.ts`
``` typescript
declare module NameList {
  class NameList {
    names: Array<string>;
    get(): string[];
    add(value: string): void;
  }
}

declare module 'NameList' {
  export = NameList;
}
```
and in `about.ts` I import it like this
``` typescript
import {NameList} from 'NameList';
```
But system.js still tries to import by filename, so I got this error

![is-this-a-bug](https://cloud.githubusercontent.com/assets/916076/10812120/29e4a948-7e13-11e5-9b7c-0c25f9517dfe.png)

Am I doing something fundamentally wrong, or is this a misconfiguration or maybe a bug?

**Comment by ludohenin** [comment]
@sclausen you have to add `paths: { 'NameList': 'service/name_list' }` to `system.config.js` (without system tries to load it form server root).

**Comment by sclausen** [comment]
Yes, this did the job, thanks! :smile:

**Comment by jesperronn** [comment]
@sclausen just curious, can you post an example of your modified code, so that others can learn from it?

**Comment by ludohenin** [comment]
@jesperronn You can have a look at this one, https://github.com/ludohenin/angular2-seed-ng2-bootstrap which is basically the same thing.

**Comment by sclausen** [comment]
@jesperronn: I can't really write more than that. It works simply by adding the module name you want to use in the `system.config.js` and do everything else I already described. I simply missed to tell system.js to load the module `NameList` from the path were the ts-file will be.

``` js
System.config({
  defaultJSExtensions: true,
  paths: {
    'NameList': 'services/name_list'
  }
});
```

**Comment by sclausen** [comment]
@jesperronn: I can't really write more than the code in my question and the answer. It works simply by adding the module name you want to use in the `system.config.js` and do everything else I already described. I simply missed to tell system.js to load the module `NameList` from the path were the ts-file will be.

``` js
System.config({
  defaultJSExtensions: true,
  paths: {
    'NameList': 'services/name_list'
  }
});
```
