### ISSUE TITLE
Move building dependency angular2 from es6 to ts

### ISSUE THREAD

**Issue by hakamairi** [mgechev/angular2-seed#21]
The Angular2 node_module/sources are delivered in TypeScript as well, why not to use those instead es6? 

You could loose the definitions file then.

**Comment by ludohenin** [comment]
@hakamairi we are working on it but the benefit does not seems to be that high. Still need System to build a single file.

**Comment by mgechev** [comment]
Here's one related issue https://github.com/mgechev/angular2-seed/issues/44

**Comment by ludohenin** [comment]
@mgechev I think we can close this issue. This is a no go imo as we will either be using the bundles (now supplied with npm pkg) or the es6 format (may be in the future for very modern browsers). But building from ts just adds an extra build step (ts > js > bundled js) that is not necessary.
