### ISSUE TITLE
Server never serves 404 not found

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#210]
When I start a webserver, then I am surprised that I will not get a `404` error if I try to load a nonexisting file (for instance `http://localhost:5555/nonexisting-url-not-matching-any-files.json`)

This is probably related to configuration of the webserver:

https://github.com/mgechev/angular2-seed/blob/master/tools/utils/server.ts#L23

I believe that the thought behind it is that if you cannot find an URL, then serve the frontpage `/index.html`. This works well for `/`, which is then resolved to the context of `/index.html`.

Elsewhere, I think it typically is done as redirecting from `/` => `/index.html` (client-side redirect 301 or 302)

Two things:

1. For my own purpose: How can I ensure that `404` are served (I need them for json responses so that I don't parse unless a correct file is loaded)
2. For the purpose of this project: Does it make sense to modify the default, so that we don't eat the `404`

**Comment by ludohenin** [comment]
@jesperronn We basically return index.html for every request not matching a static resource to support deep linking page reload (i.e. localhost:555/about).
if you want to track not found statics, then you will have to "namespace" them (say `assets`) then add a route to the server `assets/*` and return `404`

**Comment by jesperronn** [comment]
ah I see. Will close this issue as it works per design. 

For my purpose I learned that I could comment out the lines 22-24

```
  //server.all(APP_BASE + '*', (req, res) =>
  //  res.sendFile(resolve(process.cwd(), PATH.dest[ENV].all, 'index.html'))
  //);
```

https://github.com/mgechev/angular2-seed/blob/e1c2460aeda72d97960f7b59b706f4b3d64d5bd2/tools/utils/server.ts#L22:L24

Exactly like @ludohenin comments: This requires me to reload the page from `/` and that `/about` will not work directly in the browser. However, for my purpose I like that tradeoff :+1:
