### ISSUE TITLE
Docs are not generated.

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#215]
When I run `npm docs` it opens this url `https://github.com/mgechev/angular2-seed#readme` in browser and there is no `docs` folder in project root. Maybe you missed some files in commit?

**Comment by tarlepp** [comment]
Hmm, weird I tried that and docs are served as supposed.

**Comment by natarajanmca11** [comment]
I think `gulp build.docs` command's  source only merged with master. `gulp serve.docs` command's source not merged with master.  please refer https://github.com/mgechev/angular2-seed/commit/c231391f1c0f1d35d7d0bafba7e4fc7175434f27

**Comment by tandu** [comment]
`gulp build.docs` works, `npm docs` doesn't work.

**Comment by ludohenin** [comment]
you have to `npm run docs`

**Comment by tandu** [comment]
```bash
➜  angular2-seed git:(master) npm run docs
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "run" "docs"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.8

npm ERR! missing script: docs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tandu/work/active/gl/Iris3/angular2-seed/npm-debug.log
```

**Comment by ludohenin** [comment]
@tandu yeah, I just updated my answer

**Comment by tandu** [comment]
I see, thanks, `gulp build.docs` works as well. In `readme.md` it says that to generate docs we should use `npm docs`. Either readme should be updated or this command should work. Right now it might confuse users.
