### ISSUE TITLE
Working with subfolders

### ISSUE THREAD

**Issue by artaommahe** [mgechev/angular2-seed#218]
Want to add small monitoring app as subfolder for main (local dev urls futher)
```
// main app
http://smth/
// monitoring app(with this seed)
http://smth/monitoring
```
nginx config
```nginx
location ~ ^/monitoring/(.*)$ {
    alias /path/to/main/app/monitoring/dist/dev/
}
```
config.ts
```typescript
export const APP_BASE         = argv['base']        || '/monitoring';
```

When i open http://smth/monitoring all css/js files loaded properly, but then
```http
GET http://smth/bootstrap.js 404 (Not Found)
Error: XHR error (404 Not Found) loading http://smth/bootstrap.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"
```
Real location of bootstrap.js for '/monitoring' APP_BASE is http://smth/monitoring/bootstrap.js and here it's opened.

Am i missed some config var or this case does not implemented yet?

**Comment by mgechev** [comment]
Did you add bootstrap to this array? https://github.com/mgechev/angular2-seed/blob/master/tools/config.ts#L42-L68

**Comment by ludohenin** [comment]
> `export const APP_BASE         = argv['base']        || '/monitoring';`
should be
`export const APP_BASE         = argv['base']        || '/monitoring/';` (with trailing slash)

**Comment by artaommahe** [comment]
> export const APP_BASE = argv['base'] || '/monitoring/'; (with trailing slash)

this helps, thx
