### ISSUE TITLE
Useless .js files created inside the app directory

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#22]

**Comment by ludohenin** [comment]
@mgechev when do you get that ? what's the file name ? I don't have any on my side.

**Comment by mgechev** [comment]
After I run `gulp serve.dev`, open `app.ts`, save it there are `*.js` files created in `/app`. Basically all TypeScript files except `init.ts`.

**Comment by mgechev** [comment]
I reproduced the issue when run `gulp build.app.dev` and while the task was running saved the `app.ts` file...

**Comment by mgechev** [comment]
It seems my vim configuration (I guess the TypeScript tools I use), causes this.
