### ISSUE TITLE
add autogenerated js

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#220]
I'm adding `socket.io` to the project. How should I include its `js` file? That file is generated on the server side automatically and is accessible at `/socket.io/socket.io.js` url. I have added it to `index.html` here:
```html
  <script src="/socket.io/socket.io.js"></script>
  <!-- inject:js -->
  <!-- endinject -->
```
in my component I use it that way:
```typeScript
/// <reference path="../../../tools/typings/tsd/socket.io-client/socket.io-client.d.ts" />
import {Component} from 'angular2/angular2';
declare var io: SocketIOClientStatic;

@Component({
  selector: 'home',
  templateUrl: './components/home/home.html',
  styleUrls: ['./components/home/home.css']
})
export class Home {
  constructor() {
    // listen to notifications about images uploading
    io().on('imageUploaded', function(data) {
      console.log('data: ' + data);
    });
  }
}
```
Is it right way to add remote js files?

**Comment by mgechev** [comment]
Yes, seems good to me, or you can include it to [this array](https://github.com/mgechev/angular2-seed/blob/master/tools/config.ts#L42-L53).

**Comment by jesperronn** [comment]
In case you wonder where to include your file, see #201 for a longer explanation
