### ISSUE TITLE
'Type Definitions' from tsd.json are not installed on 'npm start'

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#232]
I have added new td
```bash
tsd install socket.io-client --save 
```
When I checkout project and run install definitions are not installed. I think you should add `tsd update` into preinstall or postinstall script.

**Comment by mgechev** [comment]
@tandu I'll take a look at this issue tomorrow. Thanks for the suggestion!

**Comment by mgechev** [comment]
I've been quite busy last days. I'll take a look at the issue during the weekend or early next week.

**Comment by sclausen** [comment]
@tandu typings are installed with `postinstall` after `npm install`

**Comment by mgechev** [comment]
Is this issue still reproducable?

**Comment by tandu** [comment]
I haven't added more libraries after that. Probably this issue was solved at some time in the past. If I ever face with it again I will let you know. I think you can close this issue for now.

**Comment by mgechev** [comment]
Okay, great
