### ISSUE TITLE
Component level assets.

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#236]
I have modified logic in my project so components have their assets inside their folder. That way I think it will be easier to reuse components.
```md
.
├── app
│   ├── bootstrap.ts
│   ├── components
│   │   ├── about
│   │   │   │   ├── assets
│   │   │   │   │   └── image.jpg
│   │   │   ├── about.html
│   │   │   ├── about.ts
│   │   │   └── about_spec.ts
```
I have added `build.images.dev.ts`
```javascript
import {join} from 'path';
import {PATH} from '../config';

export = function buildImagesDev(gulp, plugins) {
  return function () {
    return gulp.src([
        join(PATH.src.all, '**/*.png'),
        join(PATH.src.all, '**/*.jpg'),
        join(PATH.src.all, '**/*.svg')
      ])
      .pipe(gulp.dest(PATH.dest.dev.all));
  };
}
```
It preserves images location throughout the project, and we can add here more asset types. What do you think? Will you add support for `assets` in components folders?

**Comment by johnjelinek** [comment]
This should address @mgechev's concern in #167. This + #233 should handle global and local assets.

**Comment by mgechev** [comment]
@tandu looks good to me! Do you want to open a PR?

**Comment by tandu** [comment]
here it is https://github.com/mgechev/angular2-seed/pull/239
