### ISSUE TITLE
Shorten paths in styleUrls and templateUrl

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#240]
I have created this issue https://github.com/angular/angular/issues/5183 in angular 2. Will it work with current angular2-seed implementation in case they add that feature? If not can you make it to be possible to shorten file names to look like that?
```typeScript
@Component({
  selector: 'about',
  templateUrl: './about.html',
  styleUrls: ['./about.css']
})
```
It will make components be portable without editing urls in sources if component is copied into another location/project.

**Comment by ludohenin** [comment]
Closing this issue as not related to the seed.
If any new features/implementations in ng2 brake it, of course we will fix.
