### ISSUE TITLE
Where put custom type definitions?

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#241]
I have defined some interfaces in my application. For now they are defined in `ts` files where they are used or logically bound. As I understand type definitions should be moved into `*.d.ts` file/files, right? How this should be done in angular2-seed?

**Comment by ludohenin** [comment]
@tandu manual typings are place under `tools/typings`. But in your case (IMO), interfaces can stay in your code as type definitions are more intended for external libraries.

**Comment by tandu** [comment]
Ok, thank you. I will keep them in my files. But in case I add manual typings in `tools\typings` then they will be accessible in application immediately? Or I will need to add `/// <reference path="../../tools/typings/my_custom.d.ts" />` in classes where I'm going to use them?

**Comment by ludohenin** [comment]
yes they should be immediately available.
