### ISSUE TITLE
npm test gives "Error during instantiation of NgZone!"

### ISSUE THREAD

**Issue by larsthorup** [mgechev/angular2-seed#242]
A fresh install of angular2-seed with

    npm install
    npm test

Gives

    Home component
        x should work
    Error: EXCEPTION: Error during instantiation of NgZone! (DynamicComponentLoader -> Compiler -> RuntimeCompiler -> ProtoViewFactory -> Renderer -> DomRenderer -> EventManager -> NgZone).
    ORIGINAL EXCEPTION: TypeError: Subject is not a function

**Comment by larsthorup** [comment]
I believe the issue is with the latest rxjs-5.0.0-alpha.10... and .8 seems to work. Just locking down the version seems not the right approach to me though. Anyone have an idea what the root cause of this issue may be?

**Comment by butterfieldcons** [comment]
Just a note - Alpha.44 Angular2 build works up to rxjs-5.0.0-alpha.10.  Test performed on Windows 7.

**Comment by mgechev** [comment]
https://github.com/mgechev/angular2-seed/commit/f0e7ed97269a22fc1951c5e33ff00a249a16c1f3 fixes the issue

**Comment by butterfieldcons** [comment]
confirmed and thank you mgechev

**Comment by larsthorup** [comment]
Works. Thanks :)
