### ISSUE TITLE
Only @Component, no @View?

### ISSUE THREAD

**Issue by bertvh** [mgechev/angular2-seed#246]
Just a quick question. In the components, you use @Component without an @View annotation. This works but I don't get why.

In the angular2 docs and about any other tutorial, they say "Each Angular component requires a single @Component and at least one @View annotation".

Is this something new / undocumented?

**Comment by ludohenin** [comment]
`@View` is optional since few release. Not sure whether it'll be dropped or not.
We've decided not to use it so we basically either have `components` or `directives`.

**Comment by bertvh** [comment]
Thanks!
