### ISSUE TITLE
Importing Rx?

### ISSUE THREAD

**Issue by bertvh** [mgechev/angular2-seed#249]
I'm trying to use Observables. In order to do to, I have added this import (same path as angular is using internally):

```import {Observable} from '@reactivex/rxjs/dist/cjs/rx';```

and I have added the rx lib to the js dependecies as follows:

```
jslib_copy_only: [
   resolve('@reactivex/rxjs/dist/cjs/Rx')
]
```

Is this the right wat to do this (I'm on angular2 alpha 44)? 

The Rx.js is now available in the dist/lib folder but Require/SystemJs is trying to load it from the root and tries to go into subfolders (which seems right). How can I preserve the path when copying? Am I doing this right?

Edited: fixed the copy-lib

**Comment by ludohenin** [comment]
@bertvh If you want to preserve the path in the dist/lib folder you have to reference `@reactivex` only (this will copy the entire module), if you just wanna copy cjs/Rx, then it's fine how you did it, but you'll have to set the path in system config (ie `paths: { '@reactivex/rxjs/dist/cjs/Rx' : 'lib/Rx.js'`}

**Comment by bertvh** [comment]
Ok, thanks. I finally fixed it. There were several problems with my node_modules. Apparently I can use Rx without even copying the file. Is Rx included in angular completely?

PS. If this is not the forum for such questions, let me know ;)

**Comment by NathanWalker** [comment]
I have also run into this frustration trying to add extra libs. We should add a pointer about the system config `paths: { ... }` necessity as I believe that will be a common case for anyone using this seed.

**Comment by ludohenin** [comment]
yeah, got similar question on gitter. I think it the config itself that needs to be improve.
Hope to come soon with something.

**Comment by bertvh** [comment]
+1 on improving the readme ;). If I have the time, I'll fork and make a suggestion.
