### ISSUE TITLE
npm run tsd.... will not pass params correctly to tsd

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#251]
I tried to install typings file in a private repos based on this project, where I ran into an odd situation

```bash
$ npm run tsd install sugar --save

> xxx@0.0.0 tsd /Users/jesper/src/angular2-seed
> tsd "install" "sugar"

 - sugar / sugar    

>> running install..
>> written 1 file:

    - sugar/sugar.d.ts
```

Now, while this installed the sugar/sugar.d.ts (in the ignored typings folder), it FAILED TO UPDATE `tsd.json`.

I would expect a dirty `tsd.json` file:

```bash
$ git status

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

### Workaround:
You can install tsd globally, and it works:

```bash
$ tsd install sugar --save

 - sugar / sugar    

>> running install..

>> written 1 file:

    - sugar/sugar.d.ts

```

now the `tsd.json` is updated correctly:

```
$ git status

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   tsd.json
no changes added to commit (use "git add" and/or "git commit -a")
```
 
### The error
is probably that `npm run tsd` will not correctly pass params to tsd command. Instead, `--save` is probably eaten by npm. Question is how we can solve this?

For reference to tsd/typings workflow, see also issues #200, #201, #232

**Comment by ludohenin** [comment]
you have to run `npm run tsd -- install sugar --save`. `--` indicates the end of npm args and passes what's after to the called script (that's in npm docs)

**Comment by jesperronn** [comment]
Awesome! An easy-to-overlook detail! Thanks
