### ISSUE TITLE
Using an existing backend server during development

### ISSUE THREAD

**Issue by skribling** [mgechev/angular2-seed#253]
hi,

I'm trying to include an existing backend server into the devlopment cycle so I can use the rest services from this server in my angular2 app.
My initial approach was to reroute all non matched requests inside https://github.com/mgechev/angular2-seed/blob/master/tools/utils/server.ts to my backend server, but I'm running into many problems.
Is there a recommended way or best practice for angular2-seed to include an existing backend server into the development cycle?

**Comment by ludohenin** [comment]
Maybe the best is to have a process to serve the app and another for the API end point. If they run on the same machine, then use a different port for each.
