### ISSUE TITLE
Handle external dependencies (RFC)

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#255]
Currently it is quite painful to use external libraries in the project especially ones with a lots of dependencies. We need to list all the individual files, including their direct and indirect dependencies in the build system. This occurs because `node_modules` is not visible by the development server.

My suggestion is to make slight changes in the project's build configuration:

* [ ] - Change the root of the development static server to the root of the project itself. This way the `node_modules` folder will be accessible.
* [ ] - Change add system.js configuration file:

```javascript
System.config({
  defaultJSExtensions: true,
  paths: {
    '*': '/node_modules/*',
  }
});
```

As drawback I see that we'll slightly violate the encapsulation of the dev environment since the static file server will have access to all the files (including the build) of the project.

Sample semi-working implementation with a lot of hardcoded values could be found at https://github.com/mgechev/angular2-seed/tree/external-libs.

// cc @ludohenin @NathanWalker @tarlepp @briantopping

**Comment by briantopping** [comment]
I'm not a fan of the source being at the top level because (for one) it becomes more difficult to clean a build manually from the command line. 

Do you see the "drawback" related to the first, second or both options?  It doesn't seem to be a problem in the second one. 

Another option that I have done is have dev builds remap the location of `node_modules` virtually when being locally served and when a production build is generated, actually copy the folder to the layout you describe.

**Comment by ludohenin** [comment]
:+1: 
@briantopping in what @mgechev proposes, the app is still built into `dist/${ENV}`
@mgechev we can prevent server access to any resources but dist folder and node_modules

**Comment by ludohenin** [comment]
Another drawback is that asset urls will need to be prepended with `./<%= APP_DEST %>/path/to/my/asset/file`. Is that acceptable ? (for me it is - needs to be documented tho)

**Comment by ludohenin** [comment]
Fully working example :) https://github.com/mgechev/angular2-seed/commit/389263146ad91fc001fac5ade7313b8fce725126

**Comment by briantopping** [comment]
I certainly want to be careful with my statements, one can never object to a situation they can't or won't put to code! :) So I'm not taking my comments too seriously here, just trying to share experience.

**Comment by mgechev** [comment]
@ludohenin I merged your branch with `external-libs` and did a couple of changes. I prefer to use `APP_BASE_HREF` (when it gets stable) instead of prefixing the uris of all resources inside of the CSS files.

I think from usability point of view it'll be better; in case user of the seed forget to use the template string and instead add `/dist/dev`, her or his production build will have invalid links.

**Comment by ludohenin** [comment]
@mgechev can we merge `external-libs` ? That should fix #258 & #261

**Comment by ludohenin** [comment]
btw, livereload is broken in `external-libs` and not sure why.

**Comment by mgechev** [comment]
Yes, I guess we need to use different `LocationStrategy`. I'll fix it today.

**Comment by mgechev** [comment]
Landed in master.
