### ISSUE TITLE
How to properly add Ionic2@alpha to angular2-seed project

### ISSUE THREAD

**Issue by jksoftpro** [mgechev/angular2-seed#257]
Hi, I'd like to add Ionic2 support on top of angular2-seed project. I removed angular2 dependecy and added Ionic2 alpha bundled with angular2:

```javascript
  "dependencies": {
    "bootstrap": "^3.3.5",
    "es6-module-loader": "^0.17.8",
    "es6-shim": "^0.33.6",
    "ionic-framework": "^2.0.0-alpha.35",
    "systemjs": "^0.19.4"
  }
```
Then I added new typescript code importing ionic2:
```
import {App, IonicApp, Platform} from "ionic/ionic";
....
// the rest of Ionic/Angular code
```
Unfortunately "ionic/ionic" is highlighted red and warning in console and VS Code says:
```
app/app/app.ts(1,39): error TS2307: Cannot find module 'ionic/ionic'.
```
All angular2 imports you configured guys work great! What I am missing here to set up Ionic properly? Any hints will be greatly appreciated? Thanks!

**Comment by ludohenin** [comment]
If the package is distributed with type definition files it should work (you can try `npm run tsd -- --link`), otherwise you have to use tsd (if it exist) otherwise you have to make the .d.ts file yourself.

**Comment by jksoftpro** [comment]
Thanks for the hint. I am going to generate Ionic typings from TypeScript  using gulp plugin. I will let you know if it worked for me.

Can you please point me out to Angular2 typings in this project and how it is configured. Unfortunately I can't see that. All I can see is:

/// <reference path="async/async.d.ts" />
/// <reference path="del/del.d.ts" />
/// <reference path="express/express.d.ts" />
/// <reference path="glob/glob.d.ts" />
/// <reference path="gulp-shell/gulp-shell.d.ts" />
/// <reference path="gulp/gulp.d.ts" />
/// <reference path="mime/mime.d.ts" />
/// <reference path="minimatch/minimatch.d.ts" />
/// <reference path="node/node.d.ts" />
/// <reference path="orchestrator/orchestrator.d.ts" />
/// <reference path="q/Q.d.ts" />
/// <reference path="serve-static/serve-static.d.ts" />
/// <reference path="systemjs/systemjs.d.ts" />

**Comment by ludohenin** [comment]
@jksoftpro ng2 is distributed with its own typings, so no configuration is required. Look at `node_modules/angular2`, you'll see that every file has its `.d.ts` counterpart ... ts compiler knows about it.
