### ISSUE TITLE
Project breaks in chrome after clearing the cache.

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#258]
If you clear cache or refresh page with ctrl+shift+R or cmr+shift+R it breaks with this error:

`Error: XHR error (404 Not Found) loading http://<remote_server>/angular2/angular2.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"`

Error is triggered when run application from remote server, locally everything is fine. I have faced with this issue when updated to the latest version yesterday. I think the bug is somewhere in the latest commits.

**Comment by ludohenin** [comment]
@tandu are you loading your app from a remote server (not on your local machine) ?

**Comment by ludohenin** [comment]
// ref: #255

**Comment by tandu** [comment]
@ludohenin yes, I'm loading it from the remote machine. I agree, it  is most likely race condition. When angular2.dev.js is cached it is loaded first and everything is fine. Before it was working well what has changed in the latest commits?

**Comment by tandu** [comment]
When the update is planned? It actually breaks the same way in all browsers.

**Comment by mgechev** [comment]
I can't manage to reproduce it. I use chrome devtools opened in incognito mode. Are you using the last version on master?

**Comment by tandu** [comment]
Can't reproduce it too on the latest version.
