### ISSUE TITLE
scss linter

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#260]
Basically we need a simple task to check ```scss``` files syntax. There is solutions for this already:

https://www.npmjs.com/package/gulp-scss-lint
https://www.npmjs.com/package/gulp-scss-lint-stylish2

Although this task is not in the main "core" of this project, but I don't see any harm adding this one.

**Comment by mgechev** [comment]
Lets let the users of the seed extend it they way they want and keep the seed out of scss linting for now.
