### ISSUE TITLE
Not working after install

### ISSUE THREAD

**Issue by rodzzlessa24** [mgechev/angular2-seed#261]
Im cloning the latest repo and the index page only shows `loading...`. I'm not getting any errors on `npm install` or `start`. I do get this error on the console:

``` bash
(program):1 Uncaught SyntaxError: Unexpected token <
system.src.js:1379 Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:5555/angular2/angular2.js
localhost/:29 Uncaught Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:5555/angular2/angular2.js
	Evaluating http://localhost:5555/bootstrap.js
	Error loading http://localhost:5555/bootstrap.js Report this error at https://github.com/mgechev/angular2-seed/issues
```

**Comment by z-bit** [comment]
Same here: on Windows 7, Windows 8 and Ubuntu.

**Comment by ludohenin** [comment]
same as #258

**Comment by koodikindral** [comment]
Looks like there's some kind of race condition, because the error occurs on every ~2nd reload:

    Uncaught SyntaxError: Unexpected token <
    Uncaught Uncaught SyntaxError: Unexpected token <
        Evaluating http://domain.tld:3000/angular2/angular2.js
    Uncaught Uncaught SyntaxError: Unexpected token <
        Evaluating http://domain.tld:3000/angular2/angular2.js
        Evaluating http://domain.tld:3000/bootstrap.js
        Error loading http://domain.tld:3000/bootstrap.js Report this error at https://github.com/mgechev/angular2-seed/issues

**Comment by mgechev** [comment]
@koodikindral thanks for the extra information! Since this is a duplicate lets close it and see whether #258 will be fixed by merging the `external-libs` branch.
