### ISSUE TITLE
route-link with PathLocationStrategy puts "null/dist/dev/about" in href

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#264]
When change location strategy to `PathLocationStrategy` in d72e5b6f460d95f95092110d23af948b6ef44376 `route-link` puts links like `null/dist/dev/about` to href. If you click the link it navigates to `localhost:5555/about` and shows the about page correctly. When you refresh browser with that page you get `Cannot GET /about` error.

**Comment by ludohenin** [comment]
This is a ng2 bug that should be fixed in beta.00 release. See https://github.com/angular/angular/issues/5028
