### ISSUE TITLE
How properly add css from /assets folder to index.html?

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#268]
I have put `main.css` into `/assets' folder`. How properly add it to `index.html`?

I have tried adding it in `config.ts`:

`{ src: 'assets/main.css', dest: CSS_DEST, inject: true }`

and tried linking it directly from `index.html`:

`<link rel="stylesheet" type="text/css" href="/assets/main.css"/>`

with no success. How this can be done?

**Comment by koodikindral** [comment]
Have you tried to add full path for assets source? Like '<your_path>/app/assets/', worked for me.

**Comment by tandu** [comment]
Yes, it works, missed that thing. The only issue is that as I understand the idea is to not touch index.html at all and setup its content from config.ts. Also that resourse will miss ?version=0.0.0 abbreviation that kills cache on version update thought it seems that now it is removed from all resources in index.html and is not a case.

**Comment by mgechev** [comment]
```js
{ src: 'assets/main.css', dest: CSS_DEST, inject: true }
```
will work now.

**Comment by tandu** [comment]
```typeScript
'angula2/angular2': `${LIB_DEST}/angular2.dev.js`
```
*angula2* is it mistype or intended?

**Comment by mgechev** [comment]
It is my mistake. This line is actually not required.

**Comment by tandu** [comment]
When I added `{ src: 'assets/main.css', dest: CSS_DEST, inject: true }` I get this in terminal:
```
[20:24:25] 'copy.css' errored after 657 μs
[20:24:25] Error: Cannot find module 'assets/main.css'
```

**Comment by tandu** [comment]
`main.css` is in `/assets` folder.

**Comment by mgechev** [comment]
Fixed now. Take a look at `config.ts` there's an array called `APP_ASSETS`, which allow injecting such assets.

**Comment by tandu** [comment]
Great, it works now, thanks.
