### ISSUE TITLE
Source maps: where?

### ISSUE THREAD

**Issue by bertvh** [mgechev/angular2-seed#269]
My dist directory doesn't seem to contain any ts or map files. However, chrome is able to find something under /source/... I don't get where this comes from. These files aren't loaded from the network. Gulp just seems to start a server in the dist directory. Could you help me understand this?

**Comment by mgechev** [comment]
We use inline, in order to reduce the number of http requests.

**Comment by bertvh** [comment]
Oooh.. ok, I didn't notice this. Didn't even know this was possible. Thanks!
