### ISSUE TITLE
import d3 ts semantic error

### ISSUE THREAD

**Issue by lanocturne** [mgechev/angular2-seed#272]
Getting an error message like `: error TS2307: Cannot find module 'd3/d3'.`

I have npm and tsd installed d3. On my component file I import d3 by `import * as d3 from 'd3/d3';`

Notice at runtime the browser loads d3 successfully and it's rendering svg.

**Comment by ludohenin** [comment]
@lanocturne What you get is a compiler (tsc) error. You need to add the type definition using tsd if it exist, otherwise you'll have to draw something yourself.

**Comment by pragyandas** [comment]
@lanocturne Please ensure that you have d3.d.ts in the typings or use tsd to download one. If you don't wish to use a definition file for d3 you can use require('d3') instead of import. This error happens when compiler is not able to find a definition file.
