### ISSUE TITLE
Reference to the wrong location after build

### ISSUE THREAD

**Issue by Bigous** [mgechev/angular2-seed#273]
Hi all, nice work on this seed... it may be the best source code I've seen.

I realized that after build the application with gulp, the injected files are pointed to the original ones and not the lib or css copy directory.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My Angular2 App</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- inject:css -->
  <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.css">
  <link rel="stylesheet" href="/dist/dev/assets/main.css">
  <!-- endinject -->
</head>
<body>

  <app>Loading...</app>

  <!-- shims:js -->
  <script src="/node_modules/es6-shim/es6-shim.min.js"></script>
  <script src="/node_modules/reflect-metadata/Reflect.js"></script>
  <script src="/node_modules/systemjs/dist/system.src.js"></script>
  <!-- endinject -->

  <script>
    System.config({"defaultJSExtensions":true,"paths":{"*":"/node_modules/*"}})

    System.import('/dist/dev/bootstrap')
      .catch(function (e) {
        console.error(e,
          'Report this error at https://github.com/mgechev/angular2-seed/issues');
      });
  </script>

  <!-- libs:js -->
  <script src="/node_modules/angular2/bundles/angular2.dev.js"></script>
  <script src="/node_modules/angular2/bundles/router.dev.js"></script>
  <script src="/node_modules/angular2/bundles/http.dev.js"></script>
  <!-- endinject -->

  <!-- inject:js -->
  <!-- endinject -->

</body>
</html>
```

I think it should be:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My Angular2 App</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- inject:css -->
  <link rel="stylesheet" href="css/bootstrap.css">
  <link rel="stylesheet" href="assets/main.css">
  <!-- endinject -->
</head>
<body>

  <app>Loading...</app>

  <!-- shims:js -->
  <script src="lib/es6-shim.min.js"></script>
  <script src="lib/Reflect.js"></script>
  <script src="lib/system.src.js"></script>
  <!-- endinject -->

  <script>
    System.config({"defaultJSExtensions":true,"paths":{"*":"/node_modules/*"}})

    System.import('./bootstrap')
      .catch(function (e) {
        console.error(e,
          'Report this error at https://github.com/mgechev/angular2-seed/issues');
      });
  </script>

  <!-- libs:js -->
  <script src="lib/angular2.dev.js"></script>
  <script src="lib/router.dev.js"></script>
  <script src="lib/http.dev.js"></script>
  <!-- endinject -->

  <!-- inject:js -->
  <!-- endinject -->

</body>
</html>
```
Am I right?

**Comment by mgechev** [comment]
Yes, thanks for pointing this out! You're correct, we are not setting the correct path here after we copy the libraries.

On the other hand, I don't see a reason why we need to copy them in case we provide the modules directly from `node_modules`. Lets keep the issue open, in a few days I'll fix the incorrect behavior.

**Comment by Bigous** [comment]
True!
I like more the approach of copying everything that is used to the new directory and serve from that directory (dist/dev) for example, and do not expose the node_modules...
Just because I feel more comfortable, not a practical reason for development environment.

I think when you provide the production build it will follow this to deploy only what is needed, right?

**Comment by e-oz** [comment]
@mgechev please copy files, because not all users can run build scripts on the server (on deploy), and without it they will not have node_modules on the server. And pushing all modules to git index would not the best idea.

**Comment by mgechev** [comment]
@e-oz for production build we'll provide a single bundle by default which includes the application and all libraries. I don't think it makes sense to copy the files for dev.

**Comment by e-oz** [comment]
@mgechev then I'll have to stay on alpha46 release until you release version with prod build :) But it's ok, I like that version:)

**Comment by mgechev** [comment]
This issue is fixed here https://github.com/mgechev/angular2-seed/tree/refactoring.
Once the branch gets merge to master we can close this issue.
