### ISSUE TITLE
build.js.dev is freezing up on the following code...

### ISSUE THREAD

**Issue by meenie** [mgechev/angular2-seed#274]
Whenever I do `npm start`, the build process freezes up on the `build.js.dev` task when running the following code:

```typescript
this.loadUsers
      .switchMap(() => this.http.get('http://little-pond-7454.getsandbox.com/users'))
      .map(res => res.json())
      .map(payload => ({type: POPULATE_USERS, payload}))
      .subscribe(this._dispatcher);
```

It's specifically the second line of the code above.  Not sure if it's trying to parse the url somehow?

**Comment by mgechev** [comment]
I tried the same code but I can't manage to reproduce it. Would you provide link to the repository which contains the code that leads to the issue?

**Comment by meenie** [comment]
Sorry it took so long, was out with the family.  Here's my branch: https://github.com/meenie/angular2-seed/tree/broken

**Comment by meenie** [comment]
Forgot to mention that you can go to https://getsandbox.com/ and select "Blank".  No need to sign up.  It will give you a URL to use for an hour.

**Comment by meenie** [comment]
@mgechev: Were you able to reproduce with my branch?

**Comment by mgechev** [comment]
There was the following compile-time error:
```
app/services/users.ts(44,23): error TS2339: Property 'json' does not exist on type '{}'.
```
You can fix it by:

```ts
import {Http, Response} from 'angular2/http';

...

this.loadUsers
  .switchMap(() => this.http.get('http://little-pond-7454.getsandbox.com/users'))
  .map((res: Response) => res.json())
        ^^^^^^^^^^^^^
  .map(payload => ({type: POPULATE_USERS, payload}))
  .subscribe(this._dispatcher);
```

**Comment by meenie** [comment]
Ya, I did see that error.  And yes, the above fix does work for that.  But I'm still getting the hangup on the task `build.js.dev`.  This is what my output is:

```
λ meenie [~/dev-files/angular2-seed] at broken !
→ npm start                                                                                 [ae299c4]

> angular2-seed@0.0.0 start /Users/meenie/dev-files/angular2-seed
> gulp serve --env dev

[00:17:40] Requiring external module ts-node/register
[00:17:44] Using gulpfile ~/dev-files/angular2-seed/gulpfile.ts
[00:17:44] Starting 'serve'...
[00:17:44] Starting 'build.dev'...
[00:17:44] Starting 'clean.dist'...
[00:17:44] Finished 'clean.dist' after 13 ms
[00:17:44] Starting 'tslint'...
[00:17:45] Finished 'tslint' after 985 ms
[00:17:45] Starting 'copy.lib'...
[00:17:45] Starting 'copy.css'...
[00:17:45] Starting 'copy.fonts'...
[00:17:45] Finished 'copy.css' after 16 ms
[00:17:45] Finished 'copy.fonts' after 23 ms
[00:17:45] Finished 'copy.lib' after 30 ms
[00:17:45] Starting 'build.deps'...
[00:17:45] Finished 'build.deps' after 2.98 μs
[00:17:45] Starting 'build.sass.dev'...
[00:17:45] Finished 'build.sass.dev' after 67 ms
[00:17:45] Starting 'build.assets'...
[00:17:45] Finished 'build.assets' after 2.72 ms
[00:17:45] Starting 'build.images.dev'...
[00:17:45] Finished 'build.images.dev' after 4.06 ms
[00:17:45] Starting 'build.js.dev'...
```

And then it just sits there.  If I leave it for around 30 seconds, my laptop fan kicks in (2015 macbook pro) and the CPU starts to heat up in a big way.

**Comment by mgechev** [comment]
I see other issues in this branch but I can't manage to reproduce the freezing up error.

Lets reopen the issue and keep it that way for a few more days in case someone else have the same problem.

**Comment by meenie** [comment]
I'll create a fresh branch off master, with as minimal change as possible to recreate it on my side.

**Comment by meenie** [comment]
Another clue to this puzzle is that when running `npm start`, Gulp shoots up to `99.9` on the Activity Monitor.

**Comment by meenie** [comment]
@mgechev: Here's another branch that changes less code around https://github.com/meenie/angular2-seed/tree/gulp-locking-up

If I replace lines 44/45 of `app/services/name_list.ts` with:
```typescript
  .flatMap(() => new BehaviorSubject(['hi', 'there']).throttle(100))
```
all of the code works fine.

**Comment by meenie** [comment]
I also want to point out that if I just put in the line:
```
this.http.get(this._url).map((res: Response) => res.json()).subscribe(data => console.log(data));
```
That it works fine.  It's only when that `http.get()` is inside of the `flatMap()` callback ><

**Comment by meenie** [comment]
Okay, made a bit of a breakthrough.  If I replace the `flatMap()` line with this, it works:
```javascript
  .flatMap(function() {
    return this.http.get(this._url)
  }.bind(this))
```
So it's something to do with using the fat arrow function

**Comment by meenie** [comment]
I decided to delete my `node_modules` folder and start fresh and now it works fine with the original syntax ><.  I'm going to close this off for now.  Thanks for your time.

**Comment by mgechev** [comment]
No problem! Thanks for digging into the issue! So I guess the problem was in old version of `tsc`?
