### ISSUE TITLE
http proxy for express

### ISSUE THREAD

**Issue by pmackowski** [mgechev/angular2-seed#276]
Have you considered adding support for http proxy? It would be a very helpful feature.

tools/utils/server.ts file:
```
export function serveSPA() {
  ...  

  //  currently express-http-proxy is not  DefinitelyTyped
  var proxy = require('express-http-proxy');  

  server.use('/api/*', proxy('localhost:4567', {
      decorateRequest: function(req) {
        req.path = req.path + req.params['0'];
        return req;
      },
      forwardPath: function(req, res) {
        return require('url').parse(req.url).path;
      }
    })
  );
}
```

For the above code, /api/somePath will be translated to localhost:4567/somePath

**Comment by mgechev** [comment]
Hey @pmackowski thanks for the suggestion! This is out of the scope of the seed project. We provide only the front-end of your application, express is included only for development purposes.
