### ISSUE TITLE
App directory structure

### ISSUE THREAD

**Issue by un33k** [mgechev/angular2-seed#28]
Which one do you think is better. Grouping things by type or by feature.  Here we have all components together and all services together as well. Do you think it would be better to pack them by features?

**Comment by ludohenin** [comment]
@un33k Angular 2 is really about components, and you may have app level services as well as components level ones. I think is it's fine like that.

**Comment by mgechev** [comment]
@un33k I think soon Google should announce official guidelines. Until then, I think what is suggested in [most](https://github.com/mgechev/angularjs-style-guide#directory-structure) style [guides](https://github.com/johnpapa/angular-styleguide) is still valid.
