### ISSUE TITLE
Way to go back to PathLocationStrategy?

### ISSUE THREAD

**Issue by DennisRoam** [mgechev/angular2-seed#283]
I was on an older version of this seed and recently upgraded to fix a small typing issue and it blew everything up because of the switch to the hash strategy. 

I'd like to keep current but I have links like `<img src="/images/whatever.jpg">` or build dynamic links like that and it doesn't work at all anymore. 

There wasn't anything on the home page about the switch nor any info on how to migrate.. It's not just the strategy, the server was changed too and it's been a pain to go through everything. 

Is there a way to switch it back or in the future let people decide?

**Comment by mgechev** [comment]
For your image you can use relative paths instead of absolute: `<img src="./images/whatever.jpg"/>`.
