### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by episodeyang** [mgechev/angular2-seed#285]
```Error
projects/angular2-seed/tools/utils/tasks-tools.ts:32
    readdirSync(path).forEach(function(file) {
TypeError: undefined is not a function
```

did `npm install` under project root. I'm using node 0.12.7 somehow.

**Comment by episodeyang** [comment]
yet when I do this it is totally fine:

https://www.dropbox.com/s/pn769u1x66xevsq/Screenshot%202015-12-09%2019.41.06.png?raw=0

**Comment by episodeyang** [comment]
okay I think I'm missing es6

**Comment by mgechev** [comment]
Yes, you need node version >= 4 and npm >= 3.
