### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#288]
The npm dependencies are [out-of-date](https://david-dm.org/mgechev/angular2-seed#info=devDependencies).

**NOTE**: Currently we are blocked from using the latest version of TypeScript by https://github.com/sebastian-lenz/typedoc/issues/162.

**Comment by Bigous** [comment]
Just for documentation - [here is the repository](https://github.com/AngularShowcase/angular2-sample-app).
