### ISSUE TITLE
Prod build broken

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#292]
HTML minifyer normalize attribute to lower case. This leads to compiler errors when using for instance `routerLink` => 'routerlink'

We can comment task `build.html_css.prod` before we find a solution.

see https://github.com/angular/angular/issues/5789

**Comment by mgechev** [comment]
I bet this is going to be a common problem, just wondering whether it will make the core team revert pack to snake-case.

Lets comment it for now.

**Comment by mgechev** [comment]
The issue is fixed so we can close it. We will have to use the offline template compiler that Igor mentioned in the issue you opened.
