### ISSUE TITLE
where is setting "argv"; 

### ISSUE THREAD

**Issue by rdlabo** [mgechev/angular2-seed#295]
thanks development.

I want to change ENV in tools/config.ts. ENV is set argv['env'] ( argv is import {argv} from 'yargs'; ). 
but I can't look for yargs. 

AND I  change manualy.
|| export const ENV                  = argv['env']         || 'dev';
|| ↓
|| export const ENV                  = 'product';
It not working.

I want to where is setting "argv".

regards.

**Comment by mgechev** [comment]
You can use:

```
$ gulp serve --env prod
```

or for your case:

```
$ gulp serve --env product
```
