### ISSUE TITLE
npm v3 required... does it need to?

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#297]
For those that contribute to https://github.com/angular/angular , it's required that npm must be < 3.

Working with this library requires at least 3. To go back/forth is painful.
It sounds like angular team may update their repo to use Node 5/npm 3 by end of month (https://github.com/angular/angular/issues/3193), but in the event they don't, was thinking maybe we could not require npm 3 to ease this. Just something I've run into in past month that is close to forcing me to use another seed in meantime.

**Comment by ludohenin** [comment]
Have you tried the seed with npm < 3 ?
At some point we needed to rely on npm 3 flat installation, I'm not quite sure this is still valid.

**Comment by NathanWalker** [comment]
It does seem to break when used with < 3, can't recall exact error as I'm
on phone at moment but when I get chance to try again I'll report back.

**Comment by NathanWalker** [comment]
Thanks!
