### ISSUE TITLE
namespace extravaganza

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#298]
mama mia, can we get some cooperation around here...

https://github.com/angular/angular2-seed
https://github.com/ghpabs/angular2-seed
https://github.com/mgechev/angular2-seed

Minko, you were first, just sayin'.

**Comment by ludohenin** [comment]
That would obviously be nice. Have to be sure these projects aim to the same thing tho.
I like the hero app :)

**Comment by mgechev** [comment]
https://github.com/angular/angular2-seed seems closer to https://github.com/AngularClass/angular2-webpack-starter because it is webpack based.

I saw https://github.com/ghpabs/angular2-seed a day [ago](https://github.com/AngularClass/angular2-webpack-starter/pull/149). It seems quite close to what we have here. As main difference I can point out the lack of static typing in the build.

**Comment by NathanWalker** [comment]
Doesn't really matter but was surprised to see it. My preference would be that others not use names that already exist out there, but unfortunately doesn't sound like anyone else will rename:
https://github.com/ghpabs/angular2-seed/issues/31

Some live in the clouds and just don't see practical issues.

**Comment by gdi2290** [comment]
I'm changing the direction of `angular2-webpack-starter` so it's not too similar to angular2-seed. I also started including some of my findings from my repo to merge into angular's official seed repo

**Comment by NathanWalker** [comment]
@gdi2290 a **true** professional :+1:

**Comment by mgechev** [comment]
@gdi2290 sounds great! Looking forward for your collaboration with @robwormald!

**Comment by robwormald** [comment]
@mgechev totally sorry about the name, for real :sob: i'd certainly consider changing it if its a major issue, blame @igorminar.

**Comment by NathanWalker** [comment]
lol. sry to have potentially started something here. It may seem rather silly in scheme of things, but...

`May` be worth taking a moment and think about an incoming audience of new developers to angular or those angular1 devs looking for seeds to start an upgrade from and seeing 3,4,5, however many of same named seeds. Not to mention learning new ground with angular2, then to be faced with sorting through a myriad of great seeds, but to become frustrated sorting apples from oranges.

In the end, I won't :sob: about it, but others down the road might.

**Comment by NathanWalker** [comment]
https://github.com/ghpabs/angular2-seed/issues/31

**Comment by robwormald** [comment]
i'll ask igor about changing ours tomorrow, i'd probably get in trouble for unilaterally renaming a repo. no sweat. our end goal is basically to have the CLI be the blessed solution.

**Comment by robwormald** [comment]
https://github.com/angular/angular2-seed/issues/26

**Comment by NathanWalker** [comment]
+1 a **true** gentlemen @robwormald

**Comment by robwormald** [comment]
all that said. if y'all are gonna be the blessed seed project from the community, getting some Http and Router up in here would be useful. Also usage of the RxJS operators. That was a primary driver behind us firing one up. Discuss.

**Comment by NathanWalker** [comment]
Tru dat. There have been discussions about adding examples here going awhile back.
At moment, this was created:
https://github.com/AngularShowcase/

And an effort has been made to keep this seed slim, with examples aside in the showcase, however I personally have gone back/forth on that. https://github.com/AngularClass/angular2-webpack-starter used to have `examples` in the repo, but recently broke them out here: https://github.com/AngularClass/angular2-examples

### Examples in repo

**Pros**:
- You have a lot to go on straight out of the box.
- Less confusing as you don't have to figure out how to integrate example into the particular build setup as they would be made to work out of the box 

**Cons**:
- you have to keep them up to date

**Comment by mgechev** [comment]
Hey guys @robwormald, @ghpabs, I'm totally fine with the name collision as well. angular2-seed seems like the default naming choice for such a type of a project anyway. Uniqueness of the repositories names is not a requirement given the way the projects are going to be used by the community. I don't think it is worth it to spend time in renaming your repos if the name collision is the only concern.

Currently we're aiming to provide a stable statically typed production and dev gulp builds with the best dev experience possible (we're working on integration with the hot loader). @robwormald, it'd be awesome to discuss your suggestions! Does adding a simple example with the Http module which requests a static resource in the `app` directory seems like a good idea to you?

Together with @ludohenin tried to collaborate with @juliemr for her [ng2-test-seed](https://github.com/angular/ng2-test-seed) but the goals of both projects are quite different so the Angular 2 seed wasn't able to get in use. @robwormald we'd love to do the same with [angular2-seed](https://github.com/angular/angular2-seed) if you see a bigger intersection between both projects!

**Comment by NathanWalker** [comment]
^
Totally true, however to use, one must find and evaluate first. That was more my point here ;)

3 things on that:
1. when searching github and seeing tons of same name repos, one doesn't know right away if one is a fork of the other, etc (maybe that user is just contributing to the parent). It requires investigation that no-one has time for.
2. when cloning to evaluate in a single directory before making a decision about which one fits their needs, you get name collisions on checkout (unless you renamed on clone **which most novices don't do**), you end up with a directory like this:
```
angular2-seed
angular2-seed-1
angular2-seed-2
angular2-seed-3
```
3. Now upon simple cursory review, you can't remember what is what and where they came from.

:+1:   As stated, not a huge deal to me as I would rename upon evaluation, but others may find it a tad frustrating.

**Comment by NathanWalker** [comment]
moving examples discussion here: https://github.com/mgechev/angular2-seed/issues/308

**Comment by NathanWalker** [comment]
Not to keep beating a dead horse here, but this last piece of evidence is relevant.
When you receive a mobile notification, one must ask (is this for mgechev, ghpubs, angular, my brother's, my sister's angular2-seed? which one is it??)

You see what I mean :)

![img_3347](https://cloud.githubusercontent.com/assets/457187/11854684/628b05d2-a3fa-11e5-9b4b-248366770992.PNG)

**Comment by Bigous** [comment]
@NathanWalker true, but I think it's more a Github problem (they could easily avoid it sendind mgechev/angular-seed). I like the name - it describes exactly what is this repo... and it was the first one... so, I vote for not changing this one ;)

**Comment by ludohenin** [comment]
@Bigous +1
