### ISSUE TITLE
Deep linking for development - return 'index.html'

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#30]
Would it be possible to modify the gulpfile and make the `connect` npm module to return `index.html` for page requests? That way you could refresh the browser on route such as `/about'...

**Comment by ludohenin** [comment]
@NathanWalker Thanks for pointing this out. This is actually on the todo list and coming very soon.

**Comment by NathanWalker** [comment]
This is awesome thank you!

**Comment by Sushant1791** [comment]
Hello Ludohenin, 

Any updates on this so far? Because our application is able to take us to the desired route when we are running the application in the **dev** mode but on **prod**, it gives us the error of **404**.
