### ISSUE TITLE
Copying all build assets to dist folder

### ISSUE THREAD

**Issue by donskifarrell** [mgechev/angular2-seed#300]
Hi,

I've just updated to the latest version of this seed project (thanks btw - it's great) but have noticed that the  gulp build is no longer copying all the files to the dist folder (e.g fonts, 3rd party libs). It is serving them up on localhost correctly so that part is fine.

Is there a way to turn this behaviour back on? Reason being is that it was quite easy to copy the dist folder to my dev server with just the necessary files to run my app.

**Comment by mgechev** [comment]
At the moment this behavior is enabled only for the production build. We can enable it for dev as well, it should not slowdown the build significantly.

// cc @ludohenin @NathanWalker

**Comment by donskifarrell** [comment]
Thanks, that would be great!

Noticed the Prod build but haven't been able to enable it when passing the env arg: 

```
npm start --env 'prod' 
```
is that correct?

**Comment by ludohenin** [comment]
The easiest way I see would be re-introduce `build.asset` task that was basically just copying asset folder. Add it to gulpfile/build.dev sequence. I don't think it requires to be added (back) tot the seed.

**Comment by ludohenin** [comment]
@donskifarrell you should try `npm start --- --env prod`

**Comment by mgechev** [comment]
The hot loader will require to copy the assets as well (at least the templates and the css files). The current strategy of inlining the templates will confuse the loader since it can't associate the individual changed templates to their corresponding components.

**Comment by donskifarrell** [comment]
@ludohenin unfortunately not working. The log shows the gulp command:

```
gulp serve --env dev "--env" "prod"
```

when I run your command. Also, dist folder/localhost is now serving from 

```
http://localhost:5555/dist/dev,prod/
```

Will get build.asset added to the gulp pipeline in the meantime.

**Comment by mgechev** [comment]
You can use `$ gulp serve --env prod`.

I keep getting System is not defined. // cc @ludohenin

**Comment by ludohenin** [comment]
Production server isn't supported right now.

**Comment by mgechev** [comment]
This change is in the [hot-loader branch](https://github.com/mgechev/angular2-seed/tree/hot-loader), I think we can close this issue.

**Comment by simonh1000** [comment]
+1 for the original poster. I have a .json file in /app/assets that is no longer being copies over to /dist. Worse, /dist is being rewritten all the time so I can't remedy the situation manually. Not sure what to do based on the thread above

**Comment by mgechev** [comment]
Once we merge the hot-loader branch this feature will be available.
