### ISSUE TITLE
Wrong url to assets in production

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#302]
The generated url `http://localhost:3000/app/components/menu_cmp/assets/home.jpg` can't load image and when I remove app `http://localhost:3000/components/menu_cmp/assets/home.jpg` image is loaded correctly.

**Comment by mgechev** [comment]
Yes, you should not include "app" in your path.

**Comment by tandu** [comment]
The problem is that in dev mode css should be
`background-image: url(/app/components/root_menu/assets/Icons_Menu_New_OFF.svg);`
In prod it is broken and should be
`background-image: url(/components/root_menu/assets/Icons_Menu_New_OFF.svg);`
instead. But at the same time that second url doesn't work in dev.

**Comment by mgechev** [comment]
You can use relative path instead of absolute one:

```
background-image: url(./components/root_menu/assets/Icons_Menu_New_OFF.svg);
```

**Comment by tandu** [comment]
relative path `./components...` doesn't work.

**Comment by tandu** [comment]
Hm, it works in local server 5555, but doesn't work from my nodejs server.
