### ISSUE TITLE
RxJS operator issue with beta in prod build

### ISSUE THREAD

**Issue by e-oz** [mgechev/angular2-seed#304]
After `npm run build.prod` I'm getting 404 on /rxjs/Subject.js. I use rxjs this way: `import 'rxjs/Rx';`

**Comment by e-oz** [comment]
with alpha53 all was fine..

**Comment by mgechev** [comment]
I found the cause of the issue. In minutes I'll push a fix.

**Comment by e-oz** [comment]
@mgechev thank you!
