### ISSUE TITLE
Why don't use webpack?

### ISSUE THREAD

**Issue by leshin** [mgechev/angular2-seed#305]

**Comment by mgechev** [comment]
This is how we decided to approach to the problem initially. For a webpack starter take a look at:
* [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter)
* [angular2-seed](https://github.com/angular/angular2-seed)

**Comment by dancancro** [comment]
For anyone searching this project's issues for "webpack" I wanted to add a couple more suggestions.

[Angular-CLI](https://github.com/angular/angular-cli) switched from System.js to Webpack. Initially, it limited access to Webpack configurations which upset a lot of people but [they opened that up too](https://www.reddit.com/r/Angular2/comments/5uszhz/angularcli_supports_webpackconfigjs/?ref=share&ref_source=link). Power to the people! :)

[Here](https://github.com/dancancro/great-big-angular2-example#demonstrations-and-features) is an Angular-CLI project of mine and a comparison to some others. It uses Webpack.

Also, [here](https://www.reddit.com/r/Angular2/comments/5rj14a/helpful_angular_2_github_repos_curated_through/) is a nice collection of Angular 2 project starters that lists the build tools.

@mgechev have you had any new thoughts about Webpack lately?
