### ISSUE TITLE
underscore

### ISSUE THREAD

**Issue by nglazov** [mgechev/angular2-seed#307]
I catch building error when i trying to use underscore package.

I've add to package.json underscore 1.8.2 dependency and have import to my component:
```javascript
import * as _ from 'underscore/underscore';
``` 
On build i catch:
```
error TS2307: Cannot find module 'underscore/underscore'.
```
Despite this my app work ok.
Is it problem of underscore default package or this seed-project?

**Comment by mgechev** [comment]
Most likely you're lacking the type definition of underscore.

You can install it via: `tsd install underscore --save` and later reference it within `./app`.
