### ISSUE TITLE
rxjs - Error on fetch for rxjs at ...

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#309]
I'm getting this on latest when trying to use rxjs:
```
Unhandled rejection Error on fetch for rxjs at file:///Users/nathanbackup/Documents/github_projects/NathanWalker/ng2-image-lazy-load/tmp/rxjs.js
	Loading bootstrap
	Loading components/app/app
	Error: ENOENT: no such file or directory, open '/Users/nathanbackup/Documents/github_projects/NathanWalker/ng2-image-lazy-load/tmp/rxjs.js'
```

**Comment by NathanWalker** [comment]
![screen shot 2015-12-16 at 2 28 54 pm](https://cloud.githubusercontent.com/assets/457187/11855824/62503716-a401-11e5-8f71-6befbba76007.png)

**Comment by NathanWalker** [comment]
Nvm, was able to solve it. There was one incorrect `import`!

**Comment by ludohenin** [comment]
rx path's probably missing in your System config.
https://github.com/mgechev/angular2-seed/blob/master/tools/config.ts#L45
