### ISSUE TITLE
Injecting js does not work in Windows

### ISSUE THREAD

**Issue by stefanocke** [mgechev/angular2-seed#310]
Node: v4.2.3
npm: 2.14.7
OS: Windows 7

Injection of dependencies into index.html does not work in Windows. 
I noticed that when running "gulp build.prod -- env prod". No JavaScript was injected at all.
For development build, it works, but this seems to be "by accident".

For me, it worked after the following changes to build.index.ts:

import {join, **sep**} from 'path';

...
function mapPath(dep) {
    console.log('inject dep: ' + dep);
    let prodPath = '${dep.dest}/${dep.src.split(**sep**).pop()}';
....

**Comment by mgechev** [comment]
@stefanocke thanks for pointing this out! Would you open a PR with the change?

**Comment by jzanko** [comment]
Hey, I just had the same issue on Windows. I think that there is also no need to concat DEPENDENCIES and APP_ASSETS in build.index.ts as the DEPENDENCIES are already build out of NPM_DEPENDENCIES and APP_ASSETS.

**Comment by stefanocke** [comment]
@mgechev  thanks a lot for the fix. Sorry I did not manage to create the PR so fast ;-)

**Comment by mgechev** [comment]
@stefanocke no worries, I'm glad the issue is fixed now :-)
