### ISSUE TITLE
Use sass for component styling 

### ISSUE THREAD

**Issue by lihaibh** [mgechev/angular2-seed#316]
We use css when we style a component today, is there any way that on our develop environment we will link sass file on our component directive but when we compile it will link to the result css?

**Comment by mgechev** [comment]
We have already discussed this [here](https://github.com/mgechev/angular2-seed/issues/85). Although sass is popular it is not the default choice when styling components. It is quite possible the developers using the seed to choose less or anything else instead. In the same time we're trying to keep the seed as minimalistic as possible (although it scope grew a little last a couple of months).

Lets close this issue for now.
