### ISSUE TITLE
Build and start two projects using a higher level packages.json and gulpfile.ts

### ISSUE THREAD

**Issue by Alber70g** [mgechev/angular2-seed#317]
I really like the way this project is structured. Therefore I'd like to ask a question that is not explicitly the issue of this particular project, but more an question on how to deal with something.

I have the following structure:

```
├── frontend
│   ├── <contents of mgechev/angular2-seed>
├── backend
│   ├── <asp.net 5 application>
├── docs
```

Is it possible to create a `package.json` and `gulpfile.ts` in the root of this project to build both the frontend and the backend?
This could result in this structure:

```
├── frontend
│   ├── <contents of mgechev/angular2-seed>
├── backend
│   ├── <asp.net 5 application>
├── docs
├ tools 
│   ├── tasks
│   │   ├── build.ts
├ package.json
├ gulpfile.ts
```

Now the build would have `build.frontend`, `build.backend` and `build.all` and possibly `serve.all` where the frontend would start a `npm start` and the backend `dnx web`.

Is this even advisable, or is this a very bad way of letting projects depend on each other?

**Comment by tarlepp** [comment]
Personally I would use two different repositories to manage that case.

1) Repository for frontend (mgechev/angular2-seed)
2) Repository for backend (your asp.net 5 application)

With that structure you can totally separate those sides (front- and backend) from each other. And if you want to use just "one" repository you can always link n repositories to your "main" one.

**Comment by Alber70g** [comment]
But still, functionally, the two repos are very connected to each other. For the frontend there isn't gonna be another backend talking, and same way around. There might be in the future a new frontend in the form of an app, but that shouldn't be a problem to build and start both backend and frontend. 
It's more of a convenience to

**Comment by mgechev** [comment]
We can discuss this in gitter since it is not directly related to the project I propose to close it for now.
