### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by neridonk** [mgechev/angular2-seed#320]
This is more a  question so prio isn't high
Currently the "npm start" commans generates a dev folder with the deploy files.

So if i move this files in my dev Folder to e.g xampp htdocs, this wont work because i need some node_modules and other stuff, furthermore the path with host.com/#dist/dev is not good.

Am I missing something that you have already build in, a task to get a clean deploy folder with normal path :) ?

**Comment by mgechev** [comment]
You should run the production build and right after that move your `/dist/prod` directory in the context of your server.

**Comment by tomlobato** [comment]
Some suggestion for the server stack? So far, running the prod build is ok, but now I`m wondering what would be the best stack to serve it. I cannot simply put the prod generated files into a web folder (say Apache), since my users will need to be able to access some pages directly, without going to / before (/order for instance).

**Comment by mgechev** [comment]
You can provide link to `/orders` and if your static server handles properly HTML5-style urls it should work.

**Comment by tomlobato** [comment]
HTML5-style urls are common urls, without # as in ng1, from what I`ve seen.
So we are talking about to put in a web directory, served only by Apache, the index.html generated by prod build (and the rest of files, that doesn`t include a /orders folder). 
Well, in this case the apache would return 404 for GET /orders, as it doesn`t know about the ng2 routes.

**Comment by mgechev** [comment]
No, you need to redirect all the requests to non-existing resources & endpoints to `index.html`. Take a look at this [StackOverflow question](https://stackoverflow.com/questions/17444072/angularjs-cant-get-html5-mode-urls-with-ui-route-state).

**Comment by tomlobato** [comment]
@mgechev perfect!
Simple internal redirect to index.html, so the app is downloaded and initialised normally and the ng router will handle the original path (/order) on client side.
Now its clear. Tks a lot!

**Comment by TheDonDope** [comment]
@tomlobato you can also have a look here: https://github.com/mgechev/angular-seed/blob/master/.docker/nginx.conf for the nginx config
