### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#322]
How to add favicon.ico in a right way? I have put it into `assets/` folder and added link in `index.html`
```html
<link rel="shortcut icon" href="/app/assets/favicon.ico" type="image/x-icon" />
```
But it will not work for production.

**Comment by tandu** [comment]
Added `join(APP_SRC, '**/*.ico')` in `tools/tasks/build.img.dev.ts` and changed link to
```html
<link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
```

**Comment by mgechev** [comment]
Just like you mentioned, you need to keep the path relative (i.e. `./assets/favicon.ico`).
