### ISSUE TITLE
Invalid paths on serve (404 not found error)

### ISSUE THREAD

**Issue by lihaibh** [mgechev/angular2-seed#324]
When i run 'npm start' i receive an error when i load the site.
on the console it appears that it tries to find invalid route path:
http://localhost:5555/D:/path-to-project/node_modules/bootstrap/dist/css/bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)

It serves invalid path (uses absolute path to the file instead of relative path) in dist/dev/index.html

OS: windows 10
npm version: 3.5.2
Node version: 5.2.0

**Comment by mgechev** [comment]
Just tried to reproduce your issue but I cant manage to do so:

![](https://i.imgur.com/WFcKpft.png)

**Comment by lihaibh** [comment]
It doesnt work for me unfortunately, it generates invalid path when running task 'build.index', i made a new clone locally installed npm dependencies and start, it produce the index.html with this content:
  
  <script src="/D:/Projects/WebStorm/Github/Angular2/angular-seed2/node_modules/es6-shim/es6-shim.min.js"></script>
  <script src="/D:/Projects/WebStorm/Github/Angular2/angular-seed2/node_modules/reflect-metadata/Reflect.js"></script>
  <script src="/D:/path/to/project/node_modules/systemjs/dist/system.src.js"></script>
  <script src="/D:/path/to/project/node_modules/angular2/bundles/angular2-polyfills.js"></script>
  

  <script>System.config({"defaultJSExtensions":true,"paths":{"bootstrap":"/dist/dev/bootstrap","*":"/node_modules/*"}})</script>

**Comment by lihaibh** [comment]
Ok i understood what caused this, i made a junction link to my projects directory in C: drive that will point to its location in D: drive, when i run npm install & npm start, from its original location it works however when i try to run it from the symbol link it failes give the full path instead of the relative path.

**Comment by mgechev** [comment]
Ok, so we ca close this.
