### ISSUE TITLE
[question] Scaling to hundreds of components?

### ISSUE THREAD

**Issue by cthrax** [mgechev/angular2-seed#325]
This looks like a great seed! Thanks for the work! My current angular 1.x project has a couple hundred directives that I would imagine translate directly to components, but this organization doesn't seem to scale to that very well. I presently use an organization that is somewhat hierarchical for each directive and child directive. With a top-level components folder for shared directives (and their children). I'm just curious what recommendations and accommodations you have for such a project.

Cheers!

**Comment by NathanWalker** [comment]
@cthrax Could you provide a sample of what your hierarchy looks like (in short)? Just to be sure we understand exactly what your structure is.

**Comment by cthrax** [comment]
Sure, and just to be clear, I'm not proposing my structure as the "right" structure, it's just what has evolved to accommodate my needs, I was actually hoping that another structure had been developed.

Presently I use something akin to (at the folder level):

app
-components
--common-component
---child-component1
---child-component2
--common-component2
-page1
--subview1
---child-component
----grandchild-component
--subview2

**Comment by NathanWalker** [comment]
It seems like that should be no problem. Have you tried a similar setup with this seed and encountered issues with compiling TypeScript or something else?

**Comment by cthrax** [comment]
No, not at all. I really was just asking what the collective braintrust here has come up with for a scenario such as I posited. If that's beyond the scope of this project, that's fine.

**Comment by NathanWalker** [comment]
This seed is pretty well setup to handle just about whatever you can throw at it. 
I've been converting a large production app with hundreds of components myself at the moment with this seed as the base and it's been great :+1: 

Enjoy!
