### ISSUE TITLE
[help] guidance configure external lib

### ISSUE THREAD

**Issue by mmrath** [mgechev/angular2-seed#326]
Hi 

I would like to use https://github.com/medialize/URI.js in a angular2-seed project. Would anyone know how to configure it?

I installed it using npm and tsd. Tried importing with the following, but it did not work

    import {URI} from 'urijs';
    import {URI} from 'urijs/URI'; 

Any help is much appreciated.

**Comment by tandu** [comment]
Look at `tools/config.ts`, you should add it here in `NPM_DEPENDENCIES` array.

**Comment by mgechev** [comment]
Just updated the guidelines for adding a [custom library](https://github.com/mgechev/angular2-seed#now-to-extend).
