### ISSUE TITLE
How to make it / instead of /dist/app

### ISSUE THREAD

**Issue by tehthird** [mgechev/angular2-seed#328]
Hello, is there an easy way to get this app to be loading from the root of the server, / , instead of /dist/app ? I have tried to edit config.ts and set APP_DEST to '', and move the assets to the root too, and it works, but then i get an error on i click on boostrap tabbed windows' links: EXCEPTION: TypeError: Cannot read property 'toUrlPath' of null. Tried quite a bit without luck. 

I also had to change from "    System.import('bootstrap')" to "    System.import('./bootstrap')" in order for angular2 to boot this way, but i guess my approach is wrong anyway.

**Comment by mgechev** [comment]
If you build the app with:

gulp build.prod

You can move dist/prod to / and everything should work.

**Comment by tehthird** [comment]
It sure did, thank you mgechev, and thanks for this awesome repository.

**Comment by NathanWalker** [comment]
In other words, the prod build is meant to create a build that you can drop
into your server root no matter what your server setup is and it should
just work.

If you are trying to get PathLocationStrategy working on the prod build
"within the seed", I'm not sure, there may be a way.

**Comment by tehthird** [comment]
Nathan, i dont get that error more after running it with "npm start -- --env prod" and editing APP_DEST to ""; Now i can click #tabbed links just fine, while the app is in root

**Comment by NathanWalker** [comment]
Excellent :)
