### ISSUE TITLE
gulp build.prod broken?

### ISSUE THREAD

**Issue by neilyoung** [mgechev/angular2-seed#329]

**Comment by mgechev** [comment]
It isn't use:

gulp build.prod --evn prod

**Comment by neilyoung** [comment]
You're right. My bad. Sorry

**Comment by Bigous** [comment]
or 
```
npm run build.prod
```

**Comment by mgechev** [comment]
@neilyoung no worries! The current API is slightly confusing anyway. In case you use gulp build.prod it shouldn't be necessary to set the environment flag.

**Comment by neilyoung** [comment]
However, I cannot even produce something useful for prod. Could you please check? Fresh install. npm run build.prod ok, but it is not really running then

**Comment by ludohenin** [comment]
@neilyoung you should check #350
