### ISSUE TITLE
Adding angular2/forms

### ISSUE THREAD

**Issue by Narretz** [mgechev/angular2-seed#33]
I am trying to import stuff from angular2/forms inside a component. I have added "forms" analogue to router in the gulpfile, but the typescript compiler still cannot find the angular2/forms module (`app\components\home\form.ts(2,78): error TS2307: Cannot find external module 'angular2/forms'.`). Is there something specfic in the seed project that I need to change / add?

**Comment by ludohenin** [comment]
@Narretz As of now, everything is exported from `angular2/angular2` (except for `angular2/router`). This will likely change in the future. The definition file is auto-generated from the source and is according to [angular2 module](https://github.com/angular/angular/blob/master/modules/angular2/angular2.ts).
So you can `import {formDirectives, ...} from 'angular2/angular2'`.
Also note that the definition file isn't perfect yet and often needs manual patches.

**Comment by Narretz** [comment]
@ludohenin Thanks a lot, that was it. I had previously tried that, but I wrote `FormsDirectives`, with a capital `F` ...
