### ISSUE TITLE
Overrides to config.ts

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#330]
Okay, so what about some overrides to config.ts defaults? Eg. some simple ```config.json``` file that is ignored in VCS where those default values are read from if file exists, otherwise those "default defaults". With this modification users could just make single json file which contains default config values without need to specify these on cmd.

**Comment by mgechev** [comment]
Externalizing the dependencies into a JSON file and allowing the users to override the defaults using it sounds like a good idea to me.

We already have a lot of config options so passing them as flags using the command line interface sounds not that comfortable.

**Comment by tarlepp** [comment]
Hmm, I did little work for this. https://gist.github.com/tarlepp/f3105107575b4b6d0931

What do you think?

**Comment by tarlepp** [comment]
@mgechev did you look that gist?

**Comment by mgechev** [comment]
At first sight looks great! I will review it further on Monday.

**Comment by ludohenin** [comment]
@tarlepp Looks good to me as well. The only thing maybe would be how to load a config.{ENV}.json based uppon targetted build (dev, prod, pre-prod ...) ?

**Comment by ludohenin** [comment]
I'm actually thinking of adding an initial `config` task for that (the same way as `clean.x` ones).

**Comment by mgechev** [comment]
@tarlepp I like it! The suggestion by @ludohenin makes sense, it'll be great to include specific configuration based on the set environment.

Also, you can externalize [most of these constants](https://gist.github.com/tarlepp/f3105107575b4b6d0931#file-config-ts-L10-L42). What do you think?

**Comment by tarlepp** [comment]
Yeah, env specified config files should not be a problem. What needs some thinking imho:
* What is the format? json, yaml? I would prefer json
* Is it ok that app checks some not existing file? eg. if dev.json not founded app will use 'static' defaults
* I would keep those constants because of imports, or is there some another way to get this working?
* Docs should be updated after this PR
* What else?

**Comment by mgechev** [comment]
* Yes, JSON seems good to me
* I'm thinking of a `config` directory under `./tools`
* Yes, I think that should be the default behavior (if the config doesn't exist use the hardcoded configuration inside `config.ts`)
* Yes, keep the current constants. You can just set them different value based on the choosen configuration based on the environment, in case such a config file exists
* Yes, the docs needs to be updated. It'll be also great if we add a [wiki page](https://github.com/mgechev/angular2-seed/wiki)

I think thats all.

**Comment by ludohenin** [comment]
@mgechev what do you think openning a `config` branch, @tarlepp to make a PR on that one so we can work on it from this repo ?
Maybe some comments
* JSON +1 (by default but keep it open)
* `config` +5
* I would get rid of the current constant and add `seed.json, seed-default.json ... whatever`. The `extend` cascade could maybe be `seed.json => seed.env.json => user.env.json` Maybe we should be able to define `--env=prod` and `--config=preprod.ts` from cli
* doc/wiki +1

**Comment by aminmagdich** [comment]
Hi,
 I can't find any information online to point me in any direction of solving this issue.

![captureaaa](https://cloud.githubusercontent.com/assets/11071691/12881311/3a8626ec-ce49-11e5-8ef9-9562f15a8262.PNG)

**Comment by mgechev** [comment]
@tarlepp do we have this working?
