### ISSUE TITLE
Test results are ignored

### ISSUE THREAD

**Issue by SIGAN** [mgechev/angular2-seed#333]
Currently, all tests always ignore any `expect` statements inside of `.then(rootTC => { ... })`.

for example, add to Home_spec.ts right after last `expect` this code:
`expect(true).toEqual(false);`
It won't trigger failure of tests...
You can change selector to 'h2' and it will succeed as well...

How to fix that?

**Comment by mgechev** [comment]
Thanks for the catch! I'll take a look at the issue asap.

**Comment by SIGAN** [comment]
I have found the reason - 'angular2/testing_internal' should be changed to 'angular2/testing'
But unfortunately then fails DOM (it is null)

**Comment by ludohenin** [comment]
DOM isn't null for me, but I'm getting this error
```
Can't bind to 'ngForOf' since it isn't a known native property ("
    </form>
    <ul>
      <li [ERROR ->]*ngFor="#name of list.get()">{{name}}</li>
    </ul>
  "): AboutCmp@13:10
Property binding ngForOf not used by any directive on an embedded template ("
    </form>
    <ul>
      [ERROR ->]<li *ngFor="#name of list.get()">{{name}}</li>
    </ul>
  "): AboutCmp@13:6
```

**Comment by mgechev** [comment]
Fixed the issue here https://github.com/mgechev/angular2-seed/tree/fix-333
