### ISSUE TITLE
css not working

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#334]
Hi,
If I put my css directly at index.html like:
```html
<link rel="stylesheet" type="text/css" media="screen" href="/app/assets/css/smartadmin-production-plugins.min.css">
```
It works!
But if I put my css to be inject configuring at config.ts like:
```typescript
{ src: `${ASSETS_SRC}/css/smartadmin-production-plugins.min.css`, inject: true, dest: CSS_DEST },
```
This not works. My css is loades at html page (not receiving 404) but it not works.

Another problem is that my CSS and JS that I put at config.js is not being copy to dest folder, at html page they still being refer to app folder and not to dist/dev folder

Some js examples:
```typescript
export const APP_ASSETS = [
//some CSS
{ src: `${ASSETS_SRC}/css/smartadmin-production-plugins.min.css`, inject: true, dest: CSS_DEST },

//some JS
{ src: `${ASSETS_SRC}/js/notification/SmartNotification.min.js`, inject: true, dest: `${JS_DEST}/notification`},
];
```

**Comment by mgechev** [comment]
At this point the CSS files do not get copied to the `dist/dev` directory. After we merge the hot-loader branch you will get this behavior. Injecting the resources should work properly:

```ts
export const APP_ASSETS = [
  { src: `${ASSETS_SRC}/main.css`, inject: true, dest: CSS_DEST },
  { src: `${ASSETS_SRC}/css/test.css`, inject: true, dest: CSS_DEST }
];
```
The code above will add the following:

```html
<link rel="stylesheet" href="/app/assets/css/test.css">
```

It is not considered good practice to add CSS files using the absolute path since in production and (after the merge of the hot-loader branch) in development environment the path should be different, so it is better to list the resources in the `APP_ASSETS` array.

**Comment by gustavolira** [comment]
But I did exactly what you said. If you see my code that I put here:
```typescript
{ src: `${ASSETS_SRC}/css/smartadmin-production-plugins.min.css`, inject: true, dest: CSS_DEST },
```
I put all my css and js at config.js inside of APP_ASSETS

**Comment by grunzmeniroj** [comment]
hi mgechev,
I followed these steps https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support after that 
css file injection is not working 

inside tools/config/project.config.ts  i modified constructor like this
```

constructor() {
    super();
    this.APP_TITLE = 'Welcome to Nylnda';
    let additional_deps: InjectableDependency[] = [
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'}
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

    this.APP_ASSETS = [
      
      { src: '${this.ASSETS_SRC}/main.scss', inject: true}, // renamed SASS file
    ];
    const seedDependencies = this.NPM_DEPENDENCIES;

    this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);
    this.CSS_PROD_BUNDLE = 'main.css';

  }
```

Build process doesn't show any error but as expected main.css is not injected in index.html 

```
 <title>Welcome to Nylnda</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- inject:css -->
  <!-- endinject -->
</head>
<body><script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.12.8.js'><\/script>".replace("HOST", location.hostname));
//]]></script>


  <nd-app>Loading...</nd-app>

```

what might be wrong... Please help me

**Comment by TheDonDope** [comment]
Have you renamed and moved your `src/client/assets/css/main.css` to `src/client/assets/main.scss`?

**Comment by grunzmeniroj** [comment]
Yes I did that...

**Comment by grunzmeniroj** [comment]
hi 
Now I have another question.... I installed susy using npm install susy --save
How to load the susy in my .scss file ?
