### ISSUE TITLE
Support for the Angular 2 beta

### ISSUE THREAD

**Issue by codeslubber** [mgechev/angular2-seed#338]
I cloned this project and was able to get Karma working, tests run in IntelliJ.

However, in trying to get same working in another project, that has the beta, it doesn't work. I am getting a 404 when the shim attempts to load the browser adapter. But then I also got a bunch of errors from the attempted loading of other files stipulated in the karma conf.

```
WARN [watcher]: Pattern "./node_modules/angular2/bundles/angular2.js" does not match any file.
WARN [watcher]: Pattern ".node_modules/angular2/bundles/testing.js" does not match any file.
WARN [watcher]: Pattern './src/test/matchers.js" does not match any file.
WARN [watcher]: Pattern "./src/**/*.css" does not match any file.
```

Of course the angular file is not there (I shortened the paths.)

**Comment by mgechev** [comment]
We support Angular 2 beta. I don't think this issue is related to the seed project?

What is the other project where you can't get karma working?

**Comment by codeslubber** [comment]
I cloned the project yesterday or the day before and this is in the package.json file:

```
  "devDependencies": {
    "angular2": "2.0.0-alpha.44",
```
The other project is one of my own projects that has running angular2 code in it, trying to simply add karma to it. For whatever reason, the angular 2 docs do not cover karma in their testing section (which makes no sense).

**Comment by mgechev** [comment]
We tagged `2.0.0-beta.0` a few weeks ago. Take a look at [this](https://github.com/mgechev/angular2-seed/blob/master/package.json#L82).

You can see how we did the integration with karma and use it in your personal project.

**Comment by codeslubber** [comment]
I cloned master yesterday. So I should have cloned the tag? It looks like the PR was merged, no?

**Comment by codeslubber** [comment]
My mistake. Thanks.
