### ISSUE TITLE
Question: http libraries from angular2/angular2 ?

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#35]
Why not leave the imports in the place most people will be taught to import from?

Shouldn't `httpInjectables` and `Http` come from "angular2/http" ?

I think this will confuse people more than help.

**Comment by ludohenin** [comment]
@NathanWalker you should have a look at #33

**Comment by NathanWalker** [comment]
Ah ok, thanks for that :+1:
