### ISSUE TITLE
Possible issue with #349

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#353]
Hmm, not sure if this is only on me, but reporting still. Apps start like it should with ```npm start``` but in my browser console I get this:

![image](https://cloud.githubusercontent.com/assets/595561/12129333/94d49bb8-b40b-11e5-886b-ade7918c96bc.png)

And if I just remove ```"outDir": "dev/ts_compiled"``` from tsconfig.json file all works like it should. It seems like that adds ```app``` folder under ```dist/dev``` and that causes all the problems. And screenshot about that difference:

![image](https://cloud.githubusercontent.com/assets/595561/12129643/8bc0a9fc-b40d-11e5-8733-1409b3011507.png)

**Comment by ouq77** [comment]
Hey. I'm not able to reproduce this in the seed app. Have tried in both WebStorm and ItelliJ.

Can you tell me a bit more about your setup?

This is what it looks like for me (not the toplevel dev/ts_compiled folder):

![dev ts_compiled](https://cloud.githubusercontent.com/assets/1796191/12132430/4ed9129a-b480-11e5-9c24-ac06c6f7eaf8.png)

**Comment by tarlepp** [comment]
Basically just a clone of this repo, you can see the sources from there https://github.com/tarlepp/angular-sailsjs-boilerplate-frontend-angular2/

**Comment by mgechev** [comment]
@tarlepp same here. I'll make a hot fix in master but it'll be nice to keep the `outDir` somehow.

**Comment by mgechev** [comment]
@tarlepp I reverted back. Let me know if the issue still occurs, otherwise you can close it as fixed.

**Comment by tarlepp** [comment]
Yeah, removing that config solves this.
