### ISSUE TITLE
Example including a 3rd party lib with tsd via DT?

### ISSUE THREAD

**Issue by bertvh** [mgechev/angular2-seed#357]
I've included moment.js. In Typescript 1.6, I didn't import moment but just used the global variable. Probably not such a good idea. Anyway, it worked.

Since I've upgraded to typescript 1.7, the compiler doesn't like that anymore:
    
    error TS2304: Cannot find name 'moment'
    error TS2503: Cannot find namespace 'moment'.

So I've tried to add this

    import * as moment from 'moment/moment'

That doesn't work either

     error TS2307: Cannot find module 'moment/moment'.

The moment.d.ts file is in typings/tsd and is included in tsd.d.ts. What am I missing here?

Everything works at runtime, but I don't like big red errors on the console :s

**Comment by mgechev** [comment]
`tsd.d.ts` is used by `gulpfile.ts` and the tasks it uses. For now you can either move `moment.d.ts` in a location visible by the application or include it as `<reference path="../../tools/typings/tsd/moment.d.ts"/>`.
