### ISSUE TITLE
Serve production build

### ISSUE THREAD

**Issue by caracena** [mgechev/angular2-seed#358]
First of all,  thanks for this amazing work. Really helpful to setup your own project.

I have a doubt about how can I serve a production build. When I run ``` npm run build.prod ``` and then serve dist/prod with python like ``` python3 -m http.server ``` and check the browser, I got the next errors: 
``` 
Failed to load resource: the server responded with a status of 404 (File not found) http://localhost:8000/bootstrap.js
Error: XHR error (404 File not found) loading http://localhost:8000/bootstrap.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues" localhost/:37
``` 
and the site keep loading forever (with Loading...). 
I tried to change the System.import('bootstrap') in index.html without results.
I use ``` npm 2.14.7 ```, ``` node v4.2.2 ```, ``` chrome v47 ``` and ``` Ubuntu 15.10 ```

**Comment by mgechev** [comment]
Most likely related to https://github.com/mgechev/angular2-seed/issues/350

**Comment by czaktesta** [comment]
I'm not sure yet what is the exact issue but the problem is related to the version of systemjs. It works fine with 0.19.9. Does not work anymore with 0.19.12. Changing the version should help at least as 'quick fix'.

**Comment by mgechev** [comment]
@czaktesta thanks for pointing this out! We'll need to take a further look at this issue, for now I workarounded it with the fix you suggested.
