### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by Nemmo** [mgechev/angular2-seed#359]
Here is the log from `npm-debug.log` file:
```console
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@0.0.0~prestart: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@0.0.0~start: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\OpenServer\domains\angular2-seed\node_modules\.bin;c:\openserver\modules\php\PHP-5.6\ext;c:\openserver\modules\php\PHP-5.6\pear;c:\openserver\modules\php\PHP-5.6\pear\bin;c:\openserver\modules\php\PHP-5.6;c:\openserver\modules\imagemagick;c:\openserver\modules\wget\bin;c:\openserver\modules\git;c:\openserver\modules\git\bin;c:\openserver\modules\git\mingw\bin;c:\openserver\modules\git\cmd;c:\openserver\modules\database\MySQL-5.6\bin;c:\openserver\modules\http\Nginx-1.7\bin;c:\openserver\modules\http\Nginx-1.7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\SysWOW64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\HashiCorp\Vagrant\bin;C:\Program Files\nodejs\;C:\Users\Alimzhan\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Alimzhan\AppData\Roaming\npm
10 verbose lifecycle angular2-seed@0.0.0~start: CWD: C:\OpenServer\domains\angular2-seed
11 silly lifecycle angular2-seed@0.0.0~start: Args: [ '/d /s /c', 'gulp serve --env dev' ]
12 silly lifecycle angular2-seed@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve --env dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd C:\OpenServer\domains\angular2-seed
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 start: `gulp serve --env dev`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve --env dev
23 error You can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gnjuguna** [comment]
I am getting the same error.

**Comment by thedanotto** [comment]
I also cannot start the application.

    [angular2-seed]$ npm start                                                                                                                                                                               [5/5]

    > angular2-seed@0.0.0 start /Users/angular2-seed
    > gulp serve --env dev

    [17:51:56] Requiring external module ts-node/register
    ----------------------------------
    ⨯ Unable to compile TypeScript
 
     gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)`

**Comment by mgechev** [comment]
@thedanotto most likely your setup is lacking the type definition. Did you run `npm install`? What is your OS?

**Comment by Nemmo** [comment]
@mgechev So, what about my problem? Seem like @thedanotto has different problem, not like my.

**Comment by thedanotto** [comment]
Sorry for hijacking thread, I can start a new issue.

**Comment by mustafacoskuncom** [comment]
Hi everybody. I am new in Angular 2 and I wonder that just we are starting the app via terminal? npm or other codes? Is there anyway like classical index.html run on localhost and open the project? Would you explain it? Thanks for your helps.

**Comment by Bigous** [comment]
Lots of questions @mustafacoskuncom  :D
 > I am new in Angular 2 and I wonder that just we are starting the app via terminal? npm or other codes?

```bash
git clone https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install
npm start
```
look at the [Readme.md](https://github.com/mgechev/angular2-seed/blob/master/README.md)

 > Is there anyway like classical index.html run on localhost and open the project?

If you build the production setting of this seed ```npm build.prod```, you will see that it will create ```dist/prod``` under your clone directory... it has a classical ```index.html``` and everything else you need to run your application

 > Would you explain it?

Well... this is the main references you should learn from:
- [Angular2](https://angular.io/docs/ts/latest/guide/);
- [gulp](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md)
- [NodeJS](http://nodejs.org);
- [NPM](https://docs.npmjs.com/);
- [Typescript](http://www.typescriptlang.org/);

**Comment by Nemmo** [comment]
Still cannot run the application.

**Comment by mustafacoskuncom** [comment]
I think you misunderstood me I already run the app there is noproblem. But when I run directly index html real or clone directory not important.. Just waiting Loading.... and there is nothing. Understand?

**Comment by Bigous** [comment]
@Nemmo could you try to run it with Node 4.2.x ?

**Comment by Nemmo** [comment]
@Bigous Yes, of course I've tried already with Node 4.2.x

**Comment by Bigous** [comment]
@mustafacoskuncom Yes, it happens when angular or another required library was not loaded... look at your browsers console log to see what happened.

**Comment by Bigous** [comment]
@Nemmo The npm log was the same?

**Comment by mustafacoskuncom** [comment]
Yes as you said I check th Console and could not load the files when run it directly without terminal codes. And also I learned by this way this app run on "Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode." :) I think that it seams VS export application style... Debug mode and release mode... At the beginning of the learning stage have so many problems would u share your tutorials or sources like this if it won t be problem for you? Thanks again.

**Comment by mgechev** [comment]
@Nemmo I cant reproduce this issue (Windows 10, node 5.3.0, npm 3.3.12).

**Comment by Bigous** [comment]
@Nemmo I cant reproduce too (Windows 10, node 4.2.3, npm 3.3.10)...

Try a fresh install of nodejs and npm, npm clean cache before clone the repo again and try a npm install and npm start.

**Comment by Bigous** [comment]
@mustafacoskuncom  This repo is an start kit to angular2, but if you want to learn how angular 2 works, you should look at the references I gave you first...
To work with this repo, at the development, you will need a terminal window to start node... it was not made to run without it. 
It could be a feature request to have a .vscode directory with a start script where you could press F5 and everything just works starting node behind the scenes. But it should be another issue and @mgechev and others should discuss about it first.

**Comment by Nemmo** [comment]
@Bigous It works! I have just cleaned the cache and cloned the repo again. It's really strange, because my two friends tried to run the app on the another computers and it fails like me.

**Comment by mgechev** [comment]
@Bigous @Nemmo we can close this issue?

**Comment by Nemmo** [comment]
@mgechev Yes, we can. Especially thank @Bigous for help with my issue!

**Comment by Bigous** [comment]
:+1:

**Comment by dracon** [comment]
@mgechev Thank you...
It worked for me with npm clean cache and npm install!

**Comment by keepscoding** [comment]
@mgechev Thanks you.
It worked for me on OS X 10.11.3 after 
1 npm run reinstall
2 delete the newly cloned seed
3 clone again

**Comment by BojanKogoj** [comment]
Weird issue, I first tried this seed and it worked, tried again and I can't get it to work. So this issue persists

**Comment by DanSiew** [comment]
I have the same problem and found the lesson-server.ts uses port 8080

var server = app.listen(8080, function() {
    console.log("Server running at http://localhost:" + server.address().port);
});

My 8080 port is used, so I have changed it to 8081, it works.

**Comment by LungeloNzimande** [comment]
After trying some suggestions I updated Node and restarted my PC, run npm install and it worked...
