### ISSUE TITLE
Consider using rx.all.js?

### ISSUE THREAD

**Issue by jimthedev** [mgechev/angular2-seed#36]
Hello.

I'm curious at the difference between using rx.js and rx.all.js in the gulpfile. As a newcomer to Rx, I struggled to figure out the version of rx that I needed in order to use to use .fromCallback. What is the tradeoff between rx.all and rx? 

In the end, I swapped in rx.all.js in the gulpfile and ran `tsd install rx.async-lite --save` and was able to use this feature.

Thanks for this project, just wanted to get this small feedback to you to see what the difference is between these two options.

**Comment by mgechev** [comment]
I think this question belongs to the Rx.js project's issue tracker. Here's what part of [Rx.js Angular 2 uses](https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts).

However, judging from the [`Gulpfile.js` in the Rx.js's repo](https://github.com/Reactive-Extensions/RxJS/blob/master/Gruntfile.js), you can find `.fromCallback` in:

- `rx.all.js`
- `rx.all.compat.js`
- `rx.lite.js`
- `rx.lite.compat.js`
- `rx.async.js`
- `rx.async.compat.js`

**Comment by jimthedev** [comment]
Thanks! I think I had modified my gulpfile to include Rx in BuilderNg2 but had not actually included it in my list of global dependencies.
