### ISSUE TITLE
Debugging tasks

### ISSUE THREAD

**Issue by amb-it-ion** [mgechev/angular2-seed#361]
First of all: Great job. I am using this seed already in a big portal project, and feel blessed to have found you.

However, I felt quite in pain, when traing to debug some gulp-pipes. Frankly, I have not found a solution yet and believe, this would be VERY helpful to have. Can you please provide some comments or documentation on how to do this? E.g. I was trying to rename the file path for compiled sass files coming from "assets/scss" folder to "assets/css" folder using the gulp-rename plugin:

```javascript
return gulp.src(join(APP_SRC, "**", "*.scss"))
      .pipe(plugins.sass().on("error", plugins.sass.logError))
      .pipe(rename(function (path) {
        path.dirname = path.dirname.replace("scss","css");
      }))
      .pipe(gulp.dest(APP_DEST));
```

This works nicely now, however I can not debug anything inside here. Hack, I do not even not know how to print some value to the console. :-(

**Comment by mgechev** [comment]
Thanks for the kind words, we're glad we helped!
May be `[gulp-debug](https://www.npmjs.com/package/gulp-debug)` with `[node-inspector](https://github.com/node-inspector/node-inspector)`will help.
