### ISSUE TITLE
CSS files in the prod build are not minified

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#362]

**Comment by ludohenin** [comment]
Components' css files are minified in the prod build. @mgechev Are you thinking to something else ?

**Comment by mgechev** [comment]
The CSS files located at assets are not getting minified yet.

**Comment by ouq77** [comment]
I've been looking at cache busting, which could take care of the minification during the revision task. Have a look here: https://github.com/mgechev/angular2-seed/compare/master...ouq77:feature/revision.

**Comment by Bigous** [comment]
I thing we should copy assets directory as is, or, how could we put an example CSS file to show somewhere in the application?
A minified version of the file is not too good to be shown to the final user :D
