### ISSUE TITLE
Run the e2e tests in CI

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#363]
Currently the e2e tests are not run in Travis neither in AppVeyor.

**Comment by NathanWalker** [comment]
@ludohenin or @tarlepp If either of you could help with configuring the e2e tests here would be appreciated!

**Comment by ludohenin** [comment]
@NathanWalker First I think instead of using the `build.dev` it would make more sense to use `build.test` (requires a protractor conf update) and then I guess it just a matter of adding the command to the npm script `"test": "gulp test"` => `"test": "gulp test && npm run e2e"`

**Comment by ludohenin** [comment]
see #447

**Comment by NathanWalker** [comment]
Thanks @ludohenin ... If a PR results out of #447 then I will submit a PR to take care of this using that adjustment.

**Comment by mgechev** [comment]
@NathanWalker we already have it https://github.com/mgechev/angular2-seed/pull/476
