### ISSUE TITLE
Production build enhancements

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#364]
- [ ] Minify CSS files https://github.com/mgechev/angular2-seed/issues/362
- [ ] Automatically set the environment variable when `gulp build.prod` is used https://github.com/mgechev/angular2-seed/issues/350
- [ ] Produce a single minified JavaScript file for all the JavaScript resources
- [ ] Use production version of Angular (the one without the template compiler) (blocked by Angular for now)

**Comment by flofly** [comment]
+1 for this issue

**Comment by mgechev** [comment]
@flofly you can give it a try at https://github.com/mgechev/angular2-seed/tree/prod-enhancements.

Let me know what you think.
