### ISSUE TITLE
How to make main.scss @import "compass/css3"; work when using sass?

### ISSUE THREAD

**Issue by Alber70g** [mgechev/angular2-seed#369]
I've used the sass extend in the readme with something to make the importer work.

I've installed the `sass-npm` module to make the `@import "compass/css3";` work, but it cannot resolve it. 

So in my `main.scss` is now: 
```
@import "compass/css3";
```

My `build.sass.dev.ts` looks like this:
```
import {join} from 'path';
import {APP_SRC, APP_DEST} from '../config';
import {importer} from 'sass-npm';

export = function buildSassDev(gulp, plugins, option) {
  return function () {
    return gulp.src(join(APP_SRC, '**', '*.scss'))
      .pipe(plugins.sass({
          importer: importer
      }).on('error', plugins.sass.logError))
      .pipe(gulp.dest(APP_DEST));
  };
}
```

**Comment by Malines** [comment]
@Alber70g have you tried to to this to use the importer?

tasks_tools.ts en edit the following function 
```
export function task(taskname: string, option?: string) {
  util.log('Loading task', chalk.yellow(taskname, option || ''));
  return require(join('..', 'tasks', taskname))(gulp, gulpLoadPlugins({pattern: ['gulp-*', 'gulp.*', 'sass-npm']} ), option);
}
```
and then use the plugins to get the importer 

```
import {join} from 'path';
import {APP_SRC, APP_DEST} from '../config';

export = function buildSassDev(gulp, plugins, option) {
  return function () {
    return gulp.src(join(APP_SRC, '**', '*.scss'))
      .pipe(plugins.sass({
          importer: plugins.sassNpm.importer
      }).on('error', plugins.sass.logError))
      .pipe(gulp.dest(APP_DEST));
  };
}
```

I also have trouble to import the filer for foundation-sites. the @import fails on the node_modules folder
I only get the first lines of comments and a class I added for test all the referenced imports are failing

**Comment by Alber70g** [comment]
Thanks for this advice. It does work indeed, but I have to fill the full path: `import "node_modules/compass-mixins/lib/compass/css3";`. Is there a way to avoid this?

Maybe I should include all sources including the ones from `node_modules/**`?

**Comment by mgechev** [comment]
I closed this issue since it is no longer related to the seed.
