### ISSUE TITLE
e2e not working on Windows

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#370]
When running `npm run e2e` I'm getting the following:
```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
[launcher] Error: Error: Could not find chromedriver at C:\www\angular2-seed\node_modules\protractor
\selenium\chromedriver.exe
```

This maybe an issue to run test with appveyor (see #363)

**Comment by NathanWalker** [comment]
@ludohenin I've seen a similar error even on OS X depending on whether the web driver was updated.
Did you try running this first?:
npm run webdriver-update

**Comment by mgechev** [comment]
I can't reproduce it on Windows 8.1 running in Parallels. Had the same issue when I forgot `npm run webdriver-update`.

**Comment by ludohenin** [comment]
LGTM
