### ISSUE TITLE
How to include folder with fonts

### ISSUE THREAD

**Issue by e-oz** [mgechev/angular2-seed#372]
Currently if I place "fonts" folder with fonts and css (to /assets or somewhere else), only 1 file copied: svg version of font. What I can change in config to copy all fonts? Or just whole assets folder, without any filtering.

**Comment by ludohenin** [comment]
Like this (in `config.ts`):
```
const NPM_DEPENDENCIES = [
  //...
  { src: 'node_modules/my-lib/dist/fonts/**/*', dest: FONTS_DEST }
];
```

**Comment by Bigous** [comment]
Yes, but shouldn't we copy everything inside assets?

**Comment by ludohenin** [comment]
It's copied to `dist/prod`. We avoid copying things around for dev.

**Comment by e-oz** [comment]
And it makes me to invent workarounds to fix issues with paths, it's ugly and inconvenient.

**Comment by e-oz** [comment]
please consider to make it configurable

**Comment by ludohenin** [comment]
@e-oz is it because you want to "deploy" dev builds ?

**Comment by mgechev** [comment]
It seems like this issue is resolved? [Now we copy assets in dev](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.assets.dev.ts). because of several issues in the past and the external component templates.

**Comment by e-oz** [comment]
No, still only 1 file copied (most fresh version of seed - master branch).

<img width="248" alt="screenshot 2016-01-14 14 25 03" src="https://cloud.githubusercontent.com/assets/526352/12323225/b7b86126-baca-11e5-9b3f-b96a2b48e5a9.png">

**Comment by e-oz** [comment]
@ludohenin no, it's because I had links to assets and in "beta.0" release they weren't working without `<=% APP_ROOT %>assets/` addition (and were working just fine in deployed prod build). In `beta.1` release it's fixed, so please ignore my ask to make it configurable. And thank you for fixing it.

**Comment by mgechev** [comment]
@e-oz you may need to add `ttf`, `eot` and `woff` files to this task https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.assets.dev.ts

**Comment by e-oz** [comment]
@mgechev thank you. I wonder why not `**` :) But maybe there are reasons for it. Thank you, now I know where to configure it.

**Comment by mgechev** [comment]
May be we can copy everything except `*.ts` files in order to ease the configuration?
// cc @ludohenin

**Comment by ludohenin** [comment]
@mgechev sounds good to me.
