### ISSUE TITLE
Turkish Character Problems

### ISSUE THREAD

**Issue by mustafacoskuncom** [mgechev/angular2-seed#374]
I tried Turkish Character sets and App did not run. There is a blank white page if I use İ,Ğ,ş,ö,ç etc. What can be problem? I saved the file UTF-8 however problem continue. Have you ever faced like this issue? Thanks again.

**Comment by mgechev** [comment]
I am able to reproduce your issue but it seems related with the Angular's DOM compiler, not with the seed. You can report it [here](https://github.com/angular/angular/issues).
