### ISSUE TITLE
Generic ServiceWorker support

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#375]
We already can [use ServiceWorkers](https://jakearchibald.github.io/isserviceworkerready/) in Chrome and Firefox.

We may include a generic implementation of a SW in the seed which implements basic caching for offline-first application support. Here is a [great post by Jake Archibald](https://jakearchibald.com/2014/offline-cookbook/) that we can keep in mind. Lets consider which strategy from the described suits best to the seed and discuss if there's a point to add ServiceWorker support at all.

**Comment by NathanWalker** [comment]
+1 on basic implementation with basic caching.

**Comment by mgechev** [comment]
Results from the poll I started on Twitter https://twitter.com/mgechev/status/686836778276372480
