### ISSUE TITLE
Something wrong on Windows 10

### ISSUE THREAD

**Issue by dracon** [mgechev/angular2-seed#377]
npm-debug after npm run reinstall:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\PATH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'reinstall' ]
2 info using npm@3.5.2
3 info using node@v5.4.0
4 verbose run-script [ 'prereinstall', 'reinstall', 'postreinstall' ]
5 info lifecycle angular2-seed@0.0.0~prereinstall: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prereinstall: no script for prereinstall, continuing
7 info lifecycle angular2-seed@0.0.0~reinstall: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~reinstall: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~reinstall: PATH: C:\PATH\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\PATH\PhpstormProjects\angular2-test\ng-quick-ts\angular2-seed\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Live\Shared;C:\development\sdk\platform-tools;C:\development\sdk\tools;C:\ant\bin\bin;C:\Program Files\Java\jdk1.8.0_25;C:\Program Files\Java\jdk1.8.0_25\bin;C:\Program Files (x86)\Git\bin;C:\server\php;C:\ProgramData\ComposerSetup\bin;C:\PATH\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\PATH\AppData\Local\Programs\Python\Python35-32;C:\Python25;C:\Program Files (x86)\Skype\Phone\;C:\WT-NMP\bin;C:\Program Files\nodejs\;C:\Ruby21-x64\bin;C:\Program Files (x86)\OpenVPN\bin;C:\Program Files (x86)\Git\bin;C:\PATH\AppData\Local\Android\android-sdk;C:\ant\bin;C:\PATH\AppData\Local\Android\android-sdk\platform-tools;C:\PATH\AppData\Local\Android\android-sdk\tools;C:\PATH\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom\;C:\Program Files (x86)\Notepad++;C:\bin;C:\PATH\AppData\Roaming\npm
10 verbose lifecycle angular2-seed@0.0.0~reinstall: CWD: C:\PATH\PhpstormProjects\angular2-test\ng-quick-ts\angular2-seed
11 silly lifecycle angular2-seed@0.0.0~reinstall: Args: [ '/d /s /c',
11 silly lifecycle   'rimraf node_modules && npm cache clean && npm install' ]
12 silly lifecycle angular2-seed@0.0.0~reinstall: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~reinstall: Failed to exec reinstall script
14 verbose stack Error: angular2-seed@0.0.0 reinstall: `rimraf node_modules && npm cache clean && npm install`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\PATH\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\PATH\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd C:\PATH\PhpstormProjects\angular2-test\ng-quick-ts\angular2-seed
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\PATH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "reinstall"
19 error node v5.4.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 reinstall: `rimraf node_modules && npm cache clean && npm install`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 reinstall script 'rimraf node_modules && npm cache clean && npm install'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rimraf node_modules && npm cache clean && npm install
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mgechev** [comment]
Here is similar issue https://github.com/mgechev/angular2-seed/issues/359

Would you try the same solution and let us know if it works.

**Comment by dracon** [comment]
@mgechev Thank you...
It worked for me with npm clean cache and npm install.

**Comment by LuxDie** [comment]
I have this problem right now and `npm cache clean` doesn't help. `npm reinstall` fails no matter what. I'm on Windows 10,
