### ISSUE TITLE
How to load templateUrl?

### ISSUE THREAD

**Issue by Sophia-nguyen** [mgechev/angular2-seed#378]
Hi,
I see `templateUrl: './components/about/about.html'`.
But when I run` serve-dev`, it load template with path `dist/dev/components/about/about.html`.
How can do it? I can't find config in this app.

I create new app, and try to run `serve-dev` but it don't work. If I define serve with `root: '.'` it will load `html` files with path `/components/about/about.html` , and if I define `root:'dist/'` it can't load `node-modules`. This is my app https://github.com/Sophia-nguyen/myApp

Please help me, thanks

**Comment by ludohenin** [comment]
This is because it's a relative template url and you're browsing `http://localhost:5555/dist/dev/`

**Comment by Sophia-nguyen** [comment]
@ludohenin, could you please guide me how to do relative template url ?
Thanks,

**Comment by mgechev** [comment]
@Sophia-nguyen take a look at [this SO answer](https://stackoverflow.com/questions/2005079/absolute-vs-relative-urls).

**Comment by Sophia-nguyen** [comment]
@mgechev more question,that mean I can use relative template url `http://localhost:5555/dist/dev/`, if I config server with `root: 'dist/dev/'`, but In this case, how to load all libs from `node-modules`.
I try to setup for my app, but it still don't work. It can't load libs in `node-modules`
Please help me.

**Comment by ludohenin** [comment]
The dev server is not design to work with any other root than the project root.

**Comment by Sophia-nguyen** [comment]
I'm clear, thanks @ludohenin :)
