### ISSUE TITLE
Proposal: 'organize by feature' instead of 'organize by type'

### ISSUE THREAD

**Issue by evanplaice** [mgechev/angular2-seed#379]
Take a look at:
https://egghead.io/lessons/angular-2-organizing-angular-2-projects-by-feature

## Proposal

*Organize angular2-seed by feature instead of type*

I know it's tempting to follow the structure traditionally used by MVC platforms (ie organization by type), especially on smaller projects. I'm arguing that component-based development is a different beast and there are advantages that come with abandoning the old model.

*Example: Organization by Type*
```
- components
  - HeaderComponent
  - MainComponent
  - MarkdownEditorComponent
  - MarkdownPreviewComponent
  - FooterComponent
  - SomeOtherComponent
- services
  - SomeOtherService
  - MarkdownService
- models
  - SomeOtherModel
  - MarkdownModel
- AppComponent
```

*Example: Organize by Feature:*
```
- main
  - components
    - HeaderComponent
    - MainComponent
    - FooterComponent
- markdown
  - components   
    - MarkdownEditorComponent
    - MarkdownPreviewComponent
  - models
    - MarkdownModel
  - services  
    - MarkdownService
- shared
  - components
    - SomeOtherComponent
  - services
    - SomeOtherService
  - models
    - SomeOtherModel
- AppComponent
```

*Propositions:*

*1. Organizing by feature promotes better reusability*

Lets say I'm building an interactive Markdown editor for a site. It requires one main component and a number of smaller subcomponents, a service, and a model. The functionality is feature-complete and a use case pops up where it would be desirable to use it on another project.

With a by-type structure, reuse would require manually extracting and copying the features over into the other project. Being careful to update all of the path references, so as not to break functionality.

With a by-feature structure, simply copy the entire feature directory over because it's completely self-contained. With relative paths, nothing should break.

To take things this approach one step further. If a feature is sufficiently decoupled from the app, it becomes trivial to host the feature in it's own repo so it can be versioned independently and installed via tools like JSPM.

I understand it may seem awkward at first for devs who are used to the traditional MVC structure. But, isn't reusability the primary factor behind the shift to web components?

*2. Organizing by feature makes it easier to reason about the code*

Splitting things up by type works very well for describing the usage on small/trivial demonstrations where a component, service, model, pipe are all conveniently given the same name.

As a project grows in scope to include many components, services, pipes, models, things will become more cumbersome to navigate. For example, a service may require one-or-more models that whose definitions some from outside sources. So, naming the model to match the service/component wouldn't work. Etc...

**Reasoning:**

Aside from any perceived axe-grinding/paintshedding, the only reason I bring this topic up is because many users new to ng2 view this project as a jump off point to get started. I think it would be beneficial for the community whole to promote 'organization by feature' as a 'best practice' from the start.

Rather than have users use the current model until it grows too cumbersome to manage. Then, either reorganize everything after-the-fact, or put up with an inefficient structure.

**Comment by NathanWalker** [comment]
I'd be happy to look at a PR?

**Comment by evanplaice** [comment]
@NathanWalker I think I can handle that. Just didn't want to waste the time doing the work if it doesn't follow the intent of the project.

**Comment by NathanWalker** [comment]
It is purposely minimal so I'm not sure there's enough here to warrant
organization by feature.

**Comment by evanplaice** [comment]
@NathanWalker If it's intended to be built upon and/or stand as an example of how a project should start. The size isn't really a relevant factor.

**Comment by BostjanPisler** [comment]
+1

**Comment by NathanWalker** [comment]
@evanplaice got tied up in work but thanks for this effort, much nicer and ready to scale!

**Comment by evanplaice** [comment]
@NathanWalker Thanks, the encouragement is much appreciated :+1:

**Comment by nareshbhatia** [comment]
@evanplaice, nice work!

One request: for those who like to keep sources and tests in separate folders, could you please add a little note as to how to achieve that? What tasks would be impacted?

**Comment by evanplaice** [comment]
@nareshbhatia Sure thing.

Since a feature is created a self-contained module of code you'd simply move the tests from the `components` folder into a `tests` folder. 

```
- feature
  - components
    - feature.ts
    - feature.html
  - models
    ...
  - services
    ...
  - pipes
    ...
  - tests
    - feature.spec
    - feature.e2e.ts
```

The tasks aren't impacted at all. You'll have to fix the path in the .spec file to point to the new location of the feature component. The e2e test uses a headless web browser to test the rendered output so the paths/structure is irrelevant.

**Comment by nareshbhatia** [comment]
Awesome! Thanks, @evanplaice.
