### ISSUE TITLE
npm run build.prod broken

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#383]
If I add `homeCmp` in `app.ts`
```typeScript
directives: [ROUTER_DIRECTIVES, HomeCmp]
```
and add home tag in `app.html`
```html
<section class="sample-app-content">
  <nav>
    <a [routerLink]="['/Home']">Home</a>
    <a [routerLink]="['/About']">About</a>
  </nav>

  <router-outlet></router-outlet>
  <home></home>
</section>
```

I get `﻿RangeError: Maximum call stack size exceeded` error when run production version of angular2-seed. It happens if I put any component into `app.html`. In my application it is `topBar` component.
<img width="1280" alt="screenshot 2016-01-14 23 31 05" src="https://cloud.githubusercontent.com/assets/273313/12336704/f895c64c-bb16-11e5-8fed-2d44960779e5.png">

**Comment by mgechev** [comment]
`HomeCmp` is already added in `@RouteConfig`, you don't have to add it in `directives`.

**Comment by tandu** [comment]
Yes, it solves the issue. Why it doesn't break in dev?

**Comment by tandu** [comment]
I have looked at my code, I don't have component being listed in routes and have this issue.

**Comment by tandu** [comment]
I have created new component `Cmp` and added it to angular2-seed. It breaks application in prod.
[angular2-seed.zip](https://github.com/mgechev/angular2-seed/files/90989/angular2-seed.zip)

**Comment by mgechev** [comment]
I'll take a look at this issue tomorrow.

**Comment by tandu** [comment]
Just in case it might matter - I'm testing it by running python server and then opening it in browser at `localhost:8000`:
```bash
cd dist/prod
python -m SimpleHTTPServer
```

**Comment by mgechev** [comment]
@tandu the issue seems fixed in this branch https://github.com/mgechev/angular2-seed/tree/prod-enhancements.
Let me know if it solves your issue.

**Comment by tandu** [comment]
I have checked, it works well, thank you.
