### ISSUE TITLE
question:  why is an iframe being generated

### ISSUE THREAD

**Issue by VictorEverett** [mgechev/angular2-seed#384]
I see in the generated html an iframe and the angular code is placed within the iframe.  why is the iframe being used?  if there an option to not use an iframe?  is this generated by gulp?  just  trying to understand.  thanks for your response

**Comment by ludohenin** [comment]
@VictorEverett I don't have any `iframe`

**Comment by VictorEverett** [comment]
thanks for working with me on this.  I can't imagine why whey I run the app I get an iframe yet when you run the app you don't.  why would you just close this?

**Comment by mgechev** [comment]
If you are using this project and you see an iframe then take a look at the browser extension's you've installed.

I closed the issue because it is not related to the angular2-seed.
