### ISSUE TITLE
Roll back to angular beta 0

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#389]
Can you roll back to beta 0 until this is fixed?
https://github.com/angular/angular/issues/6489
https://github.com/angular/angular/issues/6404

I have these exceptions in my application and if I set angular version to beta 0 it complains about hot-loader: `angular2-hot-loader@0.0.16 requires a peer of angular2@2.0.0-beta.1 but none was installed.`

**Comment by mgechev** [comment]
In order to fix it just use `angular2-hot-loader@0.0.15`.

**Comment by creat-or** [comment]
beta.2 has been released yesterday :)

**Comment by mgechev** [comment]
Yes, I'll upgrade today.
