### ISSUE TITLE
Sass task example breaks test task

### ISSUE THREAD

**Issue by LuxDie** [mgechev/angular2-seed#391]
Hi. After the last change in the example, where generated `css` files where moved from `APP_SRC` to `APP_DEST`, applying the example breaks tests. Tests use `gulp-inline-ng2-template` to read css from `APP_SRC`, so when it finds only `scss` files, it fails.
A simple change to make `gulp-inline-ng2-template` read from `APP_DEST` is not enough, because there is no guarantee that the tasks that generate `APP_DEST` will be run before the `test` task.
Adding `build.dev` to the beginning of the `test` task stack seems like overkill.
Also, `gulp-inline-ng2-template` has an option for jade templates, although is not working right now, and ludoheim is also planning on adding `css` preprocessing, so this could be solved from that front.
Still I wouldn't like having 2 preprocessors installed, 1 for the build task and 1 as a dependency of `gulp-inline-ng2-template`, leading to potentially having 2 different versions of it.

**Comment by mgechev** [comment]
Hey @LuxDie. You can solve this problem by including the sass preprocessing in the `build.test.ts`.

**Comment by mgechev** [comment]
@LuxDie here is a more detailed explanation of how you can do this:

```ts
// gulpfile.ts
// ...
// --------------
// Test.
gulp.task('test', done =>
  runSequence('clean.test',
              'tslint',
              'build.assets.test',
              'build.sass.test',
              'build.test',
              'karma.start',
              done));
// ...
```

```ts
// build.assets.test.ts
import {join} from 'path';
import {APP_SRC, TEST_DEST} from '../config';

export = function buildAssetsDev(gulp, plugins) {
  return function () {
    return gulp.src([
        join(APP_SRC, '**'),
        '!' + join(APP_SRC, '**', '*.ts')
      ])
      .pipe(gulp.dest(TEST_DEST));
  };
}
```
```ts
// build.sass.test.ts
import {join} from 'path';
import {APP_SRC, TEST_DEST} from '../config';

export = function buildSassDev(gulp, plugins, option) {
  return function () {
    return gulp.src(join(APP_SRC, '**', '*.scss'))
      .pipe(plugins.sass().on('error', plugins.sass.logError))
      .pipe(gulp.dest(TEST_DEST));
  };
}
```
```ts
// build.test.ts
import {join} from 'path';
import {APP_SRC, TEST_DEST} from '../config';
import {tsProjectFn} from '../utils';

export = function buildTest(gulp, plugins) {
  return function () {
    let tsProject = tsProjectFn(plugins);
    let src = [
                join(APP_SRC, '**/*.ts'),
                '!' + join(APP_SRC, 'bootstrap.ts')
              ];

    let result = gulp.src(src)
      .pipe(plugins.plumber())
      .pipe(plugins.inlineNg2Template({ base: TEST_DEST }))
      .pipe(plugins.typescript(tsProject));

    return result.js
      .pipe(gulp.dest(TEST_DEST));
  };
};
```

**Comment by LuxDie** [comment]
Cool! Thanks for the solution.

I'm confused about the `build.assets.test` task. Why are you copying the `ts` files? Maybe you copied the wrong code? I copied the actual `build.assets.dev` task and it worked.

I still feel this is kind of duplicating code. There should be a way to pass the destination directory to a single task instead of having 2 almost identical tasks.

By the way, it would be great if this solution could be documented somewhere.

**Comment by mgechev** [comment]
There's exclamation mark before the `.ts`, this is negation.

Yes, documenting it will be a good idea. I'll have working on a wiki page as a pending task in mind.

**Comment by LuxDie** [comment]
Great. I'd be glad to help, may you need it.

**Comment by dloomb** [comment]
I attempted to follow the above code snippets but was still unable to get it working. I see that the gulpfile has changed a bit since these snippets were written. Is it possible to get some updated ones? Possibly even added to the wiki?

**Comment by LuxDie** [comment]
I'm checking it out.

**Comment by dloomb** [comment]
Thank you. I spent most of yesterday trying to figure it out.

**Comment by LuxDie** [comment]
I couldn't find a solution.

Current situation is as follows:

1. There is no more `TEST_DEST`, since tests are now output to `APP_DEST`.
2. The `build.js.test.ts` task uses a [plugin](https://github.com/ludohenin/gulp-inline-ng2-template) to inline html and css into each component. I couldn't find a way to tell the plugin how to read the generated `.css` files from `APP_DEST`. The solution would be to output the generated `.css` files to `APP_SRC`, but I hate mixing source and generated files.
3. I was able to make tests work using the plugin's built-in support for preprocessors, but it requires changing the component's metadata `styleUrls` property's path extension from `.css` to `.scss`. This breaks the developer build, which doesn't inline the files. I'll keep trying to make this approach work.

**Comment by dloomb** [comment]
Yeah that all the stuff I ran into as well. Thanks for trying.

**Comment by LuxDie** [comment]
I went for the simplest solution and removed the inlining plugin, as well as unified dev, unit and e2e builds into one. According to #447's discussion there seems to be an interest in compiling one kind of test at a time in a given build. I can't see the merit of it, and unifying the builds eases a lot of complexities.

So this is my version with SASS compilation and builds working properly: https://github.com/LuxDie/angular2-seed-jade/tree/sass.

If there is consensus with this approach (@mgechev, @ludohenin, @nareshbhatia), I can make a pull request with the build changes.

**Comment by nareshbhatia** [comment]
I have a successful Sass build at https://github.com/archfirst/angular2-seed-sass, with all unit and e2e tests running properly. Also see my note at the end of this issue for the approach I took: https://github.com/ludohenin/gulp-inline-ng2-template/issues/11. Is this similar to your approach?

**Comment by LuxDie** [comment]
Yes I saw your build, you are generating the `.css` files inside the `src` directory. I don't like that, because it makes me really confused when I'm trying to edit css to have to think which of the 2 files I have to edit each time. I imagine it would be even worse if I were mixing `.css` and `.scss` files in the same project.

**Comment by nareshbhatia** [comment]
I too don't like mixing css and scss but trying to keep src directory pure was making the build deviate too much from angular2-seed and also very complex. So this was my compromise solution. Also I didn't find a reason for writing raw css when I was already using a preprocessor. In any case I will look at you approach hopefully tomorrow and provide comments.

**Comment by mgechev** [comment]
Any updates here?

**Comment by mgechev** [comment]
Sass is not officially supported by the seed so I think we can close this issue.

**Comment by LuxDie** [comment]
Alright, I'd suggest then changing the wiki example for adding a custom Gulp task to something simpler that doesn't break tests and production builds, or at the very least adding a warning about it.

**Comment by mgechev** [comment]
Yes, makes sense. If you have some spare time and idea for another gulp task you can edit the wiki page as well (I think it is open for everybody).

**Comment by LuxDie** [comment]
I updated the wiki example with the newest refactoring and the configuration suggested by nareshbhatia (generating the "css" files inside the "src" folder). It still requires a small tweak to a "seed task", but I guess it's close enough.

**Comment by nareshbhatia** [comment]
Just a quick note - the [angular2-seed-sass](https://github.com/archfirst/angular2-seed-sass) project has been fixed to not create `.css` files in the `src` folder. These files are now created in the `dist` folder. Thanks to @asgarddesigns for the fix.
