### ISSUE TITLE
Using 3rd party JavaScript libraries such as moment.js

### ISSUE THREAD

**Issue by nareshbhatia** [mgechev/angular2-seed#393]
I am completely new to TypeScript and angular2-seed. I see a number of references to using 3rd party libraries in angular2-seed but they all assume I know about things like `tsd` etc. Without this kind of background, I tried the following naive way, which obviously did not work:

    npm install moment --save

then added following line to `DEV_NPM_DEPENDENCIES` in config.ts

    { src: 'moment/moment.js', inject: true, dest: JS_DEST }

then included the following import in my `.ts` file:

    import {moment} from 'moment/moment';

Could someone please provide me the necessary background and/or step-by-step instructions to use 3rd party JS libraries with angular2-seed?

Thanks in advance for your time.

**Comment by mgechev** [comment]
Hey @nareshbhatia you can take a look at the explanation on how to include `angular2-jwt` in the project https://github.com/mgechev/angular2-seed/issues/392#issuecomment-172216617.

In short. You need the library:

```
npm install moment --save
```
After that you need the type definition:
```
tsd install moment --save
```
and at last, you need to include it in your project:
```
// Note that the package name might be different
import {moment} from 'moment/moment';
```

**Comment by nareshbhatia** [comment]
@mgechev, I tried your suggestion, but I am still getting:

    error TS2307: Cannot find module 'moment/moment'

I also tried changing my import to the following based on a stackoverflow question:

    import * as moment from "moment";

but I get the same error.

P.S. I took out the `src` line from DEV_NPM_DEPENDENCIES. Assuming that that is not needed.

**Comment by mgechev** [comment]
Did you use:

```
tsd install moment
```

This is required in order to make the type definitions visible to tsc.

Yes, the import is:

```ts
import * as moment from 'moment';
```

**Comment by nareshbhatia** [comment]
Yes, I did run

    tsd install moment --save

I have the correct import:

    import * as moment from 'moment';

But I am still getting the error.

Here is the output from `cd tools/typings/tsd && tree .` `moment` is there:

```
.
├── async
│   └── async.d.ts
├── browserify
│   └── browserify.d.ts
├── chalk
│   └── chalk.d.ts
├── del
│   └── del.d.ts
├── es6-promise
│   └── es6-promise.d.ts
├── express
│   └── express.d.ts
├── glob
│   └── glob.d.ts
├── gulp
│   └── gulp.d.ts
├── gulp-shell
│   └── gulp-shell.d.ts
├── gulp-util
│   └── gulp-util.d.ts
├── mime
│   └── mime.d.ts
├── minimatch
│   └── minimatch.d.ts
├── moment
│   ├── moment-node.d.ts
│   └── moment.d.ts
├── node
│   └── node.d.ts
├── orchestrator
│   └── orchestrator.d.ts
├── q
│   └── Q.d.ts
├── serve-static
│   └── serve-static.d.ts
├── systemjs
│   └── systemjs.d.ts
├── through2
│   └── through2.d.ts
├── tsd.d.ts
├── vinyl
│   └── vinyl.d.ts
└── vinyl-source-stream
    └── vinyl-source-stream.d.ts
```

Also I see that `tsd.json` now contains:

```
    "moment/moment.d.ts": {
      "commit": "93bae1bb4c887c1375a4c1f0c3bb849ff06b8ac6"
    },
    "moment/moment-node.d.ts": {
      "commit": "93bae1bb4c887c1375a4c1f0c3bb849ff06b8ac6"
    }
```

**Comment by mgechev** [comment]
Okay, I see. You can fix this by:

1. Create a file in `app` called `typings.d.ts`.
2. As content of the file add `/// <reference path="../tools/typings/tsd/moment/moment.d.ts"/>`

This should fix your issue.

**Comment by nareshbhatia** [comment]
That indeed fixes the problem! Can you please explain what this is doing? I could not find a reference to `typings.d.ts` anywhere. Is this a magic file?

**Comment by mgechev** [comment]
Take a look at the `build.js.dev.ts` [task](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.js.dev.ts#L8-L11). It searches the entire `app` directory for type definitions (not `tools/typings`). We added `typings.d.ts` to this directory which made the typing visible to the compiler.

Do not include `tools/typings` because you'll get plenty of duplicate definitions.

**Comment by nareshbhatia** [comment]
Got it! Thanks a lot for your help on this.
