### ISSUE TITLE
prod build behaves differently in windows & unix environments - wrong injectables

### ISSUE THREAD

**Issue by koodikindral** [mgechev/angular2-seed#394]
npm run build.prod:

*unix:*

/dist/prod/index.html:

    
    <script src="js/shims.js"></script>
    <script src="js/app.js"></script>
    

*windows:*

/dist/prod/index.html:

    
    <script src="/dist/prod/js/shims.js"></script>
    <script src="/dist/prod/js/app.js"></script>
    

Same goes for the CSS

**Comment by koodikindral** [comment]
Here is the problem:

*tools/tasks/build.index.prod.ts:*

    transform: function (filepath) {
        let path = filepath.split(sep);
        arguments[0] = path.slice(path.length - 2, path.length).join(sep);
        return plugins.inject.transform.apply(plugins.inject.transform, arguments);
    }

sep in windows environment: \
sep in unix: /

**Comment by mgechev** [comment]
Thanks for the PR!
