### ISSUE TITLE
Add wiki page

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#397]
It will be extremely useful if we include a wiki page with examples:

- How to add a third party library to the seed:
   - Installing the module
   - Adding the type definitions (external via tsd and distributed with the package)
   - Referencing the module inside of any of the project files
- Extending the build with a custom task (for instance adding SASS support, which is almost completely described by https://github.com/mgechev/angular2-seed#adding-custom-gulp-task and in https://github.com/mgechev/angular2-seed/issues/391)

Help will be greatly appreciated!

**Comment by NathanWalker** [comment]
great idea +1 ... I'll help soon!

**Comment by mgechev** [comment]
Done! Here's the basic [wiki page](https://github.com/mgechev/angular2-seed/wiki).
