### ISSUE TITLE
Advanced project seed - extended option to angular2-seed

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#398]
Over the next couple weeks, I'm thinking about expanding a fork of this seed to represent a more advanced seed. It will remain a fork (or branch here) so improvements to the build can always be merged into it. It will not change anything about the setup, but rather expand it to become a more sophisticated setup for a larger project. Curious what everyone believes would represent a nice advanced seed.
My thoughts for example:
- lodash
- ng2-translate for i18n
- provider for LocalStorage (abstraction for IndexedDB, WebSQL, localStorage, perhaps a port of localForage)
- https://github.com/ngrx/store for state management (Redux inspired)
- more sophisticated setup for Service Worker
- including `angular cli` to help in component, service, pipe creation, etc. (it would `not` use it for the build, only for certain features)
- potentially an out of the box setup which can bootstrap for NativeScript (when targeting native apps) and the web all working off same codebase.
- Electron setup to optionally bootstrap for cross platform desktop applications.

...add to list for anything you'd like to see.

Also, would you like to see this as a branch inside this repo? Or as a separate repo?
Either way, the advanced seed will remain a fork of this seed so any improvements to the build can be easily merged.

**Comment by mgechev** [comment]
The project sounds fun to me. I think if it is a separate repository it'll be more discoverable. What do you think?

**Comment by Bigous** [comment]
I like the Idea, but why not having all of it inside this seed on master? I already consider this seed "advanced" specially if you compare with any other angular2 seed :D

**Comment by NathanWalker** [comment]
@Bigous Yes indeed this is a great seed and certainly is `advanced` as far as most projects go.
What I'm aiming for with a more advanced seed is to expand what's already great about this seed into a setup with quite a deeper level of sophistication supporting targeting cross platform native mobile apps with NativeScript as well as cross platform native desktop applications with Electron. It would also include more core utilities often used in very large sophisticated applications.

@mgechev I'm thinking I will make a separate repo which will remain a fork of this so it's build system can stay up to date with latest upstream changes.

**Comment by ludohenin** [comment]
@NathanWalker sounds great.

**Comment by mgechev** [comment]
@NathanWalker sounds good to me. Keep me up-to-date, I'd love to follow your progress! :-)
