### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by johnjelinek** [mgechev/angular2-seed#4]
Could you create a branch or upgrade to a scenario where there's a typescript transpiling build step and you can drop the dependency on traceur.

**Comment by mgechev** [comment]
Yes, this is planned for my weekend :-)

**Comment by johnjelinek** [comment]
:+1:

**Comment by ludohenin** [comment]
Cool.
They seems to have a pretty decent angular2.d.ts file here [ttps://github.com/angular-class/angular2-webpack-starter...](https://github.com/angular-class/angular2-webpack-starter/blob/master/typings/angular2/angular2.d.ts)

**Comment by johnjelinek** [comment]
:+1:

**Comment by mgechev** [comment]
`gulp-typescript` still uses TypeScript 1.4.x. I'll wait a few days until 1.5 is officially released. For now traceur works perfectly.

**Comment by johnjelinek** [comment]
I don't think you need `gulp-traceur` at all if you're using typescript.
Just run `tsc` as a postinstall script with npm. It'll read your tsconfig
for the output directory.

**Comment by mgechev** [comment]
Yes, you're correct, I don't need it. However, my point is that I want a consistent build configuration.

**Comment by johnjelinek** [comment]
I don't understand. Why would you lose your build configuration by removing traceur?



—

**Comment by mgechev** [comment]
I won't use it, I will make it inconsistent. Right now the project uses gulp for:
- Building Angular
- Structuring the project by moving the required libraries
- Starting static HTTP server
- Watching the dev files, building them and outputting them in the `dev` directory.

However, by introducing `tsc` there will be one more tool, which won't have (not-hacky) integration with `gulp`. Workaround could be to use `gulp-shell` for running `tsc`.

**Comment by johnjelinek** [comment]
I think gulp-shell sounds good. I think a successful typescript conversion
will show that typescript is no longer necessary.

**Comment by johnjelinek** [comment]
Sorry, traceur* is no longer necessary

**Comment by ludohenin** [comment]
[gulp-typescript](https://www.npmjs.com/package/gulp-typescript) does the job very nicely.

**Comment by mgechev** [comment]
`gulp-typescript` has as dependency TypeScript 1.4.x, which means that it doesn't support a [lot of features](https://github.com/Microsoft/TypeScript/wiki/Roadmap#15) used by Angular.

Do you have a working example with `gulp-typescript`?

**Comment by ludohenin** [comment]
I have a working example (but not online yet unfortunately). In fact you can specify which version of typescript you want to use in the config passed to `gulp-typescript` by doing so 

```javascript
// ...
var tsProject = ts.createProject('tsconfig.json', {
    typescript: require("typescript") // <-- installed locally with version 1.5.0-beta or Microsoft/TypeScript
});
gulp.task('ts', ['clean:js'], function () {
    var result = gulp.src(PATH.ts.src)
        .pipe(plumber())
        .pipe(ts(tsProject));

    return result.js.pipe(gulp.dest(PATH.ts.dest));
});
```

**Comment by ludohenin** [comment]
With typescript you can then write things like that
```javascript
import {Component} from 'angular2/angular2';
```
no need to go the indirect way anymore.

**Comment by mgechev** [comment]
@ludohenin sounds great! I'm going to try this tomorrow!

**Comment by ludohenin** [comment]
I started from here [https://github.com/rkirov/ng2-ts-hello](https://github.com/rkirov/ng2-ts-hello) but the angular build is not good in my opinion, not the apha.23 but rather a custom build from github (directives are in the form of `NgIf` for instance, not `If`)

**Comment by mgechev** [comment]
@ludohenin btw, if you have some time you can change the `gulpfile.js` and make a pull request, otherwise I'll fix this tomorrow.

**Comment by ludohenin** [comment]
never done that but I'll try ... glab to contribute :-)

**Comment by ludohenin** [comment]
PR sent and ready to be merged.

**Comment by mgechev** [comment]
Awesome! I'll merge it tomorrow morning, it is a bit late here already.
Thanks!

**Comment by mgechev** [comment]
#7

**Comment by mgechev** [comment]
#9 fix this
