### ISSUE TITLE
loading all angular2 js separated

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#400]
I broke this issue out of a compounded issue here:
https://github.com/mgechev/angular2-seed/issues/399 ... which I renamed to his other issue.

As @gustavolira mentions...

> Today I did a pull at project and now I all angular2 js is loading separeted taking much more time to finish to load the page. 
> [omitted]
> There's some way to load only angular2 bundle js instead of separeted?

I have also seen this in the latest changes and not sure why every single little .js file is now loading separately. It makes development much slower as the page load to refresh is now painfully slow. :(

**Comment by mgechev** [comment]
The issue should be fixed in this branch https://github.com/mgechev/angular2-seed/tree/fix-400

@NathanWalker would you verify and merge?

**Comment by NathanWalker** [comment]
IE issue with beta.1 :(
https://github.com/angular/angular/issues/6501

**Comment by gustavolira** [comment]
beta.2 released!
Now is possible!!

**Comment by mgechev** [comment]
Fixed in https://github.com/mgechev/angular2-seed/pull/420.
