### ISSUE TITLE
Doesn't work in Internet Explorer 11

### ISSUE THREAD

**Issue by zachallen** [mgechev/angular2-seed#402]
Cloned the repo today, ran `npm install` and `npm start`. The server starts up fine but the page doesn't render in Internet Explorer 11 (The page just shows Loading...). Console shows:
> EXCEPTION: SyntaxError: The use of a keyword for an identifier is invalid
>    EXCEPTION: SyntaxError: The use of a keyword for an identifier is invalid
>    STACKTRACE:
>    SyntaxError: The use of a keyword for an identifier is invalid
>    at evalExpression (http://localhost:5555/node_modules/angular2/bundles/angular2.js:452:5)
>    at TemplateCompiler.prototype._createViewFactoryRuntime (http://localhost:5555/node_modules/angular2/bundles/angular2.js:23969:9)
>    at Anonymous function (http://localhost:5555/node_modules/angular2/bundles/angular2.js:23924:13)
>    at run (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:138:7)
>    at Anonymous function (http://localhost:5555/node_modules/angular2/bundles/angular2.js:13247:15)
>    at zoneBoundFn (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:111:7)
>    at lib$es6$promise$$internal$$tryCatch (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:1511:9)
>    at lib$es6$promise$$internal$$invokeCallback (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:1523:9)
>    at Anonymous function (http://localhost:5555/node_modules/angular2/bundles/angular2-

**Comment by mgechev** [comment]
Everything should work now.
