### ISSUE TITLE
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

### ISSUE THREAD

**Issue by redaikidoka** [mgechev/angular2-seed#405]

**Comment by mgechev** [comment]
We can't do much here. The warning comes from old version of `glob-watcher` which comes as dependency of `vinyl-fs`.

**Comment by tarlepp** [comment]
@redaikidoka create an PR to that repo that is using old version of lo-dash. That should help with this one.
