### ISSUE TITLE
3rd party dependencies not found

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#409]
Hi,
If you do:
```npm install angular2-jwt --save```
And them add in config.ts at DEV_NPM_DEPENDENCIES:
{ src: 'angular2-jwt/angular2-jwt.js', inject: true, dest: JS_DEST }

And them import angular2-jwt at some component like:
import {tokenNotExpired} from 'angular2-jwt/angular2-jwt';

You will receive ``` http://localhost:5555/dist/dev/angular2-jwt/angular2-jwt.js 404 Not Found```

**Comment by mgechev** [comment]
@gustavolira take a look at [this issue](https://github.com/mgechev/angular2-seed/issues/392).
