### ISSUE TITLE
upgrade `tsd` to use `typings`

### ISSUE THREAD

**Issue by gdi2290** [mgechev/angular2-seed#410]
see https://github.com/angular/answers-app/pull/27/files and https://github.com/angular/universal-starter/commit/cfb7b52b12e1da9de7ee7c2a452e7636c93aaa09
```
$ npm uninstall tsd
$ rm -rf typings
$ npm install typings
$ typings init --upgrade
$ rm tsd.json
$ typings install
```
For the differences between `tsd` and `typings` see https://github.com/typings/typings/issues/72

**Comment by NathanWalker** [comment]
Thanks @gdi2290 I'll take care of this tomorrow!

**Comment by NathanWalker** [comment]
https://github.com/mgechev/angular2-seed/pull/411

Please see comments there ^, @gdi2290 I need your help to finalize.

**Comment by mgechev** [comment]
Closed by https://github.com/mgechev/angular2-seed/pull/411.
