### ISSUE TITLE
Failed to build prod version

### ISSUE THREAD

**Issue by fellz** [mgechev/angular2-seed#413]
Hi
I run into issue with building production bundle, so here is command in console

``` npm run build.prod ```

then i have this index.html in dest/prod

https://gist.github.com/fellz/44950e7628430022327d

what prod file should look like ? 1 css file and 1 js file + System.js config in <script> section ?

**Comment by mgechev** [comment]
I can't reproduce it. When I run `npm run build.prod` in `dist/prod` I have:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My Angular2 App</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- inject:css -->
  <link rel="stylesheet" href="css/all.css">
  <!-- endinject -->
</head>
<body>

  <app>Loading...</app>

  <!-- shims:js -->
  <!-- endinject -->

  <!-- libs:js -->
  <!-- endinject -->

  <!-- inject:js -->
  <script src="js/shims.js"></script>
  <script src="js/app.js"></script>
  <!-- endinject -->

  

</body>
</html>
```

**Comment by fellz** [comment]
Ok you can try my build here https://github.com/fellz/Angular-seed-app
