### ISSUE TITLE
Update requirements and setup to use Node >=5.4.1 <6 and npm >=3.5.3 <4.0?

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#414]
Now that the angular repo has updated to the latest node/npm, should we update this seed as well just to advance in that direction?
https://github.com/angular/angular/blob/master/DEVELOPER.md

**Comment by mgechev** [comment]
We're not dependent on the Angular's build process so I think we're good.

**Comment by Bigous** [comment]
I think we should keep with LTS too..

**Comment by NathanWalker** [comment]
:+1:
