### ISSUE TITLE
Is it possible to build index.html and copy outside of dist/dev 

### ISSUE THREAD

**Issue by ahmad2x4** [mgechev/angular2-seed#415]
I want to use `<app></app>` in any html  in website outside of dist/[env]:
When you build index.html all js and shims are referenced with {APP_BASE} path which is great.
But if you try to build and copy index.html to other directories (let say root), you would get 404 for loading app.html (this is used in templateURL)
Is there any way to replace ./app paths for templateURLs either in build tasks or using systemJS to use {APP_DEST}/app instead of ./app?

**Comment by ahmad2x4** [comment]
Found an awesome post in [reddit](https://www.reddit.com/r/Angular2/comments/3ylt5b/angular2_relative_paths_for_templateurl_and/) basically it referees to [CommonJS module format in SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#commonjs)
If we mention `moduleId = module.id` [ComponentMetadata](https://angular.io/docs/ts/latest/api/core/ComponentMetadata-class.html) we dont need to use relative path. basically `@Component` will be like following code

``` Typescript
@Component({
  moduleId: module.id,
  selector: 'app',
  viewProviders: [NameList],
  templateUrl: 'app.html',
  styleUrls: ['app.css'],
  encapsulation: ViewEncapsulation.None,
  directives: [ROUTER_DIRECTIVES]
})
```

I am not sure if you are happy for this change if I send a pull request

**Comment by ludohenin** [comment]
@ahmad2x4 there might be an issue with the hot loader and relative path. I guess @mgechev will confirm.

**Comment by ahmad2x4** [comment]
@ludohenin Yeah.  build.dev is OK but it seems build.prod does not like this approach. gulp-inline-ng2-template looks for html file in root

**Comment by ahmad2x4** [comment]
@ludohenin  to make gulp-inline-ng2-template happy I just needed to pass useRelativePaths: true and update to version 0.0.10.

**Comment by mgechev** [comment]
@ahmad2x4 you can run:

```bash
npm run build.prod
```

The content of `dist/prod` is self contained so you can move it wherever you want.
