### ISSUE TITLE
Preview of angular2-seed-advanced (Compliment to this seed) - built-in support for i18n, lodash, and many more coming...

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#416]
For those that want to see the beginnings of a relatively sophisticated setup which expands on this excellent seed:
https://github.com/NathanWalker/angular2-seed-advanced

- Full i18n support using [ng2-translate](https://github.com/ocombe/ng2-translate) implemented as well as integration with `lodash`.
- Examples of creating custom decorators for your components to reuse common setups.
- You can switch between 5 different languages (all configurable) at the moment, `English, Spanish, French, Russian, Bulgarian` :+1: 
- The underpinnings of the architecture will provide an easily scalable codebase to many different platforms.
- Much more coming.

Please let me know initial thoughts.

/cc @mgechev @ludohenin @ocombe @gdi2290

**Comment by ocombe** [comment]
Nice ! I'll take a look at it tonight ! (even if I prefer webpack :P)

**Comment by ludohenin** [comment]
This is going to be cool :)

**Comment by Bigous** [comment]
Really good Work Nathan.

**Comment by mgechev** [comment]
Sounds great! Looking forward for testing it!
