### ISSUE TITLE
launch.json for vscode

### ISSUE THREAD

**Issue by malfborger** [mgechev/angular2-seed#417]
If you'd like to debug in vscode debugger is it possible together w/ gulp? I've tried to setup a launch config like this 
`{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "app/main.ts",
			"stopOnEntry": false,
			"args": [],
			"cwd": ".",
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
            "preLaunchTask": "",
            "sourceMaps": true,
            "outDir": "dist/dev"
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858
		}
	]
}`

but I get stuck at 
`angular2-seed/node_modules/angular2/src/core/util/decorators.js:161
    throw 'reflect-metadata shim is required when using class decorators';
    ^
reflect-metadata shim is required when using class decorators`

**Comment by ludohenin** [comment]
@malfborger Do you want to debug the ng2 app or the build tools ?

**Comment by malfborger** [comment]
the whole ng2 app! @ludohenin

**Comment by Bigous** [comment]
I'm assuming you are trying to debug the final app and not the build... if that is the case, VSCode does not provide integration with Chrome out of the box. [There is an extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) to do this job...  but I have never used it... So I cannot tell if it works...

**Comment by malfborger** [comment]
I'm trying to debug the current build, are you guys doing it in dev tools instead?

**Comment by ludohenin** [comment]
@malfborger yes that's what I do, and use vscode debugger for node applications.

**Comment by Bigous** [comment]
Me too... just press F12 inside chrome and be happy ;)

**Comment by malfborger** [comment]
hehe ok, I'll start w/ that :) Thanks for quick answers, close it :)

**Comment by piyushchauhan2011** [comment]
Any help here ? How to debug with vscode @malfborger

**Comment by ludohenin** [comment]
with vscode you can debug server side but not client side app

**Comment by piyushchauhan2011** [comment]
I watched this video and trying to figure out the workflow https://www.youtube.com/watch?v=E9ixpuLTUUk @ludohenin
