### ISSUE TITLE
what's the seed's nodejs version NO？does those ERR effect ?

### ISSUE THREAD

**Issue by RunningV** [mgechev/angular2-seed#419]
npm ERR! node v4.2.0
npm ERR! npm  v2.14.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2-ext@0.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2-ext@0.1.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2-ext
npm ERR! There is likely additional logging output above.

**Comment by mgechev** [comment]
Problem in phantomjs2-ex as npm states? It is not issue related to the seed.
