### ISSUE TITLE
Additional modules failing to load

### ISSUE THREAD

**Issue by brian428** [mgechev/angular2-seed#423]
Since work on the beta2 branch is in progress, you may be aware of this. But if I include an additional npm dependency (say, for ng2-bootstrap), at runtime the path used to load to this file is incorrect. Instead of looking under node_modules (as it used to), it tries to find it under /dist. I removed the packages block from config.ts and added back in the paths block, and it seems to work again.

Just wanted to mention it in case it's an unintended side effect of the recent changes.

**Comment by mgechev** [comment]
Good point!
