### ISSUE TITLE
Running dev builds from '/' instead of '/dev/dist'

### ISSUE THREAD

**Issue by nareshbhatia** [mgechev/angular2-seed#425]
Just trying to understand why dev build is designed to run from `/dev/dist`. I am guessing it's to allow getting node modules from `/node_modules`. Curious if we could run the server with 2 base directories instead: `/dev/dist` *and* `/node_modules`.

The reason I ask is that I am trying to run with `PathLocationStrategy` and I had to hard code `<base href="/dist/dev/">` in `index.html` to make this work. Ideally I would like this to simply be `<base href="/">`.

One more newbie question: have you considered running the builds with [BrowserSync](https://www.browsersync.io/) or [lite-server](https://github.com/johnpapa/lite-server)? Both allow the use of multiple base directories quite easily? Do you see any major gotcha's in moving to these?

**Comment by NathanWalker** [comment]
Agreed. I believe this does need to change. Using `PathLocationStrategy` must be easy and ready to change from `HashLocationStrategy` out of the box. +1
I'll leave to @mgechev @ludohenin @tarlepp  for best way forward here.

**Comment by Bigous** [comment]
+1

**Comment by mgechev** [comment]
BrowserSync seems like a good idea to me. I can take care of this during the weekend. If anybody wants to help with the migration from express to BrowserSync - PRs are greatly appreciated!

**Comment by ludohenin** [comment]
+1 for BrowserSync.
@mgechev will see if I can come up with something before the week-end :)

**Comment by Bigous** [comment]
The only problem with BrowserSync is that it's compiled... and on Windows it can be a pain...

**Comment by nareshbhatia** [comment]
Not a Windows user, so don't have any experience there. I did find [this note](https://www.browsersync.io/docs/#windows-users) on the BrowserSync site, does that help reduce the pain? Otherwise, I have found BrowserSync to be an immensely useful out-of-the-box solution for app development.

**Comment by Bigous** [comment]
Yes, the pain is that people on Windows usually doesn't have the Visual Studio or python installed to build C++ programs. Specially if they doesn't write code in C/C++.
This is one reason way many projects (like [phamtonjs](http://phantomjs.org/)) went to a solution of having the binary itself ready to download and use as a fallback to the compilation process.
There is the [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) project that aims to do exactly that (act before node-gyp and look for a binary version compatible with your environment to download - if it exists, download and bypass node-gyp, if not, run node-gyp do build the binary).
Other projects (like oracle's [node_oracledb](https://github.com/oracle/node-oracledb/issues/18)) are actively discussing how to avoid this problem.
Using BrowserSync is good, but if we go into it, the usage of this seed will have more steps, not only a single npm install...

**Comment by nareshbhatia** [comment]
Do you know of other solutions that are less painful on Windows? For example, [live-server](https://github.com/tapio/live-server) or [http-server](https://github.com/indexzero/http-server). The fallback, of course, is express with multiple base directories. I just try to not reinvent the wheel :-).

**Comment by Bigous** [comment]
I use them both, live-server and http-server... to test the production build at this seed I use http-server installed globally. To me BrowserSync is not a problem as well, as I'm a C/C++ developer :D. My concern is about common windows web developers...

**Comment by ludohenin** [comment]
So BrowserSync doesn't seem to be such a good idea. 
I'm pretty sure we can find a way make the `LocationStrategy` configurable.
We basically have those 2 providers set:
```es6
// For PathLocationStrategy
const PROVIDERS = [
  provide(APP_BASE_HREF, { useValue: <%= APP_ROOT %> }),
  provide(LocationStrategy, { useClass: PathLocationStrategy })
];

// For HashLocationStrategy
const PROVIDERS = [
  provide(LocationStrategy, { useClass: HashLocationStrategy })
];
```
There's no need to set the `base` element.
What do you think ?

**Comment by Bigous** [comment]
@ludohenin Just an add, PathLocationStrategy is the default strategy, so, we can just do:
```typescript
// For PathLocationStrategy
const PROVIDERS = [
  provide(APP_BASE_HREF, { useValue: '<%= APP_ROOT %>' })
];
```
It will start the app normally, but at `/dist/dev/`... to achieve the goal of the issue, we will need to set `/` to `./dist/dev` in express and add `node_modules` route to `./node_modules` in dev environment.

**Comment by Bigous** [comment]
Ok, I looked deeper into `browser-sync`... it's not compiled... `utf-8-validate` and `bufferutil` which are subdependencies of it are. But they both have pure javascript fallback (they will still emit errors during npm install on windows without python or visual studio, but it will work).
If you choose to use it, windows people won't get hurt :D

**Comment by mgechev** [comment]
Currently Windows people get hurt by the [`ws`](https://www.npmjs.com/package/ws) dependency of the `angular2-hot-loader`.

**Comment by ojacquemart** [comment]
+1 for browsersync.

Maybe, it could be an another issue but it would be great to provide css injection in order to avoid a full page reload while changing a single line of css. WDYT? I could try to work on it if you want?

**Comment by mgechev** [comment]
BrowserSync with CSS injection sounds good to me. @ojacquemart it'll be great if you can help with this feature.

**Comment by ojacquemart** [comment]
Still in draft https://github.com/ojacquemart/angular2-seed/commit/465156079a997336993a4865648188592d4176f6 but a working brower-sync integration.

**Comment by mgechev** [comment]
@ojacquemart looks awesome, great job!

You won't need this workaround if you update the SystemJS config to:

```ts
// ----------------
// SystemsJS Configuration.
const SYSTEM_CONFIG_DEV = {
  defaultJSExtensions: true,
  paths: {
    [BOOTSTRAP_MODULE]: `${APP_BASE}${BOOTSTRAP_MODULE}`,
    'hot_loader_main': `${APP_BASE}hot_loader_main`,
    'angular2/*': `${APP_BASE}angular2/*`,
    'rxjs/*': `${APP_BASE}rxjs/*`,
    '*': `${APP_BASE}node_modules/*`
  },
  packages: {
    angular2: { defaultExtension: false },
    rxjs: { defaultExtension: false }
  }
};
```

**Comment by mgechev** [comment]
Just FYI https://github.com/BrowserSync/browser-sync-client/issues/32#issuecomment-179761912.

**Comment by ojacquemart** [comment]
Thanks, it's ok with the right systemjs config :)
Do you think it is good for a PR while waiting for the new browser-sync version?

I am working on the css injection and have an issue with the styleUrls attribute used on components. Angular injects the css in the head as style elements. It works in the other cases.

**Comment by mgechev** [comment]
I think we can merge even before the official Angular 2 support if we don't officially announces that we are using browser-sync. This way the introduced change be transparent for the users of the seed and once A2 is officially supported the cross-device livereload will come for free.

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/commit/6af7e020ae33cdbea56da25a5cd88508df0c8147. Thanks to @ojacquemart!
