### ISSUE TITLE
IE11 console error

### ISSUE THREAD

**Issue by allenhwkim** [mgechev/angular2-seed#427]
Seeing errors of SCRIPT5007: Unable to get property 'prototype' of undefined or null reference

![image](https://cloud.githubusercontent.com/assets/1437734/12758357/d23ce3a8-c9a9-11e5-9a51-9ca04b102051.png)

![image](https://cloud.githubusercontent.com/assets/1437734/12758391/f20ac524-c9a9-11e5-9979-523c46ed25fa.png)

My guess is there is some error related to System JS polliyfill.

**Comment by mgechev** [comment]
I can't reproduce your issue :-/

**Comment by allenhwkim** [comment]
Don't have IE11 or have IE11 and works fine for you?

**Comment by mgechev** [comment]
@allenhwkim would you test against master in order to verify whether the latest changes fix the issue? For me the seed didn't work on IE11 but I got different error.

**Comment by allenhwkim** [comment]
Thanks, verifying with the latest changes ...

**Comment by mgechev** [comment]
@allenhwkim awesome! Let me know how it goes!

**Comment by allenhwkim** [comment]
This is the result from my screen.
![image](https://cloud.githubusercontent.com/assets/1437734/12786656/0bf3aad0-ca60-11e5-8874-1074693cc594.png)

**Comment by mgechev** [comment]
Yep, thats it!

**Comment by allenhwkim** [comment]
Thank you very much @mgechev
