### ISSUE TITLE
Possible problem with default tsconfig.json

### ISSUE THREAD

**Issue by brian428** [mgechev/angular2-seed#428]
I notice that the most recent beta2 build changed the tsconfig.json from this:
```
"exclude": [
    "node_modules"
]
```

to this:

```
"files": [
    "typings/main.d.ts",
    "app/main.ts"
]
```

This seems to introduce issues in IDEA (which understands tsconfig.json). Namely, files in the app/ folder are flagged as not found (the actual error is that they're not present in tsconfig.json). Switching it back to the exclude syntax solves the problem, since that's including everything except node_modules.

Just curious if there was a reason for this change, and to let you know about this location issue in case you want to switch it back.

**Comment by mgechev** [comment]
@brian428 thats a good point again. This issue should be fixed now.
