### ISSUE TITLE
How import rxjs extensions?

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#429]
Rx import for operators worked that way:
```typeScript
import {Component} from 'angular2/core';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map.js'; // Error: Doesn't work

@Component({
  selector: 'home',
  templateUrl: './home/components/home.html',
  styleUrls: ['./home/components/home.css']
})
export class HomeCmp {
  constructor() {
    let a = new Observable();
    a.map(d=>d);
  }
}
```

and now when I updated to latest angular seed version I get this error:
```
Error: XHR error (404 Not Found) loading http://localhost:5555/dist/dev/rxjs/add/operator/map.js
	Error loading http://localhost:5555/dist/dev/rxjs/add/operator/map.js as "rxjs/add/operator/map.js" from http://localhost:5555/dist/dev/home/components/home.js
```

**Comment by mgechev** [comment]
Remove the `.js` extension from the import.

It should be:

```ts
import 'rxjs/add/operator/map';
```

**Comment by tandu** [comment]
Tried import without js, it doesn't work.

**Comment by mgechev** [comment]
What error do you get? Are you using the latest version of the seed?

**Comment by tandu** [comment]
I'm using the latest version - updated about an hour ago. Before I was using version about 2 weeks old.
<img width="940" alt="screenshot 2016-02-03 13 55 12" src="https://cloud.githubusercontent.com/assets/273313/12780238/cc41511c-ca7d-11e5-9227-a084b0439de2.png">

**Comment by tandu** [comment]
You should be able to see that error if replace home.ts with this code in angular seed.
```typeScript
import {Component} from 'angular2/core';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';

@Component({
  selector: 'home',
  templateUrl: './home/components/home.html',
  styleUrls: ['./home/components/home.css']
})
export class HomeCmp {
  constructor() {
    let a = new Observable();
    a.map(d=> d);
  }
}
```

**Comment by mgechev** [comment]
@tandu thanks! I'll take a look and let you know what I find.

**Comment by mgechev** [comment]
@tandu thats weird but I still can't manage to reproduce the issue. I tried both in Chrome and FF. I also removed the import so the `map` method wasn't added to the `Observable`'s prototype.

**Comment by tandu** [comment]
Hm, I tried clean version of angular seed with the only change in home.ts. I will only get back to my pc in 4-5 hours. I will test it in other browsers and let you know.

**Comment by tandu** [comment]
I have double checked. The problem was that I first did similar changes in about.ts and for the simplicity I have moved logic to home.ts as it has less code and removed them from about.ts but forgot to save them on disk. So your suggestion to remove `.ts` is correct. Sorry for inconvenience. You can close the issue.
