### ISSUE TITLE
how can i add a task to compass the lib

### ISSUE THREAD

**Issue by axetroy** [mgechev/angular2-seed#430]
when I build a project.
run the cmd
```
npm run build.prod
```
it will generate the folder "dist"
but the lib folder was not compass together

when we want to public this app
we want compass it to reduce the request not requre the lib one by one.

so how do i add a gulp task to compass this?

sorry,I don't good at gulp.

i wish the auth make a thinking for about this
i think it's nesscessry.

thansk

**Comment by mgechev** [comment]
You can use something like [gulp-compass](https://www.npmjs.com/package/gulp-compass). There's guide how to integrate `gulp-sass` with the seed project, doing the same for `gulp-compass` should be quite similar.
