### ISSUE TITLE
Problem updating SystemJS to 0.19.18

### ISSUE THREAD

**Issue by jmcota** [mgechev/angular2-seed#431]
System.config (index.html) is not working anymore using SystemJS v 0.19.18 for dev/prod.

If I downgrade to SystemJS v.019.17 it's still working.

**Comment by jesperronn** [comment]
Please describe more the error you see (stacktrace, etc). Can you run the tests?

**Comment by mgechev** [comment]
@jmcota would you test against this branch https://github.com/mgechev/angular2-seed/tree/systemjs ?

If your issue is fixed and you don't have any other problems with the introduced changes we'll merge to master.

**Comment by mgechev** [comment]
Closed by https://github.com/mgechev/angular2-seed/pull/436.
