### ISSUE TITLE
Can't include gulp-sass.

### ISSUE THREAD

**Issue by nitinkumarmishra** [mgechev/angular2-seed#432]
Hi, thanks for this wonderful seed project. I just wanted to know the proper way to import `gulp-sass` into my project. I'm planning on using it with bootstrap. I tried installing gulp-sass from npm and importing it in my gulpfile.ts. But it errored saying that `gulp-sass module couldn't be found`. Can you help me?

**Comment by mgechev** [comment]
Hey @nitinkumarmishra!

Thanks for the kind words! You can take a look at how to integrate `gulp-sass` in this [Wiki page](https://github.com/mgechev/angular2-seed/wiki/Add-custom-Gulp-task).
