### ISSUE TITLE
manual_typings usage example

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#433]
Hi I am running into a problem with adding my own typings file in the folder `manual_typings`. 

Eventually, it could be cool with a usage example somewhere here, but for the current state, we don't have it.

I would appreciate some help since I cannot get it to work. 

In return, I will distill and update here so that it can serve as a usage example for others to use later :)

My specific problem below:

I want to use a js library with custom typings. Runtime it works, but my import statement gives a compile error. I get the error
```app/services/motor.ts(1,20): error TS2307: Cannot find module 'mathjs'.```

for the line:

```import {math} from 'mathjs';```

Now, I added a manual typings file in `/tools/manual_typings/mathjs.d.ts` And did nothing else. Am I missing some wiring up I need to do?

**Comment by mgechev** [comment]
Hey @jesperronn would you share the content of `mathjs.d.ts`?

**Comment by jesperronn** [comment]
yeah, it's at https://github.com/jesperronn/DefinitelyTyped/blob/mathjs_mathnode_typings/mathjs/mathjs.d.ts

And I just read about how to refer any custom javascript library without typings. http://stackoverflow.com/a/27434010/109305 

The trick Basarat suggests is to add the following line in the top of my file:
```
declare var math:any; // Magic
```

With this, I can now easily use as if I had typings. Much easier, but without the type safety of a typings file. This, I can easily live with.

**Comment by jesperronn** [comment]
@mgechev thanks for asking. This means that my issue is actually solved and I will close this.

In case others have this problem, it's probably not the most elegant solution, but it works:

## include a pure javascript dependency in the project:
(for this example I will use `mathjs`)

First, install your dependency with npm:

```npm install mathjs --save```

Then, add it to the build script at both `DEV_NPM_DEPENDENCIES` and `PROD_NPM_DEPENDENCIES`:

```
  { src: 'mathjs/dist/math.js', inject: true, dest: JS_DEST },
```

Then add it to your test runner `karma.conf`:

```
    // list of files / patterns to load in the browser
    files: [
      'node_modules/mathjs/dist/math.js',
```

Then add it to `test-main.js`: in the group `System.config.paths`:

```
  paths: {
    'mathjs': 'node_modules/mathjs/dist/math.js',
    'angular2/*': 'node_modules/angular2/*.js',
```

Then, finally you can use it by declaring that variable which is exported by the library inside your code. Consider I want to use it in a service, I could add the following line in the top of, say, `app/services/calculator.ts`:

```
declare var math:any; // Magic. see http://stackoverflow.com/a/27434010/109305
```

And in my actual code I could do:

```
    ...
    let result = math.parse(this.incredibleExpression).eval(myVariables);
    ...
```

All is good, there are no validation errors during compile time.
