### ISSUE TITLE
How about renaming top level `app` folder to `src`??

### ISSUE THREAD

**Issue by tapas4java** [mgechev/angular2-seed#439]
Currently we have 2 `app` directories in hierarchy(app root folder and app component). 

How about renaming top level `app` folder to `src`??

**Comment by Bigous** [comment]
+1

**Comment by UnnoTed** [comment]
it also bothers me, `src` is better organized

**Comment by NathanWalker** [comment]
I agree as well. 
+1 for this reorg of folder setup:
```
src/components/about/about.ts
src/components/app/app.ts
src/components/home/home.ts
```

Keeps all components together in `src` directory and creates a more scalable setup for others.

**Comment by tapas4java** [comment]
Here is the PR #440
