### ISSUE TITLE
npm start doesn't work npm ERR! Please include the following file with any support request: npm ERR!   \angular2-seed\npm-debug.log

### ISSUE THREAD

**Issue by NathanielMalca** [mgechev/angular2-seed#441]
Hey , 

I followed the simple steps of https://github.com/mgechev/angular2-seed#how-to-start

i triggered the npm start command and got the following error:

> angular2-seed@0.0.0 start C:\Users\Nethanel\WebstormProjects\WorldUnitedFrontEnd\angular2-seed
> gulp serve --env dev

module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Nethanel\WebstormProjects\WorldUnitedFrontEnd\angular2-seed\tools\utils\server.js:2:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nethanel\WebstormProjects\WorldUnitedFrontEnd\angular2-seed\npm-debug.log

Please help

OS:win10
IDE:WebStorm 11

**Comment by mgechev** [comment]
@NathanielMalca would you try with a clean clone? I just merged a change in the dev server.

**Comment by NathanielMalca** [comment]
Hey @mgechev  thanks. just worked :)
