### ISSUE TITLE
date-formatter.ts not able to find moment.ts

### ISSUE THREAD

**Issue by harikrishna266** [mgechev/angular2-seed#442]
when i add ng2-bootstrap in my project,  I get an error that moment.js is not found.

**Comment by mgechev** [comment]
Have you tried to add moment as dependency? The seed doesn't contain moment.js so you need to install it.

**Comment by harikrishna266** [comment]
I think i have installed momentjs. 
This is the dependencies in package.json
```
"dependencies": {
    "angular2": "2.0.0-beta.2",
    "bootstrap": "^3.3.5",
    "es6-module-loader": "^0.17.8",
    "es6-shim": "^0.33.3",
    "moment": "^2.11.2",
    "ng2-bootstrap": "^1.0.3",
    "ng2-file-upload": "^1.0.0-beta.1",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "systemjs": "0.19.9",
    "underscore": "^1.8.3",
    "zone.js": "0.5.10"
  }
```
I have edited the file named date-formatter.js 
from 
var moment = require('moment');
to 
var moment = require('../../../moment/moment');
and then it seems to work. The issue is that everybody in the team has to edit the file 
node_module/ng2-bootstrap/components/datepicker/date-formatter.js 

i think this is more of ng2-bootstrap based issue. You may close this issue. 
Thanks

**Comment by ceelian** [comment]
A quick workaround:

Add the following line anywhere in the constructor of project.config.ts:

`(<any>this.SYSTEM_BUILDER_CONFIG.paths)['moment'] =
			`node_modules/moment/moment.js`;`

**Comment by quiringk** [comment]
I had this issue today. I tried many different changes to my systemjs.config.js file and kept getting 

localhost/:20 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/moment(…)

@harikrishna266 answer was the only work after hours of trying to figure out what happened. 

Here is my relevant systemjs.config.js:

// map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    'rxjs':                       'node_modules/rxjs',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    '@angular':                   'node_modules/@angular',
    'moment':                     'node_modules/moment',
    'ng2-bootstrap':              'node_modules/ng2-bootstrap'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { defaultExtension: 'js' },
    'moment':                     { defaultExtension: 'js' },
    'ng2-bootstrap':              { defaultExtension: 'js' }
  };
