### ISSUE TITLE
node.d.ts included twice after adding sass, npm start fails

### ISSUE THREAD

**Issue by midthun** [mgechev/angular2-seed#444]
I followed the steps [here](https://github.com/mgechev/angular2-seed/wiki/Add-custom-Gulp-task) to add support for sass. After following all the steps, I ended up with a "gulp-sass" folder and a "node" folder inside my "typings" folder. 

When I try to run "npm start" I get all sorts of "Duplicate identifiers" messages, first one being: 

`"typings/main/ambient/node/node.d.ts (15,5): Duplicate identifier 'stack'. (2300)"`

I assume this is because node definitions already is inside the "typings" folder. It seems like installing gulp-sass added another. 

Finally the process exits with the following error: 
```
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: 'gulp serve --env dev'
npm ERR! Exit status 1
```
using node v4.2.1 and npm v2.14.7

Is there a better way to add gulp tasks and update definitions?

**Comment by mgechev** [comment]
You can exclude the extra [node definition here](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.js.dev.ts#L9-L13).
