### ISSUE TITLE
Inconsistency in test compilation

### ISSUE THREAD

**Issue by nareshbhatia** [mgechev/angular2-seed#447]
While unit tests are compiled to `/test`, e2e tests are compiled to `/dist/dev`. This has the following downsides:
- Unit tests and e2e tests are treated inconsistently.
- `/dist/dev` has a mix of application js and e2e js.
- Many people like to keep test source in `/test`, but this name is now taken to store unit test compiles.

Can I suggest the following organization:
- Unit tests get compiled to `/dist/test/spec`
- e2e tests get compiled to `/dist/test/e2e`

This not only makes the compilation of unit and e2e tests consistent, but also frees up the `/test` directory for people wishing to use it for storing test source.

I can create a PR if this seems like a good idea.

P.S. I personally don't like to mix application and test source. I can understand why some people do, perhaps to keep it together with the source. I tend to create far more test files than application files, hence mixing them obscures the application source. Also I tend to write tests in layers, following the [Test Automation Pyramid](https://www.mountaingoatsoftware.com/blog/the-forgotten-layer-of-the-test-automation-pyramid) suggested by Mike Cohn. I find it easier to do this if my tests are in a separate directory structure. In any case, it is a matter of opinion and I would appreciate if the seed project accommodates both ways of working.

**Comment by mgechev** [comment]
Seems like a very good idea to me and we'll really appreciate your help!

**Comment by nareshbhatia** [comment]
Sounds good. Will start working on it today.

**Comment by mgechev** [comment]
Great! Looking forward for the PR!

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/pull/476.

**Comment by nareshbhatia** [comment]
@mgechev, I am trying to extend the build to include Sass and realizing that the decision to split the dev, unit and e2e builds into 3 different directories may not be a good one. Since Sass requires an additional step of converting from .scss to .css, I am finding that I have to write additional tasks for each type of build. I am now thinking that it would be better to use `/dist/dev` as a *playground* for all dev activities, including unit and e2e testing. It will make the build process much simpler.

The only question in my mind is why was the e2e build in a separate directory earlier (`/test`)? As far as I can tell, it can be folded quite easily into `/dist/dev`. Am I missing something? If not, I can work on a PR.

**Comment by mgechev** [comment]
@nareshbhatia I don't think there's any particular reason. @NathanWalker added the e2e testing support so he can verify.

**Comment by ludohenin** [comment]
@nareshbhatia I have a pending issue on `gulp-inline-ng2-template` plugin to add preprocessors here: https://github.com/ludohenin/gulp-inline-ng2-template/issues/11. It may be a good way to solve your issue ?

**Comment by nareshbhatia** [comment]
Yes, that would solve the problem. The issue is that the plugin expects the `.css` file to be specified in the TypeScript file and there is no css file there! We could run the preprocessor before invoking the inline-plugin, but that would mean writing to the source directory, which I don't like. Moving everything to a temp directory for the dev build is also a pain. This is not an issue for the prod build because in that case we do go through a temp directory anyway and I can preprocess before running the inline plugin.

However, I would also like to keep the option open to not have to inline for running tests. I will look into this today. Will keep you posted.

**Comment by ludohenin** [comment]
@nareshbhatia the idea of preprocessors for the plugin is to declare `.scss`, `.stylus`... in you component and to provide a processed string to the plugin. This way you don't mess up the `src` folder nor have the intermediate `tmp` step.

**Comment by nareshbhatia** [comment]
Yep, I got that and would love to see that solution. I was just commenting that I would like to explore running the tests without having to inline, just out of curiosity :-). Any ETA for your solution? How do you plan to pick up preprocessor options? Also do you see any drawbacks to inlining during dev builds, e.g. longer build times?

**Comment by NathanWalker** [comment]
@nareshbhatia Sorry for delay here. I've been traveling for more than a week now but will be back late tomorrow evening. e2e tests build/run location can definitely change. Just keep in mind of course protractor needs to access and test off a running site. Thank you for your help here though, I definitely agree keeping test and app builds seperate is the way to go.

**Comment by nareshbhatia** [comment]
@NathanWalker, thanks for responding even from the road! Wasn't clear about your last sentence:

> I definitely agree keeping test and app builds separate is the way to go.

To summarize this discussion, my latest PR uses two directories for builds:

- `/dist/dev/` is used for dev, unit test and e2e test builds.
  - dev builds are working correctly with BrowserSync
  - unit tests are working correctly with karma/jasmine
  - e2e tests are working correctly with protractor
- `/dist/prod` is used for prod builds and this is also working correctly

If this looks ok to you, @mgechev can accept the pull request

**Comment by NathanWalker** [comment]
As long as protractor is running correctly then this sounds great :+1: 

Ideally I like keeping all test builds isolated in a `test` directory but since the different build tasks exclude the test files (ie, the dev build: https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.js.dev.ts#L13-L14), then it's just as good.

Thank you for the improvements here.

**Comment by nareshbhatia** [comment]
Happy to help.

Yes, I was very meticulous about

- dev and prod builds not containing any tests
- unit test build not containing any e2e tests
- e2e test build not containing any unit tests

The build tasks are now very modular and focused on the build type. Hope this will keep everything straight in our heads!

@mgechev, can you please merge PR #482

**Comment by d3viant0ne** [comment]
@nareshbhatia - Thanks for this one, solid DX improvements :)

**Comment by nareshbhatia** [comment]
@d3viant0ne, my pleasure :)

**Comment by mgechev** [comment]
:+1:

**Comment by LuxDie** [comment]
@NathanWalker 
> /dist/dev/ is used for dev, unit test and e2e test builds. 

This approach doesn't work when I'm running the dev server and tests at the same time, since they overwrite each other, which is messy. Even worse if I run the tests on watch mode, say with `npm run build.test.watch`.

We need to either have a dev build that is exactly the same for dev server, unit tests and e2e tests, or have a separate directory for each. If the latter, it would mean builds pipelines also differ, which would mean also having separate build tasks (dev, unit, e2e), which I agree gets complicated and redundant.
