### ISSUE TITLE
Exception Does not support more than 9 expressions

### ISSUE THREAD

**Issue by aminmagdich** [mgechev/angular2-seed#449]
Hi,
 I can't find any information online to point me in any direction of solving this issue

![captureaaa](https://cloud.githubusercontent.com/assets/11071691/12881311/3a8626ec-ce49-11e5-8ef9-9562f15a8262.PNG)

**Comment by mgechev** [comment]
Hey! What are the steps for reproducing this issue? Is it related with the seed?

**Comment by aminmagdich** [comment]
Hi, 
thank you for your answer
when i use more than 9 expressions (template syntax) into my view

**Comment by mgechev** [comment]
This issue is not related to angular2-seed. It is either a mistake you did or an issue in angular2.
