### ISSUE TITLE
Uncaught ReferenceError: System is not defined Exception

### ISSUE THREAD

**Issue by NathanielMalca** [mgechev/angular2-seed#450]
When adding the 

<script src="/node_modules/angular2/bundles/http.dev.js"></script>
<script src="/node_modules/rxjs/bundles/Rx.js"></script>

to the index.html file within the <head> following the example in:
https://angular.io/docs/ts/latest/guide/server-communication.html

i get to exceptions regarding each file 

Uncaught ReferenceError: System is not defined Exception

Any idea maybe?

thanks

**Comment by mgechev** [comment]
System is not implemented in the browsers yet, thats why we use systemjs. Take a look at [SystemJS](https://github.com/systemjs/systemjs) and take a look at how external script references work.
