### ISSUE TITLE
Prod build has issue loading bundle

### ISSUE THREAD

**Issue by natarajs** [mgechev/angular2-seed#452]
Hi,
      I am new to gulp/systemjs and could be doing this wrong. I tried to do a production build using this command:
      gulp build.prod --env prod

     Then went into dist/prod folder and tried to run live-server.

     I get Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost:8080/bootstrap.js.

     I understand it has to do with trying to load the bundle. I am comparing the dev and prod configs in config.ts. I am not sure what the change needs to be.

const SYSTEM_CONFIG_DEV = {
  defaultJSExtensions: true,
  paths: {
    'bootstrap': `${APP_ROOT}bootstrap`,
    '*': `${APP_BASE}node_modules/*`
  }
};

const SYSTEM_CONFIG_PROD = {
  defaultJSExtensions: true,
  bundles: {
    '/bundles/app': ['bootstrap']
  }
};

Thanks in advance
Sayee

**Comment by mgechev** [comment]
SystemJS is not used for the prod build, there we use browserify.

For running the production build use:

```bash
npm run build.prod
cd dist/prod
http-server
```
