### ISSUE TITLE
React js integration

### ISSUE THREAD

**Issue by ksminu** [mgechev/angular2-seed#454]
Hi Team,

I am very new to gulp and I am trying to integrate reactjs with this project. I have installed the react and react-dom using npm. But when i am referencing it, its throwing errors 404 not found for react.js and react-dom.js. Do i need to change any configuration for react to work with this project? Thanks in advance.

**Comment by mgechev** [comment]
Hey @ksminu take a look at the project [wiki page](https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency).

May I ask what is your use case? Are you migrating a legacy React application to Angular 2 or you're developing a hybrid Angular 2/React app?

**Comment by ksminu** [comment]
Hi 
I am creating an Angular2 app where some of the controls will be react controls. 

Thanks
Minu

**Comment by ksminu** [comment]
Hi

I am still not able to integrate react with this project. I also tried adding the react, react-dom into DEV_NPM_DEPENDENCIES. But its still throwing issues.

Thanks 
Minu

**Comment by mgechev** [comment]
What is your use case for implementing components with React instead of using Angular 2 ones (just interested).

Otherwise, you need to configure SystemJS in order to make it find the react module. Take a look at [`config.ts`](https://github.com/mgechev/angular2-seed/blob/master/tools/config.ts#L87-L99).

**Comment by ksminu** [comment]
We need some additional functionality in grid which we found was available in React data grid rather than angular2 grids. React has some better controls compared to angular2 like datetimepicker available. So only some controls we are planning to implement in React.

I already tried adding it in config.ts. But couldn't get it to work. I think I need to browserify it. 

Thanks,
Minu

**Comment by mgechev** [comment]
Since we use SystemJS for dev, you can take a look at this repo https://github.com/lalitkapoor/systemjs-es6-react-boilerplate

**Comment by ksminu** [comment]
I was able to fix this issue as you suggested by adding the react and react-dom to npm-dev-dependencies and adding to it systemjs. This approach works for simple react components. My requirement is to use components like react-bootstrap-datetimepicker and react data grid. When adding datetimepicker, its internally referencing lot of other modules which is again creating issues. Its not feasible to add all the references into SystemJS. I even tried writing a gulp task to browserify the datetimepicker component but still facing issues.

Could you please let me know if there is any other way it can be done in your project? Thanks in advance.
