### ISSUE TITLE
'Add custom Gulp task' wiki page is out-of-date

### ISSUE THREAD

**Issue by zcsongor** [mgechev/angular2-seed#455]
Upgraded to typings, but the wiki page still using tsd.

**Comment by mgechev** [comment]
Fixed.

**Comment by zcsongor** [comment]
Thanks! Tried the same, got 'duplicate identifier' errors. I did a reinstall, now works like a charm.

**Comment by NathanWalker** [comment]
@mgechev shoot, I missed those links, sry about that! In future, I'll be sure to go through all links on the wiki!

**Comment by mgechev** [comment]
@NathanWalker no worries! I missed them as well.
