### ISSUE TITLE
@ngrx-store 404 error

### ISSUE THREAD

**Issue by cramhead** [mgechev/angular2-seed#457]
After including running ```npm install @ngrx/store --save``` and integration the example code I get a 404 error when the app attempts to get the store.js file. i.e. ```http://localhost:5555/node_modules/@ngrx/store.js``` fails with a 404. The store.js file does exist in ```http://localhost:5555/node_modules/@ngrx/store/dist/store.js```. 
I'm not sure if the error is due to the "@" in the name or something odd like that or if the package should have the store.js file at a higher level in the file hierarchy. If I manually copy the file to the expected location all works fine.

If it would help I can make a repo with a broken or work around.

Please detail the affected browser(s) and operating system(s): 
chrome 48.0.2564.97 (64-bit) on OSX 10.11.3 (15D21)
Please be sure to state which version of node and npm you're using: 
node v5.1.0 & npm 3.6.0

**Comment by mgechev** [comment]
You may need to change the SystemJS configuration in `./tools/config.ts`. Take a look at this SystemJS issue https://github.com/systemjs/systemjs/issues/767.

**Comment by hhubik** [comment]
Ran into the same issue with the latest Seed (as of yesterday).  The solution was to put the following in `project.config.ts`:
```
    let additionalPackages: ExtendPackages[] = [
      { name: '@ngrx/core', path: 'node_modules/@ngrx/core/bundles/core.min.umd.js' },
      { name: '@ngrx/store', path: 'node_modules/@ngrx/store/bundles/store.min.umd.js' }
    ];

```
