### ISSUE TITLE
problem with prod environment (assignment to undeclared variable $this)

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#458]
Hi,
After run npm run build.prod and put the result at apache I'm receiving this error when accessing the pages:
`assignment to undeclared variable $this`
The exception at firebug starts at:
`initApp</app.domReadyMisc@http://myurl/js/shims.js:19:25719`

With dist environment everything works normal.
Please someone could help me?

**Comment by mgechev** [comment]
Would you try:

```bash
npm install -g http-server
npm run build.prod
cd dist/prod
http-server .
```

After that open: http://localhost:8080/ and tell me if the app works.

**Comment by gustavolira** [comment]
The same problem.
This does not happen with a fresh angular2-seed install. My application already has several pages...
The strange thing is that in DEV works perfectly

**Comment by mgechev** [comment]
@gustavolira would you clean `node_modules` and `typings` and try again?

**Comment by gustavolira** [comment]
I just clean node_modules and typings but unfortunately I had the same problem.
Some information that I can provide for easier debug?

**Comment by gustavolira** [comment]
At chrome console `shims.js:4 Uncaught ReferenceError: $this is not defined`

**Comment by mgechev** [comment]
You can compare the bundles produced by the fresh app prod build and the one you have problems with. I guess any of the dependencies is not bundled properly.

**Comment by gustavolira** [comment]
really strange, I'm using the same `package.json`, I just included my components with some pages

**Comment by mgechev** [comment]
Did you verify that the bundles are different?

**Comment by gustavolira** [comment]
The shim.js of my application has 364,8 kb and from the fresh app has 86,5 this is what I get different, and off course app.js because my components.
I substitute shim.js with the fresh app but did not solved.

**Comment by gustavolira** [comment]
I will exclude component by component until figure out what's happening.
When I figure out I back here to say what was the problem.
You can close this issue if you want.

**Comment by mgechev** [comment]
@gustavolira let me know what you find out. We can close it if we verify that the issue is not caused by the build configuration.

**Comment by mgechev** [comment]
@gustavolira do you have any progress in finding the cause?

**Comment by gustavolira** [comment]
Sorry @mgechev  for delayed reply.
I could figured out what was happening.
I'm using this [template](https://wrapbootstrap.com/theme/smartadmin-responsive-webapp-WB0573SK0l) and there's a file (app.min.js) that are using the variable $this without declare and the error only appears at production bundle because minified. I fixed this at app.min.js declaring var $this.
Thank you for your attention
