### ISSUE TITLE
Switch to Browserify from SystemJS for dev

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#459]
Currently we use browserify for the production build and SystemJS for dev. SystemJS requires further configuration for some dependencies which are hosted in `node_modules`. If we ignore this, there are still differences in the way all external modules are being loaded/bundled which may lead to inconsistencies between the `dev` and `prod` builds.

Examples:
- Inconsistency https://github.com/mgechev/angular2-seed/issues/458
- Managing dev dependencies https://github.com/mgechev/angular2-seed/issues/457 https://github.com/mgechev/angular2-seed/issues/442 https://github.com/mgechev/angular2-seed/issues/393

What are your thoughts on this?

// cc @ludohenin @nareshbhatia @gdi2290

**Comment by c-ice** [comment]
+1 for consistency
what its mean for us in the typescript code? Will be there some changes in importing dependencies?

**Comment by mgechev** [comment]
Everything should be the same except that the page load should be faster (only a single bundle instead of multiple files loaded asynchronously with SystemJS).

**Comment by c-ice** [comment]
so why not :)

+1

**Comment by ludohenin** [comment]
@mgechev will this still work with the hot loader ?
otherwise, yeah why not ... tho that also mean we give up on multi-bundles

**Comment by zcsongor** [comment]
@mgechev i dont quite understand, sorry for my ignorance, but I must ask: isn't async loading would be faster? now in prod build we load a big bundle first when we don't even need some of the modules yet. what am I missing?

**Comment by gdi2290** [comment]
+1 Browserify

**Comment by gdi2290** [comment]
check out this https://gist.github.com/substack/68f8d502be42d5cd4942 to improve the build of browserify

**Comment by mgechev** [comment]
@ludohenin yes, you're correct. We can disable the hot loader for a while. Angular 2 core team are planning drastic changes on the `AppView` API so there will be breaking changes quite soon anyway and part of the hot loader need to be rewritten.

**Comment by zcsongor** [comment]
@mgechev could you clarify my doubts? I'm a newbie, so please forgive if I asked smthg silly

**Comment by mgechev** [comment]
@zcsongor yes, sure, sorry for the delay.

When each individual component is loaded individually this requires separate HTTP GET requests which slows down the bootstrap. In contrast, in the optimal case browserify will produce a single bundle that will that will require only a single GET request.

AsyncRoutes will be a bit tricker since you'll need to create separate bundles for each sub tree that you want to load asynchronously in the dependency tree of your project.

**Comment by zcsongor** [comment]
Oh, I see. Thought the latency isn't the biggest problem, but on mobile networks, it could be.

**Comment by Bigous** [comment]
@mgechev is browserify that good? I mean, doing this we will disable the ability to load modules only when needed and for big projects it will be necessary and during development you wanna test what you are developing and 1 line of code changed will cause 100% reload... just guessing if won't be a bad thing in the future...

**Comment by mgechev** [comment]
@Bigous the first problem can be solved with multiple bundles, the second with hot loading.

At this point, the only thing bothering me is the inconsistency between the two builds, however, switching the prod build to SystemJS will be a step back because of the big bundles it produces.

**Comment by Bigous** [comment]
Agree, but the browserify prod build does not work well... for example, with jquery plugins and components, it frequently breaks (start throwing undefined init) where in SystemJS is working flawless.

**Comment by mgechev** [comment]
@Bigous based on the inconsistency again. Well, we can switch the production build to use the [SystemJS builder](https://github.com/systemjs/builder), which should be able to bundle the entire code in CommonJS format and thus produce it with minimal file size (similar to browserify).

**Comment by mgechev** [comment]
A few more issues in the production build:

https://github.com/mgechev/angular2-seed/issues/473
https://github.com/mgechev/angular2-seed/issues/479

**Comment by juristr** [comment]
@mgechev Just for curiosity. What's the reason for switching from SystemJS to Browserify?

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/pull/483.
