### ISSUE TITLE
Replace SystemJS with TypeScript to CJS + Browserify

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#46]
Based on https://github.com/mgechev/angular2-seed/issues/44

**Comment by mgechev** [comment]
@ludohenin we need to decide whether its worth it to switch to Browserify + TS with CJS, because it will require changes in https://github.com/mgechev/angular2-seed/issues/45 as well.

The overhead of TS + Browserify will be lower, traceur-runtime won't be required. What are your thoughts?

**Comment by ludohenin** [comment]
@mgechev getting rid of traceur-runtime seems to be a good idea. I never used Browserify so don't know the pro/cons. Is it a lot better than requirejs ?

What I like with systemjs though, is that it is more straight forward build and support any kind of module definition (cjs, amd, umd) making it more generic. 

Another build to explore would be to replace traceur by Babel in systemjs. But not quite sure babel-core is light-weight compare to traceur-runtime.

**Comment by mgechev** [comment]
Yeah, lets keep system.js.
