### ISSUE TITLE
Cannot GET route when pasting or reloading url

### ISSUE THREAD

**Issue by londonoaa** [mgechev/angular2-seed#463]
Hello Guys,

I have configured my app so that it handles the urls in html5 style (pushstate), it works fine with RouteLinks but not when pasting or reloading the url, except for home. I have added the <base href="/"> in the header and removed the hash location strategy code from main.ts

am i missing something?

**Comment by londonoaa** [comment]
works great!

**Comment by londonoaa** [comment]
not working in production

**Comment by mgechev** [comment]
@londonoaa it depends on your server. It needs to always serve `index.html` except when you request an existing resource. Take a look [at this](http://discuss.emberjs.com/t/apache-rewrite-rule-for-html5-browser-history-url-bookmarkability/1013).

**Comment by londonoaa** [comment]
I think there is something wrong, because it is not working with nested routes
