### ISSUE TITLE
Can't include external dependency

### ISSUE THREAD

**Issue by nikkwong** [mgechev/angular2-seed#465]
I've read the external dependency guide that's been shared, but it doesn't solve my problem. 

I'm simply trying to import underscore into one of my .ts files:

````
import * as _ from 'underscore';
````

Where underscore has been defined in my typings. No luck, I get:

````
app/services/ThreadsService.ts(5,20): error TS2307: Cannot find module 'underscore'.
````

What gives? Is there something I'm doing wrong?

**Comment by mgechev** [comment]
https://github.com/mgechev/angular2-seed/issues/307

**Comment by nikkwong** [comment]
Unfortunately that hasn't been working for me. If you know of any other possible issues that could be causing it—that would be great! Thanks a bunch.

**Comment by mgechev** [comment]
@nikkwong `tsc` cannot find the underscore type definition. That is the issue. Since now we are using typings instead of tsd you need to use:

```
typings install underscore --ambient --save
```

**Comment by nikkwong** [comment]
I'm still getting the error in the command line, although `underscore` is now no longer showing up as missing in the script itself.

Will be interesting to see if anyone else runs into this issue.. Thanks for the help.

**Comment by nikkwong** [comment]
Another interesting note: 


```
import * as _ from 'underscore';
export class AppCmp implements OnInit {
  ngOnInit() {
    console.log(_);
  }
}
````

It appears to be looking for the library in ```node_modules``` according to the output.

**Comment by nikkwong** [comment]
With this setup it was also imperative that i `exclude` the typings in `tsconfig` or it would attempt to require itself twice:

````

typings/browser/ambient/underscore/underscore.d.ts (57,3): Duplicate identifier 'length'. (2300)
typings/browser/ambient/underscore/underscore.d.ts (3977,2): Duplicate identifier 'templateSettings'. (2300)
typings/browser/ambient/underscore/underscore.d.ts (5912,2): Duplicate identifier 'export='. (2300)
typings/main/ambient/underscore/underscore.d.ts (17,3): Duplicate identifier 'leading'. (2300)
typings/main/ambient/underscore/underscore.d.ts (22,3): Duplicate identifier 'trailing'. (2300)
````

Fix:

````
    "exclude": [
        "node_modules",
        "typings/browser",
        "typings/browser.d.ts"
    ],
````

Though that doesn't fix the issue.

**Comment by nikkwong** [comment]
Could this issue potentially be reopened?

**Comment by mgechev** [comment]
@nikkwong you need to configure SystemJS in `config.ts` in order to point the correct [path to underscore](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#paths).

>Why isn't it grabbing from the type definitions in the typings/ directory?

The ambient type definitions have nothing to do with the package implementation itself.

>Could this issue potentially be reopened?

This is not issue with the seed itself but involves some configuration details which need to be documented. However, we are planning to [switch to browserify](https://github.com/mgechev/angular2-seed/issues/459), which will make requiring external dependencies much less painful.
