### ISSUE TITLE
Two typings folders?

### ISSUE THREAD

**Issue by bobmonteverde** [mgechev/angular2-seed#47]
Hey, not sure if this is an issue, assuming you guys probably did this on purpose, but I'm very new to TypeScript and Angular2.

You have  ./tsd_typings and ./app/typings .   Just guessing, I would think tsd_typings is for TypeScript definitions from http://definitelytyped.org/tsd/ (basically 3rd party definitions)... and ./app/typings is for your app specific TS definitions.  But it seems like ./app/typings/systemjs.d.ts is a 3rd party definitions file that should be in /tsd_typings.

Any clarification would be very welcome.  I haven't been able to find a good boilerplate or yeoman generator for Angular2, so trying to put one together myself.  Though might be a little ambitious.... trying to do a Gulp + jspm (SystemJS) +  BrowserSync + WebPack + TypeScript->ES6->(babel)->ES5 + PostCSS (and some useful plugins, PreCSS, cssnext, autoprefixer, etc)... and possibly more.   Working in baby steps.... and since this is the best angular2 seed I can find, trying to base part of my boilerplate off of it.

**Comment by NathanWalker** [comment]
Hi @bobmonteverde. Yes indeed you are correct in your statements. ./app/typings are custom ones that are either not available via `tsd` or required customizations. The systemjs.d.ts was used temporarily as I had a pending PR for definitelytyped for that at the time, but I will get that integrated with the 3rd party definitions here soon to clean that up. Thanks for heads up.

That is a very ambitious endeavor there for sure. Let us know if any of us can help.
We are all very busy but your goal would be something the entire community would greatly appreciate.

**Comment by bobmonteverde** [comment]
OK, amazing, thank you for confirming that one.  Luckily after being stuck for a little bit, did some research into TSD and had figured out that I was probably on the right line.  I guess for you guys, being such early adapters, probably spend more time making workaround then removing them when things get fixed/changed.

Not sure if I'll be reaching my original goal initially with the boilerplate, but hopefully will get the major stuff out of the way.  Gonna try to play with it on my own for another day or two so I get a decent grasp on things, but after that would love to get some outside input from people who have a little more experience with the stack (or at least the parts of the stack I'm not too familiar with).  It seems like the angular2 community is in need of a good boilerplate with everything setup nice so it'll be easier for people to just get rolling and play around with things while angular2 is still beta.  I'll get back to you in a couple of days to see if you're up for checking out where I'm at.

**Comment by NathanWalker** [comment]
Awesome @bobmonteverde thanks! 
I just posted a PR which will resolve the systemjs customization :+1: 
https://github.com/mgechev/angular2-seed/pull/48

**Comment by NathanWalker** [comment]
Resolved here:
https://github.com/mgechev/angular2-seed/pull/48
And explained above.
