### ISSUE TITLE
Changes made to css file don't refresh app in browser for ViewEncapsulation.Emulated

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#471]
I'm using `encapsulation: ViewEncapsulation.Emulated` in my project and after any change in css file I need to manually refresh browser. Autorefresh doesn't work.

**Comment by mgechev** [comment]
There is not auto refresh functionality.

**Comment by eskinderg** [comment]
Any temporary or permanent solution for this feature/issue ?
