### ISSUE TITLE
"npm run reinstall" fails

### ISSUE THREAD

**Issue by LuxDie** [mgechev/angular2-seed#474]
Hi. Running `npm run reinstall` exits with error "The system cannot find the path specified." **after** deleting the `node_modules` directory.
I'm running Windows 10, Node.js v5.3.0 and Npm v3.5.2.

**Comment by mgechev** [comment]
@LuxDie in case you've removed the `node_modules` directory use `npm install`. Part of `npm run reinstall` removes `node_modules` which in your case doesn't exist so thats why the error occurs.

**Comment by LuxDie** [comment]
@mgechev that's not it. I follow these steps:

1. Clone a fresh copy of the repo.
2. `npm install`
3. `npm run reinstall`
4. Error pops up and `node_modules` directory is gone

**Comment by d3viant0ne** [comment]
Works as intended on OSX 10.11 (node v5.6.0 / npm 3.6.0) all be it a bit slowly.

I'm spinning up a Windows 10 VM now to try and verify @LuxDie 's issue.

**Comment by LuxDie** [comment]
Thanks guys!

**Comment by mgechev** [comment]
@d3viant0ne great job on this!
