### ISSUE TITLE
Change structure so there is a components folder inside src

### ISSUE THREAD

**Issue by londonoaa** [mgechev/angular2-seed#475]
it is better if there is a folder for components inside src, cause if your app grows it will be huge. Also remove components folder inside each component folder.

**Comment by mgechev** [comment]
We are discussing the directory structure in the [Angular 2 Style Guide repo](https://github.com/mgechev/angular2-style-guide/issues/5).

When we reach a consensus there we'll implement the directory structure we've agreed on here.

**Comment by e-oz** [comment]
Please don't change structure of this seed.. It's just perfect.

**Comment by e-oz** [comment]
sorry, @londonoaa , I wasn't aware of already existing changes in structure. Agree, currently it looks awful. And proposals in linked thread are even worse.
