### ISSUE TITLE
Is there an interest in removing the dependency on Twitter Bootstrap?

### ISSUE THREAD

**Issue by nareshbhatia** [mgechev/angular2-seed#477]
I would like to propose styling the seed app with plain old CSS instead of Bootstrap. This means one less dependency and the flexibility for people to add any CSS or component framework of choice (e.g. Angular 2 Material when it becomes available). What do you think? I can work on a PR.

**Comment by mgechev** [comment]
Yes, I agree. I'll remove bootstrap today.

**Comment by nareshbhatia** [comment]
@mgechev, when you do that, can you please style the app to be a bit more polished? This will give people even more confidence in the quality of this project. I had something very simple but elegant in mind - see below.

1. A prominent navbar at the top.
2. Proper margins around the content area. Currently content is hitting the left margin.
3. Replace the smiley icon with something more useful, e.g. a menu icon in the navbar. I assume that the purpose of adding the smiley icon is to have a placeholder for assets.
4. Make navbar a component instead of hardcoding in `app.html`. So `app.html` would look simply like this:

```
    <section class="sample-app-content">
      <navbar></navbar>
      <router-outlet></router-outlet>
    </section>
```

![angular2 seed screen shot](https://cloud.githubusercontent.com/assets/1220198/13028435/fb37f784-d23c-11e5-8220-67ab4885ce0b.png)

**Comment by mgechev** [comment]
Yes, we should do that. I like your ideas, we can make the navbar accept an input with the links and their labels. The home information can contain some basic list with items (similar to the one we currently have). On the about we can add some basic information about the seed.

**Comment by nareshbhatia** [comment]
That would be perfect!
