### ISSUE TITLE
ng2-bootstrap load failure

### ISSUE THREAD

**Issue by Myrmex** [mgechev/angular2-seed#478]
I'm new to System js and I'm trying to play with this beautiful seed and a couple of libraries like `toastr` and `ng2-bootstrap`, but I cannot get them to load. I installed both using `npm install ng2-bootstrap` and `npm install toastr`, but when the app starts I get:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:65 Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/ng2-bootstrap.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ localhost/:65
http://localhost:5555/node_modules/toastr.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

Also, `toastr` is not found as system.js is looking for it at `http://localhost:5555/node_modules/toastr.js` whereas it is located under `node_modules/toastr`. I tried adding a `map` property to  `SYSTEM_CONFIG_DEV` under `config.ts` like:

```
  map: {
    toastr: `${APP_BASE}node_modules/toastr/toastr.js`
  },
```

but this does not seem to have any effect. Could anyone suggest a solution?

**Comment by mgechev** [comment]
Instead of `map` use `paths`. Take a look at the [API](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md) doc.
