### ISSUE TITLE
Production build gives a "Uncaught TypeError: Cannot read property 'navigator' of undefined"

### ISSUE THREAD

**Issue by giejay** [mgechev/angular2-seed#479]
Just did a npm install and a npm run build.prod of the clean angular-seed and ran into this error. 

Next to that, I'm also getting this one: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

What am I doing wrong?

The URL: http://giejay.nl/test/

**Comment by mgechev** [comment]
I get `Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.` as well.

I saw the error on the URL you provided but I can't manage to reproduce the production build issue you have. Are you getting this error with the latest seed version? Would you give me the output of:

```
git rev-parse HEAD
```

**Comment by spike1292** [comment]
got the same issue, see https://bootcamp2016.firebaseapp.com

**Comment by hpinsley** [comment]
@mgechev I can confirm the same error:

`shims.js:4 Uncaught TypeError: Cannot read property 'navigator' of undefined(anonymous function) @ shims.js:4(anonymous function) @ shims.js:4e @ shims.js:4(anonymous function) @ shims.js:4(anonymous function) @ shims.js:4e @ shims.js:4(anonymous function) @ shims.js:4(anonymous function) @ shims.js:4
app.js:23 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`

$ git rev-parse head
24d87407879de59f59e2e1b16f6f2cad0676dc2e

**Comment by mgechev** [comment]
Thanks for the comment! I'll switch back the production build to SystemJS asap.

**Comment by giejay** [comment]
Thanks for the quick response!

My head is: 73141a25fdc618a3cc1aebd07be937c7141ad40e
