### ISSUE TITLE
Suggestion for cache problem

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#480]
There's any plan to add randon hash at .js file names to avoid cache in PROD build?

**Comment by mgechev** [comment]
Good point! We already have this in dev, I've missed it in production...

**Comment by d3viant0ne** [comment]
@mgechev - Same implementation as what is already in dev?

@gustavolira - You going to PR this or shall I?

**Comment by gustavolira** [comment]
Hi @d3viant0ne feel free if you want to make PR

**Comment by gustavolira** [comment]
The name of app.js should be changed right?

**Comment by mgechev** [comment]
@gustavolira what do you mean?

**Comment by gustavolira** [comment]
To avoid cache, every time we build the app the names of .js files would change like:
app.4de4411f.js

next time that run `npm run build.prod`
app.537de411f.js

On this way every time that we need to do a new 'deploy' cache will be refresh

**Comment by mgechev** [comment]
I think it should be fine with appending query parameter as well.

**Comment by gustavolira** [comment]
This generator https://github.com/yeoman/generator-angular change the .js files when you run `grunt build` and them put the right js file names at .html files
I get this idea from there

**Comment by mgechev** [comment]
Yes, both should work.
