### ISSUE TITLE
Problem with bundle prod and .beta06

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#481]
Hi,
After pull with last commit of master branch, I started have a problem with my Forms.
My forms stopped sending values when at my functions.
With Dev environment everything works ok but minified with  prod environment this problem happens.
If I just change to .beta2 everything works Ok.

**Comment by mgechev** [comment]
There are changes pending in the prod environment. We will bundle the application using the SystemJS builder in order to make the build more consistent (at this point dev uses SystemJS, prod uses browserify).

**Comment by mgechev** [comment]
@gustavolira would you verify if the issue is fixed after merging https://github.com/mgechev/angular2-seed/pull/483?

**Comment by gustavolira** [comment]
Hi @mgechev now I'm receiving this error:
`Unhandled rejection Error on fetch for angular2-jwt/angular2-jwt.js at file:///home/gustavo/git/issuerFront/tmp/angular2-jwt/angular2-jwt.js
	Loading main.js
	Error: ENOENT: no such file or directory, open '/home/gustavo/git/issuerFront/tmp/angular2-jwt/angular2-jwt.js'
    at Error (native)
`

**Comment by mgechev** [comment]
@gustavolira would you share with me your SystemJS configuration? Do you set the same config for `SYSTEM_CONFIG_PROD`?

**Comment by gustavolira** [comment]
Sorry I didn't understand.
I just did pull origin master, npm install, npm run build.prod
With npm run build.prod I receive this error message.

**Comment by mgechev** [comment]
Would you share your `config.ts` under the `tools` directory?

**Comment by gustavolira** [comment]
Sure, here is my config.ts https://gist.github.com/gustavolira/f883b36d36a1f6825a87

**Comment by mgechev** [comment]
You can workaround this by:

```ts
export const SYSTEM_BUILDER_CONFIG = {
  defaultJSExtensions: true,
  paths: {
    '*': `${TMP_DIR}/*`,
    'angular2/*': 'node_modules/angular2/*',
    'angular2-jwt': `${PROJECT_ROOT}/node_modules/angular2-jwt/angular2-jwt.js.js`,
    'rxjs/*': 'node_modules/rxjs/*'
  }
};
```

// cc @ludohenin

**Comment by ludohenin** [comment]
This isn't a workaround IMO but the correct way to declare NPM packages.
I'm just not sure why the `${PROJECT_ROOT}` though.

**Comment by gustavolira** [comment]
I do this 'workaround' but the same error happens

**Comment by krzysztofsaja** [comment]
The same problem. Development runs OK, but production give me this message:
`Unhandled rejection Error on fetch for ng2-bootstrap/ng2-bootstrap.js at file:///home/cogo/Dokumenty/Development/Softbay/PI-Angular2/PI2-Beta6/tmp/ng2-bootstrap/ng2-bootstrap.js
	Loading main.js
	Loading app/components/app.js
	Error: ENOENT: no such file or directory, open '/home/cogo/Dokumenty/Development/Softbay/PI-Angular2/PI2-Beta6/tmp/ng2-bootstrap/ng2-bootstrap.js'
    at Error (native)`

**Comment by ludohenin** [comment]
@mgechev I see your workaround `.js.js` ... that one works for me.

**Comment by gustavolira** [comment]
I see .js.js too, but even put the right name of .js file I still receiving same error. @ludohenin  That one works for you?

**Comment by ludohenin** [comment]
Got it! ... though I don't have a rational explanation to it.

config.ts
```es6
// ...
export const SYSTEM_BUILDER_CONFIG = {
  defaultJSExtensions: true,
  paths: {
    '*': `${TMP_DIR}/*`,
    'angular2/*': 'node_modules/angular2/*',
    'rxjs/*': 'node_modules/rxjs/*',
    'angular2-jwt/*': 'node_modules/angular2-jwt/*'
  }
};
// ...
```

app.ts
```
import * as jwt from 'angular2-jwt/angular2-jwt';

let x = jwt;
console.log(x);
```

//cc @guybedford any idea why only this config works and not direct module access?

**Comment by ludohenin** [comment]
@krzysztofsaja Would you try the same with `ng2-bootstrap`?

**Comment by guybedford** [comment]
@ludohenin I believe this was the bug just fixed in https://github.com/systemjs/systemjs/commit/60b3fc003140e1097f829e51b1f9d5555d4dd551 actually, which will be released shortly. Apologies for the regression.

**Comment by ludohenin** [comment]
@guybedford excellent, and thanks for your (ultra) quick answer.

**Comment by ludohenin** [comment]
@gustavolira @krzysztofsaja would you test with the latest master (acef35c)

**Comment by Bigous** [comment]
It's working for me!

**Comment by d3viant0ne** [comment]
@ludohenin Works on latest master for me as well :)

**Comment by gustavolira** [comment]
@ludohenin For me the producion bundle is working for me, the problem now is dev environment, I'm receiving 404 for app.html (not happening with prod) I'm already using relative paths, like:
`module: module.id,
 templateUrl: './app.html'
`
This is happening with my app (already has several components), not with fresh angular2-seed

**Comment by ludohenin** [comment]
@gustavolira Can you try with removing `module.id` ? 
or by removing this line (for dev only) https://github.com/mgechev/angular2-seed/blob/master/src/index.html#L36

**Comment by d3viant0ne** [comment]
@ludohenin Looking at it now

**Comment by ludohenin** [comment]
my last suggestions doesn't make a lot of sense ...

**Comment by d3viant0ne** [comment]
And oddly enough, works though I have no idea why

**Comment by d3viant0ne** [comment]
@gustavolira - Can you hop in the gitter chat. Probably be quicker to try and work this out there.

**Comment by gustavolira** [comment]
I'm there how can I find you there? I've never used gitter before

**Comment by gustavolira** [comment]
See the problem:
http://i.imgur.com/oA7Wgqc.png
http://i.imgur.com/j1dOvsL.png
http://i.imgur.com/yvAboeZ.png

**Comment by gustavolira** [comment]
If I change to `templateUrl: './app/components/app.html',` DEV works but at PROD build I receive this error message: 
`Unhandled rejection Error on fetch for tmp/app/components/app.js at file:///home/gustavo/git/issuerFront/tmp/app/components/app.js
	Loading tmp/main.js
	Error: ENOENT: no such file or directory, open '/home/gustavo/git/issuerFront/tmp/app/components/app.js'
    at Error (native)
`

I cant get both DEV and PROD working, It's one or another

**Comment by d3viant0ne** [comment]
@gustavolira Just getting home. I'll dig into this shortly.

**Comment by d3viant0ne** [comment]
@gustavolira - In the [README.md](https://github.com/mgechev/angular2-seed) there is a little badge that says "Gitter Join Chat"

Click that it will launch Gitter in a browser window, click the "join chat" button on the bottom and it will land you in chat room (It's based off of git creds). I'll be working but around all day, message me when you have some time and we will work this issue out.

**Comment by gustavolira** [comment]
I just see what was the problem and I want to kill myself but before this I want to apologize with all of you because my lack of attention.
I was using `module: module.id` instead of `moduleId: module.id`

**Comment by mgechev** [comment]
@gustavolira no worries, mistakes happen. Glad we helped!
