### ISSUE TITLE
Component names do not adhere to style guidelines

### ISSUE THREAD

**Issue by nareshbhatia** [mgechev/angular2-seed#486]
According to the [Angular 2 Style Guide](https://github.com/mgechev/angular2-style-guide#directives-and-components):

> The name of any directive or component should be formed following the rule BasicDescription + Directive or Component.

The angular2-seed project uses names like `AppCmp`, `HomeCmp` and `AboutCmp`. These should be changed to `AppComponent`, `HomeComponent` and `AboutComponent`.

**Comment by ludohenin** [comment]
This is also true for the file names I guess (`app.component.ts`)

**Comment by nareshbhatia** [comment]
Ah, yes! Thanks for reminding.

As a side, the only place I don't use a suffix is when defining domain entities. For example, I like `Person`, `Company`, `Order` as opposed to `PersonEntity` or `PersonModel`. `Person` just feels more natural.

**Comment by ludohenin** [comment]
yeah and those entites/models probably live under entities/models folder anyway.

**Comment by nareshbhatia** [comment]
Yep. I usually call that folder `domain`, but I have seen people name it `models` also. I am good with either.

BTW, should I work on a PR to change `Cmp` to `Component` and use the `component.ts` suffix on files.

**Comment by ludohenin** [comment]
@nareshbhatia not sure
Maybe @mgechev will prefer to wait for a larger consensus on this part of the style guide?

**Comment by d3viant0ne** [comment]
@ludohenin - Based on his latest summary comment, i think type suffix is pretty much set. mgechev/angular2-style-guide#5

**Comment by evanplaice** [comment]
@d3viant0ne @nareshbhatia @ludohenin I added issue #490 to cover file naming.

Since these changes require a considerable amount of [Shotgun Surgery][https://en.wikipedia.org/wiki/Shotgun_surgery].

To avoid unnecessary merge conflicts, I suggest this change waits until https://github.com/mgechev/angular2-seed/pull/489 lands. File renaming can follow the PR that resolves this issue.

**Comment by Bigous** [comment]
If we will go with the recommended, so we should remove the directories "components",  "services", "pipes", because it follows the same logic of "Models" and "Entities".
I prefer the way it is today (everything following the "Models" and "Entities" pattern), but I think it's a matter of taste.

**Comment by d3viant0ne** [comment]
@Bigous The discussion related to the changes here is going on in mgechev/angular2-style-guide#5
It has all of the background, reasoning and counter arguments. Please feel free to add to the discussion :)
