### ISSUE TITLE
XHR error 404 not found

### ISSUE THREAD

**Issue by gregkuha60** [mgechev/angular2-seed#497]
This service
import {Injectable} from 'angular2/core';
import {SUPPLIERS} from '../../supplier/components/moch-suppliers.ts';
import {Supplier} from '../../supplier/components/supplier.ts';

@Injectable()
export class SupplierService {
    getSuppliers() {
        return Promise.resolve(SUPPLIERS);
    };
   getSuppliersSlowly() {
        return new Promise<Supplier[]>(resolve =>
            setTimeout(() => resolve(SUPPLIERS), 2000) // 2 seconds
        );
    }
};
Causes this error
Error: XHR error (404 Not Found) loading http://localhost:5555/shared/services/supplier.service.ts.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

However in dis/shared/services/ folder there is a file with the name supplier.service.js
What i'm i missing?

**Comment by ludohenin** [comment]
@gregkuha60 remove the `.ts` extension! from the `import` statement.
