### ISSUE TITLE
Loading moment.js locale's

### ISSUE THREAD

**Issue by Myrmex** [mgechev/angular2-seed#499]
I'm trying to load moment.js into this seed as follows:

1. npm install --save moment
2. typings install --save --ambient moment
3. typings install --save --ambient moment-node
4. add to the Systemjs `paths` in `SYSTEM_CONFIG_DEV` (`config.ts`) this one:

    'moment': `${APP_BASE}node_modules/moment/moment`,

5. finally, import like:

    import * as moment from 'moment';

This works fine. My issue is that I'm not able to load any locale, using method calls like `moment.locale('it');`. The moment source (function `loadLocale`) uses this code to load:

    require('./locale/' + name);

Thus, AFAIK this should already let the import work. Yet this does not happen. Googling around, I found only this link: https://github.com/moment/moment/issues/2962. Could anyone help?

**Comment by mgechev** [comment]
You can write a task which copies the content of `node_modules/moment/locale` to `src`. This way the resources will be available to the application.
