### ISSUE TITLE
Really slow `build.prod`

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#500]
After updating to latest code, where @ludohenin has done significant improvements to the prod build, we unfortunately have a very slow build proces

(at least after commit f335cd52ea25219fe1c04338fa1c156aaa32dc46 )

I believe that the reason is that the build now bundles all angular resources along with all the application files. Imagine that every build must minify and combine all files from angular. Every time.

In my setup, I want to run continuous deployment on every merge of pull-requests. Unfortunately, with this change, the server times out at 10 minutes unable to finish the build.

I usually recommend building into two files: a `vendor.js` and a `application.js`. This way, I can build only what I want and when I change it.

In this project, however, I have not fully understood how the production build works. 

If I were to split the production build, where should I modify?

**Comment by jesperronn** [comment]
wow! issue #500 :) good that so few are actually open :+1:

**Comment by ludohenin** [comment]
@jesperronn Every happens here: https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/build.bundles.app.ts#L21-L23
And here is an implementation of a multiple-bundles ready task https://github.com/ludohenin/ng2-wp-blog/blob/master/tools/tasks/build.bundles.ts#L16-L24, you can add an extra build for `vendors` for instance ... adapt the arithmetic as you like.

**Comment by jesperronn** [comment]
Suggestion: We could change prod to 'just' concat the vendor files. They are already minified once for a release. 

..hmm that is probably what @ludohenin is doing in https://github.com/ludohenin/ng2-wp-blog/blob/master/tools/tasks/build.bundles.ts#L16-L24
