### ISSUE TITLE
Support main file of installed npm dependencies

### ISSUE THREAD

**Issue by jeffbcross** [mgechev/angular2-seed#502]
Take for example, [angularfire2](https://github.com/angular/angularfire2). It declares a main file in its [package.json](https://github.com/angular/angularfire2/blob/master/package.json#L5), `angularfire2.js`.

If I try to import a symbol without specifying a path to a file, a 404 occurs:

```ts
import {FIREBASE_PROVIDERS, defaultFirebase} from 'angularfire2';
```

```
GET http://localhost:5555/node_modules/angularfire2.js 404 (Not Found)
```

I _think_ the fix should be as simple as setting the `main` field in `System.config.packages.angularfire2` to the value from `package.json.(main|browser)` 'angularfire2.js'. I can open a PR once I figure out where to do that...

**Comment by jeffbcross** [comment]
Worth noting, I know the easy fix to this issue is to import from angularfire2/angularfire2.

**Comment by beaverusiv** [comment]
This is an issue for me too, where I can explicitly put a full path but then it fails on a dependency of the lib. My example is [angular2-config](https://www.npmjs.com/package/angular2-config) which fails as
> http://localhost:5555/node_modules/angular2-config.js

But if I import from `'angular2-config/dist/index'` it fails on
> http://localhost:5555/node_modules/nested-property.js

which is it's dependency.

**Comment by ludohenin** [comment]
@jeffbcross @beaverusiv I suppose what you are looking at it [here](https://github.com/mgechev/angular2-seed/blob/master/tools/config.ts#L94-L116).

That's maybe not the right place for this discussion but IMO, following the simple convention `{package_name}/{module_name}` for your packages (instead of some other fancy ones) make things so much easier (no need of specific config for every packages).

**Comment by jeffbcross** [comment]
> following the simple convention {package_name}/{module_name} for your packages

For the sake of simplicity, let's assume I'm only a consumer of packages, not an author. I'd venture to guess that most modules don't adhere to importing via `package/module`. We did it with Angular 2 because Angular 2 is big and supports many platforms, and provides several optional submodules. So for most npm packages, I would have to either import from `package/index.js` or figure out what the main file is and import that, `angularfire2/angularfire2.js`. 

> (no need of specific config for every packages).

Declaring a main entry is a convention already supported by node's module resolution via the `main` field of package.json and System config via the `main` field of packages config. It wouldn't require package-specific configuration; it would just be a build step to look at the package.json of the package and see if it declares a main file, or if it has an index.js file, and then add it to the system config.

**Comment by Bigous** [comment]
@ludohenin I think that this behavior was implemented in Typescript itself (on version 1.6.3 if my memory is not wrong). So, I think this could be a feature request to SystemJS?

**Comment by beaverusiv** [comment]
I am wondering if something like [system-npm](https://github.com/stealjs/system-npm) should be used? I've tried integrating myself to no avail, and also looking into issues with SystemJS - of which their official line is "not my problem" when asked about using node-like loading algorithms.

**Comment by mgechev** [comment]
For the first-level dependencies we can generate the configuration with something like that:

```ts
function generateConfig(root) {
  return fs.readdirSync(root).map(f => {
    var path = join(root, f, 'package.json');
    if (fs.existsSync(path)) {
      return [f, require(`.${sep}${path}`).main];
    }
  })
  .filter(p => p && p[1] && !/^index\.js|index$/.test(normalize(p[1])))
  .reduce((res, c) => {
    res[c[0]] = { main: c[1] };
    return res
  }, {});
}
```

This works well in most cases with the flat structure of npm. However, in case we have nested dependencies, therefore name collisions of dependencies with different versions, it won't be trivial to resolve them when required.

It doesn't work with `angularfire2` because of its dependency `firebase`, which exports two bundles:

- main - which is the node module
- browser - which is the browser bundle

If I change the above implementation to:

```ts
if (fs.existsSync(path)) {
  let package = require(`.${sep}${path}`);
  return [f, package.browser || package.name];
}
```

it fails because other modules are using the `browser` field in `package.json` differently.

**Comment by beaverusiv** [comment]
Would it be better to approach packages with Bower? Would that solve the issue?

**Comment by mgechev** [comment]
@beaverusiv bower, with its flat directory structure, will be a workaround rather than a solution.

The possible case I see is to use the above solution and allow developers to customize the configuration further if required.

**Comment by mgechev** [comment]
@jeffbcross do you have any ideas on this one?

**Comment by jeffbcross** [comment]
> However, in case we have nested dependencies, therefore name collisions of dependencies with different versions, it won't be trivial to resolve them when required.

@mgechev the tooling could just support `peerDependencies` and leave it up to manual configuration if nested dependencies are required. For cases where manual editing is required, perhaps a couple of commented-out lines could be added to the system config to give hints where a package needs to be configured:

```js
System.config({
  map: {
    /** 
     * Package "firebase" needs to be configured.
     * See: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md
     **/
    // firebase: 'node_modules/firebase/',
    'angularfire2': 'node_modules/angulafire2/'
  },
  packages: {
    angularfire2: {
      main: 'angularfire2.js',
      format: 'cjs',
      defaultExtension: 'js'
    }
  }
})
```

**Comment by mgechev** [comment]
@jeffbcross we're setting `packageConfigPaths` [here](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L119).

This seems to solve the problem of using the `main` file, to some extent. Do you think we're good here or SystemJS needs further hints?

**Comment by mgechev** [comment]
Closing the issue for now until we renew the discussion if necessary.
