### ISSUE TITLE
over complicated

### ISSUE THREAD

**Issue by nhhockeyplayer** [mgechev/angular2-seed#505]
I find the build infrastructure to be in order with
  o  jspm
  o  webpack

and the countless issues surrounding TSD & TYPINGS
whereby everything is incoherent and over complicated

they cannot even implement a damn wildcard to compile all *.ts files

burying everything into massive config and build files is atrocious

and I remain unimpressed with google, and all the open source hackers that have created a nightmare for any individual trying to perform a simple hello world typescript angular2 web app.

on a scale of 1..12 I grade this app a 3
it has all the ingredients
but all the ingredients are smeared all over the place and too numerous before it even gets to index.html

needs to be cut down and simplified to 3 files tops

typings is a disaster in itself and they cannot even fix the duplicate identifier issue
angular releases to releases have huge sections on CRASH CHANGES

**Comment by d3viant0ne** [comment]
@nhhockeyplayer - If you want to avoid Typescript, there are a few pure ES6 offerings floating around.

This one for instance by @blacksonic is a good place to start https://github.com/blacksonic/angular2-es6-starter
