### ISSUE TITLE
styleUrls doesn't allow to link to external css file

### ISSUE THREAD

**Issue by tandu** [mgechev/angular2-seed#508]
Before this was working
`component.ts`
```typeScript
  styleUrls: [
    './my_framework/default.css',
    './components/component/component.css'
  ]
```
now with this code
```typeScript
  moduleId: module.id,
  styleUrls: [
    './my_framework/default.css',
    './component.css'
  ]
```
I get this error in browser:
```
"EXCEPTION: Failed to load http://localhost:5555/components/component/my_framework/default.css"
```
I tried these urls with no success: `my_framework/default.css`, `/my_framework/default.css`, `../../my_framework/default.css`.

**Comment by UnnoTed** [comment]
you can use `styles: []` instead of `styleUrls: []` and require the file as string `styles: [ require('./component.css') ]`

**Comment by tandu** [comment]
`require` adds `.js` to the end. Actually it was my mistake - I had to add `../../../` instead of `../../`. Relative paths are working.
