### ISSUE TITLE
Home is not loaded on page-load in the production build

### ISSUE THREAD

**Issue by giejay** [mgechev/angular2-seed#509]
Did a clean checkout of the git repo (to check if the problem did not occur due to any of my modifications), ran npm install and npm run build.prod which results in: http://giejay.nl/test/

I need to click home link for the home controller/view to load, how can I fix it to automatically load?

**Comment by Bigous** [comment]
Not occurring on my environment:
Windows 10 - node 4.3.1 - npm 2.14.12
sequence:
```
git clone https://github.com/mgechev/angular2-seed.git angular2-seed
cd angular2-seed
npm install
npm run build.prod
http-server dist/prod
```
List of global packages installed:
```
├── http-server@0.8.5
├── ts-node@0.5.5
├── tsd@0.6.5
├── typescript@1.9.0-dev.20160210
└── typings@0.6.7
```
Could you specify your environment @giejay ?

**Comment by giejay** [comment]
Windows 10 - Node 4.0.0 - npm 2.14.2

Is my url working for you?

**Comment by giejay** [comment]
When using http-server, it works fine. When I open the index.html in chrome manually, the same error occurs.

**Comment by d3viant0ne** [comment]
@giejay - I'm looking at it now. Just a sec

**Comment by d3viant0ne** [comment]
@giejay - The production build off of current master works fine running on my local apache

![screen shot 2016-02-17 at 3 17 01 pm](https://cloud.githubusercontent.com/assets/8420490/13125103/99912244-d589-11e5-991c-f67752772e07.png)

**Comment by d3viant0ne** [comment]
Actually, that was npm install && npm serve.prod 

Then I coppied the dist/prod contents to web root.

Let me try that with build.prod

**Comment by giejay** [comment]
And what happens when you just open the index.html in a browser? Without a server

**Comment by d3viant0ne** [comment]
@giejay - I have tried the prod build in the master branch on ..

serve.prod locally
build.prod hosted on local apache ( OSX 10.11.3 )
build.prod hosted on EC2 apache2 server running on ubuntu 14.04.3

All three of those options load the root route as they should.

**Comment by Bigous** [comment]
I don't know why, but opening index.html from dist/prod direct from chrome (without a webserver) the css is not resolved... no response comes and no error is generated... but with any webserver I've tryed works...
Maybe FILE protocol does not fits the requirements to run the system which was made to run using HTTP protocol (cookies, etc...) see the [reference](https://developer.mozilla.org/en-US/Learn/Open_a_file_in_a_browser)

**Comment by Bigous** [comment]
Ok, first things first.

The problem with FILE protocol is true. But there is a problem with prod build.
When I tried:
 ```
git clone https://github.com/mgechev/angular2-seed.git angular2-seed
cd angular2-seed
npm install
npm run build.prod
http-server .
```
And tried to open chrome with the URL: ```http://127.0.0.1:8080/dist/prod/``` I get the same error that @giejay reported.
So, congrats :D you found a bug :D

**Comment by Bigous** [comment]
@ludohenin could you help with this one?

**Comment by Bigous** [comment]
I see no error on chorme and the only file that ```http-server``` doesn't serve is favicon.ico which doesn't exists.
Maybe the router is getting lost...

**Comment by Bigous** [comment]
Just to confirm:
Updating app.ts to this, solves the problem, but I didn't like the solution :D
```typescript
import {Component, ViewEncapsulation, OnInit} from 'angular2/core';
import {
  RouteConfig,
  ROUTER_DIRECTIVES,
  Router
} from 'angular2/router';

import {HomeCmp} from '../../home/components/home';
import {AboutCmp} from '../../about/components/about';
import {NameList} from '../../shared/services/name_list';

@Component({
  selector: 'app',
  viewProviders: [NameList],
  moduleId: module.id,
  templateUrl: './app.html',
  styleUrls: ['./app.css'],
  encapsulation: ViewEncapsulation.None,
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  { path: '/', component: HomeCmp, name: 'Home' },
  { path: '/about', component: AboutCmp, name: 'About' }
])
export class AppCmp implements OnInit {
  constructor(private _router: Router) {}
  ngOnInit() {
    this._router.navigate(['Home']);
  }
}
```

**Comment by d3viant0ne** [comment]
@Bigous There is no active route when the page loads outside of some sort of http server.

So while I agree about your comment on that solution, it's not too far off the mark as to the issue.

**Comment by d3viant0ne** [comment]
@giejay - A side question. If it works on an apache server. Is there a reason why you can't just npm run serve.prod ?

Workaround until we can figure out the funky route issue

**Comment by giejay** [comment]
I'm hosting it on a server which just has a simple php server (I think, don't know exactly what is running on it) which is outside of my control. I just ftp'ed the files to that server and the issue occurred.

**Comment by ludohenin** [comment]
@Bigous 
> And tried to open chrome with the URL: http://127.0.0.1:8080/dist/prod/ I get the same error that
If you want to do so, you have to set the `APP_BASE`. otherwise `http-srver ./dist/prod`

**Comment by ludohenin** [comment]
the route `/dist/prod/` doesn't exist.

**Comment by ludohenin** [comment]
@giejay Can you please try with setting `APP_BASE` ... `npm run build.prod -- --base /test/`

**Comment by ludohenin** [comment]
It will not work as [this line](https://github.com/mgechev/angular2-seed/blob/master/src/main.ts#L10) isn't correct. It should be 
```es6
provide(APP_BASE_HREF, { useValue: '<%= APP_BASE %>' })
```

Will fix it today.

**Comment by Bigous** [comment]
:+1:
