### ISSUE TITLE
IE: Issue with app.js bundle, when minify is set to "true" for systemjs builder

### ISSUE THREAD

**Issue by dimarzionist** [mgechev/angular2-seed#510]
When opening production dist in IE11, you get syntax error in app.js.
Appears after migration from browserify to sustemjs builder.
Only happens when "minify" set to true for bundler options.

Please see the attachment for full snapshot of error log console from IE. 
IE11,
npm 3.7.2
node 5.3.0

EXCEPTION: SyntaxError: Expected ')'
   EXCEPTION: SyntaxError: Expected ')'
   STACKTRACE:
   SyntaxError: Expected ')'
   at evalExpression (file:///C:/dev/git/angular2-seed/dist/prod/js/app.js?1455752277346:27:30172)
   at TemplateCompiler.prototype._createViewFactoryRuntime (file:///C:/dev/git/angular2-seed/dist/prod/js/app.js?1455752277346:8:20302)
   at Anonymous function (file:///C:/dev/git/angular2-seed/dist/prod/js/app.js?1455752277346:8:17949)
...

![capture](https://cloud.githubusercontent.com/assets/631258/13129128/e0b3cf50-d62e-11e5-89ef-9f665e5d6a66.PNG)

**Comment by Bigous** [comment]
Just to add some information... on Microsoft Edge (aka IE 12) the problem does not occurs.

**Comment by d3viant0ne** [comment]
@dimarzionist I'll spin up a windows vm and take a look at this

**Comment by d3viant0ne** [comment]
@Bigous Can you tag this one, That's confirmed on Win10/IE 11

**Comment by d3viant0ne** [comment]
I'll see if I can run down the "why" portion

**Comment by dimarzionist** [comment]
Could be related to this:
https://github.com/angular/angular/issues/6695

**Comment by d3viant0ne** [comment]
It is the compression version of the problem. it works if you just mangle it.

**Comment by Bigous** [comment]
Removed the bug label - @dimarzionist is right.

**Comment by Bigous** [comment]
Mangle the code can cause another issues in injector according to the same issue report.
