### ISSUE TITLE
prod build fails with subfolder structure

### ISSUE THREAD

**Issue by neridonk** [mgechev/angular2-seed#514]
I have a folderstructure which is like :

/components/admin/part/part.ts

when I try to call the part.ts via router navigate I get an error where the browser looks in dev structure

> Error: XHR error (404 Not Found) loading  http://localhost:85/lizi//components/admin/part/part

when my file is on /components/part/part.ts all works fine

**Comment by d3viant0ne** [comment]
tools/tasks/build.js.prod.ts

```javascript
    let src = [
      'typings/browser.d.ts',
      'tools/manual_typings/**/*.d.ts',
      join(APP_SRC, '**/*.ts'),
      '!' + join(APP_SRC, '**/*.spec.ts'),
      '!' + join(APP_SRC, '**/*.e2e.ts')
    ];
```

File glob only looks one level deep, so no that wouldn't work. Given this project is being moved inline with the style-guild, it may or may not be changed for nested child components.

None the less, just add a joint that grabs your child components.

@mgechev @ludohenin - Have we solidified child components enough for this to be modified or should @neridonk just stick with the work around.

May also be a good idea to move the file globs into the config so this is easily modifiable.

**Comment by ludohenin** [comment]
> File glob only looks one level deep, so no that wouldn't work. Given this project is being moved inline with the style-guild, it may or may not be changed for nested child components.

Nope, the glob looks deeper than one level (I haven't checked the source but I'd guess it's an "infinite" recursive lookup).

For ref, [this one](https://github.com/ludohenin/ng2-wp-blog/tree/master/src/components/blog/components/post) works like a charm :)

@neridonk Can you share you're project (I suspect a wrong import somewhere)?

**Comment by d3viant0ne** [comment]
I'm going to stop commenting on issues until I finish my coffee and put my damn glasses on 

**/* (derp)

**Comment by neridonk** [comment]
Ohhhh damit when i looked today in my project i found 

  new AsyncRoute({
    path: '/about',
    loader: () => System.import('./components/admin/admin/about').then(m => m.About),
    name: 'about'
  })


changed it to this ->

loader: () => Promise.resolve()

sry for making a bit trouble but thank you!
