### ISSUE TITLE
gulp clean does not erase files

### ISSUE THREAD

**Issue by professorviz** [mgechev/angular2-seed#516]
When I run ```gulp clean.dev```, I expect the dist/dev directory to be deleted. However, the dist/dev directory still exists.

Steps to reproduce:

- Pull this repository
- ```npm install```
- Run ```npm start``` to generate a dist/dev folder
- ```ls dist/dev``` to verify the files are built
- ```gulp clean.dev``` to clean the files in dist/dev
- ```ls dist/dev``` - I see that the built files still exist. We expect ```gulp clean.dev``` to remove the files in dist/dev

Thanks!

**Comment by d3viant0ne** [comment]
I'll take care of this shortly, thanks :)
