### ISSUE TITLE
"npm test" fails at the end.

### ISSUE THREAD

**Issue by manish5377** [mgechev/angular2-seed#521]
[npm-debug.txt](https://github.com/mgechev/angular2-seed/files/138862/npm-debug.txt)

Hi,

I am fairly new to Angular2 and was trying this seed project. it fails at the end if in run "npm test".

![image](https://cloud.githubusercontent.com/assets/2945833/13192096/474dcebe-d72e-11e5-9140-8af148a53cd0.png)

Can someone guide, if I missing something OR is an issue.

**Comment by mgechev** [comment]
@manish5377 would you try:

```bash
rm -rf node_modules
npm cache clean
```

Or the equivalent on Windows, and try again.

**Comment by manish5377** [comment]
Thanks a lot @mgechev ...It worked....
