### ISSUE TITLE
Including a javascript library inside a component

### ISSUE THREAD

**Issue by NathanielMalca** [mgechev/angular2-seed#527]
I'm trying to implement lazy loading as you've showed at your post addressing this subject: http://blog.mgechev.com/2015/09/30/lazy-loading-components-routes-services-router-angular-2

Now, in one of the components that i want to lazyload i use a simple easy to use javascript library , for that matter a library called "country-list".

Of course i'm not interested of including the file at the DEV_NPM_DEPENDENCIES or PROD_NPM_DEPENDENCIES because i want it to be loaded only when i route to that specific component 

I've tried to use" let countryList= require('country-list') " but the require doesn't point to the right path at the browser ( not entering the node_modules folder).

I've also tried to do it as the Wiki says with the following declaration at the component head : 
" import * as countryList from 'country-list/country-list' " -  this gives me a typescript compilation error.

How can i accomplish it  ?

thanks

**Comment by mgechev** [comment]
Hey @NathanielMalca you need to configure SystemJS [for this purpose](https://github.com/mgechev/angular2-seed/blob/master/tools/config.ts#L97-L111).

Also note that for implementing lazy loading the production build will need a lot of customization since it should not provide only a single bundle.

**Comment by NathanielMalca** [comment]
Hey @mgechev. First, I have great respect to the work you and the others contributors have put to this Angular 2 seed. With that said  , Since i see lazy loading as a fundamental part of real-world applications . Don't you believe that all these optimizations should  be an integral part of the seed itself ?

**Comment by mgechev** [comment]
@NathanielMalca you're correct about this. The problem of lazy loading is that it highly depends on the domain of your application.

What we can do in the seed is to provide separate bundles for the individual "bounded contexts" we have. For sure it'll be a good idea to add it to our roadmap.
