### ISSUE TITLE
Unable to use map operator of RxJs

### ISSUE THREAD

**Issue by kambojankit** [mgechev/angular2-seed#529]
I am trying to retrieve a rest API response with following code:

Given:
```
import {Injectable} from 'angular2/core';
import {Http, Response} from 'angular2/http';
import {Observable}     from 'rxjs/Observable';
```

And proper injection:
```
constructor (private http: Http) {

	}
	_base_URL: string = 'http://manin-arhatech.rhcloud.com/services/marketplace/ManageFlipkart/getOrders';
```

and following code to hit the API
```
this.http.get(this._base_URL)
			.map(res => <any>res.json())
			.catch(this.handleError);
```.


I get the below error on console log:
`TypeError: this.http.get(...).map is not a function in [null]`

**Comment by ludohenin** [comment]
@kambojankit I have to use `subscribe`
```
this.http.get(this._base_URL)
            .subscribe(res => <any>res.json())
            .catch(this.handleError);
```

**Comment by NathanWalker** [comment]
I believe you're just missing this:
import 'rxjs/add/operator/map';

Add with other imports :)

**Comment by kambojankit** [comment]
Thanks for the response, the import statement was missing.
It works now.

> Note: Was using subscribe with the actual function call instead.

**Comment by dave0783** [comment]
> I believe you're just missing this:
> 
> import 'rxjs/add/operator/map';
> Add with other imports :)

This doesn't work for me.

`.map()` still yields ``TypeError: this.http.get(...).map is not a function in [null]``

**Comment by d3viant0ne** [comment]
@dave0783 - ` add the code block and we can try and help  `

**Comment by vijaypatel** [comment]
This is the code snippet 
`import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';

import { Observable } from 'rxjs/Observable';

import 'rxjs/add/operator/map';

import { IApplication } from './IApplication'
import { AppSettings } from './../appSettings'

@Injectable()
export class ApplicationService {
    private applicationUri = 'api/application/getall';

    constructor(private _http: Http) {
    }

    getApplications(): Observable<IApplication[]> {
        let uri = AppSettings.BaseAddress + this.applicationUri;
        return this._http.get(uri)
            .map((response: Response) => <IApplication[]>response.json())
            .catch(this.handleError);


    }

    handleError(error: Response) {
        console.log(error);
        return Observable.throw(error.json().error || 'Server error');
    }
}`

**Comment by pruthvip** [comment]
import 'rxjs/add/operator/map'; is not working. Is there a solution ?

**Comment by vijaysaluru** [comment]
similarly missing import issue with your for .catch operator ..

`import 'rxjs/add/operator/catch';`

**Comment by ashishsharma123** [comment]
may be there is compatibility issue with rxjs and angular compiler version otherwise there is nothing wrong with syntax of map import.
you can try importing like this:
 **import 'npm:rxjs@5.4.0-beta.12/add/operator/map';**  
this will import the latest version of rxjs.

Hope this will work for you :)

**Comment by mariannafld** [comment]
Hello, I have the same problem but only in production mode. Operator map is imported.
```
vendor.4986ce3c7de5198c6356.bundle.js:1 ERROR TypeError: this.httpClient.post(...).map(...).do is not a function
    at n.getDatasets (main.88e8b3d8041b47d43993.bundle.js:1)
    at n.getDatasets (main.88e8b3d8041b47d43993.bundle.js:1)
    at n.ngOnInit (main.88e8b3d8041b47d43993.bundle.js:1)
    at ln (vendor.4986ce3c7de5198c6356.bundle.js:1)
    at Jn (vendor.4986ce3c7de5198c6356.bundle.js:1)
    at Yn (vendor.4986ce3c7de5198c6356.bundle.js:1)
    at kr (vendor.4986ce3c7de5198c6356.bundle.js:1)
    at Object.updateDirectives (main.88e8b3d8041b47d43993.bundle.js:1)
    at Object.updateDirectives (vendor.4986ce3c7de5198c6356.bundle.js:1)
    at Qn (vendor.4986ce3c7de5198c6356.bundle.js:1)
```

**Comment by mdarfilal** [comment]
@mariannafld 
use pipe.
see : https://github.com/angular/angular/issues/20460#issuecomment-344697675

**Comment by kasraJannati** [comment]
@mariannafld  pipe will be work for map ,but what about catch?

**Comment by zaxaco** [comment]
@kasraJannati  use pipe with catchError 
don't forget to import it.
import { catchError } from 'rxjs/operators';
