### ISSUE TITLE
Use as dependency

### ISSUE THREAD

**Issue by czosel** [mgechev/angular2-seed#531]
First of all: Thank you for this awesome seed! :+1: 

I only started using the seed a couple of days ago, and i hope i'm not missing anything obvious. My question goes along the lines of #506 but adds another twist to it - my use case is the following:

I have multiple angular 2 apps, which should all be based on the same fork of angular2-seed. Improvements to my version of the seed should obviously only be done at one place, so it would be nice if one could just load and use the seed as a dependency via npm. 

My first approach goes like this: Add `export = gulp;` àt the end of `gulpfile.ts`, make all devDependencies in `package.json` actual dependencies, publish the fork on npm (private), and use it in a new gulpfile like this: 

```javascript
import gulpconf = require('my-angular2-seed/gulpfile');

// has to be used, otherwise it doesn't seem to survive compilation
const conf = gulpconf;
```
Unfortunately i don't quite manage to get it to work right now (currently struggling with the fact that some dependencies can't be found) - but before going more into detail (i'd be happy to share the code if it is of interest) it would be great to get some feedback on the approach - maybe there's a much simpler way to do this?

Maybe my problem solves itself when `/tools` is dependency of the seed, which would allow me to just reference `/tools` (or my fork of it) in my angular apps. 

Thank you in advance!

**Comment by d3viant0ne** [comment]
@czosel - We have decided against going the npm package route.

The plan to make this easier to maintain & reuse can be found here - https://github.com/mgechev/angular2-seed/pull/528

**Comment by ludohenin** [comment]
Yes I _think_ it will be a lot easier to support multiple projects when the refactored tools will land, but will think about it. Would be nice to support it but what about dependencies and version management, just to name those.

@czosel does that mean you use a single repo for all your apps ?

**Comment by czosel** [comment]
@d3viant0ne thanks - i will definitely try the refactored tools.

@ludohenin No, on the contrary: I have several apps, all in their own repository. The apps have very similar demands (same look and feel, common services and directives, ... ) - thats why i'd like to have the same build process for all of them, but maintain and extend it at one place only. The idea stems from a Grunt-based build process for an older angular 1 stack, where i did exactly the same. There is definitely some redundancy for dependency and version management, but in the old stack i was able to keep most of the heavy lifting outside of the actual app.

**Comment by mgechev** [comment]
@czosel since there's no progress on this issue lets close it. If you have any progress with this I'd love to keep me up to date!
