### ISSUE TITLE
Error when try to build production

### ISSUE THREAD

**Issue by harishk90** [mgechev/angular2-seed#538]
Before submitting the issue, take a look at the already existing solutions to:

- [x] `Cannot find module '...'` - your issue is related to not existing type definitions.
- [x] Adding [sass support](https://github.com/mgechev/angular2-seed/wiki/Add-custom-Gulp-task).
- [x] Adding [external styles](https://github.com/mgechev/angular2-seed/wiki/Add-an-external-styles).
- [x] Configuring [SystemJS](https://github.com/mgechev/angular2-seed/issues/499).
- If you are not sure your configuration is correct, please take a look at the documentation of [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md), [typings](https://github.com/typings/typings/blob/master/README.md) and [gulp](https://github.com/gulpjs/gulp/blob/master/docs/README.md).

**Comment by harishk90** [comment]
when try to build production(gulp buid.prod),got this error :Unhandled rejection Error on fetch for dist/tmp/app/components/app.js at file:///C:/evolumi/src/webapp/dist/tmp/app/components/app.js

**Comment by harishk90** [comment]
when try to build production(gulp buid.prod),got this error :

Unhandled rejection Error on fetch for dist/tmp/app/components/app.js at file:///C:/evolumi/src/webapp/dist/tmp/app/components/app.js

**Comment by d3viant0ne** [comment]
@harishk90 - This a github project one of us can go look at?

Can't find file X is almost always a config problem or a project that it out of sync with the seed tools. Both of which are hard to figure out without being able to see it.

**Comment by angelmalca** [comment]
:+1: 

Unhandled rejection Error on fetch for dist/tmp/UserManagement/components/user-management.js at file:///C:/angeltemp/WU24-3-2016/dist/tmp/UserManagement/components/user-management.js
        Loading dist/tmp/app/components/app.component.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'C:\angeltemp\WU24-3-2016\dist\tmp\UserManagement\components\user-management.js'
    at Error (native)

**Comment by angelmalca** [comment]
@d3viant0ne when you say config issue what do you mean ? i have download the latest seed and still this is what i see after prod.build . where in the project can i look to check what is wrong with the configuration ?
