### ISSUE TITLE
 Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev'.

### ISSUE THREAD

**Issue by Attimo91** [mgechev/angular2-seed#543]
nodejs: 4.3.1
npm: 2.14.7

i did everything that was in readme and i got this error:
npm ERR! Linux 3.16.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

**Comment by d3viant0ne** [comment]
@Attimo91 - Master works fine on OSX / Ubuntu 14.04.3 / WIndows ( ick )

![screen shot 2016-02-27 at 9 18 31 am](https://cloud.githubusercontent.com/assets/8420490/13373667/3a63f36c-dd33-11e5-9634-8170837b5d80.png)

**Comment by ReneVallecillo** [comment]
![screenshot from 2016-02-27 15 45 05](https://cloud.githubusercontent.com/assets/424273/13375574/1aaa8316-dd69-11e5-9868-c3c512259311.png)

Having the same problem

**Comment by d3viant0ne** [comment]
@ReneVallecillo - What node version are you running?

**Comment by Attimo91** [comment]
@d3viant0ne
not for me. I have ubuntu 14.04, fresh instalation of nodejs and npm.

**Comment by d3viant0ne** [comment]
I'll take a look, give me a minute

**Comment by ReneVallecillo** [comment]
@d3viant0ne 

```
rene@rene-Unix:~/Development/Angular2/penshiru$ node -v
v0.12.7
```

**Comment by d3viant0ne** [comment]
@Attimo91- This is a fresh Ubuntu LTS VM
Ubuntu: 14.04.4
NodeJS: v4.3.1
npm: v2.14.12

Running current master of https://github.com/mgechev/angular2-seed

![screen shot 2016-02-27 at 5 32 07 pm](https://cloud.githubusercontent.com/assets/8420490/13376130/21800d50-dd78-11e5-9f32-245558e76f5b.png)

**Comment by d3viant0ne** [comment]
@mgechev @ludohenin Are we supporting Node v0.12 ?

**Comment by d3viant0ne** [comment]
@ReneVallecillo - FYI, I don't have a problem helping out with an issue on v0.12. I just need to know if it's officially supported in case a change is required

**Comment by ReneVallecillo** [comment]
Thanks @d3viant0ne.  Yeah I was running an old version. My bad. Thanks for your time.

**Comment by ashokc** [comment]
I seem to have the same issue, even though my versions (node: 4.4.2 & npm:2.15.0) seem to be fine...
On ubuntu 15.10

0 info it worked if it ends with ok
1 verbose cli [ '/opt/software/node-v4.4.2-linux-x64/bin/node',
1 verbose cli   '/opt/node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular2-seed@0.0.0
6 info start angular2-seed@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular2-seed@0.0.0 Failed to exec start script
9 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve.dev --color`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/software/node-v4.4.2-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/opt/software/node-v4.4.2-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular2-seed@0.0.0
