### ISSUE TITLE
SyntaxError: Expected ')' in Prod build in IE 11

### ISSUE THREAD

**Issue by NareshPagadala** [mgechev/angular2-seed#548]
I have downloaded the structure and created the PROD build and deployed the code.It was working fine in Mozilla and Firefox. but in IE11, we are getting a strange error --> SyntaxError: Expected ')'.

When I changed the value of minify to false in the file build.bundles.app.ts , its working fine in IE as well. Which means its causing a break when we are trying to minify the js.

Before:

const BUNDLER_OPTIONS = {
  format: 'cjs',
  minify: true,
  mangle: false
};

After:

const BUNDLER_OPTIONS = {
  format: 'cjs',
  minify: false,
  mangle: false
};

Can this be resolved as without minifying the js, its taking time to load the js files.

Screenshot of the error attached.
![ie_error_afterminify](https://cloud.githubusercontent.com/assets/17527026/13379230/edea68cc-de45-11e5-9382-526c897b357a.png)

**Comment by d3viant0ne** [comment]
@NareshPagadala - https://github.com/mgechev/angular2-seed/issues/510
