### ISSUE TITLE
IE Support in prod build

### ISSUE THREAD

**Issue by baodongliu** [mgechev/angular2-seed#549]
Thanks a lot for creating this excellent Angular2 Seed Project. The Dev build support IE without any issue. However, the Prod build does not support IE 11 quite well. It keeps says "Loading...". 

Thanks again.

Before submitting the issue, take a look at the already existing solutions to:

- [x] `Cannot find module '...'` - your issue is related to not existing type definitions.
- [x] Adding [sass support](https://github.com/mgechev/angular2-seed/wiki/Add-custom-Gulp-task).
- [x] Adding [external styles](https://github.com/mgechev/angular2-seed/wiki/Add-an-external-styles).
- [x] Configuring [SystemJS](https://github.com/mgechev/angular2-seed/issues/499).
- If you are not sure your configuration is correct, please take a look at the documentation of [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md), [typings](https://github.com/typings/typings/blob/master/README.md) and [gulp](https://github.com/gulpjs/gulp/blob/master/docs/README.md).

**Comment by mgechev** [comment]
It seems the issue is not related to the seed project https://github.com/mgechev/angular2-seed/issues/548
