### ISSUE TITLE
error when trying to run on windows 8.1

### ISSUE THREAD

**Issue by shootermv** [mgechev/angular2-seed#55]
tried to run the project on windows machine - getting error:
Y:\Projects\angular2-seed>gulp serve.dev
module.js:338
throw err;
^
Error: Cannot find module 'orchestrator'

**Comment by mgechev** [comment]
Thanks for reporting the issue! We'll take a look at it next a couple of days.

**Comment by ludohenin** [comment]
@shootermv isn't it an error with gulp itself ?

**Comment by mgechev** [comment]
@shootermv would you give it a try with the latest changes on master?

**Comment by shootermv** [comment]
hi, got latest, working now. Thanks
