### ISSUE TITLE
Assemble html templates and use inline-ng2-template

### ISSUE THREAD

**Issue by Dinistro** [mgechev/angular2-seed#550]
In our application we are assembling the `index.html` and the `app.html` with handlebars. This means, that these html-files are not present in the src folder. We configured our assemble task to pipe the created files into the `TMP_DIR` folder. For the `build.dev` we just copy them into the dist.

Now we want to use inline-ng2-template for our productive build, but are not able to make sure, that the plugin can find either the assembled templates or the normal html files. When we `useRelativePaths: true`, the plugin can find the normal templates, but searches for the assembled ones in the src-directory. The other way around, with `useRelativePaths: true`, it can find the assembled templates, but none of the normal ones. 

What would you suggest to fix this? Is there a 

Note: I'm not sure, but I think the build worked very well last week.

**Comment by mgechev** [comment]
If you need to transform your templates you can use the `templateProcessor` function and keep the templates in `src`. Take a look at [the plugin's readme](https://github.com/ludohenin/gulp-inline-ng2-template#configuration).

**Comment by Dinistro** [comment]
As I said, the templates are not present in the src directory, because they do not exist (they are split up in multiple .hbs files) and are only created in the build process. Because of this, they are moved into the `TMP_DIR`. 

**Example**
templateUrl in the AppComponent:

`templateUrl: './app/app.tpl.html',`

After the assembling, the app.tpl.html can be found in the `TMP_DIR` under `app/app.tpl.html`. Now I need to tell the `inline-ng2-template`-plugin, that it should search in the `TMP_DIR` and **not** in der src. don't forget that there are also normal html templates in the src for other components, that means, that I can't just set the `useRelativePaths` to `false`.

Do you think there is a possible solution? Or should I better ask in the the plugin repo?

**Comment by Dinistro** [comment]
Thanks. This will not directy fix my problem, because we use an old version of handlebars assemble, that has no gulp support, and so we run it with grunt. But we are working on it.

**Comment by mgechev** [comment]
I don't think you need a gulp support. You can define your template transformation with the handlebars node modules without any wrapper.

**Comment by Dinistro** [comment]
I will take a look, thank you.

**Comment by ludohenin** [comment]
@mgechev Yes this is correct.
@Dinistro handlebars render function has to be synchronous.
