### ISSUE TITLE
karma not in sync with build.test.watch on Windows

### ISSUE THREAD

**Issue by dodoshanti** [mgechev/angular2-seed#551]
We're having problems with karma re-running before build.test has completed. We initially thought it was our 'fork' but tested it on the seed and get the same behavior.

**Comment by mgechev** [comment]
Would you provide more details for this issue?

**Comment by dodoshanti** [comment]
npm run build.test.watch      # 1st window
npm run karma.start  # 2nd window

make a change to a ts file and save. build.test runs automatically again, karma runs and reports 0 tests

**Comment by mgechev** [comment]
Thanks for the feedback! We'll take a look at this as soon as possible.

**Comment by mgechev** [comment]
@dodoshanti this issue should be fixed by https://github.com/mgechev/angular2-seed/tree/fix-551

**Comment by ludohenin** [comment]
This could be due to `autoWatchBatchDelay` config property in `karma.conf.js`.
It defaults to 250ms, that might be not enough.

**Comment by mgechev** [comment]
@ludohenin yeah, playing with the issue I found that:

- Change in files is detected
- The build task removes the files from dist
- Karma detects changes
- Karma runs tests
- Files are being transpiled

In the end there's missing karma call.

@dodoshanti would you try if `autoWatchBatchDelay` fixes your issue?

**Comment by dodoshanti** [comment]
@mgechev @ludohenin We did try `autoWatchBatchDelay ` but it didn't work.

Will try the fix

**Comment by dodoshanti** [comment]
Fix-551 works but introduces 2 minor issues:

1. no tests are run at first pass until you edit a ts file
2. can't debug in chrome as window opens and closes

**Comment by ludohenin** [comment]
I've tried setting up `autoWatchBatchDelay: 3000` and it does work.
The only thing is it executes the test twice:
* once with no test (files have just been deleted)
* 2nd time is OK

**Comment by dodoshanti** [comment]
Looks like this might be an issue with our setup cause that setting does not make any difference.
I suppose you can close the issue.
Thanks!
