### ISSUE TITLE
fix(docs): serve.docs doesn't work

### ISSUE THREAD

**Issue by d3viant0ne** [mgechev/angular2-seed#553]
Related to https://github.com/sebastian-lenz/typedoc/issues/162

Typedoc v0.3.12 is using TypeScript 1.6.2 document generation isn't going to work until the package is up to date with TypeScript 1.8

- [ ] Fix document generation & serve.docs

**Comment by ludohenin** [comment]
@d3viant0ne yes it has worked at some point.

**Comment by d3viant0ne** [comment]
@ludohenin - Thanks, I'll get it working again

**Comment by ludohenin** [comment]
I checked that one.
* `npm run docs` actually works, generate and serve the docs.
* `npm run serve.docs` doesn't as it's not defined in as a npm script (`npm run gulp -- serve.docs` works)

**Comment by d3viant0ne** [comment]
@ludohenin - Not sure how you got that working with the older TS lib without vomiting a ton of errors but "Yay!" :)

**Comment by ludohenin** [comment]
Didn't do anything special, just ran `npm run docs`.

**Comment by d3viant0ne** [comment]
@ludohenin Didn't work before you landed #528. Once I got the task working, it would vomit out a bunch of typedoc / typescript errors.

I'm good with "magical" fixes
