### ISSUE TITLE
Error in build.dev

### ISSUE THREAD

**Issue by natarajanmca11** [mgechev/angular2-seed#554]
Hi Team,

I am getting error while build.dev.  

I have tried the following but no luck. 
1. npm cache clean
2.  npm run reinstall
3 . delete all global npms and reinstall again.

Error: 

[11:10:07] TypeError: Object E:\Natarajan\Git\angular2-seed\node_modules\systemj
s\dist\system-polyfills.src.js has no method 'startsWith'
    at mapPath (E:\Natarajan\Git\angular2-seed\tools\tasks\build.index.dev.ts:32
:17)

FYR:

![image](https://cloud.githubusercontent.com/assets/9244766/13410575/737d9a10-df9d-11e5-8747-29ab0d4d01cd.png)

![image](https://cloud.githubusercontent.com/assets/9244766/13410498/ff163e52-df9c-11e5-8d1a-9c85d7666574.png)

npm logs:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build.dev' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prebuild.dev', 'build.dev', 'postbuild.dev' ]
6 info prebuild.dev angular2-seed@0.0.0
7 info build.dev angular2-seed@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular2-seed@0.0.0 Failed to exec build.dev script
10 error angular2-seed@0.0.0 build.dev: `gulp build.dev`
10 error Exit status 1
11 error Failed at the angular2-seed@0.0.0 build.dev script.
11 error This is most likely a problem with the angular2-seed package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     gulp build.dev
11 error You can get their info via:
11 error     npm owner ls angular2-seed
11 error There is likely additional logging output above.
12 error System Windows_NT 6.1.7601
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.dev"
14 error cwd E:\Natarajan\Git\angular2-seed
15 error node -v v0.10.29
16 error npm -v 1.4.14
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

Regards,
Natarajan Ganapathi

**Comment by d3viant0ne** [comment]
@natarajanmca11 - ![screen shot 2016-02-29 at 4 19 31 pm](https://cloud.githubusercontent.com/assets/8420490/13410975/4429c27c-df00-11e5-99a5-2a66334add0c.png)

**Comment by natarajanmca11** [comment]
I have installed node 5.7 and npm "3.7.5". but in command prompt shows like the above.

**Comment by natarajanmca11** [comment]
@d3viant0ne 

I found the root cause. Actually the problem was the environment variable path mentioned two times and two different path. I have removed the duplicate path form environment variable. Now its working as expected.  Thanks for your support.
