### ISSUE TITLE
Undefined is not a function, RouteConfig()

### ISSUE THREAD

**Issue by aboeglin** [mgechev/angular2-seed#56]
It seems there is a little issue with the Router in the current version. Here is the error :
[Error] TypeError: undefined is not a function (evaluating 'router_1.RouteConfig')
	(anonymous function) (about, line 31)

 I could find a quick fix though. In the init.ts file we have :

```
// Dirty workaround in order to load angular2/router properly
System.import('angular2/router').then(m => {
  System.defined['angular2/router'] = { normalizedDeps: [] };
  System.defined['angular2/router'].module = {};
  System.defined['angular2/router'].module.exports = m;
});


System.import('app')
  .catch(e => console.error(e,
    'Report this error at https://github.com/mgechev/angular2-seed/issues'));
```
The problem seems to be that when we load app and bootstrap it, the router is maybe not loaded yet, therefore I queued the import of the app in the promise returned by the import of the router like this : 

```
// Dirty workaround in order to load angular2/router properly
System.import('angular2/router').then(m => {
  System.defined['angular2/router'] = { normalizedDeps: [] };
  System.defined['angular2/router'].module = {};
  System.defined['angular2/router'].module.exports = m;
  System.import('app')
    .catch(e => console.error(e,
      'Report this error at https://github.com/mgechev/angular2-seed/issues'));
});

```

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/commit/e5a418d872b0b939da6887a7c5bc4ff2833d2bfb
