### ISSUE TITLE
Test coverage server report does not include source with 0% coverage

### ISSUE THREAD

**Issue by jt3po** [mgechev/angular2-seed#560]
Perhaps I'm missing something, but the coverage reports generated by npm test and viewed by running npm run serve.coverage are a bit misleading if there are source files that are not covered by any test. 

When building and maintaining a large application, it's helpful to see not just how much a particular source file is covered by test, but if there is any source that has no coverage at all. 

I attempted adding "includeAllSource: true" in the coverageReporter configuration in karma.conf.js, which produces the report I might expect, but remap-istanbul chokes on the results, complaining that it can't find main.ts in the dist/dev directory. 

Ideas?

**Comment by mgechev** [comment]
@NathanWalker can you take a look at this one?

**Comment by NathanWalker** [comment]
I'll take a look tomorrow!

**Comment by mgechev** [comment]
Awesome thanks!

**Comment by d3viant0ne** [comment]
@NathanWalker FYI - There are two problems I can find so far
- there is a problem with build.js.test.ts not writing sourcemaps which I have fixed locally
- there is an issue with remap-istanbul that I haven't run down yet

 I very well may resolve this issue in #567

**Comment by NathanWalker** [comment]
@d3viant0ne Thanks for the insight there. Trying to track down as well. Lemme know if you find a fix.

**Comment by d3viant0ne** [comment]
@jt3po - For reference, it's not the 0% coverage that is causing problems.

It's an issue with remap-istanbul (wrong source directory) & gulp-sourcemaps (path bug)

Will be resolved with https://github.com/mgechev/angular2-seed/pull/568

**Comment by d3viant0ne** [comment]
@jt3po  - Got bogged down in other stuff this weekend. #580 is next up in my OSS queue. Call it PR by Wednesday to be safe

**Comment by jt3po** [comment]
@d3viant0ne - Makes sense thanks!

**Comment by d3viant0ne** [comment]
@jt3po - I've tested adding a new component in the branch for #622 which returned 0% coverage as I would expect.

If you are still having issues after that PR lands, please @ me so I can work out the issue you are having.
