### ISSUE TITLE
Reducing app.js filesize...

### ISSUE THREAD

**Issue by thinkgareth** [mgechev/angular2-seed#564]
Thanks for the great project! Really lets you hit the ground running with Angular2!

I'm concerned about the output JS file size.. Ignoring the fact that Gzip reduces the overall bandwidth, it's still a big file to start...

With fresh install of this repo;

shims.js = ~166kb
app.js = ~872kb

By the time i've added in a few more repositories it's sitting around 1.2mb

What are the biggest contributors to this file and is there a way to optimise this?

Best,

Gareth

**Comment by mgechev** [comment]
Reducing the file size is something which will happen in the next releases of Angular, once they drop the compuler from the production bundle. Until then, there is nothing we can do.

*Angular, combined with RxJS is a lot.

**Comment by thinkgareth** [comment]
Makes sense, good to know it's going to drop as Angular matures :)

Thanks for taking the time!
