### ISSUE TITLE
Coverage remap not working (no remapping of js results to .ts files)

### ISSUE THREAD

**Issue by jesperronn** [mgechev/angular2-seed#567]
Coverage map error: No sourcemaps found

Running `npm run serve.coverage` (after `npm test`) produces the following:

```
[15:29:02] 130 $ npm run serve.coverage

> angular2-seed@0.0.0 serve.coverage /Users/jesper/src/jesperronn-angular2-seed
> remap-istanbul -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage

[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/about/components/about.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/shared/services/name-list.service.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/home/components/home.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/app/components/app.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/app/components/navbar.component.js"]
[Error: Could not find source map for: "/Users/jesper/src/jesperronn-angular2-seed/dist/dev/app/components/toolbar.component.js"]

> angular2-seed@0.0.0 gulp /Users/jesper/src/jesperronn-angular2-seed
> gulp "serve.coverage"

[15:29:09] Requiring external module ts-node/register
[15:29:11] Loading task serve.coverage 
[15:29:11] Using gulpfile ~/src/jesperronn-angular2-seed/gulpfile.ts
[15:29:11] Starting 'serve.coverage'...
[15:29:11] Finished 'serve.coverage' after 6.13 ms

```

Lot's of missing sourcemaps. And I see that the remap has actually not occured. As you can see from the screenshot, coverage maps the js files and not the ts files.

<img width="948" alt="code_coverage_report_for_app_components_navbar_component_js" src="https://cloud.githubusercontent.com/assets/6267/13497478/ad5f3e6e-e155-11e5-9283-c092dbd05ecc.png">

I am running on latest master (commit 6eca776de0b8b30260b384a4dc9da16edcc88fce ). This is apparently unrelated to #560, which is the full sources mapping flag.

**Comment by d3viant0ne** [comment]
@jesperronn This may very well be on me from when I updated the dev deps last week #547 .

I'll take a look at it when I get out of this meeting.

**Comment by d3viant0ne** [comment]
@jesperronn - I've gotten this close to where it should be with a bit of hackery. That said, as long is this isn't blocking you from getting work done, I would like to wait on opening the real PR until after https://github.com/mgechev/angular2-seed/pull/528 which should land tonight.

In the mean time, I'll branch off of 528 and validate the same fixes there.

**Comment by jesperronn** [comment]
@d3viant0ne no hurry, I am not sure you broke it, since I tried this very same a couple of weeks ago. As I recall another sourcemaps writer was required due to issues with either remap or ts-sourcemaps-inline-compilation. I saw a js example but didn't have the time to investigate. 

This in no way blocks.

**Comment by d3viant0ne** [comment]
After a bit of discussion, the PR will allow for the coverage to be a typescript/transpiled javascript configurable option. I'll have it done this afternoon.

**Comment by d3viant0ne** [comment]
@jesperronn - Got bogged down in other stuff this weekend. #580 is next up in my OSS queue. Call it PR by Wednesday to be safe
