### ISSUE TITLE
Extending PATH.src in gulpfile to provide more modularity

### ISSUE THREAD

**Issue by aboeglin** [mgechev/angular2-seed#57]
Hi everyone,

I just wanted to propose a little improvement to the gulpfile. The idea would be to add source file paths to the PATH variable in order to be able to quickly change a project's structure if needed. At the moment almost every gulp.src() uses a plain './app/something' form. The idea would be to replace it by say gulp.src(PATH.src.root+'something'). Like that we might offer better modularity over the structure of the folders to allow source files to be in /src or /client/app, /src/app. All you'd have to do is just to locate the root of your angular2 app source files within the PATH variable.

**Comment by mgechev** [comment]
Totally makes sense. Do you want to open a PR?

**Comment by aboeglin** [comment]
Yes, not sure I have time in the coming days but I'll do it !

**Comment by mgechev** [comment]
It is not urgent anyway, it is related with code improvements so it can wait a little. :-)

**Comment by aboeglin** [comment]
Ok it's almost done if you want to have a look. I checked how we can also support subfolders, which isn't as straightforward as I thought but manageable. It would allow to build from a deeper src file. But then I thought, it's actually not really needed I believe. Since we only focus on the client side here the case of /src/client isn't necessary.

**Comment by mgechev** [comment]
Where we can take a look?

**Comment by aboeglin** [comment]
Sorry, it's here : https://github.com/aboeglin/angular2-seed/tree/gulp-src-reference
I have basically extended the Configuration variables and used these to define the PATH. Like this we can just do changes to the paths at one point. So we can now change the source and destination paths easily.

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/pull/60
