### ISSUE TITLE
Insane paths and file names

### ISSUE THREAD

**Issue by kamikaze** [mgechev/angular2-seed#570]
Why do we need "src/COMPONENTS/whatever/whatever.COMPONENT.ts"-like paths and file names??? "COMPONENT" is mentioned twice and comonent`s name is mentioned twice... How about triple then?

**Comment by d3viant0ne** [comment]
@kamikaze - Everything the seed is based on https://github.com/mgechev/angular2-style-guide

Feel free to join the discussion about directory structure & file naming there.
