### ISSUE TITLE
bug(tools): Serve prod fails

### ISSUE THREAD

**Issue by d3viant0ne** [mgechev/angular2-seed#575]
- [x] Remove serve.prod task from npm scripts

**Comment by ludohenin** [comment]
Ph yes, I drop that one while refactoring (and cleaning up). The fact is that's not relevant anymore, we are supporting prod server for a while now.
A simple `http-server ./dist/prod` do the job.
But ... I forgot to clean up npm scripts.

**Comment by d3viant0ne** [comment]
@ludohenin So I should change the top level npm script to "http-server ./dist/prod" or just yank it all together?

**Comment by ludohenin** [comment]
@d3viant0ne you self answered that one :)

**Comment by d3viant0ne** [comment]
@ludohenin With coffee comes logic :)
