### ISSUE TITLE
Configuration issues Unable to run application if APP_BASE set to non root directory

### ISSUE THREAD

**Issue by iazarny** [mgechev/angular2-seed#577]
It seems to me that APP_BASE conf variable has no effect for some files

1 APP_BASE changed in config.ts
export const APP_BASE             = argv['base']        || '/my-app/';

2.  npm start     and open http://localhost:5555/my-app/
a lot of 404

3. The same will be if sett APP_BASE to root and run 
npm start -- --port 8080 --reload-port 4000 --base /my-app/

**Comment by ludohenin** [comment]
@iazarny I can't reproduce, seems to work fine. Are you using the latest master?

**Comment by d3viant0ne** [comment]
@iazarny I can't reproduce that either running on the latest master

**Comment by iazarny** [comment]
On latest master work well. 
Thanks, Igor
