### ISSUE TITLE
deprecated graceful-fs@3.0.8

### ISSUE THREAD

**Issue by raupach** [mgechev/angular2-seed#578]
"npm install" made this warning:

npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by d3viant0ne** [comment]
@raupach - That is an upstream dependency in browser-sync & not something that we can do about.

The warning can be ignored
