### ISSUE TITLE
Production build is broken

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#58]

**Comment by mgechev** [comment]
As @ludohenin suggested, we're closing this issue. Having production build without Angular 2 being officially released doesn't make a lot of sense.

**Comment by e-oz** [comment]
Actually it does.. Some projects will be released after Angular 2 Beta release, so it's already good time to start.

**Comment by ludohenin** [comment]
@e-oz agree with you. We've started to think about it. But the choice for a bundler it not that obvious.
Expect something to come up soon.
btw, any suggestion is welcome ;)

**Comment by bkinsey808** [comment]
I'm curious how this will be solved with just gulp and not webpack or jspm. Will there be bundling?

**Comment by e-oz** [comment]
as I see, only thins left are concatenation and minification - can be easily solved with Gulp.
