### ISSUE TITLE
chore(tools): Configurable coverage reporting

### ISSUE THREAD

**Issue by d3viant0ne** [mgechev/angular2-seed#580]
Feature based on discussion for a bug fix. Code coverage reporting will be a configurable option allowing the user to choose coverage based on TypeScript or the Transpiled JavaScript.

- [x] Fix remap-istambul error
- [x] Add sourcemaps to build.test ( Fixes #567 )
- [ ] Move coverage to a configurable gulp task
- [x] Investigate command line output configuration / both 
- [x] Verify zero percent coverage ( Fixes #560 )

**Comment by d3viant0ne** [comment]
I will finish this out once #622 lands

**Comment by mgechev** [comment]
@d3viant0ne can we close this one? We can add a wiki page or reference to istanbul on how to configure the coverage report.

**Comment by d3viant0ne** [comment]
Yeah, sorry
