### ISSUE TITLE
chore(build.prod): Implement workaround for mangling

### ISSUE THREAD

**Issue by e-oz** [mgechev/angular2-seed#585]
AngularClass starter found some workaround to be able use mangling:
https://github.com/AngularClass/angular2-webpack-starter/commit/1a4edb9693d60ae3b39810bb75b4199123b798ad

Is it possible to apply it somehow to the angular2-seed?

**Comment by mgechev** [comment]
The same workaround should be possible. We are using `gulp-uglify` that uses [uglify-js](https://github.com/mishoo/UglifyJS2) and it supports `screw_ie8` and `except`.

**Comment by e-oz** [comment]
I just tried to put value `{ screw_ie8 : true, except: ['RouterLink']}` instead of false to `build.bundles.app.ts` and `build.bundles.ts` (to both of them and to only one of them, each), and it didn't worked.

**Comment by d3viant0ne** [comment]
@e-oz - I've renamed & tagged this to ensure it gets picked as a working task.

**Comment by mgechev** [comment]
Lets close the issue for now. The WebPack starter [disabled it as well](https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.prod.js#L130).
