### ISSUE TITLE
Add "default" task to gulpfile.ts

### ISSUE THREAD

**Issue by TheBolmanator** [mgechev/angular2-seed#587]
Many thanks for the FANTASTIC work, just thought I would make an effort to try to contribute;
this may help others (of course the task list is up to individuals).  

gulp.task('default', function(){
  runSequence('serve.dev');
});

**Comment by mgechev** [comment]
We don't use `gulp` directly but instead we wrap the gulp tasks [with npm](https://github.com/mgechev/angular2-seed/blob/master/package.json#L9-L30).

But a default gulp task will be no harm. You're welcome to create one.
