### ISSUE TITLE
Typings : Should we gather them through npm install ?

### ISSUE THREAD

**Issue by aboeglin** [mgechev/angular2-seed#59]
Do we need to add typings that aren't part of the official packages to fix alpha issues ? If not we could easily install the typings when we install the dependencies as a postinstall script in the package.json.

**Comment by ludohenin** [comment]
It could be an idea.
@mgechev your opinion ?

**Comment by mgechev** [comment]
Yeah, I think it makes sense. @aboeglin do you want to open a PR for this?

**Comment by aboeglin** [comment]
Yes, I'll do it.
