### ISSUE TITLE
proxy backend rest calls

### ISSUE THREAD

**Issue by raupach** [mgechev/angular2-seed#592]
Hi,

I'm a java backend developer and I have the need to load static data via rest calls from a running tomcat instance during the development phase.

I already tested ember and the I have the possibility to proxy rest calls. For example:
ember serve --proxy http://localhost:3000/

Please provide a brief instructions how to do this in the angular2-seed-project.

**Comment by mgechev** [comment]
We don't have such functionality out of the box. The seed provides only a quick starter for Angular 2 development without any back-end (except browsersync for development server and express for serving docs).

You can use [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) for this purpose.

**Comment by raupach** [comment]
Hi,

I'm not so familiar with nodejs. How can I integrate node-http-proxy
<https://github.com/nodejitsu/node-http-proxy> in angular2-seed? Is this
not a common situationto have a running backend for rest calls?

-Oliver


Am 07.03.2016 um 22:15 schrieb Minko Gechev:

**Comment by d3viant0ne** [comment]
This is a small seed project & a set of tools to get most of the boilerplate out of the way.
People build applications on top of the seed, this is client side boilerplate & build pipeline.

API layer is a NodeJS server side project and outside the scope of this project.

**Comment by raupach** [comment]
Yes, the project is a really good job of your team.I try also to build
an applicationon top of the seed.However, at the moment I'm stuck on
this problem....

Oliver



Am 07.03.2016 um 22:28 schrieb Joshua Wiens:

**Comment by mgechev** [comment]
@raupach here's a sample integration https://github.com/mgechev/angular2-seed/pull/593

**Comment by raupach** [comment]
Hi,

hmmm, it did not work for me. I have the following config:

Development:
http://localhost:5555/myapp/

Backend:
http://localhost:8080/myapp/rest/ping

My seed.config.ts looks as follow:

...
  PROXY_PATH           =
argv['proxy_target_path']           || '/myapp/rest';
  PROXY_HOST           =
argv['proxy_target_host']           || 'localhost';
  PROXY_PORT           =
argv['proxy_target_port']           || 8080;
  PROXY_PROTOCOL       =
argv['proxy_target_protocol']       || 'http';
  PROXY_LOCAL_PATH     =
argv['proxy_local_path']            || this.PROXY_PATH;
...

But a call to http://localhost:5555/myapp/rest/ping comes back with
the "index.html" ....

Oliver

Am Dienstag, dem 08.03.2016 um 9:36 schrieb Minko Gechev:

@raupach [1] here's a sample integration #593 [2]

—
Reply to this email directly or view it on GitHub [3].



Links:
------
[1] https://github.com/raupach
[2] https://github.com/mgechev/angular2-seed/pull/593
[3]
https://github.com/mgechev/angular2-seed/issues/592#issuecomment-193663071

**Comment by Doormouse2House** [comment]
@raupach did you solve this?  Were you using HTTPS?

**Comment by Doormouse2House** [comment]
OK, figured that the proxy middleware added isn't firing and instead the connect-history-api-fallback is triggering.
