### ISSUE TITLE
Replace del with rimraf

### ISSUE THREAD

**Issue by Shyam-Chen** [mgechev/angular2-seed#594]
[rimraf](https://github.com/isaacs/rimraf)
[gulp-rimraf](https://github.com/robrich/gulp-rimraf)

**Comment by UnnoTed** [comment]
![](http://i.imgur.com/9mcp624.png)
![](http://i.imgur.com/rIDQho6.png)

**Comment by d3viant0ne** [comment]
Replace issue with pull request :)

**Comment by mgechev** [comment]
Yes, PRs are usually very welcome! Today I had some extra time and did the change. You can verify whether it works here https://github.com/mgechev/angular2-seed/pull/596.
