### ISSUE TITLE
Browsersync not reloading any longer?

### ISSUE THREAD

**Issue by brian428** [mgechev/angular2-seed#599]
It looks like (for me at least), the Browsersync reloading isn't happening any longer after the last round of refactoring to the build scripts? Looking through the code, I see the changed() function in code_change_tools.ts, but this doesn't seem to be invoked anywhere. Am I missing something? Or is this just a bug that slipped in during the refactoring?

**Comment by d3viant0ne** [comment]
@brian428 - I'll take a look at this in a sec.

**Comment by d3viant0ne** [comment]
@brian428 
Code change tools aren't picking up the change & notifying Browsersync, file watcher rebuilds which breaks the connection to Browsersync.

I'll get this fixed as soon as I finish stuffing my face :)

**Comment by d3viant0ne** [comment]
@brian428 - I have this working, just need to clean up and I'll get a PR open
