### ISSUE TITLE
Runtime errors after installing ng2-bootstrap.

### ISSUE THREAD

**Issue by kambojankit** [mgechev/angular2-seed#600]
I have a fresh clone of angular2-seed project and installing ng2-bootstrap and the typings for moment.js as below:

```
npm install --save ng2-bootstrap
typings install moment --save

```
I also added the following mapping in System Js Configuration:
```
map: {
      moment: 'node_modules/moment/moment.js'
    }
```

But during application start i get the below errors:

> Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/moment.js(…) 

Can you please help me resolve this issue.

**Comment by e-oz** [comment]
I think StackOverlow is a better place to ask for help.

**Comment by mgechev** [comment]
@kambojankit you can take a look at the SystemJS documentation. You are on the right track but you have misconfigured the path.

**Comment by kambojankit** [comment]
@e-oz, @mgechev thanks for the quick reply, i found it to be similar to issue #442 Its an issue i believe with ng2-bootstrap.
