### ISSUE TITLE
Is /tools/tasks/seed/clean.tools.ts used?

### ISSUE THREAD

**Issue by tarlepp** [mgechev/angular2-seed#602]
Can't find any usages of this file? Am I missing something or is this not needed anymore?

**Comment by d3viant0ne** [comment]
@tarlepp my guess would be @ludohenin left it in to allow people to use it but that is really a question for him. iirc he is on vacation until Thursday.

**Comment by ludohenin** [comment]
yep, I'm back :)
`clean.tools` is to be used individualy `npm run gulp -- clean.tools`.
To debug using vscode, transpilation is required, that's just a utility to clean the mess up.
This is to be documented (coming soon, hopefully), you can see #528 thread until then.

**Comment by ludohenin** [comment]
oh! and to answer the issue question, yes it's used ;)
