### ISSUE TITLE
[Docs] Guidance on how to add components, routes

### ISSUE THREAD

**Issue by Meligy** [mgechev/angular2-seed#605]
I'd like to see some guidance on how to add components, routes, etc to the project.

For example, the components have a folder structure a bit similar to what angular-cli generates, is it recommended to add new components via angular-cli generator?
Some other (maybe yeoman etc) generator?
Some specific npm/gulp tooling?
Just manually create the folders and files? (which is OK, if that's the expectation)

Same of course for other things like routes, pipes, etc. but I think it's more of a question for components.

I couldn't find that in the readme or wiki. The wiki shows adding external stuff, but not project items like components.

Can someone please mention the recommended approach for these?

**Comment by d3viant0ne** [comment]
@Meligy - Having done some work with the cli in Material2, I wouldn't recommend relying on it at this point.

It wouldn't be hard to whip up a utility that creates a component from a template.

Hi! by the way :)

**Comment by d3viant0ne** [comment]
Personally, until the tooling matures I am just using snippets to generate code. Less than optimal but a more stable option imo.

**Comment by Meligy** [comment]
Hi Josh!

(sorry for skipping that essential part of a new conversation, oops!)

I think there is value in capturing just that stance in the wiki. What do you think?

And by the way, thanks for the awesome project!

**Comment by d3viant0ne** [comment]
I definitely agree on the docs. 

Component generation was something I saw in the NG6-starter that was actually really valuable in extending it while play around. It was something that seemed a useful addition here as well, the issue will be implementing it in a way that is configurable given the preprocessors we support.

**Comment by mgechev** [comment]
Here's a page which describes the basics https://github.com/mgechev/angular2-seed/wiki/Using-the-seed.

**Comment by Meligy** [comment]
Awesome, thanks :)

**Comment by d3viant0ne** [comment]
@Meligy The other half of this, the cli is next up for dev

**Comment by Meligy** [comment]
Yeah. Thanks for mentioning me there BTW. I have a few thoughts on this, been lazy not putting them in, will join the conversation in the weekend.

Thanks for all the awesome stuff.
