### ISSUE TITLE
Evaluate the usage of Gulp method decorators

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#606]
[This project](https://github.com/pleerock/gulpclass) provides more object-oriented approach to Gulp.

We can evaluate it for eventual integration with the seed.

// cc @ludohenin

**Comment by d3viant0ne** [comment]
@mgechev - That looks promising.

One side note, I think it may be a good idea to spend a few days stabilizing the tools after the last refactoring before we do it again.

**Comment by mgechev** [comment]
@d3viant0ne totally agree.

**Comment by ludohenin** [comment]
Not quite sure.
Our task programing model is really simple now, don't you think it should remain ?

**Comment by d3viant0ne** [comment]
@ludohenin - I like the idea of using decorators but you are totally right, we would have to be able to implement it while retaining the simplicity that comes the last refactoring.

**Comment by mgechev** [comment]
The biggest problem I see is the coincidental cohesion of the classes.

However, in a perfect scenario each task could be implemented as an individual class which will encapsulate its logic. This way the class will have a single public method annotated with `@Task`. In this perspective the gulpclass package won't bring extra complexity but instead will help with bringing polymorphic behavior to the classes by having method overrides, inheritance, abstraction and encapsulation (thanks to the private methods that help us implement the `@Task`).

The biggest drawback I see is the extra level of indirection which may make everything look like magic.
