### ISSUE TITLE
Getting started: Where to begin? Can I start now?

### ISSUE THREAD

**Issue by Sn3b** [mgechev/angular2-seed#608]
Hey everyone, nice job you've done there with this seed.
Just playing with it and I really like its elegance.

I'd like to start a project with angular2, and this seems to be the perfect start point, but I have a couple of questions as I'm not totally familiar with all the technologies used, really I'm only getting started with tools such as npm, gulp, karma, typings etc...

So far I've managed to get the whole thing running, added a dependency to normalize.css, created a couple of pages and played with simple requests, even added authentication with auth0, I've very proud :P

Anyway, I'd like to start doing some real code soon, and I had a couple of questions:
1. I've been following it (from a distance) for a little while and I saw a lot of activity, new code being added, conventions being changed etc... Is the seed ready for production use now? And if not, can I start with one (I like the sass one), develop on it and still benefit from future commits?
2. I would need to define my own types/entities, either as classes or interfaces that would somewhat match the ones I have in the backend, where would I do that? In the shared folder?
3. I think I have most basic types covered except for 1, I use UUIDs/GUIDs as IDs for my entities in the backend, is it possible here too?

Thanks folks!

Seb :)

**Comment by d3viant0ne** [comment]
@Sn3b - Nothing Angular2 is "Production" ready. That said, I think it's close enough to start working with it. It's really all the tooling surrounding Angular2 that is a bit behind as you would expect.

1.) As far as the seed goes, I feel we have gotten it to a place where you can now build on top of it and still be able to pick up changes from the seed.

2.) You will notice in the seed that all of the tooling has two sub-folders, project & seed. The project directories would be where you want to add project specific tooling / typings / whatever

3.) manual_typings/project

**Comment by d3viant0ne** [comment]
Also something to note. A lot of what we are working on now will be providing examples in the wiki / repo of how to build x, y, z on top of the seed.

@NathanWalker 's [Advanced Seed](https://github.com/NathanWalker/angular2-seed-advanced) is a really excellent example of that.

As is the additions from @tsm91 here #598

**Comment by Sn3b** [comment]
Super, thanks! :)

**Comment by Sn3b** [comment]
Sorry but I don't understand your number 2, I mean I do, but I'm looking and I don't see what you mean by the tooling has 2 sub folders...

**Comment by d3viant0ne** [comment]
For instance - https://github.com/mgechev/angular2-seed/tree/master/tools/manual_typings

**Comment by d3viant0ne** [comment]
project is for extending
seed is for this repo

**Comment by Sn3b** [comment]
Ah sorry I should have got the latest version before checking :)

Thanks!
