### ISSUE TITLE
gulp build.prod throws error

### ISSUE THREAD

**Issue by the-ult** [mgechev/angular2-seed#610]
After fresh checkout.
Run `gulp build.prod` throws the following error:
```console
[21:51:38] Starting 'build.prod'...
[21:51:38] Starting 'clean.prod'...
[21:51:40] 'clean.prod' errored after 1.1 s
[21:51:40] TypeError: Cannot read property 'map' of undefined
    at /angular2-seed/tools/utils/seed/clean.ts:11:30
    at Gulp.<anonymous> (/angular2-seed/tools/utils/seed/tasks_tools.ts:21:14)
    at module.exports (/angular2-seed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/angular2-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/angular2-seed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/angular2-seed/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/angular2-seed/node_modules/run-sequence/index.js:88:16)
    at runSequence (/angular2-seed/node_modules/run-sequence/index.js:99:2)
    at Gulp.<anonymous> (/angular2-seed/gulpfile.ts:40:3)
    at module.exports (/angular2-seed/node_modules/orchestrator/lib/runTask.js:34:7)
[21:51:40] 'build.prod' errored after 1.15 s
[21:51:40] Error in plugin 'run-sequence'
Message:
    An error occured in task 'clean.prod'.
```
line 11 in `clean.ts` -> `let promises = pathsArray.map(p => {`
```typescript
import * as util from 'gulp-util';
import * as chalk from 'chalk';
import * as rimraf from 'rimraf';

export function clean(paths: string|string[]): (done: () => void) => void {
  return done => {
    let pathsArray: string[];
    if (!(paths instanceof Array)) {
      pathsArray = [<string>paths];
    }
    let promises = pathsArray.map(p => {
      return new Promise(resolve => {
        rimraf(p, e => {
          if (e) {
            util.log('Clean task failed with', e);
          } else {
            util.log('Deleted', chalk.yellow(p || '-'));
          }
          resolve();
        });
      });
    });
    Promise.all(promises).then(() => done());
  };
}
```

related to #607 ??

**Comment by TheDonDope** [comment]
Hi,
this is in need of a null and or size check to `pathsArray`, since it will get initialized empty and only if the `paths` argument is `instanceof`Array, the `pathsArray` will be filled.
Therefore the line `let promises = pathsArray.map(p => {`must be wrapped in a null and `.length` check as such: 
```typescript

    if (pathsArray != null && pathsArray.length > 0) {
      let promises = pathsArray.map(p => {
        return new Promise(resolve => {
          rimraf(p, e => {
            if (e) {
              util.log('Clean task failed with', e);
            } else {
              util.log('Deleted', chalk.yellow(p || '-'));
            }
            resolve();
          });
        });
      });
      Promise.all(promises).then(() => done());
    }

```

**Comment by the-ult** [comment]
Or perhaps an `forEach` which adds a new promise to `let promises`

**Comment by TheDonDope** [comment]
> But the question is.. Why does it throw an error?

Because in the current implementation: 
`let pathsArray: string[];` the variable is not yet initialized and therefore `undefined`. So then, 
`let promises = pathsArray.map(p => {     // pathsArray === undefined -> 'Cannot read property map of undefined` would fail.

**Comment by the-ult** [comment]
I know.
I meant one step before... What is the reason path is undefined or not an
Array.. Which results in pathArray stays undefined.

You're fix, fixes the error, but does not resolve the starting problem..
Path being a single value or undefined..
And what should happen in those cases?

Op wo 9 mrt. 2016 22:52 schreef Christian Dobert <notifications@github.com>:

> But the question is.. Why does it throw an error?
>
> Because in the current implementation:
> let pathsArray: string[]; the variable is not yet initialized and
> therefore undefined. So then,
> let promises = pathsArray.map(p => { // pathsArray === undefined ->
> 'Cannot read property map of undefined would fail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgechev/angular2-seed/issues/610#issuecomment-194525259>
> .
>
-- 
met vriendelijke groet,
Arjen

M 06-51 800 419
W www.payt.nl

**Comment by TheDonDope** [comment]
> You're fix, fixes the error, but does not resolve the starting problem..

Thank you for the hint! You are right, i only looked to fix the result not the source :/ I am sorry.

**Comment by the-ult** [comment]
No worries. We are al trying to help and make angular2-seed even better. 
Learning things from each other each day.

**Comment by d3viant0ne** [comment]
@the-ult @TheDonDope - For reference, you could null/length check pathsArray but the end result is still that we are passing path witch is only assigned `if (!(paths instanceof Array))`

So why technically, @TheDonDope is correct about null checking, given what we are passing, effectively "DEV_DEST & PROD_DEST" it can't be null as no build task would work.

All we needed was a condition that would handle the array being passed in as `path`

**Comment by TheDonDope** [comment]
@d3viant0ne Thank you for the information :)
@the-ult Thanks for your help :)

**Comment by the-ult** [comment]
@d3viant0ne
Thanks. I figured that an extra else check would fix it. 

Next time I find an error, I'll create an Pull Request with an fix, instead of just a bug report 😉

Thanks for the fix
