### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by Sn3b** [mgechev/angular2-seed#612]
In the previous version of the seed, I added a dependency to normalize.css by adding the line `{ src: 'normalize.css/normalize.css', inject: true }` in the config.ts file, but now there's a project.config.ts file where I guess this is supposed to go. However this way it injects normalize.css after main.css, and I think normalize.css should be first if I recall correctly...

Is it ok to have it in the seed.config.ts file without risking anything?

Thanks!

Seb :)

**Comment by mgechev** [comment]
Yes, it is totally fine to use it in `seed.config.ts`. It will be eventually slightly harder to upgrade to a newer version of the seed if you have made change in any of the `**/seed/**` files.

**Comment by Sn3b** [comment]
I opted for project.config.ts but changed it to make sure normalize.css gets injected first:

```javascript
import {join} from 'path';
import {SeedConfig, normalizeDependencies} from './seed.config';

export class ProjectConfig extends SeedConfig {
  PROJECT_TASKS_DIR    = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    //this.APP_TITLE = 'Put name of your app here';
    let priority_deps = [
      { src: 'normalize.css/normalize.css', inject: true },
    ];
    let additional_deps = [
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

    this.DEV_NPM_DEPENDENCIES = normalizeDependencies(priority_deps)
    .concat(this.DEV_DEPENDENCIES
      .concat(normalizeDependencies(additional_deps)));
    this.PROD_NPM_DEPENDENCIES = this.PROD_NPM_DEPENDENCIES.concat(normalizeDependencies(additional_deps));

    this.APP_ASSETS = [
      // {src: `${this.ASSETS_SRC}/css/toastr.min.css`, inject: true},
      // {src: `${this.APP_DEST}/assets/scss/global.css`, inject: true},
      { src: `${this.ASSETS_SRC}/main.css`, inject: true },
    ];

    this.DEV_DEPENDENCIES = this.DEV_NPM_DEPENDENCIES.concat(this.APP_ASSETS);
    this.PROD_DEPENDENCIES = this.PROD_NPM_DEPENDENCIES.concat(this.APP_ASSETS);
  }
}

```

**Comment by mgechev** [comment]
This looks fine. We definitely need to consider injecting the dependencies provided by the project config first.

// cc @ludohenin

**Comment by ludohenin** [comment]
Not sure it should always be first, but don't you think we should have the possibility to `append` and `prepend` ?
I've achived that in one of my project this way:

```ts
APP_ASSETS: InjectableDependency[] = [
  { src: `${this.ASSETS_SRC}/prism.min.js`,  inject: 'libs' },
  { src: `${this.ASSETS_SRC}/prism.css`, inject: true },
  ...this.APP_ASSETS
];
```

Maybe we should provide an abstraction layer for this ?
```ts
config(APP_ASSETS)
  .append([/*injectableDependencies*/])
  .prepend([/*injectableDependencies*/])
```

**Comment by Sn3b** [comment]
Indeed this would be nice, as a quick google search confirmed normalize.css needs to be first.
