### ISSUE TITLE
Production build not including dependencies

### ISSUE THREAD

**Issue by aderito7** [mgechev/angular2-seed#621]
I am running `npm run build.prod` and I can't see where I can do anything else to ensure that my node_modules references are included into my `prod` folder. One would assume that this would just take care of this for you or otherwise there would be some docs / guidelines / advice / whatever on how to achieve this.

Sorry if I missed it :)

**Comment by d3viant0ne** [comment]
@aderito7 - The documentation in this area definitely needs to be expanded, so no you didn't miss it.

It's going to depend on exactly what you are trying to do, so a bit more specific information would be helpful.

That said, there have been numerous discussion on the toping in Gitter and in a few closed issues.

#473 #468 & in particular #527 ( links in first comment from @mgechev )

If you can add a specific use case, I'm sure one of us can help you out. Also either a link to the repo or a plunkr would also be a good idea.

**Comment by mgechev** [comment]
I think we can close it for now.

@aderito7 the production build uses similar config to `dev` since it takes advantage of the SystemJS builder.

**Comment by aderito7** [comment]
@mgechev Does SystemJS loader get its bootstrap and jQuery from the node_modules for both PROD and DEV environments?
More specific I think I should be asking is it possible yet to to create packaged PROD build that I may upload to a live environment? Does angular2-seed aim to achieve this or is it something I will have to hack myself. I've had to copy my PROD folder along with node_modules folders to a live server in order to have a full functional app with all my dependencies. I hope I made sense...

**Comment by mgechev** [comment]
You don't have to. The production build creates self contained application by bundling all the libraries you are using inside of your application, together with the application itself. The bundles are then packed as cjs modules and minified.

**Comment by aderito7** [comment]
The production build is now working as expected after a fix to #627, I'm not sure if perhaps I did not state the issue clearly, but I'm glad it's all fixed now :)

**Comment by mgechev** [comment]
You were quite clear. In the last commits we did a lot of changes in the seed which introduced some issues. In all cases, we'll work on taking care of all of them.

Let us know if you find anything else.
