### ISSUE TITLE
html_css.prod task error - cssnano

### ISSUE THREAD

**Issue by ggaborx** [mgechev/angular2-seed#625]
The build.html_css.prod.ts task fails with this error:
>  TypeError: plugins.cssnano is not a function

**Comment by TheDonDope** [comment]
Hi @ggaborx,

on which release / commit are you having this error.

I just tested it with cdfb4992322265920d288f77e53e8a71dfaee641 and it works fine. Can you please copy the latest commit id from `$ git log` in your local repository?

**Comment by d3viant0ne** [comment]
@ggaborx I've tried this as well and I can't reproduce. @TheDonDope suggestion is probably going to be the answer here as I'm pretty sure you are either behind master or out of sync with it. 

If you are sure you are up to date but have extended the project, I'd suggest a diff of the tools & config. I've personally goofed up when pulling in changes from the seed before ( more than once ).

**Comment by ggaborx** [comment]
@TheDonDope, @d3viant0ne: you are all right. I mixed up my source with the latest commit and I didn't realized that the html_css.prod.ts removed. 

BTW my original issue was that if I listed some external .css in the DEV_DEPENDENCIES (inside project.config.ts) it skipped by the html_css.ts task. As I see it is still true.

**Comment by d3viant0ne** [comment]
@ggaborx - Trying to make sure I understand. Adding a "project" dependency for external .css isn't being picked up by the html_css.ts task?

**Comment by ggaborx** [comment]
@d3viant0ne : I created a new issue for this because its not related to the cssnano.
