### ISSUE TITLE
Call to NameListService.get executed 12 times

### ISSUE THREAD

**Issue by Sn3b** [mgechev/angular2-seed#626]
After cloning the repo, I just run the seed, set a break point to the return line of the get method in the NameListService, and it gets hit over 10 times when I get to the Home page, is it normal?

**Comment by mgechev** [comment]
We are using the default change detection strategy. During the initialization there are multiple passes of the CD so most likely this is a normal behavior.

**Comment by Sn3b** [comment]
Ok thanks :)
