### ISSUE TITLE
Made my own App class - template url is wrong (404)

### ISSUE THREAD

**Issue by alvipeo** [mgechev/angular2-seed#628]
All I did is use my own App class as a component but when I run the prj I get 404:

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR): GET - http://localhost:5555/app.html

This url is wrong, it should be http://localhost:5555/app/components/app.html

I spent hours and can't get it to work :( Here's component code:
```
import {Component} from 'angular2/core';
import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
import {FORM_PROVIDERS} from 'angular2/common';

import {RouterActive} from './directives/router-active';
import {IlgGalleryEditor} from "./galleryEditor/galleryEditor";
import {stateAndDispatcher} from "./diconfig";

// TESTING
import {UploaderTest} from "./uploaderTest";

@Component({
    selector: 'app',
    providers: [...FORM_PROVIDERS, stateAndDispatcher],
    directives: [...ROUTER_DIRECTIVES, RouterActive],
    pipes: [],
    templateUrl: "./app.html"
})
@RouteConfig([
    { path: "/editor/...", name: "GalleryEditor", component: IlgGalleryEditor },    // , useAsDefault: true
    { path: "/uploader", name: "UploaderTest", component: UploaderTest },
])
export class App {   // implements OnInit
    angularclassLogo = 'assets/img/angularclass-avatar.png';

    //constructor() {}
}
```
The folder structure is the same. The only difference I do not name it app.component.* - just app.* (all classes are either components or services in ng2, they usually reside in different folders so..)

**Comment by d3viant0ne** [comment]
@alvipeo - Can you add your main.ts as well please

**Comment by alvipeo** [comment]
main.ts

```
import {provide, enableProdMode} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
import {ROUTER_PROVIDERS, APP_BASE_HREF} from 'angular2/router';
import {App} from './app/components/app';

if ('<%= ENV %>' === 'prod') { enableProdMode(); }

bootstrap(App, [
  ROUTER_PROVIDERS,
  provide(APP_BASE_HREF, { useValue: '<%= APP_BASE %>' })
]);

// In order to start the Service Worker located at "./sw.js"
// uncomment this line. More about Service Workers here
// https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
// if ('serviceWorker' in navigator) {
//   (<any>navigator).serviceWorker.register('./sw.js').then(function(registration) {
//     console.log('ServiceWorker registration successful with scope: ',    registration.scope);
//   }).catch(function(err) {
//     console.log('ServiceWorker registration failed: ', err);
//   });
// }
```

**Comment by mgechev** [comment]
@alvipeo try `./app/components/app.html` for `templateUrl`.

**Comment by alvipeo** [comment]
That fixes it but when I run 'npm test' I get almost the same error (which is fixed reverting to the original path). So either build or test works.

**Comment by d3viant0ne** [comment]
@alvipeo - The seed is designed to work with the conventions defined in the style-guide so i'm not terribly surprised that something else isn't picking the change up.

Changing the tools to deviate from the conventions kind of defeats the purpose and is going to make picking up changes to the tools more of a chore for you.

**Comment by d3viant0ne** [comment]
It's also worth noting that what is pasted above for your app component isn't from the seed.

**Comment by alvipeo** [comment]
True. But that's simple component with templateUrl. Also, it has a pretty simple test. The issue is with templateUrl path which works either in build or a test. No style guide would cover that.

**Comment by Tmeister** [comment]
@alvipeo I had the same issue; I create a simple component and the templateUrl always shows a 404 error, the error was gone when I add the moduleId parameter in the `@Component ` definition.

```javascript
import {Component} from 'angular2/core';

@Component({
  selector: 'sd-brand',
  moduleId: module.id,
  templateUrl: './brand.component.html'
})

export class BrandComponent {
}
```

**Comment by alvipeo** [comment]
Oh, thanks! That's a hidden gem :)

**Comment by sunkarashruthi** [comment]
Hello everyone! I am new to Angular2, Pl correct me if am wrong.

I get 404: angular2.dev.js:20736 GET http://localhost:3000/app/contact-form.component.html 404 (Not Found)
I have all the components in my app folder.

Below is my root component:
app.component.ts
import {Component} from 'angular2/core';
import {ContactFormComponent} from './contact-form.component';


 @Component({
 		selector: 'my-app',
 		directives:[ContactFormComponent],
 		template: `
 			<contact-form></contact-form>
 		`
 	
 		
})
export class AppComponent { 

	}

contact-form.component.ts:
import {Component} from 'angular2/core';


 @Component({
 		selector: 'contact-form',
 		templateUrl:'app/contact-form.component.html'
 		
})
export class ContactFormComponent { 

	}

contact-form.component.html
<form>
	<div class="form-group">
		<label for="firstname"> First Name</label>
			<input id ="firstname" type="text" class="form-control"></input>
	</div>
	<div class="form-group">
        <label for="lastname"> Last Name</label>
			<input id ="lastname" type="text" class="form-control"></input>
	</div>
<div class="form-group">
        <label for="comment">Comment</label>
			<textarea id ="comment" cols="30" rows="10"class="form-control"></textarea>
	</div>
		<button class="btn btn-primary" type="submit">Submit</button>
</form>

How can i resolve my 404 issue?

**Comment by arun-awnics** [comment]
Hi @sunkarashruthi You should declare contact-form component in the app module before you load it. Have you done it? Try doing it if not. That should resolve the issue.
