### ISSUE TITLE
Cache bust for resources in CSS

### ISSUE THREAD

**Issue by Paladinium** [mgechev/angular2-seed#631]
Say you add a style to src/assets/main.css that references an image, e.g.

```
.my-style {
   background-image: url("./img/my_image.png");
}
```

It would be great to have support from angular2-seed to have a cache bust in the resulting CSS file, at least for prod (in dist/prod/css/all.css):

```
.my-style {
   background-image: url("./img/my_image.png?some_cache_bust");
}
```

I see that there are some gulp plugins for that kind of functionality, but I don't know which one is the best (e.g. gulp-buster, gulp-rev, gulp-rev-css-url, ...) and it surely would be awesome to have angular2-seed support this out-of-the-box.

Just to say, angular2-seed already applies the cache bust to resources like JS and CSS files referenced from index.html for the prod environment. This issue is about resources _within_ the resulting CSS.

**Comment by ludohenin** [comment]
Can't this be handled by `post-css` stuffs ?

// cc @tsm91

**Comment by d3viant0ne** [comment]
@ludohenin - https://www.npmjs.com/package/postcss-cachify though I would be interested if @tsm91 knows of a more mainstream package to handle this.

**Comment by tsm91** [comment]
@ludohenin @d3viant0ne never tried this with a postcss plugin before, but actually [postcss-assets](https://github.com/assetsjs/postcss-assets#cachebuster) handles this too

it should work, and there is an existing recipe for the implementation

**Comment by d3viant0ne** [comment]
@tsm91 - You're the resident postcss guy, pick one and we will spec out the enhancment

**Comment by tsm91** [comment]
i would go with postcss-assets for now

**Comment by mgechev** [comment]
So we can close it for now. This [wiki page could be used](https://github.com/mgechev/angular2-seed/wiki/Add-PostCSS-Assets-to-the-CSS-pre-processing-stack). @tsm91 let me know if I am wrong.

**Comment by Paladinium** [comment]
@mgechev : thanks a lot for the wiki. Why did you decide not to add it to your product? To me, it looks like an extremly useful feature.

**Comment by tsm91** [comment]
@mgechev in some sort of way this should be added to the project i think, i mean a production build should support this kind of functionality

if we dont want to do it with `postcss-assets` (i never did cache busting that way) we can still do something like the `gulp-rev` and `gulp-rev-replace` combo. Something like [here](https://github.com/tsm91/gulp-starter/tree/master/tools/tasks) the rev-assets and rev-update-references tasks

**Comment by ouq77** [comment]
I am using gulp-rev and gulp-rev-replace. Happy to add to this project if there is an appetite for it.

**Comment by mgechev** [comment]
@tsm91 yes, lets it. May be `postcss-assets` makes sense since we already use `gulp-postcss` already.

**Comment by tsm91** [comment]
@mgechev one thing to note, you will have to use `resolve()` in order to apply the cachebusting functionality. That means it is a must to use postcss-assets, and implement a custom stylelint rule to enforce the usage of resolve. 

p.s: sorry for late responses, i am still packing out my stuff because i moved back to budapest
