### ISSUE TITLE
How-to: debug unit test

### ISSUE THREAD

**Issue by HNeukermans** [mgechev/angular2-seed#634]
I'm having trouble trying to get karma run a test in debug.
Is this feature supported inside ng2-seed.

I'm isolating the test with ddescribe and adding a debugger statement in inside the test I want to run. 
However for some reason karma does not break into my test.

Could you provide some guidance? Would be really helpfull.

**Comment by d3viant0ne** [comment]
@HNeukermans 

Step one in debugging anything in the tools is to compile them to JS.

- Set DEBUG === true in the config
- gulp build.tools

This allows debugging using "node debugger" ( for future reference )

I'm guessing here but my bet is it's getting lost in the typescript somewhere ( depending on how you are running karma while debugging )

- Something else to try would be to execute karma directly from the command line ( if you aren't already )

I'll have to to try it when I get home to give you an answer based in fact.
