### ISSUE TITLE
Possibility to watch config files. 

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#637]
When changing config files on build.dev, i have to manually restart the task. Can it be automated?

**Comment by d3viant0ne** [comment]
Wouldn't be too much work to stick it in your project tasks. I  personally don't know how I feel about opening up the watch to all the tooling but my first impression would be, given the extensibility built into the tooling that would tend to be flakey.

//cc @ludohenin @mgechev

**Comment by ludohenin** [comment]
I think it would be better to use something like `nodemon` for that ?

**Comment by d3viant0ne** [comment]
After giving this a bit more thought, it's really not viable imo.

- Given that a change in the tools could very well change how / what / where you are outputting you would have to trigger a rebuild 
- That rebuild depending on what changed may or may not function the same way as the existing which would leave you in a messy state.

There certainly isn't a reason why you can't add a watch to your project tasks but I personally don't see this one being viable for all the options we support.
