### ISSUE TITLE
Adding auth0/angular-jwt to the seed

### ISSUE THREAD

**Issue by Myrmex** [mgechev/angular2-seed#640]
I'm trying to add [auth0](https://auth0.com) support to this seed: basically, this should imply adding the NPM package `angular2-jwt`, yet as a newbie I'm probably missing something as I get errors when launching the app. Could anyone give some guidance? Maybe such questions are somewhat useful for writing entry-level docs about packages configuration. Here are my steps:

* (1) `npm install --save angular2-jwt` to install the package.

* (2) in `seed.config.ts`, add to SystemJS config this entry:

```typescript
    'angular2-jwt': `${this.APP_BASE}node_modules/angular2-jwt/angular2-jwt`,
```

* (3) in `main.ts`, add DI for `AuthHttp`:

```typescript
    import {Http} from 'angular2/http';
    import {AuthHttp, AuthConfig} from 'angular2-jwt';
    //...
    bootstrap(AppComponent, [
      ROUTER_PROVIDERS,
      provide(APP_BASE_HREF, { useValue: '<%= APP_BASE %>' }),
      provide(AuthHttp, {
          useFactory: (http: Http) => {
            return new AuthHttp(new AuthConfig(), http);
          },
          deps: [Http]
      }),
    ]);
```

If now I try using AuthHttp e.g. in `app.ts`, I get the angular2 EXCEPTION: No provider for Http! (AppComponent -> AuthHttp -> Http). Http is a dependency of AuthHttp, but I thought this should be taken care of by my changes in bootstrap.

**Comment by Sn3b** [comment]
import {AuthHttp, tokenNotExpired, JwtHelper} from 'angular2-jwt/angular2-jwt';

**Comment by d3viant0ne** [comment]
And don't add things to the seed-config, extending projects should be done in the project config

**Comment by Myrmex** [comment]
Sorry, I edited my comment before getting your replies (my connection has troubles). I fixed the typo but I'm getting some errors in the AuthHttp dependencies.

**Comment by Myrmex** [comment]
Thanks again, as for d3viant0ne's comment, I removed the line from `seed.config.ts` and added it in `project.config.ts` at the end of its constructor, like:

```typescript
    (<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-jwt'] =
        `${this.APP_BASE}node_modules/angular2-jwt/angular2-jwt`;
```

Is this the intended way of handling such cases in the seed? Apart from this, I'm still getting the Http injection error.

**Comment by Myrmex** [comment]
Ok, found it, I had forgotten to move the HTTP_PROVIDERS "macro" before the provide in bootstrap. Sorry to bother. Anyway, this discussion helped me getting more in touch with the intended seed usage, thanks to all again.

**Comment by Sn3b** [comment]
Not sure you actually need anything in any of the config files. I implemented Auth0 with the seed myself but on an older version and I didn't touch the config.

**Comment by Myrmex** [comment]
The config are required to import the angular2-jwt modules, even if there seems to be some errors in TS, probably the angular2 version used by the JWT library is not synched with that used by the seed (see below). Anyway this does not seem to harm. To recap, as this might be useful to someone else:

* (1) `npm install --save angular2-jwt` to install the package.

* (2) in `project.config.ts`, add to the end of the constructor code:

```typescript
(<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-jwt'] =
        `${this.APP_BASE}node_modules/angular2-jwt/angular2-jwt`;
```

* (3) in `main.ts`, add DI for AuthHttp (remember to import HTTP_PROVIDERS too!):

```typescript
    import {Http, HTTP_PROVIDERS} from 'angular2/http';
    import {AuthHttp, AuthConfig} from 'angular2-jwt';
    //...
    bootstrap(AppComponent, [
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(APP_BASE_HREF, { useValue: '<%= APP_BASE %>' }),
      provide(AuthHttp, {
          useFactory: (http: Http) => {
            return new AuthHttp(new AuthConfig(), http);
          },
          deps: [Http]
      }),
    ]);
```

* (4) usage example:

```typescript
import {AuthHttp} from 'angular2-jwt/angular2-jwt';
//... use in your code ...
```

The TS errors are like:

* `main.ts`: error TS2345: Argument of type 'Http' is not assignable to parameter of type 'Http'.
  Property '_backend' is protected but type 'Http' is not a class derived from 'Http'.
* when using `AuthHttp`: error TS2322: Type 'Observable<Response>' is not assignable to type 'Observable<Response>',  and Property 'source' is protected in type 'Observable<Response>' but public in type 'Observable<Response>'.

**Comment by mgechev** [comment]
@Myrmex thanks for the great explanation! I didn't get any TS errors with the latest version of the seed.

Would you want to update the wiki page?

**Comment by Myrmex** [comment]
Did it right now, I'm happy to give my 2 cents to this wonderful seed.

**Comment by mgechev** [comment]
Thank you!

**Comment by geminiyellow** [comment]
@mgechev thanks for your seed.
and this question's answer.

and follow this issue, i can import `angular2-jwt` in the project. 
but what i want to ask is, could i use SystemJS import Auth0Lock.

i copy some code from `auth0-samples/auth0-angularjs2-systemjs-sample`,
and notice that, it use `Auth0Lock` by script in `index.html`.
i read the `SystemJS`'s docs, and i try to include it like the `angular2-jwt`, 
but alway `EXCEPTION: Error in :0:0 caused by: Auth0Lock is not defined`.

could you tell me how to import it?

**Comment by geminiyellow** [comment]
i can use it like

```
{
  map: {
    'auth0-lock': 'cdn link'
  }
}
```

or tons of deps 

```
{
  map: {
    'auth0-lock': 'npm:auth0-lock',
    'npm:auth0-lock': {
      ...
    }
  }
}
```

is there any simple method to import it?

**Comment by Tiger-man** [comment]
# - ll4**54554540**
