### ISSUE TITLE
Dangerous npm run reinstall

### ISSUE THREAD

**Issue by Toktik** [mgechev/angular2-seed#641]
The new way for deleting dependencies before install is dangerous in `npm run reinstall` call, you can easily lose new files.

I'm about this piece of code.
`git clean -dfx -e '.*'`

I just ripped of some new components I wrote :smiley:

**Comment by d3viant0ne** [comment]
Personally, I think the reinstall task does exactly what the name implies. That said, the situation above kind of sucks and accidentally deleting peoples code is an unacceptable side effect.

Options 
- Keep reinstall and add a console interaction you have to accept but can override with something like -y
- Modify reinstall in it's current state to only clean the root level of the project
- Go back to rimraf and deal with the Windows / All other "non sucking" operating systems.

//cc @mgechev @ludohenin

**Comment by ludohenin** [comment]
@d3viant0ne I would not expect `reinstall` to delete my code but reinstall dependencies only. Maybe `reset | reinitialize` or something to start from a clean project.

**Comment by ludohenin** [comment]
Prompt confirmation is a must have here I think.

**Comment by mgechev** [comment]
I removed the script just to make sure we won't experience such issues in future.

I'm mostly for `rimraf`, I'll explore how we can deal with it on windows.
