### ISSUE TITLE
SASS support wiki suggestion

### ISSUE THREAD

**Issue by kiuka** [mgechev/angular2-seed#642]
Hello,

I tried to add SASS support follow the steps in the wiki, but it fails due to tslint, error and a missing param.

The copied import line
import {APP_SRC, TMP_DIR, CSS_PROD_BUNDLE, CSS_DEST, APP_DEST, BROWSER_LIST, ENV, getEnvDependencies} from '../../config';

should be look like the following:

import {APP_ASSETS, APP_SRC, TMP_DIR, CSS_DEST, APP_DEST, BROWSER_LIST, ENV} from '../../config';

**Comment by d3viant0ne** [comment]
I'll get it updated. For reference, @nareshbhatia also maintains an example repo - https://github.com/archfirst/angular2-seed-sass

**Comment by d3viant0ne** [comment]
And thanks btw :)

Polite usually shows up after the first cup of coffee.

**Comment by kiuka** [comment]
yes, I've used it until now, but unfortunately it has the old config structure, so I moved to the new one:)

**Comment by mgechev** [comment]
@kiuka would be great if you help with the update of the wiki page!

**Comment by simonh1000** [comment]
+1 - for me, and I think a few others, not having sass support is major roadblock to adopting the seed

**Comment by kiuka** [comment]
@mgechev it needs only the line above that I mentioned, everything else worked fine for me:)

**Comment by simonh1000** [comment]
In which file?

**Comment by kiuka** [comment]
Copy /tools/tasks/seed/build.html_css.ts to /tools/tasks/project/build.html_scss.ts. Open it up and edit it like this:

in this step:
Edit the file like that, and change the import at the top of the file from
import {APP_SRC, TMP_DIR, CSS_PROD_BUNDLE, CSS_DEST, APP_DEST, BROWSER_LIST, ENV, getEnvDependencies} from '../../config';


to:
import {APP_ASSETS, APP_SRC, TMP_DIR, CSS_DEST, APP_DEST, BROWSER_LIST, ENV} from '../../config';


thats all, after that it should works:)

**Comment by simonh1000** [comment]
I think I am doing somehing wrong as I get one of these errors for each components - can you advise?

And now I have just seen that there are two guides to SASS on the wiki
 - https://github.com/mgechev/angular2-seed/wiki/Add-custom-Gulp-task
 - https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support

Which one have you made work?

@mgechev - it would be great if your be ruthless and delete whichever guide is not best practise

```
[15:53:57] Plumber found unhandled error:
 Error in plugin 'gulp-inline-ng2-template'
Message:
    ENOENT: no such file or directory, open '/home/sim/code/btsync/HTML/tcx/ng2/dist/tmp/lap/lap/lap.css'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: /home/sim/code/btsync/HTML/tcx/ng2/dist/tmp/lap/lap/lap.css
    fileName: /home/sim/code/btsync/HTML/tcx/ng2/dist/tmp/lap/laps.ts
```

**Comment by kiuka** [comment]
I have used the second one (https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support)

**Comment by mgechev** [comment]
Ok, great so we can close this issue :-)

@kiuka would you fix the incorrect link?

**Comment by kiuka** [comment]
Yes, I've added the missing line to the wiki:)

**Comment by simonh1000** [comment]
I've spent all afternoon trying this, and it all works in dev but I'm not getting an compiled SASS coming through in production. From what I can see, all the css files have been put in `/dist/tmp` EXCEPT main.scss, but it is only the latter (compiled) that is making it through to `/dist/prod`

Any more ideas?

**Comment by simonh1000** [comment]
I think there is an error in these instructions, that becomes apparent when you want to use e.g. bootstrap as well (cc @d3viant0ne ). I have not tracked it all down but I'm pretty certain we need to make getExternalScss use

`PROD_DEPENDENCIES.filter(d => /\.scss$/.test(d.src));`

At present is uses `APP.ASSETS`, which generally only includes main.scss. 

Based on https://github.com/mgechev/angular2-seed/wiki/Add-an-external-styles I think the scss version would be 

```
    let additional_deps: Array<any> = [
        {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
        {src: 'bootstrap/dist/js/bootstrap.min.js', inject: 'libs'},
        {src: 'bootstrap-sass/assets/stylesheets/_bootstrap.scss', inject: true}, // inject into scss section
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];
```

which gets brought into 'scope' through

    this.PROD_DEPENDENCIES = this.PROD_NPM_DEPENDENCIES.concat(this.APP_ASSETS);

However, even with these changes I can't get bootstrap into my production builds, so this is not everything that needs consideration

**Comment by nareshbhatia** [comment]
FYI, the [angular2-seed-sass](https://github.com/archfirst/angular2-seed-sass) project has now been synced up with the latest angular2-seed. Thanks to  @asgarddesigns for his efforts.
