### ISSUE TITLE
Subsequent variable declarations must have the same type. Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.

### ISSUE THREAD

**Issue by Sn3b** [mgechev/angular2-seed#643]
Trying to add dependency to JQuery as well as JQuery typings, but when I try to run I get the above error...

As a work around I have changed the type of $ from JQueryStatic to cssSelectorHelper at the bottom of the files typings/browser/ambient/jquery/index.d.ts and typings/main/ambient/jquery/index.d.ts, but is there a more elegant or automated way to achieve this?

**Comment by mgechev** [comment]
Hey @Sn3b it seems your problem is mostly related to the jQuery type definition itself not to the seed. You can contact the maintainer of the package.

**Comment by Sn3b** [comment]
Yes indeed, but I was hoping you guys had run into a similar issue and found a better work around ;)

Thanks!
