### ISSUE TITLE
Including Bootstrap in a project

### ISSUE THREAD

**Issue by simonhull** [mgechev/angular2-seed#647]
I followed the instructions on the wiki about adding bootstrap in as a dependency.  The styles work fine but none of the Javascript is working, things like dropdown menus and accordions have no interactivity.  
I can get the javascript to work if I place the code in the root HTML file, but not when it's inside a component.

Am I missing something?

**Comment by d3viant0ne** [comment]
Dependencies should be added in the project.config

Easiest way to figure out what is or isn't making it in would be to check what is being injected into the generated index.html

Figure out what isn't there and you will know what you are missing in the systemjs config

**Comment by simonhull** [comment]
Sorry, I should have clarified, both are registered in the project.config, and both are being included when the page is run. 
Again Bootstrap components can be used in the index.html file at the root of the src folder just fine. Everything works perfectly. But any code in components will be properly styled but without the javascript interaction.
.
I've also tried using Bootstraps CDN links, and including the files in the assets folder as opposed to node_modules

**Comment by sfabriece** [comment]
Having the same problem when adding dependency on foundation. The css works, but the javascript doesn't. Would be helpful for someone who has gotten it to work to include a guide.

**Comment by d3viant0ne** [comment]
@simonhull - Bootstrap example of the seed coming up.

Just finishing the Material2 version, i'll have it done this evening.

**Comment by d3viant0ne** [comment]
For reference, it will be here - https://github.com/DeviantJS/angular2-seed-ng2-bootstrap

**Comment by d3viant0ne** [comment]
For reference, the production build will take a bit of work. It works fine for Dev.

I'm going to close this, if you have ng2-bootstrap related questions, feel free to ask in the example repo.

Hoping to have the dist build worked out this evening.
