### ISSUE TITLE
Gulp.test build task: type errors

### ISSUE THREAD

**Issue by ultrasonicsoft** [mgechev/angular2-seed#65]
Hi There,

I am trying to run your seed-test project without any modification. But it's failing in test with below errors:
        
    C:\angular2\angular2-seed-test>gulp test
    [09:55:50] Using gulpfile C:\angular2\angular2-seed-test\gulpfile.js
    [09:55:50] Starting 'build.test'...
    app\components\about\about_spec.ts(16,19): error TS2307: Cannot find module 'ang
    ular2/src/dom/dom_adapter'.
    app\components\about\about_spec.ts(24,31): error TS2345: Argument of type 'typeo
    f TestComponent' is not assignable to parameter of type 'Type'.
      Type 'TestComponent' is not assignable to type 'Type'.
        Property 'apply' is missing in type 'TestComponent'.
    app\components\home\home_spec.ts(16,19): error TS2307: Cannot find module 'angul
    ar2/src/dom/dom_adapter'.
    app\components\home\home_spec.ts(23,30): error TS2345: Argument of type 'typeof
    TestComponent' is not assignable to parameter of type 'Type'.
      Type 'TestComponent' is not assignable to type 'Type'.
        Property 'apply' is missing in type 'TestComponent'.
    [09:55:55] TypeScript: 4 semantic errors
    [09:55:55] TypeScript: emit succeeded (with errors)
    [09:55:55] Finished 'build.test' after 5.2 s
    [09:55:55] Starting 'karma.start'...
    INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
    INFO [launcher]: Starting browser Chrome
    INFO [Chrome 44.0.2403 (Windows 8.1 0.0.0)]: Connected on socket PipeNHjYqtNISFs
    yASA7 with id 48809517
    Chrome 44.0.2403 (Windows 8.1 0.0.0): Executed 1 of 3 SUCCESS (0 secs / 0.008 se
    Chrome 44.0.2403 (Windows 8.1 0.0.0): Executed 2 of 3 SUCCESS (0 secs / 0.209 se
    Chrome 44.0.2403 (Windows 8.1 0.0.0): Executed 3 of 3 SUCCESS (0 secs / 0.228 se
    Chrome 44.0.2403 (Windows 8.1 0.0.0): Executed 3 of 3 SUCCESS (0.239 secs / 0.22
    8 secs)
    [09:56:21] Finished 'karma.start' after 26 s
    [09:56:21] Starting 'test'...
    [09:56:21] Finished 'test' after 36 ms

Here are the steps I followed:
1. Downloaded zip version of seed-test project
2. Ran "npm install" command
3. Ran "gulp serve.dev" -> works fine
4. Ran "gulp test" -> failed.

Could you please let me how to solve this error?

Thanks!

**Comment by ludohenin** [comment]
@ultrasonicsoft your logs say that the test are passing (`Executed 3 of 3 SUCCESS`).
Even though there are some TypeScript type cheching error, they are not blocking ... I have to fix that in [custom types](https://github.com/mgechev/angular2-seed/blob/test/app/typings/ng2_test.d.ts)

**Comment by ultrasonicsoft** [comment]
Thanks for reply ludohenin!

Yes, log says (Executed 3 of 3 SUCCESS). but there are errors too as below:

	error TS2307: Cannot find module 'ang
	ular2/src/dom/dom_adapter'.
	app\components\about\about_spec.ts(24,31): error TS2345: Argument of type 'typeo
	f TestComponent' is not assignable to parameter of type 'Type'.
	  Type 'TestComponent' is not assignable to type 'Type'.
		Property 'apply' is missing in type 'TestComponent'.
	app\components\home\home_spec.ts(16,19): error TS2307: Cannot find module 'angul
	ar2/src/dom/dom_adapter'.
	app\components\home\home_spec.ts(23,30): error TS2345: Argument of type 'typeof
	TestComponent' is not assignable to parameter of type 'Type'.
	  Type 'TestComponent' is not assignable to type 'Type'.
		Property 'apply' is missing in type 'TestComponent'.
	[09:55:55] TypeScript: 4 semantic errors

I am very new to karma and jasmine. Could you please let me know whether should I ignore these errors, or should I take any latest code of yours to remove these erros?

Could you please also let me know if you have any e2e test using protractor?

Thanks a lot!

**Comment by ludohenin** [comment]
As stated above, they are TypeScript errors (occured during stranspiling phase: convertion es6/es7 -> es5) and have nothing to do with jasmine and/or karma. It is also stated in the log that `TypeScript: emit succeeded (with errors)`
No e2e tests at the moment.

**Comment by ultrasonicsoft** [comment]
Okay. Thank you very much for your help!

**Comment by ludohenin** [comment]
This is not solved, I have changed the title and types errors have to cleared.

**Comment by ultrasonicsoft** [comment]
Hi 

When I re-ran "gulp test" for second time, I got below error. Seem 3rd test is failing. I haven't change anything. I have try to pull latest code 30 mins ago and then ran "npm install" and then "gulp test".

Am I missing anything?

Please advise.

Thanks in advance!

	C:\TEMP\angular2-seed-test>gulp test
	[15:46:39] Using gulpfile C:\TEMP\angular2-seed-test\gulpfile.js
	[15:46:39] Starting 'build.test'...
	app\components\about\about_spec.ts(16,19): error TS2307: Cannot find module 'ang
	ular2/src/dom/dom_adapter'.
	app\components\about\about_spec.ts(24,31): error TS2345: Argument of type 'typeo
	f TestComponent' is not assignable to parameter of type 'Type'.
	  Type 'TestComponent' is not assignable to type 'Type'.
		Property 'apply' is missing in type 'TestComponent'.
	app\components\home\home_spec.ts(16,19): error TS2307: Cannot find module 'angul
	ar2/src/dom/dom_adapter'.
	app\components\home\home_spec.ts(23,30): error TS2345: Argument of type 'typeof
	TestComponent' is not assignable to parameter of type 'Type'.
	  Type 'TestComponent' is not assignable to type 'Type'.
		Property 'apply' is missing in type 'TestComponent'.
	[15:46:41] TypeScript: 4 semantic errors
	[15:46:41] TypeScript: emit succeeded (with errors)
	[15:46:41] Finished 'build.test' after 1.46 s
	[15:46:41] Starting 'karma.start'...
	INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
	INFO [launcher]: Starting browser Chrome
	INFO [Chrome 29.0.1547 (Windows 7 0.0.0)]: Connected on socket PXOMZir5VVB0p3pQQ
	kBA with id 98949632
	WARN [web-server]: 404: /base/node_modules/systemjs/dist/system-polyfills.js
	WARN [Chrome 29.0.1547 (Windows 7 0.0.0)]: Disconnected (1 times), because no me
	ssage in 10000 ms.

	[15:46:54] 'karma.start' errored after 13 s
	[15:46:54] Error: 1
		at formatError (C:\Users\apatel2\AppData\Roaming\npm\node_modules\gulp\bin\g
	ulp.js:169:10)
		at Gulp.<anonymous> (C:\Users\apatel2\AppData\Roaming\npm\node_modules\gulp\
	bin\gulp.js:195:15)
		at Gulp.emit (events.js:107:17)
		at Gulp.Orchestrator._emitTaskDone (C:\TEMP\angular2-seed-test\node_modules\
	gulp\node_modules\orchestrator\index.js:264:8)
		at C:\TEMP\angular2-seed-test\node_modules\gulp\node_modules\orchestrator\in
	dex.js:275:23
		at finish (C:\TEMP\angular2-seed-test\node_modules\gulp\node_modules\orchest
	rator\lib\runTask.js:21:8)
		at cb (C:\TEMP\angular2-seed-test\node_modules\gulp\node_modules\orchestrato
	r\lib\runTask.js:29:3)
		at removeAllListeners (C:\TEMP\angular2-seed-test\node_modules\karma\lib\ser
	ver.js:215:7)
		at Server.<anonymous> (C:\TEMP\angular2-seed-test\node_modules\karma\lib\ser
	ver.js:226:9)
		at Server.g (events.js:199:16)

	C:\TEMP\angular2-seed-test>

**Comment by ludohenin** [comment]
Strange, it works perfectly well for me.
Karma is crashing because of this `WARN [web-server]: 404: /base/node_modules/systemjs/dist/system-polyfills.js`. Please make sure you have npm packages installed correctly and that you have this file.

**Comment by ultrasonicsoft** [comment]
I followed below steps:
1. downloaded latest code (45 mins back)
2. ran "npm install"
3. ran "npm install gulp -g"
4. ran "gulp serve.dev"

I can see mentioned files are there.

Will you please advise me whether I should follow any different command/sequence?

![image](https://cloud.githubusercontent.com/assets/4145169/9578069/a5d1dce8-5004-11e5-9a01-a534a52a4b54.png)

Thanks!

**Comment by ludohenin** [comment]
ca you try to add `{ pattern: 'node_modules/systemjs/dist/*.js', included: false, watched: false }` to `files` array in `karma.conf.js` ?

**Comment by ultrasonicsoft** [comment]
You are Awesome man...
Hurray!! After adding this line, my test passed.

	C:\aj\angular2-seed-test>gulp test
	[17:33:55] Using gulpfile C:\aj\angular2-seed-test\gulpfile.js
	[17:33:55] Starting 'build.test'...
	[17:33:56] Finished 'build.test' after 1.46 s
	[17:33:56] Starting 'karma.start'...
	INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
	INFO [launcher]: Starting browser Chrome
	INFO [Chrome 29.0.1547 (Windows 7 0.0.0)]: Connected on socket T4SBKlcus8KHc-Sup
	HPF with id 78401738
	Chrome 29.0.1547 (Windows 7 0.0.0): Executed 1 of 3 SUCCESS (0 secs / 0.003 secs
	Chrome 29.0.1547 (Windows 7 0.0.0): Executed 2 of 3 SUCCESS (0 secs / 0.052 secs
	Chrome 29.0.1547 (Windows 7 0.0.0): Executed 3 of 3 SUCCESS (0 secs / 0.059 secs
	Chrome 29.0.1547 (Windows 7 0.0.0): Executed 3 of 3 SUCCESS (0.062 secs / 0.059
	secs)
	[17:34:02] Finished 'karma.start' after 5.17 s
	[17:34:02] Starting 'test'...
	[17:34:02] Finished 'test' after 9.18 ms

But "gulp serve.dev" still failing. Do you want me to share any of conf file?

Could you please let me know what's wrong in my any configuration?

Thanks!

**Comment by ludohenin** [comment]
`gulp serve.dev` may be related to [#64](https://github.com/mgechev/angular2-seed/issues/64)

**Comment by ultrasonicsoft** [comment]
I am sorry but #64 seem to be very specific developer discussion who wrote it from scratch. In my gulpfile.js I can see "transformPath" function with same definition as of #64 .

I am really not getting where to use concatination or what action item is proposed solution for the issue (where to change and what to change).

Will you please give me bit more pointers?

Thanks!

**Comment by aboeglin** [comment]
As I understood it, it should be about replacing the line :
```
arguments[0] = join(APP_BASE, filename);
```
with :
```
arguments[0] = APP_BASE + filename;
```

I think the problem is that path.join() generates backslahes on windows platform.

**Comment by ultrasonicsoft** [comment]
Hi ludohenin and aboeglin,

Thank you for your reply.

I have replaced path.join with + but it didn't work. I also tried replacing all occurrences of "join" with "+" but it seem "dist/dev" is missing when I did "+". I guess "dist/dev" is provided by "join" with backslash.

Does same gulpfile.js is working at your end on windows 8 machine? 

Could you please let me know what should I try else to solve this issue?

Thanks!

Updated gulpfile.js section:

	function transformPath(env) {
	  var v = '?v=' + getVersion();
	  return function (filepath) {
		var filename = filepath.replace('/' + PATH.dest[env].all, '') + v;
		arguments[0] = APP_BASE + '/' + filename;
		console.log(arguments[0]);
		return inject.transform.apply(inject.transform, arguments);
	  };
	}

"gulp serve.dev" command output is:

	C:\angular2\angular2-seed-master>gulp serve.dev
	[09:27:57] Using gulpfile C:\angular2\angular2-seed-master\gulpfile.js
	[09:27:57] Starting 'build.dev'...
	[09:27:57] Starting 'clean.dev'...
	[09:27:57] Starting 'livereload'...
	[09:27:57] Finished 'livereload' after 2.32 ms
	[09:27:57] Finished 'clean.dev' after 33 ms
	[09:27:57] Starting 'build.lib.dev'...
	[09:27:57] Finished 'build.lib.dev' after 38 ms
	[09:27:57] Starting 'build.app.dev'...
	[09:27:57] Starting 'clean.app.dev'...
	[09:27:57] Finished 'clean.app.dev' after 4.73 ms
	[09:27:57] Starting 'build.js.dev'...
	[09:27:59] Finished 'build.js.dev' after 1.28 s
	[09:27:59] Starting 'build.assets.dev'...
	[09:27:59] Finished 'build.assets.dev' after 13 ms
	[09:27:59] Starting 'build.index.dev'...
	[09:27:59] gulp-inject 9 files into index.html.
	//dist/dev/lib/traceur-runtime.js?v=0.0.0
	//dist/dev/lib/es6-module-loader-sans-promises.js?v=0.0.0
	//dist/dev/lib/Reflect.js?v=0.0.0
	//dist/dev/lib/system.src.js?v=0.0.0
	//dist/dev/lib/angular2.dev.js?v=0.0.0
	//dist/dev/lib/router.dev.js?v=0.0.0
	//dist/dev/app.css?v=0.0.0
	[09:27:59] Finished 'build.index.dev' after 32 ms
	[09:27:59] Finished 'build.app.dev' after 1.33 s
	[09:27:59] Finished 'build.dev' after 1.41 s
	[09:27:59] Starting 'serve.dev'...
	[09:27:59] Finished 'serve.dev' after 11 ms

Browser output:

![error](https://cloud.githubusercontent.com/assets/4145169/9595878/225e888a-508a-11e5-8df2-aa0e34914dab.png)

Dist folder structure:

![image](https://cloud.githubusercontent.com/assets/4145169/9595979/00d007aa-508c-11e5-9151-3c36ff344331.png)

**Comment by aboeglin** [comment]
If your APP_BASE is / then you shouldn't add the / but just concatenate like I posted above.

**Comment by ultrasonicsoft** [comment]
Hi aboeglin, 
Even with your approach I am getting same error.
Below is the function where I have replaced "join" with "+".

	function transformPath(env) {
	  var v = '?v=' + getVersion();
	  return function (filepath) {
		var filename = filepath.replace('/' + PATH.dest[env].all, '') + v;
		arguments[0] = APP_BASE + filename;
		return inject.transform.apply(inject.transform, arguments);
	  };
	}

Don't know what's wrong?

Sorry to bother you much..

**Comment by ludohenin** [comment]
@ultrasonicsoft it's been fixed. Would you please try with the latest master ?

**Comment by ultrasonicsoft** [comment]
Hi ludohenin,

I am following below steps:
1. Download latest master zip 
2. Unzip folder
3. run "npm install" command
4. run "gulp serve.dev" command

I got below error:

![image](https://cloud.githubusercontent.com/assets/4145169/9603267/2cef0142-50cd-11e5-84b6-80e8afabb22d.png)


After changing "join" to "+" in below function, I get below error:

	function transformPath(env) {
	  var v = '?v=' + getVersion();
	  return function (filepath) {
		var filename = filepath.replace('/' + PATH.dest[env].all, '') + v;
		arguments[0] = APP_BASE + filename;
		console.log();
		return inject.transform.apply(inject.transform, arguments);
	  };
	}
output of above command:

	C:\aj\seed-master\latest>gulp serve.dev
	[17:19:53] Using gulpfile C:\aj\seed-master\latest\gulpfile.js
	[17:19:53] Starting 'build.dev'...
	[17:19:53] Starting 'clean.dev'...
	[17:19:53] Starting 'livereload'...
	[17:19:53] Finished 'livereload' after 2.96 ms
	[17:19:53] Finished 'clean.dev' after 39 ms
	[17:19:53] Starting 'build.lib.dev'...
	[17:19:53] Finished 'build.lib.dev' after 47 ms
	[17:19:53] Starting 'build.app.dev'...
	[17:19:53] Starting 'clean.app.dev'...
	[17:19:53] Finished 'clean.app.dev' after 4.18 ms
	[17:19:53] Starting 'build.js.dev'...
	[17:19:54] Finished 'build.js.dev' after 1.43 s
	[17:19:54] Starting 'build.assets.dev'...
	[17:19:54] Finished 'build.assets.dev' after 15 ms
	[17:19:54] Starting 'build.index.dev'...
	[17:19:54] gulp-inject 10 files into index.html.
	//lib/traceur-runtime.js?v=0.0.0
	//lib/es6-module-loader-sans-promises.js?v=0.0.0
	//lib/Reflect.js?v=0.0.0
	//lib/system.src.js?v=0.0.0
	//lib/system.config.js?v=0.0.0
	//lib/angular2.dev.js?v=0.0.0
	//lib/router.dev.js?v=0.0.0
	//app.css?v=0.0.0
	[17:19:54] Finished 'build.index.dev' after 25 ms
	[17:19:54] Finished 'build.app.dev' after 1.48 s
	[17:19:54] Finished 'build.dev' after 1.58 s
	[17:19:54] Starting 'serve.dev'...
	[17:19:54] Finished 'serve.dev' after 15 ms

![image](https://cloud.githubusercontent.com/assets/4145169/9603316/8e3f701c-50cd-11e5-8950-916fbf1124f2.png)

Could you please let me know what's I am missing?

Thanks!

**Comment by ludohenin** [comment]
Your `lib` path start with double backslashes `\\lib\...`. That's why.

**Comment by ultrasonicsoft** [comment]
So what's should be correct path?
1. /dist/lib/...
2. /lib/...

And should that change be done across gulpfile for replacing "join" with "+" or only in "transformPath" function?

**Comment by ludohenin** [comment]
It should work as it is (I'm also on Windows plateform).Correct path is `/lib/my-lib.js`. 


     On Tuesday, September 1, 2015 1:59 PM, ultrasonicsoft <notifications@github.com> wrote:
   

 So what's should be correct path?
1. /dist/lib/...
2. /lib/...And should that change be done across gulpfile for replacing "join" with "+" or only in "transformPath" function?—
