### ISSUE TITLE
Test in a different directory than `dist/dev`

### ISSUE THREAD

**Issue by allenhwkim** [mgechev/angular2-seed#650]
Problem:
We cannot run test while `gulp serve.dev` is running because `gulp test clears `dist/dev` and rewrites every single file

Solution:
Run  tests in `dist/test` directory instead of `dist/dev` directory.

I have done this approach locally, and it was good experience for me.

**Comment by mgechev** [comment]
@allenhwkim I think @nareshbhatia tried this approach and it had some drawbacks. Take a look at https://github.com/mgechev/angular2-seed/issues/447#issuecomment-184010613

**Comment by d3viant0ne** [comment]
@allenhwkim - It has side effects when using pre/post processors. I've tried the same approach & what I get why you would want to, it's not generic enough to work for all the options we support.

**Comment by allenhwkim** [comment]
I do not know what exactly does not work. At least, I wish it does not delete all files and re-create when I run a test.

**Comment by mgechev** [comment]
@allenhwkim you can workaround it using:

```ts
// --------------
// Build test.
gulp.task('build.test', (done: any) =>
  runSequence(/* 'clean.dev', */
              'tslint',
              'build.assets.dev',
              'build.js.test',
              'build.index.dev',
              done));
```
