### ISSUE TITLE
Having trouble injecting normalize.css from node_modules?

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#651]

**Comment by sfabriece** [comment]
this is how my config looks like: 
`
export class ProjectConfig extends SeedConfig {
    PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

    constructor() {
        super();
        this.APP_TITLE = 'Perkd';
        let additional_deps: InjectableDependency[] = [
            // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
            // {src: 'lodash/lodash.min.js', inject: 'libs'},
            { src: 'foundation/js/vendor/jquery.js', inject: 'libs' },
            { src: 'foundation/js/vendor/custom.modernizr.js', inject: 'libs' },
            { src: 'foundation/js/foundation/foundation.js', inject: 'libs' }
        ];

        const seedDependencies = this.NPM_DEPENDENCIES;

        this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);

        this.APP_ASSETS = [
            { src: 'normalize.css/normalize.css', inject: true },
            { src: `${this.ASSETS_SRC}/css/foundation.css`, inject: true },
            { src: `${this.ASSETS_SRC}/main.css`, inject: true },
        ];

        (<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-jwt'] =
            `${this.APP_BASE}node_modules/angular2-jwt/angular2-jwt`;
    }
}
`
normalize.css is npm dependecy. 

normalize.css is not being included in the dev build.

**Comment by d3viant0ne** [comment]
`
constructor() {
    super();
    this.APP_TITLE = 'Perkd';
    let additional_deps: InjectableDependency[] = [
        // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
        // {src: 'lodash/lodash.min.js', inject: 'libs'},
        { src: 'foundation/js/vendor/jquery.js', inject: 'libs' },
        { src: 'foundation/js/vendor/custom.modernizr.js', inject: 'libs' },
        { src: 'foundation/js/foundation/foundation.js', inject: 'libs' },
        { src: 'normalize.css/normalize.css', inject: true },
        { src: `${this.ASSETS_SRC}/css/foundation.css`, inject: true },
    ];

    const seedDependencies = this.NPM_DEPENDENCIES;

    this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);

    this.APP_ASSETS = [
        { src: `${this.ASSETS_SRC}/main.css`, inject: true }
    ];

    (<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-jwt'] =
        `${this.APP_BASE}node_modules/angular2-jwt/angular2-jwt`;
}
`

**Comment by d3viant0ne** [comment]
I'm on my phone, I'll have to tinker with it when I get home to give you an exact answer

**Comment by sfabriece** [comment]
Thanks :)
