### ISSUE TITLE
Possible wiki bug for SASS external dependencies

### ISSUE THREAD

**Issue by simonh1000** [mgechev/angular2-seed#653]
I'm struggling to get bootstrap into my production builds together with SASS. When I compare the seed code with the wiki, I think this line needs to be changed. 

However, this change alone does not seem to be enough to get SASS working. I'll make the edit after I get some validation here.

```
function getExternalScss() {
    -- return APP_ASSETS.filter(d => /\.scss$/.test(d.src));
    ++ return getEnvDependencies().filter(d => /\.scss$/.test(d.src));
}
```

**Comment by mgechev** [comment]
You can use `DEPENDENCIES`, it merges both the npm dependencies and your app assets.
