### ISSUE TITLE
beta.11 - Cannot read property 'zone' of undefined

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#658]
```
angular2-polyfills.js?1458434653551:142 Uncaught TypeError: Cannot read property 'zone' of undefined
```

https://github.com/angular/angular/issues/7652
https://github.com/angular/angular/issues/7666

**Comment by NathanWalker** [comment]
On latest master now.

**Comment by d3viant0ne** [comment]
![screen shot 2016-03-19 at 9 15 40 pm](https://cloud.githubusercontent.com/assets/8420490/13902473/c3bb9ca6-ee17-11e5-9207-ff9e5236cc1d.png)

**Comment by drew-moore** [comment]
+1, same here. Looks like a browser-sync-related bug that came up with beta-10: https://github.com/angular/angular/issues/7652

**Comment by drew-moore** [comment]
@d3viant0ne - this is happening for me after deleting my typings folder

**Comment by drew-moore** [comment]
Ah sorry, just realized @NathanWalker noted that issue in the original post. 

In any case, reverting to beta-9, leaving all other changes #656 intact, seems to work fine.

**Comment by fourctv** [comment]
+1 back to beta-9 for now

**Comment by mgechev** [comment]
We're back to beta.9.
