### ISSUE TITLE
Update Angular2

### ISSUE THREAD

**Issue by be-codified** [mgechev/angular2-seed#659]
This is probably a begginer question but how can I update angular2 to latest version?

**Comment by mgechev** [comment]
The seed is already updated to Angular 2 beta.11, you can use [this tag](https://github.com/mgechev/angular2-seed/tree/2.0.0-beta.11). However, there's upstream zone.js issue https://github.com/angular/angular/issues/7652, so better stick to beta.9 until beta.12 is out with new version of zone.js.

**Comment by be-codified** [comment]
Should I just change version of Angular2 in package.json and run `npm install`? Or this will break something?

**Comment by mgechev** [comment]
@be-codified yes, you can. If you update angular 2 and its corresponding `peerDependencies` everything should work.

**Comment by be-codified** [comment]
@mgechev thank you for your reply. Can you explain what are `peerDependencies`, I am kind of new in updating things.

**Comment by jesperronn** [comment]
As I read https://github.com/angular/angular/issues/7652#issuecomment-198909889
it should work, but with an error in the console. Just FYI, my app (based on this seed) is working.

However, though, this seed and my app have drifted apart, so I am basing my code on an older version of this seed.
