### ISSUE TITLE
Exit status 3221225501

### ISSUE THREAD

**Issue by GeTaj** [mgechev/angular2-seed#663]
npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Geta.Zhu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.8.2
3 info using node@v4.3.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@0.0.0~prestart: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@0.0.0~start: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~start: PATH: C:\Users\Geta.Zhu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\work\angular2-seed\node_modules\.bin;C:\Program Files\nodejs;%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Geta.Zhu\AppData\Roaming\npm;C:\Users\Geta.Zhu\AppData\Local\Programs\Git\bin
10 verbose lifecycle angular2-seed@0.0.0~start: CWD: E:\work\angular2-seed
11 silly lifecycle angular2-seed@0.0.0~start: Args: [ '/d /s /c', 'gulp serve.dev' ]
12 silly lifecycle angular2-seed@0.0.0~start: Returned: code: 3221225501  signal: null
13 info lifecycle angular2-seed@0.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve.dev`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Geta.Zhu\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Geta.Zhu\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd E:\work\angular2-seed
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Geta.Zhu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.3.2
20 error npm  v3.8.2
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 start: `gulp serve.dev`
22 error Exit status 3221225501
23 error Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve.dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by d3viant0ne** [comment]
Current master works fine on Node 4 LTS / Windows 10
