### ISSUE TITLE
Can not find Observable.of

### ISSUE THREAD

**Issue by nathasm** [mgechev/angular2-seed#664]
Using latest node (5.6.X) with Chrome, I use `Observable.of` in one part of my code. The JS error console suggests that I submit an issue.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:96 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/rxjs/add/observable/of.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ localhost/:96
```

**Comment by NathanWalker** [comment]
Add this along with your other imports:
```
import {Observable} from 'rxjs/Observable';
```

**Comment by NathanWalker** [comment]
If you still encounter issue, please provide link to Github repo with line number causing issue or provide your code inline here.

**Comment by nathasm** [comment]
Modified `app.component.ts`

```
import {Observable} from 'rxjs/Observable';
import {Component} from 'angular2/core';
import {ROUTER_DIRECTIVES, RouteConfig} from 'angular2/router';
import {NavbarComponent} from './navbar.component';
import {ToolbarComponent} from './toolbar.component';
import {HomeComponent} from '../../home/components/home.component';
import {AboutComponent} from '../../about/components/about.component';
import {NameListService} from '../../shared/services/name-list.service';

@Component({
  selector: 'sd-app',
  viewProviders: [NameListService],
  moduleId: module.id,
  templateUrl: './app.component.html',
  directives: [ROUTER_DIRECTIVES, NavbarComponent, ToolbarComponent]
})
@RouteConfig([
  { path: '/',      name: 'Home',  component: HomeComponent  },
  { path: '/about', name: 'About', component: AboutComponent }
])
export class AppComponent {
  constructor() {
    Observable.of(1,2,3);
  }
}
```

![screen shot 2016-03-21 at 8 19 23 pm](https://cloud.githubusercontent.com/assets/410832/13938271/812f4d7e-efa2-11e5-8700-a87544ce160d.png)

**Comment by NathanWalker** [comment]
I'll take a look later. Last time I checked, 'of' worked fine with only importing Observable.

**Comment by d3viant0ne** [comment]
Go look at what is being imported.

Lines 11271 - 11374 of Rx.js - there is no require for "rxjs/add/operator/of"

**Comment by nathasm** [comment]
Correct, but adding `import 'rxjs/add/operator/of'` yields the error from my original post...I'm wondering do I need to add a mapping in systemJS somewhere so it can find the rest of the operators?

**Comment by d3viant0ne** [comment]
No. Update to beta 3, the require statement is back in the Rx.js bundle

**Comment by d3viant0ne** [comment]
I'll bump the version in the seed when I get home

**Comment by mgechev** [comment]
@nathasm the seed uses angular2 beta.9 (because of the zones issue), which depends on older version of rxjs.

Once the core team release beta.12 we'll update both rx and the angular version itself.

**Comment by amannguptaggg** [comment]
**instead of using in Angular v6 or v6+:**
`import {of } from 'rxjs';`

**Use**
`import {of as useOf } from 'rxjs';`

and implement as:

`getBooks():Observable<Book[]>{
    return useOf(this.BOOKS);
  }`
