### ISSUE TITLE
chore(deps): update to rxjs 5 beta.3

### ISSUE THREAD

**Issue by d3viant0ne** [mgechev/angular2-seed#665]
Per the discussion in #664, Beta.2 is missing observable.of which would be moderately annoying if you actually wanted to use the Rx package.

Bumping the Rx version to beta 3 doesn't appear to have any Angular2 side effects outside of much faster build times and less memory consumption

**Comment by mgechev** [comment]
This is part of the beta.10 and beta.11 branches, and will be part of beta.12 once released.
