### ISSUE TITLE
Running multiple instances at once (npm start)

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#668]
Correct me if I am doing something wrong, but it looks like the current setup doesn't allow for a user to run multiple instances of the seed at once using **npm start**  When I do it, I get this error:  
Finished 'serve.dev' after 31 s
Error: listen EADDRINUSE :::5555
Obviously the reason is because I already have an instance running on this port.  I have seen other examples solve this by incrementing the port if the one it wants to use is already being used.  So the next time I run npm start it should go for 5556.

Here is the use case:  
I am working on multiple projects at the same time that are using the seeder.  Instead of stopping and running each one, it would be easier/faster to just being able to run them at same time.

**Comment by mgechev** [comment]
What you can make is:

```
npm start -- --port 5556
```
