### ISSUE TITLE
Install tds typings in an npm post install script

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#67]
Don't you think we should remove the `tds_typing` folder from repo and get the `*.d.ts` files installed in an mpm post install script (in the same fashion as [#59](https://github.com/mgechev/angular2-seed/issues/59)) ?

**Comment by aboeglin** [comment]
That's what I had in mind when I proposed #59.

**Comment by ludohenin** [comment]
OK, so to make sure we're on the same track. That would cover installing tds typings + copying ng2 ones from `node_modules/angular2/bundles/typings/angular2` ?

**Comment by aboeglin** [comment]
The typings for ng2 from definitelytyped should be up to date, at least they have been updated 11 hours ago here : https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2. So do we need to copy them from the npm package ?

**Comment by ludohenin** [comment]
Unfortunately it does not include `http.d.ts` but maybe we can live without it.

**Comment by mgechev** [comment]
I think it is better to use `node_modules/angular2/bundles/typings/angular2`. If we depend n `DefinitelyTyped` we may have mismatch between versions.

**Comment by mgechev** [comment]
How about this? https://github.com/mgechev/angular2-seed/commit/f3e23f5533aa9e77cd87caf1e3a605aa80aaf42c#diff-b9e12334e9eafd8341a6107dd98510c9R258

**Comment by aboeglin** [comment]
Good, like that we can easily change the path in case bundles is moved or renamed in future releases, so now we need to delete the tsd_typings from the remote and add the postinstall call to tsd.

**Comment by ludohenin** [comment]
@mgechev perfect. Just `http` is missing as referred in #62

**Comment by ludohenin** [comment]
@mgechev `tsd` can be invoke using `gulp-shell` plugin.

**Comment by mgechev** [comment]
Yep, sounds good.
