### ISSUE TITLE
State shared across network :O (amazing but weird)

### ISSUE THREAD

**Issue by Sn3b** [mgechev/angular2-seed#670]
I'm still in the process of familiarising myself with the seed and I notice something I really do not understand. When I run the seed and view it from multiple computers (or phone) on the network, state seems to be shared :/

Whatever I type in the textbox to add a new scientist, automatically appears in the same textbox on other computers (or phone!!).

What is it that triggers this behaviour?

Also, when I hit the "Add" button it simply refreshes the page on the other computers.

Thanks :)

**Comment by mgechev** [comment]
Yes, this is thanks to BrowserSync. It doesn't work well yet because there's no proper integration of zone.js with browsersync but we're working on it here https://github.com/BrowserSync/browser-sync-client/issues/32.

**Comment by Sn3b** [comment]
I see, how can I disable it?

**Comment by mgechev** [comment]
Here's the API doc of browsersync https://www.browsersync.io/docs/options/

**Comment by Sn3b** [comment]
Thanks! :)

**Comment by mgechev** [comment]
Your configuration change [should be somewhere here](https://github.com/mgechev/angular2-seed/blob/master/tools/utils/seed/code_change_tools.ts#L16-L25).

**Comment by Sn3b** [comment]
Yes that's what I was looking at, thanks again :)
