### ISSUE TITLE
Integrating outside TypeScript library

### ISSUE THREAD

**Issue by jgenchik** [mgechev/angular2-seed#680]
This is probably more of a question then a bug, but I think other's will want to know how to do this right.I am trying to integrate ng2-charts into the application based on this seed. I have to install ng2-charts from the github (latest version) because of the @View directive (`"ng2-charts": "github:valor-software/ng2-charts"`). The problem is that github repository does not contain any JavaScripr, only TypeScript.
I tried to solve that by modifying project.config.ts file like so:
```
(<any>this.SYSTEM_CONFIG_DEV.paths)['ng2-charts'] =
        `${this.APP_BASE}node_modules/ng2-charts`;
    (<any>this.SYSTEM_CONFIG_DEV.packages)['ng2-charts'] = { 'defaultExtension': false };
```
but this did not help.
Any suggestions on how to integrate an outside TS lib?

**Comment by d3viant0ne** [comment]
npm install --save ng2-charts

In your project.config.js

```
    let additional_deps: InjectableDependency[] = [
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
     {src: 'ng2-charts/ng2-charts.js', inject: 'libs'}
    ];
```

**Comment by jgenchik** [comment]
Thank you. But, like I said in my original post, there is no .js. If I get ng2-charts from their github repo, it only contains a **.ts** I attempted to `tsc ng2-charts.ts`  but that did not work. Any ideas how I can use the **.ts** instead of **.js**?

**Comment by d3viant0ne** [comment]
I loaded it in my dev environment, there is a .js bundle and the name is listed above.

<img width="329" alt="screen shot 2016-03-24 at 3 05 27 pm" src="https://cloud.githubusercontent.com/assets/8420490/14029744/e6df6e2a-f1d1-11e5-9b79-6ee727da38c6.png">

**Comment by lukazadel** [comment]
Did you get the charts to work ? in my case, whatever i do nothing gets them running...
