### ISSUE TITLE
Best path to upgrading angular2-seed?

### ISSUE THREAD

**Issue by jayhahn** [mgechev/angular2-seed#681]
I'm running on a very early version of angular2-seed based on angular2@2.0.0-beta.0. It looks like a lot has changed since then and I want to upgrade it to at least match beta.9. 

Is there an easy way to do this? Or do I kind of have to individually look at all the files/dependencies that have changed and try to make those changes to my existing beta.0 version of angular2-seed? There doesn't seem to be a changelog to track what got changed/dropped/added.

**Comment by mgechev** [comment]
Hey @jayhahn. Unfortunately updating to the latest seed from this exact version will not be an easy task.

In beta.8 @ludohenin did a major refactoring which makes the update process trivial but it broke the backwards compatibility with previous versions. What I can recommend you to do is to download the latest seed version (or beta.9 instead, take a look at https://github.com/mgechev/angular2-seed/issues/682), and move your application to the `src` directory. If you haven't done any significant changes in the build, the migration should be trivial as well.
