### ISSUE TITLE
chore(update): task for updating the seed to the latest version in master

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#687]
The seed is already modular. Thanks to the changes by @ludohenin we have separation between seed and project:
- `tools`.
- `utils`.
- `config`.

Thanks to this modular structure we can automate the process of update of our projects to the seed's version from master.

## High-level implementation

In the basic implementation we will:
- Clone the latest version of the seed from master to `dist/tmp` with `nodegit`.
- Overwrite all `tools/*/seed` directories with the content from the respective `dist/tmp/tools/*/seed`.

### NPM dependencies

The biggest challenges in front of the seed are how to update seed dependencies if changed. Possible suggestion is to create another `package.json` file inside `tools`, which will contain most of the seed's `devDependencies`. In this case the only `devDependencies`, that need to be left in the root `package.json`, left are `typescript`, `gulp`, `ts-node` (because `ts-node` is required for running `gulpfile.ts`).

### Typings

Because of the same reasons mentioned in the **NPM dependencies** section, we need to allow update of the ambient type definitions used by the seed, in case they change. Here are two possible (*reasonable*) solutions:

- Distribute all the ambient typings on which the seed depends in a bundle, upload them to the seed repo.
- Inside `tools` create `typings.json` file which will allow us to define seed-specific ambient definitions, and declare all other such definitions inside `PROJECT_ROOT/typings.json`.

## Problems

Here are a few possible problems that may/will occur:
- Overcomplicating the seed.
- Duplicate packages between `PROJECT_ROOT/node_modules` and `tools/node_modules`, which may also lead duplicate type definitions. In such case one of the type definitions needs to be added to the `exclude` section inside `tsconfig.json`.

### Duplicate definitions

Duplicate definitions are acceptable unless we meet the following scenario:
- You need type definitions for the package "A" and install them in `PROJECT_ROOT/typings`.
- Later the seed depends on the same package "A" and adds type definitions to "tools/typings".
- You update the seed with, lets say, `npm run seed.update` and get `Duplicate definition` TS error. The easiest possible solution is to use the seed's ambient type definition, but what about they are for packages with different versions?

## Conclusion

Does it worth it to implement such functionality or it is going to make the seed more complicated? Breaking simplicity is definitely a deal-breaker for such feature.

**Comment by e-oz** [comment]
I like the idea of update by gulp task, but possible conflict of dependencies looks serious - when problems are predictable even before implementation, in the process of implementation they will be unavoidable. If upgrade of app's deps will be able to breake build tasks, then it will happen very soon.

**Comment by mgechev** [comment]
[Here are the results of the poll](https://twitter.com/mgechev/status/713367770952560640).

I'm not sure if an `update` task will provide enough value given all the edge cases.
