### ISSUE TITLE
Add --color to Gulp tasks?

### ISSUE THREAD

**Issue by brian428** [mgechev/angular2-seed#688]
I'm not sure if this would cause any problems, but I was wondering if you'd consider adding the --color flag to the Gulp tasks called from the npm scripts?

E.g. instead of this:
"build.dev.watch": "gulp build.dev.watch",

It would be:
"build.dev.watch": "gulp build.dev.watch --color",

This way, you always see the color-formatted output. In my experience, without this, you don't see colors in the console output when running the command from within something like IntelliJ IDEA.

Obviously, this is minor. But if you don't think it would cause problems, it might be nice to include?

**Comment by mgechev** [comment]
There will be no collisions with existing flags. Do you want to open a PR with that change?

**Comment by brian428** [comment]
Sure, I'll try to do that today.

**Comment by mgechev** [comment]
@brian428 I added a wiki [page here](https://github.com/mgechev/angular2-seed/wiki/FAQ). Feel free to modify it if it doesn't sound good to you.
