### ISSUE TITLE
watch task not working in Vagrant shared folder

### ISSUE THREAD

**Issue by bogdanbrudiu** [mgechev/angular2-seed#691]
In my env watch is not working. I have an ubuntu image running inside virtualbox deployed using vagrant on window 7.

The working folder is the shared /vagrant folder (shared from windows to /vagrant in the ubuntu vm).
Using this configuration brings some weird things like having to run npm install with --no-bin-links

In this configuration to make watch available tools/utils/seed/watch.ts file needs to be changed by adding **usePooling : true** opts

 `plugins.watch(join(APP_SRC, '**'), {usePolling: true}, (e:any) =>`

It took me some time to figure this out... maybe it needs to be added as new config option?

**Comment by mgechev** [comment]
@bogdanbrudiu it is a good idea to create a FAQ page in the wiki and include this information there.

In general, I don't think it is a good idea to use polling by default.
