### ISSUE TITLE
Help serving prod with nginx

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#692]
I'm new with nginx. 

I'm trying to serve the production files with nginx with the following configuration.
```
server {  
        listen 3000;
        index index.html;
        server_name localhost;
        root G:/www/;

        location / {
           try_files $uri$args $uri$args/ $uri/ /index.html =404;
        }
    }
```
The files are being loaded as html instead of their respective types.
![nginx_not_working](https://cloud.githubusercontent.com/assets/3108592/14063257/afb61198-f3c9-11e5-8080-0c543b302221.png)

This problem only occurs with nginx.
Any help with this is appreciated.

**Comment by mgechev** [comment]
Here is how to use nginx with `pushState` API https://stackoverflow.com/questions/9184959/rewriting-nginx-for-pushstate-urls.
