### ISSUE TITLE
Nested HTML5 paths don't work in production due to relative path of js injections

### ISSUE THREAD

**Issue by jayhahn** [mgechev/angular2-seed#694]
I'm using beta.9 version of angular2-seed. 

When I do a prod build, the js injections look like this

 ```
<script src="js/shims.js?1459198619395"></script>
<script src="js/app.js?1459198619396"></script>
```

I'm using html5 paths (not the hash /#/ based routes). 

It works fine for root path (/) and one level nested routes (/example) because it will load those files fine. If I go 2 levels deep (/example/path) then it won't work because it tries to load /example/js/shims.js (which doesn't exist) since the JS path is relative. These injections need to be absolute for html5 path based routing (which seems to be the default in beta.9 of angular2-seed).

**Comment by mgechev** [comment]
@jayhahn thanks for the report! It should be fine now.

**Comment by jayhahn** [comment]
@mgechev nice, that change is what I did in my code as well. Thanks!

**Comment by mgechev** [comment]
@jayhahn there's further change which should be made. I'll update master in a sec.

**Comment by mgechev** [comment]
@jayhahn a better way to approach https://github.com/mgechev/angular2-seed/commit/4384552443a4366f0a832ac0486beaf4f1589d3f.
