### ISSUE TITLE
Tests - double or even triple run on spec save

### ISSUE THREAD

**Issue by red010b37** [mgechev/angular2-seed#696]
I am doing TDD with the following setup

Debug - In two different shell windows
npm run build.test.watch # 1st window
npm run karma.start # 2nd window

Then I edit/create a spec file and save, I then get a karma double or tripple run

Firstly as the dist folder rebuilds then the watcher fires a karma runs which gives 
SUMMARY:
✔ 0 tests completed

Make perfect sense as there is nothing in dist as everything was removed.

Then as dist builds it runs the tests again which is fine
SUMMARY:
✔ 6 tests completed
ℹ 68 tests skipped

It all works but is there a way to make it that the karma run only triggers once the dist build complete -or something like that?

**Comment by ludohenin** [comment]
@red010b37 in karma.conf, you can increase `autoWatchBatchDelay`
