### ISSUE TITLE
build.prod task failing after adding external dependency 

### ISSUE THREAD

**Issue by pinalbhatt** [mgechev/angular2-seed#697]
I Added dependencies to firebase and angularfire2 using https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

Added following to project.config.ts

 (<any>this.SYSTEM_CONFIG_DEV.paths)['firebase'] =
      `${this.APP_BASE}node_modules/firebase/lib/firebase-web`;
    (<any>this.SYSTEM_CONFIG_DEV.paths)['angularfire2'] =
      `${this.APP_BASE}node_modules/angularfire2/angularfire2`;

Added firebase to typings.json

And added code to work with angularfire2. dev build is running fine but when i try to build for prod  ( npm run build.prod) i get following error

[21:17:47] Starting 'build.bundles.app'...
Unhandled rejection Error on fetch for firebase.js at file:///Users/User1/Proj1/node_modules/firebase.js
        Loading angularfire2/angularfire2.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open '/Users/User1/Proj1/node_modules/firebase.js'
    at Error (native)

**Comment by dominik-beste** [comment]
How are you importing firebase in your component?

I added *ng2-file-upload* to a project I was working and followed the instructions in the wiki. At first during development it worked, but during production it didn't. From following the tutorial, I imported ng2-file-upload as:
```
import {FILE_UPLOAD_DIRECTIVES, FileUploader} from 'ng2-file-upload';
```
and it worked during development. With the following change, it works in development and production:
```
import {FILE_UPLOAD_DIRECTIVES, FileUploader} from 'ng2-file-upload/ng2-file-upload';
```
I think this line tells it to look for the module under (...)/node_modules/ng2-file-upload/ng2-file-upload.js, check where firebase.js is located and change accordingly.

**Comment by mgechev** [comment]
@dominik-beste thanks for the assistance!

@pinalbhatt follow back if you have any issues.

**Comment by pinalbhatt** [comment]
@dominik-beste  @mgechev  this does not seem to be working.

Tried with both
 import {FIREBASE_PROVIDERS, defaultFirebase, AngularFire} from "angularfire2/angularfire2"; 
and
import {FIREBASE_PROVIDERS, defaultFirebase, AngularFire} from "angularfire2";

Problem is with firebase.js . My code does not have any direct access to actual firebase js . AngularFire2 may be referring  it. Not sure its angularfire2 issue or angular2-seed.  

Posting this issue over here as dev build is working fine. issue is only with prod build.

**Comment by pinalbhatt** [comment]
asking  @jeffbcross if he has any idea as he is involved with both angularfire2 and this project.

**Comment by mgechev** [comment]
@pinalbhatt I'll investigate the issue today and follow back in a few hours.

**Comment by mgechev** [comment]
@pinalbhatt here's how you can use angularfire2: https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2.

**Comment by pinalbhatt** [comment]
Thanks a lot @mgechev

**Comment by Geoide** [comment]
I have the same error in production with lodash. It works fine in dev mode. If I add 
```'lodash': 'node_modules/lodash/lodash.min.js',```
in SYSTEM_BUILDER_CONFIG, then it seems works.

**Comment by AshMcConnell** [comment]
@Geoide The SYSTEM_BUILDER_CONFIG doesn't look like that any more.  I am having trouble with lodash in production, do you have an updated config you could share?


I tried: -
```
'lodash': {
                main: 'lodash.js',
                defaultExtension: 'js'
            }
```

**Comment by karlhaas** [comment]
I think you don't need any special config for the builder. Do you have `'node_modules/*': 'node_modules/*',` in SYSTEM_BUILDER_CONFIG.paths?

**Comment by AshMcConnell** [comment]
I had /node_modules/**/package.json.  I have it working, but I'm don't fully understand why it works.  What config do you have to add lodash?  Does it depend on how I import.  I am currently using: - import * as _ from 'lodash';

Everything was working fine in Dev mode, but prod mode needed a lot more config.  I have my extra dependencies in SYSTEM_BUILDER_CONFIG,packages, it builds, but when running the server I get a problem with ng2-bootstrap (where it says System.registerDynamic is not a function).

I'm trying to understand how it all hangs together, it is working fine in Dev mode, I didn't think there would be much more effort needed for prod.  I'm trying to figure out where I've gone wrong

**Comment by karlhaas** [comment]
We only added lodash to tsconfig types array. It works without any import. We just use it like `_.get...`.
In our project there is no special builder configuration for prod mode. The above mentioned line seems to be needed so that system js builder can fetch and use the package.json files in node_modules. Then it can automatically look up the main file of each package and resolve the module content. I think you have to add packages which don't have a main entry in package.json.

My seed config is identical to current version in master.
