### ISSUE TITLE
Build takes very long time after seed upgrade

### ISSUE THREAD

**Issue by Toktik** [mgechev/angular2-seed#699]
After upgrading angular2-seed for my project, I get very slow `npm install` and builds.

```
[06:36:46] Requiring external module ts-node/register
[06:37:23] Loading tasks folder C:\project\client\tools\tasks\seed
```

It takes around 40 seconds between those steps if you look at the time diff.

It fixes when I downgrade `ts-node` dependency from 0.7.1 to 0.5.5.

I don't see anything suspicious in my setup.
Either it is `ts-node` itself or the way we use it. Any idea?

**Comment by mgechev** [comment]
It could be `ts-node`. At this point we don't want to give up static typing so there is nothing much that we can do.

Here's proposal for `ts-node` 1.0 which will bring a lot of performance improvements https://github.com/TypeStrong/ts-node/issues/44.
