### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by alvipeo** [mgechev/angular2-seed#701]
I really like angular2 but the build ecosystem....

My project got bigger and now can't compile at all:

> > angular2-seed@0.0.0 start d:\Documents\Visual Studio 2015\Projects\angular2-seed
> gulp serve.dev --color

[15:37:39] Requiring external module ts-node/register

<--- Last few GCs --->

   88896 ms: Mark-sweep 1367.7 (1456.9) -> 1371.7 (1456.9) MB, 1202.7 / 0 ms [allocation failure] [GC in old space requested].
   90091 ms: Mark-sweep 1371.7 (1456.9) -> 1371.8 (1456.9) MB, 1194.5 / 0 ms [allocation failure] [GC in old space requested].
   91303 ms: Mark-sweep 1371.8 (1456.9) -> 1365.6 (1456.9) MB, 1211.8 / 0 ms [last resort gc].
   92515 ms: Mark-sweep 1365.6 (1456.9) -> 1367.3 (1456.9) MB, 1212.0 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003547C9E3AD1 <JS Object>
    1: getUnionType(aka getUnionType) [d:\Documents\Visual Studio 2015\Projects\angular2-seed\node_modules\typescript\lib\typescript.js:~19010] [pc=000001512CA74A21] (this=000003547C904189 <undefined>,types=0000000CF82CB009 <JS Array[5]>,noSubtypeReduction=000003547C904231 <true>)
    2: instantiateType(aka instantiateType) [d:\Documents\Visual Studio 2015\Projects\angular2-seed\node_modules\...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

typescript 1.8.9

**Comment by mgechev** [comment]
@alvipeo do you get this error each time you compile your project or only after angular2-seed has  incrementally built on change for given amount of time?

**Comment by mgechev** [comment]
@alvipeo I found two similar issues in the TypeScript's issue tracker. May be you can post the issue there as well, if it is caused by the incremental compilation and some memory leaks there, I don't think we can do much in the seed.

**Comment by alvipeo** [comment]
I just restarted my machine and tried to compile - crashed. So it's not incremental. I actually had this issue with https://github.com/angularClass/angular2-webpack-starter but @gdi2290 changed something and it started to work. So he knows better about the cause I think.

Your seed is cleaner now but no go with my project :(

Also, could you answer my qtn regarding loosing zone? I sent you a pm yesterday. Rob Wormald was **really** helpful localizing this issue but when I showed him exactly the place where zone is lost he said "interesting". so I'm stuck with it..

**Comment by mgechev** [comment]
That is the issue I guess https://github.com/AngularClass/angular2-webpack-starter/issues/372.

Tomorrow/during the weekend I'll do some profiling and let you know what I find.

**Comment by alvipeo** [comment]
thank you!

**Comment by gdi2290** [comment]
update to rxjs beta4 and you should be fine (ignore the warning)

**Comment by alvipeo** [comment]
Thanks! That worked!
