### ISSUE TITLE
npm run docs includes node_modules but it shouldn't

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#708]
I just downloaded the latest version of the seed and ran npm install and npm run docs on it.  When the docs opened up, for some reason it was including all of node_modules files as well.  Can this please be updated to be only the project src?

**Comment by mgechev** [comment]
The `node_modules` doc is in the `external` section. However, if you want to exclude external modules completely, you can uncomment [this line](https://github.com/mgechev/angular2-seed/commit/0e5614341f950bc95209c9f19df80dc2345acf46#diff-82947a6521f20d4e0e59590132a0aaa9R22).
