### ISSUE TITLE
ENOENT ___jb_tmp____

### ISSUE THREAD

**Issue by c-muresan** [mgechev/angular2-seed#717]
I get the following after editing files.

Error: ENOENT: no such file or directory, stat 'C:\WebstormProjects\project\src\app\portfolios\components\all.bonds\all.bonds.ts___jb_tmp___'
    at Error (native)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_mo                                                                                                         dules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! project@0.0.1 start: `gulp serve.dev`

**Comment by d3viant0ne** [comment]
That's an incorrect import or something borked in your Systemjs config. Either way, there is no way to figure out what is incorrectly configured without being able to see the repo.

**Comment by c-muresan** [comment]
It was and WebStorm error, it creates a temporary file for safe writing. There are a lot of WebStorm users, I think you should ignore this files

**Comment by dspies** [comment]
For anyone hitting this error and using IntelliJ, turn off "safe write" in 
Settings > System Settings > Use "safe write" (save changes to a temporary file first)

**Comment by d3viant0ne** [comment]
@dspies - Good little tidbit for the Wiki :)
