### ISSUE TITLE
project + seed config.ts never refresh

### ISSUE THREAD

**Issue by OlivierMary** [mgechev/angular2-seed#718]
Hi,

**Steps to reproduce and a minimal demo of the problem**

Change `./tools/config/project.config.ts` or `./tools/config/project.config.ts` and change `APP_TITLE`

`npm start`

**Current behavior**

Title still "My Angular2 App".

**Expected/desired behavior**

Title + other config set with the new value.

**Other information**

Workaround : 
```bash
rm tools/config/*.js
rm tools/config/*.map
tsc --project tsconfig.json
npm start
```

Without `tsc --project tsconfig.json` I get this error :

```bash
> gulp serve.dev --color

module.js:341
    throw err;
    ^

Error: Cannot find module './config/project.config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

```

Regards.

**Comment by mgechev** [comment]
Yes, the config will not change if you have previously compiled js files. Note that precompiling gulp related files is only required for speeding up the build on windows.

**Comment by OlivierMary** [comment]
Ok, it's same for all ts in the project ?

Why I get this error if I dont precompil js files ? 

```bash
> gulp serve.dev --color

module.js:341
    throw err;
    ^

Error: Cannot find module './config/project.config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

I got it only on windows...

**Comment by OlivierMary** [comment]
@mgechev  any idea ?
