### ISSUE TITLE
Visual Studio Code shows errors

### ISSUE THREAD

**Issue by ghost** [mgechev/angular2-seed#719]
Hello,
**Steps to reproduce and a minimal demo of the problem**

Just clone current repo:
`git clone --depth 1 https://github.com/mgechev/angular2-seed.git`
`cd angular2-seed`
`npm install`

_What steps should we try in your demo to see the problem?_

Open `angular2-seed` folder in Visual Studio Code.

**Current behavior**

All decorated with @Component markup classes shows error (or warning, but VS Code shows it as error):

> Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

(it ignores tsconfig.json: `"experimentalDecorators": true,`)

Same with @Input() and @Output decorators (and probably all others).
Also:

`moduleId: module.id` shows 

> Cannot find name 'module'.

**Expected/desired behavior**

VS Code shouldn't show any errors (like in projects created from scratch by hand - `npm init` and so on, but without 99% of this seed's magic).

**Other information**

It compiles and run just fine (`npm start`), same `npm run build.prod`. It's just awful at development stage.

**Comment by mgechev** [comment]
Should be fixed by adding another tsconfig.json inside app. I'll do that tomorrow.

**Comment by mc100s** [comment]
I have exactly the same problem as _ghost_ but I'm using Sublime Text.

**Comment by gkonings** [comment]
Same problem as ghost here. VSCode on OSX.

**Comment by mgechev** [comment]
What version of VSCode are you using? For me:

VSCode Version 1.5.3 (1.5.3) with the latest TypeScript plugin works like a charm for me (I recently updated the TypeScript plugin and it helped resolving some issues).

**Comment by gkonings** [comment]
Same version of  VSCode for me. Which typescript plugin are you referring too?

**Comment by mgechev** [comment]
Actually I don't have any TypeScript plugin installed, but I have installed TypeScript 2.0.3 globally.

**Comment by gkonings** [comment]
You gave me a good hint there. I updated my global installed typescript to 2.0.3. Then I had a mismatch with my VSCode settings and my global installed tsc compiler, So I added the following line to my settings.json
`"typescript.tsdk": "node_modules/typescript/lib",`

Now it works like a charm :)
