### ISSUE TITLE
Running tests in windows only runs once

### ISSUE THREAD

**Issue by red010b37** [mgechev/angular2-seed#720]
When I run the following on windows - latest seed, fresh pull and npm i
```
# Debug - In two different shell windows
npm run build.test.watch      # 1st window
npm run karma.start           # 2nd window
```

The first run it works correctly
```
SUMMARY:
√ 8 tests completed
```

Then when I change any (spec or js) file the karma says it has removed files 
```
06 04 2016 12:10:38.311:INFO [watcher]: Removed file  "C:/xxxxxx/xxxxxx/xxxx"
```

Karma then runs and with and no tests execute
```
SUMMARY:
√ 0 tests completed
```

And when I change another file and run karma never runs again - game over :(.

I thought I might be the build time so I added a 20 sec batch delay - overkill but just wanted to see if it was that
```
autoWatchBatchDelay: 20000,
```
But did not fix it.

I think when the test watcher removes and rebuilds the files karma does not register them in the project anymore.

Any suggestions?

**Comment by red010b37** [comment]
Ok its the clean causing the issues, commenting out makes karma run correctly 

```
gulp.task('build.test', (done: any) =>
  runSequence(//'clean.dev',
              'tslint',
              'build.assets.dev',
              'build.js.test',
              'build.index.dev',
              done));
```

**Comment by mgechev** [comment]
@red010b37 the issue with removing `clean.dev` will be that removed tests from `src` will be still runnable.

**Comment by red010b37** [comment]
yea this is the issue im having now. but karma just is totally not happy with the dist clean, it reginises all the files where removed then never seems to watch new one that were added back. 

Really makes tdd hard

**Comment by benpriebe** [comment]
The easy solution is to clean out the /dist/dev directory while keeping the top-level /dist/dev intact.

There doesn't appear to be an easy way to delete all files/foldes in a directory using rimraf so you have to read the file system and delete accordingly.

![image](https://cloud.githubusercontent.com/assets/1300551/14516678/e0c40ece-0248-11e6-893b-2ad8bcec61db.png)

**Comment by mgechev** [comment]
@benpriebe thanks for the comment!

@red010b37 does this work for you? If it does, it'll be awesome if @benpriebe can open a PR with that change!

**Comment by red010b37** [comment]
@benpriebe, @mgechev 

Sorry I have been away - yea that works. karma runs 2-3 times but it doesnt break now - Thanks @benpriebe for the answer :D

**Comment by vip32** [comment]
this is also [bugging](https://github.com/mgechev/angular2-seed/wiki/continuous-unit-testing) me

**Comment by stiasta** [comment]
Has this bug been fixed in the prod build?
I downloaded the seed a couple of days ago and got this exact bug.
