### ISSUE TITLE
"src" in "exclude" in tsconfig.json disables TypeScript settings in Sublime editor

### ISSUE THREAD

**Issue by htdt** [mgechev/angular2-seed#722]
Sublime Text editor (build 3103) with [Typescript plugin (0.1.12)](https://github.com/Microsoft/TypeScript-Sublime-Plugin) doesn't apply `tsconfig.json` settings for `.ts` files from `src` folder.
Due to this, the editor highlights wrong errors. For example,
> Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.

If `src` is removed from `exclude` in `tsconfig.json`, the editor is working as intended.

**Comment by mgechev** [comment]
This seems like a limitation in Sublime Text's TypeScript plugin and not related to the seed.

As temporal workaround you can remove `src` from `exclude` but generally this config is required for the speed-up workaround for Windows.

**Comment by zachallen** [comment]
It appears that the secondary tsconfig.json file located in src/client messes with Sublime. If you open up one of the e2e scripts (about.component.e2e.ts for example) it doesn't understand what `describe`, `browser`, `element`, etc are. If you delete that tsconfig.json file, it does.

**Comment by d3viant0ne** [comment]
@zachallen - In my experience the support from best to worst === VisualStudio Code / Atom / WebStorm / Vim / Sublime for TypeScript

The support in sublime is lacking to say the least.

**Comment by htdt** [comment]
The editor (tested in Sublime and VS Code) cannot get typings with `tsconfig.json` in `src` (`src\client`) folder. To solve it, create `typings.d.ts` with `/// <reference path="../typings/browser.d.ts" />` in `src` (`src\client`).

**Comment by Sjiep** [comment]
I can confirm that the issue mentioned above by @htdt also is the case in Intellij (Webstorm) and adding the `typings.d.ts` into `src/client` resolves the issue. Any reason why this file should not be part of the seed?
