### ISSUE TITLE
Test command result summaries are not consistent

### ISSUE THREAD

**Issue by dejanpaler** [mgechev/angular2-seed#723]
Running `npm test` outputs:
```
=============================== Coverage summary ===============================
Statements   : 86.11% ( 93/108 )
Branches     : 48.28% ( 70/145 )
Functions    : 100% ( 25/25 )
Lines        : 94.32% ( 83/88 )
================================================================================
```
Running `npm run serve.coverage` outputs
```
100% Statements 48/48
100% Branches 0/0
100% Functions 10/10
100% Lines 37/37
```

Results should be the same.

**Comment by mgechev** [comment]
@NathanWalker would you take a look at this one?

**Comment by OlivierMary** [comment]
Hi,

Coverage on npm test it's the js Coverage,  so more lines / branches...

On serve.coverage it's typescript coverage.

No ?

Le mer. 6 avr. 2016 14:22, Minko Gechev <notifications@github.com> a écrit :

> @NathanWalker <https://github.com/NathanWalker> would you take a look at
> this one?
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/mgechev/angular2-seed/issues/723#issuecomment-206346015>
>
-- 
Olivier.

**Comment by d3viant0ne** [comment]
@OlivierMary - Correct.

The console coverage is based on the transpiled JavaScript, the [serve.coverage command executes](https://github.com/mgechev/angular2-seed/blob/master/package.json#L23) remap-istanbul and the generated coverage is mapped back to the actual TypeScript code.

**Comment by dejanpaler** [comment]
How could I apply remap-istanbul also to the console coverage?

Since both application files and spec files are written in TypeScript then the expected coverage would also be on the actual TypeScript. 
What would be a clear use case for code coverage on transpiled JavaScript given that all sources are written in TypeScript?
