### ISSUE TITLE
how to update to latest copy of seed files?

### ISSUE THREAD

**Issue by pinalbhatt** [mgechev/angular2-seed#731]
I Created project based of angular2-seed about 15 days back. how can i update to latest seed files?

**Comment by gvsdan** [comment]
there was a conversation in #687 @pinalbhatt

**Comment by mgechev** [comment]
@pinalbhatt go to your project and run the following commands:

```
git remote add upstream https://github.com/mgechev/angular2-seed
git pull upstream master
```

After that you need to resolve the merge conflicts (if any) and you're ready to go!

**Comment by vip32** [comment]
this is handy info for the wiki (https://github.com/mgechev/angular2-seed/wiki/FAQ)

**Comment by Sn3b** [comment]
@pinalbhatt have a look at this [seed](https://github.com/NathanWalker/angular2-seed-advanced), it's based on the angular2 seed, but with a few extra features. At the bottom of the page there's a section called "How best to use for your project" that tells you how to do it :)
