### ISSUE TITLE
Protractor CI

### ISSUE THREAD

**Issue by Shyam-Chen** [mgechev/angular2-seed#732]
Protractor + Travis CI + <s>Sauce Labs</s>

**Comment by mgechev** [comment]
At the moment we don't have plans to run the e2e tests in CI, however, if you have some time you're welcome to contribute with that!

**Comment by Shyam-Chen** [comment]
OK, but I need a SAUCE_USERNAME and SAUCE_ACCESS_KEY (open source)

[Like it](https://github.com/angular/protractor/blob/master/.travis.yml#L10)

![default](https://cloud.githubusercontent.com/assets/13535256/14344631/535e050c-fcdb-11e5-8bc4-83c0b9d2c4ff.png)

**Comment by Shyam-Chen** [comment]
#734

**Comment by mgechev** [comment]
@Shyam-Chen any updates here?

**Comment by Shyam-Chen** [comment]
Is still failures 

`Failed: Component returned failure code`

[result](https://travis-ci.org/Shyam-Chen/ng2-test-ci/jobs/123857303)

**Comment by mgechev** [comment]
Here's a related issue. Do you think it can help? https://github.com/angular/protractor/issues/2297

**Comment by Shyam-Chen** [comment]
I don't know, either

I think it's no crash



In my Angular 1 project is successfully executed

**Comment by Shyam-Chen** [comment]
I finished

[result](https://travis-ci.org/Shyam-Chen/Angular2TS-Starter-Kit)

version: rc.1

**Comment by mgechev** [comment]
Awesome job! I see only one e2e test running. Do you know what is causing this?

**Comment by Shyam-Chen** [comment]
That is my simple project.

I'll wait for this merger (#808), and then start working

**Comment by mgechev** [comment]
@Shyam-Chen awesome! Looking forward for it!
