### ISSUE TITLE
Scss support not working

### ISSUE THREAD

**Issue by nitinkumarmishra** [mgechev/angular2-seed#733]
i did all the steps described in https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support but it didn't work. In development mode no terminal error but in production mode 
`ENOENT: no such file or directory, open '/Users/nitin/Sites/projects/angular2-seed/dist/tmp/about/components/about.component.css'`

**Comment by mgechev** [comment]
Most likely the path is wrong. Make sure you've set the correct one (there should be `app` prefix before `about/components`).
