### ISSUE TITLE
Error during compilation when gulp watches for changes

### ISSUE THREAD

**Issue by OskarKaminski** [mgechev/angular2-seed#736]
I run `npm start`
Sometimes when I make a changes, I get an error as below and task is dying.
![image](https://cloud.githubusercontent.com/assets/7963279/14363526/0d4354bc-fd05-11e5-82eb-d27cc6639df8.png)

**Comment by mgechev** [comment]
WebStorm generates these temporary files. What you can do is to ignore them during compilation.
