### ISSUE TITLE
how to create sourcemaps in prod build?

### ISSUE THREAD

**Issue by elijahiuu** [mgechev/angular2-seed#739]
Is there a way to create external sourcemaps for app.js in prod build?

**Comment by Shyam-Chen** [comment]
use sourcemaps debugging is in development

**Comment by mgechev** [comment]
Source maps are not included in the prod build for performance concerns.

As @Shyam-Chen mentioned, you can debug in dev. In case you still want to generate them, you can override [this task](https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.js.prod.ts).
