### ISSUE TITLE
tsc --project error 

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#740]
according to the wiki, running 
```
tsc --project tsconfig.json 
```
is supposed to work.

I'm getting

```
TS5023: Unknown option 'project'
```

**Comment by mgechev** [comment]
What is your typescript version (`tsc -v`)?

**Comment by d3viant0ne** [comment]
also check for a version mismatch

```npm list -g --depth=0```

**Comment by sfabriece** [comment]
tsc -v gives me 1.0.1.0
while globally i get 1.8.9

**Comment by mgechev** [comment]
Try `npm update -g typescript` or instead of `tsc --project tsconfig.json` run `./node_modules/.bin/tsc --project tsconfig.json`.
