### ISSUE TITLE
angular2-logger inclusion causes build.prod to fail

### ISSUE THREAD

**Issue by edud69** [mgechev/angular2-seed#747]
On the latest version master branch, including library _angular2-logger_ causes the build.prod to fail. It fails at task _build.bundles.app_

_package.json:_
"dependencies": {
    "angular2": "2.0.0-beta.14",
    "angular2-jwt": "^0.1.9",
    "angular2-logger": "^0.2.2", // << --- ADDED
    "es6-module-loader": "^0.17.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "~0.19.25",
    "zone.js": "^0.6.6"
  }

_project.config.ts constructor() :_
` 
  (<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-logger'] =
          ``${this.APP_BASE}node_modules/angular2-logger/bundles/angular2-logger``;
`

_main.ts_
`import {Logger} from 'angular2-logger/core';
...
bootstrap(AppComponent, [
   ...
   Logger // <--- ADDED
]);
`

In deb.build, everything works, but when running _npm run build.prod_. I get the following error:
Unhandled rejection Error on fetch for angular2-logger/app/core/level.ts.js at file:///f:/A-PATH/node_modules/angular2-logger/app/core/level.ts.js
        Loading angular2-logger/core.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'f:\A-PATH\Frontend Web\node_modules\angular2-logger\app\core\level.ts.js'
    at Error (native)

**Comment by mgechev** [comment]
The configuration should be as follows:

```ts
(<any>this.SYSTEM_CONFIG_DEV.paths)['angular2-logger/*'] = ${this.APP_BASE}node_modules/angular2-logger/bundles/angular2-logger;
```

**Comment by edud69** [comment]
@mgechev I am still unable to build the prod project.

The _build.bundles.app_ tries to find a file _node_modules\angular2-logger\app\core\level.ts.js_

There is no such file but a file _level.ts_ exists. I am not sure if this is due to the configuration from _tools/config/seed.config.ts_

```
SYSTEM_BUILDER_CONFIG = {
    defaultJSExtensions: true
}
```

**Comment by mgechev** [comment]
In such case you can set `defaultJSExtension` to `false`, just like we do [here](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L125-L128).

**Comment by edud69** [comment]
Thank you very much!
