### ISSUE TITLE
app_base causing issues when serving content statically from a subfolder

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#749]
The current setup works great if you serve the prod content one of the ways:

- Using node with the serve.prod command.

- Running it on a web server statically but the domain has to be at the root level.

However, if you want to serve it by a web server through a subdomain, like so: www.example.com/content/, it will not load the style and js assets from index.html.  This is because it uses the app_base to serve this content which the seed wants you to setup before packaging for prod.  But most of the time the app could be deployed in a bunch of different testing and live locations so there is no way to preset that app base.

So the real question is what is the benefit of having the app base if the app can just load it all by using relative paths?

Here is the solution that I did until there is something better:
**index.html**
Removed following lines:
`<base href="<%= APP_BASE %>">`

**tools/tasks/seed/build.index.prod.ts**
Removed APP_BASE by changing this line:
From this:
`arguments[0] = APP_BASE + path.slice(3, path.length).join(sep) + '?${Date.now()}';`
To this:
`arguments[0] = path.slice(3, path.length).join(sep) + '?${Date.now()}';`

**Comment by mgechev** [comment]
Yes, today I hit the same issue. In a bit I'll come up with a patch.

**Comment by robbatt** [comment]
Having the same problem. Will give your solution a try, thanks!

**Comment by ludohenin** [comment]
What I did for this use case is to add a cli arg `--dest` and config `APP_DEST`. This way I can ship several envs while still packaging for prod. Another good option to have is the `APP_ENV` (build prod but with app dev config for instance).
* example build.stage: `gulp build.prod --env prod --app-env dev --dest stage --base /stage/`

> So the real question is what is the benefit of having the app base if the app can just load it all by using relative paths?

This breaks loading the app from a deep-link when using the router.

**Comment by robbatt** [comment]
@ludohenin this looks nice, just what I need, a little confusing though in terms of naming and the usage of APP_BASE in prod build in general
