### ISSUE TITLE
why use angular bundles in dev instead of just loading from node_modules? 

### ISSUE THREAD

**Issue by njs50** [mgechev/angular2-seed#752]
I might be missing something, but it seems like a bit of additional configuration to be using the angular bundles instead of the same files (from node_modules) used in the production build.

i.e I could delete a bunch of lines from the the config.seed.ts to leave:
```javascript
  NPM_DEPENDENCIES: InjectableDependency[] = [
    { src: 'systemjs/dist/system-polyfills.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'reflect-metadata/Reflect.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'es6-shim/es6-shim.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'systemjs/dist/system.src.js', inject: 'shims', env: ENVIRONMENTS.DEVELOPMENT },
    { src: 'angular2/bundles/angular2-polyfills.js', inject: 'shims' }
  ];

...

  // SystemsJS Configuration.
  protected SYSTEM_CONFIG_DEV = {
    defaultJSExtensions: true,
    packageConfigPaths: [`${this.APP_BASE}node_modules/*/package.json`],
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '*': `${this.APP_BASE}node_modules/*`
    }
  };
```

Am I missing some benefit to using those bundles? I just noticed this because one of our things was using the angular2/animate module (probably a bad idea I know) but that isn't part of any of the angular bundles.

**Comment by ludohenin** [comment]
This is for performance reason, as loading each and every file can be quite long.

**Comment by njs50** [comment]
is performance actually an issue for local development? I can't say I notice any difference without it bundled. What I do notice is the extra config and that now I can't easily use the "experimental" modules that aren't bundled. i.e animation and i18n. Is there any easy way to use them with this setup?

**Comment by mgechev** [comment]
Without bundles the seed loads each individual Angular 2 module with a separate request. This is quite time consuming given the livereload functionality.

The "experimental" modules could be used with some additional SystemJS configuration.
