### ISSUE TITLE
Loading local files, with require(), adds .js extension to path

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#754]
I need to load a local environment file tha has all of my api urls.  I tried doing the following:
**Loading the file:**
```javascript
let resource = require('resource')
```
**Changes made to system_config_dev:**
```javascript
 protected SYSTEM_CONFIG_DEV = {
    defaultJSExtensions: true,
    paths: {
      [this.BOOTSTRAP_MODULE]: '${this.APP_BASE}${this.BOOTSTRAP_MODULE}',
      'angular2/*': '${this.APP_BASE}angular2/*',
      'rxjs/*': '${this.APP_BASE}rxjs/*',
      'resource': '${this.APP_BASE}resource',  // Added this line
      '*': '${this.APP_BASE}node_modules/*'
    },
    packages: {
      angular2: { defaultExtension: false },
      rxjs: { defaultExtension: false },
      resource: { defaultExtension: false }  // Added this line
    }
  };
```
However it is still trying to load the file with .js extension at the end.  So I also tried the same method for resource.json, but again it added a .js at end.  What do I need to do?

**Comment by mgechev** [comment]
Use `require('./resource.json');`. Take a [look at the config here](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L194).

**Comment by mpetkov** [comment]
Thanks for quick reply however issue is not that it doesn't load from correct path, it is that it is loading resource.json.js instead of just resource.json.  So the path is fine, its the extension that is wrong because the default extension is set to JS and for some reason it is not reading the overwrite in packages.

Here is screenshot:
**If I do require('./resource.json');**
![screen1](https://cloud.githubusercontent.com/assets/8858458/14497293/00b597ea-015c-11e6-91eb-514d0f0767be.JPG)

**If I do require('./resource');**
![screen2](https://cloud.githubusercontent.com/assets/8858458/14497298/03eee182-015c-11e6-8ab5-c7f11367fe08.JPG)

**Comment by mgechev** [comment]
```
'resource': '${this.APP_BASE}resource',  // Added this line
```

means `/resource.js` (because there's `defaultJSExtensions: true`). If `resource` is located in different directory use: 

```
'resource': '${this.APP_BASE}/data/resource'
```

Now `resource` will be loaded from `/data/resource.js`.

**Comment by mpetkov** [comment]
Sorry if I am not explaining it correctly but the path is not the issue, the extension is.  So how do we make the app call a require or a require.json file with .js extension?

**Comment by mgechev** [comment]
You need to disable the `defaultJSExtension` option for this "module". For further information take a look at the [SystemJS API docs](https://github.com/systemjs/systemjs).
