### ISSUE TITLE
build.prod config for dependent loading of systemjs

### ISSUE THREAD

**Issue by marcgr** [mgechev/angular2-seed#756]
I have a use case that requires loading my application first via an amd loader (via dojo) that on load runs the System.import for the rest of the application.  This works okay for the dev build, but not for the production build since it creates a self executing output from systemjs builder and is not then loaded in the right order.

Here is the code that works for the dev build that I wrapped around the system.import section of the index.html:
<% if (ENV === 'dev') { %>
    
        // load esri modules needed by this application
        // into a System.js module called esri
        esriSystem.register([
          'esri/map',
          ...          
        ], function () {
            // then bootstrap application
            System.import('<%= BOOTSTRAP_MODULE %>')
      .catch(function (e) {
          console.error(e,
            'Report this error at https://github.com/mgechev/angular2-seed/issues');
      });
        }, {
            outModuleName: 'esri-system-js',
            moduleNameOverrides: {
                'esri/map': 'esriMap',
                ...
            }
        });
    
    <% } %>

Are there any logical config settings that could be used to leverage this approach?

I am following the use pattern from this git project.  [(https://github.com/Esri/esri-system-js)]

I realize this may border a support question, but may also expand the range of use cases that the angular2 seed project can support.  

Marc

**Comment by mgechev** [comment]
This is mostly SystemJS related question. My suggestion is to move the production build to SystemJS as well, instead of cjs output like now.

You can do this by overriding the `build.js.prod` task by creating the file `build.js.prod.ts` in `tools/tasks/project`.

**Comment by hhubik** [comment]
I think I am running into a similar problem. @mgechev could you please provide a bit more detail on what needs to be in the `tools/tasks/project/build.js.prod.ts` (assuming the current version of the Seed) to "move the production build to SystemJS".  Thanks.
