### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by ludohenin** [mgechev/angular2-seed#758]
I'm getting this error `npm ERR! cb() never called!` when installing dependencies from the latest master.
It's working well from this commit aa9ad6ab32cf568fcf93f4b5e1c77d095c33c8a2

Can anyone reproduce ?

_OSX - node 5.9.1 - npm 3.8.6_

**Comment by mgechev** [comment]
Did you try `npm cache clean`?

**Comment by mgechev** [comment]
Here's what I found https://github.com/angular/angular/issues/8053

**Comment by ludohenin** [comment]
node 5.10.1 fixed the issue.
