### ISSUE TITLE
Question How to handle Application Environment Config file ?

### ISSUE THREAD

**Issue by brindasanth** [mgechev/angular2-seed#766]
I have a basic question, I have set of Rest service endpoints, which depends on environment ( dev, st, uat,prod). What is the best way to inject the application properties respective to environment in this seed ?

**Comment by d3viant0ne** [comment]
@ludohenin is doing a bit of that here -> https://github.com/ludohenin/ng2-wp-blog

**Comment by mgechev** [comment]
One option is to define the config like in the [example above](https://github.com/ludohenin/ng2-wp-blog/blob/master/src/config.ts). The problem with this approach is  that when you change the config, you need to restart the build (i.e. stop the build and run `npm start` again).

Another option is to do something like this in `src/client/app/config/config.ts`:

```ts
const BASE_CONFIG = {
  // ...
};
const ENV_CONFIG['prod'] = {
  // ...
};
const ENV_CONFIG['dev'] = {
  // ...
};
export const CONFIG = Object.assign(BASE_CONFIG, ENV_CONFIG['<%= ENV %>']);
```
