### ISSUE TITLE
Request : Default login component, Socket and Material Design

### ISSUE THREAD

**Issue by brindasanth** [mgechev/angular2-seed#767]
I see this seed is very much active. Is it possible to provide default login component with Socket, material design integration ? ( We are looking for seed like https://github.com/angular-fullstack/generator-angular-fullstack with angular2 )

**Comment by d3viant0ne** [comment]
@brindasanth - The seed is meant to be very extendable, thus adding those things would have side effects for other users.

I've extended the seed to use material2 ( what's available that is ) and it's simple enough.

Add packages to package.json, add the same to the ```DEPENDENCIES``` in project.config.js and you are off to the races.

As far as a login page and socket integration, that is well beyond the scope of this project though much like adding Material2 / sass / PostCSS / angular2-jwt / whatever it just a matter of adding packages, systemjs config & then importing.
