### ISSUE TITLE
Unable to resolve dependencies "typings install && gulp check.versions && npm prune" Proxy Issue

### ISSUE THREAD

**Issue by dhaselden** [mgechev/angular2-seed#778]
If you are behind a corporate proxy the post install step "typings install && gulp check.versions && npm prune" step will fail. Re: [This typings module issue](https://github.com/typings/typings/issues/106)

To fix issue create ".typingsrc" file in angular2-seed project root and set the contents to this;

`proxy=YOUR_PROXY`
`rejectUnauthorized=false`

**Comment by mgechev** [comment]
Thanks for pointing this out! I'll add it to the FAQ section of the wiki.

**Comment by OlivierMary** [comment]
@dhaselden Thhhhhhhhhhhhhhhhannnnnnnnnnnnnnnnnnnnnnnnkkkkkkkkkkkkkkkkkkkkkkksssssssssss :+1:
