### ISSUE TITLE
End to End testing is refreshing browser for every test module

### ISSUE THREAD

**Issue by kunjee17** [mgechev/angular2-seed#780]
Hi, first of all thanks for wonderful project. Thanks to your effort now there is not need to hack around to get TS support. 

I have a query regarding E2E testing. I don't know where to ask; so asking here. If that is not appropriate please let me know the channel and feel free to close the issue. 

While doing E2E testing, for every bunch (file / module) it is refreshing the browser. Now, we are facing issues when user can do sign in and check one page it fails with angular not found issue (I guess file is yet to be loaded after page refresh). Also, test execution is little slower as it is refreshing browser every time. 

In previous project we have used selenium (Java) to write all test cases for angular application. In that everything was serial. Means whole bunch execute at once and page will not refresh until new page (whole page reload). It will be great if you can provide some insight over approach current project is following and if it is possible to by pass page reload. 

Please, do let me know if any further details required  from my end.

**Comment by d3viant0ne** [comment]
//cc @Shyam-Chen

**Comment by Shyam-Chen** [comment]
@kunjee17 
If you do not refresh your browser, you can put it all together

```coffee
# example.coffee
describe 'Core', ->
  beforeEach ->
    browser.get '/'
    browser.waitForAngular()

  it 'should have a router', ->
    expect(browser.getLocationAbsUrl()).toMatch '/'

    el = element By.css 'md-content span'

    element(By.id 'about').click()
    expect(browser.getCurrentUrl()).toMatch '/about'
    expect(el.getText()).toEqual 'About Page'

    element(By.id 'home').click()
    expect(browser.getCurrentUrl()).toMatch '/'
    expect(el.getText()).toEqual 'Home Page'
```

**Comment by d3viant0ne** [comment]
@Shyam-Chen - Thanks 👍

**Comment by kunjee17** [comment]
@Shyam-Chen @d3viant0ne thanks for reply. So, for dumb questions I m not a automation guy. 

I just reiterate things again and you let me know if I understand correctly. 

I should keep test separated. Basically I have for big project. But if I allow refresh page which is happening due `browser.get()` then how can I maintain state. Means how can I do sign in and check the module if application refresh is throwing me back to sign in page. 
Don't I need to sign in again and again in that case?

**Comment by Shyam-Chen** [comment]
@kunjee17 
You can write in `beforeEach` inside

```coffee
# baz.coffee
describe 'About', ->
  beforeEach ->
    browser.get '/'
    browser.waitForAngular()
    element(By.id 'about').click()  # It's here

  it 'should have a content', ->
    el = element By.css 'md-content span'
    expect(el.getText()).toEqual 'About Page'
```

**Comment by kunjee17** [comment]
@Shyam-Chen OK. I ll have a look at this approach. Will disturb you again in case of queries. Thanks for help. :+1:

**Comment by mgechev** [comment]
@kunjee17 any updates here?

**Comment by kunjee17** [comment]
@mgechev I have tried and make it working using `browser.wait()`. but now trying to make in sync with server response. But I still feel little different with approach. Lets see.

**Comment by mgechev** [comment]
Lets close this one. If there are other queries around this topic we can re-open it.
