### ISSUE TITLE
Client Folder

### ISSUE THREAD

**Issue by DiegoYungh** [mgechev/angular2-seed#781]
Why was added recently a **src/client** folder ?
I looked into the styleguide to understand this approach but could not get it.

Are you planning on using server|client folders ?

**Comment by d3viant0ne** [comment]
https://github.com/mgechev/angular2-seed/pull/750

**Comment by d3viant0ne** [comment]
Discussion around your question is in the pull request

**Comment by DiegoYungh** [comment]
Oh thanks
I just saw the commit, not the PR

The pull is self-explanatory, I agree with the new structure but as you said I do not know if I agree on adding a "+" sign lazy-loaded components.

Please update the front readme and angular2-styleguide regarding this approach

**Comment by DiegoYungh** [comment]
we can close this :+1:
