### ISSUE TITLE
Unit testing - mocha reporter displays out of order

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#787]
A recent change to the dependencies has caused this to happen:
```
21 04 2016 16:19:50.453:INFO [Chrome 49.0.2623 (Mac OS X 10.11.4)]: Connected on socket /#Awdez7PG9N_Vg6SXAAAB with id 97744564
  About component
    ✔ should work
  NameList Service
  Home component
  App component
    ✔ should return the list of names
    ✔ should work
    ✔ should work
```

They used to display under the proper category; they now display out of sequence. Not sure why yet. 

node `v5.5.0`, npm `v3.5.3`

**Comment by TheDonDope** [comment]
Hi @NathanWalker,

i tried to reproduce your error on the latest HEAD (https://github.com/mgechev/angular2-seed/commit/9a41f2369079c275ef59b5c7444cc51a351a5fae), but my output looks fine:

```bash
START:
26 04 2016 09:37:25.391:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
26 04 2016 09:37:25.407:INFO [launcher]: Starting browser PhantomJS
26 04 2016 09:37:25.429:INFO [launcher]: Starting browser Chrome
26 04 2016 09:37:27.047:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#8MxYeDS54NInXoqIAAAA with id 22142106
26 04 2016 09:37:29.439:INFO [Chrome 50.0.2661 (Mac OS X 10.11.4)]: Connected on socket /#6k4aLutD4XN9tarCAAAB with id 26896990
  About component
    ✔ should work
  NameList Service
    ✔ should return the list of names
  Home component
    ✔ should work
  App component
    ✔ should work

Finished in 0.798 secs / 0.743 secs

SUMMARY:
✔ 8 tests completed
``` 

However my node and npm versions are different:

```bash
$ node -v
v5.10.1
```

```bash
$ npm -v
3.8.6
```

I made a `git bisect` between Release `2.0.0-beta.14` and `master` but couldn't reproduce it at any point :/

**Comment by OlivierMary** [comment]
Hi,

I had the same problem last week and now it's good for me, but dont know why...

**Comment by mgechev** [comment]
@OlivierMary may be you've updated any of the project's dependencies?

@NathanWalker can you still reproduce the issue?

**Comment by d3viant0ne** [comment]
Oops, wrong button

**Comment by d3viant0ne** [comment]
@mgechev - I saw the same thing last week which is no longer an issue. As it stands right now, whatever the root cause was no longer exists.
