### ISSUE TITLE
Crashes on editing source file

### ISSUE THREAD

**Issue by csvan** [mgechev/angular2-seed#788]
**Steps to reproduce and a minimal demo of the problem**

1. Install seed project according to instructions in README
2. Run `npm start`
3. Do a trivial source change (e.g. add a blankspace after a semicolon) to `main.ts` (for example) and save to trigger an update

**Current behavior**

Process crashes with the following output. Actual file system paths have been replaced by `myPath`

```
Error: ENOENT: no such file or directory, stat '/myPath/WebstormProjects/angular2-seed/src/client/main.ts___jb_tmp___'
    at Error (native)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /myPath/WebstormProjects/angular2-seed/npm-debug.log
```

**Expected/desired behavior**

The normal update process should occur.

**Other information**

IDE: Webstorm 2016.1
OS: Ubuntu 16.04
Browser: Chrome 50
Nodejs: 5.10.1
NPM: 3.8.3

**Comment by mgechev** [comment]
Not related to the seed https://github.com/mgechev/angular2-seed/issues/717.

You can include all `*. ts___jb_tmp___` files to the list of ignored ones, that should not be processed.
