### ISSUE TITLE
Crashes on npm run docs - "missing script"

### ISSUE THREAD

**Issue by csvan** [mgechev/angular2-seed#789]
**Steps to reproduce and a minimal demo of the problem**

1. Install seed project according to instructions in README
2. Run `npm run docs`

**Current behavior**

Process crashes with the following output.

```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docs"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! missing script: docs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/christopher/WebstormProjects/angular2-seed/npm-debug.log
```

**Expected/desired behavior**

The docs should be shown

**Other information**

IDE: Webstorm 2016.1
OS: Ubuntu 16.04
Browser: Chrome 50
Nodejs: 5.10.1
NPM: 3.8.3

**Comment by mgechev** [comment]
It is a bug in the readme. You should run `npm run build.docs`.
