### ISSUE TITLE
Live reloading watcher not working , application terminate in some basic changes.

### ISSUE THREAD

**Issue by ishara** [mgechev/angular2-seed#790]
Live reloading watcher not working , application terminate in some basic changes.

Reproduce : run npm start and add new link to 'src\client\app\components\navbar.component.html' and save , Then undo the changes and save. 

Error  :

`[BS] Serving files from: dist/empty/
Error: ENOENT: no such file or directory, stat 'd:\RNDA\AngulerJS\codegen\angular2-seed\src\client\app\components\navbar.component.html___jb_tmp___'
    at Error (native)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\ishara\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\RNDA\AngulerJS\codegen\angular2-seed\npm-debug.log`

**Comment by d3viant0ne** [comment]
seed\src\client\app\components\navbar.component.html___jb_tmp___' <------ jb_tmp === JetBrains

Run it from the command line and it works fine.

**Comment by ishara** [comment]
Hi 

yes I have run with command line ,Still process killed.

Error Log -
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:5555/
    External: http://172.16.3.59:5555/
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://172.16.3.59:3001
 -------------------------------------
[BS] Serving files from: dist/empty/
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat 'E:\trunk\research\CGN2Component\src\client\app\components\navbar.component.html___jb_tmp___'
    at Error (native)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ishara\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-component@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!

**Comment by mgechev** [comment]
Duplicate of https://github.com/mgechev/angular2-seed/issues/717

**Comment by ishara** [comment]
Yes this is issue due to WebStrome "safe write".
Thanks
