### ISSUE TITLE
Compile error with Injector class as beta.16

### ISSUE THREAD

**Issue by fourctv** [mgechev/angular2-seed#793]
I've just synced to latest seed, beta.16, and I'm getting compile errors in the Injector class, it says: 
`Injector.resolve does not exist on type 'typeof Injector'`.

I went back to beta.15 and everything works as before (of course need to backtrack APP_BASE_REF reference). 

Is the Injector class broken in beta.16?

**Comment by JohnCashmore** [comment]
There are quite a few breaking changes that need updating, do you have an example of where it breaks?

Does the seed work for you when you do a clean clone and run that?

**Comment by fourctv** [comment]
Yes, the seed seems to work. It is some of my code where I use the Injector class that breaks with `beta.16`.

Up until `beta.15` the Injector class had a bunch of static methods, `Injector.resolve()` being one of them. They all seem to be gone now. They do not show up in code hinting and now cause a syntax error.

Maybe that class has changed in `beta.16` and I need to update my code. Angula2 docs does not cover that class.

**Comment by mgechev** [comment]
@fourctv thanks for reporting the issue!

I think this is not related to the seed. Would you check the Angular issue tracker for related issues?

**Comment by JohnCashmore** [comment]
If you look at the breaking changes there was some changes to the injector, i'd start there https://github.com/angular/angular/blob/master/CHANGELOG.md


> Injector was renamed into ReflectiveInjector, as Injector is only an abstract class with one method on it
> Injector.getOptional() was changed into Injector.get(token, notFoundValue) to make implementing injectors simpler
