### ISSUE TITLE
No auto complete from manual typing anymore :(

### ISSUE THREAD

**Issue by Sn3b** [mgechev/angular2-seed#800]
In a previous version I had created a manual typing in the folder tools>manual_typings>project, named it mytyping.d.ts and that was it, I could then reference it from any component without any problem like so: `import {IMyInterface} from 'mytyping';` and I could even have empty braces, place the cursor in the middle and hit Ctrl+Space to get see a list of available objects/interfaces.

Now it still works, as I don't get any compile time error and my project works as expected, but my IDE (SublimeText) underlines `'mytyping'` in red, saying Cannot fine module 'mytyping' and I don't have any suggestions anymore when hitting Ctrl+Space :(

Is there something else I should do now when creating manual typings?

Thanks!

**Comment by atticae** [comment]
I tried to fix this by adding a `typings.d.ts` in the `src/` folder, looking like this:

```
/// <reference path="../typings/browser.d.ts" />
/// <reference path="../tools/manual_typings/project/custom-typings.d.ts" />
```

This approach works great for dev build, but fails on prod build:

```
dist\tmp\typings.d.ts(1,1): error TS6053: File 'C:/Projekte/sd4/frontend/dist/typings/browser.d.ts' not found.
dist\tmp\typings.d.ts(2,1): error TS6053: File 'C:/Projekte/sd4/frontend/dist/tools/manual_typings/project/custom-typings.d.ts' not found.
```

I would love to see a consistent solution. It looks like VS Code does not include the `typings/` and `tools/manual_typings` folders in the build anymore since the second `tsconfig.json` was added to the `src/` directory, and therefore has no access to typings during development.

**Comment by d3viant0ne** [comment]
Taking a run at this one now.

**Comment by mgechev** [comment]
Add `manual_typings.d.ts` in `client` and add references to the manual typings. For instance:

```ts
/// <reference path="../../tools/manual_typings/seed/karma.d.ts"/>
```

**Comment by d3viant0ne** [comment]
I think the point was to be able to use the project's manual typings in the same way we can use the seed typings.

i.e. 
![screen shot 2016-05-07 at 9 59 55 pm](https://cloud.githubusercontent.com/assets/8420490/15095762/13f411e6-149f-11e6-8349-9349aac5f6c3.png)

**Comment by mgechev** [comment]
```ts
/// <reference path="../../typings/browser.d.ts"/>
/// <reference path="../../tools/manual_typings/project/sample.package.d.ts"/>
```

**Comment by atticae** [comment]
Does this work on prod for you? See my comment above, the paths won't work in prod build and throw an error in my project.

**Comment by mgechev** [comment]
You can override the build.js.prod task and this way include the manual typings in the production build.
