### ISSUE TITLE
Unit-tests not finding dependency

### ISSUE THREAD

**Issue by EmanuelEriksson** [mgechev/angular2-seed#801]
We've just added ng2-dragula to our project, so I'm not sure if this should be asked here or there.

Ng2-dragula works in both dev and production builds, but not when running tests.

When we're running with 'npm test' after including ng2-dragula. We're getting the following error:

```
25 04 2016 15:33:18.841:WARN [web-server]: 404: /base/ng2-dragula/ng2-dragula.js
Chrome 50.0.2661 (Mac OS X 10.11.3) ERROR: Error{originalErr: Error{}}
25 04 2016 15:33:18.942:WARN [web-server]: 404: /base/ng2-dragula/ng2-dragula.js
ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?e1a1843273d23ee5028aa25121066ce32fecdb29'}
```

and some of our tests are no longer being executed.

To reproduce start with a fresh checkout of this seed install dragula and ng2-dragula from npm

add "'dragula': `node_modules/dragula/dist/dragula.min.js`" to SYSTEM_BUILDER_CONFIG.paths
add "'dragula': `${this.APP_BASE}node_modules/dragula/dist/dragula`" to SYSTEM_CONFIG_DEV.paths

add "{ src: 'dragula/dist/dragula.min.js', inject: 'libs' },{ src: 'dragula/dist/dragula.min.css', inject: true }" to additional_deps 

and include DragulaService in any component. When you run 'npm test' you get the same error and only 3 of the 4 tests are run, the tests for the component is not executed and doesn't show up in the list of tests.

using dragula 3.6.8 and ng2-dragula 1.1.6

Is there something i'm missing?

**Comment by Neil-Ni** [comment]
@EmanuelEriksson did you also add them under karma.conf.js and test-main.js?

**Comment by EmanuelEriksson** [comment]
@Neil-Ni Brilliant, thank you, that fixed the problem.

**Comment by bsanth** [comment]
@Neil-Ni Can you attach what changes to karma.conf.js and test-main.js you made here? I am facing the same issue. Thanks!

**Comment by EmanuelEriksson** [comment]
In karma.conf i added

'node_modules/dragula/dist/dragula.min.js'
and
{ pattern: 'node_modules/ng2-dragula/**/*.js', included: false, watched: false }

in files for the config



in test-main i added

'ng2-dragula':'node_modules/ng2-dragula',
'dragula':      'node_modules/dragula/dist/dragula.min.js',

in map for system.config.
