### ISSUE TITLE
Possible Issue with inclusion of reflect-metadata in production build

### ISSUE THREAD

**Issue by brian428** [mgechev/angular2-seed#802]
I don't think this is directly related to the seed project, but I thought I would mention it:

After this change (57d18695dfc73cd769e34947ef419237cd8b7954), I started getting some errors in my app after a production build. Traced it back to the inclusion of reflect-metadata. If I change Reflect back to only include in the dev build, things seem to work fine again.

My understanding of things like Reflect, Zone, and angular2-polyfills is limited, so I'm not exactly sure why Reflect is causing me problems (and why it's only in the production build). My app is expanded from what's in the base seed, and the error is a strange issue when working with SVGElement (something done by the Highcharts library). This makes me think it must have something to do with a shim or prototype override. But I'm not even sure if it's actually Reflect, or if it's really one of the other shims and including Reflect just causes the problem to manifest itself.

Anyway, as I said, I don't think this is really a seed project issue, but just wanted to point it out in case you wanted to mention possible issues caused by including these in production in the wiki or readme.

(That said, if you have any idea off the top of your head about what the problem might be, I'd be all ears!)

**Comment by atticae** [comment]
I have the same issue in production mode and solved it by reverting the change you linked. No idea what exactly is causing the problem. I am also working with Highcharts, so it might be related to that?

**Comment by brian428** [comment]
Well I doubt it is Highcharts itself, since it works fine in dev mode, and works fine in prod mode when Reflect is omitted. I'd tend to think it's something Reflect is doing, but not sure what (I know what Reflect is in general terms, but not really how it does what it does). 

If other people are seeing this, that makes me think maybe I should add an issue to the Reflect tracker...

**Comment by sprell** [comment]
I am experiencing a similar issue. Seems to be due to the fact that reflect.js has "use strict" at the top which impacts all the other JavaScript in NPM_DEPENDENCIES.

**Comment by brian428** [comment]
If that's the case, I wonder why it works fine when included in the dev build, but fails in the prod build.

**Comment by sprell** [comment]
Likely due to the concatenation and minification for the prod build. For dev they are all separate script tags. Regardless, I manually commented out the "use strict" in relfect.js any my prob build works fine now. I know that's not a good log term solution, but it gets me past the issue for now. I could not simply remove the two shims altogether from the prod build, because I need them for IE to work properly.

**Comment by atticae** [comment]
Hmm, maybe all "use strict" should be removed during bundling then?

**Comment by mpetkov** [comment]
Looks like it is related to #818

**Comment by brian428** [comment]
It's definitely the strange "use strict" that ends up at the top of shims.js after a prod build. The odd thing  is that you can look at the source for Reflect (https://github.com/rbuckton/ReflectDecorators/blob/master/Reflect.js#L17) and see that their "use strict" is _inside_ their IIFE. So this shouldn't be happening...but it is.

I guess the question is how/why is this being moved outside of the IIFE, where it can interfere with all the other JS that runs on the page? Something in the concatenation maybe? Or some other processor that the JS is being run through?

**Comment by brian428** [comment]
If anyone's interested, I was able to work around this by installing gulp-replace and setting up my own build.bundles.ts to strip out 'use strict':

```
function bundleShims() {
  return gulp.src(getShims())
    // Strip 'use strict'
    .pipe(plugins.replace(/('|")use strict\1;/g, ''))
    // Strip comments and sourcemaps
    .pipe(plugins.uglify({
      mangle: false
    }))
    .pipe(plugins.concat(JS_PROD_SHIMS_BUNDLE))
    .pipe(gulp.dest(JS_DEST));
}
```

**Comment by mgechev** [comment]
@brian428 would you open a PR?

**Comment by brian428** [comment]
Sure, I'll see if I can do that today.

**Comment by mgechev** [comment]
Any updates here?

**Comment by brian428** [comment]
Sorry, not yet. Was out of town (camping) for a few days. I should be able to do this in the next day or two.

**Comment by mgechev** [comment]
No worries, let me know if you need any assistance.
