### ISSUE TITLE
build+rebuild of dev

### ISSUE THREAD

**Issue by njs50** [mgechev/angular2-seed#803]
I think it'd be nice if there was still a clean on the initial build to get rid of the junk that accumulates. Also having ts/css linting again would be good.

my suggestion is perhaps something like:

```
gulp.task('rebuild.dev', (done: any) =>
  runSequence('tslint',
              'css-lint',
              'build.assets.dev',
              'build.html_css',
              'build.js.dev',
              'build.index.dev',
              done));

gulp.task('build.dev', (done: any) =>
  runSequence('clean.dev', 
              'rebuild.dev', 
              done));
```

then just get the watcher to run the rebuild.dev task. i'm not sure but maybe some of the other tasks like copying assets could be moved to only run on the initial build?

Is it possible to use gulp-cached on the tslint and css-lint as in the build.js.dev task to only lint the files which have changed? that'd speed things up but keep the linting around.

**Comment by d3viant0ne** [comment]
That doesn't really assist in solving the problems related why things like linting were removed in the first place.

Discussed in detail here https://github.com/mgechev/angular2-seed/pull/782

Feel free to modify your development workflow in which ever way you like but for seed master, speed is the preference with a more robust workflow being opt-in
