### ISSUE TITLE
System is not defined after update

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#805]
Hi,

After update the project I'm receiving this error message:
`SyntaxError:` expected expression, got '<'

System.config(<%=

ReferenceError: System is not defined

System.import('<%= BOOTSTRAP_MODULE %>')
`
But System.js is being loaded correctly, there's no 404 in browser-sync-client.js

**Comment by gustavolira** [comment]
In the browser I just see
`Loading... <% if (ENV === 'dev') { %> <% } %> <% if (ENV === 'dev') { %> <% } %> `

**Comment by gustavolira** [comment]
I could figure out what is the problem.
If you change the location of `APP_SRC              = 'src/client';` from `seed.config.ts` you will receive this error

**Comment by d3viant0ne** [comment]
If you need to change file paths, override the settings in the project.config.ts

Changing core seed settings makes updates more difficult on you.

Also, if you have the issue worked out can you please close the issue.

**Comment by gustavolira** [comment]
Thanks @d3viant0ne
