### ISSUE TITLE
Server Port 5555 conflict with Android Studio's ADB

### ISSUE THREAD

**Issue by Kunepro** [mgechev/angular2-seed#809]
I presume that the choice of port was arbitrary, and therefore I would suggest to change the default server port from 5555 to any other one.
The reason is that it conflicts with [Android Studio's](https://developer.android.com/tools/studio/index.html) ADB. I tried to change ADB's port, but I was unable to reach an happy solution.
Otherwise if a fix is known for ADB's can this be posted in the wiki?

**Comment by salemdar** [comment]
You can change it yourself in `tools/config/project.config.ts`
Just add a line in the constructor:
`this.PORT = 9000 // or any port number`

**Comment by Kunepro** [comment]
I'm perfectly aware of that and I already did, thanks.
You also need to change protractor.conf.js if you need to test (and that's exactly why I need Android Studio).
However the point stands. If, like I assumed, the choice of port was deliberate I am pointing out that this is causing issue with a tool that may be more or less widely used and with plenty of choices for a port number there's no need to use the same that Google's Android Studio uses while developing in Google's Angular2.

**Comment by d3viant0ne** [comment]
IMO you can throw a dart at a port array and conflict with something which is why the seed was designed to allow configuration settings to be easily overridden to fit a developers specific project needs.

We could change the default seed port and your exact argument could be made by someone else with different needs.
