### ISSUE TITLE
Upgrade Angular to the Release Candidate

### ISSUE THREAD

**Issue by gempir** [mgechev/angular2-seed#810]
Since Angular 2 is now out of beta it would be nice to now have the RC in this project aswell. 

https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

**Comment by NathanWalker** [comment]
It is in process 👍 
https://github.com/mgechev/angular2-seed/pull/808

**Comment by ludohenin** [comment]
@gempir there is an open PR for that #808
