### ISSUE TITLE
prod shims.js adds 'use strict' to the top of document

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#818]
Not sure when exactly this update was made, but within the last month shim,js now has 'use strict' at the of the document.  This causes issues with some external libraries such as d3 as can be seen here:
https://github.com/mbostock/d3/issues/2502.  Other than the potential bugs, there is no benefit of adding 'use strict' in production ready code anyway.

I am guessing that this got introduced by an external library that the seeder uses?  If so, which library was it so that I can downgrade?

**Comment by Shyam-Chen** [comment]
[The spec](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code) says:
* Module code is always strict mode code.
* All parts of a ClassDeclaration or a ClassExpression are strict mode code.
* ...

**Comment by mgechev** [comment]
@brian428 is already working on this https://github.com/mgechev/angular2-seed/issues/802
