### ISSUE TITLE
Cannot run succesfully rc0 branch

### ISSUE THREAD

**Issue by sergidt** [mgechev/angular2-seed#826]
After executing npm install and npm start on branch rc0, App doesn't do anything and prints following error into console: 

Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:86 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/package.json(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by d3viant0ne** [comment]
@sergidt - There is a discussion around this in the PR for rc0 https://github.com/mgechev/angular2-seed/pull/808 

Currently incomplete as most of the maintainers were at ngconf this week.
