### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by oricalvo** [mgechev/angular2-seed#83]
It looks as the gulp script uses shell commands that does not work under Windows OS. The issue is with the install.typings task the uses Unix style path ./XXX/YYY

**Comment by PascalPrecht** [comment]
Hey @oricalvo could you give more information on the error that you're getting?

I'm actually taking a look at this now, don't have a windows machine tho. The task is executed using `gulp-shell` I would expected that it properly normalises shell commands when executed on windows machines..

**Comment by Zyzle** [comment]
@PascalPrecht We spoke about this earlier so I did some digging. According to the gulp-shell documentation:

>By default, all the commands will be executed in an environment with all the variables in process.env and PATH prepended by ./node_modules/.bin (allowing you to run executables in your Node's dependencies).

I removed the `./node_modules/.bin` prefix from the commands in `install.typings` and it seems to have worked.

**Comment by ludohenin** [comment]
thanks @Zyzle

**Comment by PascalPrecht** [comment]
Thanks for fixing this!

**Comment by oricalvo** [comment]
Verified successfully. Thanks
