### ISSUE TITLE
Docs: TypeDoc uses TS 1.6 - Ambient modules cannot be nested in other modules

### ISSUE THREAD

**Issue by NathanWalker** [mgechev/angular2-seed#830]
We should update the api doc generation to TypeScript >1.8 or consider moving to:
https://github.com/docscript/docscript

This is continuation of this issue originally posted on advanced seed:
https://github.com/NathanWalker/angular2-seed-advanced/issues/53

**Comment by NathanWalker** [comment]
I'll work on a PR for this soon. Curious other thoughts around either improving doc generation to use something other than TypeDoc or other thoughts on upgrading.

**Comment by d3viant0ne** [comment]
@NathanWalker - I'm open to other options as that project is painfully slow keeping up with TypeScript.

**Comment by d3viant0ne** [comment]
The only real viable answers are TypeDoc & DocScript and whatever love I had for TypeDoc died waiting on updates of the TypeScript Version.

So yeah, DocScript it is unless @mgechev / @ludohenin have an issue with it.

**Comment by mgechev** [comment]
DocScript seems like a WIP at the moment, and it doesn't seem to have [many npm users](https://www.npmjs.com/package/docscript) at the moment. Do you have experience with it?

**Comment by d3viant0ne** [comment]
Current Options seem to be Not Active and WIP. Here is the crux of the problem.

![screen shot 2016-05-15 at 4 27 17 am](https://cloud.githubusercontent.com/assets/8420490/15273124/634618dc-1a55-11e6-96b1-e4c765d5a9c8.png)

**Comment by mgechev** [comment]
Lets drop the documentation support then..

**Comment by jerryorta-dev** [comment]
Would it be acceptable to use of fixed forked version of either TypeDoc or DocScript until issues are fixed on their ( which ever you choose ) master?

**Comment by mgechev** [comment]
If there's such patched fork we can use it.

**Comment by d3viant0ne** [comment]
It's probably just better to go directly to the horses mouth and ask @blakeembry what his plans are for it if any before we go ripping things out.

**Comment by jerryorta-dev** [comment]
The repo is in the process of transferring ownership to TyoeStrong. I do see recent activity that includes bumping TypeScript to 1.8.10. I think once the transfer is complete, typedoc will be back in business for this project.

See: https://github.com/TypeStrong/typedoc/issues/210

> The repo was recently adopted from the original creator into a larger community project (TypeStrong), we are now waiting for npm publish permisions from the same user. Hopefully this won't take too long

**Comment by blakeembrey** [comment]
I definitely intend to keep TypeDoc up-to-date (or help to community do so)  but first I need to get publish rights and access to the default theme from Sebastian. I can't say how long that'll take unfortunately.
