### ISSUE TITLE
Prod build error on loading @angular/core.js

### ISSUE THREAD

**Issue by RobNordon** [mgechev/angular2-seed#831]
Upon building the production version `gulp build.prod` an error is caused in the `build.bundles.app` task which stops the build.

[14:01:36] Starting 'build.bundles.app'...
Unhandled rejection Error on fetch for @angular/core.js at file:///C:/Dev/angula
r2-seed/node_modules/@angular/core.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'C:\Dev\angular2-seed\nod
e_modules\@angular\core.js'
    at Error (native)

**Comment by NathanWalker** [comment]
Try running: `npm run build.prod`

**Comment by NathanWalker** [comment]
Also you may need to:
```
rm -rf node_modules typings
git pull
npm install
npm run build.prod
```

**Comment by RobNordon** [comment]
Thanks Nathan, however the same error results.

I'm using Node v6.1.0, NPM v3.8.8 on Windows 7.

**Comment by NathanWalker** [comment]
This may be a specific version issue with Windows. @d3viant0ne Do you happen to have a Windows setup to help test this out?

**Comment by Shyam-Chen** [comment]
I also encountered the same problem

```bash
Unhandled rejection Error on fetch for @angular/core.js at file:///D:/angular2-seed/node_modules/@angular/core.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'D:\angular2-seed\node_modules\@angular\core.js'
    at Error (native)
```

**Comment by kambojankit** [comment]
I am also facing the same issue with the prod build.

The error i get is as below: 
```
Unhandled rejection Error on fetch for @angular/core.js at file:///C:/****/node_modules/@angular/core.js
        Loading dist/tmp/main.js
        Error: ENOENT: no such file or directory, open 'C:\*****\node_modules\@angular\core.js'
    at Error (native)
```

**Comment by Shyam-Chen** [comment]
[report](https://ci.appveyor.com/project/mgechev/angular2-seed/build/985#L1382)

**Comment by Sjiep** [comment]
Also receiving the prob build error. Receiving the same error as mentioned by @kambojankit and @Shyam-Chen.

**Comment by mgechev** [comment]
I will fix this tomorrow. Most likely wrong system builder config.

**Comment by AntonyBaasan** [comment]
Thanks mgechev. In my case: Windows 10, Node v6.0.0, npm 3.8.6

**Comment by NathanWalker** [comment]
@mgechev I was able to test the fix out with VirtualBox... You were right, system builder config just needed `packages`. Went ahead and cleared everyone here.

**Comment by Priyankashelar10** [comment]
facing same issue
