### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by brindasanth** [mgechev/angular2-seed#838]
While building getting this error.

npm ERR! argv "C:\\Program Files\\IBM\\node\\node.exe" "C:\\Program Files\\IBM\\
node\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package es6-shim@0.33.13 does not satisfy its siblings'
 peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants es6-shim@^0.35.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\brinda\Application\angular2\angular2-seed\npm-debug.log

**Comment by NathanWalker** [comment]
Sounds like you are not up to date?
Try deleting `node_modules` and `typings`, then:
```
git pull
npm install
```

**Comment by Sjiep** [comment]
This error actually shows up when doing a git clone and then npm install:
```
git clone https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install
```

**Comment by mgechev** [comment]
The problem is only reproducible with npm < 3. Caused by a angular2-service-worker, which depends on angular2 beta.17.

**Comment by Sjiep** [comment]
Updating to npm 3.8.9 indeed solves the issue.

**Comment by mgechev** [comment]
@Sjiep i fixed the problem by removing the service worker dependency. Once it is up-to-date I'll revert it back.
