### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by JohnCashmore** [mgechev/angular2-seed#839]
Is it within the scope of this project to add more examples? For instance how to mock a http request for unit tests, how to use mock a class for testing etc.

Or do you think this is better handled else where?

Obviously i am happy to contribute towards these.

**Comment by mgechev** [comment]
We're trying to keep it minimalistic. However, if we grab the computer scientists from a JSON file using XHR I don't think we'll get such a scope creep.

**Comment by JohnCashmore** [comment]
Thats what i thought, I'll branch off master, implement the computer scientists that way and you can have a look and see if you're happy to include it.
