### ISSUE TITLE
loading all angular2 js separated

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular2-seed#846]
Hi,

This behvior https://github.com/mgechev/angular2-seed/issues/400 is happening again?

Thanks

**Comment by mgechev** [comment]
Yes, it is. Angular are not distributing system bundles but only umd bundles so we need to play with the configuration of the seed.

I'd love to assist if anyone wants to take care of this one!

**Comment by ludohenin** [comment]
What's the issue, too long to load all the files in dev ?

**Comment by mgechev** [comment]
Yes, on refresh there's a delay.

**Comment by gustavolira** [comment]
Just to explain in more details...
Nowadays when I start the application (dev mode) I'm receiving 500 requests of .js, 90% is from angular 2.
http://i.imgur.com/KzlGVPH.png

**Comment by mgechev** [comment]
Yes, I agree that it is kind of annoying. I'll see if I can find time for this in the upcoming week.
