### ISSUE TITLE
tslint errors during build.prod

### ISSUE THREAD

**Issue by blackheart01** [mgechev/angular2-seed#847]
**Steps to reproduce and a minimal demo of the problem**

git clone --depth 1 https://github.com/mgechev/angular2-seed.git
cd angular2-seed
npm install
npm run build.prod

**Current behavior**
...
[11:45:14] Starting 'tslint'...

/tmp/angular2-seed/tools/tasks/project/sample.task.ts
      line 13  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.assets.dev.ts
      line 13  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.assets.prod.ts
      line 27  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.docs.ts
      line 31  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.index.prod.ts
      line 24  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.js.e2e.ts
      line 26  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.js.prod.ts
      line 29  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.js.test.ts
      line 29  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/build.js.tools.ts
      line 24  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/check.versions.ts
      line 33  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/clean.all.ts
      line 4  col 25  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/clean.dev.ts
      line 4  col 25  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/clean.prod.ts
      line 4  col 37  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/clean.tools.ts
      line 11  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/karma.start.ts
      line 9  col 2  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/serve.coverage.ts
      line 3  col 23  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/serve.docs.ts
      line 3  col 19  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/server.prod.ts
      line 3  col 19  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/server.start.ts
      line 3  col 18  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/watch.dev.ts
      line 3  col 28  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/watch.e2e.ts
      line 3  col 28  missing semicolon

    ✖ 1 error

/tmp/angular2-seed/tools/tasks/seed/watch.test.ts
      line 3  col 29  missing semicolon

    ✖ 1 error

[11:45:16] Finished 'tslint' after 1.51 s
...

**Expected/desired behavior**

No tslint errors.

**Other information**

OS: Kubuntu 16.04

**Comment by mgechev** [comment]
@blackheart01 if you have time, it'll be great to add the semicolons and open a PR!

**Comment by blackheart01** [comment]
I'm working on that now actually. Will have a PR shortly.

**Comment by blackheart01** [comment]
@mgechev I've made a PR with the fix. I'm not really sure how to link it to this issue. I just put "Fixes #847" in the title of the PR.

**Comment by mgechev** [comment]
Awesome! I'll take a look tonorrow and merge.
