### ISSUE TITLE
Add sass/less

### ISSUE THREAD

**Issue by devmark** [mgechev/angular2-seed#85]
bootstrap 4

**Comment by mgechev** [comment]
We're trying to keep the seed project as minimalistic as possible. Adding extra styles is out of the scope of the project.

**Comment by sclausen** [comment]
I can totally agree with keeping the seed as minimalistic as possible.
Adding bootstrap css/js by adding the includes to PATH.src.lib is very easy, but is there a simpler way to add fonts for bootstrap, or fontawesome by creating a new gulp task like build.dev.libs.js, add the directory to the clean.js task and add the corresponding paths to PATH.src and dest?

**Comment by mgechev** [comment]
It seems like a good idea to create a generic gulp task which manages the application resources. Currently we handle styles and libraries (@ludohenin please correct me of I'm wrong).

Interesting problem which appeared recently is https://github.com/mgechev/angular2-seed/pull/117

**Comment by ludohenin** [comment]
I opened an issue to discuss it #120

**Comment by ludohenin** [comment]
and this one #121
