### ISSUE TITLE
Directory structure - alignment with the style guide

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#857]
After a lot of discussions between we agreed upon a directory structure, which is published at https://angular.io/styleguide.

Unfortunately, angular2-seed is violating it. Here are suggestions for alignment with the standard:

> Instead of grouping by type it'll be better to group by feature, i.e. we can remove the components directory here, same for +home.

> For app, we should move app.component.* outside the components directory and move toolbar, navbar, into separate directories within a directory called shared. After that we need to add barrels in each lazy-loading boundary.

Source https://github.com/mgechev/angular2-seed/pull/856#discussion_r62858563

**Comment by TheDonDope** [comment]
I'll work on it an create a PR for it :)

**Comment by mgechev** [comment]
Awesome! Looking forward for it! I think for now we can keep the `client` directory because the seed could be used for building applications for different platforms (like @NathanWalker do in his advanced seed), so I'd suggest to leave it for now. However, we need to document it and state what it is used for.

**Comment by TheDonDope** [comment]
Hi @mgechev, i've uploaded a first draft, but still have a few issues at runtime. If you could spare some help, i would be super glad! (Also: alright about the `client` directory, i left that alone)

**Comment by mgechev** [comment]
Just finished coding for today. I'll be in gitter. :-)
