### ISSUE TITLE
Change bundles

### ISSUE THREAD

**Issue by phiphou** [mgechev/angular2-seed#860]
Hi,

Your seed works fine, and I using it to learn angular2. But, looking for good seeds, I've notice many of webpack based ones produce 3 bundles : one for the app itself, with just app code, a second one for vendors (angular2,lodash,etc..) and one for polyfills. It's a good pratice because app,vendors and polyfills lifecycles aren't often the same. So I tried to update your seed to achieve this, but with no luck. Any one can help me to do this ? Thanks

**Comment by NathanWalker** [comment]
Hi @phiphou, have you tried creating a production build?
```
npm run serve.prod
```
Take a look at the bundles it creates in `dist/prod`.

**Comment by phiphou** [comment]
Sure I tried ;) But produces 2 bundles, a "big" one (app+vendors) and one for shims. What i'm trying to do is just to explode app bundle in two files, one with just app (should be very small) and one for the rest. So, 3 bundles instead of the actual 2 ;) Hope we understand now well (sorry for my bad english, I'm french ;))

**Comment by zeeshanjan82** [comment]
+1

**Comment by ludohenin** [comment]
@phiphou that should be fairly easy to achieve. What your looking for happens here https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.bundles.app.ts#L20-L23, so by overriding this tasks and read this https://github.com/systemjs/builder#bundle-arithmetic that should work.

**Comment by mgechev** [comment]
Here's an issue for this: https://github.com/mgechev/angular2-seed/issues/864

You're welcome to join the discussion and state opinion.
