### ISSUE TITLE
Is difficult to understand Seed configuration file

### ISSUE THREAD

**Issue by sergidt** [mgechev/angular2-seed#861]
I think is difficult to understand the seed.config.ts file, what is each thing and what is used for.

Is important because if somebody wants to add news libraries, is not clear what have to modify.

**Comment by mgechev** [comment]
I agree. Here are some [example projects](https://github.com/mgechev/angular2-seed#examples) where we can trace how the individual pieces fit together.

If you have time a PR with comments above the properties in the `seed.config.ts` file will be greatly appreciated!

**Comment by TheDonDope** [comment]
I am currently working on documentation for the tools section. There is a `READE.md` in `/tools/` which i will propose a PR with some basic information. Afterwards i'll be looking at general code documentation within the `ts` source files.

Greetings

Dope

**Comment by Bigous** [comment]
Well, it's much better now that we separated the seed.config from project.config. But agree too.
