### ISSUE TITLE
Regarding Production Build

### ISSUE THREAD

**Issue by zeeshanjan82** [mgechev/angular2-seed#862]
I have cloned the repo and was trying the command 'gulp build.prod' which creates the production release however I am a little puzzled as I see one app.js file which has all the code for different components minified and uglified in it. Does it mean when I have say 100 components in the application along with their html , js files , all these components will be put into one app.js file. This means the size of this app.js file will always increase and we are not then using lazy loading as we do not load components which we need, in this way we will be loading all the components which index.html file is loaded.

**Comment by mgechev** [comment]
Yes, at the moment that is the case. More advanced production build will be considered in future.

For sure we'll include tree-shaking and offline compilation in near future when we'll reduce the app size to ~50kb gzipped and minified.
