### ISSUE TITLE
Add inline documentation to existing TypeScript files

### ISSUE THREAD

**Issue by TheDonDope** [mgechev/angular2-seed#867]
Currently, there is just a little inline documentation in the existing TypeScript files (tasks, utils etc.).
Continuing the strive for more documentation it should be aimed at to add more documentation on code level.

I will sign up for this, and keep this as a tracking issue. The following sections should be documented:

- [X] Files in `src/client` (merged with https://github.com/mgechev/angular2-seed/commit/e1a32af5592beb776affc96655a5eb27f87e9867)
- [X] Files in `tools/tasks` (merged with https://github.com/mgechev/angular2-seed/commit/2b8cc50d51820b11bd72fd02b24803d7bbb967ca)
- [X] Files in `tools/utils` (merged with https://github.com/mgechev/angular2-seed/commit/32280fdba91ce3dea7d60b76528b767a65b178a0)

Greetings

Dope

P.S.: Can someone please assign this issue to me, or is an assignment only possible for write-access contributors?

**Comment by d3viant0ne** [comment]
@TheDonDope - Assignment requires write access to the repository.

**Comment by TheDonDope** [comment]
@d3viant0ne Ah, thanks for the clarification! Then i'll have to make do without the assignment i guess, i mostly would have wanted it as a sign of "someone is already working on that, no need to do redundant work" :)

**Comment by d3viant0ne** [comment]
Can also be accomplished by a pull request 
i.e - [WIP] feat(docs): Inline Documentation

**Comment by TheDonDope** [comment]
I plan on submitting separate PRs for the different tasks in this issue, to keep this issue as a "tracker" of sorts. My train of thought was:
1. PR for docs in src/client -> merge -> update task list in this issue
2. PR for docs in tools/tasks -> merge -> update task list in this issue
3. PR for docs in tools/utils -> merge -> update task list in this issue
4. Close this issue as all tasks have been finished.

**Comment by TheDonDope** [comment]
:tada: 
All done :) Thanks for the reviews and merges! 
Issue can be closed now.

Greetings

Dope

**Comment by mgechev** [comment]
Thanks for the great work! :-)

**Comment by TheDonDope** [comment]
Glad to have been of help :)
