### ISSUE TITLE
Overriding port in project.config.ts isn't respecting

### ISSUE THREAD

**Issue by zachallen** [mgechev/angular2-seed#868]
I'm attempting to change the port that the application runs on. In project.config.ts I've got:
`    // this.APP_TITLE = 'Put name of your app here';
    this.PORT = 3000;`
However the app continues to start on port 5555. Changing the APP_TITLE seems to work.

**Comment by Bigous** [comment]
It seems to me that you put the code in a commented line... uncomment it an ti will work.

**Comment by zachallen** [comment]
No, I put them on separate lines. It just formatted it that way.
