### ISSUE TITLE
Provide example of getting/testing scientist names from http service

### ISSUE THREAD

**Issue by stphivos** [mgechev/angular2-seed#869]
It would be really helpful to add this feature, as devs new to angular2 like myself, might not know how to implement it with best practices and also write relevant specs with a mock backend etc.

My idea was to write a scientist main component that has child routes for create/edit/list components and does a bit of url manipulation for an underlying rest service, because that is something most frontend devs will need to do at least once.

I've been trying to contribute this myself, but I got stuck with this issue and I spent hours with no luck...
```
src/client/app/shared/services/scientist.service.spec.ts(20,7): error TS2345: Argument of type 'Function' is not assignable to parameter of type '(done: () => void) => void'.
  Type 'Function' provides no match for the signature '(done: () => void): void'
```

I would appreciate it if someone could provide some help with fixing this spec:
```ts
import {provide} from 'angular2/core';
import {beforeEachProviders, inject} from 'angular2/testing';
import {XHRBackend, ResponseOptions, Response} from 'angular2/http';
import {MockBackend, MockConnection} from 'angular2/src/http/backends/mock_backend';
import {Scientist} from './scientist';
import {ScientistService} from './scientist.service.ts';

export function main() {
  describe('Scientist Service', () => {
    beforeEachProviders(() => {
      return [HTTP_PROVIDERS, provide(XHRBackend, {useClass: MockBackend}), ScientistService];
    });
    it('should get the list of scientists',

      // ##### Line below causes the error #####
      inject([XHRBackend, ScientistService], (mockBackend:MockBackend, scientistService:ScientistService) => {

        mockBackend.connections.subscribe(
          (connection:MockConnection) => {
            connection.mockRespond(new Response(
              new ResponseOptions({
                  body: [] // TODO: Fake scientists
                }
              )));
          });
        // TODO: Expects
      }));
  });
}
```
Thanks.

**Comment by TheDonDope** [comment]
There is currently a PR in progress (https://github.com/mgechev/angular2-seed/pull/841) which addresses this. This issue is also already tracked in https://github.com/mgechev/angular2-seed/issues/839

Greetings 

Dope

**Comment by stphivos** [comment]
Maybe I didn't search enough then.. Awesome thanks @TheDonDope!
