### ISSUE TITLE
Is it possible to provide a CHANGELOG  ??

### ISSUE THREAD

**Issue by mwaa** [mgechev/angular2-seed#870]
Is there any possible way of tracking changes that are made. Reason for this is because i cloned the seed 2 weeks ago and been actively coding using that version of the seed which by now is a little behind. 

It would be nice to have a CHANGELOG text file that can inform me of any new changes made rather than me having to track the changes via commits. Or if there is an easier way to pull in changes to my project i will be grateful for the assistance.

**Comment by TheDonDope** [comment]
Hi @mwaa,
what kind of CHANGELOG would be helpful for you? Something like this: https://github.com/angular/angular/blob/master/CHANGELOG.md (Basically listing features / bugfixes / breaking changes for every release)? 

As for syncing / pulling changes, have a look here:
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

Greetings

Dope

**Comment by mgechev** [comment]
@mwaa as @TheDonDope mentioned the breaking changes you had are actually introduced by Angular 2 rc.1 not by the seed itself.

**Comment by mwaa** [comment]
@TheDonDope thanks for the assist i am using that already.

@mgechev I do realize that the breaking changes are not because of the seed itself. But a CHANGELOG file for any fixes you make to the seed would be helpful.

An example been that you made a fix to given issue say no. 12 . And on my project fork i encounter the issue described in no. 12. I would then come to your repo and check the change log and identifier the exact changes that were made to fix it

**Comment by mgechev** [comment]
You don't need to make updates manually. All you need to do is:

```bash
git add remote upstream https://github.com/mgechev/angular2-seed
git pull upstream master
```

If you have followed the conventions described by @TheDonDope [here](https://github.com/mgechev/angular2-seed/tree/master/tools) everything should work fine.

**Comment by mwaa** [comment]
Cool Thanks.
