### ISSUE TITLE
npm install, npm start and then localhost:5555 and....

### ISSUE THREAD

**Issue by ceballos59** [mgechev/angular2-seed#871]
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:98 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@angular/package.json(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ localhost/:98

**Comment by TheDonDope** [comment]
Hi @ceballos59, at which commit does your local git HEAD stand?
Based on the latest commit (https://github.com/mgechev/angular2-seed/commit/94d472c8ad7a3af36ee4dc480139d3809661b88b) i cannot reproduce your problem.
Also: Which platform are you on? What's your node version? What's your npm version?

**Comment by mgechev** [comment]
@ceballos59 any updates?

**Comment by vmumo** [comment]
Same error. On Linux. node -v6.0.0 npm -v1.4.21

**Comment by TheDonDope** [comment]
@vmumo Your npm version doesn't seem to fulfill the required version for the seed, quoting the README:

> Note that this seed project requires node v4.x.x or higher and npm 2.14.7.
