### ISSUE TITLE
Sass support broken?

### ISSUE THREAD

**Issue by vdest** [mgechev/angular2-seed#872]
After following "Adding Sass support" rules, the app no longer launches. After running `npm start` or `gulp build.dev` it hangs at `Starting 'build.html_scss'...`

**Comment by d3viant0ne** [comment]
https://github.com/archfirst/angular2-seed-sass

**Comment by vdest** [comment]
Yes I know this fork. I was trying with this one because it's been updated to angular rc1. The other fork is still using beta.

**Comment by d3viant0ne** [comment]
My point being, if the issue is going to be figured out / fixed that will be where it's done.

If I have time later this evening, I'll see if I can figure out what the issue is. You are following the instructions in the wiki yes?

**Comment by vdest** [comment]
Yes I did follow the wiki. I'll try taking seed tasks from seed-sass fork and put them in this seed to see if they work.

**Comment by JCCR** [comment]
I followed the same wiki entries but on `npm start` everything looks fine to me. It's just watching for changes and updating with browsersync breaks.

**Comment by d3viant0ne** [comment]
Just pulled a fresh clone of the seed & ran through the sass wiki instructions, works fine.
