### ISSUE TITLE
Can't bootstrap angularfire2

### ISSUE THREAD

**Issue by aayushkapoor206** [mgechev/angular2-seed#873]
**Steps to reproduce and a minimal demo of the problem**

bootstrap FIREBASE_PROVIDERS

**Current behavior**

console error
`http://localhost:5555/node_modules/http/package.json `
`http://localhost:5555/node_modules/https/package.json `
`http://localhost:5555/node_modules/_stream_writable/package.json`

**Expected/desired behavior**

No error

**Other information**

**Comment by mgechev** [comment]
Here's an updated article https://github.com/mgechev/angular2-seed/wiki/Integration-with-AngularFire2.
