### ISSUE TITLE
is it possible to get the client console output?

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#874]

**Comment by mgechev** [comment]
What input do you want to provide?

**Comment by sfabriece** [comment]
I want to get the console output from the browser so that I can see error in the terminal instead of chrome dev tools.

**Comment by mgechev** [comment]
If it is a runtime error it will be always outputted in chrome dev tools.

**Comment by sfabriece** [comment]
looking for a way it can be pushed to the terminal from devtools. 
Ionic cli has that kind of functionality.
