### ISSUE TITLE
Start dev server without lauching the browser

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#875]
Can a flag be added to start the dev server without lauching the browser.

**Comment by mgechev** [comment]
Yes, sure. Do you want to open a PR for that?

**Comment by sfabriece** [comment]
I have no idea where to start, since we are using gulp. Any pointer on how to pass arguments to a gulp task?

**Comment by ludohenin** [comment]
@sfabriece  This would require a new option like `PORT` in [`seed.cong.ts`](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L35), say `no-open` to use as `npm start -- --no-open` .
It will look like this `OPEN = argv['no-open'] || true;`
Then you can just import your config member you need like [`this`](https://github.com/mgechev/angular2-seed/blob/master/tools/utils/seed/server.ts#L8)

**Comment by sfabriece** [comment]
I'll give it a go, when I have time.

**Comment by ludohenin** [comment]
Byw that's the other way around tre || argv...
