### ISSUE TITLE
Injecting  self defined service into another self defined service

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#877]
Sorry for posting an angular question here. Desperate times. 

I'm struggling to inject a service into another service. I'm getting undefined.

```
Cannot resolve all parameters for 'PerkStoreService'(undefined). 
Make sure that all the parameters are decorated with Inject...
```

When I inject both services into a component, they work just fine.

What could be the problem?

**Comment by ludohenin** [comment]
@sfabriece you can have a look [here](https://github.com/ludohenin/ng2-wp-blog/blob/master/src/blog/services/wp/xhr.ts#L77)

**Comment by sfabriece** [comment]
i've done exactly that. But i'm still getting undefined. The injected service returning undefined is exported with a barrel. I don't know if that is the reason.

**Comment by mgechev** [comment]
Not related to the seed. You can move the discussion to gitter.
