### ISSUE TITLE
spec.ts for http get service is not working.

### ISSUE THREAD

**Issue by rushikeshsarode** [mgechev/angular2-seed#883]
Following is my 'user.service.ts' file which uses http get to receive data from users.json file :

```ts
import {Injectable} from '@angular/core';
import { IUser } from './userInterface';
import { Http, Response } from '@angular/http';
import{ Observable } from 'rxjs/Observable';

@Injectable()

export class UserService {
    private _productUrl = '../app/users/users.json';
    constructor(private _http: Http) {}
    getUsers(): Observable<IUser[]> {
        return this._http.get(this._productUrl)
        .map((response: Response) => <IUser[]>response.json());
    }
}
```

I have following 'user.service.spec.ts' file to test the above service :

```
import {
describe,
expect,
beforeEach,
it,
inject,
beforeEachProviders
} from '@angular/core/testing';
import { UserService } from './user.service';
import { HTTP_PROVIDERS } from '@angular/http';

export function main() {

  describe('UserService test', () => {
      let service: UserService;

      //setup
      beforeEachProviders(() => {
        return[
            HTTP_PROVIDERS,
            //provide(XHRBackend, {useClass: MockBackend}),
            UserService
            ];
    });

      beforeEach(inject([UserService], (l:any) => {
        service = l;
      }));

    it('should return the list of users', () => {
      service.getUsers().subscribe(x => {
      expect(x).toEqual(jasmine.any(Array));
      });
    });
  });
}
```

Any guess why this is not working and throws error (attached screenshot) when I run 'npm test'... Thanks in advance.
![untitled](https://cloud.githubusercontent.com/assets/18325320/15289914/e6c10e72-1b92-11e6-8ea5-912504ba5d04.png)

**Comment by JohnCashmore** [comment]
I did start working on an example on how to do this, but I was too slow and the project structure changed before it could be merged 
https://github.com/JohnCashmore/angular2-seed/tree/http-example/src/client/app/shared/services 

I will look at opening another pull request at some point 

Hopefully this will help

**Comment by rushikeshsarode** [comment]
Thanks for the inputs @JohnCashmore JohnCashmore . I have copied both of the files name-list.service.spec.ts and name-list.service.ts... also created name-list.json file. When i run 'npm test' i get following errors :
![untitled1](https://cloud.githubusercontent.com/assets/18325320/15291418/5c549ed0-1b9b-11e6-8029-9a19fe733d1b.png)

**Comment by mgechev** [comment]
@rushikeshsarode for Angular support you can try both angular2-seed and angular channels on gitter.
