### ISSUE TITLE
feature-suggestion: simplify scss stylesheet implementation

### ISSUE THREAD

**Issue by hank-ehly** [mgechev/angular2-seed#895]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**
Users are able to enable sass support by following the instructions on the Wiki page, or by referencing the angular2-seed-sass fork.

**Expected/desired behavior**
Allow seed users to enable sass support by specifying a command-line / project.config variable.

**Other information**
In issue #746 , @ludohenin and @d3viant0ne mentioned the benefit of providing an easier way of implementing scss stylesheets.

I have created [a rough example](https://github.com/hank-ehly/angular2-seed/tree/feature/alternate-css-scss) of how this could be done. I understand this issue may be low-priority, but I hope you can consider my contribution.

**Comment by TheDonDope** [comment]
Hi @hank-ehly,

stating my personal opinion, i would like to see this included in the seed. I know there have been arguments against it (referecing #746 as base of the discussion), but i think providing sass support which can be toggled by configuration would be a good compromise. 

Greetings

Dope

**Comment by mgechev** [comment]
Sounds good to me. Not sure if it is worth it to be part of the global project configuration or plugin specific config which was recently implemented by @brian428 here https://github.com/mgechev/angular2-seed/commit/9a86bf51fa0ccba4830fdea01eeeaabb671063a2.

I don't mind merging it since it seems that Sass is very desired feature. @d3viant0ne and @ludohenin what are your thoughts?

**Comment by hank-ehly** [comment]
@mgechev 
Thank you for your feedback. 
I will prepare a refactored & up-to-date version of the above fork for your review by June 1st.

**Comment by mgechev** [comment]
Awesome, looking forward to see it!

**Comment by ludohenin** [comment]
@hank-ehly Don't know if this will help but in version `2.0.0` of [`gulp-inline-ng2-template`](https://github.com/ludohenin/gulp-inline-ng2-template) I've added async support for processor functions (template and styles) and customFilePath ... just to let you know.

**Comment by htdt** [comment]
I'm using http://cssnext.io with `postcss-import` as an alternative to sass. It works as a polyfill, neat and compact in this seed. There was an issue with `build.js.test`, but async support in `gulp-inline-ng2-template` just has solved it. If somebody is interested, I can share the tasks.

**Comment by d3viant0ne** [comment]
@htdt - I normally use pre/postcss for scss functionality but there are and always will be people that want or need to use a preprocessor for their styles.

Personally I think the ability to simply define your style sheets implementation of choice without having to jump through a bunch of hoops is a solid feature.

**Comment by hank-ehly** [comment]
@mgechev,

I have rebased my commits onto the current master branch and submitted a pull request for your review (#952)

Just as @d3viant0ne mentioned, this allows users to define their stylesheet preference without having to manually edit any seed files.

- To begin using scss, specify the flag: `npm start -- --scss`
    - If everyone would rather enable scss-processing without modifying the global project configuration, please let me know and I will find a different solution.
- References to `stylesheetUrls` from .ts components should use the `.css` format, not `.scss`

Thank you for your consideration

Hank

**Comment by TheDonDope** [comment]
Thank you very much @hank-ehly for the PR :)
