### ISSUE TITLE
Hotjar script in index.html?

### ISSUE THREAD

**Issue by dodoshanti** [mgechev/angular2-seed#896]
We would like to add the the below tracking code into the index.html. The code requires an ID which needs to be different depending on environment. 
What's the best way to way to handle this?
Thanks
` (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:<ID>,hjsv:5};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
      })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');`

**Comment by mgechev** [comment]
For support you can use gitter.
