### ISSUE TITLE
setTimeout intercepted and requires Timer type variable to be assigned to

### ISSUE THREAD

**Issue by jeserkin** [mgechev/angular2-seed#901]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_
1.  Create class
```typescript
import { Component, OnDestroy } from "@angular/core";

@Component({
  selector: 'sample',
  tempalte: '<div></div>'
})
class SampleComponent implements OnDestroy {
  private currentTimeout: number;

  public sampleMethodCall() {
    this.currentTimeout = setTimeout(() => {
      alert('working');
    }, 300);
  }

  ngOnDestroy(): any {
    return undefined;
  }
}
```
2. Save
3. Watch comiler consile livereload

**Current behavior**
On `*.ts` file change comiler in console shows following error
`.component.ts(27,5): error TS2322: Type 'Timer' is not assignable to type 'number'.`

**Expected/desired behavior**
Like in every `setTimeout` TypeScript tutorial on the web. Excpect it to return `number` type result, not `Timer`.

**Comment by mgechev** [comment]
[Here's the first result](https://github.com/Microsoft/TypeScript/issues/842) when Googling the error you have, i.e.:

```ts
...
    this.currentTimeout = window.setTimeout(() => {
      alert('working');
    }, 300);
...
```

solves your problem.

**Comment by jeserkin** [comment]
Okay, but all examples on the internet don't need to specify. Is it only angular2-seed issue?

**Comment by ludohenin** [comment]
I think it is due to core node.d.ts lib in typescript.

**Comment by nadavsinai** [comment]
@mgechev isn't adding window.XXXXXX breaks the possibility of running the app in server/worker based rendering scenario? I thought removing the node.js type definitions would help but unfortunately it doesn't seem to work, any other ideas?

**Comment by mgechev** [comment]
@nadavsinai yes, you're correct. Directly accessing `window` will prevent your application from running in Web Worker/Server.
