### ISSUE TITLE
webpack's resolve.alias doesn't seem to work for 3rd party modules

### ISSUE THREAD

**Issue by bbottema** [mgechev/angular2-seed#904]
I'm trying to make npm [ng2-prism](https://github.com/tpadjen/ng2-prism) work with this seed, but it has an issue importing _angular2/http_, which as we know have been rescoped into @angular.

However, I would have thought that the aliases in webpack's config would solve these, but for some reason it's not picking up the alias.

vendor.ts (this is the only file I modified in the seed project)

```
// Angular 2
import '@angular/platform-browser-dynamic';
import '@angular/platform-browser';
import '@angular/core';
import '@angular/http';
import '@angular/router-deprecated';

import 'ng2-prism';
```

The import in ng2-prism's source code is straightforward (codeblock.component.d.ts:1:66):

```
import { AfterViewChecked, AfterContentChecked, ElementRef } from 'angular2/core';
```

The alias configured in webpack.config.js

```
...
resolve: {
    root: [ path.join(__dirname, 'src') ],
    extensions: ['', '.ts', '.js', '.json', '.css', '.html', '.less'],
    alias: {
     ...,
      'angular2/core': path.join(__dirname, 'node_modules', '@angular', 'core', 'index.js'),
     ...
    }
  },
...
```

The error I'm getting on _npm start_:

> ERROR in [default] C:/workstation/simple-java-mail/src/main/webapp/node_modules/ng2-prism/src/codeblock.component.d.ts:1:66 
> Cannot find module 'angular2/core'.

Ofcourse [ng2-prism should update its dependencies](https://github.com/tpadjen/ng2-prism/issues/4), but this is a situation we will run into sooner or later with one library or another. 

But I don't see a reason why the import can't be resolved. What am I missing? I'm not even sure if the issue is with webpack or a config issue in this project seed.

**Comment by bbottema** [comment]
I'm [trying my luck on stackoverflow](http://stackoverflow.com/questions/37333071/webpacks-resolve-alias-doesnt-seem-to-work-for-3rd-party-modules) as well.

**Comment by ludohenin** [comment]
@bbottema We are not using webpack in this seed. Closing as this not related to the seed. Thanks.

**Comment by bbottema** [comment]
@ludohenin, sorry, I clicked the wrong seed in Google (it has the same name, different github user).
