### ISSUE TITLE
Core-js instead of es6-shim

### ISSUE THREAD

**Issue by Toktik** [mgechev/angular2-seed#908]
I had issue with IE11 in prod mode. Generating a 20 rows/10 columns table was taking 50 seconds comparing to <1second on Chrome/Firefox.

This is the issue in Angular repo
https://github.com/angular/angular/issues/8112

As suggested, I've replaced es6-shim with core-js. Now IE has same performance as Chrome.

Lets use core-js by default in seed?

**Comment by Shyam-Chen** [comment]
migrate to core-js from es6-shim
