### ISSUE TITLE
Sass support in wiki

### ISSUE THREAD

**Issue by christophertrudel** [mgechev/angular2-seed#910]
[Sass support broken? #872](https://github.com/mgechev/angular2-seed/issues/872)

As discussed in the above the instructions work to support Sass. I have noticed when you run  `npm run serve.prod` or `npm run build.prod` it doesn't work. I'm pretty sure I didn't miss any instructions. Here is the directory structure difference.
![screen shot 2016-05-21 at 9 33 25 am](https://cloud.githubusercontent.com/assets/394759/15449335/f2841a6c-1f37-11e6-802d-2258bdab1cb8.png)

I suspect there is something missing for `build.index.prod.ts`?

**Comment by adrianfaciu** [comment]
Where did you placed your main.scss file ? In the wiki guide it's placed inside the assets folder, and it works fine. If you just rename the main.css file to main.scss it will still be in the css folder and the path you specify in APP_ASSETS will be invalid `${this.ASSETS_SRC}/main.scss`.

**Comment by christophertrudel** [comment]
Ugh. Brain fart, should have noticed that. Exactly what was wrong, I didn't noticed the main.css file being moved to the `assets` folder. Thanks for the solution.
