### ISSUE TITLE
Codelyzer styles guide causing error in CI

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#911]
I there a way to treat the style guide as a suggestion instead of causing errors when they fail?

Specifically, I'm create a custom routeoutlet that the style guide wants me to use as an attribute instead of element. That suggestion has currently a bug that make is impossible to use.

When I run my code in codeship with suggested way to do it, it fails.

**Comment by mgechev** [comment]
Change [this flag](https://github.com/mgechev/angular2-seed/blob/2b8cc50d51820b11bd72fd02b24803d7bbb967ca/tools/tasks/seed/tslint.ts#L25) to false, or better disable the codelyzer's rules you don't follow.
