### ISSUE TITLE
Conflicts between Backbone, JQuery typings and the seed

### ISSUE THREAD

**Issue by fourctv** [mgechev/angular2-seed#919]
I've installed `Backbone`, `jQuery` and some other 3rd party libraries to my copy of the seed.

There are conflicts between typings definitions in those modules and some of the stuff on the seed.
For example, "$" is declared in `angular-protractor` as `cssSelectorHelper`, and that conflicts with jQuery's declaration.

There is also what seems to be a bug in a `Backbone` declaration, where a function's argument is declared with the name `arguments?`, and that seems to be a Typescript reserved word.

So, to work around those issues I installed `grunt` and created a grunt task to fix the issues above, and added a call to grunt to the `postinstall` script.

I had to use `grunt`, because the typings errors prevent gulp.ts to run, so I could not use a gulp task. And I have it on the `postinstall` script, because the `typings install` step refreshes those typing definitions files.

My `postinstall` script now looks like:
```
typings install  && grunt && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
```

And my `gruntfile.js` looks like this:
```
module.exports = function (grunt) {
    // Do grunt-related things in here
    grunt.initConfig({
        replace: {
            fixProtractor: {
                src: ['typings/main/ambient/angular-protractor/index.d.ts','typings/browser/ambient/angular-protractor/index.d.ts'],
                overwrite: true,                 // overwrite matched source files 
                replacements: [{
                    from: 'declare var $: cssSelectorHelper;',
                    to: '//declare var $: cssSelectorHelper;'
                }]
            },
            fixBackbone: {
                src: ['typings/main/ambient/backbone/index.d.ts','typings/browser/ambient/backbone/index.d.ts'],
                overwrite: true,                 // overwrite matched source files 
                replacements: [{
                    from: 'arguments?:',
                    to: 'args?:'
                }]
            }
        }
    });
    
    grunt.loadNpmTasks('grunt-text-replace');
    grunt.registerTask('default', ['replace']);

};
```

Not sure if this could/should be added to seed or not, or maybe just added to the wiki, describing additional steps for Backbone and jQuery installs. Or even if this is the right approach to the situation.

Additionally, thanks a lot for putting this seed project out. It really help me getting up to speed with ng2.

**Comment by mgechev** [comment]
Thanks for reporting the issue but it doesn't seem related to the seed.

- We don't offer jQuery, Backbone support.
- We are consumers of our dependency typings so if it can't handle the collision of the duplicate `$` identifier this is not something we should take care of.

I'd recommend you to edit the typings manually.

**Comment by fourctv** [comment]
an update to the `gruntfile.js` to be compatible with the latest seed:

```
module.exports = function (grunt) {
    // Do grunt-related things in here
    grunt.initConfig({
        replace: {
            fixProtractor: {
                src: ['typings/global/angular-protractor/index.d.ts'],
                overwrite: true,                 // overwrite matched source files 
                replacements: [{
                    from: 'declare var $: cssSelectorHelper;',
                    to: '//declare var $: cssSelectorHelper;'
                }]
            },
            fixBackbone: {
                src: ['typings/global/backbone/index.d.ts'],
                overwrite: true,                 // overwrite matched source files 
                replacements: [{
                    from: 'arguments?:',
                    to: 'args?:'
                }]
            }
        }
    });

    grunt.loadNpmTasks('grunt-text-replace');
    grunt.registerTask('default', ['replace']);

};
```

**Comment by jmvermeulen** [comment]
Thanks @fourctv! I've created a gulp version of this same concept.
Create a file 'typings-fix.task.ts' in \tools\tasks\project\ with the content:

```
import * as gulp from 'gulp';
import * as replace from 'gulp-replace';

export = () => {
    var source = gulp.src(['typings/globals/angular-protractor/index.d.ts'])
    .pipe(replace('declare var $: cssSelectorHelper;', '//declare var $: cssSelectorHelper;'))
    .pipe(gulp.dest('typings/globals/angular-protractor/'));

    return source;
;}
```

And add the task to gulpfile.ts
```
gulp.task('build.prod', (done: any) =>
  runSequence('clean.prod',
              'typings-fix.task',
```

**Comment by MartinLeoJr** [comment]
@jmvermeulen, I liked your solution and added some regex so it only comments it out once. 
.pipe(replace(/^\s*?declare var \$: cssSelectorHelper;/m, '//declare var $: cssSelectorHelper;'))
