### ISSUE TITLE
Error after changes

### ISSUE THREAD

**Issue by jlberrocal** [mgechev/angular2-seed#921]
Hi everybody, first thanks for this awesome seed project.

Now, i have a problem that occurs when i make changes over the code(any kind of file), when it reload the browser the console throws the following:

EXCEPTION: TypeError: dep is nullbrowser_adapter.js:86
EXCEPTION: TypeError: dep is nullbrowser_adapter.js:77:13

EXCEPTION: Error: Uncaught (in promise): TypeError: dep is nullbrowser_adapter.js:86
EXCEPTION: Error: Uncaught (in promise): TypeError: dep is nullbrowser_adapter.js:77:13

STACKTRACE:browser_adapter.js:77:13

resolvePromise@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:538:32
makeResolver/<@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:515:14
ApplicationRef_.prototype.run/</<@http://dev5-metro.alkaid.cr/node_modules/@angular/core/src/application_ref.js:295:25
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:323:20
NgZoneImpl/this.inner<.onInvoke@http://dev5-metro.alkaid.cr/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:32
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:322:20
Zone</Zone</Zone.prototype.run@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:216:25
scheduleResolveOrReject/<@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:571:53
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://dev5-metro.alkaid[…]browser_adapter.js:77:13

Unhandled Promise rejection: dep is null ; Zone: angular ; Task: Promise.then ; Value: TypeError: dep is null
Stack trace:
[object Object]zone.js:461:14

Error: Uncaught (in promise): TypeError: dep is null

I'm running firefox developer edition under Ubuntu 15.04 (just in case)

Thanks in advance

**Comment by TheDonDope** [comment]
Hi @jlberrocal at which commit is your local git repo's HEAD at? Do you have the latest commit https://github.com/mgechev/angular2-seed/commit/830f0616348a62eefd76a1bb621d9cb3ccba0e9e included?

**Comment by jlberrocal** [comment]
Hi @TheDonDope i can't say that because i remove the git folder, i use this seed project for my own project and it is under other git repository

**Comment by jlberrocal** [comment]
I had an backup and this is the head of the local project 
c076787d5cf6ac8a105b34876cd98324cd6b6a2d

i ran this command to get it 
`git rev-parse HEAD`

**Comment by TheDonDope** [comment]
Hi @jlberrocal, thanks for the info! Can you try to update to the latest commit of the seed and see if you can still reproduce it?

**Comment by jlberrocal** [comment]
on my backup looks like is not happening after i apply the last commit, i'll merge both projects and then i'll try again

**Comment by jlberrocal** [comment]
Ok, now when i try to compile i'm having the following:
 TypeError: task is not a function at Gulp.<anonymous> (/home/jberrocal/Projects/alkaid-metro/trunk/metro-portal/tools/utils/seed/tasks_tools.js:31:33)

**Comment by jlberrocal** [comment]
forget my last comment, it compile now.

I already merge both projects and i'm still getting the error after any change on code

**Comment by cristi-en** [comment]
I also have problems after live reload. 
I've made a comparison of the dist/dev directories before after start and after live reload and the metadata info is missing and live reload.

**Comment by jlberrocal** [comment]
if that were the case and according with what i know that can be solve using the typescript.json file, right @TheDonDope ???

**Comment by ludohenin** [comment]
I can't reproduce.

**Comment by jlberrocal** [comment]
Ok i'll give you more context, i take out the content of the folder client (i don't need more path), then i rename the +about and +home to the same names but with out the plus symbol, that should be the reason???

**Comment by ludohenin** [comment]
If you rename the path to the corresponding modules wherever their are imported, that should work.

**Comment by jlberrocal** [comment]
Yes, i change the name in the imports and also i change the path in config file for delete the client folder

**Comment by mgechev** [comment]
Any updates here? I can't reproduce it neither.

**Comment by jlberrocal** [comment]
Well I downloaded the seed again and add the modules again and now I'm not seeing the error

**Comment by mgechev** [comment]
Great to hear that!

**Comment by cristi-en** [comment]
My problems got fixed after adding some typings. I can't explain why....
