### ISSUE TITLE
Why do you use export function main() in tests?

### ISSUE THREAD

**Issue by silentHoo** [mgechev/angular2-seed#922]
I still wonder why there's the need to export the main() function in every test spec. Could you explain that for me? The tests are still run by karma if I forget to put my tests into the main() section. Is there any reason for that?

If you have a look at test-main.js:89-95 you will find the code where main() is expected and called:

````
return System.import(path).then(function(module) {
    if (module.hasOwnProperty('main')) {
      module.main();
    } else {
      throw new Error('Module ' + path + ' does not implement main() method.');
    }
  });
````

Thanks in advance.

**Comment by ludohenin** [comment]
@silentHoo It's a convention.
