### ISSUE TITLE
Live-reload not working when changing Component CSS

### ISSUE THREAD

**Issue by Sjiep** [mgechev/angular2-seed#925]
Is it normal that the live-reload functionality doesn't update the CSS if it is part of a Component. 

Even on a cleanly installed seed and I change for example the background-color of the HomeComponent :host, the changes is only reflected when doing a 'hard' reload.

Might this have something to do with the fact that it is injected by Angular2 in the head of the index.html file?

**Edit:** this seems only to be the case when referencing an external CSS file, that is, using `styleUrls` inside the Component annotator. When you use the `styles` key and define the CSS directly in the Component it seems to work alright.

**Comment by ludohenin** [comment]
@Sjiep I just check that point and I don't see any ways to make this working. When a css file is modified, browsersync looks if it is in the document (which is not the case for components) so it doesn't inject anything, futhermore, component style sheets need to be compiled by Angular, those files would then need to trigger a full reload, but as there are css, browsersync doesn't trigger that one.

When you modify a component (styles or any else), you modify a js (compiled ts) file which triggers the full reload.

**Comment by htdt** [comment]
As a partial solution, `injectChanges: false,` in [config](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L389) will update window on every change.

**Comment by mgechev** [comment]
I think disabling the CSS injection makes sense.

**Comment by sfabriece** [comment]
What are the implication of disabling CSS injection? thanks.

**Comment by ludohenin** [comment]
@sfabriece not much, when you will change a style sheet from `css` folder, it will trigger a full relaod instead of injecting that file only.

**Comment by sfabriece** [comment]
Ok, thanks @ludohenin .

**Comment by Sjiep** [comment]
Thanks, that indeed solved the issue!
