### ISSUE TITLE
Environment configuration management

### ISSUE THREAD

**Issue by jbouzekri** [mgechev/angular2-seed#927]
It would be nice to have a way to manage different configuration parameters based on environment. It could allow to store things like api endpoints, ...

For example angular-cli override a environment.ts file based on the target environment.

**Comment by mgechev** [comment]
I am already doing this in a project where I am using the seed. I will try to push this feature upstream early next week.

**Comment by btrajkovski** [comment]
Also it would be nice if we could dynamically add environments, and not be limited to just `development` and `production`. 
I don't know your concrete implementation if you have this that is great, if not maybe this could a feature for some future release?

**Comment by mgechev** [comment]
I am thinking of only two build configurations - dev and prod like what we have now.

On top of that, we can have multiple configuration variables loaded dynamically from a JSON config files, located somewhere in the root. So npm run build.prod --env-config staging will run the prod build but set end points, settings, etc for the staging environment.

**Comment by TheDonDope** [comment]
Hi,

@mgechev has a point; from a build technical perspective, a "development" build and a "production" build should be sufficient. But i agree too, any further environment specific environments (e.g. staging, integration <insert-your-fancy-environment-name-here>) could be provided for / configured through JSON config files. IMHO we should rough out a more specific concept for this (in the likes of #913), and then tacle it. Yet, i guess it would be preferable if we first finish up with the works on #913 (respectively https://github.com/mgechev/angular2-seed/pull/926) before we add / enhance on the environment configuration.

**Comment by mgechev** [comment]
@TheDonDope makes sense, lets hold it until #913 is resolved.

**Comment by mgechev** [comment]
Actually looking at my current solution I don't think we should add this to the seed at this point.

@jbouzekri my suggestion for managing configurations for different environments is to add plugin/task [specific config in your `project.config.ts` file](https://github.com/mgechev/angular2-seed/blob/227135ccf18a959ca26aa034cf21d4433569926a/tools/config/seed.config.ts#L385-L408). 

Let you can require this config using [this call](https://github.com/mgechev/angular2-seed/blob/227135ccf18a959ca26aa034cf21d4433569926a/tools/utils/seed/code_change_tools.ts#L10). You can store the entire configuration for all the different environments in JSON files, if you prefer.

Finally in your `config.ts` (or whatever you name it) which is part of your project, you can just insert the correct configuration based on the user choice using a template `<%= CHOSEN_CONFIG %>`. This is [also supported by the seed](https://github.com/mgechev/angular2-seed/blob/227135ccf18a959ca26aa034cf21d4433569926a/src/client/index.html#L43-L49).

**Comment by jbouzekri** [comment]
@mgechev : thanks. Too bad you won't add it to seed. I think it would be useful in a professional job environment to be able to manage this.

I have already implemented my own solution inspired by angular-cli where I deploy in dev or tmp folder an environment.ts file containing the configuration for my current environment target.

**Comment by mgechev** [comment]
Just for the record - the feature is implemented and waiting to be merged here https://github.com/mgechev/angular2-seed/pull/1026.
