### ISSUE TITLE
myUtil function not called

### ISSUE THREAD

**Issue by jbouzekri** [mgechev/angular2-seed#928]
I don't know if I am doing it wrong but I have just copy pasted the example from : https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency and run `npm start` but this function is never called.

Tested on a clean clone of this repository.

Either the documentation is outdated or their is a regression on this functionnality.

```
npm : 3.3.12
node : v5.4.0
```

**Comment by jlberrocal** [comment]
You have to add the library as a dependency, it should work as you are doing it but just in case do the following:
In your seed.config.ts look for `SYSTEM_BUILDER_CONFIG: any `
Into the packages key add the external dependency, it should work

**Comment by jbouzekri** [comment]
The _quick example_ works fine but not the _full example_. I succeeded by doing what you said but it means that the documentation is wrong. Moreover, I am (almost 100%) sure that the `myUtil` function from sample_utils.ts is never called.

**Comment by jlberrocal** [comment]
Well that i'm not sure about that, but apparently yes, the documentation is wrong because if you follow it your project maybe that don't compile for production (at least for me don't work)

**Comment by ludohenin** [comment]
@jbouzekri I confirm that the doc is worng. I'll go and fix that right away. `myUtil` is a sample class meant to be used with the tools like the seed utils. What the doc explains should simply refer to `config.project`.
