### ISSUE TITLE
HomeComponent not initialized if sd-navbar component removed and no Router instance in AppComponent constructor

### ISSUE THREAD

**Issue by cviccaro** [mgechev/angular2-seed#932]
**Steps to reproduce and a minimal demo of the problem**
This may be an angular2 issue and not an angular2-seed issue, but since it's been a couple months since I've worked with angular2 and angular2-seed, I'm not sure.  Since this requires only the removal of 2 lines of markup from a template file, I anticipate a demo is not necessary but steps to reproduce it follow.

I attempted to start fresh and rebuild a previous small SPA using the latest commit of angular2-seed.  First thing I did was remove from app.component.html the first two components, sd-navbar and sd-toolbar, leaving it like so:

app.component.html:
``
<router-outlet></router-outlet>
``

Running ``npm start`` compiles fine, opens the browser, and presents you with a nice white screen.  Implementing ``AfterViewInit`` and ``OnInit`` reveals that the app component and its view are being initialized:

![screen shot 2016-05-27 at 2 11 46 pm](https://cloud.githubusercontent.com/assets/1939251/15617020/fac991ca-2414-11e6-9956-10874eea6319.png)

Odd, I thought, so I tried to hook into the router, which requires of course initializing it in the constructor:

```
export class AppComponent implements OnInit, AfterViewInit {
  constructor(private _router: Router) {
    this._router.changes.subscribe(function() {
      console.log(arguments);
    });
  }
  ngOnInit() {
    console.log('AppComponent initialized', this);
  }
  ngAfterViewInit() {
    console.log('AppComponent view initialized', this);
  }
}
```

Now the HomeComponent route appears!

![screen shot 2016-05-27 at 2 13 53 pm](https://cloud.githubusercontent.com/assets/1939251/15617076/419c3d0a-2415-11e6-87a4-92fae161bf36.png)

Just to be sure, next I removed the subscription to the changes Observable, and it still works.  So it seems simply initializing the router in the constructor fixed the issue.  

And actually, now that I write this, I notice that sd-navbar also initializes the Router.  Could this then be why an empty AppComponent with no sd-navbar in its template and no Router initialized yields a white screen?  It seems so, I just tested (testing as I'm writing, sorry all) it with sd-toolbar in the template and no Router in AppComponent, and lo and behold we get an sd-toolbar but no HomeComponent:
![screen shot 2016-05-27 at 2 21 20 pm](https://cloud.githubusercontent.com/assets/1939251/15617297/505200c2-2416-11e6-8a60-6e11c0e35eef.png)

_What steps should we try in your demo to see the problem?_

1) Install angular2-seed
2) Remove sd-navbar from template
3) Start the app!

**Current behavior**
HomeComponent doesn't appear if there is no Router instance.

**Expected/desired behavior**
Is this expected behavior?  I'm not sure.  It would seem odd to have to initialize a Router into a variable  or class property that you aren't going to use.

**Other information**

**Comment by Green-Cat** [comment]
It's a issue with the new angular router. 
The best current workaround is to insert a blank navigation link to the page like this:
```<a [routerLink]="['/']"></a>```

**Comment by Green-Cat** [comment]
Here's a link to the issue on the angular repo https://github.com/angular/angular/issues/8409

**Comment by cviccaro** [comment]
@Green-Cat OK, great, thanks!  Glad this is known about. Should have searched on angular's issues first, my fault.
