### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by nelkov** [mgechev/angular2-seed#935]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

Running Karma tests

**Steps to reproduce and a minimal demo of the problem**
```
npm test
```
```typescript
import { TestComponentBuilder } from '@angular/compiler/testing';
import { Component } from '@angular/core';
import {
  async,
  beforeEachProviders,
  describe,
  expect,
  inject,
  it
} from '@angular/core/testing';
import { ROUTER_FAKE_PROVIDERS } from '@angular/router/testing';

import { AppIndex } from './app.index';

export function main() {

  describe('App component', () => {

   
  });
}

@Component({
  selector: 'test-cmp',
  template: '<sd-app></sd-app>',
  directives: [AppIndex]
})
class TestComponent {}
```

_What steps should we try in your demo to see the problem?_

**Current behavior**

```
START:
29 05 2016 09:24:53.506:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
29 05 2016 09:24:53.512:INFO [launcher]: Starting browser PhantomJS
29 05 2016 09:24:53.538:INFO [launcher]: Starting browser Chrome
29 05 2016 09:24:53.874:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#ocAmUDkXRdq3Z5PgAAAA with id 90154950
29 05 2016 09:24:54.993:INFO [Chrome 51.0.2704 (Linux 0.0.0)]: Connected on socket /#KX8vHKS6eDrbcxHbAAAB with id 61012701
29 05 2016 09:24:56.116:WARN [web-server]: 404: /base/ng2-bootstrap/ng2-bootstrap.js
PhantomJS 2.1.1 (Linux 0.0.0) ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?e1a1843273d23ee5028aa25121066ce32fecdb29'}
29 05 2016 09:24:56.403:WARN [web-server]: 404: /base/ng2-bootstrap/ng2-bootstrap.js
ERROR: Error{originalErr: Error{}}

The test is not run:

SUMMARY:
✔ 0 tests completed
```
**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
There are no assertions in the test above this is why you get `0 tests completed`.

You're using `ng2-bootstrap` but you haven't configured the correct path to it. Take a look at `test-main.js` for this.

**Comment by nelkov** [comment]
Actually test-main.js is:

// Load our SystemJS configuration.
System.config({
  baseURL: '/base/'
});

System.config({
  defaultJSExtensions: true,
  map: {
    'rxjs': 'node_modules/rxjs',
    '@angular': 'node_modules/@angular',
    'ng2-bootstrap': 'node_modules/ng2-bootstrap',
  },
  packages: {
....

As far as assertions is concerned I've just added this one:

export function main() {
  describe('App component', () => {
    it('should build without a problem',() => {
            expect(true).toEqual(true);
    });
  });
} 

The behavior is the same:

START:
29 05 2016 19:37:06.007:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
29 05 2016 19:37:06.014:INFO [launcher]: Starting browser PhantomJS
29 05 2016 19:37:06.035:INFO [launcher]: Starting browser Chrome
29 05 2016 19:37:06.359:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#I-vBtJKLEyU8cSzOAAAA with id 95915651
29 05 2016 19:37:07.950:INFO [Chrome 51.0.2704 (Linux 0.0.0)]: Connected on socket /#Ikpk-VfndhFZ_l11AAAB with id 83598962
29 05 2016 19:37:08.997:WARN [web-server]: 404: /base/node_modules/ng2-bootstrap/ng2-bootstrap.js
PhantomJS 2.1.1 (Linux 0.0.0) ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?e1a1843273d23ee5028aa25121066ce32fecdb29'}
29 05 2016 19:37:09.455:WARN [web-server]: 404: /base/node_modules/ng2-bootstrap/ng2-bootstrap.js
ERROR: Error{originalErr: Error{}}

Finished in 0.316 secs / 0 secs

SUMMARY:
✔ 0 tests completed

What I am doing wrong?

**Comment by ludohenin** [comment]
@nelkov 
> 29 05 2016 19:37:08.997:WARN [web-server]: 404: /base/node_modules/ng2-bootstrap/ng2-bootstrap.js
PhantomJS 2.1.1 (Linux 0.0.0) ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?

You have errors, so the test are actually not ran.

**Comment by bsanth** [comment]
I am facing the same issue with any third party libraries I have used.

```
[12:52:59] Starting 'karma.start'...

START:
08 06 2016 12:53:01.028:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
08 06 2016 12:53:01.033:INFO [launcher]: Starting browser PhantomJS
08 06 2016 12:53:01.912:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#WNUu_MpjgLYdCfMDAAAA with id 95058771
**08 06 2016 12:53:03.056:WARN [web-server]: 404: /base/ng2-toasty/ng2-toasty.js
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?e1a1843273d23ee5028aa25121066ce32fecdb29'}**

Finished in 0.05 secs / 0 secs

```

Any solutions?

**Comment by cristianmtr** [comment]
I'm also facing the same issue:

```
START:
09 06 2016 11:53:32.097:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
09 06 2016 11:53:32.106:INFO [launcher]: Starting browser PhantomJS
09 06 2016 11:53:33.432:INFO [launcher]: Starting browser Chrome
09 06 2016 11:53:37.318:INFO [Chrome 51.0.2704 (Windows 7 0.0.0)]: Connected on socket /#D6yiPjBLkstlhDpiAAAA with id 20485513
09 06 2016 11:53:37.454:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#T89bD_EvSCuCrjIMAAAB with id 85792821
09 06 2016 11:53:39.545:WARN [web-server]: 404: /base/node_modules/ng2-bootstrap/ng2-bootstrap.js
Chrome 51.0.2704 (Windows 7 0.0.0) ERROR: Error{originalErr: Error{}}
09 06 2016 11:53:41.026:WARN [web-server]: 404: /base/node_modules/ng2-bootstrap/ng2-bootstrap.js
ERROR: Error{stack: null, originalErr: Error{}, line: 821, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?e1a1843273d23ee5028aa25121066ce32fecdb29'}
```

my `test-main.js`:
```
System.config({
  defaultJSExtensions: true,
  map: {
    'rxjs': 'node_modules/rxjs',
    '@angular': 'node_modules/@angular',
    'ng2-bootstrap': 'node_modules/ng2-bootstrap'
  },
```

**Comment by cristianmtr** [comment]
Turns out you also have to include `{pattern: 'node_modules/ng2-bootstrap/**', included: false, watched: false},` in `karma.conf.js`. I guess you have to do this for every dependency.

**Comment by MathijsHoogland** [comment]
@cristianmtr I am having exactly the same problem but adding that line in karma.conf.js didn't solve it for me. Did you adjust anything else?

**Comment by bsanth** [comment]
In test-main:

```
System.config({
  defaultJSExtensions: true,
  paths: {
    'ng2-toasty': 'node_modules/ng2-toasty/ng2-toasty.js',
    'ng2-toasty/*': 'node_modules/ng2-toasty/*.js'
  },
  map: {
    'rxjs': 'node_modules/rxjs',
    '@angular': 'node_modules/@angular'
  },

```

In karma.conf:
 ```
   files: [
     ...
      { pattern: 'node_modules/ng2-toasty/**/*.js', included: false, watched: false },
     ...
     ]
```

**Comment by jiraan** [comment]
Try changing the systemjs expected module format as described [here](http://stackoverflow.com/a/38895070/4240307)
