### ISSUE TITLE
webpack-dev-server.js:1 Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by rdroft** [mgechev/angular2-seed#938]
git clone
cd angular2-webpack-starter
npm install 
npm start

open chrome browser and navigate to localhost:3000

**Current behavior**
there is 2 errors like this
webpack-dev-server.js:1 Uncaught TypeError: Cannot read property 'replace' of null
app.component.ts:66 Initial App State Object

and intial application loaded without images and some tags are not substituted 
like
<% if (webpackConfig.metadata.ENV === 'development') { %> <% } %>

**Expected/desired behavior**
No errors on console

**Other information**
just download version and followed to the instruction

**Comment by ludohenin** [comment]
@rdroft You're in the wrong repo!

**Comment by rdroft** [comment]
right 
sorry
