### ISSUE TITLE
angular2-seed will not run under Windows IIS

### ISSUE THREAD

**Issue by butterfieldcons** [mgechev/angular2-seed#94]
As I expand angular2-seed, I would like to run it under IIS mainly due to CORS and lack of control over server side response headers.

With that said the following paths need the '.' before the 'lib' to load correctly.  Without it a 404 will occur.  An issue or not?  Regardless, good to get this information down in writing.

    <script src=".\lib\traceur-runtime.js?v=0.0.0"></script>

**Comment by butterfieldcons** [comment]
As I expand angular2-seed, I would like to run it under IIS mainly due to CORS and lack of control over server side response headers.

With that said the following paths need the '.' before the 'lib' to load correctly. Without it a 404 will occur. An issue or not? Regardless, good to get this information down in writing.

**Comment by ludohenin** [comment]
@butterfieldcons this is on purpose that lib paths are absolute. This is to support deep linking (which would not work with relative ones).

**Comment by butterfieldcons** [comment]
Hi,
Yes, I can see your point.   Still poses a bit of a quandary for my situation.  Funny IIS doesn't like 'lib' or '/lib'.  It only likes './lib'.  You would think that it would work similar to a command prompt.  For example, I can type 'dir lib' and see the contents of a directory.

**Comment by butterfieldcons** [comment]
If you need those components to use a relative path....

function transformPath(env) {
  var v = '?v=' + getVersion();
  return function (filepath) {
    // var filename = filepath.replace('/' + PATH.dest[env].all, '.') + v;
    // arguments[0] = join(APP_BASE, filename);
    // above lines would make the path absolute; below line makes it relative
    arguments[0] = filepath.replace('/' + PATH.dest[env].all, '.') + v;
    return inject.transform.apply(inject.transform, arguments);
  };
}
