### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by Rademanc** [mgechev/angular2-seed#941]
Hi.
I added bootstrap to a clean install of the seed project as described in the wiki.
A dev build works fine, but a production build gives me these errors:

(index):1 Failed to decode downloaded font: http://localhost:5555/fonts/glyphicons-halflings-regular.woff2
(index):1 OTS parsing error: invalid version tag
(index):1 Failed to decode downloaded font: http://localhost:5555/fonts/glyphicons-halflings-regular.woff
(index):1 OTS parsing error: invalid version tag
(index):1 Failed to decode downloaded font: http://localhost:5555/fonts/glyphicons-halflings-regular.ttf
(index):1 OTS parsing error: invalid version tag

Any ideas?

**Comment by TheDonDope** [comment]
Hi @Rademanc, yes! Have a look here:  https://github.com/mgechev/angular2-seed/wiki/Add-external-fonts

**Comment by Rademanc** [comment]
Thanks a lot.
