### ISSUE TITLE
How to include angular firebase?

### ISSUE THREAD

**Issue by ryanlangton** [mgechev/angular2-seed#944]
I'm having trouble adding angular2 firebase to the seed project.  Instructions to add angular2 firebase here:
https://angularfire2.com/api/

The code that is failing is in my main.ts after adding:

`import {FIREBASE_PROVIDERS, defaultFirebase, AngularFire} from 'angularfire2';`

The seed is pretty confusing with regards to setting up the system config.  Do I need to add something to tools -> config -> seed.config.ts??  Here is the error I'm getting:

`zone.js?1464609483106:101 GET http://localhost:5555/node_modules/_stream_writable/package.json 404 (Not Found)scheduleTask @ zone.js?1464609483106:101ZoneDelegate.scheduleTask @ zone.js?1464609483106:336Zone.scheduleMacroTask @ zone.js?1464609483106:273(anonymous function) @ zone.js?1464609483106:122send @ VM1255:3fetchTextFromURL @ system.src.js?1464609483099:1154(anonymous function) @ system.src.js?1464609483099:1735ZoneAwarePromise @ zone.js?1464609483106:584(anonymous function) @ system.src.js?1464609483099:1734(anonymous function) @ system.src.js?1464609483099:2759(anonymous function) @ system.src.js?1464609483099:3333(anonymous function) @ system.src.js?1464609483099:3600(anonymous function) @ system.src.js?1464609483099:3985(anonymous function) @ system.src.js?1464609483099:4448(anonymous function) @ system.src.js?1464609483099:4700(anonymous function) @ system.src.js?1464609483099:406ZoneDelegate.invoke @ zone.js?1464609483106:323Zone.run @ zone.js?1464609483106:216(anonymous function) @ zone.js?1464609483106:571ZoneDelegate.invokeTask @ zone.js?1464609483106:356Zone.runTask @ zone.js?1464609483106:256drainMicroTaskQueue @ zone.js?1464609483106:474ZoneTask.invoke @ zone.js?1464609483106:426
(index):74 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/_stream_writable/package.json(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ (index):74ZoneDelegate.invoke @ zone.js?1464609483106:323Zone.run @ zone.js?1464609483106:216(anonymous function) @ zone.js?1464609483106:571ZoneDelegate.invokeTask @ zone.js?1464609483106:356Zone.runTask @ zone.js?1464609483106:256drainMicroTaskQueue @ zone.js?1464609483106:474ZoneTask.invoke @ zone.js?1464609483106:426
zone.js?1464609483106:101 GET http://localhost:5555/node_modules/_stream_duplex/package.json 404 (Not Found)scheduleTask @ zone.js?1464609483106:101ZoneDelegate.scheduleTask @ zone.js?1464609483106:336Zone.scheduleMacroTask @ zone.js?1464609483106:273(anonymous function) @ zone.js?1464609483106:122send @ VM1255:3fetchTextFromURL @ system.src.js?1464609483099:1154(anonymous function) @ system.src.js?1464609483099:1735ZoneAwarePromise @ zone.js?1464609483106:584(anonymous function) @ system.src.js?1464609483099:1734(anonymous function) @ system.src.js?1464609483099:2759(anonymous function) @ system.src.js?1464609483099:3333(anonymous function) @ system.src.js?1464609483099:3600(anonymous function) @ system.src.js?1464609483099:3985(anonymous function) @ system.src.js?1464609483099:4448(anonymous function) @ system.src.js?1464609483099:4700(anonymous function) @ system.src.js?1464609483099:406ZoneDelegate.invoke @ zone.js?1464609483106:323Zone.run @ zone.js?1464609483106:216(anonymous function) @ zone.js?1464609483106:571ZoneDelegate.invokeTask @ zone.js?1464609483106:356Zone.runTask @ zone.js?1464609483106:256drainMicroTaskQueue @ zone.js?1464609483106:474ZoneTask.invoke @ zone.js?1464609483106:426
zone.js?1464609483106:101 GET http://localhost:5555/node_modules/http/package.json 404 (Not Found)scheduleTask @ zone.js?1464609483106:101ZoneDelegate.scheduleTask @ zone.js?1464609483106:336Zone.scheduleMacroTask @ zone.js?1464609483106:273(anonymous function) @ zone.js?1464609483106:122send @ VM1255:3fetchTextFromURL @ system.src.js?1464609483099:1154(anonymous function) @ system.src.js?1464609483099:1735ZoneAwarePromise @ zone.js?1464609483106:584(anonymous function) @ system.src.js?1464609483099:1734(anonymous function) @ system.src.js?1464609483099:2759(anonymous function) @ system.src.js?1464609483099:3333(anonymous function) @ system.src.js?1464609483099:3600(anonymous function) @ system.src.js?1464609483099:3985(anonymous function) @ system.src.js?1464609483099:4448(anonymous function) @ system.src.js?1464609483099:4700(anonymous function) @ system.src.js?1464609483099:406ZoneDelegate.invoke @ zone.js?1464609483106:323Zone.run @ zone.js?1464609483106:216(anonymous function) @ zone.js?1464609483106:571ZoneDelegate.invokeTask @ zone.js?1464609483106:356Zone.runTask @ zone.js?1464609483106:256drainMicroTaskQueue @ zone.js?1464609483106:474ZoneTask.invoke @ zone.js?1464609483106:426
zone.js?1464609483106:101 GET http://localhost:5555/node_modules/https/package.json 404 (Not Found)`

**Comment by mgechev** [comment]
Duplication of https://github.com/mgechev/angular2-seed/issues/697
