### ISSUE TITLE
XHR error (404 Not Found) loading http://localhost:5555/app/login.js

### ISSUE THREAD

**Issue by keerthivasan-r** [mgechev/angular2-seed#945]
Hi,
I am migrating from webpack-starter to angular2-seed. I have the application structure as shown below, where every component and services are in their own respective folders.

When i try to do `npm start`, the code gets transpiled into `dist/dev` directory successfully.when it opens in the browser, it loads to the login component as configured in routes for `'/'` by default. it seems to look for `login.js` in the `app `folder. but, there is no such file in it.

![image](https://cloud.githubusercontent.com/assets/11159385/15652173/e44e167a-26a1-11e6-982c-36a82959a33b.png)

I get the following error in the console. 

![image](https://cloud.githubusercontent.com/assets/11159385/15652195/1069b390-26a2-11e6-86ad-c586d267b2ac.png)

Do i have to modify anything in the seed.config.ts to make it work? 

Thanks for your time and help.

**Comment by TheDonDope** [comment]
Hi @keerthivasan-r ! It is a bit hard to give advice without the full source at hand, but i have a hunch.
I see you do have barrel files (`index.ts`) within your modules (`app/login/index.ts`). When you import something from your login module, you certainly have something along the likes of:

`import { LoginComponent } from './login'; `, right? 

You do need to add the `/index` suffix to the import to make it work:

`import { LoginComponent } from './login/index';

Again: This is just a hunch, give it a try and feel free to tell if it helped.

Greetings

Dope

**Comment by keerthivasan-r** [comment]
@TheDonDope Thanks for the help. it definitely fixed the issue. But, may i know why we should explicitly add in the imports `/index`.

**Comment by TheDonDope** [comment]
@keerthivasan-r You are welcome! The reason you have to add `/index` as a suffix to your import is, because without it, just as shown in your errors, the app wouldn't know it has to look for a `index.js` and would rather look for a `login.js`. 
But i think this is a configuration problem that can be solved (allowing barrel imports in the Typescript files to omit the `/index`).

@mgechev Can you maybe shed some light on this?

**Comment by savageqm** [comment]
any updates on why we have to add index to the end of the path? is there a way to end that requirement?

**Comment by fisenkodv** [comment]
@keerthivasan-r did you find a solution with index?
