### ISSUE TITLE
Intellij code errors for name-list.service.ts

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#950]
I just pulled down the latest version of the seed project and Intellij is showing up some errors for name-list.service.ts.  Inside the get function, it says that it can't resolve the items in red shown in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/8858458/15686319/59844584-2735-11e6-991d-67a4a8c582f6.png)

Is anyone else seeing this issue?

**Comment by hank-ehly-mulodo** [comment]
@mpetkov , I have also experienced this error in Webstorm. 
It may be common throughout JetBrains IDE products.

I was able to solve the issue by doing the following:
- Added an `import 'rxjs/Rx';` statement in main.ts
    - (A more specific statement is preferrable)
- Go to File -> Invalidate Caches / Restart and select "Invalidate and Restart"

**Comment by hank-ehly** [comment]
@mpetkov , I have also experienced this error in Webstorm. 
It may be common throughout JetBrains IDE products.

I was able to solve the issue by doing the following:

Added an import 'rxjs/Rx'; statement in main.ts
(A more specific statement is preferrable)
Go to File -> Invalidate Caches / Restart and select "Invalidate and Restart"

**Comment by mpetkov** [comment]
@hank-ehly - I am curious why the old version of the seed which used the alpha angular didn't have this issue?

**Comment by hank-ehly** [comment]
@mpetkov

Unfortunately I've only been using angular 2 -- as well as the seed -- since beta. I would not know if there were an issue during alpha.

Where the above troubleshooting steps any help?

**Comment by mpetkov** [comment]
@hank-ehly - Tried it out and same issue.  I guess I will just learn to ignore the false-positives :)
