### ISSUE TITLE
Unable to build prod with angular2-material

### ISSUE THREAD

**Issue by ryanlangton** [mgechev/angular2-seed#951]
Trying to include angular2-material.  
gulp dev.build works fine and I can see it working locally.
gulp dev.prod results in an error:

`[20:30:43] Finished 'build.bundles' after 2.08 s
[20:30:43] Starting 'build.bundles.app'...
Unhandled rejection Error on fetch for @angular2-material/icon/icon.js at file:///c:/Dev/daybreak/node_modules/@angular2-material/icon/icon.js
        Loading dist/tmp/app/app.component.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'c:\Dev\daybreak\node_modules\@angular2-material\icon\usr\local\google\home\jelbourn\material2\tmp\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\0\components\icon\icon.js.map'
    at Error (native)`

The following is in seed.config.ts:

`  protected SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    packageConfigPaths: [
      `${this.APP_BASE}node_modules/*/package.json`,
      `${this.APP_BASE}node_modules/**/package.json`,
      `${this.APP_BASE}node_modules/@angular/*/package.json`,
      `${this.APP_BASE}node_modules/@angular2-material/*/package.json`
    ],
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '@angular2-material/icon': `${this.APP_BASE}node_modules/@angular2-material/icon/icon.js`,
      'rxjs/*': `${this.APP_BASE}rxjs/*`,
      'firebase': '/node_modules/firebase/lib/firebase-web',
      'app/*': `/app/*`,
      '*': `${this.APP_BASE}node_modules/*`
    },`

`  SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    packageConfigPaths: [
      join(this.PROJECT_ROOT, 'node_modules', '*', 'package.json'),
      join(this.PROJECT_ROOT, 'node_modules', '@angular', '*', 'package.json'),
      join(this.PROJECT_ROOT, 'node_modules', '@angular2-material', '*', 'package.json')
    ],`

That's all I have added for angular2-material.

**Comment by ludohenin** [comment]
> ENOENT: no such file or directory, open 'c:\Dev\daybreak\node_modules\@angular2-material\icon\usr\local\google\home\jelbourn\material2\tmp\broccoli_type_script_compiler-input_base_path-IydvmmBU.tmp\0\components\icon\icon.js.map'

I suppose this is an upstream issue, source map path looks ... incorrect!

**Comment by ryanlangton** [comment]
Yes I thought so too, but why would it only occur on the prod build?  Any suggests for workarounds?

**Comment by lzoubek** [comment]
I had the same issue with ng2-toastr. I ended up in forking their project, [fixing](https://github.com/PointInside/ng2-toastr/pull/24) it and referring to my fork in my package.json.  I'd be happy for better workaround as well

**Comment by mgechev** [comment]
@d3viant0ne did a demo with the seed and material2 so most likely this is not issue related to the seed.

**Comment by andvasp** [comment]
Hi @ryanlangton /@mgechev /@d3viant0ne.

I have the same problem. Npm start works perfectly but run build.prod does not. I've just forked the  material2 seed from @d3viant0ne but we have the same problem. I created the issue https://github.com/DeviantJS/angular2-seed-material2/issues/40 on his repository.

Material2 is going to be largely used. Would be good the have it running perfectly in the seed.

Thanks guys!

**Comment by ravivit9** [comment]
I am also facing the same issue.
`[11:02:33] Error on fetch for @angular/material/icon.js at file:///Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js
        Loading dist/tmp/app/app.module.ngfactory.js
        Loading dist/tmp/app/main-prod.js
        Error: ENOENT: no such file or directory, open '/Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js'
    at Error (native)
[11:02:33] 'build.prod.aot' errored after 21 s
[11:02:33] Error in plugin 'run-sequence(build.bundles.app.aot)'
Message:
    Error on fetch for @angular/material/icon.js at file:///Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js
        Loading dist/tmp/app/app.module.ngfactory.js
        Loading dist/tmp/app/main-prod.js
        ENOENT: no such file or directory, open '/Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js'
Stack:
Error on fetch for @angular/material/icon.js at file:///Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js
        Loading dist/tmp/app/app.module.ngfactory.js
        Loading dist/tmp/app/main-prod.js
        Error: ENOENT: no such file or directory, open '/Users/USER-A/dev/PROJ-NAME/node_modules/@angular/material/icon.js'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 build.prod.aot: `gulp build.prod.aot --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@1.0.0 build.prod.aot script.
`

**Comment by Vomitory1** [comment]
I am also getting a error message 


[15:09:56] Error in plugin 'run-sequence(build.bundles.app.aot)'
Message:
    SyntaxError: Unexpected token: name (OficinasService)[object Object]app.jsfalse[object Object]
Stack:
Error: SyntaxError: Unexpected token: name (OficinasService)[object Object]app.jsfalse[object Object]
    at minify (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\systemjs-builder\lib\output.js:82:11)
    at exports.writeOutputs (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\systemjs-builder\lib\output.js:157:14)
    at C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\systemjs-builder\lib\builder.js:807:14
    at tryCatcher (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Usuario\Documents\groupcenter-mrc-frontend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 build.dev.aot: `gulp build.prod.aot --color --env-config dev --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 build.dev.aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2017-12-29T20_09_56_864Z-debug.log
