### ISSUE TITLE
How do I host dev/prod on IIS?

### ISSUE THREAD

**Issue by shoebsd** [mgechev/angular2-seed#953]
**Steps to reproduce and a minimal demo of the problem**

1. run npm install
2. run npm serve.dev
3. **This works locally**, also this creates a dev directory in the dist folder as in the following snapshot: 
![image](https://cloud.githubusercontent.com/assets/7359157/15741096/b178b526-28d5-11e6-98f7-bb5ca19caf1b.png)
4. Go to IIS by pressing [Windows + R] and typing 'inetmgr'
6. Right click Default Web Site and select 'Add application'
7. Enter application name and point the virtual directory to the dist/dev folder as follows : 
![image](https://cloud.githubusercontent.com/assets/7359157/15741240/6b8dbfc4-28d6-11e6-9490-af315c857bcb.png)
8. Nothing shows except the word 'Loading...' as the following snapshot : 
![image](https://cloud.githubusercontent.com/assets/7359157/15741309/b5ae6130-28d6-11e6-8f4d-9dde1d0f6efc.png)

9. I ran npm run serve.prod just now and I see the following 
![image](https://cloud.githubusercontent.com/assets/7359157/15741566/ee46c2de-28d7-11e6-97eb-4c377a17c2e7.png)

**Current behavior**
I see the word 'Loading...' on the page, which means angular dependencies are not being loaded. 

**Expected/desired behavior**
The website should render the way it does on npm serve.dev

**Comment by TheDonDope** [comment]
Hi @shoebsd,
can you please provide more information on your current behaviour? (Stack trace, error log, screenshots etc.)

**Comment by shoebsd** [comment]
Hi, 

I was able to run the project locally, but I couldn't host it on IIS server.

**Comment by TheDonDope** [comment]
Hi @shoebsd,
yes, i could read that from your original posting:
>Current behavior
>I get internal server error when i start the website 

But this information is too generic to be able to help. Therefore i need more **specific** information, for example screenshots, stack traces of the error, log file excerpts.

**Comment by shoebsd** [comment]
Hi Don, 

I have updated the question

**Comment by lzoubek** [comment]
@shoebsd serving dev files from IIS does not make sense ( as serve.dev already starts up local web server for you) and won't work (see [seed.config.ts](https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts#L412)). Not sure about serving prod files (I have not tried) but it looks like your build fails - but I cannot see the reason in your console screenshot

**Comment by shoebsd31** [comment]
Hi Izoubek, 

This is shoeb here. I am developing a web application in angular2. The idea is to get a dist/build version created out of my angular2  application. Ideally with prod build I want a minified js, css and html file. I want to host this application on IIS server.

**Comment by TheDonDope** [comment]
Hi @shoebsd & @shoebsd31:
Try the following:

1. `$ npm build.prod`
2. Create your IIS server and point it to `dist/prod`

**Comment by shoebsd31** [comment]
Hi Don,

This is what I did exactly. It doesn't work

**Comment by mgechev** [comment]
Make sure you use "npm run build.prod", not "serve.prod".

Also, make sure you have valid configuration of the production build. For support requests we can move the discussion to gitter.

**Comment by mcgrat88** [comment]
I am running into this exact issue and can't seem to get around it. Wondering what the solution to this was?

**Comment by junj0619** [comment]
go to your production open index.html. Change your  <base href="/"> to <base href="/a2seed/">

**Comment by MateenKadwaikar** [comment]
Any update on it ? I am too facing the same issue.

**Comment by mhlulani** [comment]
@junj0619 I've resolved it by doing as you suggested, but whats worse is that you need to do that for ALL references of you resources (css, js and images absolute paths) too.
Any reference in the main index.html should have a /a2Seed prefix to it.

I think there is an automated way of doing this as opposed to changing it manually

**Comment by phani257** [comment]
@mhlulani  I tried the way you suggested. It didn't work

**Comment by ducmaxime** [comment]
I have an error on IIS.

1. npm run build.prod
2. I copy dist/prod content on my IIS application folder (C:\inetpub\wwwroot\myapp)

(All off my css, js and other are founded correctly)

but I have this error : 
EXCEPTION: Uncaught (in promise): TypeError: System.import is not a function

Any idea ?

**Comment by kevin192291** [comment]
I am getting this as well, I wish there could be a fix for it, I have yet to find one though.

**Comment by ducmaxime** [comment]
I have a solution. You have to change the app base URL with the name of your app. By default it is / . You have to change this for /your-app-name (your-app-name is the name of your ISS application name) . And maybe you have to add a web.config file for authorize special content like .woff , woff2.

**Comment by kevin192291** [comment]
No, I have done this(as other posts have recommended) it does not work :(
I have even tried to place it at the root so there is no application name needed. All fails,
Uncaught ReferenceError: System is not defined
    at system-config.js:1
I wish I could get this to temporarily work while I move to CLI

**Comment by ankurgupta1401** [comment]
I found a nice and detailed explanation of deploying angular 2 app in IIS at this [link](http://getgoingit.blogspot.in/2018/02/publishing-and-deploying-angular-4.html)
