### ISSUE TITLE
ENABLE_SCSS. build.prod doesn't generate main.css file

### ISSUE THREAD

**Issue by suren1525** [mgechev/angular2-seed#954]
Hello
I have enabled scss and renamed all css files to scss. 
build.dev works fine, but build.prod doesn't generate and inject main.css file.
Thanks

**Comment by TheDonDope** [comment]
Hi @suren1525 !

Did you rename your `main.css` file in `src/client/css/main.css` to `main.scss` and move that file to `src/client/assets/main.scss` ?

**Comment by TheDonDope** [comment]
I can reproduce it with latest `master`:

```bash
$ npm run build.prod
[...]
[19:06:27] Starting 'build.index.prod'...
[19:06:27] gulp-inject 2 files into index.html.
[19:06:27] gulp-inject Nothing to inject into index.html.
[19:06:27] Finished 'build.index.prod' after 81 ms
[...]
```

I think `build.index.prod.ts` needs an update too: https://github.com/mgechev/angular2-seed/blob/master/tools/tasks/seed/build.index.prod.ts#L53

@hank-ehly do you have a suggestion how to fix this?

**Comment by hank-ehly** [comment]
@TheDonDope 
Thank you for the information. I will get on this right away.

**Comment by hank-ehly** [comment]
@suren1525 / @TheDonDope 

It seems that adding the following line to the project.config.ts file does **not** override the seed.config.ts value. I verified that this results in the main.css file not being injected during `npm run build.prod`

    // project.config.ts
    constructor() {
        ...
        this.ENABLE_SCSS = true;

I am able to output main.css by doing either of the following:
- run `npm run build.prod -- --scss`
- modify the seed.config.ts ENABLE_SCSS value directly

@suren1525, I apologize for the inconvenience. Please try the above two methods while I troubleshoot the project.config issue. Or, if you have already tried the above, please let me know and I will take a closer look.

Hank

**Comment by suren1525** [comment]
Thank you @hank-ehly! 
Setting ENABLE_SCSS = true in seed.config.ts solves the problem.
I look forward to the solution of the project.config issue.

**Comment by HendrikZero72** [comment]
@hank-ehly The problem is more generic, it involves all constants in the `SeedConfig` class in the `seed.config.ts` file that are built up dynamically. Some examples:
```javascript
  /**
   * The folder of the applications asset files.
   * @type {string}
   */
  ASSETS_SRC = `${this.APP_SRC}/assets`;

  /**
   * The folder of the applications css files.
   * @type {string}
   */
  CSS_SRC = `${this.APP_SRC}/scss`;
```

The value of `this.APP_SRC` is in the context of the `SeedConfig` class. Perhaps you could reverse the logic, i.e. make the ProjectConfig constants available to the SeedConfig and then do it something like this:
```javascript
  /**
   * The folder of the applications asset files.
   * @type {string}
   */
  ASSETS_SRC = `${ProjectConfig.APP_SRC || this.APP_SRC}/assets`;

  /**
   * The folder of the applications css files.
   * @type {string}
   */
  CSS_SRC = `${ProjectConfig.APP_SRC || this.APP_SRC}/scss`;
```
That would solve the current issue anyway. Perhaps it would cause others in return ;-)

I hope my observation helps

**Comment by hank-ehly** [comment]
@HendrikZero72 

Thank you for your comment.

Yes, this seems to be a larger issue -- one which has been mentioned in numerous other issues from what I've gathered. Currently issue #823 seems to be where the discussion is taking place.
