### ISSUE TITLE
HomeComponent not rendered

### ISSUE THREAD

**Issue by zeeshanjan82** [mgechev/angular2-seed#958]
I will try to explain as much as I can about the problem. I have cloned the repo and started to integrate my logic inside the repository with only one component i.e HomeComponent which is assigned on the default route. When I load my application using command 'gulp serve.dev' I am able to see the header and footer which are part of the app.component but home component is not visible it seems its not loaded. There is no error in the console but still the home component's html is not visible. I have also used <router-outlet></router-outlet> inside app.component.html but nothing gets loaded in it

**Comment by mgechev** [comment]
Make sure you're including the non-rendered components in the `directives` property within the `@Component` decorator.

**Comment by zeeshanjan82** [comment]
@mgechev I am using HomeComponent in the Route and I have declared the route as this
`````js
@Routes([
    { path: '/', component: HomeComponent}
])
```````

**Comment by mgechev** [comment]
This is the configuration of the seed itself, and it seems to work.

What is your implementation of `HomeComponent`?

**Comment by zeeshanjan82** [comment]
````js
import {Component} from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'sd-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
export class HomeComponent{
  constructor(){
   //OnLoad();
   console.log('Loaded');
  }
}
````

**Comment by zeeshanjan82** [comment]
Loaded message is not printed in console.

**Comment by mgechev** [comment]
What's the content of `home.component.html`?

**Comment by zeeshanjan82** [comment]
its all html with bootstrap css applied, would you like me to post that as well?

**Comment by zeeshanjan82** [comment]
I was previously using normal angular2 app before moving to the seed project there the html was working

**Comment by mgechev** [comment]
Most likely the issue is not related to the seed itself, since as you said it was initially working. This is how the `AppComponent` should look like:

```ts
@Component({
  moduleId: module.id,
  selector: 'sd-app',
  viewProviders: [NameListService, HTTP_PROVIDERS],
  templateUrl: 'app.component.html',
  directives: [ROUTER_DIRECTIVES, NavbarComponent, ToolbarComponent]
})
@Routes([
  {
    path: '/',
    component: HomeComponent
  },
  {
    path: '/about',
    component: AboutComponent
  }
])
export class AppComponent {}
```

Most likely you're missing declaration of directives that you're using somewhere. For further reading I'd recommend you the [dev guide here](https://angular.io).

**Comment by zeeshanjan82** [comment]
I have been able to reproduce the issue in the seed. If I remove the Navbar component from the html of app component along with toolbar component then the home component is not rendered.
