### ISSUE TITLE
Error when using custom router outlet

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#964]
NOTE: using router-deprecated!

**Steps to reproduce and a minimal demo of the problem**

Extend RouterOutlet
Include it as a directive for a component.

**Current behavior**

When the application loads, I get a ```No provider for String!```

**Expected/desired behavior**

The router outlet should be used.

**Comment by mgechev** [comment]
This doesn't seems like an issue in the seed project.

For support requests you can start a discussion in the gitter channel of the project.

**Comment by sfabriece** [comment]
Given that the angular version hasn't changed only the tools. I have reason to believe that it's the tools. Let me ask on gitter and see what happens.

**Comment by mgechev** [comment]
The last version of Angular introduced a new router, this is the reason now we have `@angular/router` and `@angular/router-deprecated`. Mismatch in providers is the case of your issue, this is why I redirected your support request to the appropriate channel :-).

**Comment by sfabriece** [comment]
Found out that there was a missing @Attribute() annotation. That caused the problems.
