### ISSUE TITLE
Navbar Home tab always keeps active.

### ISSUE THREAD

**Issue by luozt** [mgechev/angular2-seed#965]
Clicking switch the navbar tabs will not change Home tab style. It always keeps active...

![image](https://cloud.githubusercontent.com/assets/6123916/15803494/07b4c1ac-2b13-11e6-8120-432beac0b78b.png)

Hope it can be fixed soon.

**Comment by mgechev** [comment]
I'll take this one today,

**Comment by mgechev** [comment]
It's an upstream issue https://github.com/angular/angular/issues/8397
