### ISSUE TITLE
Force case sensitive loading of dependencies on Windows.

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#966]
On windows, adding a dependency using the config file is not case sensitive. It caused an error when runing on a linux CI.

Is it possible to force case sensitivity?

**Comment by mgechev** [comment]
I believe it is responsibility of developer to make sure she providers correct paths to the resources.

// cc @ludohenin @TheDonDope @d3viant0ne

**Comment by TheDonDope** [comment]
I agree, i see this as a developers responsibility too.

**Comment by sfabriece** [comment]
Thanks for the response.
