### ISSUE TITLE
Wiki - page empty / broken for Pug(Jade)

### ISSUE THREAD

**Issue by ganySA** [mgechev/angular2-seed#967]
The wiki for Pug (Jade) is broken - any chance someone could provide the instructions for how to implement PugJs?

**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
I removed the page. Most likely someone had an intention to add further information but in the end didn't.
