### ISSUE TITLE
Adding external fonts in production builds fails

### ISSUE THREAD

**Issue by MathijsHoogland** [mgechev/angular2-seed#969]
Hi guys, I think the documentation on how to add external fonts to the seed is outdated. I did the following to add the font (basically the same as mentioned in the documentation):

 In `tools/config/project.config.ts`:
```
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');
  FONTS_DEST = `${this.APP_DEST}/fonts`;
  FONTS_SRC = [
      'node_modules/font-awesome/fonts/**',
      'node_modules/bootstrap/dist/fonts/**'
  ];
....
```

Added the following task:
  ```ts
import * as gulp from 'gulp';
import {FONTS_SRC, FONTS_DEST} from '../../config';

export = () => {
  return gulp.src(FONTS_SRC)
        .pipe(gulp.dest(FONTS_DEST));
}
  ```

And added this task at the correct locations in my gulpfile.

**Current behavior**

When trying to view my application, the font's aren't loaded and I see the following warnings in my terminal:
<img width="984" alt="screen shot 2016-06-06 at 08 35 16" src="https://cloud.githubusercontent.com/assets/7372934/15813752/b6f42280-2bc1-11e6-9c43-3db0f90931d8.png">

**Expected/desired behavior**

I would expect the fonts to load correctly.

**Other information**
I think that something is going wrong when all CSS files are combined together, not sure however. Do you guys have the same issue?

**Comment by csreddy** [comment]
I have the exact same issue with prod build

**Comment by Sjiep** [comment]
I actually got this working last week. It seems like your reference to the font-awesome font files is incorrect. 

First of all, can you verify that the build has copied the files to `dist/prod/fonts`.

Then when using font-awesome, you have to reference it correctly, depending on what method you use CSS or Sass/Less. It seems to me that this is where it's going wrong. Which method are you using?

**Comment by TheDonDope** [comment]
Hi @MathijsHoogland! As @Sjiep mentioned: Depending on which stylesheet mechanism you are using you need to reference the corresponding files correctly. 

In a personal project (based on the seed) i also use font-awesome in conjunction with sass.
Therefore in my `src/client/css/main.scss` i have the following line:

```scss
@import 'font-awesome/scss/font-awesome';
```

**Comment by MathijsHoogland** [comment]
@Sjiep thanks for your help, I am using CSS. The fonts are correctly loaded, and the reference also is correct when I load the development environment. This is what it looks like when I look at my main.css file:
    src: url(../../../font-awesome/fonts/fontawesome-webfont.eot?v=4.6.3);

This obviously should be src: url(../fonts/fontawesome-webfont.eot?v=4.6.3), and in the source file (font-awesome.css) this is also how it looks. Somehow this is changed during the building process of production. Do you know how I can fix this?

**Comment by Sjiep** [comment]
In my project I've used the Sass version, so I don't have any experience with the CSS version. How are you including the `font-awesome.css` into your project? 

To me it sounds a bit strange that a source url inside a css file is changed during the build.

**Comment by MathijsHoogland** [comment]
In my `project.config.ts` file I added font-awesome with the following line:

   let additional_deps: InjectableDependency[] = [
      {src: 'font-awesome/css/font-awesome.min.css', inject: true},
    ];

Inside this file, there are references to the fonts (that all work). It is after all stylesheets are converted to `main.css` that the reference isn't correct anymore. 

>

**Comment by TheDonDope** [comment]
@MathijsHoogland have a look here: https://github.com/mgechev/angular2-seed/issues/850#issuecomment-218736860

**Comment by mpetkov** [comment]
I also have the same issue with the new seed, has there been a solution on how to correctly use a css font in prod?  Jus tlike mentioned above, the prod build for some reason changes the font url inside the css file.  Currently the only way I can solve it is by create a seperate build.fonts task for dev and prod.

**Comment by csreddy** [comment]
Yes - in `build.html_css.ts` replace this line in `processExternalCss()`
 `.pipe(isProd ? plugins.concatCss(CSS_PROD_BUNDLE) : plugins.util.noop())` with 
`.pipe(isProd ? plugins.concatCss(CSS_PROD_BUNDLE,{rebaseUrls:false}) : plugins.util.noop())` 

this worked for me, this is same as what was suggested the good folks in the comments above

**Comment by mpetkov** [comment]
Thanks @csreddy, since I am using a newever version of the seed, I used your answer and did the following:
In my project.config.ts file, I added this line at the end of the constructor function:
`this.mergeObject( this.PLUGIN_CONFIGS['gulp-concat-css'], { rebaseUrls: false } );`

**Comment by mthor** [comment]
@csreddy     Thanks for the post!! this was killing us trying to fix for a release of our beta!  thanks to all who helped out, this seed starter has been great
