### ISSUE TITLE
Protractor tests pass locally, but not in Travis CI

### ISSUE THREAD

**Issue by mraible** [mgechev/angular2-seed#970]
**Steps to reproduce and a minimal demo of the problem**

I created a simple angular2 application using angular2-seed as a starting point. You can find it at https://github.com/mraible/angular2-tutorial. As part of creating this project, I wrote a tutorial on testing that you can find [here](https://github.com/mraible/angular2-tutorial/blob/master/TESTING.adoc). 

To reproduce the problem, fork my project and enable your repo in Travis CI. Then start a build. You should see an error like the following:

https://travis-ci.org/mraible/angular2-tutorial/jobs/135517549#L1190

**Current behavior**

Running `npm run webdriver-start`, `npm run serve.e2e` and `npm run e2e` passes locally, but [fails in Travis CI](https://travis-ci.org/mraible/angular2-tutorial/jobs/135517549#L1190). I believe this is because directly accessing URLs doesn't work in Travis.  For example, here's one of the tests:

```js
describe('Search', () => {

  beforeEach(() => {
    browser.get('/search');
  });

  it('should have an input and search button', () => {
    expect(element(by.css('sd-app sd-search form input')).isPresent()).toEqual(true);
    expect(element(by.css('sd-app sd-search form button')).isPresent()).toEqual(true);
  });

  it('should allow searching', () => {
    let searchButton = element(by.css('button'));
    let searchBox = element(by.css('input'));
    searchBox.sendKeys('M');
    searchButton.click().then(() => {
      // doesn't work as expected - results in 0
      //expect(element.all(by.repeater('person of searchResults')).count()).toEqual(3);
      var list = element.all(by.css('sd-search table tbody tr'));
      expect(list.count()).toBe(3);
    });
  });
});
```

Do my tests need to be re-written so they access the component by clicking on a link from the homepage, or is it possible to make this work in Travis CI like it does locally?

**Comment by mgechev** [comment]
@Shyam-Chen would you take a look?

**Comment by mraible** [comment]
I was able to workaround this issue by [navigating to each component](https://github.com/mraible/angular2-tutorial/commit/11fa5220d5264abfdc675323ca526e228e5204a5). However, I'd would love know if it's possible to just tweak some configuration to make this work.

**Comment by Shyam-Chen** [comment]
Hi @mraible 

```ts
browser.get('/search');  // There can not be obtained directly URLs
```

**Comment by harmandeol** [comment]
I fixed it by https://github.com/harmandeol/moviesearch/commit/ffe0e550f298235ed35993e05e5cca9b27d179ef

Ideally all the routing should be at one place.

**Comment by Shyam-Chen** [comment]
@harmandeol pull request?

**Comment by GonzaloCabanasYuste** [comment]
Hello! I used to have the same problem while trying to implement the tests on Travis CI.

I figured out that if you give some time to every command, seems to be more than enough to pass Travis, like this example:

export function loginQAWeb(user, password, redirectURL) {

    browser.waitForAngularEnabled(false);
    browser.get(redirectURL)
        .then(() => browser.sleep(1000))
        .then(() => browser.wait(until.presenceOf(element(by.id("loginButton"))), timeout, "timeoutmessage"));

    // Logs in applying environment credentials
    element(by.id("loginButton")).click();
    element(by.id("username")).sendKeys(user);
    element(by.id("password")).sendKeys(password);
    element(by.tagName("button")).click()
        .then(() => browser.sleep(3000))
        .then(() => browser.refresh())
        .then(() => browser.wait(until.presenceOf(element(by.id("headerAdminMenuItem"))), timeout, timeoutmessage))
}

My method would consist in givin 1 second with browser.sleep, and wait for the element to appear with browser.wait() (to run the tests synchronous)
