### ISSUE TITLE
Enable SCSS #952 Integration is not injecting the npm dependencies

### ISSUE THREAD

**Issue by gvsdan** [mgechev/angular2-seed#971]
i'm trying to use the scss  #952  integration in development mode is working fine but when i use the prod mode is not creating the '.css' for all the npm dependencies injected in the 'project.config.ts'

**Comment by hank-ehly** [comment]
@gvsdan, thank you for your comment. I'll take a look.

**Comment by gvsdan** [comment]
@hank-ehly Thanks to you for making the sass support

**Comment by TheDonDope** [comment]
Fixed by #976, thank you very much Hank!

**Comment by gvsdan** [comment]
@hank-ehly Everything is working fine but now the external dependencies in production are broken.
