### ISSUE TITLE
importing rxjs operator timeInterval produce error "unexpected token <" in the browser

### ISSUE THREAD

**Issue by elpddev** [mgechev/angular2-seed#973]
This is related ti #784 I think.

I tried:
```
import 'rxjs/add/operator/timeInterval';  
```

Which gives the following error in the browser:

```
(index):89 Error: SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:5555/app/shared/scroll-tracker/scroll-tracker.service.js:13:1)
	    at eval (http://localhost:5555/app/shared/scroll-tracker/scroll-tracker.service.js:36:4)
	    at eval (http://localhost:5555/app/shared/scroll-tracker/scroll-tracker.service.js:37:3)
	Evaluating http://localhost:5555/node_modules/rxjs/add/operator/timeInterval
	Evaluating http://localhost:5555/app/shared/scroll-tracker/scroll-tracker.service.js
	Evaluating http://localhost:5555/app/app.component.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"
```

1. When I try other operators, it works.
2. The timeInterval files exists in the node module rxjs add folder

I temporarily fixed the problem by commenting out the rxjs path and packages in the seed file as was mantioned in the related issue and it works. But I don't think this is a solution. 
```
paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      //'rxjs/*': `${this.APP_BASE}node_modules/rxjs/*`,
      'app/*': `/app/*`,       
      '*': `${this.APP_BASE}node_modules/*`
    },
   packages: {                 
      //rxjs: { defaultExtension: false }
    }
```

**Comment by mgechev** [comment]
You have entered a wrong path to the operator. The browser (by default) loads `index.html` which is executed as JavaScript by SystemJS and you get this error of unexpected token.

Make sure your import is correct.

**Comment by nosachamos** [comment]
@mgechev path as indeed correct, and the file exists. I'm not sure why one must comment out those configs, but without that only certain operators can be actually added (such has map, filter, etc). You can try on any project - `timeInterval` cannot be added until these configs are commented out even though the file is there and the extension is .js just like the other operator patch files.

**Comment by nosachamos** [comment]
It turns out the fix is to change the default extension for the rxjs package to `js`:

```
    packages: {
      rxjs: { defaultExtension: 'js' }
    }
```

Hope this helps someone else.

**Comment by mgechev** [comment]
@nosachamos nice finding! Do you want to open a PR with the change?

**Comment by nosachamos** [comment]
@mgechev absolutely, on the way!
