### ISSUE TITLE
Some RxJS operators are missing from the bundle the seed uses

### ISSUE THREAD

**Issue by eppsilon** [mgechev/angular2-seed#977]
**To Reproduce:**

With a clean copy of the seed, replace `home.component.ts` with this:

```ts
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/pairwise';

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'sd-home',
  template: ''
})
export class HomeComponent implements OnInit {
  scores = Observable.from([43, 44, 45, 46]).pairwise();

  ngOnInit() {
    this.scores.subscribe(scores => {
      console.log('scores', scores);
    });
  }
}
```

Run the seed via `npm start`. The page will not load and the console will have an error like ` SyntaxError: Unexpected token <`.

Now remove/disable `import 'rxjs/add/operator/pairwise';` and the `pairwise()` call. The page loads fine and you see the numbers printed to the console.

The `pairwise` operator exists in RxJS 5 beta 6 - [here's the source code](https://github.com/ReactiveX/rxjs/blob/5.0.0-beta.6/src/add/operator/pairwise.ts).

I think others have been running into this problem too:

- #973: `timeInterval` can't be loaded ([it's in beta 6](https://github.com/ReactiveX/rxjs/blob/5.0.0-beta.6/src/add/operator/timeInterval.ts))
- #784: `exhaustMap` can't be loaded ([also in beta 6](https://github.com/ReactiveX/rxjs/blob/5.0.0-beta.6/src/add/operator/exhaustMap.ts)]

***

I dropped in RxJS 5 beta 8 and the seed ran and loaded the `pairwise` operator as expected.

Sometime after beta 6, it looks like the RxJS developers combined a few versions (plain Rx, Rx.KitchenSink, Rx.DOM) into one - I think that's why the operators are available in beta 8.

Since Angular requires beta 6, perhaps we could reference a different bundle that includes everything?

**Comment by mgechev** [comment]
We're coupled to beta.6 as being peer dependency of Angular 2 rc.1.

**Comment by mgechev** [comment]
Lets wait until rc.2 is out. The version of the peer dependency most likely will be changed.

**Comment by mgechev** [comment]
I suggest to close this issue for now since it is not directly related to the seed.
