### ISSUE TITLE
Referencing shared folder in imports

### ISSUE THREAD

**Issue by davidgfolch** [mgechev/angular2-seed#978]
Hi all,

I'm trying to put a path or map to reference the shared folder directly in the imports, but with no success.

Example: instead of using imports like this:

`import { NameListService } from '../shared/index';`

It would be very interesting to use them like that:

`import { NameListService } from 'shared/index';`

This way you can move folders arround with no pain, thats only an example on shared folder but my real target would be an alias to use in imports for each subfolder in shared folder: components, pojos, services, etc..

Is that really not supported in the seed or I'm misunderstanding how it works.  I've tried to modify in project.cofig.ts and/or seed.config.ts adding path and/or map but don't work, I'm alwais getting:

src\client\app\contracts\list.ts(8,31): error TS2307: **Cannot find module** 'shared/...'.

**Comment by mgechev** [comment]
You need to use "shared/index". We don't support node module resolution because of compatibility with SystemJS.

**Comment by davidgfolch** [comment]
Hi and thanks for answer.

There is not an alternative to module resolution to get something like this working?



In my project I have some generic objects (services/components/pojos):

app/contracts/list.ts

app/shared/components/Messages.ts
app/shared/components/Pagination.ts
app/shared/components/TableHeader.ts
...
app/shared/pojos/Message.ts
...
app/shared/rc/impl1/index.ts
app/shared/rc/impl1/RestClientService.ts
app/shared/rc/impl1/RestClientConfig.ts
...

Then until now I was using:

```
import { ContractService, RestClientConstants } from '../shared/rc/impl1/index';
import { Pagination } from '../shared/pojos/Pagination';
import { PaginationComponent } from '../shared/components/Pagination';
import { TableHeaderComponent } from '../shared/components/TableHeader';
import { MessagesComponent } from '../shared/components/Messages';
import { Message } from '../shared/pojos/Message';
import { RemoveHostTag } from '../shared/components/RemoveHostTag';
```

But thats not a good strategy, neither for refactor or modulation, we should use something like that:

```
import { ContractService, RestClientConstants } from '**RestClient**';
import { Pagination } from '**pojos**/Pagination';
import { PaginationComponent } from '**components**/Pagination';
import { TableHeaderComponent } from '**components**/TableHeader';
import { MessagesComponent } from '**components**/Messages';
import { Message } from '**pojos**/Message';
import { RemoveHostTag } from '**components**/RemoveHostTag';
```

¿And have a global file to config this paths? :)

```
"**components**/*": "app/shared/components/*"
"**RestClient**": "app/shared/rc/impl1/index"
"**pojos**": "app/shared/pojos/*"
```

**Comment by mgechev** [comment]
Yes, having such configuration in SystemJS is possible.

**Comment by davidgfolch** [comment]
Yes that works (but doesn't integrate with TS compiler, that give errors on paths like 'restClient/...'):
```
System.config({
      paths: {
        'restClient/*': 'app/shared/services/restClient/*'
      }
    });
```

But if I put it in seed.config.ts or project.config.ts doesn't work (is going to look for localhost:5555/node_modules/restClient/package.json):
      'restClient/*': `app/shared/services/restClient/*`

**Comment by mgechev** [comment]
Take a look at the Angular CLI. They use barrels in their SystemJS config.
