### ISSUE TITLE
Pug / Jade support.

### ISSUE THREAD

**Issue by ganySA** [mgechev/angular2-seed#980]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

Pug / Jade support in build process :)

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by mgechev** [comment]
Thanks for the suggestion! I are planning to keep the seed project minimalistic, adding jade doesn't seem like a good fit at this point. On the other hand, we can add a wiki page on how this can be achieved.

**Comment by ludohenin** [comment]
@ganySA you can have a look at the following
https://github.com/ludohenin/gulp-inline-ng2-template#processors-configuration
https://github.com/ludohenin/gulp-inline-ng2-template/blob/master/test/test.js#L69
