### ISSUE TITLE
Using Mocha and Chai instead of Jasmine is not working

### ISSUE THREAD

**Issue by ghudeihed** [mgechev/angular2-seed#982]
I installed karma-mocha and karma-chai and modified karma.config.js as the following link: 

https://github.com/ghudeihed/angular-seed-with-mocha-chai

I added typings for both mocha and chai in the typings.json file and removed the jasmine typings. 

now I run the gulp test task I get 0 test run and no code coverage

anybody can tell me what am I doing wrong here, I have been trying to get it to work all day but no luck getting any result.

![image](https://cloud.githubusercontent.com/assets/169615/15984450/fdac7e7c-2f7f-11e6-80e2-3e2903cb8c53.png)

**Comment by mgechev** [comment]
@ghudeihed we don't officially support mocha and chai, although with proper configuration you can make it work. For support requests you can use gitter.
