### ISSUE TITLE
adding css inject

### ISSUE THREAD

**Issue by Geraldf** [mgechev/angular2-seed#986]
I added a dependency in project.config.js to add bootstrap. 
it routine is adding the bootstrap.min.js correctly, but not the bootstrap.min.css

Any ideas?

`  constructor() {
    super();
    // this.APP_TITLE = 'Put name of your app here';
    let additional_deps: InjectableDependency[] = [
      {src: 'bootstrap/dist/js/bootstrap.min.js',inject:'libs'},
      {src: 'bootstrap/dist/css/bootstrap.min.css',inject:'css'},
    ];`

**Comment by mgechev** [comment]
For support requests you can use gitter.
