### ISSUE TITLE
Loading manual_typins are not working

### ISSUE THREAD

**Issue by bozhidarc** [mgechev/angular2-seed#987]
I create a typing for a jQuery plugin and I put it into `tools/manual_typings/project/jquery-ripple.d.ts`.
The first problem is that I can not find information how or where to add it so vscode can give me suggestions when typing.
I supposed that it has to be in `src/typings.d.ts` or in `typings/index.ts`. I put it into the first place.
Even included like that I still receive the following error "ORIGINAL EXCEPTION: TypeError: jQuery(...).ripple is not a function"

The jQuery plugin: https://github.com/adamsea/jquery-ripple

Here is some code.

**Importing jQuery:**
`import * as jQuery from 'jquery';`

**Calling the plugin:**
`jQuery(this.buttonEl.nativeElement).ripple();`

**The type definition:**
```
interface JQRippleOptions {
    /** The ripple effect color. */
    color?: string;
}

interface JQuery {
    ripple(options?: JQRippleOptions): JQuery;
}
```

**Comment by mgechev** [comment]
This doesn't seem like an issue related to the seed. For support requests, please move the discussion to the gitter channel of the project.
