### ISSUE TITLE
CanActivate

### ISSUE THREAD

**Issue by simoazzo** [mgechev/angular2-seed#988]
Hi Guys,

I am using this project but cannot figure it out from where I get the CanActivate Component Decorative?

Any help.

**Comment by TheDonDope** [comment]
Hi @simoazzo, the `CanActivate` decorator was removed in the `@angular/router` package in the `2.0.0-rc.1` version. Currently the router topic is under heavy construction. For further info have a look here: http://angularjs.blogspot.de/2016/06/improvements-coming-for-routing-in.html http://victorsavkin.com/post/145672529346/angular-router

**Comment by simoazzo** [comment]
Hi @TheDonDope ,

Thank you for you reply.

Currently, are there any alternative for CanActivate, for cases where you have protected Content?

Cheers.

**Comment by TheDonDope** [comment]
Hi @simoazzo, the newest angular router uses a concept of guards (as seen in ngrx router), but i haven't found too much information about it.

See here for some directions: http://victorsavkin.com/post/145672529346/angular-router#comment-2723379489

Quote from the article of above post (http://victorsavkin.com/post/145672529346/angular-router): 
> We haven’t touched on the following important topics: navigation guards, monitoring, debugging, error handling, and lazy loading. All of these topics will be covered in future blog posts.
