### ISSUE TITLE
How best to use my project with continuous integration from angular2-seed

### ISSUE THREAD

**Issue by harishrohokale** [mgechev/angular2-seed#989]
As like angular2-seed-advanced, Can I use this repo in my project and do continuous merge from angular2-seed.

I will just make changes in SRC directory for my app and rest will be the same.
Also If i want to add any new library in package.json, how would i manage that?

**Comment by Rademanc** [comment]
Yeah I also have this problem. 
A fork would probably be best.

**Comment by TheDonDope** [comment]
https://github.com/NathanWalker/angular2-seed-advanced#how-best-to-use-for-your-project https://help.github.com/articles/configuring-a-remote-for-a-fork/
