### ISSUE TITLE
Expanding "spec" testing is limited

### ISSUE THREAD

**Issue by butterfieldcons** [mgechev/angular2-seed#99]
Looked at this for a while, I'm hoping its just something simple that I'm missing.  With a basic git clone of the current project how come I cannot......

import {Pipeline} from 'angular2/src/router/pipeline';

into, let's say, about_spec.ts?

app\components\about\about_spec.ts(19,24): error TS2307: Cannot find module 'angular2/src/router/pipeline'.

Scratching my head a little bit since I had this working with a previous version (.36) (again base clone will produce error message)

Thanks All!!

**Comment by ludohenin** [comment]
@butterfieldcons This is just a TypeScript compiler issue. Adding the following declaration to `app/typings/ng2_test.d.ts` should fix it.
```typescript
declare module "angular2/src/router/pipeline" {
  export = ng;
}
```
or simply
`import {Pipeline} from 'angular2/router';`

**Comment by butterfieldcons** [comment]
Thanks,  Sometimes when a lot of pieces move (I upgraded) you are not certain why something breaks.  Things seemingly look the same, but.......   I also had an issue with a corrupt file in npm-cache which was not helping (i.e. npm install).  Thanks again.
