### ISSUE TITLE
Issue for accessing child router by using navigate for RC1

### ISSUE THREAD

**Issue by harishrohokale** [mgechev/angular2-seed#992]
Can someone please help me on how to navigate to child router from login page?

It was working on beta but after migrating to RC1 it fails.

I could see in latest angular2-seed sub components are removed form About.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
