### ISSUE TITLE
Build Ko under windows but ok on linux with exactly the same config and script

### ISSUE THREAD

**Issue by jcamus** [mgechev/angular2-seed#994]
Running the latest angular2-seed for a given project
command typed is : _npm run build.prod_
under linux (ubuntu) : **build is ok, no problem.**

under windows 7; error in task : build.bundles.app with following stack trace : 

_[09:25:21] 'build.bundles.app' errored after 2.93 s
[09:25:21] Error on fetch for dist\tmp\app\main.js at file:///c:/oldGen/TransfolioWeb/client/node_modules/dist\tmp\app\main.js
        Error: ENOENT: no such file or directory, open 'c:\oldGen\TransfolioWeb\client\node_modules\dist\tmp\app\main.js'
    at Error (native)
[09:25:21] 'build.prod' errored after 38 s
[09:25:21] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    build.bundles.app callback_

Path is wrong : here is the SYSTEM_BUILDER_CONFIG used by default in the build :
_{ defaultJSExtensions: true,
  packageConfigPaths:
   [ 'c:\\oldGen\\TransfolioWeb\\client\\node_modules\\*\\package.json',
     'c:\\oldGen\\TransfolioWeb\\client\\node_modules\\@angular\\*\\package.json' ],
  paths: { 'dist/tmp/*': 'dist/tmp/*', '*': 'node_modules/*' },
  packages:
   { '@angular/core': { main: 'index.js', defaultExtension: 'js' },
     '@angular/compiler': { main: 'index.js', defaultExtension: 'js' },
     '@angular/common': { main: 'index.js', defaultExtension: 'js' },
     '@angular/http': { main: 'index.js', defaultExtension: 'js' },
     '@angular/platform-browser': { main: 'index.js', defaultExtension: 'js' },
     '@angular/platform-browser-dynamic': { main: 'index.js', defaultExtension: 'js' },
     '@angular/router-deprecated': { main: 'index.js', defaultExtension: 'js' },
     '@angular/router': { main: 'index.js', defaultExtension: 'js' },
     rxjs: { defaultExtension: 'js' } } }_

After a quite long time to understand to set up this correctly I finally typed this into project.config.ts :

_this.SYSTEM_BUILDER_CONFIG = {
		defaultJSExtensions: true,
		packageConfigPaths: [join(this.PROJECT_ROOT, 'node_modules', '*', 'package.json')],
		paths : {
			[`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`,	      
			'@*' : 'node_modules/@*',
			'components/*' : `${this.TMP_DIR}/app/components/*`,
			'ng2-translate*' : 'node_modules/ng2-translate/*',
			'rxjs*' : 'node_modules/rxjs/*'
		},
		packages: { 
			'@angular/core': { main: 'index.js', defaultExtension: 'js' },
			'@angular/compiler': { main: 'index.js', defaultExtension: 'js' },
			'@angular/common': { main: 'index.js', defaultExtension: 'js' },
			'@angular/http': { main: 'index.js', defaultExtension: 'js' },
			'@angular/platform-browser': { main: 'index.js', defaultExtension: 'js' },
			'@angular/platform-browser-dynamic': { main: 'index.js', defaultExtension: 'js' },
			'@angular/router-deprecated': { main: 'index.js', defaultExtension: 'js' },
			'@angular/router': { main: 'index.js', defaultExtension: 'js' },
			rxjs: { defaultExtension: 'js' } 
			} 
		}_ 

It seems build under windows has a bug with the paths and not interpreting correctly this :
paths: { 'dist/tmp/*': 'dist/tmp/*', '*': 'node_modules/*' },

I know Windows is not used often has a build platform for js, but I DO NEED it to build my project. So Linux is not the solution for my project.
Did you test angular2-seed under windows ? How to explain this problem (ok under linux, ko under windows with exactly the same script??)

**Comment by zwolej** [comment]
Same issue with me. Fix here:
https://github.com/mgechev/angular2-seed/issues/993

**Comment by jcamus** [comment]
Ok it works !! (almost a miracle!).
So my systemjs-builder version was 0.15.20, fixing that to 0.15.14 solves the problem.

in package.json I changed : 
 "systemjs-builder": "^0.15.14",
with 
 "systemjs-builder": "0.15.14",

If someone can explain why Windows not working with this upper version ?

Many thanks.

**Comment by mgechev** [comment]
Master is already using this specific version of the systemjs builder https://github.com/mgechev/angular2-seed/blob/master/package.json#L103.
