### ISSUE TITLE
sass support not working with test

### ISSUE THREAD

**Issue by dodoshanti** [mgechev/angular2-seed#995]
Hi
We've enabled sass support as per the wiki (PR #952 ) in our build and can't get our compiled component test to work. 
The build dumps the css in dist/dev  but the gulp-inline-ng2-template plugin looks for the css files in APP_SRC. We've tried chainging the base param of the plugin to APP_DEST but it didn't work.

build.js.test task fails with the error below:

`[10:25:34] Plumber found unhandled error:                                                      
 Error in plugin 'gulp-inline-ng2-template'                                                    
Message:                                                                                       
    ENOENT: no such file or directory, open 'D:\repos\angular2-seed-latest\src\client\app\share
d\components\modal\modal.css'                                                                  
Details:                                                                                       
    errno: -4058                                                                               
    code: ENOENT                                                                               
    syscall: open                                                                              
    path: D:\repos\angular2-seed-latest\src\client\app\shared\components\modal\modal.css       
    fileName: D:\repos\angular2-seed-latest\src\client\app\shared\components\modal\modal.compon
ent.ts`

**Comment by mgechev** [comment]
Most likely you'd need to set the `styleProcessor` property of https://www.npmjs.com/package/gulp-inline-ng2-template.

**Comment by zwolej** [comment]
Something changed about that ? It fails for me also. Should I write for myself some styleProcessor or there are built in components ?

**Comment by mgechev** [comment]
`styleProcessor` is a callback which transpiles your Sass files to CSS. For further information take a look at `gulp-inline-ng2-template` plugin.
