### ISSUE TITLE
Karma autowatch is not working

### ISSUE THREAD

**Issue by dfaglioni** [mgechev/angular2-seed#996]
After start npm run build.test.watch and npm run karma.start, all  works fine for the first time and it show 10 tests on summary. But when I change something on the test, the karma console show me 0 tests on summary.

**Steps to reproduce and a minimal demo of the problem**
 npm run build.test.watch / npm run karma.start
Change something on test

**Current behavior**
  Show me 0 tests
  
**Expected/desired behavior**
Should show some tests

node v6.2.0
npm 3.8.9
windows 7 Professional

**Comment by netstart** [comment]
I have the same problem, but 

npm 3.9.5
node 5.9.1
windows 10

**Comment by JPtenBerge** [comment]
Same thing on Node.js 6.0.0, npm 3.8.6 and Windows 10.

**Comment by mgechev** [comment]
You need to run:

```bash
npm start
```

and in another window:

```bash
npm run karma.start
```

`karma.start` works with transpiled files only.

**Comment by rbuskov** [comment]
Same here. Seems that Karma detects when files are deleted in the `dist/dev` folder, but not when they are created again. Removing `clean.dev` from the `build.test` target in the gulp file fixes this issue. 

Obviously, you'll then need to clean the `dist/dev` folder manually and restart the watcher whenever you remove or rename files from your project. I added `clean.dev` to the `build.test.watch`  target so I can just break and restart quickly in the prompt.
