### ISSUE TITLE
build.assets.prod copies files/folders outside of the assets folder

### ISSUE THREAD

**Issue by mpetkov** [mgechev/angular2-seed#998]
The **build.assets.prod** task currently copies all folders with content in the APP_SRC location instead of just the ones in the ASSETS_SRC.  Maybe this was done intentionally, but that is not what the name of the task and what the comment in the code describe:

```javascript
/**
 * Executes the build process, copying the assets located in `src/client/assets` over to the appropiate
 * `dist/prod/assets` directory.
 */
export = () => {
  return gulp.src([
    join(APP_SRC, '**'),
    '!' + join(APP_SRC, '**', '*.ts'),
    '!' + join(APP_SRC, '**', '*.css'),
    '!' + join(APP_SRC, '**', '*.html'),
    '!' + join(APP_SRC, '**', '*.scss'),
    '!' + join(ASSETS_SRC, '**', '*.js')
  ].concat(TEMP_FILES.map((p) => { return '!' + p; })))
    .pipe(onlyDirs(es))
    .pipe(gulp.dest(APP_DEST));
};
```

As you can see, the comment clearly says thhat it copies assets located in **src/client/assets** but the code is doing **join(APP_SRC, '\*\*')** instead of **join(ASSETS_SRC, '\*\*'),** 

Could one of the following be done:
- Change build.assets.prod to truly only copy files inside assets.
- If for some reason the seed needs to remain the way it is, please update the comment section to reflect the true functionality and also rename build.assets.prod to something else.

**Comment by mgechev** [comment]
Thanks for the issue! The comment is fixed.
